### ISSUE TITLE
Move the consent question below the admin registration form

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#1000]
When creating a new registration in the admin, the consent checkbox appears above the form. Can we move that to below the registration form?
![‹ Events by Espresso — WordPress 2019-03-05 13-08-52(1).jpg](https://images.zenhubusercontent.com/58ac869e51aa2c3057750fb2/16c13b7e-8218-421d-a182-1e10b8ae1a60)

**Comment by joshfeck** [comment]
There was some related work done to the admin reg form and the consent question is now at the bottom of the form.
