### ISSUE TITLE
Unit Tests should make an assertion

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1007]
## or it gets really annoying

per @mnelson4:

> I'm doing most of my development with PHP7.1 and when I run the unit tests, PHPUnit gets upset if there are no assertions made during a test. This makes it hard to find legitimate failures. I'd like to add a simple `assertTrue(true);` to those tests just to remove those annoying notices. Theoretically this may only take 15 minutes
> 
> Actually just adding that assertion to `tearDown` will work too, but I think the warnings point out a legitimate issue: most tests should make an assertion, or explicitly `assertTrue(true)` and give an explanation why that's ok.

**Comment by nerrad** [comment]
You can also mark a test as incomplete:

```php
// Stop here and mark this test as incomplete.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
```

I think that would be preferable so that it's clear it is a test to be completed at some point.

**Comment by tn3rb** [comment]
@mnelson4 
can you plz list the specific tests here that you are referring to?

**Comment by mnelson4** [comment]
Sure, I believe they are...
* [ ] `EEM_Base_Test::test_model_table_exist`
* [ ] `EEH_Parse_Shortcodes_Test::test_invalid_attendee_obj_EE_Attendee_Shortcodes`
* [ ] `EEH_Template_Test::test`
* [ ] `EE_Model_Matching_Query_validation_Strategy_Test::test_valid` and `test_valid__treating_input_as_other_field`
* [ ] `EE_Plaintext_Validation_Strategy_Test::test_validate__pass`
* [ ] `EE_CHeckoutTest::test_add_reg_step`
* [ ] `EE_PMT_Paypal_Standard_Test::test_set_redirect_info__total_mismatch__itemized_lower`
