### ISSUE TITLE
Change the size of review title headings

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#1008]
The heading size of the review title headings, on the review tab (WP Admin > Event Espresso > About > Reviews) could be lowered a bit, from h2 to h3.

Here's an example:

Current h2 headings for the review titles:
![events by espresso wordpress 2019-03-08 06-32-44](https://user-images.githubusercontent.com/235315/54031661-9b57b280-416c-11e9-9d6e-77b5a5e0d477.jpg)

Headings changed to h3:
![events by espresso wordpress 2019-03-08 06-32-19](https://user-images.githubusercontent.com/235315/54031681-ae6a8280-416c-11e9-9f35-71a84c6c94f2.jpg)

**Comment by joshfeck** [comment]
Fixed as part of PR #1004 in BUG/target-blank-links branch.
