### ISSUE TITLE
Add "Filtered CSV Report" button next to "Filter" buttons located before the Registrations list table

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1016]
## Issue Overview

This would improve the user interface for preparing a filtered CSV report. Currently you select and apply all the filters, then you need to scroll down the page to find the "Filtered CSV Report" button located after the table. (which could be a lengthy scroll if page settings are more than 20 or so). The "Filtered CSV Report" button could be placed alongside the "Filter" and "Reset Filters" buttons.

**Comment by mnelson4** [comment]
Sounds like a good idea
