### ISSUE TITLE
Remove link to event's checkins when context is already viewing event's checkins

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1022]
Originally reported by @Pebblo in https://events.codebasehq.com/projects/event-espresso/tickets/9368

Note in the screenshot the outlined text:
https://monosnap.com/file/3iJIimoy5UKzdihZbKbY01riRsgwjw#

The outlined text is a hyperlink that goes to a list of checkins for that event. It's a helpful link if you navigate to the "all events" Event Check-In tab by clicking on the tab from the "All registrations from all events" page.

Where it's not helpful is when you're already viewing a page of checkins for the event. 

Could we either a) remove the column entirely when on that view or b) remove the link and leave the text?

**Comment by tn3rb** [comment]
should just remove the column from that view since it has no additional information to add and therefore no purpose at that point

**Comment by joshfeck** [comment]
resolved in #2579
