### ISSUE TITLE
Fix issues with EE3 to EE4 attendee data migrations

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1034]
While testing #881 I found some issues with EE3 to EE4 database migrations where EE3 attendee data went missing after migrating to EE4. The same issues happened regardless of whether I had master checked out or the branch for #881. It didn't matter which branch was activated while doing the migration, the same thing happened.

**To Reproduce**

In this case I set up one event, with two extra question groups, and set 1 custom question to each extra question group. I also set 1 custom question to the Personal Information group. Then I did 3 registrations for the event. Then I migrated to EE4.

**Expected behavior**

Expected each of the 3 attendees to have the correct information migrated

**Screenshots**

### _events_attendee table
<img width="365" alt="Screen Shot 2019-03-25 at 5 32 23 PM" src="https://user-images.githubusercontent.com/891156/54955540-00a8f300-4f24-11e9-94b3-88df1a46bdbb.png">

### _events_answer table
<img width="453" alt="Screen Shot 2019-03-25 at 5 33 36 PM" src="https://user-images.githubusercontent.com/891156/54955612-27672980-4f24-11e9-95ba-3557f8c73108.png">

### _esp_registration table
<img width="316" alt="Screen Shot 2019-03-25 at 5 34 46 PM" src="https://user-images.githubusercontent.com/891156/54955660-4cf43300-4f24-11e9-8c66-0a7bdce33a08.png">

### _esp_attendee_meta table
<img width="774" alt="Screen Shot 2019-03-25 at 5 35 11 PM" src="https://user-images.githubusercontent.com/891156/54955712-701ee280-4f24-11e9-8d42-da2023ad7bea.png">

**note in the above, no address information**

### _esp_answer table
<img width="372" alt="Screen Shot 2019-03-25 at 5 36 43 PM" src="https://user-images.githubusercontent.com/891156/54955758-9a70a000-4f24-11e9-8923-047e3789fc96.png">

**note in the above, the answers are related to REG ID 3 only, and the answer values are actually for REG ID 1**

**Environment:**
 - Version of Event Espresso:  4.9.80.rc (current master)
 - Version of WordPress: 5.1.1
 - Browser Firefox
 - PHP Version 7.3

**Comment by mnelson4** [comment]
Ugh ya that's pretty borked.
When I ran the migration from EE3 with the above setup, I got a bunch of warnings after the first migration, including

```
Could not find new registrations for old attendee 2 when creating answer {"id":"1","registration_id":"1-5ca3aabe99425","attendee_id":"2","question_id":"1","answer":"fname2","is_primary":"1","lname":"lname2","fname":"fname2","address":"","address2":"","city":"","state":"","zip":"","country_id":"","organization_name":"","vat_number":null,"email":"email2@email.ema","phone":"","date":"2019-04-02 18:32:30","price_option":"General Admission","orig_price":"0.00","final_price":"0.00","quantity":"1","total_cost":"0.00","amount_pd":"0.00","coupon_code":"","payment":"","payment_status":"Completed","txn_type":"","txn_id":null,"payment_date":"April 2, 2019","event_id":"1","event_time":"08:00","end_time":"17:00","start_date":"2019-05-02","end_date":"2019-05-02","attendee_session":"hr8iq0lmpdr8mgpqepd05ocsr1-5ca3aaa8b9ab23.82572404","transaction_details":null,"pre_approve":"1","checked_in":"0","checked_in_quantity":"0","hashSalt":null,"event_code":"1-5ca3aa36049f8","event_name":"e1","event_desc":"","display_desc":"Y","display_reg_form":"Y","event_identifier":"e1-1-5ca3aa36049f8","registration_start":"2019-04-02","registration_end":"2019-05-01","registration_startT":"00:01","registration_endT":"23:59","visible_on":null,"venue_title":"","venue_url":"","venue_image":"","venue_phone":"","virtual_url":"","virtual_phone":"","reg_limit":"999999","allow_multiple":"Y","additional_limit":"5","send_mail":"N","is_active":"Y","event_status":"A","conf_mail":"","use_coupon_code":"N","use_groupon_code":"N","category_id":null,"coupon_id":null,"tax_percentage":null,"tax_mode":null,"member_only":"N","post_id":null,"post_type":null,"country":"","externalURL":"","early_disc":"","early_disc_date":"","early_disc_percentage":"Y","item_groups":null,"event_type":null,"allow_overflow":"N","overflow_event_id":"0","recurrence_id":"0","email_id":"0","alt_email":"","wp_user":"1","require_pre_approval":"0","timezone_string":"","likes":null,"ticket_id":"0","submitted":"2019-04-02 18:30:14"}
```

* [ ] The additional registration had "REG_count"=1 (it should have been two, as it was a group of 2)
* [ ] A ton of registration were erroneously grouped onto the same trasaction (actually, the only one that wasn't on the same transaction was the additional registration, which SHOULD have. It's like there's a conditional that's doing the opposite of what it should.)
* [ ] There is only one answer for each question (instead of an answer for each registration for each question)
