### ISSUE TITLE
Implement semantic improvements that are available with WordPress 5.2 for admin tabs.

### ISSUE THREAD

**Issue by nerrad** [eventespresso/event-espresso-core#1048]
## Issue Overview
WordPress 5.2 introduces some [semantic and accessibility improvements](https://make.wordpress.org/core/2019/04/02/admin-tabs-semantic-improvements-in-5-2/) to admin tabs in the WordPress admin.  We should review EE core and observe any places we can add the same improvements.   Some places I think might be relevant are:

- our about page
- tabs on all our admin pages.

This would be a good issue to target for updates whenever we raise the minimum requirements of WP to 5.2 for EE core.

**Comment by joshfeck** [comment]
After reviewing this and thinking a bit about it, I'm realizing we may not need to raise the minimum requirements of WP to 5.2 for EE core to do this, barring any unforeseen CSS conflicts that could potentially happen if a site was on a version of WP prior to 5.2. We may _need_ to address this **before** 5.2 ships if CSS conflicts do occur.

I'll give this a try in a PR and see how the tabs look on both a WP 5.2 site and on a pre-5.2 site.

**Comment by joshfeck** [comment]
> Please note: if your plugin or theme uses items that actually toggle the visibility of in-page content instead of linking to another page, then they are not navigation items. You should not use ARIA tabs nor `<nav>` element in that case.

**Comment by nerrad** [comment]
> Please note: if your plugin or theme uses items that actually toggle the visibility of in-page content instead of linking to another page, then they are not navigation items. You should not use ARIA tabs nor <nav> element in that case.

In some cases this is true (messages settings, payment methods).  However, most of our admin pages have tabs that actually link to a different url so they qualify imo.

**Comment by garthkoyle** [comment]
Payment methods don't seem to have different urls but you can access their individual PM settings page via a unique url and I use them to link people to certain pages within their own site whether it be EE or ES:

`/wp-admin/admin.php?page=espresso_payment_settings&payment_method=stripe_onsite` or wp-`/admin/admin.php?page=espresso_payment_settings&action=default&payment_method=paypal_smart_buttons`

etc.

I'm not 100% sure my comment contributes to this discussion but I hope it does.

**Comment by nerrad** [comment]
> Payment methods don't seem to have different urls but you can access their individual PM settings page via a unique url and I use them to link people to certain pages within their own site whether it be EE or ES.

True, but once you've loaded the payment method settings screen, the links there just hide/show content already on the page (and don't change the `window.href`)... so for the purpose of this clarification comment and accessibility, I don't think they'd be navs.
