### ISSUE TITLE
Convert all generic JSON objects into model entities and wire up CRUD functionality for the Event Dates and Available Tickets Metaboxes

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1055]
Mostly done, but there are a few items left to do:

- [x] In some places changes don’t seem to “stick” whereas other places they do. Sometimes it is even the exact same code that is running, but changes will get saved properly one time but not another despite there being no error messages. This could be due to an issue in the models

- [ ] Some screens load really slow due to the number of queries that get triggered in the background. This may require rewriting the queries to be more performant, or possibly changing how the models are used, or loading data in the background before it is even requested,

**Comment by tn3rb** [comment]
essentially done, and passed off for review, but lacking unit tests and documentation

**Comment by tn3rb** [comment]
going to close this issue since the EDTR has been wired up to the models for a while now, and that second point regarding speeding up the models is going to require a more incremental refactoring to fix, which is already in progress via other PRs such as: #1641
