### ISSUE TITLE
Create TicketPriceCalculator form modal

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1056]
- [x] Build modal for controlling a ticket's price modifiers.
- [x] Add the ability to “reverse engineer” the ticket base price from the ticket total

- [ ]Todo: Still a bit glitchy sometimes when you add a new modifier

**Comment by tn3rb** [comment]
done and passed off for review, although no unit tests or documentation yet

**Comment by tn3rb** [comment]
![ticket price calculator](https://user-images.githubusercontent.com/1751030/57401680-06346280-718b-11e9-8bf8-1844095396ea.png)

**Comment by tn3rb** [comment]
this is done and refactorings that Darren did have fixed the "glitchiness"
