### ISSUE TITLE
WP 5.2+: Refactor any dependencies on wp.editor that should be changed to wp.block-editor

### ISSUE THREAD

**Issue by nerrad** [eventespresso/event-espresso-core#1059]
As a part of the WordPress 5.2 release, there was some refactoring of editor related packages so that the block-editor is independent from the post-editor context.  You can [read more about this here](https://make.wordpress.org/core/2019/04/09/the-block-editor-javascript-module-in-5-2/).

Since back-compat is preserved via proxies, there's no urgency to updating any of our components or dependencies on wp-editor but to support future iterations of the editor being used throughout WordPress, it would be good for us to review where we have dependencies on `wp.editor`and the proxies there that should be switched to `wp.blockEditor` instead.

**Comment by joshfeck** [comment]
@nerrad will this require changing the minimum required version of WP to be 5.2?

**Comment by nerrad** [comment]
yessir.  if we WANT to preserve back-compat, we _could_ but it would require quite a bunch of additional code to account for both `wp.editor` and `wp.block-editor`.

We could time the changes here to happen after any other changes requiring a version bump if you wanted.  A bit trickier to manage, but doable.

**Comment by joshfeck** [comment]
This could end up being the change that requires the version bump.

**Comment by tn3rb** [comment]
According to the WP post about the the block editor changes, things are backwards compatible and they may not even begin showing deprecation notices until version 5.4, so it seems somewhat premature to force this change on our users any time soon.

**Comment by nerrad** [comment]
> Since back-compat is preserved via proxies, there's no urgency to updating any of our components or dependencies on wp-editor but to support future iterations of the editor being used throughout WordPress, it would be good for us to review where we have dependencies on wp.editorand the proxies there that should be switched to wp.blockEditor instead.

@tn3rb I highlighted that in my original post here.   However, this was still in my "next" queue so I assumed Josh decided he was fine with doing this now.

**Comment by nerrad** [comment]
Also worth noting that if we want the EventAttendees block to be available with the new widget ui WP is converting over to react/GB then we need to do what I did in the attached pull.  Of course we can delay actual release of the work until its needed but just worth mentioning.

**Comment by tn3rb** [comment]
no longer applicable
