### ISSUE TITLE
REST API _links are erroneously for join-models when querying across a relation

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/event-espresso-core#1062]
## Issue Overview

Eg, `mysite.com/wp-json/ee/v4.8.36/datetimes/1/tickets` returns entities with `_links` that appear to actually be for `datetime_tickets` entities, not `tickets`.
However `mysite.com/wp-json/ee/v4.8.36/tickets`'s `_links` are fine.

This was causing Brent and Darren some grief in their Javascript code that consumes the REST API.

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Environment Data:

Version of EE: 4.9.80

Version of WordPress:any

PHP Version:  any

Browser used:  any

## Expected Behaviour

If the results are `tickets`, the `_links` should only be for them.

## Current Behaviour

When querying for related data across a has-and-belongs-to-many-relation, `_links` is for the join model/entitiy/table.

**Comment by joshfeck** [comment]
#1064 was merged
