### ISSUE TITLE
Review usage of PayPal DoCapture API response parameters

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1079]
Some parameters will be retired soon so the bundled PayPal gateways that use the NVP/SOAP API should probably be checked to see if anything needs to be updated.

https://www.paypal-status.com/history/eventdetails/8741/

**Comment by mnelson4** [comment]
Thanks for bringing this up.

We're not using the response parameters 
• TAXAMT
• TRANSACTIONTYPE
• RECEIPTID
so that's good.
We are, however, sending "TAXAMT" in requests, but there is no mention of that being a problem (and not sending it would be a problem for now).
So we should be good.
