### ISSUE TITLE
Fix issue where additional attendee questions column headings are omitted in CSV report

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1087]
**Describe the bug**

Questions that belong to question groups that are asked of Additional Attendees **only** do not have column headings in the CSV report. The answers are included in the report, so the report ends up with mismatched columns when this happens.

**Screenshots**

![Screen Shot 2019-04-15 at 3 54 08 PM](https://user-images.githubusercontent.com/891156/56161231-07f97480-5f97-11e9-957b-1185e23c5e1a.png)

**To Reproduce**
1. Add a question in Event Espresso > Reg Form > Questions
2. Add a question group in Event Espresso > Reg Form > Question Groups
3. Add an event and set the question group so it's used in the forms for additional attendees **only**
4. Go to the event page, select at least 2 tickets, then complete the reg forms
5. Go to Event Espresso > Registrations for the event and download the CSV report
You'll note that there's no column heading for the additional attendee-only question 

**Expected behavior**

Additional Attendee-only question should also have a column heading in the CSV report

**Environment:**
 EE4 current master

**Additional context**

**Comment by mnelson4** [comment]
Oh cool.

**Comment by mnelson4** [comment]
Hmmm I'm initially having trouble reproducing this issue, see https://drive.google.com/file/d/1i-zrcct-h1f7GtpitNsUcaYJ3BOj4wtK/view Can you see anything I'm doing wrong in order to reproduce @joshfeck?

One way I could see this issue being reproduced is by having a registration marked as INCOMPLETE, and that registrant being the only one asked a certain question.

**Comment by mnelson4** [comment]
I also tried defining `EE_USE_OLD_CSV_REPORT_CLASS` to true to see if that was the difference, but nope. I am not reproducing, and looking at the code, I don't see how this would happen (it fetches all the questions for any registrations that would appear in the report, including those who are 
@joshfeck are you still able to reproduce this issue? If so, could you maybe send me a DB dump, or set it up on a publicly-accessible site so I can play with it?

**Comment by joshfeck** [comment]
Looks like this is related to a migration from EE3 issue, the registrations CSV report were from registrations made with EE3 that were migrated to EE4. I'll see if the latest migration fixes happen to resolve this.

**Comment by joshfeck** [comment]
Updated steps:

1. Using EE3, add a question in Event Espresso > Questions
2. Add a question group in Event Espresso > Question Groups, and assign the question to that group
3. Add an event, set Allow group registrations to "Yes", set "Additional Attendee Registration info?" to "Full registration information", and set the question group so it's used in the forms for additional attendees **only**
4. Go to the event page, register for at least two attendees and complete the registrations
5. Deactivate EE3, activated EE4. Migrate data to EE4
6. Go to Event Espresso > Registrations for the event and download the CSV report
You'll note that there's no column heading for the additional attendee-only question

**Comment by mnelson4** [comment]
aha, I'm reproducing now. It seems to have something to do with how migrated custom questions has QST_system=null, whereas ones created in EE4 has QST_system=''...

**Comment by joshfeck** [comment]
fixed in #1182

**Comment by garthkoyle** [comment]
See also: https://github.com/eventespresso/event-espresso-core/pull/3843
