### ISSUE TITLE
Question: Extending core via hooks

### ISSUE THREAD

**Issue by thread-ncraig** [eventespresso/event-espresso-core#110]
Is there any documentation on how hooks work in relation to EE_Admin_Hook.php and the Admin Page object? Im trying to extend the core with a new add-on but the hook class only fires for the Event Admin page. I need it to fire on multiple admin pages to add the pieces of the add-on to each page. (Events, registrations, venues).

**Comment by nerrad** [comment]
hey there, documentation is sparse for that currently.  What is it you are wanting to do and I can point you in the right direction (hopefully).

**Comment by thread-ncraig** [comment]
The add-on I’m writing needs to interact with the Events Admin page, the Registrations Admin page and the Venues admin page. In my add-on called ‘Services’, when I create a espresso_events_Services_Hooks.class.php it is only catches on the Events Admin page. If I try to add a second hook set, espresso_registrations_Services_Hooks.class.php it interacts with the Registrations Admin Page but the first hook set (events) no longer fires. If there’s a better way to add metaboxes to all of these pages with post catching, please point me in that direction.


Regards,

Nicholas Craig
Director of Information Technology

**Comment by nerrad** [comment]
Sounds like you were on the right path Nicholas.  It also sounds like there may be a bug with the hooks system we have but without seeing the code that's hard to know.

As an alternative, you can register your new meta-boxes directly using the core wp method for adding metaboxes.  Here's the value's you'll use for the `$screen` argument

- Event Editor: `espresso_events`
- Registration Details: `event-espresso_page_espresso_registrations`
- Attendee (Contact) Editor: `espresso_attendees`
- Venue Editor: `espresso_venues`

For capturing the post data on save/update:

Events, Attendees (contacts) and Venues are all WordPress custom post types, so you can hook into the `save_post` WordPress hook and do your processing there.

For the Registration Details page, there is no update action on that route, so uncertain what post data you are looking to capture there.  If you are adding something that does an update on that route, you'll likely have to create your own listener.

Does this help?

**Comment by thread-ncraig** [comment]
Yes, that does help,  I will go that route to get the project completed, but I can send you a copy of my current beta code if you would like to see the hook system issue in action.


Regards,

Nicholas Craig
Director of Information Technology

**Comment by nerrad** [comment]
Yah that'd be great if you could Nicholas, I'd like to determine what's going on with the hook system because if its working the way you described, its not very useful :)

**Comment by nerrad** [comment]
oh forgot to mention, you can email a copy of your beta to darren at eventespresso.com

**Comment by nerrad** [comment]
I'm just going to close this issue for now, feel free to reopen if there's still issues related to the original question :)

**Comment by thread-ncraig** [comment]
thanks


Regards,

Nicholas Craig
Director of Information Technology

**Comment by thread-ncraig** [comment]
Hey Darren,

Quick question, where would the best place be to add the metaboxes as the hook systems not working and I don’t want to add it to the main plugin instantiation file.
I guess the next best place would be the register_addon function under admin_callback?


Regards,

Nicholas Craig
Director of Information Technology

**Comment by nerrad** [comment]
The best place is to register them on a callback for the `add_meta_boxes` hook.  That will work for all the cpt routes (events, venues, attendees).  However, it won't work on the non cpt routes (registrations, transactions) unless you use the current master branch of EE core (I just pushed a fix today).  

If you aren't using the current master, the next best place to register the metaboxes for registrations and transactions is via a callback on the `admin_head` hook.

**Comment by thread-ncraig** [comment]
That makes sense, I just wasn’t sure if there was a better place to add the add_meta_boxes hook than in the additional_admin_hooks as that fires as part of the init.

For the current version im on, the hook class works for the registrations, so im handling that there, and the add/update for events and venues in the main EE_Services.class under additional_admin_hooks


Regards,

Nicholas Craig
Director of Information Technology
