### ISSUE TITLE
Fix advanced datetime editor styling issue when `WP_DEBUG` is false

### ISSUE THREAD

**Issue by nerrad** [eventespresso/event-espresso-core#1127]
If WP_DEBUG is false, the advanced datetime editor has styling that appears incorrectly:

![incorrect styling screenshot](https://www.evernote.com/l/AAPf-OUHM6VDq69207bw3xtR6NjRcPduzl0B/image.png)

The cause can be traced to this code:

https://github.com/eventespresso/event-espresso-core/blob/a8596820fce9da573fd2e4ccd6711120dc5f6017/caffeinated/admin/new/pricing/templates/event_tickets_datetime_attached_tickets_row.template.php#L2-L6

I'm not sure why that code exists but it appears if the conditional is removed and the colspan is always 7 it's okay.

**Comment by nerrad** [comment]
I wonder if as a part of fixing this a review is conducted to make sure there are no other similar usages of `WP_DEBUG` in the codebase?

**Comment by joshfeck** [comment]
I agree a review would be good to make sure there are no others as well.
