### ISSUE TITLE
Wrong jQuery selector in the function show_admin_page_ajax_msg

### ISSUE THREAD

**Issue by nvphuc1989** [eventespresso/event-espresso-core#113]
Please review the code at https://github.com/eventespresso/event-espresso-core/blob/master/core/templates/global_assets/scripts/espresso_core.js#L149
The declaration of a variable:
> var existing_message = $('#message');

It should be:

> var existing_message = '#message';

Because of the usages of the variable:
> $(existing_message).stop().hide();
> $(existing_message).length

Another way to fix is remove the jQuery selector in the usages of the variable.

**Comment by tn3rb** [comment]
There are some changes to that function being tested at the moment that also correct this issue.
Thanks for pointing this out though. The changes should hopefully be merged into master soon.

**Comment by tn3rb** [comment]
the changes I spoke of have been merged into master and will be part of the next release, so I'm going to close this issue as it is now invalid.
