### ISSUE TITLE
Introduce orphan protection in the models.

### ISSUE THREAD

**Issue by nerrad** [eventespresso/event-espresso-core#1135]
In #1134 there was an issue raised in some work @tn3rb is doing for REM that resulted in further exposure of potential issues down the road with proper handling of orphaned entities.  The basic problem is that with the REST api (and the corresponding client side data store library implementing it), it's quite easy to persist "orphaned" entities to the db.  In this scenario "orphaned" means an entity that exists in the db but does not serve any useful purpose anywhere in the app ui/ux because there's no functionality that would retrieve it.  An example would be a persisted ticket that is not a default ticket, and has no relation to a datetime.

From the discussion on #1134, we seemed to settle on the resolution that any orphan protection should exist server side.  Of course there's still issues that would need worked out.  Among them:

- Would "orphan protection" be something defined on the models?
- How would the server communicate to the client a failed persist because of orphan protection?
- In the case of a ticket, wouldn't a ticket need to be persisted first before adding the relation to a datetime? In the case of a datetime, wouldn't the datetime need to be persisted before being related to the event?  This would make it tricky to accurately determine whether orphan protection should kick in or not.
- This has implications for server based client code using the models as well.

It's likely there are many other things needing worked out before anything could be implemented for this server side.  For now, I think we need to leave it up to client apps to implement their own protections/controls for protecting against orphaned data in the db (which Brent is implementing as a part of the datetime-ticket editor for the REM work).

For now this issue is mostly to drop in planning but I don't think it needs a high priority.  I would guess that @mnelson4  and myself would mostly be involved in working out the details for this.

**Comment by nerrad** [comment]
> In the case of a ticket, wouldn't a ticket need to be persisted first before adding the relation to a datetime? In the case of a datetime, wouldn't the datetime need to be persisted before being related to the event? This would make it tricky to accurately determine whether orphan protection should kick in or not.

This is the one point that has me wondering whether there should be _any_ orphan protection at all.  It seems like it might overcomplicate things when really its an implementation detail that should be left up to client/app code maybe?

**Comment by mnelson4** [comment]
> In the case of a ticket, wouldn't a ticket need to be persisted first before adding the relation to a datetime?

Correct. So it's tricky to force not having orphaned tickets.

By the DB schema, it's valid to have a ticket that's not associated to any datetimes. It's just our current logic that doesn't know what to do with it. IMO it's quite possible that logic could change (Eg, I could sign up for a ticket whose datetime and event aren't yet defined, but will be later).

> In the case of a datetime, wouldn't the datetime need to be persisted before being related to the event?

That's actually easier- because datetimes have a foreign key to their event, there's no join table between them. So you just create the event, then the datetime afterwards.

IMO we should first just try to enforce valid foreign keys (e.g., no datetimes for non-existent events). There's an entire epic for that. After that, we could explore if it's reasonable to try to not have orphaned tickets, message templates, etc.

**Comment by tn3rb** [comment]
> There's an entire epic for that. 

there is? can you plz link to it? I'm not seeing anything in ZenHub, was this something in Codebase maybe?

If there isn't an existing Epic, then maybe you can create one, or use this ticket, or create new tickets (your preference) for the following:

> IMO we should first just try to enforce valid foreign keys (e.g., no datetimes for non-existent events).

**Comment by mnelson4** [comment]
> There's an entire epic for that.

Sorry, the epic I'm referring to is https://github.com/eventespresso/event-espresso-core/issues/883.
