### ISSUE TITLE
Wrong times being displayed

### ISSUE THREAD

**Issue by ty2u** [eventespresso/event-espresso-core#114]
Hi there,

In EE4 (premium version) on a site we have WP set to America/Toronto for the timezone and in the php.ini it's set to that as well. However in EE now when setting the start and end times for events they show properly (where they did not in a past version of EE) while editing the event, but after saving on the overview list of all events and on the event page itself when viewing the event the times are wrong. It's like the timezones are being added to it twice.

So far a (somewhat untested) fix was to modify the get_i18n_datetime function and change this line:
https://github.com/eventespresso/event-espresso-core/blob/master/core/db_classes/EE_Base_Class.class.php#L1130

From:

		return date_i18n( $format, EEH_DTT_Helper::get_timestamp_with_offset( $this->get_raw( $field_name ), $this->_timezone ) );

To:

		return date_i18n( $format, EEH_DTT_Helper::get_timestamp_with_offset( $this->get_raw( $field_name ), "UTC" ) );

So now a few questions come to mind:
Do you think this would cause any issues elsewhere in EE?
Is this the correct fix?
Why do other people not have this issue, or do they?

Thanks!

**Comment by nerrad** [comment]
Hi there,

What's likely happening is you have another plugin (or possibly theme) that is using `date_default_timezone_set` to change the timezone which is a no-no in WordPress operating environment.

We see this from time to time with our users, here's an example http://eventespresso.com/topic/wrong-time-selector-and-posting/

**Comment by ty2u** [comment]
Thank you! There was a plugin called Weekly Class Schedule using that function.

**Comment by nerrad** [comment]
glad its' resolved!
