### ISSUE TITLE
Uncaught exception 'EventEspresso\core\exceptions\EntityNotFoundException' with message 'The requested entity with Transaction ID="999999" was not found.' in EE_Registration.class.php:1711

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/event-espresso-core#1142]
**Summary**
I noticed this in New Relic: https://rpm.newrelic.com/accounts/1628382/applications/62114495/traced_errors/81b22d3d-66ce-11e9-ab21-0242ac110007_0_7189

I'm not sure how to reproduce but I noticed the transaction ID of 99999. 

Could this be related to previewing a message in the messages editor?

**Steps to reproduce**
Not sure

Stack trace
…ntent/plugins/eea-wait-lists/domain/services/modules/
EED_Wait_Lists.module.php (605)
…eckout_url_query_args called at /wordpress-5.1.1/wp-includes/
class-wp-hook.php (286)
in WP_Hook::apply_filters called at /wordpress-5.1.1/wp-includes/plugin.php (208)
…-content/plugins/event-espresso-core/core/db_classes/
EE_Registration.class.php (960)
…e/core/libraries/shortcodes/
EE_Primary_Registration_Details_Shortcodes.lib.php (172)
…nt/plugins/event-espresso-core/core/libraries/shortcodes/
EE_Shortcodes.lib.php (184)
…ntent/plugins/event-espresso-core/core/helpers/
EEH_Parse_Shortcodes.helper.php (234)
…ntent/plugins/event-espresso-core/core/helpers/
EEH_Parse_Shortcodes.helper.php (74)
…gins/event-espresso-core/core/libraries/messages/
EE_Messages_Generator.lib.php (737)
…gins/event-espresso-core/core/libraries/messages/
EE_Messages_Generator.lib.php (633)
…gins/event-espresso-core/core/libraries/messages/
EE_Messages_Generator.lib.php (322)
…gins/event-espresso-core/core/libraries/messages/
EE_Messages_Generator.lib.php (162)
…gins/event-espresso-core/core/libraries/messages/
EE_Messages_Processor.lib.php (390)
…p-content/plugins/event-espresso-core/modules/messages/
EED_Messages.module.php (1010)
…/plugins/event-espresso-core/admin_pages/messages/
Messages_Admin_Page.core.php (2143)
…/plugins/event-espresso-core/admin_pages/messages/
Messages_Admin_Page.core.php (2998)
…/plugins/event-espresso-core/admin_pages/messages/
Messages_Admin_Page.core.php (2938)
…16036/wp-content/plugins/event-espresso-core/core/admin/
EE_Admin_Page.core.php (1010)
…16036/wp-content/plugins/event-espresso-core/core/admin/
EE_Admin_Page.core.php (771)
…16036/wp-content/plugins/event-espresso-core/core/admin/
EE_Admin_Page.core.php (594)
…16036/wp-content/plugins/event-espresso-core/core/admin/
EE_Admin_Page.core.php (215)
…/plugins/event-espresso-core/admin_pages/messages/
Messages_Admin_Page.core.php (82)
…sso-core/caffeinated/admin/extend/messages/
Extend_Messages_Admin_Page.core.php (23)
in Extend_Messages_Admin_Page::__construct called at ? (?)
…/wp-content/plugins/event-espresso-core/core/admin/
EE_Admin_Page_Init.core.php (391)
…/wp-content/plugins/event-espresso-core/core/admin/
EE_Admin_Page_Init.core.php (243)
…p-content/plugins/event-espresso-core/core/admin/
EE_Admin_Page_Loader.core.php (368)
…p-content/plugins/event-espresso-core/core/admin/
EE_Admin_Page_Loader.core.php (107)
in EE_Admin_Page_Loader::__construct called at ? (?)
… at /dom12345/wp-content/plugins/event-espresso-core/core/
EE_Registry.core.php (1262)
… at /dom12345/wp-content/plugins/event-espresso-core/core/
EE_Registry.core.php (902)
… at /dom12345/wp-content/plugins/event-espresso-core/core/
EE_Registry.core.php (389)
… /dom12345/wp-content/plugins/event-espresso-core/core/admin/
EE_Admin.core.php (210)
in EE_Admin::init called at /wordpress-5.1.1/wp-includes/class-wp-hook.php (286)
…P_Hook::apply_filters called at /wordpress-5.1.1/wp-includes/
class-wp-hook.php (310)
in WP_Hook::do_action called at /wordpress-5.1.1/wp-includes/plugin.php (465)
…ed at /dom12345/wp-content/plugins/event-espresso-core/core/
EE_System.core.php (1228)
…stem::initialize_last called at /wordpress-5.1.1/wp-includes/
class-wp-hook.php (286)
…P_Hook::apply_filters called at /wordpress-5.1.1/wp-includes/
class-wp-hook.php (310)
in WP_Hook::do_action called at /wordpress-5.1.1/wp-includes/plugin.php (465)
in do_action called at /wordpress-5.1.1/wp-settings.php (505)
in require_once called at /dom12345/wp-config.php (158)
in require_once called at /dom12345/wp-load.php (37)
in require_once called at /wordpress-5.1.1/wp-admin/admin.php (34)

**Reported or seen on**
https://rpm.newrelic.com/accounts/1628382/applications/62114495/traced_errors/81b22d3d-66ce-11e9-ab21-0242ac110007_0_7189

**Comment by joshfeck** [comment]
This was fixed in https://github.com/eventespresso/eea-wait-lists/pull/16
