### ISSUE TITLE
AffiliateWP EventEspresso Integration

### ISSUE THREAD

**Issue by tubiz** [eventespresso/event-espresso-core#115]
Am currently working on an EventEspresso integration for AffiliateWP.
Will appreciate if you can share some hooks to tie into the purchase and refund process.

affiliatewp/AffiliateWP#705

**Comment by tn3rb** [comment]
The checkout payment options step class can be found at:

```
\modules\single_page_checkout\reg_steps\payment_options\EE_SPCO_Reg_Step_Payment_Options.class.php
```

and all payment processing begins within:

```
core/EE_Payment_Processor.core.php
```

All of our hooks are prefixed with either:

 * "AHEE__" for Action Hook Event Espresso, or
 * "FHEE__"  for Filter Hook Event Espresso

so if you perform a non-whole word search for those prefixes, you will find all of our hooks.

Hope that helps

**Comment by garthkoyle** [comment]
The Event Espresso and Affiliate WP integration is now available: https://eventespresso.com/product/eea-affiliatewp/
