### ISSUE TITLE
Get event's custom field value on registration form

### ISSUE THREAD

**Issue by msyadav88** [eventespresso/event-espresso-core#117]
Hi friends, 

Please can you help me to find the actions hooks for the registration form. I am trying to do as below:
I have a custom field say “ask for create page” in an event.Admin will manually insert a value yes/no in it.I also have a question ” Do you want to create page?” for that event in question listing. Now in front, before displaying the registration form, i need to check that custom field’s value. If it is “yes” then only need to display the question” Do you want to create page?” Else no. 

Please anyone guide me on this issue.

**Comment by nerrad** [comment]
Hi there, one thing that may help is all EE action hooks are prefixed with `AHEE__`

One thing that I usually do when I'm looking for a place to add something in EE is I check the source of the page where I want to add the item.  I look for something that I can search with (it may be a css id or class) and then I search through EE code using that search string.  That usually helps me zero on on a template.  Then I search for the title of that template in the code and find out where its being loaded from.  That usually leads me to the calling class.   Then I search for all action hooks in that calling class (or trace the code path at that point) and that usually leads me pretty close to the hook I'm looking for.

I just wanted to give you those pointers in case someone from our team doesn't get back to your right away.  We're a small team and at the moment we're really kept busy fixing bugs and implementing new features for customers :)   We'll keep this thread open, someone from the team may know exactly the hook you might be looking for and could post in here.

**Comment by joshfeck** [comment]
I can also suggest installing these two plugins:

https://wordpress.org/plugins/debug-bar/
https://wordpress.org/plugins/debug-bar-actions-and-filters-addon/

Then, when you view any WordPress page, you can click on the debug bar, then click Actions, and it will show you a list of action hooks fired on that page request.
