### ISSUE TITLE
Persist entity changes to the database when the user hits submit

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1180]
When the user hits submit all the entities edited via the datetime/ticket editor need to run through the models and redux store to persist to the database.

**Comment by nerrad** [comment]
@tn3rb what branch should I work on for this and is that branch ready for me to do this?  Should I also be doing a general review of how the work in that branch is structured as well?

**Comment by nerrad** [comment]
So some thoughts on things we might need to consider as a part of this:

* [ ] There's probably third party code out there that hooks in on the existing save_post hooks etc for doing additional things on an event persist.  I think we may still be okay there if we still allow the normal post save to occur after persisting event data.
* [ ] The above may be tricky if we need the new post id AFTER it's persisted to save our own things.
* [ ] This will also need to include accounting for our own add-ons hooking in on save_post (i.e. people add-on).
* [ ] How the editor is enabled (when does it replace the old editor) affects `save_post` execution we have currently in EE core code (and add-ons hooking in).  In other words what conditions cause the legacy editor to remain and the new editor to show up?

**Comment by nerrad** [comment]
Added on hold label because:

- I don't know what branch this work gets done in.
- I don't know if things are even ready for me to do this work yet.

**Comment by joshfeck** [comment]
@tn3rb can you reply to @nerrad's questions above?

https://github.com/eventespresso/event-espresso-core/issues/1180#issuecomment-488803944

**Comment by tn3rb** [comment]
@nerrad 
the admin refactor branch is: `FET/editor-dates-tickets-refactor`
and has been passed to you for a WIP code review before writing unit tests and documentation
whether you want to work directly on that branch or another is up to you.
