### ISSUE TITLE
Fix issue with Attendee Block's Ticket select - post migration from EE3

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1193]
**Describe the bug**
After migrating a site from EE3 to EE4, the attendee block UI hangs when selecting a ticket. The error in the console is:
`Unhandled promise rejection TypeError: "Instance of Currency required"`
```
assertCurrency ee-valueObjects.276cc7a17fa0c373bfe1.dist.js:2894
    js ee-valueObjects.276cc7a17fa0c373bfe1.dist.js:3399
    setCurrency ee-valueObjects.276cc7a17fa0c373bfe1.dist.js:3001
    Money ee-valueObjects.276cc7a17fa0c373bfe1.dist.js:2986
    maybeConvertToValueObject ee-model.fc93494192c32c8ac7cc.dist.js:3014
    derivePreparedValueForField ee-model.fc93494192c32c8ac7cc.dist.js:3089
    setInitialEntityFieldsAndValues ee-model.fc93494192c32c8ac7cc.dist.js:2664
    createEntityGettersAndSetters ee-model.fc93494192c32c8ac7cc.dist.js:2462
    Lodash 4
    createEntityGettersAndSetters ee-model.fc93494192c32c8ac7cc.dist.js:2451
    BaseEntity ee-model.fc93494192c32c8ac7cc.dist.js:1732
    _class ee-model.fc93494192c32c8ac7cc.dist.js:1850
    fromExisting ee-model.fc93494192c32c8ac7cc.dist.js:1941
    fullEntities resolvers.js:64
    buildAndDispatchEntitiesFromResponse$ resolvers.js:63
    tryCatch runtime.js:45
    invoke runtime.js:271
    method runtime.js:97
    yieldValue Redux
    run wp-polyfill.js:4399
    notify wp-polyfill.js:4416
    flush wp-polyfill.js:1501
wp-polyfill.js:4434:11
```

**To Reproduce**

1. Start with an EE3 site, then activate EE4 and migrate the data
2. Go to add a page, add an attendee block
3. Configure attendee block: select an event, then datetime, then on the ticket select

If you go to the Event Espresso > General Settings page and click Save, then no more errors. So it seems a bug is exposed where there's a difference in the config that affects the Attendee block.

**Screenshots**

**Environment:**
 - Version of Event Espresso:  master
 - Version of WordPress: 5.2 RC2 -- Gutenberg plugin not activated
 - Browser: Firefox
 - PHP Version: 7.3

**Additional context**

**Comment by nerrad** [comment]
On the surface, this looks like a possible error with the currency config not getting setup during a migration from EE3 to EE4 because this error means that a `SiteCurrency` object was not exposed in javascript via `CoreAssetsManager`.

**Comment by nerrad** [comment]
Okay I have a some more findings.  First my environment setup:

1. I started with a fresh install of Wordpress.
2. I activated EE3 (no events added or anything), I saved the Settings page for EE3 (because I was prompted to finish setting things up).
3. I deactivated EE3 and activated EE4
4. I progressed through all the migration steps.
5. I created an initial event and saved it (nothing other than a description modification made)
6. I created a new post and attempted to add the EventAttendees block which produced the following errors:

```
ee-valueObjects.276cc7a17fa0c373bfe1.dist.js:24977 Warning: The Site Currency object could not be created because of this error: The signB4 property on the configuration object must be a boolean primitive.
printWarning @ ee-valueObjects.276cc7a17fa0c373bfe1.dist.js:24977
```

and 

```
assertions.js:108 Uncaught (in promise) InvalidTimezone: Invalid argument provided. The timezone string provided is not valid.
    at Module.assertTimezoneIsValid (http://ee.test/wp-content/plugins/event-espresso-core/assets/dist/ee-valueObjects.276cc7a17fa0c373bfe1.dist.js:483:11)
    at Function.assertTimezoneIsValid (http://ee.test/wp-content/plugins/event-espresso-core/assets/dist/ee-valueObjects.276cc7a17fa0c373bfe1.dist.js:1250:72)
    at new DateTime (http://ee.test/wp-content/plugins/event-espresso-core/assets/dist/ee-valueObjects.276cc7a17fa0c373bfe1.dist.js:655:16)
    at Function.fromISO (http://ee.test/wp-content/plugins/event-espresso-core/assets/dist/ee-valueObjects.276cc7a17fa0c373bfe1.dist.js:1437:14)
    at maybeConvertToValueObject (http://ee.test/wp-content/plugins/event-espresso-core/assets/dist/ee-model.fc93494192c32c8ac7cc.dist.js:3010:88)
    at derivePreparedValueForField (http://ee.test/wp-content/plugins/event-espresso-core/assets/dist/ee-model.fc93494192c32c8ac7cc.dist.js:3089:10)
    at setInitialEntityFieldsAndValues (http://ee.test/wp-content/plugins/event-espresso-core/assets/dist/ee-model.fc93494192c32c8ac7cc.dist.js:2664:133)
    at http://ee.test/wp-content/plugins/event-espresso-core/assets/dist/ee-model.fc93494192c32c8ac7cc.dist.js:2462:7
    at http://ee.test/wp-includes/js/dist/vendor/lodash.js?ver=4.17.11:4911:15
    at baseForOwn (http://ee.test/wp-includes/js/dist/vendor/lodash.js?ver=4.17.11:2996:24)
```

**Comment by nerrad** [comment]
I think the issue with `currency_config` is due to the `EE_DMS_4_1_0_org_optoins.dmsstage.php` saving the `sign_b4` as an integer rather than a boolean (which is what is expected for later versions of EE4).

I suspect the timezone issue is because the javascript isn't correctly accounting for the string value being an empty string and using UTC in that case.  There are defaults but they only apply if/when timezone string is not defined.  If that's the case, then I can fix that in a separate pull too.

**Comment by nerrad** [comment]
Okay #1194 fixes the currency configuration issue.  I'll do the timezone issue in a separate pull (not connected to this issue).
