### ISSUE TITLE
Allow Ticket and Datetime label values to be optional

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1200]
These are optional with the current EE4 editor and should be in the new editor too.

**Comment by tn3rb** [comment]
completed as part of #1589

**Comment by joshfeck** [comment]
I saw that the "Ticket Label" field still has a red asterisk next its form label. Shouldn't the asterisk be removed so it doesn't look like the field is required?

**Comment by joshfeck** [comment]
Ticket Label field label no longer has an asterisk.
