### ISSUE TITLE
About Page Formatting is Messy

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#1202]
**Describe the bug**
It looks like the formatting on the about page is in disarray:
![‹ Events by Espresso — WordPress 2019-05-10 09-23-15](https://user-images.githubusercontent.com/235315/57538501-c5ad2400-7305-11e9-90a0-a868d0b129e2.jpg)

**To Reproduce**
Visit the about page in the EE admin, then scroll about half way down, and you should see that the page is in disarray. Possibly because of changes in EE or WordPress CSS styles or broken HTML.

**Expected behavior**
The about page should have a nice clean layout.

**Screenshots**
See above.

**Environment:**
 - Version of Event Espresso:   4.9.81.rc.021	
 - Version of WordPress: 5.2
 - Browser: Chrome and Firefox

**Comment by joshfeck** [comment]
This is because of some new styles (added in WP 5.2) in WP core's about.css stylesheet.
