### ISSUE TITLE
Update PayPal Pro to use SCA

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1208]
More info here:

https://www.paypal.com/uk/webapps/mpp/psd2

@mnelson4 can you outline what's needed for PayPal Pro to have SCA?

**Comment by mnelson4** [comment]
I began reading up on it, and PayPal wants you to sign up for Cardinal Commerce and they'll somehow help with 3D secure integration. I haven't yet found any documentation on what exactly is needed...
So I signed upfor Cerdinal Commerce (added the creds to the gateways doc), and am looking to begin on that. Our users who want to support SCA will also need to sign up

**Comment by mnelson4** [comment]
Aha! Documentation: https://cardinaldocs.atlassian.net/wiki/spaces/CC/pages/131806/Getting+Started 
and https://cardinaldocs.atlassian.net/wiki/spaces/CC/pages/7929857/Cardinal+Cruise+Standard

**Comment by mnelson4** [comment]
Note: I discovered today Cardinal Commerce OneConnect, which is an intermediate for a lot of different gateways. There is [a WooCommerce plugin](https://wordpress.org/plugins/cardinalcommerce-oneconnect/) that uses it.
I started a p2 regarding it: http://p2.eventespresso.com/2019/07/26/sca-is-all-the-rage/

Documentation here: https://cardinaldocs.atlassian.net/wiki/spaces/CP/pages/681148427/WooCommerce+Plugin

**Comment by mnelson4** [comment]
documentation that helped me understand what's going on: https://cruisecontrolsbox.cardinalcommerce.com/getting-started.html

**Comment by mnelson4** [comment]
A good video showing how Cardinal Commerce and PayPal Pro work with Open Cart: https://dreamvention.com/blog/paypal-pro-with-cardinal-3d-secure-tutorial/

**Comment by mnelson4** [comment]
Aha, here's some documentation on the PayPal side of things: https://developer.paypal.com/docs/classic/paypal-payments-pro/integration-guide/3d-secure/#integration-steps

Basically, the merchant's site jumps through all the Cardinal Commerce hoops for 3D secure, then when that's all done, we get some codes from Cardinal Commerce, and we pass those to PayPal to validate that the customer has been authenticated with 3D secure by Cardinal Commerce.

**Comment by mnelson4** [comment]
Testing cards: https://cardinaldocs.atlassian.net/wiki/spaces/CCen/pages/400654355/3DS+1.0+Test+Cases

**Comment by mnelson4** [comment]
Related: Authorize.net integrates with Cardinal Commerce https://community.developer.authorize.net/t5/The-Authorize-Net-Developer-Blog/Using-CardinalCommerce-with-Authorize-Net/ba-p/61267 (and even AIM does, as you can see the parameters  x_authentication_indicator and x_cardholder_authentication_value in their doc shttps://developer.authorize.net/api/upgrade_guide/#aim)

**Comment by mnelson4** [comment]
We decided to cut our losses and give up on doing Cardinal Commerce. In the case of PayPal Pro, there are lots of alternative PayPal payment methods already, and have easier PCI compliance requirements.
