### ISSUE TITLE
Email verification in check-out

### ISSUE THREAD

**Issue by jonathan-dejong** [eventespresso/event-espresso-core#121]
Hi!

So let's assume all customers are idiots (seems many are) and are incapable of typing in their own email during checkout. Since there's no verification field their registration will not send out emails to the correct emailadress (registration complete for example) and the EE admins can't contact them (unless they also required a phone number). 

I think a great addition to the checkout would be to have a email verification field like so many other checkout solutions. For EE this is especially important since they might receive a ticket to this email. 

It doesn't matter to me if it's mandatory, added via filter, available as an option in settings or whatever :) 

Thanks!

**Comment by tn3rb** [comment]
ya I think that's a great idea... will create a ticket for it

**Comment by joshfeck** [comment]
No need to create a ticket @tn3rb, we already have #7744

**Comment by jonathan-dejong** [comment]
@joshfeck so it's a work in progress?

**Comment by nerrad** [comment]
There's a ticket for it so its on our radar.  No ETA on delivery though because we've got a lot of other higher priority things in the queue.  Pull requests are welcome though :)

**Comment by joshfeck** [comment]
This may be an item that will require the registration form system rewrite we're planning in #856

**Comment by joshfeck** [comment]
https://eventespresso.com/topic/ee4-add-a-2nd-field-to-confirm-email-address-on-registration-page/#post-299492

**Comment by lorenzocaum** [comment]
"That one made an error entering their own e-mail address, and we had to track it down when our own e-mail to them was returned as undeliverable. It also means they didn't get the system-generated confirmation e-mail. It would be very handy if your plug-in included an "Enter e-mail twice" feature to avoid user mistakes."

https://secure.helpscout.net/conversation/946569780/689143?folderId=100617

**Comment by lorenzocaum** [comment]
I've spotted this a couple times recently. 

Here is the feedback from one of them:

"hi I bought a ticket for a event for NYE and haven’t received the ticket but the money’s been taken out my account?"

https://secure.helpscout.net/conversation/1042821199/730273

**Comment by joshfeck** [comment]
added in #2523
