### ISSUE TITLE
Fix the 'Registration items' showing all tickets/line items related to a transaction.

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#1210]
If you have multiple tickets within a group, all of those tickets show on the 'Registration Items' table when editing a registration.

It's easier to see this so here are the steps to reproduce:

Create an event with multiple ticket types, it doesn't matter how many but its more obvious if you have a few. My setup used 6 (Ticket 1-5) and I added another to test the attendee mover (initially we thought it was an issue from that add-on, but turns out it's not).

Add at least 1 ticket from each of your tickets to a group, for example - https://take.ms/dPQWx

Register and pay for the group.

Now edit any of the 5 registrations created for that group and look at the 'Registration items' table it'll look something like this - https://take.ms/4FHVv

That's editing the registration for Ticket 4, so it shows a price for it, all of the others show 0.00

If you move a registration using the attendee mover to a ticket you hadn't selected before (this is where my additional ticket come into play) you end up with an additional ticket type shown on that list for every registration which can appear to be from no-where.

---

I did some digging into this and it looks like it's from [EE_Admin_Table_Line_Item_Display_Strategy.strategy.php](https://github.com/eventespresso/event-espresso-core/blob/master/core/libraries/line_item_display/EE_Admin_Table_Line_Item_Display_Strategy.strategy.php) looping over all of the children from a sub-total line item, it gets to a line item related to an event and its children are all of the ticket line items related to it.

Just noting in case its an obvious fix that I can't see in the above :)

**Expected behavior**
Display the line items only related to the current registration being edited?

**Comment by joshfeck** [comment]
Yes, ideally only the ticket related to the registration should be shown in the single registration view. Other tickets should not be included in that table.
