### ISSUE TITLE
Datepicker required value validation shows if it has a field but another questions triggers the error

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#1213]
If you have a required datepicker question within your question group along with another required question, provide a value for the datepicker question but NOT for the other one and submit the form, the error shown includes the datepicker question.

Example: https://monosnap.com/file/aHwPUz782JXfSEJQV497XWDcF7V4o1

**Expected behavior**
Don't include the datepicker question if it has a value.

**Comment by joshfeck** [comment]
Hey Tony I'm not able to replicate this.

<img width="713" alt="Screen Shot 2019-05-16 at 9 02 53 AM" src="https://user-images.githubusercontent.com/891156/57855863-ab69bf00-77b9-11e9-8557-c03e2b9c8505.png">


Are there other items needed to replicate the issue?

**Comment by Pebblo** [comment]
Looks like you need something set on 'Required Text' field of the DatePicker question for it to show.

No Required Text - https://monosnap.com/file/kL6zXT9jVM1yqfEX1Wy2WBpBrzBOI2

With Required Text - https://monosnap.com/file/mIALGPQe2qESPvxka433JaiAC6EPwJ

Not sure why I don't get the 'Please enter a value...' string though.

**Comment by joshfeck** [comment]
OK yep, if anything is set for "Required" for the datepicker question, then the "Required" error text for the datepicker question is also included in the EE notice, but it shouldn't be included.

**Comment by mnelson4** [comment]
I'm able to reproduce. I see the error message is coming up before any server-side validation, so it's some problem client-side...

**Comment by mnelson4** [comment]
It doesn't sound like this is a huge priority so I'm not going to investigate the JS right away...

**Comment by tn3rb** [comment]
setting estimated effort at 10 for now, because the cause is unknown and could potentially be messy, but is likely going to be a relatively easy fix

**Comment by mnelson4** [comment]
Ok I got some time to investigate, and I see when you use the datepicker, the field temporarily flashes with a validation error message. I see `SPCO.errorPlacement()` is getting called, probably because when you click off the popup datepicker, JS validation is being triggered, and the error message is being added to `SPCO.invalid_input_errors`, and it is then used later when you try to submit the form (instead of the required field)...

**Comment by mnelson4** [comment]
fixed by https://github.com/eventespresso/event-espresso-core/pull/1415
