### ISSUE TITLE
V4 Duplicate Event Missing

### ISSUE THREAD

**Issue by KinnaT** [eventespresso/event-espresso-core#123]
There's an old issue (#31) about what I'm experiencing.  The screenshot shows all of the options I have for events in EE4, but duplicate is not one of them. For complex events, this is proving to be troublesome.
<img width="825" alt="capture9" src="https://cloud.githubusercontent.com/assets/4543324/10270381/687daf18-6ab5-11e5-97f0-dd7bb753517e.PNG">

**Comment by nerrad** [comment]
Bulk duplication is not available.  However, when you edit an event, there is a duplicate button right above the title for the event.
