### ISSUE TITLE
Adding third party gateways

### ISSUE THREAD

**Issue by gabrielmerovingi** [eventespresso/event-espresso-core#124]
Hey everyone.

Is there any documentation on how to add in a third-party gateway for EE4? My plugin supports EE3 and I have built a new one for EE4 but I can not figure out how to get EE4 to find and recognize my gateway located in my plugin.

I followed the built-in gateways and named my file: EE_PMT_myCRED.pm.php but no luck.

**Comment by joshfeck** [comment]
Hi Gabriel,

You can find documentation on how to add a third party gateway as an add-on for Event Espresso 4 here:

http://developer.eventespresso.com/docs/ee4-payment-method-development/

**Comment by gabrielmerovingi** [comment]
Thank you!
