### ISSUE TITLE
Please remove the note in Billing Information section when view transaction

### ISSUE THREAD

**Issue by nvphuc1989** [eventespresso/event-espresso-core#127]
There is a note in Billing Information section when view transaction as below:
*Note: Card expiry dates and CCV are not stored. Only the last 4 digits of card numbers are stored.*

Because of the PCI Compliance, most payment plugins never log any credit card information even the last 4 digits of card numbers. But this note is always displayed for payments having billing information and it could make the user confuse that the payment plugin doesn't follow the PCI compliance strictly.
So better if this note can be removed from EE. Thanks.
![billing information](https://cloud.githubusercontent.com/assets/11606840/10825261/ce0d4e7a-7e96-11e5-9dda-a00c6edfc57e.png)

**Comment by mnelson4** [comment]
I can see how this is confusing if the payment method doesn't store the last 4 digits of the card number. We should probably only display this when the payment method actually stores the 4 digit

**Comment by mnelson4** [comment]
just a matter of clarification, by
> most payment plugins never log any credit card information even the last 4 digits of card numbers

did you mean most Event Espresso Payment Method Addons? Or did you mean most Wordpress plugins that accept payment data (eg Woocommerce, Wp E-Commerce, etc)?

**Comment by nvphuc1989** [comment]
I just meant the common shopping carts payment plugins, includes EE. I see the Vanco plugin for EE is an example for submitting credit card directly to the gateway without storing in EE server.
We don't need to remove the note, just provide an way to customize/change it depends on how EE payment addons store customer credit card info (full, only the last 4 digits or none...).

**Comment by mnelson4** [comment]
you can try the branch FET-9015-if-billing-info-has-no-4-digits-from-credit-card. Does that meet your needs?

**Comment by nvphuc1989** [comment]
It seems I have not right to access the branch.

**Comment by mnelson4** [comment]
this branch also got merged into master and deleted, so please try master branch now

**Comment by nvphuc1989** [comment]
I'm fine with the change. Thanks.
