### ISSUE TITLE
Prepare all translation-ready strings with `wp_strip_all_tags()` before passing to `wp_localize_script()`

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1275]
Need to review core (and add-ons) to make sure strings do not include tags before they're passed to wp_localize_script().

An example that needs changing:

`EE_Registry::$i18n_js_strings['links_disabled'] = __('All the links on this page have been disabled because this is a generated preview message for the purpose of ensuring layout, style, and content setup.  To test generated links, you must trigger an actual message notification.', 'event_espresso');`

can be changed to:

`EE_Registry::$i18n_js_strings['links_disabled'] = wp_strip_all_tags(__('All the links on this page have been disabled because this is a generated preview message for the purpose of ensuring layout, style, and content setup.  To test generated links, you must trigger an actual message notification.', 'event_espresso'));`

**Comment by tn3rb** [comment]
EZ but may be a bit time consuming
