### ISSUE TITLE
Success notice in admin registration needs styling

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#1279]
**Describe the bug**
The success notice when adding a new registration via the admin is missing some styling:
![‹ Events by Espresso — WordPress 2019-05-31 14-59-43](https://user-images.githubusercontent.com/235315/58734837-c6d9ea00-83b5-11e9-9334-315fb81ce5cf.jpg)

**To Reproduce**
1. View the registrations for an event
2. Click on Add New Registration
3. Select a number of tickets, then click the submit button
4. You will see the unstyled notice at the top of the page (see screenshot above)

**Expected behavior**
Success notices should look something like this:
![‹ Events by Espresso — WordPress 2019-05-31 15-03-36](https://user-images.githubusercontent.com/235315/58734994-4c5d9a00-83b6-11e9-9550-12ac628be6f5.jpg)

**Environment:**
 - Version of Event Espresso:  4.9.82.rc.015
 - Version of WordPress: 5.2.1
 - Browser: Chrome and Firefox

**Comment by joshfeck** [comment]
Fixed in #1283
