### ISSUE TITLE
Getting error with the method EE_Payment_Processor::instance()->process_refund

### ISSUE THREAD

**Issue by nvphuc1989** [eventespresso/event-espresso-core#128]
Hi EE team,

This is related to the ticket #112 
I have done successfully with the method `EE_Payment_Processor::instance()->process_payment` but getting failed with the method `EE_Payment_Processor::instance()->process_refund`. Here is the steps:
1. I added a method `public function do_direct_refund($payment, $refund_info = null)` in My_Onsite.gateway.php file.
2. Then I trigger the function `EE_Payment_Processor::instance()->process_refund($payment_method, $payment, $refund_info);`
=> Getting an error:
>Fatal error: Call to a member function type_obj() on integer in \eventespresso4\wp-content\plugins\event-espresso-decaf\core\EE_Payment_Processor.core.php on line 285

```php
public function process_refund( $payment_method, $payment_to_refund, $refund_info = array() ){
    /** @type EE_Payment_Method $payment_method */
    $payment_method = EEM_Payment_Method::instance()->ensure_is_ID($payment_method);
    if ( $payment_method->type_obj()->supports_sending_refunds() ) {
        $payment_method->do_direct_refund( $payment_to_refund,$refund_info );
        $this->update_txn_based_on_payment( $payment_to_refund->transaction(), $payment_to_refund );
    }
    return $payment_to_refund;
}
```
I see the problem when the code set`$payment_method` to integer then check it as an object.
I have tried to comment the line **ensure_is_ID** and run it again but get another error:
>Fatal error: Uncaught exception 'EE_Error' with message 'Method do_direct_refund on class EE_Payment_Method does not exist!

Please suggest how to make the method the method `EE_Payment_Processor::instance()->process_refund` work? Thanks!

**Comment by tn3rb** [comment]
@nvphuc1989 
I've created a ticket for the issue, pushed a fix to a branch, and sent the ticket for code review.

You can view the branch and follow any changes here:
https://github.com/eventespresso/event-espresso-core/tree/BUG-9027-process-refund

we'll let you know if/when this gets merged to master.

Thanks for reporting this issue.

**Comment by mnelson4** [comment]
@nvphuc1989 if you change the line from `ensure_is_ID` to `ensure_is_obj` does it work too?

**Comment by nvphuc1989** [comment]
It doesn't work too @mnelson4

**Comment by mnelson4** [comment]
@nvphuc1989 did you try the branch Brent mentioned?

**Comment by nvphuc1989** [comment]
@mnelson4 It seems I have not right to access the branch.

**Comment by mnelson4** [comment]
I think the branch got merged into master and deleted just a little while ago. So does MASTER branch work for you?
