### ISSUE TITLE
An NVP/SOAP API username from PayPal with a plus symbol will be rejected

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/event-espresso-core#1289]
**Summary**
A customer has a plus symbol in their API username and this causes the credentials to be rejected in PayPal Express.

This works: `hello-facilitator_api1.example.com`

This causes an issue: `hello+facilitator_api1.example.com`

When I look in PayPal's sandbox, I can see that the email address is used as the API username so if the email address has a "+" then the API username will also get that plus symbol.

![Image 2019-06-05 at 8 42 36 AM](https://user-images.githubusercontent.com/1079138/58957090-e2564380-876d-11e9-9368-73e2349885ab.png)

**Steps to reproduce**
See above

**Reported or seen on**
https://secure.helpscout.net/conversation/866535185/653920/

**Other notes**
I suggested setting up PayPal Smart Buttons since it uses another set of credentials.

**Comment by joshfeck** [comment]
The error shown in the validation message is:

`Your PayPal API credentials appear to be invalid. PayPal said "Security header is not valid (10002)". Please see tips below.`

**Comment by tn3rb** [comment]
likely just needs a regex to filter the API username according to PayPal's requirements, but Michael or Nazar might know a better alternative

**Comment by mnelson4** [comment]
Thanks Brent, but on the related PR, we discovered that even if we fix things on our end (don't double URL-encode the API credentials), PayPal itself has an internal server error when an API username has a plus sign in it. So although they haven't documented that it's illegal, their system blows up with it. So this seems to be a won't-fix type situation.
