### ISSUE TITLE
Fix fatal thrown on ajax requests when UXIP notice is shown

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#1298]
See: https://eventespresso.com/topic/not-able-to-save-php-files/

If you have the UXIP notice shown on your site and try to edit any files with the WP editor you'll get a fatal error:

```
[07-Jun-2019 10:16:38 UTC] PHP Fatal error:  Uncaught Error: Class 'EE_Admin_Page' not found in /home/pebbloco/public_html/ee4/wp-content/plugins/event-espresso-core-reg/core/domain/services/pue/Stats.php:148
Stack trace:
#0 /home/pebbloco/public_html/ee4/wp-content/plugins/event-espresso-core-reg/core/domain/services/pue/Stats.php(108): EventEspresso\core\domain\services\pue\Stats::optinText()
#1 /home/pebbloco/public_html/ee4/wp-includes/class-wp-hook.php(286): EventEspresso\core\domain\services\pue\Stats->optinNotice('')
#2 /home/pebbloco/public_html/ee4/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#3 /home/pebbloco/public_html/ee4/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#4 /home/pebbloco/public_html/ee4/wp-admin/admin-header.php(281): do_action('admin_notices')
#5 /home/pebbloco/public_html/ee4/wp-admin/plugin-editor.php(153): require_once('/home/pebbloco/...')
#6 {main}
  thrown in /home/pebbloco/public_html/ee4/wp-content/plugins/event-espresso-core-reg/core/domain/services/pue/Stats.php on line 148
```

If you dismiss the notice you can once again edit your files.

---

Quick and easy way to reproduce, assuming you've already dismissed th UXIP notice, run this (I used Debug bar console):
```
$ee_config = EE_Config::instance();
$ee_config->core->ee_ueip_has_notified = false;
$ee_config->update_espresso_config(false, false);
```

Go to Plugins -> Plugin editor (Note the UXIP notice should be shown at the top of the page, leave it there)

It doesn't matter what file you edit, make no changes and just hit 'Update file', it should fail.

Dismiss the UXIP notice and hit Update File again (you don't need to refresh etc), it now should work.

**Comment by tn3rb** [comment]
there's two ways to approach this:

* if there are filters for controlling the loading of the UXIP logic, then that can be turned off ahead of time within `\EventEspresso\core\services\request\middleware\DetectFileEditorRequest` similar to how the session is prevented from loading
* or the logic for loading/executing UXIP logic can be wrapped in a conditional that checks `$this->request->isWordPressScrape()` and does not run if that returns `true`. This requires the class loading/executing the UXIP logic to have access to an instance of `\EventEspresso\core\services\request\RequestInterface` which means that has to be injected if not already.

the first option is probably both the easiest and most performant option
