### ISSUE TITLE
Fluent Setters on Datetime VO return wrong class when using ServerDateTime VO

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#1301]
**Describe the bug**
While working on REM, discovered that the fluent setters in the `DateTime` VO class don't work well when using the `ServerDateTime` VO class because those fluent setters **always** return an instance of `DateTime`.

**To Reproduce**
```js
let date = new ServerDateTime();
date = date.set( { hour: 8, minute: 30 } );
// false
console.log( 'date instanceof ServerDateTime', date instanceof ServerDateTime );
// true
console.log( 'date instanceof DateTime', date instanceof DateTime );
```

**Expected behavior**
fluent setters on an object should return instance of the same class

**Comment by tn3rb** [comment]
here's another good example that just makes makes you go "huh?"

```js
date = ServerDateTime.fromMoment( moment() );
console.log( date );
// DateTime {…}
```

**Comment by nerrad** [comment]
Ya class inheritance in javascript is definitely not the same as php inheritance ;)  I'm pretty sure I know how I'll fix this (and i'll need fixed for static methods as well).

**Comment by nerrad** [comment]
@tn3rb also reported in slack there was a problem with `isUtc` flag being true when ServerDateTime has the timezone string of "America/Vancouver" internally.
