### ISSUE TITLE
Basic Auth sometimes not working from subsites

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/event-espresso-core#1307]
## Issue Overview

Strangely, sometimes basic auth isn't authenticating requests going to subsites. See https://eventespresso.com/topic/the-application-does-not-work-on-secondary-site-multipsite-2/#post-294141
You get an error when trying to log in using the mobile apps too, of course.
We are reproducing demoee.org, but not on eventsmart or MENW, nor on my local install or on my wpcowichan.org (which is also a multisite install of EE btw).

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Environment Data:

Version of EE: 4.9.81?

Version of WordPress:?

PHP Version:  ?

Browser used:  ?

## Steps to Reproduce (for bugs)

In progress. Not quite sure what's the difference between when we're reproducing or not.

**Comment by nerrad** [comment]
Just wondering if the difference between multi-site installs where things work and multi-site installs where things don't work is the _type_ of multisite it is:  subdomain, or subfolder (somesite.domain.com vs domain.com/somesite)?

**Comment by joshfeck** [comment]
I think Darren is on to something. MENW and ES are subdomain multisites, but demoee.org (and the sites where this is an issue) are subfolder multisites.

**Comment by mnelson4** [comment]
aha, but I am reproducing on a local subdomain install. :smile:

**Comment by mnelson4** [comment]
Ok Basic Auth isn't getting loaded on the subsites because `\EventEspresso\core\domain\services\contexts\RequestTypeContextChecker::isApi()` is returning false (ie, we don't think its a REST API request)... Let's try to see why it thinks that...

**Comment by mnelson4** [comment]
ah ok, and the reason that's not working is because we're looking for a REST path like `wp-json` but are instead finding `mysite/wp-json`. (So it looks like Darren's hunch was correct, and it was working on wpcowichan.org because I was testing with an older version of EE that didn't have this bug...)
One trick is finding the current site's URL, because it seems we can't use `get_rest_url()` yet because it relies on `WP_Rewrite` which hasn't been constructed at this stage of the request...

**Comment by joshfeck** [comment]
So is this a regression from #974?

**Comment by mnelson4** [comment]
Yes I think so @joshfeck.

**Comment by joshfeck** [comment]
fixed in #1308
