### ISSUE TITLE
Support for more countries in Venues

### ISSUE THREAD

**Issue by Petervw** [eventespresso/event-espresso-core#131]
When I edit a location in the Event Espresso plugin, I'd like to select "The Netherlands". The only countries which are available are "Canada" or "United States".

This is the select field in the WP-Admin:
![image](https://cloud.githubusercontent.com/assets/7113270/11208402/45de4e44-8d1b-11e5-85ce-72e0f7ee6caa.png)

**Comment by nerrad** [comment]
This guide should help: http://eventespresso.com/wiki/change-countries-used-event-espresso/
