### ISSUE TITLE
Changes sometimes not applied when calling the save method

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#1326]
Easiest to show with a a quick example:

```
add_action('AHEE__Extend_Events_Admin_Page___duplicate_event__after', 'updateacfanddatetime', 10, 2);
function updateacfanddatetime($new_event, $orig_event) {
  $new_datetimes = $new_event->get_many_related('Datetime');
  foreach ($new_datetimes as $new_dtt) {
      $newdate = new DateTime(date("Y-m-d",strtotime($new_dtt->start_date()))) ;
      $newdateplusone = date_format($newdate->add(new DateInterval('P1D')), 'F d, Y');
      $new_dtt->set_start_date($newdateplusone);
      $new_dtt->set_end_date($newdateplusone);
      $new_dtt->save();
 }            
}
```

The above adds a single date onto your events datetimes when you duplicate an event, however, the change is not saved as `set_end_date` does not set a `_has_changes` flag in `EE_Base_Class.class.php::save()`.

So for the above to work as is, you'd need to add something like:

`$new_dtt->set('DTT_EVT_start', $new_dtt->start_date_and_time());
$new_dtt->set('DTT_EVT_end', $new_dtt->end_date_and_time());`

just before the `save()` call, as `set()` sets the `_has_changes` flag it all then works fine.

Spoke about this a little with Darren, take a look here
See: https://eventespresso.slack.com/archives/C080L8G68/p1560423687230700
(Darren replies a little below) 

Posting convo here in case we hit slack limit:

> tony [12:01 PM]
Found something that (I think) is a little strange with Datetimes.
A user is updating datetimes by 1 day when you duplicate the event and is doing it like this:
`function updateacfanddatetime($new_event, $orig_event) {
  $new_datetimes = $new_event->get_many_related('Datetime');
  foreach ($new_datetimes as $new_dtt) {
      $newdate = new DateTime(date("Y-m-d",strtotime($new_dtt->start_date()))) ;
      $newdateplusone = date_format($newdate->add(new DateInterval('P1D')), 'F d, Y');
      $new_dtt->set_start_date($newdateplusone);
      $new_dtt->set_end_date($newdateplusone);
 }            
}`
(edited)
Which apart from missing `$new_dtt->save();` I would have through worked, right?
Echoing out `$new_dtt->start_date_and_time()` and `$new_dtt->start_end_and_time()` both before and after the change shows the date is updated, but save fails.
Did some digging and in `EE_Base_Class.class.php::save()` it checks `$this->_has_changes` before doing any updates, which is false after the above, hence the fail, so the only way to update the datetime is using something like `$new_dtt->set('DTT_EVT_start', $new_dtt->start_date_and_time());` because it sets `_has_changes`.
Is that expected?
darren [3:34 PM]
tony re the above, ya that looks like a bug… I’m trying to trace when `_has_changes` was added.  the problem is `_set_date_time` modifies the internal field values on a `EE_Base_Class` instance directly rather than going through `_set`.  So as you discovered `_has_changes` isn’t flagged and the save won’t happen.
so `EE_Base_Class::_set_date_time` needs to set the `_has_changes` flag as well. (edited) 
tony [3:36 PM]
Kk thanks for checking. I can do a ticket in a little, wasnt sure if I was missing something
darren [3:51 PM]
So tony looks like the  `$_has_changes`  property was added here: https://events.codebasehq.com/projects/event-espresso/tickets/10167
I’m looking now to see if it existed in the `_set_date_time` method at one point.
(commits made in 2016 but not actually merged to master until 2017)
ya I’ve looked through git history and it looks like `_set_date_time` (or `_clear_cached_property` which should probably mark `_has_changes` as well) never had any flag or accounted for `_has_changes`.  If/when you create the ticket, can you copy/paste in the above too please?  It’s good for reference.

**Comment by joshfeck** [comment]
Was this something you were going to take on @Pebblo or should I assign to someone else?

**Comment by Pebblo** [comment]
I'd prefer one of the devs take this on.

I follow why it's happening etc, but as this is a change in `EE_Base_Class` it's likely to be a pretty broad change which one the devs would best to handle.

**Comment by Pebblo** [comment]
Turns out this wasn't actually as broad a change as I though!

Nvm, fixed now.

**Comment by mnelson4** [comment]
Don't worry, we'll make up for it by doing a complete refactor of EE next time you notice a typo! :wink:
