### ISSUE TITLE
Not everything translates

### ISSUE THREAD

**Issue by jonathan-dejong** [eventespresso/event-espresso-core#133]
Hi!

Loosely connected with this issue:
https://github.com/eventespresso/event-espresso-core/issues/130

Now that I've updated I find several strings no longer translated and I can't seem to re-translate them either.

I ran a sync with Loco translation to get the latest POT file. Then downloaded the POT file and my custom po file.

Opened the po file with poedit, synced up the POT file (found like 80 new strings and a few deprecated). I tried translating the string I found missing (som where even already translated in the PO file). 

Still no dice :/

**Comment by mnelson4** [comment]
which strings aren't translating?

**Comment by lorenzocaum** [comment]
Hi Jonathan, we recommend merging the PO file from GlotPress into your existing file. That PO file will be a combined file from our add-ons and the core plugin. You can get a copy from the language project here:

http://translate.eventespresso.com/projects/event-espresso-4

Also, double-check that there are not old files in this location:

/wp-content/plugins/event-espresso-core-reg/

Language files (e.g. the MO file) should be added here:

/wp-content/uploads/espresso/languages/

What strings are not translating?

**Comment by jonathan-dejong** [comment]
Hey,

If I merge the PO file from GlotPress, which PO file will get priority? I don't want my own strings to be overwritten.. :) 

There's no old files and I'm adding them in the correct place so no worries. I've been using custom translations for over a year now. 

I don't remember the exact strings right now (can check later if you like) but most of the strings in the ticket details (collapsing the details in the ticket selector).

**Comment by nerrad** [comment]
There's been some work on the translation strings throughout the code since March,  if there's still strings still not translating we'll need that specified in a new issue.
