### ISSUE TITLE
Translation missing in Checkout Steps

### ISSUE THREAD

**Issue by DavidSteinbauer** [eventespresso/event-espresso-core#137]
Please add translation as the following:
![2015-12-14 at 12 47](https://cloud.githubusercontent.com/assets/3392092/11780248/cc70eb24-a260-11e5-8249-cbcc70d46963.png)

**Comment by nerrad** [comment]
I closed the pull request, you can see my explanation there.

**Comment by nerrad** [comment]
In case you're wondering, I'm fairly certain the value for `$reg_step->name()` is already translated.  That value is retrieved from the `$_name` property on the `EE_SPCP_Reg_Step` child classes.  For example, if you look at `EE_SPCO_Reg_Step_Attendee_Information` you'll see this defined in it's constructor:

```
$this->_name = __('Attendee Information', 'event_espresso');
```
