### ISSUE TITLE
_has_billing_form = false not honoured

### ISSUE THREAD

**Issue by gabrielmerovingi** [eventespresso/event-espresso-core#139]
I am adding support for Event Espresso for my plugin by using an Online gateway. I am, as described in the documentation using _has_billing_form = false since all a user needs to do to pay with points is to be logged in.

But when I checkout, I get an error: 
"EE_SPCO_Reg_Step_Payment_Options - _billing_form_is_valid - 1255"

It seems that even with _has_billing_form set to false, it is not being honoured.
I did manage to get it work by adding:

    if ( ! $this->checkout->payment_method->type_obj()->has_billing_form() )
    	return TRUE;

in the _billing_form_is_valid() function in EE_SPCO_Reg_Step_Payment_Options.
But I am not sure if I the issue is somewhere else and I am just patching up my mistake.

**Comment by mnelson4** [comment]
This sounds like a bug to me and your fix sounds like a good one. 
Although, is there a reason you aren't making your payment method an OFFLINE payment method? Because if your payment method isn't communicating with any remote server that sounds like a better fit

**Comment by gabrielmerovingi** [comment]
Maybe I misunderstood the documentation as I was under the impression that you should use Offline gateways if you need to redirect users to complete a payment and handle IPN calls etc. Since users pay using points that are stored as a custom user meta, I only need them to be logged in to charge their account.

**Comment by mnelson4** [comment]
Aha, I think we're getting terms mixed up.
There are 3 basic types of payment methods: ON-site(where the user enters payment information on the wordpress/event-espresso website), OFF-site(what you're describing, where the user is redirected to a separate site where they enter payment information), and off-LINE (where payments aren't processed online via event espresso at all, instead it's mostly just a way of instructing users to get payment to you in-person or via some other method).
So what you're describing sounds a little bit more like an off-LINE payment method, where users don't need to provide any payment information at time of purchase.

**Comment by gabrielmerovingi** [comment]
Ah! I will look at going offline then. Thank you.

**Comment by mnelson4** [comment]
ok. Although regardless, we are looking into applying your fix. Because what you did should have been ok

**Comment by gabrielmerovingi** [comment]
Yeah, it would also allow me to at least release the online version, which is working, while I have time to re-write things for an offline version.

**Comment by mnelson4** [comment]
yeah neat. That sounds like an addon that's been requested a few times that we've just never gotten around to adding. Maybe consider submitting it to our 3rd party addons page.

**Comment by gabrielmerovingi** [comment]
myCRED has supported Event Espresso just over a year now. But with the re-write of the gateway setup the old gateway no longer works. My users will be happy to hear that support is back. I will make a submission once I have updated things.
