### ISSUE TITLE
How to display questions for Additional Registrants?

### ISSUE THREAD

**Issue by hoandang** [eventespresso/event-espresso-core#141]
Hi there,

I am trying to programmatically query the questions from a particular event.

So far, I can retrieve the questions by the invoke the method question_groups() (according to this doc http://code.eventespresso.com/class-EE_Event.html). However, the method doesn’t seem to differentiate which one is the main question group, which one is the additional question group?

Ultimately, I am trying to display the view like this <a href="https://dl.dropboxusercontent.com/u/10120454/Screen%20Shot%202016-01-11%20at%2010.56.08%20am.png">screenshot</a> , as you can see the first section is the questions for main registrant, if the user click the green text (Spouse/Partner Details), the questions groups for additional registrant will display.

**Comment by mnelson4** [comment]
hi @hoandang 
if you have an `EE_Event` object, say in a variable like `$event`, you could do teh following:

```
foreach( $event->question_groups() as $question_group ){
    echo "question grouop name " . $question_group->name();
    foreach( $question_group->questions() as $question ) {
        echo "question name" . $question->name();
    }
}
```
If you want help with displaying html form inputs for each question, note that on branch BUG-9165-use-forms-system-isntead I just added a convenience method on `EE_Question` called `generate_form_input` which will create a `EE_Form_Input_Base` child from the question (exactly like how we do currently in our single page checkout). You can read more about form inputs and the forms system at http://developer.eventespresso.com/docs/ee4-forms-system/

**Comment by hoandang** [comment]
@mnelson4 Thanks for a very quick response.

The given snippet was fine for displaying single form, but in this situation I would like to display 2  different forms. For example, in this event 

<img width="284" alt="screen shot 2016-01-13 at 11 04 32 am" src="https://cloud.githubusercontent.com/assets/1758446/12280945/0e626174-b9e6-11e5-9fea-9eb125084a62.png"> 

If I choose "Title and Organisation Info" question groups for primary registrants, "Personal Information" for Additional Registrants, and use the question_groups() method to retrieve all the question info, then the result would be a list of question which has no identification of which one belongs to primary registrants, which one is for additional registrants.

**Comment by mnelson4** [comment]
oh I see, you want to get the question groups for the primary registration, or for the secondary registrations. 
If you set a variable of `$is_primary` equal to `true` if you want question groups for the primary registrations, and `false` if you want question groups for secondary registrations, then you could do `$event->question_groups( array( array( 'Event_Question_Group.EQG_primary' => $primary ) ) );`

**Comment by hoandang** [comment]
This is brilliant, thanks heaps.

**Comment by mnelson4** [comment]
great! Feel free to chime in on the plugin's wordpress.org profile at https://wordpress.org/support/view/plugin-reviews/event-espresso-decaf if you want eh
