### ISSUE TITLE
custom offsite gateway return URL

### ISSUE THREAD

**Issue by rheator** [eventespresso/event-espresso-core#142]
Hi,

I have been integrating a offsite gateway and so far managed to have the payment go through on the gateway end, but when the gateway redirects the customer back to the site, nothing gets processed on event espresso end. 

The gateway requires me to have a return URL, which I have specified as the transactions page.
Is that the right URL? 

handle_payment_update() function as follows:

``````
public function handle_payment_update($update_info, $transaction) {
	if( !  isset( $update_info[ 'txnRef' ] ) ){
		return NULL;
	}
	$payment = $this->_pay_model->get_payment_by_txn_id_chq_nmbr($update_info[ 'txnRef' ] );
	if($payment instanceof EEI_Payment &&  isset( $update_info[ 'status' ] ) ){
	//borrowed code from paypal standard. only need succ and fail
		switch ( $update_info[ 'status' ] ) {

			case 'succ' :
				$status = $this->_pay_model->approved_status();
				$gateway_response = __( 'The payment is approved.', 'event_espresso' );
				break;

			case 'fail' :
				$status = $this->_pay_model->failed_status();
				$gateway_response = __( 'The payment failed for technical reasons or expired.', 'event_espresso' );
				break;

			default :
				$status = $this->_pay_model->failed_status();
				$gateway_response = __( 'The payment failed for technical reasons or expired.', 'event_espresso' );
				break;

		}	
	}
	return $payment;
}
```````
gateway's manual in link below:
https://www.nets.com.sg/images/pdf/Umapi%20Lite%20Merchant%20Integration%20Manual%20V2.1.pdf

**Comment by mnelson4** [comment]
> The gateway requires me to have a return URL, which I have specified as the transactions page.
Is that the right URL?
if I understand you right: no, that is not the right url.
You can look at paypal standard's `EEG_Paypal_Standard::set_redirection_info()` for reference: https://github.com/eventespresso/event-espresso-core/blob/master/payment_methods/Paypal_Standard/EEG_Paypal_Standard.gateway.php.
Notice how the method is passed in a `$return_url` and a `$notify_url`? That `$return_url` is where users should be returning to after they have finished paying on the gateway's server.
(We have already constructed these URLs for you, you just need to pass them to the gateway server. You shouldn't need to go constructing it yourself).
Also note: it sounds like the gateway sends a separate request to the server to notify you of payment, separately from the user returning from the gateway site. If that's the case, in your gateway CLASS you should set `$this->_uses_separate_IPN_request=true` in its constructor, see http://developer.eventespresso.com/docs/ee4-payment-method-development/#handle_payment_update. Otherwise, payment notifications sent from the gateway server will be ignored (because you have instructed the class that payment data should instead be returned WITH the user when they return from the gateway site).
Does that help with your question?

**Comment by rheator** [comment]
Hi!

Yes that does clear things up for me.
The issue I have is that I cannot pass $return_url and $notify_url to the gateway, nor is there a point in passing it. The gateway does not take the return url from the post variables sent during transaction. Instead, the url is set on the gateway end and does not change. 

I'm not sure about the separate request part, but the POST that comes back from the gateway looks like this:
`http://someredacteddomainname.com/transactions?status=succ&errorCode=00&payment=Credit&txnTime=15%3A40%3A24.000&txnDate=20160128&amount=10.00&mid=123456789&txnRef=XGP6gmji9wWTSN3UEselnvKRyx8oLA`

where:
- txnRef is a randomly generated string I sent
- mid is a constant string I sent, which the gateway requires.

Right now, what I think I need to do is to combine the $return_url with the post variables from the gateway and redirect the user to the combined url. eg. 

`http://someredacteddomainname.com/registration-checkout/?step=payment_options&action=process_gateway_response&selected_method_of_payment=enets_gateway_offsite&spco_txn=267#checkout&status=succ&errorCode=00&payment=Credit&txnTime=15%3A40%3A24.000&txnDate=20160128&amount=10.00&mid=123456789&txnRef=XGP6gmji9wWTSN3UEselnvKRyx8oLA
`

So the flow would be as follows:

- User does a registration, picks this gateway
- User is redirected to gateway site, makes payment
- User is redirected to a separate script, script combines $return_url with POST from gateway
- User is redirected to combined url

Please let me know if my assumptions are correct. Thank you!

PS: This gateway does not do any form of verification or handshake after the initial POST.
I'm currently looking into $notify_url and $payment_url for any hints of how to prepare the combined url.

**Comment by rheator** [comment]
Hi,

I couldn't find anything on $notify_url and $return_url, so I'm just going to ask this:

If the payment gateway does not allow you to pass the $return_url, what can you do?

**Comment by mnelson4** [comment]
hi sorry I didn't get back to you earlier @rheator.
Yes in cases where you can't pass the return url or notify url to the gateway dynamically, your suggested workaround is probably the next best thing. 
Basically, you should add some code outside of the EE payment methods system to detect when a request is sent to the notify url or the return url, and then redirect them to the urls the EE payment methods system will recognize.

Sorry our payment methods system doesn't support this case very well. This is the first gateway for EE4 to work like this, but I know of others for EE3 so we definetely want to add better support for it. I'll look and see if that's an easy fix or not...

**Comment by mnelson4** [comment]
It looks like it might be an easy fix for the payment methods to handle IPNs using a static notify_url, but static return_urls might be trickier. Until we have something better, I think you're best using some old fashioned wp actions to detect a return or notify request from the gateway and redirect the request to the urls the EE4 payment methods system is expecting

**Comment by syedshussaini** [comment]
Hi @mnelson4, I am running through the similar problem. 
I am developing the offline payment method, so far I am able to redirect the user to the gateway, make payment and the customer is returned to the EE thank you page, but the payment remains pending.

I am working on merchant warrior payment gateway which allows return & notify URLs. I have made the return url to go to the default one.. 
Right now the return URL looks like this which means
`http://someredacteddomainname.com/registration-checkout/?step=payment_options&action=process_gateway_response&selected_method_of_payment=enets_gateway_offsite&spco_txn=267#checkout`

Currently my set_redirection_info() looks like this
```
public function set_redirection_info($payment, $billing_info = array(), $return_url = NULL, $notify_url = NULL, $cancel_url = NULL) {

$transaction = $payment->transaction();
$order = array(
'method'                =>'blah blah',
'merchantUUID'          =>$this->_merchant_uuid,
'apiKey'                =>$this->_api_key,
'transactionAmount'     =>number_format($payment->amount(),2),
'transactionCurrency'   =>$payment->currency_code(),
'transactionProduct'    =>$payment->TXN_ID(),
'returnURL'             =>$return_url,
'notifyURL'             =>$this->_notify_url,
   );
$order = apply_filters( "FHEE__EEG_Merchant_warrior__set_redirection_info__arguments", $order, $this );
 do_action( 'AHEE_log', __FILE__, __FUNCTION__, serialize(get_object_vars($this)) );

$payment->set_redirect_url($this->_gateway_url);
$payment->set_redirect_args($order);
return $payment;
}
```
& this is what handle_payment_update() looks like..

```
 public function handle_payment_update($update_info, $transaction) {
 if ( empty($update_info['status']) || empty( $update_info['transactionID']) ) {
     if ( isset( $update_info['transactionID']) ) {
         return $transaction->last_payment();
      } else {
                return null;
      }
}
$payment = $this->_pay_model->get_payment_by_txn_id_chq_nmbr( $update_info['transactionID'] );
if ( !$payment instanceof EEI_Payment ) {
       $payment = $transaction->last_payment();
}
 switch ( $update_info['status'] ) {
        case 'approved' :
            $status = $this->_pay_model->approved_status();
            $gateway_response = __( 'The payment is approved.', 'event_espresso');
            break;
       case 'return' :
           $status = $this->_pay_model->approved_status();
           $gateway_response = __( 'The payment returned is approved.', 'event_espresso');
           break;
     case 'pending' :
          $status = $this->_pay_model->pending_status();
          $gateway_response = __( 'The payment is pending.', 'event_espresso');
          break;
   }

return $payment;
}
```
how can I pass the data to the return url, so that it updates the status from pending to what ever the actual status is returned from the gateway.

Thanks

**Comment by mnelson4** [comment]
hey @syedshussaini, I think your situation might be different because merchant warrior DOES accept dynamic return and notify urls. Can you please create a separate ticket for your issue?

**Comment by syedshussaini** [comment]
Thanks for the reply.. I created a new issue here..
[https://github.com/eventespresso/event-espresso-core/issues/143](url)

**Comment by rheator** [comment]
Hi,

Sorry for the long absence, been away for a while.

I got the gateway provider to change the static url to a page with the redirect code on it.
Currently, it redirects to the payment processed page properly, but it does not complete the payment. 

Here is the code:
```
   $spco_txn = substr(strval($_GET["txnRef"]), -3, 3); //tostr, just in case. last 3 digits is the transaction id for now. Todo: add a delimiter to generated transaction number
    echo "<form action='http://someredacteddomainname.com/registration-checkout/?step=payment_options&action=process_gateway_response&selected_method_of_payment=enets_gateway_offsite&spco_txn=".$spco_txn."#checkout' method='post' name='frm'>";

//foreach ($_POST as $a => $b) {
//echo "<input type='hidden' name='".htmlentities($a)."' value='".htmlentities($b)."'>";
//getting gibberish

//}
    //we need txnRef, status, errorCode and amount. ignore all other variables
echo "<input type='hidden' name='txnRef' value='".$_GET["txnRef"]."'>";
echo "<input type='hidden' name='status' value='".$_GET["status"]."'>";
echo "<input type='hidden' name='errorCode' value='".$_GET["errorCode"]."'>";
echo "<input type='hidden' name='amount' value='".$_GET["amount"]."'>";
echo "</form>
<script language='JavaScript'>
document.frm.submit();
</script>";

echo "Please wait while we complete your transaction.";
  return "Please wait while we process your transaction";
```
The gateway returns with the variables in the URL.

**Comment by rheator** [comment]
Cleaned up a bit.

```
$spco_txn = substr(strval($_GET["txnRef"]), -3, 3); //txn_id was passed as the last digits of txn_id_chq_nmbr sent
//typical return url, with spco_txn
echo "<form action='".get_site_url()."/registration-checkout/' method='post' name='frm'>";
echo "<input type='hidden' name='step' value='payment_options'>";
echo "<input type='hidden' name='action' value='process_gateway_response'>";
echo "<input type='hidden' name='selected_method_of_payment' value='enets_gateway_offsite'>";
echo "<input type='hidden' name='spco_txn' value='".$spco_txn."'>";
//gateway response
echo "<input type='hidden' name='txnRef' value='".$_GET["txnRef"]."'>";
echo "<input type='hidden' name='status' value='".$_GET["status"]."'>";
echo "<input type='hidden' name='errorCode' value='".$_GET["errorCode"]."'>";
echo "<input type='hidden' name='amount' value='".$_GET["amount"]."'>";
echo "</form>
<script language='JavaScript'>
document.frm.submit();
</script>";

echo "Please wait while we complete your transaction.";
  return "Please wait while we process your transaction";
```
Just to make things clear, this is placed in a new page which the gateway will redirect to once it has processed the transaction. 

From what I see, handle_payment_update was never called when the redirect happened. 
Am I going about this wrong?

**Comment by rheator** [comment]
Is there a way to know what handle_payment_update has received?

**Comment by rheator** [comment]
Never mind, figured out why. Didn't save the transactions. The post was working correctly.

**Comment by mnelson4** [comment]
glad you found it. Sorry I wasn't able to be of more help, been busy with some deadlines
