### ISSUE TITLE
EE4 Custom offsite gateway return url issue.

### ISSUE THREAD

**Issue by syedshussaini** [eventespresso/event-espresso-core#143]
Hi @mnelson4, I am running through the similar problem. 
I am developing the offline payment method, so far I am able to redirect the user to the gateway, make payment and the customer is returned to the EE thank you page, but the payment remains pending.

I am working on merchant warrior payment gateway which allows return & notify URLs. I have made the return url to go to the default one.. 
Right now the return URL looks like this which means
`http://someredacteddomainname.com/registration-checkout/?step=payment_options&action=process_gateway_response&selected_method_of_payment=enets_gateway_offsite&spco_txn=267#checkout`

Currently my set_redirection_info() looks like this

```
public function set_redirection_info($payment, $billing_info = array(), $return_url = NULL, $notify_url = NULL, $cancel_url = NULL) {

$transaction = $payment->transaction();
$order = array(
'method'                =>'blah blah',
'merchantUUID'          =>$this->_merchant_id,
'apiKey'                =>$this->_api_key,
'transactionAmount'     =>number_format($payment->amount(),2),
'transactionCurrency'   =>$payment->currency_code(),
'transactionProduct'    =>$payment->TXN_ID(),
'returnURL'             =>$return_url,
'notifyURL'             =>$this->_notify_url,
   );
$order = apply_filters( "FHEE__EEG_Merchant_warrior__set_redirection_info__arguments", $order, $this );
 do_action( 'AHEE_log', __FILE__, __FUNCTION__, serialize(get_object_vars($this)) );

$payment->set_redirect_url($this->_gateway_url);
$payment->set_redirect_args($order);
return $payment;
}
```

& this is what handle_payment_update() looks like..

```
 public function handle_payment_update($update_info, $transaction) {
 if ( empty($update_info['status']) || empty( $update_info['transactionID']) ) {
     if ( isset( $update_info['transactionID']) ) {
         return $transaction->last_payment();
      } else {
                return null;
      }
}
$payment = $this->_pay_model->get_payment_by_txn_id_chq_nmbr( $update_info['transactionID'] );
if ( !$payment instanceof EEI_Payment ) {
       $payment = $transaction->last_payment();
}
 switch ( $update_info['status'] ) {
        case 'approved' :
            $status = $this->_pay_model->approved_status();
            $gateway_response = __( 'The payment is approved.', 'event_espresso');
            break;
       case 'return' :
           $status = $this->_pay_model->approved_status();
           $gateway_response = __( 'The payment returned is approved.', 'event_espresso');
           break;
     case 'pending' :
          $status = $this->_pay_model->pending_status();
          $gateway_response = __( 'The payment is pending.', 'event_espresso');
          break;
   }

return $payment;
}
```

how can I pass the data to the return url, so that it updates the status from pending to what ever the actual status is returned from the gateway.

Thanks

**Comment by mnelson4** [comment]
First I think the line that says
```
'notifyURL'             =>$this->_notify_url,
```
should be
```
'notifyURL'             =>$notify_url,
```
right? Because the `$notify_url` variable passed into `set_redirection_info` has the correct URL for receiving IPNs.

Also, I believe mwarrior sends the payment data to the notify url, right? If so, make sure you've set `$this->_uses_separate_IPN_request = true;` in the gateway class' constructor, otherwise it will expect payment data when returning from the gateway site and IGNORE IPNs sent to the notifyUrl.

**Comment by syedshussaini** [comment]
I have made the changes to the notify url & the `_uses_seperate_IPN_request = true; ` in the construct
but am still getting transactions as pending, I think that the gateway is receiving `txn_id_chq_nmbr` as empty. on outputting EE_Payment object I got this..

`EE_Payment Object
(
    [_props_n_values_provided_in_constructor:protected] => Array
        (
            [PAY_ID] => 60
            [TXN_ID] => 62
            [STS_ID] => PPN
            [PAY_timestamp] => 2016-02-11 23:06:05
            [PAY_source] => CART
            [PAY_amount] => 1.000
            [PMD_ID] => 11
            [PAY_gateway_response] => 
            [PAY_txn_id_chq_nmbr] => 
            [PAY_po_number] => 
            [PAY_extra_accntng] => 
            [PAY_details] => 
            [PAY_redirect_url] => http://secure-xyz.dev
            [PAY_redirect_args] => a:11:{s:6:"method";s:11:"blah blah";s:12:"blah blah";s:13:"blah blah";s:6:"apiKey";s:8:"blah blah";s:17:"transactionAmount";s:4:"1.00";s:19:"transactionCurrency";s:3:"USD";s:18:"transactionProduct";i:62;s:9:"returnURL";s:190:"http://secure-xyz.dev/wordpress_4.4.2/?page_id=5&step=payment_options&action=process_gateway_response&selected_method_of_payment=merchant_warrior_offsite&spco_txn=62#checkout";s:9:"notifyURL";s:157:"http://secure-xyz.dev/wordpress_4.4.2/?page_id=6&e_reg_url_link=1-d3bf0f765b0a410e019069f9bfb28b39&ee_payment_method=merchant_warrior_offsite";s:8:"hashSalt";s:10:"blah blah";s:4:"hash";s:32:"blah blah";s:7:"urlHash";s:32:"blah blah";}
        )`

**Comment by syedshussaini** [comment]
The IPN data I am getting is just the following without any of the return data:
```
IPN data	
page_id	5
step	payment_options
action	process_gateway_response
selected_method_of_payment	merchant_warrior_offsite
spco_txn	62
```

**Comment by mnelson4** [comment]
Yeah it sounds like they aren't sending the IPNs to the notify_url you're supplying them.
That IPN data looks like what gets logged when the user returns from the gateway website, not what gets logged when receiving an IPN.
So either they're not sending IPNs at all, or there's something misconfigured on your end, or maybe you're receiving the IPNs but but aren't processing them properly and just haven't noticed the IPN logs.
I'd suggest you take note that notify_url you're sending them, and then manually simulate sending a POST request with the needed post data in it to that URL. eg, you could use the postman google chrome browser extension to build a POST request and send it to that url. Then look at ALL the payment logs for that transaction, specifically looking for the one containing "IPN data received" (which is what gets logged everytime we successfully receive an IPN, regardless of whether the payment becomes approved as a result of the IPN). See if, by manually sending the request, the expected things get logged and the payment gets approved. If you don't see something getting logged everytime you send a request to that url, then somehow that url is wrong or something is interfering. You can look at event-espresso-core/shortcodes/espresso_txn_page/EES_Espresso_Txn_Page.shortcode.php for the code that initiates handling of the IPNs and pepper it with `echo`s for debugging. 
If you're seeing something is getting logged every time you manually send a POST to the notify url, but the payment isn't getting approved, then you're reading the IPN data wrong (or it's possible you're sending it wrong too). 
If it all works when you manually send an POST to the notify url, then merchant warrior must not be sending IPNs for some reason, or at least not to the URL you've specified.
Also, I can see you have permalinks disabled in the URLs you've given. Maybe you should try enabling permalinks, it's possible that could be interfering somehow

**Comment by syedshussaini** [comment]
@mnelson4, I did it exactly the way to suggested & its working in case of notify URL 
1 - The payment is going through when I am manually doing a POST using the notify url
but one problem with notify URL is MW returns the response in XML format as shown below - 
`<mwResponse>
<responseCode>0</responseCode>
<responseMessage>Transaction	approved</responseMessage>
<transactionID>1-918490ae-9a1c-11de-8649-000c29753ad4</transactionID>
<authCode>1</authCode>
<authMessage>Approved</authMessage>
<authResponseCode>0</authResponseCode>
<custom1>Custom	Field	1</custom1>
<custom2>Custom	Field	2</custom2>
<custom3>Custom	Field	3</custom3>
<customHash>e1af7c6a17758ef2907a50c96fa56d28</customHash>
<hash>082949a8dfacccda185a135db425377b</hash>
</mwResponse>`

2- when I am trying to do the same with return URL, it some how doesn't seem to find determine the transaction. The log just shows data when the user returns from the gateway website.

`
ID	133 <br>
Payment Method:	Merchant Warrior <br>
Transaction:	Could not be determined<br>

Content	<br>

IPN data	<br>

page_id:	5
step:	payment_options
action:	process_gateway_response
selected_method_of_payment:	merchant_warrior_offsite
spco_txn:	89`

is this because the txn_id_chq_nmbr not being set correctly.? if so to what value does it need to be set.?

Thanks a lot for your help

**Comment by mnelson4** [comment]
> 1 - The payment is going through when I am manually doing a POST using the notify url
but one problem with notify URL is MW returns the response in XML format

I don't follow why MW's xml formatted response is a problem. Your code just needs to parse the XML and read whether the payment was approved or not (eg you could use http://www.w3schools.com/php/php_xml_simplexml_read.asp). You might need to look at the raw post data too (eg maybe use http://php.net/manual/en/wrappers.php.php#wrappers.php.input instead of $update_info that gets passed into `handle_payment_update()`

> 2- when I am trying to do the same with return URL, it some how doesn't seem to determine the transaction. 

Well if you're receiving the IPNs successfully on the notify url, then there's really nothing you need to do on returning.

> is this because the txn_id_chq_nmbr not being set correctly.? 

Now that you mention it, it's not being set at all, but it isn't essential. If you're going to be looking up a payment in EE by the `PAY_txn_id_chq_nmbr` during `handle_payment_update()`, then you need to have set `PAY_txn_id_chq_nmbr`  on the payment object first, during `set_redirection_info()`. I'm not sure if MW allows you to assign a transactionId, but you don't really need it anyway. The notify URL you're passing to MW has a string that identifies which EE transaction the IPN is for, and uses that to set the `$transaction` passed into `handle_payment_update()`.

**Comment by syedshussaini** [comment]
Hi, I have been trying this but I am unable to figure out where exactly the EE is getting the post data. 
for testing I am emailing my self the POST data 
````
<?php
$url = $_SERVER['SERVER_NAME'];
$dataPOST = trim(file_get_contents('php://input'));
$xmlData = simplexml_load_string((string)$dataPOST);

$mail_body = "TEST EMAIL\r\n\r\n";

if(!empty($_POST)){$mail_body .= "POST DATA\r\n". var_export($_POST,true)."\r\n\r\n";}
if(!empty($xmlData)) $mail_body .= "XML DATA(simplexml_load_string)\r\n".var_export($xmlData,true)."\r\n\r\n";
if(!empty($dataPOST)) $mail_body .= "raw Data\r\n".$dataPOST."\r\n\r\n";
mail("syed@xyz.com", "Test", $mail_body);
````

and getting empty array. I have placed this code in handle_payment_update(); am I placing this inside a wrong function.? not sure where to grab the post data inside EE. can you please point me to right direction.. as how to get the post data from notify url on the event espresso,  
Sorry for the trouble.

**Comment by tn3rb** [comment]
**\EE_Offsite_Gateway::handle_payment_update()** (or your child class's version of it)  is called by  **\EE_PMT_Base::handle_ipn()**, which is called by **\EE_Payment_Processor::process_ipn()**.

That last method is most likely called from within the ESPRESSO_TXN_PAGE shortcode, from the 
**\EES_Espresso_Txn_Page::run()** method, but could also be called from **\EE_SPCO_Reg_Step_Payment_Options::_process_off_site_payment()**.

Both of those last methods simply pass the PHP $_REQUEST array as a parameter, which then gets passed along until it finally gets to the offsite gateway **handle_payment_update()** method, where it is the first parameter, which is called **$update_info** our offsite gateway classes.

Have you tried capturing the value of that parameter?

**Comment by syedshussaini** [comment]
I am getting the following value for the $update_info

```
Array
(
    [page_id] => 5
    [step] => payment_options
    [action] => process_gateway_response
    [selected_method_of_payment] => merchant_warrior_offsite
    [spco_txn] => 129
)
```

**Comment by mnelson4** [comment]
hey @syedshussaini, you can learn more about what the IPN data should look like by trying the skeleton new addon located here https://github.com/eventespresso/event-espresso-core/tree/master/tests/mocks/addons/new-payment-method. Just put that folder in your `wp-content/plugins` as it's a regular plugin. Activate it, then go to payment methods page and then activate the "New payment method Offsite". Notice that there is a setting for "Use Separate IPN". First try setting it to "Yes". Then make a payment using that payment method. When you go to pay with it, you're taken to a static html page, with a button to send a fake IPN. Try sending the fake IPN. You should see IPN data like this in your payment methods log: https://drive.google.com/file/d/0B2KCao4zFjaxOEFReEszNjEwZnc/view?usp=drivesdk. Notice that there's no "step", "action", or "spco_txn" in the IPN data.
(THen you can press back in your browser to the static html file, and then click the link to return to the thank you page). 
Now change the payment method's  "Use Separate IPN" setting to "No". Try making a payment with it. This time the static html page just has a link to send you back directly (no form to send a separate IPN). The payment data log you'll see will look something like this: https://drive.google.com/file/d/0B2KCao4zFjaxUlBERV9aNnM1ME0/view?usp=drivesdk. See it has the same "step", "action", "spco_txn" as you're seeing.
So the data you're seeing in the log shows that your payment method has been setup to NOT receive a separate IPN. So it sounds like you haven't set `$this->_uses_separate_IPN_request = true;` like I was suggesting. Please double-check that. You could just copy-and-paste the entire gateway class if you'd like us to verify you've set it up properly

**Comment by syedshussaini** [comment]
@mnelson4 I've set the uses_separate_IPN_request to true as you suggested.. here's the gateway class

```
<?php

if (!defined('EVENT_ESPRESSO_VERSION')) {
    exit('No direct script access allowed');
}


/**
 *
 * @package         Event Espresso
 * @subpackage
 * @author              Mike Nelson
 *
 */
class EEG_Merchant_Warrior_Offsite extends EE_Offsite_Gateway{

	protected $_merchant_uuid = NULL;

	protected $_gateway_url = 'http://syed-secure.xyz.dev';
    /**
     * All the currencies supported by this gateway. Add any others you like,
     * as contained in the esp_currency table
     * @var array
     */
    protected $_currencies_supported = array(
                    'USD',
                    'GBP',
                    'CAD',
                    'AUD',
                    'EUR',
                    'JPY',
                    'MYR',
                    'NZD',
                    'SGD',
				);

	/**
	 * @return EEG_Merchant_Warrior_Offline
	 */
	public function __construct() {
		$this->set_uses_separate_IPN_request( true );
		parent::__construct();
	}


	/**
     *
     * @param EEI_Payment $payment
     * @param type $billing_info
     * @param type $return_url
     * @param type $cancel_url
     */
    public function set_redirection_info($payment, $billing_info = array(), $return_url = NULL, $notify_url = NULL, $cancel_url = NULL) {
		
		$transaction = $payment->transaction();

        $order = array(
            'method'                =>'getCard',
            'merchantUUID'          =>$this->_merchant_uuid,
            'apiKey'                =>$this->_api_key,
            'transactionAmount'     =>number_format($payment->amount(),2),
            'transactionCurrency'   =>$payment->currency_code(),
            'transactionProduct'    =>$payment->TXN_ID(),
            'returnURL'             =>$return_url,
            'notifyURL'             =>$notify_url,
            'hashSalt'              =>$this->_hashSalt,
        );

		$order = apply_filters( "FHEE__EEG_Merchant_warrior__set_redirection_info__arguments", $order, $this );

		$payment->set_redirect_url($this->_gateway_url);
		$payment->set_redirect_args($order);
        return $payment;
	}

    /**
     *
     * @param array $update_info like $_POST
     * @param EEI_Transaction $transaction
	 * @return \EEI_Payment updated
	 * @throws \EE_Error
     */
	public function handle_payment_update($update_info, $transaction) {

		mail('syed@merchantwarrior.com' , 'update info' , print_r($update_info , true));

		
		if ( empty($update_info['status']) || empty( $update_info['transactionID']) ) {
			if ( isset( $update_info['transactionID']) ) {
				return $transaction->last_payment();
			} else {
				return null;
			}
		}
		$payment = $this->_pay_model->get_payment_by_txn_id_chq_nmbr( $update_info['transactionID'] );
		if ( !$payment instanceof EEI_Payment ) {
			$payment = $transaction->last_payment();
		}

		switch ( $update_info['status'] ) {
		case 'approved' :
			$status = $this->_pay_model->approved_status();
			$gateway_response = __( 'The payment is approved.', 'event_espresso');
			break;
		case 'declined' :
			$status = $this->_pay_model->declined_status();
			$gateway_response = __( 'The payment is declined.', 'event_espresso');
			break;	
		case 'pending' :
			$status = $this->_pay_model->pending_status();
			$gateway_response = __( 'The payment is pending.', 'event_espresso');
			break;
		} 

		if ( $payment instanceof EEI_Payment ) {
			$payment->set_status( $status );
		    $payment->set_gateway_response( $gateway_response);
			$payment->set_details( $update_info );
			$payment->set_txn_id_chq_nmbr( $update_info['transactionID']);
	   		$message_log = sprintf( __('updated payment', 'event_espresso') );		
			$this->log(array(
						'message' => $message_log,
						'IPN_data' => $update_info),
			   	   $payment
			);
		
		mail("syed@xyz.com" , "Debug Email" , print_r($payment, true));
		}

		do_action( 'FHEE__EEG_Merchant_Warrior_Offsite__handle_payment_update__payment_processed', $payment, $this);

		return $payment;
	}

}





// End of file EeG_Merchant_Warrior_Offsite.php

```

**Comment by syedshussaini** [comment]
hey.. I am getting the step/action/spco_txn in the IPN data when I have set the Use Separate IPN option to "yes" in the payment method "New payment method Office" : 
[https://drive.google.com/file/d/0BxTyAOUoblzEUmFjUldkSnZGMk0/view?usp=sharing](url)

**Comment by syedshussaini** [comment]
@mnelson4.. Here's the entire gateway class

```
<?php

if (!defined('EVENT_ESPRESSO_VERSION')) {
    exit('No direct script access allowed');
}


/**
 *
 * @package         Event Espresso
 * @subpackage
 * @author              Mike Nelson
 *
 */
class EEG_Merchant_Warrior_Offsite extends EE_Offsite_Gateway{

	protected $_merchant_uuid = NULL;

	protected $_gateway_url = 'http://syed-secure.xyz.dev';
    /**
     * All the currencies supported by this gateway. Add any others you like,
     * as contained in the esp_currency table
     * @var array
     */
    protected $_currencies_supported = array(
                    'USD',
                    'GBP',
                    'CAD',
                    'AUD',
                    'EUR',
                    'JPY',
                    'MYR',
                    'NZD',
                    'SGD',
				);

	/**
	 * @return EEG_Merchant_Warrior_Offsite
	 */
	public function __construct() {
		$this->set_uses_separate_IPN_request( true );
		parent::__construct();
	}


	/**
     *
     * @param EEI_Payment $payment
     * @param type $billing_info
     * @param type $return_url
     * @param type $cancel_url
     */
    public function set_redirection_info($payment, $billing_info = array(), $return_url = NULL, $notify_url = NULL, $cancel_url = NULL) {
		
		$transaction = $payment->transaction();

        $order = array(
            'method'                =>'getCard',
            'merchantUUID'          =>$this->_merchant_uuid,
            'apiKey'                =>$this->_api_key,
            'transactionAmount'     =>number_format($payment->amount(),2),
            'transactionCurrency'   =>$payment->currency_code(),
            'transactionProduct'    =>$payment->TXN_ID(),
            'returnURL'             =>$return_url,
            'notifyURL'             =>$notify_url,
			'hashSalt'              =>$this->_hashSalt,
        );
        $order['hash'] = md5(strtolower(md5($this->_api_passphrase).$this->_merchant_uuid.$order['transactionAmount'].$order['transactionCurrency']));
		$order['urlHash'] = md5(strtolower(md5($this->_api_passphrase).$this->_merchant_uuid.$return_url.$notify_url));
		
		$payment->set_redirect_url($this->_gateway_url);
		$payment->set_redirect_args($order);
        return $payment;
	}

    /**
     *
     * @param array $update_info like $_POST
     * @param EEI_Transaction $transaction
	 * @return \EEI_Payment updated
	 * @throws \EE_Error
     */
	public function handle_payment_update($update_info, $transaction) {

	mail('syed@xyz.com' , 'update info' , print_r($update_info , true));


	        if ( empty($update_info['status']) || empty( $update_info['transactionID']) ) {
			if ( isset( $update_info['transactionID']) ) {
				 return $transaction->last_payment();
			} else {
				return null;
                        }
		}
	        $payment = $this->_pay_model->get_payment_by_txn_id_chq_nmbr( $update_info['transactionID'] );
	        if ( !$payment instanceof EEI_Payment ) {
				       $payment = $transaction->last_payment();
		       }

			switch ( $update_info['status'] ) {
			       case 'approved' :
						 $status = $this->_pay_model->approved_status();
			             $gateway_response = __( 'The payment is approved.', 'event_espresso');
			            break;
			       case 'declined' :
			             $status = $this->_pay_model->declined_status();
				         $gateway_response = __( 'The payment is declined.', 'event_espresso');
				        break;  
				   case 'pending' :
			             $status = $this->_pay_model->pending_status();
		                 $gateway_response = __( 'The payment is pending.', 'event_espresso');
			            break;
			      } 

		    if ( $payment instanceof EEI_Payment ) {
				$payment->set_status( $status );
		        $payment->set_gateway_response( $gateway_response);
		        $payment->set_details( $update_info );
		        $payment->set_txn_id_chq_nmbr( $update_info['transactionID']);
		        $message_log = sprintf( __('updated payment', 'event_espresso') );      
		        $this->log(array(
			                    'message' => $message_log,
			                    'IPN_data' => $update_info),
			                    $payment
			              );

			    mail("syed@xyz.com" , "Debug Email" , print_r($payment, true));
		    }

		   do_action( 'FHEE__EEG_Merchant_Warrior_Offsite__handle_payment_update__payment_processed', $payment, $this);

		   return $payment;
	}

}

```
I have re installed all the plugins from scratch.. now one more strange thing happening - After making transaction using MW.. **I cant see the transaction in the logs**, but I can see in the transaction tab but as payment pending.

**Comment by mnelson4** [comment]
hi @syedshussaini ya on initial glance that looks ok. I'd need to run it and debug it myself as the next step but I'm not sure I'll manage to get around to doing that anytime too soon. Did you try using the skeleton offsite payment method that I suggested? Using that as a baseline to confirm what EE payment method is supposed to work and how logs are supposed to be logged might help

**Comment by syedshussaini** [comment]
Thanks @mnelson4..! & Yes I have tried using the skeleton method & got the whole process.. & I understand the I need to parse the XML returned by the MW gateway.. 
I am still unable to figure out in EE where/how to grab the data send by MW so that I can use it & parse the XML.. & may be pass it to the $update_info then.? 

another thing I noticed...
When I am setting the uses_separate_IPN to **false** 
- I am getting IPN data like this : https://drive.google.com/file/d/0BxTyAOUoblzEcFY4d21hT2pxclE/view?usp=sharing , without any txn data... 
- Receiving EE event registration emails saying **Pending payment **
- and I can see the transaction in the log which is showing two entries for each txn like this https://drive.google.com/file/d/0BxTyAOUoblzESmN1d0Fha0owQ3c/view?usp=sharing

But I am setting the uses_separate_IPN to **true**
- It's not adding anything to the log, even though i can see it in transactions https://drive.google.com/file/d/0BxTyAOUoblzERnlYdFYxN29ib1k/view?usp=sharing  
- I am not receiving any pending or approved Event registration emails etc..

**Comment by tn3rb** [comment]
> I am still unable to figure out in EE where/how to grab the txn data sent back from MW so that I can use it & parse the XML.. & may be pass it to the $update_info then.?

you don't have to do that... the $update_info var **IS** the $_REQUEST data, so anything sent from MW via POST or GET will be in the $update_info array

you definitely want **uses_separate_IPN** to be set to **true**

I wonder if your problem is this bit of code near the top of handle_payment_update()

```
if ( isset( $update_info['transactionID']) ) {
    return $transaction->last_payment();
}
```

you shouldn't be returning the payment if you have not updated it yet unless the IPN data is missing or there is something wrong with it. It looks to me like you may have copied that code over from the EEG_Paypal_Standard class. What if you try replacing this block of code:

```
           if ( empty($update_info['status']) || empty( $update_info['transactionID']) ) {
            if ( isset( $update_info['transactionID']) ) {
                 return $transaction->last_payment();
            } else {
                return null;
                        }
        }
```

with this:

```
           if ( empty($update_info['status']) || empty( $update_info['transactionID']) ) {
                 return $transaction->last_payment();
            } else {
                return null;
           }
```

and as well, your switch statement for the $update_info['status'] has no **default** case, so if the incoming status is something different than the three options you have, then the **$status** var does not get set, which could cause problems.

what about changing:

```
                   case 'pending' :
                         $status = $this->_pay_model->pending_status();
                         $gateway_response = __( 'The payment is pending.', 'event_espresso');
                        break;
                  } 
```

to:

```
                   case 'pending' :
                   default :
                         $status = $this->_pay_model->pending_status();
                         $gateway_response = __( 'The payment is pending.', 'event_espresso');
                        break;
                  } 
```

**Comment by tn3rb** [comment]
One other question...
is "transactionID" a property that is set by MW and then sent back with their response ?
or do you have to set that value as part of the $order array that gets passed to EE_Payment::set_redirect_args() ?

**Comment by syedshussaini** [comment]
@tn3rb...
**transactionID** is property set by MW & sent back in the response xml ...  here's the sample response : 

````
<mwResponse>
<responseCode>0</responseCode>
<responseMessage>Transaction    approved</responseMessage>
<transactionID>1-918490ae-9a1c-11de-8649-000c29753ad4</transactionID>
<authCode>1</authCode>
<authMessage>Approved</authMessage>
<authResponseCode>0</authResponseCode>
<custom1>Custom Field   1</custom1>
<custom2>Custom Field   2</custom2>
<custom3>Custom Field   3</custom3>
<customHash>e1af7c6a17758ef2907a50c96fa56d28</customHash>
<hash>082949a8dfacccda185a135db425377b</hash>
</mwResponse>
````

**Comment by mnelson4** [comment]
it sounds like MW isn't sending an IPN, or sending it to the transactions page (where IPNs should go).
Regardless of how you've set up your gateway, whenever a request goes to the transaction page that has the `$_REQUEST['e_reg_url_link']` set, it should be creating a log for the request.
So maybe MW isn't sending an IPN, sending the IPN to the wrong URL, or sending it without the needed 'e_reg_url_link' part of the querystring.
To see if they're sending the IPN but leaving off the "e_reg_url_link", you can open up shortcodes/espresso_txn_page/EES_Espresso_Txn_Page.shortcode.php and edit the `run` method, change it to 

```
public function run( WP $WP ) {
		if ( EE_Registry::instance()->REQ->is_set('e_reg_url_link' )){
			$this->_current_txn = EE_Registry::instance()->load_model( 'Transaction' )->get_transaction_from_reg_url_link();
		} else {
			$this->_current_txn = null;
		}
//		if ( $this->_current_txn instanceof EE_Transaction ) {
			//EE_Registry::instance()->load_helper( 'Debug_Tools' );
			//EEH_Debug_Tools::log( __CLASS__, __FUNCTION__, __LINE__, array( $this->_current_txn ), true, 	'EE_Transaction: ' . $this->_current_txn->ID() );
			$payment_method_slug = EE_Registry::instance()->REQ->get( 'ee_payment_method', NULL );
			if( $payment_method_slug ) {
				$payment_method = EEM_Payment_Method::instance()->get_one_by_slug( $payment_method_slug );
			}else{
				$payment_method = null;
			}
			/** @type EE_Payment_Processor $payment_processor */
			$payment_processor = EE_Registry::instance()->load_core('Payment_Processor');
			$payment_processor->process_ipn( $_REQUEST, $this->_current_txn, $payment_method );
			//allow gateways to add a filter to stop rendering the page
			if( apply_filters( 'FHEE__EES_Espresso_Txn_Page__run__exit', FALSE ) ){
				exit;
			}
//		}

	}
```

This will make it log absolutely every request to that url (even if you visit it in your browser without setting any $_REQUEST parameters at all).
Then verify all requests to that transaction page are getting logged by visiting the page directly. Do you see any logs created when you visit that transaction page directly in your browser?

**Comment by nerrad** [comment]
@syedshussaini any update on this?

**Comment by theshane** [comment]
I am having the same issue. I am even using postman to simulate a post and it does not work. I have also put debug code in the handler and it is not outputting anything. I paid for support on this but they were of no help. This issue caused a huge problem for us over the weekend so a solution would be appreciated.

**Comment by joshfeck** [comment]
@theshane We reviewed your custom gateway add-on and let you know about the error in the `handle_payment_update()` method, specifically this:

`if( !  isset( $update_info[ 'gateway_txn_id' ] ) ){
	return NULL;
}`

That was not helpful? Did you try fixing the code there?

**Comment by theshane** [comment]
Hi, I re-read my message above and changed the wording. I appreciate you pointing that out but that code is directly from your own skeleton and it used to work before. But beyond that I am building my own POST and including that in my request so it should go through.

**Comment by theshane** [comment]
I have also added a WP_MAIL line in there before that If and I do not get mail nor can I see the var dump in the body anywhere. So it is almost like the handler never gets run.

**Comment by joshfeck** [comment]
It's true that it's directly from the skeleton, but the skeleton is just that, a skeleton. You actually need to change that variable to match something from the gateway response. Otherwise it will return null and the rest of the code in that method will not run.

**Comment by theshane** [comment]
Ok, I probably left out a point before, which might help this out. My code does the post not the payment provider. So I constructed my post to have all of the vars needed.

**Comment by theshane** [comment]
Based on the code, this is what I think should **work in theory**:

post to notify_url with status and gateway_txn_id should mark the payment complete no matter where it is coming from.

**Comment by theshane** [comment]
Ok, I finally got it to work by removing:

`&& $gateway->handle_IPN_in_this_request(
						\EE_Registry::instance()->REQ->params(),
						true
					)`

From the IF statement on line 86 in the Txn_Page shortcode.

I would rather fix it in my plugin though, how might I make this pass in my plugin so I do not have to alter core code?

Thanks, this thread was very helpful.

**Comment by mnelson4** [comment]
You can change your gateway's `_uses_separate_IPN_request` property to `true` in the constructor., meaning that it should watch to payment notifications sent to the transaction page (the default is to ignore those, and instead only watch for payment data when the user is redirected from the gateway's offsite website). 

We have that so we can avoid race conditions for gateways that can send a separate IPN and send payment data along with the user when they return from offsite. 

On a related note, You probably noticed the skeleton gateway does a bit of magic in its implementation of the function `uses_separate_IPN_request()` so that it can optionally handle payment notifications sent to the transaction page, or when sent along with the user as they return from being offsite. You should make sure you've removed that overriding method because you probably don't want that behaviour: it sounds like you just want the value of `_uses_separate_IPN_request` to always be `true`.

Does that work for you, without needing to change EE core?

**Comment by theshane** [comment]
That did the trick.
So, the question is why was it working before and it stopped after an update? Perhaps this was a bug that was inadvertently fixed or something.

For anyone who has the same issue, I set set_uses_separate_IPN_request to true:

`public function __construct() {
		//if the gateway you are integrating with sends a separate instant-payment-notification request
		//(instead of sending payment information along with the user)
		//set this to TRUE
		$this->set_uses_separate_IPN_request( true ) ;
		parent::__construct();
	}
	`

**Comment by mnelson4** [comment]
> So, the question is why was it working before and it stopped after an update?
That setting was introduced not too long ago (probably a year iirc) because we were having issues where some gateways (most notably PayPal) sometimes sends payment information via a separate request AND along with the use, which would cause race conditions (transactions getting partially updated by one request and then simulatneously partially updated by the other; payment messages going out twice; it was a hard-to-debug mess). So my guess is that the version of EE you were using before didn't have that setting maybe?

But regardless, glad that fixed it. Good hunting down the problem yourself too, but sorry for the inconvenience.
