### ISSUE TITLE
How to filter event Search wia Event Name?

### ISSUE THREAD

**Issue by rvpatel** [eventespresso/event-espresso-core#1445]
$where['Posts.post_title'] = array('LIKE', '%Event%');  -  i assume and try but give me valid code.

Please help me how to search for data using the event title?

https://github.com/eventespresso/event-espresso-core/blob/master/docs/G--Model-System/model-query-params.md#0-where-conditions

**Comment by rvpatel** [comment]
$result = EEM_Event::instance()->get_all( array( array( 'EVT_name' => array('LIKE', '%Test%') ) ) );

**Comment by rvpatel** [comment]
Can you help how many event statuses & how to filter with this.

**Comment by Pebblo** [comment]
Hi Ravikumar,

The answer for this is the same answer I gave you when I provided the above example in the [EE Slack channel](https://eventespresso.com/2019/07/community-chat-group/).

You need to read through the model documentation to understand how it works and what to do:

https://github.com/eventespresso/event-espresso-core/tree/master/docs/G--Model-System

You can also view the code within Event Espresso for live examples if need be but we (support) will not provide snippets of codes for you use cases, the documentation covers how to filter the details using the models.
