### ISSUE TITLE
Cannot reach v4.8.33 endpoint

### ISSUE THREAD

**Issue by PunchRockgroin** [eventespresso/event-espresso-core#145]
We are trying to implement a custom app to use the new v4.8.33 endpoint for registration check in, however, we cannot seem to reach it as our app returns 404 on /ee/v4.8.33/registrations/{REG_ID}/toggle_checkin_to_datetime/{DTT_ID}

We are certain we are up to date on the plugin as we can see core/libraries/rest_api/controllers/rpc/Checkin.php and the version the system shows is ee_version
4.8.33.p. We can also see the served_core_versions contains 4.8.33 at https://fcbr.org/wp-json, however, the main namespace remains ee/v4.8.29

**Comment by mnelson4** [comment]
try adding `define( 'EE_REST_API_DEBUG_MODE', true );` in your `wp-config.php` file. I suspect I forgot to make sure the EE routes get refreshed on updates

**Comment by mnelson4** [comment]
yeah I just reproduced locally- when I upgraded from anything before 4.8.29 to 4.8.33, and didn't define `EE_REST_API_DEBUG_MODE`, I got the same problem. Working on a fix for the next release

**Comment by PunchRockgroin** [comment]
Yep, that works for now. Thanks!

**Comment by mnelson4** [comment]
Thanks for reporting this. I have a fix that will hopefully be merged into 4.8.34

**Comment by PunchRockgroin** [comment]
Sorry, to cap this, the developer docs at http://developer.eventespresso.com/docs/ee4-rest-api-rpc-style-endpoints/ should be updated looks like the Check In route should be toggle_checkin_**for**_datetime:

`/ee/v4.8.33/registrations/{REG_ID}/toggle_checkin_to_datetime/{DTT_ID}`
should be
`/ee/v4.8.33/registrations/{REG_ID}/toggle_checkin_for_datetime/{DTT_ID}`

**Comment by mnelson4** [comment]
thanks!
