### ISSUE TITLE
Local Payment Gateway Submits Form From JS but Gets Blocked by _billing_form_is_valid

### ISSUE THREAD

**Issue by tenxor105** [eventespresso/event-espresso-core#148]
Hi,

A local payment gateway requires the following code. I have already written an onsite payment method plugin but encountered a problem.
```

<form id="2c2p-payment-form" action="./payment_non3d.php" method="POST">
    <input type="text" data-encrypt="cardnumber" maxlength="16" placeholder="Credit Card Number"><br/>
    <input type="text" data-encrypt="month" maxlength="2" placeholder="MM"><br/>
    <input type="text" data-encrypt="year" maxlength="4" placeholder="YYYY"><br/>
    <input type="password" data-encrypt="cvv" maxlength="4" autocomplete="off" placeholder="CVV2" ><br/>
    <input type="submit" value="Submit">
</form>

<script type="text/javascript" src="https://demo2.2c2p.com/2C2PFrontEnd/SecurePayment/api/my2c2p.1.6.6.min.js"></script>
<script type="text/javascript">
    My2c2p.SubmitForm("2c2p-payment-form", function(errCode,errDesc){
        if(errCode!=0){ 
            alert(errDesc);
        }
    });
</script>
```

First, I got to add data-encrypt tags in the credit card fields. Then JS would pick them up then add another field to the post body called encryptedCardData which is a long random string (to be decoded later in the payment gateway server). SubmitForm submits the form but upon doing so, some PHP error says that the form was not submitted due to "_billing_form_is_valid."

Can you please advise what is the correct approach to make this work? Thanks.

**Comment by mnelson4** [comment]
So this is an ONsite gateway right? Ie, this form will be submitted to the same server that showed the content right?

Normally you, the gateway integration developer, wouldn't declare the form tag, usually Event Espresso does that. So if you're overriding where the form is being submitted that's tinkering with EE's normal onsite payment handling and likely to break things. So ideally your code shouldn't be creating the form tag.

 And actually, you shouldn't be directly generating the input html, but instead you just build the billing form like documented here: http://developer.eventespresso.com/docs/ee4-payment-method-development/#generate_new_billing_form. When generating the payment method's billing form, you'll probably want inputs for cardnumber, month, year, and maybe one for encryptedCardData but have it be an `EE_Hidden_Input`.
When creating those EE form input objects, you can pass in the "html_other_attributes" as a string to specify the unusual `data-encrypt` attribute, and then set the `html_name` to be an empty string.

**Comment by tenxor105** [comment]
Hi, have read your documentation and actually did some coding already.

First issue - the html_other_attributes for EE_Credit_Card_Month_Input and EE_Credit_Card_Year_Input don't work. Can you please check that? My solution to this was to use EE_Text_Input instead but would be great if I could make it work for select tags.

Second issue - to clarify my original question, I have written the following form to generate billing form.
```
public function generate_new_billing_form( EE_Transaction $transaction = null ) {
		$form_name = '2C2P_Billing_Form';
		$form_args = array(
			'name' => $form_name,
			'html_id' => 'ee-2c2p-billing-form',
			'subsections' => array(
				'credit_card' => new EE_Credit_Card_Input( 
					array( 
						'html_class' => 'ee-billing-qstn ee-2c2p-pay-billing-form-credit-card',
						'required' => true, 
						'html_label_text' => __('Card Number', 'event_espresso'),
						'html_other_attributes' => 'data-encrypt="cardnumber" maxlength="16"',
					)
				),
				'exp_month' => new EE_Text_Input(
					array( 
						'html_class' => 'ee-billing-qstn ee-2c2p-pay-billing-form-exp-month',
						'required' => true, 
						'html_label_text' => __( 'Expiry Month', 'event_espresso' ),
						'html_other_attributes' => 'data-encrypt="month"',
					)
				),
				'exp_year' => new EE_Text_Input( 
					array( 
						'html_class' => 'ee-billing-qstn ee-2c2p-pay-billing-form-exp-year',
						'required' => true, 
						'html_label_text' => __( 'Expiry Year', 'event_espresso' ),
						'html_other_attributes' => 'data-encrypt="year"',
					)
				),
				'cvv' => new EE_CVV_Input( 
					array( 
						'html_class' => 'ee-billing-qstn ee-2c2p-pay-billing-form-card-cvv',
						'required' => true, 
						'html_label_text' => __( 'CVV', 'event_espresso' ),
						'html_other_attributes' => 'data-encrypt="cvv" maxlength="4"',
				
					)
				),
				'encryptedCardInfo' => new EE_Hidden_Input( 
					array( 
						'html_class' => 'ee-2c2p-pay-billing-form-card-encryptedCardInfo',
						'html_value' => '',
					)
				),
			),
			'exclude' => array( 'first_name', 'last_name', 'email', 'address', 'address2', 'city', 'zip', 'phone', 'state', 'country'),
		);
		$billing_form = new EE_Billing_Attendee_Info_Form( $this->_pm_instance, $form_args );

		return $this->apply_billing_form_debug_settings( $billing_form );
	}
```

Then, since the payment gateway requires JS to submit the form, I have created a JS object (patterned from your Stripe JS and Braintree JS files) that has the following method:

```
set_SPCO_submit_reg_form_listener : function() {
			SPCO.main_container.on( 'process_next_step_button_click', function( event, spco_submit_button ) {
				EEA_2C2P_PM.spco_submit_button = spco_submit_button;
				var my2c2p_form = $('#ee-spco-payment_options-reg-step-form');
				if ( EEA_2C2P_PM.submitted === false && SPCO.form_is_valid === true && my2c2p_form.length > 0) {
					SPCO.allow_submit_reg_form = true;
					My2c2p.submitForm( 'ee-spco-payment_options-reg-step-form', function(errCode, errDesc){
						if(errCode != 0) {
				            alert(errDesc+" ("+errCode+")");
				        }
					});
				}
			} );
		},
```
When user clicks to submit the form, the JS above submits the form but I get the following error message:

An error has occurred:
One or more billing form inputs are invalid and require correction before proceeding. 
Card Number: This field is required.
Expiry Month: This field is required.
Expiry Year: This field is required.
CVV (What's this?): This field is required.
EE_SPCO_Reg_Step_Payment_Options - _billing_form_is_valid - 1254

So, it seems that PHP doesn't get the fields submitted by the JS. Any suggestions to make this work please?

**Comment by mnelson4** [comment]
> First issue - the html_other_attributes for EE_Credit_Card_Month_Input and EE_Credit_Card_Year_Input don't work. Can you please check that? My solution to this was to use EE_Text_Input instead but would be great if I could make it work for select tags.

you're right, we hadn't ever used "other_html_attributes" on any input other than text inputs. I've made a ticket to address that, should be quickfix. Actually if you want to try branch BUG-9533-most-display-strategies-ignore-other-html-attributes, it should allow all the inputs to use the "other_html_attributes".

Also instead of using `EE_Billing_Attendee_Info_Form` and excluding most of the fields, I'd suggest you just use `EE_Billing_Info_Form`.

> So, it seems that PHP doesn't get the fields submitted by the JS. Any suggestions to make this work please?

Yeah I'm pretty sure the idea behind the 2C2P JS is to *remove* those fields with sensitive credit card data from them before they're sent to the server. Instead, I assume they send that data directly to their server.
So what you need to do is make the billing form not core if those inputs are missing, but only server-side.

You could do this by creating a new billing form class, make it extend `EE_Billing_Info_Form`, and then override its `_validate` method so that it excludes or ignores those inputs removed by the JS. Specifically this section of the documentation might help: http://developer.eventespresso.com/docs/ee4-forms-system/#Form-wide_Validation. Eg, maybe something like this:

```
class 2C2P_Billing_Form extends EE_Billing_Info_Form {
  function _validate() {
    $this->exclude( array( 'credit_card', 'exp_month', 'exp_year', 'cvv' ) );
    return parent::_validate();
  }
}
```

I haven't tested that.

**Comment by tenxor105** [comment]
Hey, just dropped by to say your input was very helpful. Extending the billing form and overriding the validate function was the way to go! Thanks brother! I'll close this question now.

**Comment by mnelson4** [comment]
Right on! Feel free to give us some stars at https://wordpress.org/support/view/plugin-reviews/event-espresso-decaf
