### ISSUE TITLE
Convert Classes and HOCs into Presentational Components and Functional Hooks

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#1489]
## Issue Overview
Currently there is a huge issue with re-renders and loading time that is exacerbated by the large stacks of higher-order-components (HOCs) used to wrap regular components in order to provide props. Much of this hierarchy was laid out prior to the introduction of React Hooks, so the only way to provide most data was via props, where shared state needed to be "raised up" to the highest component in the hierarchy and then allowed to "trickle down". Coupled with overly complex model objects this caused a LOT of re-renders.

I have been working on extracting the logic currently in HOCs and moving that into custom hooks that can now be implemented exactly where they are needed instead of having to pass props down through multiple components. As well, I have been trying to separate our components into those that are primarily presentational (JSX) versus those that are functional and process/retrieve data.

**Comment by joshfeck** [comment]
Does part of this include refactoring to implement `useDispatch` and `useSelect` hooks in the TAM composition to eliminate multiple HOCs?

Was noted in https://github.com/eventespresso/event-espresso-core/projects/4#card-23222769
