### ISSUE TITLE
In useTicketPriceCalculatorFormDecorator, ticket price calculators sorted by price type order and id but that was not exposed via the decorator to the objects in the calculators

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1502]
@nerrad noted in review #1236

> In useTicketPriceCalculatorFormDecorator I noted that even before the refactor here, there ticket price calculators sorted by price type order and id but that was not exposed via the decorator to the objects in the calculators. This should be reviewed and can be a part of the work done for implementing price ordering in the price calculator.

> This is actually a regression because the original code passed the price type.

Executive decision from @br3nt in slack was to order by `PRC_order`... so when this issue is done we'll need to make sure that logic is consistent everywhere else prices are used.

**Comment by tn3rb** [comment]
addressed by #1608
