### ISSUE TITLE
stale prices prop being used for the updateTicketPrice hook, without useRef

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1503]
Originally brought up in the #1236 review by @nerrad:

> In EditorTicketDetails there's some issues I had with stale prices prop being used for the updateTicketPrice hook. I resolved the issue for now using the useRef hook to ensure the hook is always using the latest prices passed in as a prop. However it'd be good to investigate this further to figure out why I need to use useRef.

**Comment by tn3rb** [comment]
fixed as part of #1608
