### ISSUE TITLE
copyEventDate HOC improvements

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1506]
Darren noted:

> I modified copyEventDate to be a HOC (see with-copy-event-date.js) and it now exposes a copyEventDate callback via withDispatch. However I'm not sure that we should be passing through the tickets related or the event to the datetime being copied and instead just registry.select (which is available on withDispatch via the third argument) to select the related event and related tickets. That would: 1. Make the hoc more reusable as a general copy date handler and 2. make it less fragile due to depending arguments for the relations which may get stale (depending on implementation).

**Comment by tn3rb** [comment]
completed as part of #1589
