### ISSUE TITLE
Fix issue with `createRelation` action creator

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1511]
Darren reported:

> `createRelation` action creator should first check there is not already an existing relation in the state for the given data and if there is, do not queue the addition of the relation!

**Comment by manzoorwanijk** [comment]
The UI already reflects if there is an existing relation between any two entities. which you can only revert. For example, if a ticket is related to a datetime, it will be visible in Ticket Assignment Manager, where you can only remove the relation, not add it again. So, I think that additional check is unnecessary.

**Comment by manzoorwanijk** [comment]
As discussed with @tn3rb this is really not needed. React has one way data binding which is always reflected in the UI. So there won't really be such an instance where that happens.
