### ISSUE TITLE
Fix issue where new price modifiers are listed at the top of prices

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1512]
Darren reported:

> ticket price calculator - newly added price modifiers unexpectedly appear towards the top of the list, whereas I think they should appear at the end. I think this could be rectified by initially setting the price type to nothing, as well as initially having a "please select price type" value in the price type select input options for new price modifiers (but remove that as soon as a selection is made). This would prevent the list ordering from moving new modifiers from the bottom.

**Comment by tn3rb** [comment]
completed as part of #1589
