### ISSUE TITLE
want to remove the alt text below the image 

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [eventespresso/event-espresso-core#152]
http://realwaymedia.info/aiwa-stage2/events/event-registration/?ee=88

Book Cover image // want to remove this 

This is a caption

Any help ?

**Comment by nerrad** [comment]
That has nothing to do with Event Espresso.  The caption for the image is being added by your theme.

**Comment by PrafullaKumarSahu** [comment]
Can you please tell , where can I configure 
```
echo espresso_format_content($event_desc); 
```
 of registration_page_display.php page
