### ISSUE TITLE
Add PropTypes everywhere that they can be added consistently

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1521]
In many cases, defaultProps can be provided via PropTypes instead of destructured props.

**Comment by tn3rb** [comment]
pushed a new base branch for the EDTR named: **EDTR/refactor-master**

here's a list of components that you can start on:

- /assets/src/components/ui/entity-list/index.js
- /assets/src/components/ui/image/espresso-icon.js
- /assets/src/components/ui/price-type-sign/price-type-sign.js
- /assets/src/components/ui/responsive-table/{any component missing prop types}
- /assets/src/editor/events/dates-and-times/editor-date/{any component missing prop types}
- /assets/src/editor/events/ticket-assignments-manager/{any component missing prop types}
- /assets/src/editor/events/tickets/editor-ticket/{any component missing prop types}
