### ISSUE TITLE
Refactor/Replace EntityActionMenuItem

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1523]
After replacing the `FHEE__EditorDates__EditorDateSidebar__SidebarMenuItems` filter with the slot/fill pattern we should investigate ways to restrict what components can be injected into entity action menus.

see: https://github.com/eventespresso/event-espresso-core/projects/4#card-22142568

**Comment by tn3rb** [comment]
completed as part of #1589
