### ISSUE TITLE
Review prop usage and ensure we're not passing through props unnecessarily through intermediary components

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1524]
(taking advantage of withSelect and withDispatch to grab state where necessary. For instance, it may be beneficial to introduce state for things like: current_filtered_date_ids (for the chained ticket results), selected_date/ticket (for actions such as copy and trash date and future ordering behaviour). Reducing the amount of props being passed through intermediaries helps cut down on the number of unnecessary renders due to prop changes.

**Comment by tn3rb** [comment]
completed as part of #1589
