### ISSUE TITLE
need to modify event_desc 

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [eventespresso/event-espresso-core#153]
Can you please tell , where can I configure

```
echo espresso_format_content($event_desc); 
```

of registration_page_display.php page

which page data is displayed here and where it is set ?

**Comment by nerrad** [comment]
Hi there,

`registration_page_display.php` is not a template file bundled with Event Espresso 4 and `espresso_format_content` is not a function in Event Espresso 4.  This repository is for Event Espresso 4 development and it _looks_ like your question is more directed to Event Espresso 3 usage.

Just to be sure I did a quick search using the github search box for this repo to see if anything turned up:

- `registration_page_display.php` -> https://github.com/eventespresso/event-espresso-core/search?utf8=%E2%9C%93&q=registration_page_display.php
- `espresso_format_content` -> https://github.com/eventespresso/event-espresso-core/search?utf8=%E2%9C%93&q=espresso_format_content

**Comment by nerrad** [comment]
You might want to try the [Event Espresso Support Forums](eventespresso.com/support/forums) or the [User Documentation](https://eventespresso.com/support/documentation/)

**Comment by PrafullaKumarSahu** [comment]
yes, my question is related to EE 3 .

**Comment by PrafullaKumarSahu** [comment]
your Event Espresso Support Forums  link is a 404 page ?

**Comment by nerrad** [comment]
sorry, a typo. it's been corrected.

**Comment by PrafullaKumarSahu** [comment]
I have just posted it on https://eventespresso.com/topic/need-some-change-in-registration-page/
