### ISSUE TITLE
Can you please tell me where I can modify / customize [caption] shorcode ?

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [eventespresso/event-espresso-core#154]
I got the problem . It is because 

```
[caption id="attachment_2103" align="alignnone" width="200"]<a href="http://realwaymedia.info/aiwa-stage2/wp-content/uploads/2016/03/pid_24063.jpg"><img class="wp-image-2103 size-medium" src="http://realwaymedia.info/aiwa-stage2/wp-content/uploads/2016/03/pid_24063-200x300.jpg" alt="Book Cover image" width="200" height="300" /></a> This is a caption[/caption]
```

using the image alt attribute as caption and there is another caption .

Can you help me to remove this caption generated from image alt attribute ?

**Comment by nerrad** [comment]
`[caption]` is NOT a shortcode found in Event Espresso 4 (which is this repository).  Please do at least a bit of checking before you post an issue.  Thanks.

**Comment by nerrad** [comment]
Also, please read the document (README.md) found https://github.com/eventespresso/event-espresso-core before posting another issue.  Any further issues posted by you `PrafullaKumarSahu` that are not related to this repository and follow the guidelines in that doc will be simply closed with no response.

**Comment by PrafullaKumarSahu** [comment]
Sorry for that, I got it that, it is not belongs to EE, sorry for that.
