### ISSUE TITLE
Broken HTML when adding a registration via the admin

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#1553]
**Describe the bug**
I noticed that the "New @ Event Espresso" section is out of place when adding a registration via the admin.

**To Reproduce**

Try adding a new registration to an expired event. You should see something like this:
![‹ Events by Espresso — WordPress 2019-08-28 14-41-38](https://user-images.githubusercontent.com/235315/63959273-1083b080-ca49-11e9-9394-8057f70e1608.jpg)

**Expected behavior**

The "New @ Event Espresso" section should be aligned to the right side of the screen. Like this:
![image](https://user-images.githubusercontent.com/235315/63959339-2f824280-ca49-11e9-91db-d4c4c0f526f8.png)

**Screenshots**
See above.

**Environment:**
 - Version of Event Espresso:  4.10.1
 - Version of WordPress: 5.2.2
 - Browser FF and Chrome

**Comment by joshfeck** [comment]
This is no longer an issue because #1537 was merged into master
