### ISSUE TITLE
Verify Authorize.net integration unaffected by infrastructure changes

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/event-espresso-core#1569]
## Issue Overview

Authorize.net is moving off Akamai (they're switching the API endpoints to a public network and website and portal to Cloudflare). Our integration should not need any changes, but we should verify that. Here is their FAQ page: https://support.authorize.net/s/article/Authorize-Net-Network-Change-FAQ?utm_campaign=19Q4+AkamaiEOL%2FMigrationToPCN+Notice+Developer&utm_medium=email&utm_source=Eloqua

Importantly: between October 15 2019 and February 10 2020 we should retest all our the Authorize.net integrations on their sandbox servers to verify they still work

We don't specifically bundle a certificate in our integration, so merchants don't have to worry about re-uploading a new certificate or anything.

The only thing site owners will need to do is make sure that if they were previously whitelisting Authorize.net's IP addresses, they'll need to whitelist the new ones. Their FAQ page says

> I use a firewall that needs IP Addresses to white list outbound and/or inbound connections. What do I need to do?

> If your solution uses a firewall to filter outbound and/or inbound connections, make sure to white list IP Address provided in our support article: Authorize.Net Domains and IP Addresses

See https://support.authorize.net/s/article/Authorize-Net-Domains-and-IP-Addresses

We could probably make a blog post about this too, just to inform our users.

**Comment by joshfeck** [comment]
We should remove the "Server" setting in the AIM gateway. (it's the setting that lets you toggle between Akamai and "deprecated" options)

**Comment by joshfeck** [comment]
@mnelson4 can the "Server" setting in the AIM gateway's settings be removed?
