### ISSUE TITLE
One questions answer overwrites others randomly when registering. 

### ISSUE THREAD

**Issue by jonathan-dejong** [eventespresso/event-espresso-core#157]
### Is this a bug report?
- [x] yes
- [ ] no
### What branch did this occur in?

Master (v 4.8.35.p)
### What version of WordPress is on the site this issue happened?

4.4.2
### Outline the steps to reproduce

Unclear as it happens at random. But the client has a few custom questions in the personal question group in which an answer to one question overwrites the answers to some of the others. 

So I suppose to try to reproduce it one would have to have an event with personal questiongroup required and some required custom questions in this (textinputs) and hammer out a few dozen registrations. Some might have answers overwritten. The custom questions should be text inputs and required. The ID's of our questions is:
11. (text input) - This is the field that overwrites the other two at random. Admin label: Kundens referens ID
12. (text input) Admin label: Kommun/organisation
27. (text input) Admin label: befattning-om-privatperson-skriv-privat
15. (text input) Admin label: Övriga önskemål till exempel kost

Sometimes it overwrites all other questions, sometimes only one or two. 
### Please include any screenshots ar screencasts that can help illustrate the issue (if possible).

https://dl.dropboxusercontent.com/u/10298919/EE-reg-error.jpg
### Please include any links to the page(s) demonstrating this issue (if possible).

Not possible without giving admin access.

**Comment by jonathan-dejong** [comment]
I've checked the changelog for later versions changes/fixes but can't really see anything related.

**Comment by nerrad** [comment]
Thanks for checking the changelog to see if anything related might have fixed.  However, if possible it'd still be good to setup a test site with a copy of this site's db and upgrade to the latest version of EE and see if the issue still persists.  We only troubleshoot/attempt to reproduce on the latest versions of EE.

**Comment by nerrad** [comment]
any ideas here @mnelson4 or @tn3rb ?

**Comment by jonathan-dejong** [comment]
Yeah I will also update the live site to the latest version as soon as I can.
We have a staging-site which is basically a copy of the live one. So I'll also sync up the DB there and do some testing.

**Comment by mnelson4** [comment]
hey @jonathan-dejong regarding the screenshot: the problem might be just in how the info is being displayed on that page in the admin. Can you also give a screenshot of the related rows in the database ? (this query would do the trick: `SELECT * FROM wp_esp_answer where REG_ID=$reg_id` where `$reg_id` is the ID of the registration) That would help us to know if the data in the database is incorrect, or if it's just the UI that's somehow making it just appear incorrect

**Comment by tn3rb** [comment]
@jonathan-dejong

Another possibility for something that could cause this, although it doesn't appear to be the case from the details you have provided so far, is that the way our questions and question groups work, you can NOT reuse the same question in multiple question groups within the same registration form. 

So for example, if you took our email question, which is normally part of the Personal Information Question Group, and added that question to another question group, then the answers from the second instance of that question in the registration form would overwrite, the first instance. 

The simple fix is to just create a new question with it's own unique ID and use that for the second email question. Again, it doesn't appear that this is the case for your site. That said, the only reports we have had of questions overwriting answers for other questions, is when the same question has been used multiple times within the same registration form as I have detailed above.

**Comment by jonathan-dejong** [comment]
Hi,

@mnelson4 yeah they're the same in the DB as well: https://dl.dropboxusercontent.com/u/10298919/Sk%C3%A4rmavbild%202016-04-18%20kl.%2014.25.49.png

@tn3rb I get that :) In this case you're right tho. we're not using the same questions in multiple groups for the same registrations. 

I'm currently updating the staging site and am going to try some registrations to see if it replicates there. Hard to tell tho.
