### ISSUE TITLE
Document statuses

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/event-espresso-core#1570]
## Issue Overview

The app developers were a bit confused about where to find statuses (for registrations, specifically) and what possible values the `STS_ID` could be. That's pretty understandable as I don't think we've documented it too much (probably because it was originally meant to be a bit dynamic, which is why it has its own table.)

Regardless of what our previous or current plans are, it would probably be good to help other developers understand the current reality with statuses. We probably should help them understand:

* what are the expected values for `STS_ID` on registrations, messages, payment, transactions
* what are the meanings of the various statuses, and when we'd expect to see them in use (eg `TAB` might be a bit of a gotcha, I believe we set transactions to that when the user goes offsite to pay)
* that some of the statuses in `esp_status` are deprecated (eg events and emails)
* how to get a pretty string of the status

I'm inclined to make a documentation page dedicated to it, and link to it from the relevant models and REST API docs. 
It might also make sense for this to be part of the REST API model schema, but I'm inclined to tackle that after we quickly put up a docs page.

## Bug report or feature request?

* [ ] Bug
* [ ] Feature
* [ ] Neither
* [x] Documentation

@tn3rb do you have any input on what we could quickly do to improve this situation (you can optionally include long term thoughts, but I'm hoping to add something in 20 minutes or so.)

**Comment by mnelson4** [comment]
I'd like to take 30 minutes or so to document the current state of EE statuses. This should help both new hires and 3rd party devs. wdyt @joshfeck ?

**Comment by joshfeck** [comment]
Sounds good, thanks.

**Comment by mnelson4** [comment]
This was done on #1740
