### ISSUE TITLE
Addon Development question: How do database tables get created?

### ISSUE THREAD

**Issue by ammist** [eventespresso/event-espresso-core#158]
Hi there,

I hope this is the right place to put this question.

I'm building an addon to allow people to add things like T-shirts, etc, to a registration.  I started with the Mock Addon you provided (which was super-helpful), but now I'm getting to the point where I have to create my own database tables when someone installs the addon.

Do I have to create these manually in {addon}/core/data_migration_scripts?  I'm activating and deactivating my add-on, but the tables aren't being created automatically by the Registry (if that's what's supposed to happen). 

The documentation about [Data Migration Scripts](https://github.com/eventespresso/event-espresso-core/blob/master/docs/H--Data-Migration-System/data-migration-scripts.md) would imply that I do need to do this.

Thanks,

Anca.

**Comment by nerrad** [comment]
Hi Anca,

Yes, you're on the right track with the dms.  Here's some sample code from an unreleased add-on that I have which creates tables.

```
/**
 * Used to setup tables and handle migrations
 *
 * @package EE Saas Solution
 * @subpackage tools
 * @since 0.0.1
 * @author Darren Ethier
 */

class EE_DMS_Saas_Solution_0_0_1 extends EE_Data_Migration_Script_Base  {


	public function __construct() {
		$this->_pretty_name = __('Create necessary tables for Saas Solution addon.', 'event_espresso');
		$this->_migration_stages = array();
		parent::__construct();
	}


	/**
	 * only run when EE_Saas_Solution is at exactly version 0.0.1
	 *
	 * @since 0.0.1
	 * @param string $version_string
	 * @return boolean
	 */
	public function can_migrate_from_version($version_string) {
		//we have no migration stages to run
		//so this should simply always return false
		return false;
	}

	public function schema_changes_after_migration() {}

	public function schema_changes_before_migration() {
		$this->_table_is_new_in_this_version('ee_saas_post_to_post', "
			PTP_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
			PTP_REL_SLUG varchar(45) NOT NULL,
			PTP_IDA int(10) unsigned NOT NULL,
			PTP_IDB int(10) unsigned NOT NULL,
			PRIMARY KEY  (PTP_ID)", 'ENGINE=InnoDB'
				);
	}
}
```

The above is in a file named `EE_DMS_Saas_Solution_0_0_1.dms.php`

And the file path is registered via the arguments sent into `EE_Register_Addon` in the `dms_paths` argument. Here's the snippet:

```
$addon_arguments['dms_paths'] = array( EE_SAAS_SOLUTION_PATH . 'core/data_migration_scripts/' );
```

So the important things are:

1. The file name must match the classname for your DMS script.  
2. The class/file name must match the minimum version you want it to run at.  So in my case the version of the plugin was `0.0.1`.
3. Something that has caught me occasionally is I forget the `dms` extension in the filename.  Make sure you have that.
4. In the DMS class,  you'll want to define your tables in the `schema_changes_before_migration()` method.  If its a _new_ table for this version of your add-on then within that method you use the `_table_is_new_in_this_version` method.
5. Internally, the EE DMS system uses `dbDelta()`, so all the usual care must be given to spacing/case etc. 

I hope that helps,  if you're still not seeing the new table for your add-on created, let us know and we'll try to work out why.

**Comment by ammist** [comment]
Thanks for the help!  I created the migration script, and, once I updated the plugin version, the tables were created.  

Cheers,

Anca.
