### ISSUE TITLE
The Philippine currency symbol appears as an ? when you download an invoice as a PDF

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/event-espresso-core#1593]
**Summary**
A customer on Event Smart is in the Philippines and noticed that the invoice shows the currency as a question mark when it is downloaded as a PDF.

**Steps to reproduce**
- Go to the general settings for Event Espresso
- Update your country to Philippines
- Go to the registrations screen and open an invoice using the icon in the actions column

I tried to verify on 4.10.0.p on a testing site but the PDFs do not open after they download. 
![Image 2019-09-16 at 10 43 32 AM](https://user-images.githubusercontent.com/1079138/64967613-da2e9980-d86e-11e9-930b-3d3ffacde9d3.png)

I switched back to the United States and also reset the invoice template but I see the same thing.

I tried getting a PDF of an invoice demoee.org/use-cases/ and it doesn't download from there:

![Image 2019-09-16 at 10 44 45 AM](https://user-images.githubusercontent.com/1079138/64967718-0518ed80-d86f-11e9-92b3-8623cb39f48e.png)

**Reported or seen on**
This was reported on this site on Event Smart: https://upcpiym.eventsmart.com

**Comment by joshfeck** [comment]
It sounds like the [Simple UTF8 message template variations add-on](https://github.com/eventespresso/eea-utf8-message-template-variations) needs to be installed on Event Smart to allow unicode characters to render in PDFs. I checked locally, and with that add-on activated (and its setting selected for invoices) the PDFs render the characters as expected.

[ee4 Invoice for Transaction_ 120.pdf](https://github.com/eventespresso/event-espresso-core/files/3617202/ee4.Invoice.for.Transaction_.120.pdf)

@lorenzocaum can you open an issue on the ES repo so we can get that add-on installed there?

**Comment by lorenzocaum** [comment]
Thanks Josh!
