### ISSUE TITLE
Remove unnecessary additional getters and setters from JS models

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#1594]
## Issue Overview

Currently, the JS models use the REST API schema endpoints to retrieve a description of each model's fields which are then used to dynamically generate a class for each model. This includes creating setters and getters for each field/property. This however, was done a little overzealously and multiple setters and getters were created for each field allowing one to access and change an object's properties via multiple paths.

For example, getting the "name" property for an event can be done via functions like the following:

- event.name
- event.getName
- event.evtName
- event.EVT_name

and setting can similarly be done via:

- event.name = 'new name'
- event.setName = 'new name'
- event.evtName = 'new name'
- event.EVT_name = 'new name'

These extra getters and setters are completely unnecessary and only add bloat to the system.
We do not need anything more than the first example, which follows the pattern: 

`{model-name}`.`property`

These additional getters and setters need to be removed and all affected unit tests need to be updated accordingly.

**Comment by ManzoorWaniEE** [comment]
Fixed via #1641
