### ISSUE TITLE
Messages seem to be getting stuck in the "queue_for_sending" status.

### ISSUE THREAD

**Issue by mcrisci** [eventespresso/event-espresso-core#161]
> Before submitting your issue, please ensure that what you are reporting is specific to Event Espresso 4.

When submitting an issue, please follow this rough guideline for your report.

### Is this a bug report?

* [x] yes
* [ ] no

### What branch did this occur in?

4.9.0.rc.010 

### What version of WordPress is on the site this issue happened?
4.5.1

### Outline the steps to reproduce

The mail are scheduled, but the automatic trigger that should send them did not activate.

Any specific place to look at? Is there a setting buried somewhere?

Manual send are ok

**Comment by nerrad** [comment]
Hi there, thanks for your report.  Unfortunately theres not enough information here for me to know exactly what your issue is.  Are you able to add any more details?  I'm aware it has something to do with the message system but its not clear what  is wrong with the messages system.

**Comment by mcrisci** [comment]
Thanks for reply Nerrad, maybe i didn't explain in a good way.

The issue is : message are not sent, they are Queued For Sending, but actually i have some test message queued from several hours

**Comment by nerrad** [comment]
If you click the "Send Immediately" action, does the message get sent?

Also:

- Is this happening for all message types?
- What message type and messenger IS this happening for?
- Is wp-cron disabled on your site?

**Comment by mcrisci** [comment]
if i click send immediatly the mail are sent, so the plugin is working

- actually i got in queue only 'Registration Pending Payment' kind of mail (because i'am testing)
- wp-cron is enable, because all other plugin are making their things

i've dumped also my wp-cron, but the only thing related to EE are the automatic check for plugin update every 86400 seconds, nothing related to the message system..so maybe the issue is here

**Comment by nerrad** [comment]
Yes that sounds odd if there isn't a cron schedule for messages in your dump.  If you install a plugin like [wp-crontrol](https://en-ca.wordpress.org/plugins/wp-crontrol/), you can use that to see any set schedules and even trigger them in advance.

You should see two scheduled events for the messages system: `AHEE__EE_Messages_Scheduler__generation` and `AHEE__EE_Messages_Scheduler__sending`.  If you don't see those events, then that means that something is interfering with these events getting set and it may be a conflict with another plugin or theme or custom work on the site you are testing with.

Also, if you want, you can adjust the schedule for these events from the default of 5 minutes to something lower.

For example to change it to 30 seconds do this:

```
add_filter( 'cron_schedules', 'my_custom_ee_schedule' );
function my_custom_ee_schedule( $schedules ) {
    if ( isset( $schedules['ee_message_cron'] ) ) {
         $schedules['ee_message_cron']['interval'] = 30;
    }
    return $schedules;
}
```

**Comment by mcrisci** [comment]
ok, i'll dig a little with that plugin and make also some other test

when (and if .... heheheh ) i find the soulution i'll report it there

many thanks for your support

**Comment by nerrad** [comment]
Thanks for the report!  It's a critical system so we definitely want to make sure we catch any bugs.

**Comment by mcrisci** [comment]
QUICK UPDATE:

manually adding the events AHEE__EE_Messages_Scheduler__generation and AHEE__EE_Messages_Scheduler__sending, with 'wp-crontrol' do the job.

That resolved my issue, i think that in my configuration, when updating to the latest EE, some plugin/custom code/anything else was preventing the setup of that cronjobs

If i got some other information i'll report back

Many thanks again

**Comment by nerrad** [comment]
Great thanks.  Before we release this version it'd be nice to know if this could be fixed alternatively as well.  If you're able to reset your testing environment to when it wasn't working, does deactivating/reactivating Event Espresso add the schedules?

**Comment by joshfeck** [comment]
Is there a specific plugin or some custom code that you suspect would have caused the issue? The reason I ask is because it'd be good to know and we can investigate further.

**Comment by mcrisci** [comment]
in my staging site i have all the plugin that i use on the live site.

mail related plugin i use are: 
- wpMandrill for sending trough their service
- Email Log : to log exiting mail

Also my installation of EE start from EE3 so maybe there are some issue during several update, in the next few day i can try a clean installation and see if the problem keep presenting.

For sure the issue was that the cronjob wasn't created after activating latest version of EE

**Comment by nerrad** [comment]
okay I'm going to close this issue then.  If you discover any more specifics that can potentially help us please feel free to add to the ticket.  Thanks.

**Comment by nerrad** [comment]
So one theory I have in your case is that EE creates a custom schedule for usage by its events using the `cron_schedules` hook.  That's the same hookpoint that can be used to change the EE custom schedule to something else.  However, its very easy for other plugins/themes/customcode to wipe out any schedules that are set by also using that filter hook and failing to return all the schedules.  

In WordPress, when a custom wp-cron event is added that is registered using a custom schedule, if that custom schedule does not exist when calling `wp_get_schedules()` then that means the event will NOT get saved.  

So that may be something to look for in the code on your site... anything that filters `cron_schedules`
