### ISSUE TITLE
Fix admin bar toolbar navigation for small screens/breakpoints (WP 5.3 beta + Firefox)

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1635]
## Issue Overview

After updating a site to WP 5.3 beta, the admin bar navigation isn't rendering properly on smaller screens/breakpoints.

<img width="497" alt="Screen Shot 2019-09-25 at 12 24 43 PM" src="https://user-images.githubusercontent.com/891156/65621357-984dd380-df91-11e9-924a-9884472eac25.png">

## Environment Data:

Version of EE: 
current master
Version of WordPress:
5.3 beta 1

Browser used:  
Firefox
Also tested Chrome and Safari and there's no issues with those

## Steps to Reproduce (for bugs)

- [ ] Use beta tester plugin to update a site to WP 5.3beta
- [ ] Open Firefox and log into site (if you don't already use Firefox)
- [ ] Resize browser window to a width of less than 600px

**Comment by mnelson4** [comment]
I wonder if this might be an issue experienced by other plugins adding an admin bar menu? (Eg I think Yoast does too?) If so, the fix might be more appropriate in WP core

**Comment by joshfeck** [comment]
It's not an issue for the Yoast plugin.

![Sep-25-2019 13-52-25](https://user-images.githubusercontent.com/891156/65626701-de0f9980-df9b-11e9-9a8e-ca40f2631888.gif)

**Comment by mnelson4** [comment]
thanks for checking. Ya, weird that it's just ours
