### ISSUE TITLE
Create and update events, venues and registrations via the API

### ISSUE THREAD

**Issue by devlift** [eventespresso/event-espresso-core#164]
It would be great if we could create and update events, venues and registrations via the API.

Thanks!

**Comment by devlift** [comment]
Hey guys, 

Is there some way that we may be able to contribute to the development or testing of this feature?

Thanks!

**Comment by mnelson4** [comment]
Branch https://github.com/eventespresso/event-espresso-core/tree/FET-9222-rest-api-writes has got some of the work done. It lets you do insert queries for any model, but it does NOT yet account for permissions. If you like you could test that out and see if it works for you (try inserting a variety of things, especially verify serialized, data with unusual characters, and whatever other weirdness you can think of, is supported). 

Also, if you want to follow the precedent set in `modules/EED_Core_Rest_Api.module.php` and `core/libraries/rest_api/controllers/models/Write.php`, you could try your hand at adding the ability to update and delete model objects via the API.

Do you think you could attempt these?

**Comment by mnelson4** [comment]
Just an update on this item:  https://github.com/eventespresso/event-espresso-core/tree/FET-9222-rest-api-writes now supports creating, updating and deletion of events, registrations, venues, etc. Here's its documentation: https://github.com/eventespresso/event-espresso-core/blob/FET-9222-rest-api-writes/docs/C--REST-API/ee4-rest-api-writing-data.md.
It's currently undergoing internal testing, but having someone else validate that work would help move it along.

**Comment by nerrad** [comment]
Closing this due to lack of response.  Write endpoints are now released in EE core.
