### ISSUE TITLE
Feature Request: Use Question Admin Labels in Registration Form CSS

### ISSUE THREAD

**Issue by ammist** [eventespresso/event-espresso-core#165]
I'm trying to customize the display of the questions on the registration form, and it would really help if there was a way to target questions in CSS.  Right now, the questions get an ID that's specific to the registration + question ID (for example: 

`<label for="ee_reg_qstn-309-15-deluxepackageadd50" id="ee_reg_qstn-309-15-deluxepackageadd50-lbl" class="ee-checkbox-label-after medium-lbl">`

It would be super-helpful if I could add a class to that, say:

`<label for="ee_reg_qstn-309-15-deluxepackageadd50" id="ee_reg_qstn-309-15-deluxepackageadd50-lbl" class="ee-checkbox-label-after **deluxe-package** medium-lbl">`	

This could be a great use for the "admin label" field.

Alternatively, if you can point me to where I can customize the HTML that's output with the registration form, I would be most grateful.

**Comment by tn3rb** [comment]
@ammist 

great idea for the "admin label" field, I'll see if I can sneak that into the next release for you.

re: 

> Alternatively, if you can point me to where I can customize the HTML that's output with the registration form, I would be most grateful.

Well the checkout form is built out of many different little pieces, so there isn't a single template anywhere, in fact, there really aren't many templates at all, it's almost entirely dynamically  generated.

That said, all of the form options are filtered upon construction in  **\EE_Form_Section_Proper::__construct()** ( core/libraries/form_sections/base/EE_Form_Section_Proper.form.php ) by this filter:

```
apply_filters( 'FHEE__EE_Form_Section_Proper___construct__options_array', $options_array, $this );
```

So if you hook into that, and var_dump() the incoming $options_array for all of the forms in the checkout, you will see everything that goes into building the forms. So you could do something like : 
 
```
public function spco_form_options( $options ) {
	if ( isset( $options['name'] ) && $options['name'] === 'single-page-checkout' ) {
		var_dump( $options );
	}
	return $options;
}
add_filter( 'FHEE__EE_Form_Section_Proper___construct__options_array', 'spco_form_options, 10, 1 );
```

...but that's going to be a huge data dump though, so most likely not very fun to deal with.

There's also a bunch of filters in : 

```
core/libraries/form_sections/strategies/layout/EE_Form_Section_Layout_Base.strategy.php
```

that you may be able to use, which filter the returned html from the various form layout display strategies. SPCO ( Single Page CheckOut )  primarily uses the layout display strategy in: 

```
core/libraries/form_sections/strategies/layout/EE_Div_Per_Section_Layout.strategy.php
```

so you could make a copy of those layouts and then use the filters I mentioned to return different html. This option is likely much more usable than my first suggestion.

Hope that makes sense.

**Comment by ammist** [comment]
Ooh, thanks for the info.  This is helping me understand more of how this works so I can really implement memorabilia sales the "right" way (as opposed to the tricksy way).

I would really appreciate that admin class thing, too.  I can do a lot w/ CSS when it comes to displaying information in ways that make it easier for our customers to understand what they are supposed to be doing.

**Comment by nerrad** [comment]
closing for now since it appears the question has been answered.
