### ISSUE TITLE
offsite payment gateway

### ISSUE THREAD

**Issue by Sndan** [eventespresso/event-espresso-core#167]
> Before submitting your issue, please ensure that what you are reporting is specific to Event Espresso 4.

When submitting an issue, please follow this rough guideline for your report.

### Is this a bug report?

* [ ] yes
* [x] no

1. 

I am tring to setup an offsite payment addon I want to collect information from the registration form ... like name etc

I used this $order->customerName= substr($billing_info['first_name'],0,25) . substr($billing_info['last_name'],0,25);

but it gives me a wrong information -> "Customer Name"

2.

I want to edit chekout page so I want to remove the button for the user to redirect the page

**Comment by mnelson4** [comment]
hi @Sndan,
regarding issue 1, have you defined a billing form on the payment method class? (ie, overriden `generate_new_billing_form()` and set the `_has_billing_form` property). If not, you're not collecting any billing information, and so `$billing_info` will be an empty array. If you just want the information from the REGISTRATION FORM, you can acquire that from the attendee object. eg

```
$attendee = $payment->transaction()->primary_registration()->attendee();
$first_name = $attendee->full_name();
```

For issue 2, you will have to listen for the `spco_switch_payment_methods` javascript action (triggered in `event-espresso-core/modules/single_page_checkout/js/single_page_checkout.js`), use the data provided with the hook to determine that we've changed to or from your payment method, and then use javascript to show or hide that button.
Out of curiosity, what do you want in place of that button to redirect to the gateway's site?

**Comment by Sndan** [comment]
thanks sir ..
> Out of curiosity, what do you want in place of that button to redirect to the gateway's site?
I actually it is not an important thing but the payment site is slow and want open immediately ... and if we press they button there site will not accept the request ! so I decided to reomve the button :) 

by the way I want to edit admin page for chekins and add more information like the percentage of attendance ... I just start to digging in these , where is the views ? 

thanks ,,...

**Comment by mnelson4** [comment]
> by the way I want to edit admin page for chekins and add more information like the percentage of attendance

take a look in /admin_pages/registrations/EE_Registrations_List_Table.class.php and /caffeinated/admin/extend/registrations/EE_Event_Registrations_List_Table.class.php and /caffeinated/admin/extend/registrations/EE_Registration_Checkin_List_Table.class.php. 
Feel free to open a pull request if you want to add somethign directly to core, but it sounds like that's something that would be best accomplished with a filter.
Ok so if this addresses your gateway-related questions I'm going to close this ticket. Feel free to open a new one if you have other questions
