### ISSUE TITLE
Remove feature that updates decaf to premium via 1-click

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1671]
We need to prevent any updating from ee.com's servers for the core decaf plugin.

See also:
http://p2.eventespresso.com/?p=4204#comment-16653

At first I thought we could simply remove the support license key field from decaf, but that might not be a good solution since it's possible to use add-ons with decaf. For example, someone might prefer the simplicity of decaf but also require a gateway like Stripe. So they buy an EE4 support license and Stripe, but only install Stripe. So ideally they could get 1-click updates served from ee.com for the Stripe add-on, and continue to get 1-click updates served from wp.org for EE4 decaf core.

**Comment by knazart** [comment]
@garthkoyle @lorenzocaum , we have a "premium" upgrade available from within WP admin only for EE Core (decaf >> regular), correct ? Only the core plugin has a free version, right ?

**Comment by sethshoultes** [comment]
The premium upgrade happens when someone enters the support license key into decaf, then it deactivates/removes the decaf version and installs and activates the premium version. 

I just found that the W3TC plugin has a feature that allows a user to purchase and automatically activate a license from within the WP admin:
![image](https://user-images.githubusercontent.com/235315/81698841-c6e6c480-9423-11ea-9540-04057aff7c22.png)

Can we do something similar?

**Comment by knazart** [comment]
> Can we do something similar?

We could, but this might require quite a bit of work to be done there, and some planning. We might need to include the Recurly lib into the core plugin and then also communicate with our website to properly create the subscriptions. Could be a bit complicated atm.

**Comment by tn3rb** [comment]
doesn't that break WP.org rules?

**Comment by sethshoultes** [comment]
I worry that this will cause a lot of friction for new users that are trying to upgrade. It stinks that some of our competitors and other plugins will still offer streamlined upgrades to their free versions served on WP.org. Wouldn't it make sense to first decouple the Decaf version from the Caffeinated version and require Decaf installed prior to installing Caffeinated? I think we could even install Decaf automatically during the install of Caffeinated.

**Comment by knazart** [comment]
Do we want to discuss this more ?

From the P2:
>**Mike**:
>asked to clarification on this here: https://wordpress.slack.com/archives/pluginreview/p1478119457000013. And basically we can’t have a wp.org plugin downloading code from somewhere else and putting it on the person’s site. So basically PUE’s nice UX for upgrading from decaf to caf is the problem here (they can download caf manually, and that’s fine, but they don’t like the automatic download).

>**Garth**:
>According to ipstenu (assuming she understands correctly) it’s against the policy. This item of the guidelines doesn’t state anything about the opt-in exception.

From the header message on the [upgrade page from W3TC](https://github.com/eventespresso/event-espresso-core/issues/1671#issuecomment-627352799) it seems like they don't really download and replace the plugin with a premium one (like we do), the simply "re-configure" it and allow the premium features with the proper key.

Imo, to accomplish what W3TC does we would need to have EE core combined with decaf (and not decoupled). We have our EE core in a public repo now anyways. But that might bring up other questions like having it served on wp.org.

Do we have a key for W3TC to test on another (local) install ? I'm curious if they replace the plugin or do any changes to the files when you activate the premium features.

**Comment by garthkoyle** [comment]
> Wouldn't it make sense to first decouple the Decaf version from the Caffeinated version and require Decaf installed prior to installing Caffeinated?

Currently, aren't Decaf and Regular decoupled?

> the simply "re-configure" it and allow the premium features with the proper key

I thought the wp.org terms prohibit activating premium features after adding a license key?

> Do we have a key for W3TC to test on another (local) install ? I'm curious if they replace the plugin or do any changes to the files when you activate the premium features.

That's be good. Can we find that out from their repo: https://github.com/W3EDGE/w3-total-cache

**Comment by knazart** [comment]
> I thought the wp.org terms prohibit activating premium features after adding a license key?
Right, that also could be true. So I wonder how W3TC does all that.

> Can we find that out from their repo
Maybe, but it would be much faster to see it in action.

**Comment by sethshoultes** [comment]
See also https://github.com/eventespresso/priorities/issues/1#issuecomment-740202026
