### ISSUE TITLE
Display empty text box for "no limit" or "no maximum" instead of a -1

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1699]
> For datetime and ticket limits, I prefer having “” be the value for “no limit” rather than “-1”. It’s fine to store it in the DB as “-1” but IMO an empty text box is more immediately understood to mean “nothing entered here/not in use” whereas “-1” requires reading some documentation somewhere to know what that means.

per Mike's comment in:

http://p2.eventespresso.com/2019/10/10/edtr-test-server/#comment-20394

Usage in ticket editor:
<img width="734" alt="Screen Shot 2019-10-14 at 1 37 53 PM" src="https://user-images.githubusercontent.com/891156/66771383-1a8e3100-ee88-11e9-8907-0ddd9d20dd56.png">
(Quantity, Maximum Quantity, & Number of Uses fields)

Usage in datetime editor:
<img width="681" alt="Screen Shot 2019-10-14 at 1 40 45 PM" src="https://user-images.githubusercontent.com/891156/66771497-6214bd00-ee88-11e9-81f0-8d24029362b8.png">
(Capacity field)

**Comment by nicolad** [comment]
@tn3rb I tend to think that these negative values - `-1` reflect how data is persisted in DB. If so, is there a chance to handle things differently on the server-side ? I am open to other suggestions, as well.

**Comment by manzoorwanijk** [comment]
@nicolad Yes, that's how those values are stored in db. What do you mean by **"handle things differently"?** Can you please explain?

**Comment by nicolad** [comment]
Sure, we might want to hide the internals of how things are stored in db via some kind of middleware that can treat null values for those specific fields differently only on the server-side rather than exposing that to the client.

**Comment by manzoorwanijk** [comment]
yes, that's how it should be. It also makes the things less technical for a common end user.
