### ISSUE TITLE
hook in the admin page 

### ISSUE THREAD

**Issue by Sndan** [eventespresso/event-espresso-core#170]
### Is this a bug report?

[] yes
[*] no

hello I want to hook into a page Extend_Registrations_Admin_Page   
function  _registration_checkin_list_table

I want to append string into $this->_template_args['before_list_table']

is there a list of the available hooks ?

where should I use the add_filter()/add_action() ?
is it in this ? I am using the mock addon
```
class espresso_events_New_Addon_Hooks extends EE_Admin_Hooks {

	protected function _set_hooks_properties() {
        $this->_name = 'new_addon';
    }
```
 or 
```
	public static function set_hooks_admin() {
		add_action('_registration_checkin_list_table','checkin_list_table',10);
    }
```
thanks ,,

**Comment by nerrad** [comment]
All action and filter hooks in EE are prefixed by `AHEE__` for action hooks and `FHEE__` for filter hooks.

I think the hook you want is the `FHEE__EE_Admin_Page___display_admin_list_table_page__before_list_table__template_arg` filter.

You can find it in the [`EE_Admin_Page` class](https://github.com/eventespresso/event-espresso-core/blob/master/core/admin/EE_Admin_Page.core.php#L2584)
