### ISSUE TITLE
Remove "All fields marked with an asterisk (*) are required" text from form information

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1703]
I think this message at the top of the Event Date & Ticket editors, along with the close icon next to it, isn't needed:

![Screen Shot 2019-10-14 at 5 31 14 PM](https://user-images.githubusercontent.com/891156/66784639-0e669b80-eea9-11e9-967a-b5d2e9d44770.png)

Most people know that an asterisk next to a form field will mean it's required. Also in this case the required fields are automatically populated with something, and you can't blank out the required fields anyway.

**Comment by tn3rb** [comment]
what about moving that notice to the bottom of the form (could also make the text smaller to be less intrusive)?
unless you **also** want to remove the `*` from the form fields, I think we need to indicate somewhere what that actually means.

**Comment by sethshoultes** [comment]
IMO, you could move it to the bottom and remove the border around the message.

**Comment by joshfeck** [comment]
If you'd prefer not to remove the message, it could be moved to the bottom of the form, and then just remove the little x next to it.

**Comment by tn3rb** [comment]
> and remove the border around the message.

i think that's something that Josh added to his screenshot to highlight the notice

**Comment by joshfeck** [comment]
You are correct, the orange border was added to the screenshot to outline what should be removed or at least moved.

**Comment by sethshoultes** [comment]
Derp! I thought I've seen a notice with a border somewhere before and assumed it was applied here  :)

**Comment by tn3rb** [comment]
closing this issue since  it no longer applies
