### ISSUE TITLE
Unexpected offset applied to start and end times when site timezone isn't the same as user's timezone

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1709]
**Describe the bug**

If the site timezone isn't the same as the user's timezone, there's an incorrect offset applied to the start and end times. For example if the Site timezone is set to Boise (currently Mountain Daylight time) and the user's timezone is Eastern Daylight time, a difference of two hours will be applied to the input start and end times.
**To Reproduce**
EDTR-master branch
1. Go to WordPress > Settings > General
2. Select a city that's in a different timezone than your timezone
3. go to edit an event, then edit either a datetime or ticket's start/end times

![Oct-15-2019 12-29-17](https://user-images.githubusercontent.com/891156/66850778-74a1fb80-ef47-11e9-995d-84a7948d84d9.gif)

**Comment by tn3rb** [comment]
we will want to check this again at some point

**Comment by tn3rb** [comment]
What we may want to do to ensure that this never happens is the following:

- find all cases where dates are displayed and run value through `utcToLocal()` utility at the last moment (`assets\src\application\services\utilities\date\utcToLocal.ts`)

- find all cases where dates are received from user inputs and immediately run value through `localToUtc()` utility (`assets\src\application\services\utilities\date\localToUtc.ts`) 

- examine all other date related logic and ensure that we are always operating in UTC

**Comment by tn3rb** [comment]
@manzoorwanijk 
can you please identify all places in Apollo or Form related logic that handle dates ? (ie: places where user input is received)

@nicolad 
can you please identify all places in UI related logic where dates are displayed ?

**Comment by manzoorwanijk** [comment]
In EDTR, dates are used only in two forms for now. You can have a look at the `initialValues` in these two form configs:
- `assets/src/domain/eventEditor/ui/datetimes/dateForm/useDateFormConfig.ts`
- `assets/src/domain/eventEditor/ui/tickets/ticketForm/useTicketFormConfig.tsx`

In server-side code, the dates are formatted using
`EventEspresso\core\services\graphql\types\formatDatetime()`

**Comment by manzoorwanijk** [comment]
This is now fixed via #2612
