### ISSUE TITLE
Adding a filter to invoice [PAYMENT_LIST_*] shortcode

### ISSUE THREAD

**Issue by nickheyvaert** [eventespresso/event-espresso-core#171]
> Before submitting your issue, please ensure that what you are reporting is specific to Event Espresso 4.

When submitting an issue, please follow this rough guideline for your report.

### Is this a bug report?

* [ ] yes
* [x] no

### What branch did this occur in?
master

### What version of WordPress is on the site this issue happened?
4.6.1

### Outline the steps to reproduce
All payments are shown on an invoice. It is not possible (yet) to only show approved payments. This can easily be done by adding a filter to `_get_payment_list` in `EE_Payment_List_Shotcodes.lib.php`.

E.g. `$payments = apply_filters( 'FHEE_Payment_List_Shortcodes__get_payments_list', $addressee_obj->payments );`

**Comment by nerrad** [comment]
We welcome pull requests :)
