### ISSUE TITLE
Consider removing requirement for a datetime to have a ticket

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1711]
Currently you **can** have a datetime without a ticket, and to get one you follow these steps:
1) In an event that already has at least one ticket and at least one datetime, add a new datetime
2) Set the datetime's values, then click the x
3) On the Ticket Assignments page, select all tickets shown
4) Click the Cancel button
The modal will close and you'll note that the "?" next to the tickets icon. If you try to edit ticket assignments, you'll run into validation issues at this point.
![Screen Shot 2019-10-15 at 2 39 11 PM](https://user-images.githubusercontent.com/891156/66859590-960be300-ef59-11e9-80da-d5a800ad22ec.png)

So it's possible to have an datetime without a ticket, and this is a valid use case that's requested often. You kind of have to step through some hoops to make it happen though.

### Proposed changes to the Event Date Editor modal:

1) Remove the x on the upper right corner
2) Add an "Assign Tickets" button; Most users will click this to go to the next step of assigning tickets
3) Add a "No Tickets" button to skip the ticket assignments; When a user clicks this button they'll be taken to the main event editor route

### Proposed changes to the Ticket Assignments modals:
1) Remove validation for and messages indicating that event dates must always have at least one ticket assigned to them.
2) Allow clearing any and all assigned tickets from a datetime

**Comment by tn3rb** [comment]
> Remove the x on the upper right corner

this currently can not be done because the modal is a WP core component and they do not provide the ability to modify that.

I've been considering replacing ALL of the modal windows used in the EDTR with some other way of switching views (like maybe a tabbed navigation?) which would also resolve (potentially) a bunch of the layout and appearance issues that exist with the Modal (ex: tooltip and datepicker positions, etc)


> Add a "No Tickets" button to skip the ticket assignments;

so simple, yet so brilliant 👍

**Comment by joshfeck** [comment]
There's been some discussion about this and it's been brought up that it would require a new field and a DMS in order to flag a datetime as not having a ticket. We might revisit this again, especially in the context of REM and if there's enough user requests.

In the meantime, we'll need to tighten up the validation to prevent a state where a datetime has no tickets.
