### ISSUE TITLE
Fix/Remove the `x` Button on the Ticket Assignments for All Event Dates Modal

### ISSUE THREAD

**Issue by garthkoyle** [eventespresso/event-espresso-core#1713]
The Event Dates > Ticket Assignments button modal `x` button doesn’t do anything. The Cancel button closes the modal. The tooltip for the `x` says “close ticket assignments” but it does not do anything in FF 69.0.3 on OSX.

**Comment by joshfeck** [comment]
in #1711 @tn3rb [commented](https://github.com/eventespresso/event-espresso-core/issues/1711#issuecomment-542399454):

> I've been considering replacing ALL of the modal windows used in the EDTR with some other way of switching views (like maybe a tabbed navigation?) which would also resolve (potentially) a bunch of the layout and appearance issues that exist with the Modal (ex: tooltip and datepicker positions, etc)

If we end up replacing the modal windows we can close this.
