### ISSUE TITLE
Avoid mysterious fatal errors during 4.10 migrations

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/event-espresso-core#1739]
## Issue Overview

There are occasional reports of errors during the 4.10 DMS. Eg,
![Screen Shot 2019-10-23 at 2 39 14 PM](https://user-images.githubusercontent.com/1766382/67425261-878e7e80-f58c-11e9-8d6b-be0c21c15c42.png)
Information is a little sparse, but I'm suspicious that the database queries are timing out (especially if the tables are large, like the above is).
The table being updated has 2 indexes: on the `EVT_ID` column, and on the `QSG_ID` column. The update and delete queries being ran use the `EQG_primary`, `EVT_ID` and `QSG_ID` columns during the query. 
They should be able to make use of at least one of those indexes (although not both, because once we've filtered by one, eg by `EVT_ID`, the remaining items are not organized by `QSG_ID`, so it's fastest to ignore the second index at that point).
BUT, because the database query is first querying `EQG_primary`, I think the remaining results are no longer indexed like they were originally; so NEITHER index gets used.
And if there are over a million database records, that's bad news bears.

Possibly, reordering the database query's WHERE conditions could mean we're able to use the query.
Using MySQL's `describe query` may help to confirm what indexes are in use(if I'm able to understand it's output :confounded:) and if the change makes any different to the query's efficiency.

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Environment Data:

Version of EE: 
4.10.2

Version of WordPress:
?
PHP Version:  
?
Browser used:  
Shouldn't matter.

## Steps to Reproduce (for bugs)

Not sure, but possibly: install EE 4.9. Create over a million event-question-group relations. Upgrade to 4.10. Run the migrations on a weak-sauce server.

## Expected Behaviour

They should all work fine.

## Current Behaviour

Random fatal error somewhere along the way.

**Comment by mnelson4** [comment]
I ran `EXPLAIN UPDATE wp_esp_event_question_group SET EQG_additional = 1 WHERE QSG_ID = 0 and EVT_ID = 0`, which is one of the queries we're using,  got this output:

```
"id","select_type","table","partitions","type","possible_keys","key","key_len","ref","rows","filtered","Extra"
"1","UPDATE","wp_esp_event_question_group",\N,"range","EVT_ID,QSG_ID","EVT_ID","8","const","1","100.00","Using where"
```

Note the part that "key" is "EVT_ID", meaning the "EVT_ID" key/index IS being used for the query (so I was wrong- I suspected it wasn't.) So it seems MySQL is smart enough to evaluate the indexed columns first, regardless of how they're ordered in the MySQL query.

I noticed one query had an extra placeholder, but from my testing and what I've seen in the code that shouldn't produce any errors.

The next idea is: instead of having update and delete (blocking) queries with a few WHERE conditions in them; maybe use those conditions in a (non-blocking) SELECT query, grab their primary IDs, then use those for the (blocking) update/delete query. It's overall less efficient, but it means the expensive part (evaluating the where conditions) doesn't lock up the entire table.

**Comment by joshfeck** [comment]
If you can do a branch with the above idea, I know of at least one customer that has a staging site where this idea could be tested.

**Comment by mnelson4** [comment]
Oh great! Especially if they're reproducing the issue that would be fabulous. I'll put a branch together.

**Comment by joshfeck** [comment]
They are reproducing the issue.
