### ISSUE TITLE
Conflict due to incomplete admin page setup

### ISSUE THREAD

**Issue by decodekult** [eventespresso/event-espresso-core#174]
### Is this a bug report?

* [x] yes
* [ ] no

### What branch did this occur in?
Master

### What version of WordPress is on the site this issue happened?
4.6.1 and 4.7 nightly build

### Outline the steps to reproduce
In `EE_Admin_Page_CPT::modify_pagenow`, as part of the `EE_Admin_Page_CPT::_before_page_setup` process, the global `$pagenow` is modified on custom admin pages to create ot edit events, in order to make the whole system believe we are either on `post-new.php` or on `post.php` native admin pages. This goes pretty well for most of the cases, but there are related elements that do not get properly managed

There is another global: `$hook_suffix`. This global is set just before the native method to set the current screen, which this plugin uses to modify it with the current_screen action:
https://core.trac.wordpress.org/browser/tags/4.6/src/wp-admin/admin.php#L178
This global is passed to a long series of related hooks, like:
* `admin_enqueue_scripts` at https://core.trac.wordpress.org/browser/tags/4.6/src/wp-admin/admin-header.php#L92
* `admin_print_styles-$hook_suffix`, `admin_print_scripts-$hook_suffix` and `admin_head-$hook_suffix` as well as some related footer actions.
* It also helps crafting the admin page body classname.

As a result, assets set to be registered in native add/edit pages using `admin_enqueue_scripts` and relying on the `$hook` argument it provides fail to get loaded on events add/edit pages, producing inconsistent behavior with other elements that might get added to the page using other hooks that do rely in `$pagenow`.

I would suggest to complete the page setup by also altering the `$hook_suffix` global in this same `EE_Admin_Page_CPT::modify_pagenow` method. However, I can not guarantee that you are not relying on this `$hook_suffix`, by itself or as part of an action name or arguments, for any other thing, so please consider side effects.

### Please include any links to the page(s) demonstrating this issue (if possible).
Reported here:
https://wp-types.com/forums/topic/views-message-shows-on-event-espresso-admin-page/

**Comment by nerrad** [comment]
Thanks for the detailed report!  If I get a chance I'll try to look into this today.

**Comment by nerrad** [comment]
This is currently in testing, if you want to test as well the work is found in the **BUG-10261-include-wp-hook-suffix-global-bash** branch.

**Comment by decodekult** [comment]
This solved the issue for me. Thanks a lot for the effort and speed!

**Comment by nerrad** [comment]
Thanks for posting back about your results.  We still have some internal tests to run (to rule out any side-effects) but if all goes well this will get out within the next couple of releases of EE.
