### ISSUE TITLE
Display total registrations count for tickets and datetimes

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1742]
The original UI shows the total registration count (which includes registration of all statuses, not just "sold").

In the new UI, the only place where a total registration count is shown is in the ticket list view.

I think we should remove the reserved counts from the default grid view and replace with a count of total registrations. The reserved counts can stay in the list views as they are a helpful reference.

**Comment by garthkoyle** [comment]
Can you add screenshots for clarity?

Should this be our EDTR To-Do list?  https://docs.google.com/spreadsheets/d/1XlxSbXLY3Th2VLWqtcxpHB_nuj9MO-i3oZ9nFKOcd-0/edit#gid=1386834576

**Comment by joshfeck** [comment]
<img width="593" alt="Screen Shot 2019-10-28 at 2 32 16 PM" src="https://user-images.githubusercontent.com/891156/67707300-9d3ae400-f990-11e9-97ba-c3034dc5fbf5.png">


> Should this be our EDTR To-Do list?

No because the Grid view wasn't in the original editor.
