### ISSUE TITLE
Automatically decrement ticket quantity fields when related datetimes reg limit gets set

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1747]
This was a feature in the original ticket editor where the value for the registration limit for a datetime would automatically "sync" the related ticket's quantity field. Animated gif to show the ticket fields updating after saving the event's changes:

![ticket-datetime-limit](https://user-images.githubusercontent.com/891156/67720587-b486cb00-f9aa-11e9-81c6-de37e84fc41b.gif)

In the new editor, if you change the datetime reg limit to a smaller number, the related ticket quantity field does not automatically update.
![Screen Shot 2019-10-28 at 5 31 21 PM](https://user-images.githubusercontent.com/891156/67720629-d41df380-f9aa-11e9-90da-bb93cfacd5dc.png)

**Comment by manzoorwanijk** [comment]
@joshfeck Should this be handled server side?

**Comment by manzoorwanijk** [comment]
`EE_Ticket::set_qty()` already takes care of that, but REST API handles it differently in `/core/libraries/rest_api/controllers/model/Write.php`. The `set_qty` method is bypassed by directly calling `EE_Base_Class::save()`. So we need to put that restriction somewhere in `EE_Base_Class`.

**Comment by joshfeck** [comment]
@mnelson4 can this be updated in the REST API?

**Comment by tn3rb** [comment]
We should consider doing that client side at some point though.
It is currently done server side because it was just way easier than manipulating the DOM was.
What we could do is show a popup notice saying that lowering the capacity will change related ticket quantities, and whether to proceed or undo the capacity change

**Comment by mnelson4** [comment]
> @mnelson4 can this be updated in the REST API?

Kindof. So far the design has been that the REST API is basically like low-level database access- it just updates the values you set, without any side effects or logic. If we want side effects, we would create a new endpoint (eg `/wp-json/ee/v4.8.36/datetimes/update_quantity`) that would do the side effect, and the API client would use that. But we probably wouldn't update the existing routes to perform this logic.

> We should consider doing that client side at some point though.

Yeah the client will probably need to be updated. Either to have the logic to know what ticket quantities need to be updated and how to update them; OR to just leave that to the server-side code, and have the REST API response reply with the needed information (eg what tickets should be updated and what their new quantities should be).

**Comment by joshfeck** [comment]
> show a popup notice saying that lowering the capacity will change related ticket quantities, and whether to proceed or undo the capacity change

I'd prefer to keep things simple and at most highlight the fields that are affected with the change.

**Comment by manzoorwanijk** [comment]
Fixed via #1788
