### ISSUE TITLE
Fix ticket price editing in EDTR for existing ticket after switching from original editor

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1749]
1) start with the original editor, set a ticket’s price to 10.00
2) save the event
3) Use the option to switch to new editor
4) go in and edit the event
![Screen Shot 2019-10-28 at 7 14 08 PM](https://user-images.githubusercontent.com/891156/67725203-e81c2200-f9b7-11e9-9f33-4641e11a4bbc.png)
5) using the ticket Card UI, change the price to 20.00
![Screen Shot 2019-10-28 at 7 14 20 PM](https://user-images.githubusercontent.com/891156/67725219-f5d1a780-f9b7-11e9-9b7d-278df982e3e8.png)
![Screen Shot 2019-10-28 at 7 14 26 PM](https://user-images.githubusercontent.com/891156/67725221-f9fdc500-f9b7-11e9-8071-274ae6ba85e9.png)
6) Save the event
7) Go to the front end to register, the price will be 10.00
![Screen Shot 2019-10-28 at 7 14 55 PM](https://user-images.githubusercontent.com/891156/67725240-0a15a480-f9b8-11e9-8c8a-da439fd49875.png)

Debug output in ticket price calculator:
![Screen Shot 2019-10-28 at 7 16 02 PM](https://user-images.githubusercontent.com/891156/67725267-1a2d8400-f9b8-11e9-814d-aa80e8841cd4.png)
and in the ticket editor:
![Screen Shot 2019-10-28 at 7 17 07 PM](https://user-images.githubusercontent.com/891156/67725273-21ed2880-f9b8-11e9-9b08-4e79367e7028.png)

URL to edit the above event on dev site:
https://brent.eventespresso.com/wp-admin/admin.php?page=espresso_events&action=edit&post=63

**Comment by joshfeck** [comment]
This may be related to #1778

**Comment by manzoorwanijk** [comment]
Fixed via #1820
