### ISSUE TITLE
EDTR : Handle Errors with Notice component.

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#1757]
**Describe the bug**
Garth was getting the following error while trying to save changes to an event he was editing on the devbox EDTR site:

```js
Uncaught (in promise) 
{code: "rest_datetime_invalid_id", message: "Invalid datetime ID.", data: {…}}
code: "rest_datetime_invalid_id"
data: {status: 404}
message: "Invalid datetime **ID."**
```

**To Reproduce**

1) edit an existing event (interweb conference)
2) Create a new datetime (you can see the ones I create in that event now that I can get it saved, they’re called “Expired Datetime”
3) Try to assign the tickets by selecting the first ticket
4) Click Update Ticket Assignment button

That’s when the error appears in the console

The call stack for the error shows that it is happening inside of this Promise in `/assets/src/data/eventespresso/base-controls.js`:

```js
	RESOLVE_SELECT( { reducerKey, selectorName, args } ) {
		return new Promise( ( resolve ) => {
			const hasFinished = () => selectData( 'core/data' )
				.hasFinishedResolution( reducerKey, selectorName, args );
			const getResult = () => selectData( reducerKey )[ selectorName ]
				.apply( null, args );

			// trigger the selector (to trigger the resolver)
			const result = getResult();
			if ( hasFinished() ) {
				return resolve( result );
			}

			const unsubscribe = subscribe( () => {
				if ( hasFinished() ) {
					unsubscribe();
					resolve( getResult() );
				}
			} );
		} );
	},
```

so in addition to fixing the cause of the actual error, it appears we need to add some defensive logic to better handle any errors that occur here in the future.

**Comment by nicolad** [comment]
@tn3rb I can try to debug this and add some error catching

**Comment by nicolad** [comment]
I followed steps described to reproduce and got this instead:

![image](https://user-images.githubusercontent.com/1477453/68119147-a08f1c00-ff0a-11e9-8b54-186e671e3046.png)
***
Here is the screencast of my attempt to reproduce bug:

![Peek 2019-11-04 13-52](https://user-images.githubusercontent.com/1477453/68119205-bf8dae00-ff0a-11e9-9ab0-f37dfb075fe1.gif)

**Comment by nicolad** [comment]
This error isn't happening now.
However we need to communicate to user as well what is the result of the action with something like: https://github.com/WordPress/gutenberg/tree/master/packages/components/src/notice

which can be implemented via:
https://reactjs.org/docs/error-boundaries.html

**Comment by tn3rb** [comment]
not applicable any more
