### ISSUE TITLE
EDTR: Collapsable Filter/Search bar

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#1771]
I feel like the Filter/Search bar takes up a lot of space on the screen when it might not be needed for many people with only a few datetimes or tickets. Could we make this area expandable & collapsible, defaulting to collapsed? :
![Events ‹ EDTR — WordPress 2019-10-30 11-01-10(1)](https://user-images.githubusercontent.com/235315/67880875-207d4680-fb05-11e9-9f11-f64132690563.jpg)

**Comment by tn3rb** [comment]
yes I have had this same thought and was planning to eventually replace the filter inputs with an icon button using the [filter dashicon](https://developer.wordpress.org/resource/dashicons/#filter) that would expand the filters out (ie" slide them into view) when you clicked it.

**Comment by nicolad** [comment]
@tn3rb I can take care and of that
