### ISSUE TITLE
Update usage of getters/setters where needed

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1778]
In #1641 the unnecessary getters and setters for every field/property of an entity in the model system were removed. It appears there are a few places where some of the old, removed aliases are still being used. We'll need to find those and update them.

This is likely related to the issue with editing prices as mentioned in this project card:

https://github.com/eventespresso/event-espresso-core/projects/4#card-28578673

**Comment by manzoorwanijk** [comment]
It's actually a bug related to data hydration where the price type list is not updated in `'eventespresso/lists'` store.

**Comment by manzoorwanijk** [comment]
Created #1780 from that card
