### ISSUE TITLE
EDTR: improvements.

### ISSUE THREAD

**Issue by nicolad** [eventespresso/event-espresso-core#1807]

**Comment by nicolad** [comment]
We should consider using `reselect`, instead of `rememo` and take advantage of selectors' composition.
Currently we have places where hooks are used to retrieve data from a global store, like `window.eeEditorEventData`
https://github.com/reduxjs/reselect

**Comment by manzoorwanijk** [comment]
`reselect` is no doubt a better option.

**Comment by joshfeck** [comment]
Is this still applicable? If not we can close this.
