### ISSUE TITLE
EDTR: Find and refactor any EE GB Blocks.

### ISSUE THREAD

**Issue by nicolad** [eventespresso/event-espresso-core#1837]
Find and refactor any EE GB Blocks that Utilize EE JS Models, ie: extract all data store dependencies from JS `/assets/data` folders and move into new folder locations.

**Comment by joshfeck** [comment]
Right now there's only one EE GB block. It's the Event Attendees block and it displays a list of attendees.

![Screen Shot 2019-11-12 at 4 44 19 PM](https://user-images.githubusercontent.com/891156/68713458-ea5fae00-056b-11ea-9087-b315f1f724ba.png)

**Comment by tn3rb** [comment]
- create new `/gutenberg/blocks` folders in `/assets/src/domain/` 

- move contents of `/assets/ZZZ/blocks` into `/assets/src/domain/gutenberg/blocks`

- update all internal paths that do not point to `/assets/ZZZ` folder

- add cards here for moving/converting every dependency that is still located in `/assets/ZZZ` folder

**Comment by manzoorwanijk** [comment]
Done via #2767
