### ISSUE TITLE
Extract Filter State Redux Logic

### ISSUE THREAD

**Issue by nicolad** [eventespresso/event-espresso-core#1843]
extract the logic from `/assets/ZZZ/data/eventespresso/filter-state/index.js` and move it into `/application/ui/components/input/entity-list-filter-bar/use-entity-list-filter-state.js`

- refactor `useEntityListFilterState` and any of its corresponding associates to implement `useReducer()` instead of Redux

- update all internal paths that do not point to `/assets/ZZZ` folder

- add cards here for moving/converting every dependency that is still located in `/assets/ZZZ` folder

**Comment by tn3rb** [comment]
completed in #2074
