### ISSUE TITLE
Add Black Friday Sale info to the readme.txt

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#1844]
As part of our Black Friday sale, we would like to add a message about it to the plugin page on WordPress.org. This requires modifying the readme.txt and releasing an update before and after the sale.

**Comment by sethshoultes** [comment]
Proposed message:
`Black Friday & Cyber Monday Sale Starts Now! [Click Here to Save 25% On a New Support License Right Now](https://eventespresso.com/pricing/black-friday-cyber-monday-sale/?utm_source=wordpress_org&utm_medium=link&utm_campaign=2019_holiday_sale&utm_term=2019_holiday_sale&utm_content=2019_holiday_sale)`

**Comment by sethshoultes** [comment]
Per Josh, this type of messaging would be considered spam. It was also confirmed in the `#pluginreview` channel in WP.org Slack:
![image](https://user-images.githubusercontent.com/235315/68793316-382af380-060a-11ea-823e-af7518d7e6bf.png)

**Comment by mnelson4** [comment]
Thanks for giving it some thought and doing some research. Sorry it didn't pan out.
