### ISSUE TITLE
Build `DatesListData` Container

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#1863]
- Use `useReducer` to implement Redux pattern

what do we need `useReducer` for ?  - bc

- queries Apollo for list of Dates
- returns array of date IDs

**Comment by nicolad** [comment]
@tn3rb to dispatch actions, here is an example: https://codepen.io/kinsomicrote/pen/zQzmqy

not something set in stone, will see what makes sense and isn't adding obsolete complexity

**Comment by manzoorwanijk** [comment]
We won't need `useReducer` for this. `useReducer` can be used to store the changes in individual entities before mutating the data.
