### ISSUE TITLE
Add copy attendee info section for admin (backend) registrations

### ISSUE THREAD

**Issue by thebeline** [eventespresso/event-espresso-core#188]
Title says it all: There is no option to "Use First Registrant Answers" when making a Registration via the Administrative interface.  That is going to make it tedious for the people it's most tedious for...  :-/

**Comment by thebeline** [comment]
Ok...

**Comment by joshfeck** [comment]
@nerrad, Brent already has a ticket for this in Codebase. #8076

**Comment by nerrad** [comment]
Thanks josh.

**Comment by tn3rb** [comment]
https://events.codebasehq.com/projects/event-espresso/tickets/8076

**Comment by joshfeck** [comment]
Ideally the copy attendee info option would use the setting we've just added to toggle its display. Then, we can also add a filter hook to override the setting. This way, if the site admin wants to turn off the copy attendee info option for the front-end, but keep it active on the back-end, then they can add simple filter function to activate the feature for the back-end only.

**Comment by joshfeck** [comment]
added in #1669
