### ISSUE TITLE
Extend Any Class

### ISSUE THREAD

**Issue by dalavatroll** [eventespresso/event-espresso-core#189]
This is a question, not an issue.

I'm trying to extend any class in Event Espresso from an Addon.

I'm following the documentation here:

https://github.com/eventespresso/event-espresso-core/blob/master/docs/D--Addon-API/model-and-class-extensions.md

I've copied the mock addon to the plugins folder and enabled it.  I then wrote a function called hit() in:

wp-content/plugins/eea-new-addon/core/db_classes/EE_New_Addon_Thing.class.php

And then I hard coded into the framework for testing a call to this function like EE_Addon_Thing::hit() (on line 192) in:

wp-content/plugins/event-espresso-core-reg/admin_pages/events/Events_Admin_List_Table.class.php

That works just fine!!  Hurray.  Then I made my own file right next to EE_New_Addon_Thing.class.php.  I called it EEE_Rand_Admin_List_Table.class.php.  I put my hit() function in that file and then called it from that admin file again with EEE_Rand_Admin_List_Table::hit2().  That worked, hurray again!!  Nice that it picked up that file without having to include it anywhere.

So now my goal is to extend Events_Admin_List_Table.class.php itself.  Then I should be able to override its column_name() function.  The key here is in the __construct() function in that file.  This line:

`$this->_model_name_extended = 'Events_Admin_List_Table.class';`

There is a lack of documentation of what I can put in there (or I don't know where that documentation is.)  The documentation uses "Event" there.  It seems like I should be able to extend any class in the framework by putting the correct value there, but I don't know the syntax.  Can I extend Events_Admin_List_Table.class.php by changing that line of code?

**Comment by nerrad** [comment]
The model and class extensions system is only for extending existing children of `EE_Base_Class` and `EEM_Base` classes.  It's not for any other class in the system.  The purpose is best illustrated by what's outlined in the opening paragraph of the doc you linked to:

> A central tenet of object-oriented programming is cohesion, part of which is organizing functions and methods close to the data they operate on. Eg, a function for searching for events attended by a particular attendee should be kept in the Event model (whose job is to query for events from the database), not amongst widget or templating code. This is easy for Event Espresso core developers to do: just add a method named 'get_all_events_for_attendee()' onto EEM_Event and we're done. But what about non-core Event Espresso developers? They can submit a pull request with the change, but the more feasible option is to add a model extension which magically adds that method onto EEM_Event.

`Events_Admin_List_Table` is not something intended to be "extended" by this system.

I think we could better help you if you were to describe what it is you are wanting to do and why.

**Comment by dalavatroll** [comment]
Thanks for the quick reply Darren.

I'm working on a project that extends Event Espresso.  It just made sense to me that if I could extend/override any class in the system without coding directly on them, I would have all the power I need to make any modification.  We haven't nailed down the exact features we want yet.

**Comment by nerrad** [comment]
Event Espresso _is_ built to be very extensible.  One thing that is made use of a lot is the WordPress action and filter system.  A lot of custom functionality can be built using that system alone.  However, other things in Event Espresso have been built with a modular type of system in mind so it also makes it possible to add additional functionality in.

It sounds like you're building something exciting!  When you're able to articulate what you need to do we'd be happy to point you into the right direction.

For now I'm just going to close this issue but feel free to continue the conversation in here if you want.
