### ISSUE TITLE
QTip array index specificity question.

### ISSUE THREAD

**Issue by thebeline** [eventespresso/event-espresso-core#190]
In `EE_Event_Editor_Decaf_Tips` and `EE_Event_Editor_Tips`, is there a particular reason you are implicitly defining the array indexes?  You do some fun skipping around in `EE_Event_Editor_Decaf_Tips`, but `EE_Event_Editor_Tips` is all sequential (but still implicitly defined).

If there is a method to the process, awesome, let me know, because I have a few to add (you are going to get sick of this real fast...  :-P).

**Comment by nerrad** [comment]
I think you meant to ask why we _explicitly_ define the array indices maybe?

In the case of Qtips, I don't think there's really any reason behind it.  An area of the codebase that could be improved, but currently not harming anything the way it is so no urgency to do so.

**Comment by thebeline** [comment]
AH, grammar and words.  words words words

**Comment by thebeline** [comment]
Ok, closed, then.  ;-)
