### ISSUE TITLE
REST API Edit relation between Event and Person seems broken

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1903]
Following the documentation here:

https://github.com/eventespresso/event-espresso-core/blob/master/docs/C--REST-API/ee4-rest-api-editing-relations.md

Someone was trying to update the relationship between an event and an EE Person CPT (added by the People add-on). You can send an auth'd POST request like this:

`wp-json/ee/v4.8.36/events/521/people/606/`

or even like this:

`wp-json/ee/v4.8.36/people/606/events/521`

The JSON response will be:
```
"code": "error_occurred",
"message": "There is no model named &#039;EVT_ID&#039; related to EEM_Person_Post. Query param type is 0 and original query param is EVT_ID",
"data": null
```

Despite that error, there is a new row that gets added to the `_esp_people_to_post` table. Also, if you try to send additional params to specify values for `P2P_Order` or `PT_ID`, a 0 gets written to those columns in the db.

Can you look into this Mike?

**Comment by mnelson4** [comment]
Thanks Josh, I see the issue: `\EventEspresso\core\libraries\rest_api\controllers\model\Write::addRelation` adds the relation then tries to return the new join-table row. It assumes the foreign key columns on the join table are the same as the primary keys on the joined models. That's correct in core, but not in `\EEM_Person_Post`, whose foreign key to the event model is `OBJ_ID`
