### ISSUE TITLE
Preview deletions

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/event-espresso-core#1905]
Show the user what data will be deleted before deleting it. This should use https://github.com/eventespresso/event-espresso-core/issues/1904 to figure out what information that is.
It shouldn't crash when there are thousands of registrations.
Users should confirm they have a database backup and confirm they are deleting the correct event.

* [x] generate the preview page via a batch job 
* * [x] count the records- tricky because what we're doing is discovering
* * [x] keep track of where we left off
* * [x] store the built tree (even when it has thousands of entries)
From https://github.com/eventespresso/event-espresso-core/issues/349#issuecomment-557718323
* [x] display the preview page
* [x] add a link to it
* [x] Clean out old "built trees" (database options) that weren't ever used for deletion

**Comment by mnelson4** [comment]
With #2110 merged into `CASC/base`, the next thing I think to do is actually make the preview page. 

My current plan is something like this:

`
-------------------------------------
| Preview Data for deletion
|
| X Events:
| Event x
| Event Y
|
| Y datetimes:
| datetime x
| datetime y
| 
| X tickets:
| ticket x
| ticket y
|
| ... registrations, prices, custom message templates, and I think that's all I'd mention (relation rows are assumed)
| 
| Confirm you made a database backup []
|
| You are about to delete Event X (whose permalink is y). Please confirm the permalink of the event [______]
| You are about to delete Event Y (whose permalink is x). Please confirm the permalink of the event [______]
| ...etc for each event
| (confirm and begin deletion)
`

In prose, we'll show the number of events to delete, and their names; then the number of datetimes to delete and their names (or time range etc); then tickets, registrations, prices, and message templates. (But not other data that's more removed from users, like extra meta, post meta, join-table entries, etc.)

Then we'll have a checkbox asking them to confirm they have made a database backup.

And lastly, for each event being deleted, we'll tell them they're about to delete the event's name, say its permalink, and then ask them to re-type the permalink (probably just the slug portion, the rest is should be autofilled).

@tn3rb @joshfeck does that make sense and do you have feedback on it?

**Comment by joshfeck** [comment]
I don't think it should make a mention of deleting custom message templates. I know it's only deleting the relationship between a custom message template and the event, but that could be confusing to the end user and they may think their custom message template will also be deleted, which they may not want.

**Comment by mnelson4** [comment]
Errmmm... actually it is deleting custom message templates, currently :slightly_frowning_face:. I thought they were only accessible from the one event... but I see now that they're actually accessible from elsewhere (and might be used by other events :confounded:). So I'll make it so it doesn't delete custom templates...

**Comment by mnelson4** [comment]
FYI I created https://github.com/eventespresso/event-espresso-core/pull/2173 to address that issue. It was a very simple change.

**Comment by mnelson4** [comment]
Ok I have a PR that's in progress that does the above. Here's a snapshot... https://nimb.ws/p24F3D

**Comment by mnelson4** [comment]
This work has been merged to CASC/base so is ready for testing/evaluation alongside everything else.
