### ISSUE TITLE
DateRangePicker default state/ values

### ISSUE THREAD

**Issue by nicolad** [eventespresso/event-espresso-core#1928]
- Currently picker isn't picking default values passed through `dateRange`, need to check why this is not accepting that.

**Comment by nicolad** [comment]
Also, we need to think of an indicator, as suggested in this comment: https://github.com/eventespresso/event-espresso-core/pull/1927#pullrequestreview-325160167

**Comment by tn3rb** [comment]
I've estimated 8 hours for this (plz give feedback if that does not seem to be enough).

**Comment by tn3rb** [comment]
I've estimated 8 hours for this (plz give feedback if that does not seem to be enough)
