### ISSUE TITLE
Rename ID Fields to GUID and EntityID Fields to Just ID

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#1932]
In order to differentiate between the GUIDs required by Apollo and the integer IDs used by the server side PHP Models, we currently have used the following schema:

- GUIDs: `id`
- DB IDs: `${entityType}Id` (ex: `ticketId`)

this is fine but does require you to have to construct the DB ID field names by concatenating the entity Type (event, datetime, ticket, etc) with the string `Id`.

I **JUST** realized that it would have been far easier and potentially less error prone to just use the following schema instead:

- GUIDs: `guid`
- DB IDs: `id`

:facepalm:

which would allow for logic to operate on entities without having to know the actual entity Type:

```js
const entityGuid = entity.guid;
const entityId = entity.id;
```

Despite it being a fairly significant task, I think it would be worth our while to correct this sooner rather than later as it simplifies a lot of code going forwards.

[EDIT]
another option I think I like better is to use explicit naming for both fields, ie:

- GUIDs: `GUID`
- DB IDs: `DBID`

or for the DB IDs maybe `PID` meaning Persistence ID.

@nicolad thought of another really good reason for doing this, which is it allows common logic pertaining to those fields to be extracted into a common location and then added as needed using composition.

**Comment by manzoorwanijk** [comment]
It's not recommended that we should use `guid` for global IDs. WP GraphQL uses `id` for all the global IDs, especially for CPTs like `Event`, `Venue` etc. and also expects that ID when mutating them. Also, Apollo expects it to be `id`, although we can change it in Apollo but it involves many other unnecessary overheads which are not worth the effort.
Alternative:
We could use `id` for global IDs and `_id` for DB IDs. i.e.
```js
const entityGuid = entity.id;
const entityId = entity._id;
```

**Comment by tn3rb** [comment]
Thanks for the feedback Manzoor, I didn't comment here on the issue, but had wondered in chat if there was a technical reason for things being the way they are.

> We could use `id` for global IDs and `_id` for DB IDs

I don't think `_id` is immediately clear as to what it is, so I would prefer something like `dbid`, but am still (as always) open for other suggestions

**Comment by manzoorwanijk** [comment]
Yeah I am OK with `dbid` or may be `intId` to make it even more clear.

**Comment by mnelson4** [comment]
> or may be intId to make it even more clear.

FYI not all the rows in the DB use ints for their primary keys eh- eg the country table uses a 2 character string for its primary key (`CNT_ISO`).
