### ISSUE TITLE
Using Event shortcodes in 3rd party plugins

### ISSUE THREAD

**Issue by gborbonus** [eventespresso/event-espresso-core#194]
> Before submitting your issue, please ensure that what you are reporting is specific to Event Espresso 4.

When submitting an issue, please follow this rough guideline for your report.

### Is this a bug report?

* [ ] yes
* [x ] no

### Please include any links to the page(s) demonstrating this issue (if possible).

ok. So I know this isn't an "issue" but rather some clarification/help. 
I was directed here from a forum post in the premium support forum.

It was to ask for specific info, but my question isn't really specific.

what I'm looking to do is parse a 3rd party message, I've built a plugin for waitlist, it works great.
However, I would like to be able to parse the same shortcodes that EE uses in their messages through my 3rdparty messages.

Any of you guys able to help?

**Comment by nerrad** [comment]
Hi Greg,

The shortcode parser is fairly specific to our messages system but it _can_ be adapted for third party parsing.  What you'll want to look at is the following:

- [`EEH_Parse_Shortcodes`](https://github.com/eventespresso/event-espresso-core/blob/master/core/helpers/EEH_Parse_Shortcodes.helper.php) which is used to trigger the parsing of shortcodes and return the parsed string.   Note the main method you'd likely be concerned with is `EEH_Parse_Shortcodes::parse_message_template` which would take care of kicking off the parsing. Note the dependencies it has as arguments (this is where its tied specifically to the messages system).
- Shortcode Parser classes (these are the classes that actually parse the shortcodes), they are loaded on demand via the shortcode parser helper). https://github.com/eventespresso/event-espresso-core/tree/master/core/libraries/shortcodes.

From those two things you should be able to trace the code flow and find what you need.

**Comment by gborbonus** [comment]
Thanks nerrad, I appreciate it.

**Comment by gborbonus** [comment]
ok, I've followed the logic, but Holy shit there's a lot of instance and object creation. 

I can see all the logic being used to make sure the message type is valid and so on, but damn that's a lot of doubling up on validation checks.

**Comment by nerrad** [comment]
Would **really** appreciate specific cases where you see there's unnecessary doubling up of checks happening or other "huh?" code.  Keep in mind this has been evolving code from when it was first written.  So there's definitely improvements we've been making over time (that you likely are not aware of because of the amount of code there is :) ).  

That's why having extra eyes looking at things and pointing out _specific_ wtf stuff you see is more helpful vs, "holy shit there's a lot of instance and object creation" :)
