### ISSUE TITLE
Global Date & Time Format Constants Config

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#1942]
- create centralized file for defining the various date and time formats required throughout the system
 - make config available via ConfigContext
 - import into any and all classes that are currently setting date related constants (formats, etc) and update logic to use new config constants 

I've estimated 4 hours for this (plz give feedback if that does not seem to be enough)

**Comment by nicolad** [comment]
As commented here: https://github.com/eventespresso/event-espresso-core/pull/1995#discussion_r356197828
the last item from the description cannot be done now
