### ISSUE TITLE
Use Global Timezone Data Config to Convert To & From UTC

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#1943]
- create centralized file for defining the various Timezone related constants required throughout the system
 - make config available via ConfigContext
 - import into any and all classes that are currently handling date related logic and update to use new config constants as needed.

#### **IMPORTANT**
We want **ALL** of our logic to be operating on dates that are in UTC so that there are never any issues with offsets when performing calculations. Therefore we want to **ALWAYS** do the following two things:
 - convert from UTC to localized time at the absolute last moment prior to display
 - convert from localized time to UTC immediately upon receiving user input and prior to performing any kind of other logic in dates

I've estimated 4 hours for this (plz give feedback if that does not seem to be enough)

**Comment by nicolad** [comment]
@tn3rb seems like this is also blocked by https://github.com/eventespresso/event-espresso-core/issues/1937 ? :)
