### ISSUE TITLE
EDTR: FRAGMENTS FTW!!!

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#1950]
Extract common query logic into fragments and reuse everywhere.

If we convert all of the entity specific id fields like `priceId`, `ticketId`, etc into something like `dbid` then we can likely have a fragment for `id` && `dbid`

**Comment by manzoorwanijk** [comment]
> we can likely have a fragment for `id` && `dbid`

That won't be possible because each fragment is defined for a particular type. For example
```gql
fragment priceAttributes on Price {
    ...
}
```
is defined for type `Price`
