### ISSUE TITLE
EDTR: Extract Initialization Toaster Logic

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#1951]
Extract repetitive Toaster logic for initialization queries into a custom hook and import where needed.

ie: ALL of the following could be moved into a hook, that receives values for `loadingMessage` and `successMessage`:

```js
const [initialized, setInitialized] = useState(false);
const toaster = useToaster();

onCompleted: () => {
	toaster.dismiss(loadingMessage);
	toaster.success(successMessage);
},
onError: (error) => {
	toaster.dismiss(loadingMessage);
	toaster.error(error);
},
```

the following could be packaged into some kind of `initializationNotices` callback,
that the consuming component would pass values to for `loadingFlag` and `loadingError`
```js
if (!initialized) {
	toaster.loading(loadingFlag, loadingMessage);
	toaster.error(loadingError);
}
useEffect(() => {
	if (!initialized && !loadingFlag) {
		setInitialized(true);
	}
}, [initialized]);
```

and the hook would return an object containing:

```js
{
    onCompleted,
    onError,
    initializationNotices,
}
```

estimating 8 hours for this

**Comment by nicolad** [comment]
@tn3rb this is a bit related and we might take advantage of this approach: https://github.com/withspectrum/spectrum/blob/alpha/src/actions/toasts.js
