### ISSUE TITLE
Add authentication layer to GQL

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#1952]
To authenticate certain GQL requests, we have to add an authentication mechanism. We have the following choices:
- Add `_wpnonce` as query param.
- Use `X-WP-Nonce` header. (Best for EDTR)
- Use JWT authentication.

estimating 16 hours for this because expecting JWT to have some nuances involved with utilizing it

**Comment by manzoorwanijk** [comment]
Already done using `X-WP-Nonce` in `HttpLink` for `ApolloClient`
