### ISSUE TITLE
Create EventProvider

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#1955]
Considering we are working on the **Event** editor, having access to the event dataz is going to be a common requirement, especially after we start converting other sections of the editor over to React. 

Therefore we should create a Context Provider for making the Event ID available, which can then be used to obtain the Event data from the Apollo client (via another hook?).

The Event ID can be set in `/assets/prototype/domain/eventEditor/index.js` when the provider is applied, and the file should go in `assets/prototype/infrastructure/services/contextProviders`.

**Comment by nicolad** [comment]
Based on slack discussion, we need to avoid accessing `eventId` directly from the DOM.
We can get it either from Apollo cache after rehydration or from a context provider.

**Comment by tn3rb** [comment]
this PR will also need to update `assets/prototype/domain/eventEditor/containers/queries/useEventId.js` to pull from the new Provider after #1964 gets merged.
