### ISSUE TITLE
Investigate Console Warning

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#1957]
Getting this warning in the console after the datetimes are initialized but before the tickets are initialized:

```
backend.js:6 Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state. 
    in EventEditor
```

**Comment by nicolad** [comment]
The problem is partially solved, I will need to get back after we are done with hydration.
I didn't want to spend too much time on this in PROTO phase.
cc @tn3rb @manzoorwanijk
