### ISSUE TITLE
Add types to useCreateDateMutation.

### ISSUE THREAD

**Issue by nicolad** [eventespresso/event-espresso-core#1960]
`useCreateDateMutation` is returning a function. We need to add types for that function.
Then in `AddNewDateModal` we might want to set arguments explicitly like this:
```
const AddNewDateModal = ({ eventId, tickets, handleClose, isOpen }) => {
	const createDate = useCreateDateMutation({ eventId });
	const onSubmit = ({ description, name, tickets }) => createDate({ description, name, tickets });
.
.
.
```

**Comment by manzoorwanijk** [comment]
No more relevant after #2034 got merged because this hook is now deleted.
