### ISSUE TITLE
Add types for useCreatePriceMutation

### ISSUE THREAD

**Issue by nicolad** [eventespresso/event-espresso-core#1962]
Right now `useCreatePriceMutation` isn't imported yet, so we can do the following changes:
- Change from `useCreatePriceMutation.js` to `useCreatePriceMutation.ts` in order to be able to use types.
-  Add type or interface for `onCreateHandler`

**Comment by nicolad** [comment]
If at the moment when this issue will be implemented the `useCreatePriceMutation` will be imported in a component, then we need to convert that component from `.js` to `.tsx`

**Comment by manzoorwanijk** [comment]
No more relevant after #2034 got merged because this hook is now deleted.
