### ISSUE TITLE
Add type safety for `useCreateTicketMutation`

### ISSUE THREAD

**Issue by nicolad** [eventespresso/event-espresso-core#1963]
We need to have the same approach as in this issue: https://github.com/eventespresso/event-espresso-core/issues/1962
*** 
In addition to that we need to convert `AddNewTicketModal.js` file to a `.tsx` file as I did here:
https://github.com/eventespresso/event-espresso-core/blob/EDTR/master/assets/prototype/domain/eventEditor/datesList/dateCard/DeleteDateButton.tsx

this way we will benefit of TS features

**Comment by manzoorwanijk** [comment]
No more relevant after #2034 got merged because this hook is now deleted.
