### ISSUE TITLE
Invalid structured data

### ISSUE THREAD

**Issue by csomers** [eventespresso/event-espresso-core#197]
> Before submitting your issue, please ensure that what you are reporting is specific to Event Espresso 4.

When submitting an issue, please follow this rough guideline for your report.

### Is this a bug report?

* [ x] yes
* [ ] no

### What branch did this occur in?
4.9.26p

### What version of WordPress is on the site this issue happened?
4.7

### Outline the steps to reproduce
It appears that the new "Schema.org Structured Data" feature doesn't escape quote marks in the event data, so it fails to produce valid JSON if the event has quotes in the description. 

### Please include any screenshots ar screencasts that can help illustrate the issue (if possible).
Run an event with quotes in the description through Google's "structured data testing tool" and it fails.

**Comment by PunchRockgroin** [comment]
Just researching this myself.

It looks like at line 43 of core\helpers\EEH_Schema.helper.php the $event->description() could be wrapped by esc_js() [https://developer.wordpress.org/reference/functions/esc_js/](url)

**Comment by PunchRockgroin** [comment]
On second thought, if you apply to line 23 of core/templates/json_linked_data_for_event.template.php

`"description": <?php echo json_encode(apply_filters('the_content', $event_description)) ?>,`

That should perform the the filter to render content, and apply the proper json encoding for that string.

FYI not a fan of using a string template to generate json but I get why you did it.

**Comment by joshfeck** [comment]
Thanks for reporting. There's a branch that addresses this and it's been assigned to support for testing:

https://github.com/eventespresso/event-espresso-core/tree/BUG-10411-add-escaping-event-structured-data

**Comment by joshfeck** [comment]
Update: The branch was merged to master and deleted.
