### ISSUE TITLE
Create TicketsListFilterStateHandler

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#1998]
- logic and components for filtering the tickets list needs to be copied over from its previous location in EDTR v1:

```
assets/ZZZ/editor/events/tickets/editor-ticket/filter-bar
```
into 
```
assets/prototype/domain/eventEditor/tickets/filterBar
```

- dependencies need to be updated to reflect path changes

- business logic needs to be separated from UI components

- props need to be converted from JS models to new GQL Types

- add TS Interfaces/Types for all known props and callbacks

**Comment by tn3rb** [comment]
@manzoorwanijk
can you plz break this issue up into smaller sub-tasks?
you can simply list items here and I can create the issues for them, but I will need to know some kind of rough estimate for each item, either 2, 4, or 8 hours (again totally rough, and plz be generous and give yourself more than enough time, it's not a race)

**Comment by nicolad** [comment]
@tn3rb I was thinking to pull out this step:
- add TS Interfaces/Types for all known props and callbacks

I wanted to make it work first and then apply types, because there might be some changes after list/ grid view components will be copied over.
