### ISSUE TITLE
Custom Payment Method Gateway 

### ISSUE THREAD

**Issue by getcoderzone** [eventespresso/event-espresso-core#201]
I'm Using Custom Payment Gateway . 
but i have face some problem . 

public function handle_payment_update($update_info, $transaction) {
    
    add_filter( 'FHEE__EES_Espresso_Txn_Page__run__exit', array( $this, 'send_ok' );
return $payment;
}
//sends back OK to paysera upon receipt of an IPN and informs the transaction page shortcode to exit
function send_ok() {
    echo "OK";
    return true;
}

**My Problem :**

How can i use this send_ok()  method ?   in my another notification page

Array
(
    [uts] => 1485870278
    [step] => payment_options
    [action] => process_gateway_response
    [selected_method_of_payment] => pagseguro_payment_method_offsite
    [spco_txn] => 15998
    [uses_separate_IPN_request] => 
    [status] => PAP
    [post_id] => 
    [post_name] => registration-checkout
    [post_type] => 
    [is_espresso_page] => 1
)

actually how can i add new array value in my payment notification page . 
that means when payment complete then added new array value .

**Comment by getcoderzone** [comment]
I'm using pagseguro payment gateway . 
when payment complete in pagseguro then i got payment status . 
so actually  i need when i got payment status approve then  Update EE payment status Approve  if i got payment status fail then Update EE Payment status Pending . 

Please please please help me .

**Comment by getcoderzone** [comment]
I already know its not event expresso problem  but i need your help .

**Comment by mnelson4** [comment]
hey @getcoderzone.
So you want to receive an IPN from pagseguro, update the payment in EE accordingly, and then tell pagseguro the request was received fine, right?
First, make sure you've configured your gateway class to receive IPNs in a separate request. Eg you probably have a class named `EEG_Paygseguro`. In its constructor add `$this->set_uses_separate_IPN_request( true ) ;`. That tells EE your gateway class expects to receive IPNs in separate requests (as opposed to some which get payment information immediately as the user returns from the gateway's server).
Next, inside your gateway class' `handle_payment_update`, you will need to look up the payment in EE. The simplest way to do that is to use `$payment = $transaction->last_payment();`. That will fetch the most recent payment for the transaction (which is usually the payment you want to update, but not necessarily. It would be better if you had passed a unique identifier to the pagseguro then sending them payment information, and then stored it on the EE payment using `$payment->set_txn_id_chq_nmbr()` during the `set_redirection_info()` method, and then hopefully pagseguro would pass that same identifier along with the IPN, then you could look up the EE payment using `$this->_pay_model->get_payment_by_txn_id_chq_nmbr()`, but I'm unfamiliar with pagseguro so I'm not sure if that's possible).
After you have found the EE payment, call `$payment->set_status( $this->_pay_model->approved_status())` if the `$update_info` indicated it was successful, or `$payment->set_status( $this->_pay_model->declined_status())` if it failed.
And lastly, if pagseguro expects your IPN-handling page to respond "ok", you'd use the code you posted originally.
Make sense? Closing for now unless you have more questions

**Comment by mnelson4** [comment]
You were probably aware, but https://github.com/eventespresso/event-espresso-core/blob/master/docs/L--Payment-Methods-and-Gateways/overview-payment-methods-and-gateways.md and https://github.com/eventespresso/event-espresso-core/blob/master/docs/L--Payment-Methods-and-Gateways/creating-a-payment-method.md also have some info which might be helpful to you
