### ISSUE TITLE
Find the cause of state update on unmounted components

### ISSUE THREAD

**Issue by manzoorwanijk** [eventespresso/event-espresso-core#2013]
When a Datetime or Ticket is deleted, a warning is shown `Can't perform a React state update on an unmounted component.`
![image](https://user-images.githubusercontent.com/18226415/70624133-a2ed4000-1c45-11ea-9119-1cd1a77a5495.png)

**Comment by manzoorwanijk** [comment]
It might be caused by the Entity context providers.

**Comment by nicolad** [comment]
Although this is an older article, it might shed some light: https://www.robinwieruch.de/react-warning-cant-call-setstate-on-an-unmounted-component

**Comment by tn3rb** [comment]
Fixed in #2034
