### ISSUE TITLE
Error when editing attendee information coming from thank you page

### ISSUE THREAD

**Issue by briandukes** [eventespresso/event-espresso-core#203]
> Before submitting your issue, please ensure that what you are reporting is specific to Event Espresso 4.

When submitting an issue, please follow this rough guideline for your report.

### Is this a bug report?

*  yes
* [ ] no

### What branch did this occur in?

master

### What version of WordPress is on the site this issue happened?

4.7.2

### Outline the steps to reproduce

Register for an event and then on the thank you page click on edit attendee to go back and edit attendee information. When clicking on Update Attendee Information I get Unable to save registration form data for the form input for all the inputs on the form. I have checked and verified that no questions appear on the form twice (found in some older posts that may be the cause).

### Please include any screenshots ar screencasts that can help illustrate the issue (if possible).

I have done some looking into this and I think the issue is on line 1058 in the EE_SPCO_Reg_Step_Attendee_Information class where it sets the $answer_cache_id variable. When editing the attendee information the $this->checkout->reg_url_link is set since it came from checkout however it looks like it should set the cache id to be $form_input. '-' . $this->checkout->reg_url_link . Making that change fixes everything with editing the attendee.

### Please include any links to the page(s) demonstrating this issue (if possible).

Everything was done locally so dont have any public urls to provide, if this cant be reproduced I can provide access to public url.

**Comment by joshfeck** [comment]
Can you provide access to a public URL? We're not able to reproduce this.

**Comment by briandukes** [comment]
Hi, 

I have done some more tracing through the code and debugging the issue I was having and ended up figuring out where my problem was and what was causing it.

I had created custom system questions for the site (there were actually created in 3.0 then migrated to 4.0) which is where the issues were coming from. When a form input gets passed to the _save_registration_form_input function the answer cache id would only be for updating the answers table. For example when the fname input comes in when editing an entry the answer object will never get updated since the $this->_registration_answers array keys are built with the reg_url_link in them. This creates a scenario where the custom system fields can be originally saved, but can't be found when going back to edit them.

After getting a full overview of what is going on here, I understand that this is probably set up in the way that it is so that editing attendee information will update the attendee_meta table and not the answers table. I have updated my code to use the FHEE__EE_Single_Page_Checkout__process_attendee_information__valid_data_line_item filter and filter the valid data passed so that it alters the array_keys and appends the reg_url_link to my custom fields so that they will save properly when edited. 

This has fixed the problem that I was having here so I will go ahead and close out this issue. Sorry for taking up your time and thanks for checking into this for me.

**Comment by tn3rb** [comment]
no worries, and glad to hear that things are working for you.
Ironically enough, it appears that the ternary you pointed out may be incorrect (it sure seems more logical the way you suggested rearranging things) but regardless of which way it was set, the data ultimately ended up getting saved correctly. That said, I think the objects within the system are *more* correct if the ternary is set up the way you suggested, so I may go ahead with that change.

That said, you would *still* need to have the reg_url_link as part of the answer cache id regardless, so the changes you just described would still be necessary.
