### ISSUE TITLE
Extract Search Text Logic from EDTR v1

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2038]
EDTR v1 used `useFilterEntitiesBySearchText` in `assets/ZZZ/components/ui/entity-list-filter-bar/use-filter-entities-by-search-text.js` for executing text field searches.

This logic needs to be moved over to the EDTR prototype but should be moved to a more generic non-domain location such as `assets/prototype/application/services` and renamed to something like `EntityTextFieldSearch` (other ideas???).

As well, it would be beneficial to refactor the logic in that function as follows:

- receive an array of entity fields to search instead of just one
- detect the field value type and react accordingly, for example: detecting date fields and comparing `toString()` versions of the date against search terms
- adding TS interface for props
- adding a tests folder and unit test to validate logic using an array of varied search terms run in a loop

**Comment by nicolad** [comment]
as per slack discussion, the conclusion is - `search dates as well as titles`;
we might want to add later searching through other fields, like `description`, etc
