### ISSUE TITLE
Extract DatesList Filter Logic from EDTR v1

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2039]
EDTR v1 used a variety of functions founds in `assets/ZZZ/editor/events/dates-and-times/editor-date/filter-bar/date-entities-list-filter-utils.js` for filtering the dates list. 

This logic needs to be moved over to the EDTR prototype but should have as much of its logic as possible extracted and moved to `assets/prototype/domain/shared/predicates/datetimes` and broken down as granularly as possible and then recomposed into logical blocks that can be shared throughout the application. 

As well, plz:

- add TS interface for props for any components
add a tests folder and unit test to validate filter logic using an array of varied datums run in a loop

**Comment by nicolad** [comment]
Tests are extracted into this issue: https://github.com/eventespresso/event-espresso-core/issues/2091
