### ISSUE TITLE
Custom Question Type

### ISSUE THREAD

**Issue by dysert** [eventespresso/event-espresso-core#204]
### Is this a bug report?
* [ ] yes
* [x ] no

### What branch did this occur in?
4.9.28

### What version of WordPress is on the site this issue happened?
4.7.2

On our event registration form,  I have a question for Student ID numbers, which have a format of A00000000 (The char A, followed by 8 digits). How can I make a custom question type for this?

**Comment by tn3rb** [comment]
You can create custom questions in the Event Espresso - Registration Form admin page.

Just so you know, for general support questions please visit the [Event Espresso support](https://eventespresso.com/support/) page on our website. This GitHub repo is for developer support

**Comment by dysert** [comment]
I am not asking about custom questions, I'm asking about custom question TYPES - text, us_phone, etc. I need a new one that validates data to the pattern listed above. 

I originally posted the question on that forum, and was told to post it here.

**Comment by tn3rb** [comment]
ahhh kk... 
you can see the list of existing EE input types in the ` core/libraries/form_sections/inputs/ ` folder,
and a list of "normalization" strategies in ` core/libraries/form_sections/strategies/normalization/ `

So the first thing you are going to want to do is create a new normalization strategy that uses some sort of regex to validate and sanitize your input to ensure that it matches what you want.

Then, your best bet would be to extend the ` EE_Text_Input ` class and override  what normalization strategy is set for that input type., and use the new one you just created.

Finally, check out this snippet which shows you how to inject your new input type into the rest of EE:
https://github.com/eventespresso/ee-code-snippet-library/blob/master/checkout/mn_add_question_type.php

**Comment by mnelson4** [comment]
You could alternatively use the `EE_Text_Validation_Strategy` which accepts a regular expression as an argument, and then applies that validation both in client-side javascript and server-side PHP. You can see the input ``EE_Phone_Input`` uses it.
