### ISSUE TITLE
Add Date to Event Checkin DropDown

### ISSUE THREAD

**Issue by JRyven** [eventespresso/event-espresso-core#205]
### Is this a bug report?

* [ ] yes
* [X] no

Referred from EE Forum: https://eventespresso.com/topic/add-date-to-event-checkin-dropdown/#post-231591

### What branch did this occur in?
Main

### What version of WordPress is on the site this issue happened?
All

### Outline the steps to reproduce
I manage a site that has a lot of events that have the share the same name (title). The administrators of the site manually check in registrants. Right now - they may have 4-8 events that share a title, and can not distinguish between the events to select the correct event. 

I’d like to try to modify the dropdown to include the event date so that it is easier to distinguish.

Can you direct me to the file where the dropdown is generated?

And do you already know of any nearby hooks that would be useful?

I'm happy to post my results here, when I achieve the goal.

### Please include any screenshots ar screencasts that can help illustrate the issue (if possible).
![Image of Event Checkin DropDown](http://midamericaosha.org/wp-content/uploads/2017/01/checkinsearch.png)

**Comment by nerrad** [comment]
Hi there,

This dropdown is generated by the `EE_Event_Registrations_List_Table::_get_table_filters` method.  Currently there's no filter that allows you to modify what gets printed for the event name but that would likely be the best way to accomplish what you want to do.  If you've figured out where the best location for a filter is for your needs you can submit a pull request and we'll consider it for inclusion in the plugin.

**Comment by nerrad** [comment]
Closing due to lack of response.
