### ISSUE TITLE
Iterate over the PossibleRelation type

### ISSUE THREAD

**Issue by nicolad** [eventespresso/event-espresso-core#2064]
As of Brent's comment from here: https://github.com/eventespresso/event-espresso-core/pull/2061#discussion_r359086494
I do agree that we might want to iterate over when we will have more entity types.

**Comment by tn3rb** [comment]
thought about this some more and realized the solution is likely pretty easy.

We just need to create an `Entitiy` interface in TS like:

```ts
interface Entity {
	id: string;
	dbid: number;
}
```

and then have all of our other entity types extend that:

```ts
interface TicketProps extends Entity {
	name: string;
	price: number;
	// etc
}
```
