### ISSUE TITLE
Event Espresso 4 Adding New Payment Method Payment incomplete issue

### ISSUE THREAD

**Issue by mangatsaini20** [eventespresso/event-espresso-core#212]
We have added a new payment method "Knet Payment Gateway" to Event Espresso plugin, We have used the new payment gateway Skeleton method to insert it. Every thing is fine the gateway is working properly but issue is that payment is done successfully but it shows payment is incomplete on frontend Thank you page as well as in admin section when we see the transaction status. 

We are unable to set the transaction status as complete if the payment is done successfully.
[new-payment-method.zip](https://github.com/eventespresso/event-espresso-core/files/834253/new-payment-method.zip)

I am using the payment method as "**New_Payment_Method_Offsite"**

The whole plugin files of new payment method is attached.

Please check do the needful help!!

Looking forward for your response!!

Thanks & Regards,
Mangat Saini
[new-payment-method.zip](https://github.com/eventespresso/event-espresso-core/files/834268/new-payment-method.zip)

**Comment by mnelson4** [comment]
@mangatsaini20 you haven't implemented `EEG_New_Payment_Method_Offsite` at all in there. There is no where to enter KNet gateway credentials (that should be implemented in `EE_PMT_NEw_Payment_Method`), it doesn't send the user to knet (assuming Knet is an offsite gateway, that should be set up in `EEG_New_Payment_Method::set_redirection_info()`), and it doesn't have any payment updating code (that should be happening in `EEG_New_Payment_Methd::handle_Payment_update()`). 

Please reread each of the docs at https://github.com/eventespresso/event-espresso-core/tree/master/docs/L--Payment-Methods-and-Gateways for instructions on how to transform the skeleton payment method you now have into a working payment method. 

Once you have used the renamer script (like mentioned here https://github.com/eventespresso/event-espresso-core/blob/master/docs/D--Addon-API/using-new-payment-method-addon-skeleton.md) and implemented the methods on `EE_PMT_New_Payment_Method_Offsite` and `EEG_NEw_Payment_Method_Offsite`, feel free to ask any follow-up questions. But for now, I don't see that you've actually implemented anything, so I'm going to close this ticket.
