### ISSUE TITLE
Update Date Range Picker & Friends

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2121]
- move `assets\prototype\domain\shared\dateRangeInput\DateRangePicker.js` into `assets\prototype\domain\shared\ui\components\input`
- convert to TS
- add tests

- move `assets\prototype\domain\shared\dateRangeInput\formatSelect.js` into `assets\prototype\application\utilities\date` (or maybe into a new `assets\prototype\application\utilities\formatters` folder)
- refactor `momentFormatter` to use `date-fns` lib and/or vanilla JS Date
- convert to TS
- add tests

- move `assets\prototype\domain\shared\dateRangeInput\momentDate.js` into new `assets\prototype\application\ui\components\display\dateTag` folder
- rename component to `DateTag` extract `MomentDateRange` into own file and rename to `DateRangeTag`
- refactor to use `date-fns` lib and/or vanilla JS Date
- convert to TS
- add tests

**Comment by nicolad** [comment]
@tn3rb I see that this has been removed from sprint 2 days ago.
what is the status on this, is still relevant to current sprin?

**Comment by nicolad** [comment]
![image](https://user-images.githubusercontent.com/1477453/74428429-a6798f00-4e61-11ea-81f2-fd9f8d098a40.png)

**Comment by manzoorwanijk** [comment]
Via #2253:
- `DateRangePicker` has already been converted to TS.
- `momentFormatter` has been converted to `dateFormatter` using `date-fns`

**Comment by tn3rb** [comment]
ok great thnx guys
