### ISSUE TITLE
Domain Initialization and Cache Hooks

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2122]
- create `assets\prototype\domain\eventEditor\data\queries\initialization`
- move the following files into above folder:
    - useCacheRehydration
    - useCacheRehydrationData
    - useInitQueries
- consider extracting logic from `useCacheRehydration` into separate files for different blocks of data (datetimes, tickets, etc) and possibly moving into `assets\prototype\domain\shared\data\queries\` for reusability on future admin screens
- add unit tests for the above files

**Comment by manzoorwanijk** [comment]
INMO, instead of putting that inside `/data/queries/initialization`, should go inside `/data/initialization`
