### ISSUE TITLE
Reconfigure Webpack

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2143]
In order to reduce and/or prevent conflicts with webpack  related logic from happening when merging EE's `master` branch into `EDTR/master`, we want to update our webpack config in `master` first to match any changes required for the EDTR project.

- cut PR branch from `master` (not `EDTR/master`)
- extract & organize webpack logic
- add separate config folders and files if/as needed
- trim dependencies
- reconfigure as needed

 ### IMPORTANT !!!

Any changes made must not disrupt the existing EE Gutenberg block logic located in:
- assets\src\blocks\event-attendees
- assets\src\components\event-attendees

as well as the logic in:

- assets\src\exit-modal-survey
- assets\src\wp-plugins-page

**Comment by nicolad** [comment]
This might or might not be relevant: https://betterstack.dev/blog/lerna-typescript-monorepo/#heading-base-typescript-configuration

**Comment by nicolad** [comment]
finally closed
