### ISSUE TITLE
Translation is so unreliable.

### ISSUE THREAD

**Issue by jonathan-dejong** [eventespresso/event-espresso-core#215]
Hi,

I've taken this up before. The translations for EE is always really unreliable. 
Whenever I update after a few months there is always some strings that are reverted back to english. For example at present time (with the latest version) this string wont translate:
`We're sorry, but all ticket sales have ended.`
I've followed the instructions here:
https://eventespresso.com/wiki/how-to-translate-event-espresso/#setup-your-language-files
And I do have a lot of translations working, but some don't and for some strings there's not even a translatable string found. 

Imagine my frustration when whenever we update I have to spend more time just locating failed strings and trying to fix them. 

### Is this a bug report?

* [x] yes
* [ ] no

**Comment by jonathan-dejong** [comment]
Btw the string above are in my .po file but translating it does nothing.

**Comment by nerrad** [comment]
Hi Jonathan,

So just for clarity, are you using a custom po file, or do you rely on the automatically updated po file that is sideloaded on updates?

**Comment by jonathan-dejong** [comment]
I'm using my original .po file and update it with the glotpress po file whenever there's strings not translated. So it's essentially the real glotpress file but with my own translations in it. 

Using poedit I catalog > update from pot file.

**Comment by nerrad** [comment]
Okay, so my _guess_ at this point is that we haven't updated glotpress with the latest strings yet.  I've started an internal discussion about this because we clearly need to do better with keeping our translation files up to date from any changes.

In the meantime I'm going to check with our team responsible for keeping glotpress up to date and see where we are with that.

**Comment by jonathan-dejong** [comment]
Thank you :)

**Comment by nerrad** [comment]
Hi Jonathan, our team has updated glotpress with the latest pot so the strings should be updated to match any changes in location in the codebase.  Can you regenerate your local po using what you get from our glotpress install and see if that fixes things for you?

**Comment by nerrad** [comment]
That is strange, and I _think_ this is the first I've heard of this issue.  Multisite basically uses all the same files so I'm not sure why it wouldn't work there.

I wonder if this may have something to do with the new user locale admin setting that WordPress introduced in one of its updates.  Does the subsite have the same locale set for that site as the language file?  Is the user accessing that subsite have the same locale set as the language file?

**Comment by jonathan-dejong** [comment]
So multisite should use the files in the uploads/espresso dir? Not uploads/sites/n/espresso?

I've specifically set Swedish for both the website and my logged in user but the string remains untranslated. 

The files is named `event_espresso-sv_SE`. Both an .po and .mo. They are located in wp-content/uploads/espresso/languages as well as in wp-content/uploads/sites/n/espresso/languages.
In the .po there are the string and it seems translated:
```
#: event-espresso-core/modules/ticket_selector/DisplayTicketSelector.php:257
msgid "We're sorry, but all ticket sales have ended."
msgstr "Tyvärr biljettförsäljningen är stängd"

```
The string exists in the place given above:
```
$no_ticket_available_msg = esc_html__( 'We\'re sorry, but all ticket sales have ended.', 'event_espresso' );
```

**Comment by nerrad** [comment]
Ya so specifically, translations are controlled/registered by the `EE_Load_Textdomain` class (`/core/EE_Load_Textdomain.php`).   I see that it prefixes the language directory with the values from `wp_upload_dir()` to determine the location of the files (via constants that are defined earlier).

What you might want to try doing, is add some debugging to `EE_Load_Textdomain::load_textdomain` and see what folder its looking in for the language file on the site in question.

**Comment by tn3rb** [comment]
all of our .mo files were updated recently, so hopefully this isn't an issue anymore.
going to close this, but plz feel free to reopen if things have not improved.
