### ISSUE TITLE
(maybe) Extract ALL Data Handling from UI Components

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2152]
As the last step before moving over the UI components from EDTR v1, we _may_ want to consider adopting the `Data Container => UI Component` pattern where all data handling logic is completely decoupled from UI components and moved into a separate file that then wraps the UI component and passes it the required props.

This will likely benefit us when we get to writing tests for our UI components because we will be able to separate the different scopes and use regular tests for the data containers and snapshots for the UI components.

Typically this pattern is achieved by appending `Container` onto the end of the UI component's name for the wrapper component, for example:

- DatesList (UI only)
- DatesListContainer (data handling)

The thing I don't like about this is that your application files need to import the container component, so everything in your JSX tree has `Container` on the end of the name:

```jsx
const DatesList = ({ datetimes }) => (
	<>
		<DatesListFilterBarContainer />
		{datetimes.map((datetime) => (
			<DateCardContainer datetime={datetime} />
		))}
		<AddNewDateButtonContainer />
	</>
);
```

So I think I would prefer to do the reverse instead and append `UI` onto the end of the JSX only components:

```jsx
const DatesListUI = ({ datetimes }) => (
	<>
		<DatesListFilterBar />
		{datetimes.map((datetime) => (
			<DateCard datetime={datetime} />
		))}
		<AddNewDateButton />
	</>
);
```

Which introduces a lot less noise into the code, but I'm open for suggestions for something other than `UI` since that looks a bit funny (as does `Ui`).
Maybe `View` would be better (ex: `DatesListView`)?

Another option would be to use HOCs (which I normally don't like but they are somewhat appropriate for this)

```jsx
import withDatesListData from './withDatesListData';

export const DatesList = ({ datetimes }) => (
	<>
		<DatesListFilterBar />
		{datetimes.map((datetime) => (
			<DateCard datetime={datetime} />
		))}
		<AddNewDateButton />
	</>
);

export default withDatesListData( DateList );
```

The benefit of this approach is that you can use the default export for the actual application, but still use the direct export of `DatesList` for testing purposes, and for testing the HOC, you can pass a mock component that renders the passed props in a simple and direct way allowing you to mount the HOC and examine the rendered output to verify the results. That said, NOT using a **HOC** might be slightly easier to test because the Data Container simply wraps the UI component as opposed to being a function that returns an enhanced component.

What are your guys thoughts/opinions/ideas regarding this?

Any better suggestions?

**Comment by manzoorwanijk** [comment]
If we make use of containers' default export then it shouldn't really matter to strip off `Container` from the name when using it.

**Comment by nicolad** [comment]
I think @tn3rb's suggestion is a great idea.
Next, based on short experience with `@testing-library/react-hooks` it seems like it would be easier to test hook-based containers.
***
I am taking the original suggestion to a bit different route:

```sh
├── DatesList
│   ├── useContainer.ts
│   ├── useContainer.test.ts // maybe
│   ├── list.ts // or other name
│   └── index.ts
.
.     
└── TicketList
```

And the content of `index.ts` would be something like:

```
const DatesList = () => {
  const datetimes = useContainer();

   return (
        <>
		<DatesListFilterBar />
		{datetimes.map((datetime) => (
			<DateCard datetime={datetime} />
		))}
		<AddNewDateButton />
	</>
  )
}
```
UI tests might be done at `DatesListFilterBar` and `DateCard` level.
The e2e tests might cover the gluing of the components.

**Comment by nicolad** [comment]
That is a more or less raw proposal :point_up: 
But after we will bounce ideas off on this topic, we will have a nice decoupling and testability.

**Comment by tn3rb** [comment]
This doesn't completely extract the data handling though:

```jsx
const DatesList = () => {
  const datetimes = useContainer();

   return (
        <>
		<DatesListFilterBar />
		{datetimes.map((datetime) => (
			<DateCard datetime={datetime} />
		))}
		<AddNewDateButton />
	</>
  )
}
```

There's no way to reuse that or control what data it receives (like for testing).

Whereas I'm suggesting something like:


```jsx
// DatesList.tsx
const DatesList = ({ datetimes }) => {
   return (
        <>
		<DatesListFilterBar />
		{datetimes.map((datetime) => (
			<DateCard datetime={datetime} />
		))}
		<AddNewDateButton />
	</>
  )
}

export default DatesList;


// in DatesListData.ts
const DatesListData = () => {
	const datetimes = useDatetimes();
	const { isLoading, isError } = useStatus();

	const loading = isLoading(TypeName.datetimes);
	if (loading) return <LoadingIndicator message='loading dates...' />;

	const error = isError(TypeName.datetimes);
	if (error) return <ErrorIndicator error={error} />;

	return <DatesList datetimes={ datetimes } />;
}

export default DatesListData;
```

Then, as @manzoorwanijk commented, we import the default export from `DatesListData` as `DatesList`.

Another option, although a bit more convoluted, would be to pass the view to the data container:

```jsx
// in DatesListData.ts
const DatesListData = ({ ViewComponent }) => {
	const datetimes = useDatetimes();
	//  other code
	return <ViewComponent datetimes={ datetimes } />;
}

export default DatesListData;
```

which would then be used in the consuming component like:


```jsx
// top of file
import { DatesList, DatesListData } from './datesList';

	// later in component return 
	<DatesListData ViewComponent={ DatesList } />
```

This would give us total control over what is used both for the production code as well as during testing.
This way during testing, we can pass a "view" component that just outputs divs with IDs (or classes) that are keyed to the prop they are displaying, which would make it easier to target them during tests. For example:


```jsx
// TestView.tsx
const TestView= ({ datetimes }) => {
   return (
        <div>
		{datetimes.map((datetime) => (
			<div id={datetime.id}>{ datetime.name }</div>
		))}
	<div/>
  )
}
```

I don't know how much of a benefit that would be to us though.

**Comment by manzoorwanijk** [comment]
I like this apporach:
```jsx
const DatesList = ({ datetimes }) => {
   return (
        <>
		<DatesListFilterBar />
		{datetimes.map((datetime) => (
			<DateCard datetime={datetime} />
		))}
		<AddNewDateButton />
	</>
  )
}

export default DatesList;
```
It's a clear separation between data and view. Also, it makes testing much easier.

**Comment by nicolad** [comment]
For time being and for the scope of this issue I also would agree with the simple approach as suggested with `DatesListData`.
***
But I also do like the `ViewComponent` option, this reminds me of the inversion of control.
I've seen and used this before with Semantic UI with `as` prop, here is an example of component doing that: https://react.semantic-ui.com/elements/list/
Also `ant` has an interesting approach with listing: https://ant.design/components/list/
take a look at `renderItem` prop
side note: I am not saying that we should use antd, I just recalled seeing that pattern there.
Let's loop back on this topic(the inversion of control) after the proto.

**Comment by tn3rb** [comment]
from chat:

```
Brent Christensen: 11:45 AM
just a suggestion for the naming, what about:
├── DatesList
│   ├── View.ts
│   └── Data.ts
```
