### ISSUE TITLE
JS bug in latest version causes failure in editing an event.

### ISSUE THREAD

**Issue by jonathan-dejong** [eventespresso/event-espresso-core#216]
This also seem to cause all preexisting tickets to disappear?? Are they reliant on JS?
I can give you temporary admin access if you want

### Is this a bug report?

* [x] yes
* [ ] no

### What branch did this occur in?
Latest stable version

### What version of WordPress is on the site this issue happened?
4.7.n

### Outline the steps to reproduce
Go to an events admin and click the "create ticket" option. 
Check console.

### Please include any screenshots ar screencasts that can help illustrate the issue (if possible).

![skarmavbild 2017-03-13 kl 14 14 56](https://cloud.githubusercontent.com/assets/1508751/23855996/2522af7a-07f8-11e7-9802-4983f9ec3ed2.png)

**Comment by jonathan-dejong** [comment]
I'm attempting to reupload the latest version. The same issue does not occur on the mirror staging site with same plugins etc. active.

**Comment by nerrad** [comment]
I'm not able to reproduce this.

What file is your js screenshot from?

**Comment by jonathan-dejong** [comment]
It was resolved by reuploading the files :) 
Seems there was an issue with the first upload via FTP.
