### ISSUE TITLE
frontend claims there are no ticket falsely.

### ISSUE THREAD

**Issue by jonathan-dejong** [eventespresso/event-espresso-core#217]
After update it seems something has gone awry with the tickets.
Previously the tickets where nonexistent and I got the JS error in the other issue ticket. 
That resolved itself with a refresh of the files. 

But now we're seeing this. there is a ticket, it's locked somehow (maybe they should be) but the frontend say there are none.

### Is this a bug report?

* [x] yes
* [ ] no

### What branch did this occur in?
Latest stable

### What version of WordPress is on the site this issue happened?
Latest

### Outline the steps to reproduce
Updated EE to latest. thats it :)

### Please include any screenshots ar screencasts that can help illustrate the issue (if possible).
![skarmavbild 2017-03-13 kl 16 44 56](https://cloud.githubusercontent.com/assets/1508751/23862702/03872c86-080e-11e7-80da-451c87e63db7.png)
![skarmavbild 2017-03-13 kl 16 45 01](https://cloud.githubusercontent.com/assets/1508751/23862703/03877e48-080e-11e7-8cc2-d5cffdaba8e4.png)

### Please include any links to the page(s) demonstrating this issue (if possible).
http://kfsk.se/konferens/kurs-konferens/hr-dagen-offentlig-sektor-2017/

**Comment by tn3rb** [comment]
tickets get locked like that if you edit their price after registrations have been created using that ticket. This maintains the accuracy of the internal accounting. ie: raising the price to $15 after someone pays $10 for a ticket would throw off your accounting if you tried to count that registration as having paid $15.

Anyways, did you edit that ticket, either via the event editor or via custom code anywhere?
A possible scenario is if you edited the ticket price, then deleted the new ticket that was created (not saying that this is exactly what happened, but a case that would cause what you are seeing).

We have never seen this issue come up with anyone else before, so for the time being you can correct it by going directly into your db, finding that ticket in the "esp_ticket" table, and changing its "TKT_deleted" field from ` 0 ` to ` 1 `

If it happens again, we'll need to find out how your tickets are getting archived.

**Comment by jonathan-dejong** [comment]
Hi Brent,

Thanks for the reply.
Changing the TKT_deleted field from 0 to 1 did nothing I'm afraid. 
This behaviour happened after the update and seemingly to random (but plenty) of events. I can't find any correlation between them so far. 

I compared the values between a ticket that works and a ticket that's doing this and they are identical (except of course for dates, names and ticket_qty.

**Comment by jonathan-dejong** [comment]
I went through all events and turns out it was just this event and one other that had the issue. 
The other one I was actually able to reinsert the enddate on and update and it was fixed. For this we just created a second identical ticket as a substitute. 

Very strange issue but for now it's "solved".
