### ISSUE TITLE
Events displaying as sold out - no event sold but all tickets for event reserved

### ISSUE THREAD

**Issue by michalm123** [eventespresso/event-espresso-core#218]
> Before submitting your issue, please ensure that what you are reporting is specific to Event Espresso 4.

When submitting an issue, please follow this rough guideline for your report.

### Is this a bug report?

* [ x] yes
* [ ] no

### What branch did this occur in?
4.9.33.p and 4.9.32.rc.014

### What version of WordPress is on the site this issue happened?
4.7.3

### Outline the steps to reproduce
Using Multiple Event Registration plugin to add multiple events to a cart.
Create an event with multiple tickets - set the max ticket size to the max number of tickets available. So basically if you buy all of one type of ticket the event is sold out.
Go and select all the tickets forcing the event to be sold out by adding to cart. Never proceed to registration and go do something else. The tickets after a few repeats of this sequence of events are status sold out and never returned so effectively the event is sold out even though there are no tickets.

### Please include any screenshots ar screencasts that can help illustrate the issue (if possible).
Attached screen shot shows the issue and also that the event is "Open" as no one has registered.
http://prntscr.com/ejlanr

**Comment by tn3rb** [comment]
plz try this branch:
https://github.com/eventespresso/event-espresso-core/tree/BUG-10537-cart-ticket-reservations

**Comment by michalm123** [comment]
We started there and then Josh told us to post on the developer's 
network as the issue is just reproduced. It works for a bit and then the 
events get stuck and there is no releasing them.

Brent Christensen wrote:

**Comment by tn3rb** [comment]
So just to clarify... you **have** downloaded and activated the version of EE in this branch:
https://github.com/eventespresso/event-espresso-core/tree/BUG-10537-cart-ticket-reservations

If so, there is also a corresponding fix for the Multi Event Registration addon as well now, which you can access here:
https://github.com/eventespresso/ee4-mer/tree/BUG-10592-line-item-cancellation

**Comment by tn3rb** [comment]
closing issue as this has been released as part of 4.9.35
