### ISSUE TITLE
Cleanup old batch job data

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/event-espresso-core#2182]
## Issue Overview

Batch jobs store the job's progress in an option like 'ee_job_parameters_%'. They're not getting removed (or at least not consistently).
That's a small issue when they only stored less than a kilobyte of data, but with the cascading deletion feature they can get really big (like megabytes), so it's more important to clean them up.
Deleting the options is pretty easy (although it should probably be done in way that works with redis cached mambo-jumbo etc, so using WordPress' core functions would probably be good.)
The only trick is there's no timestamp on the options, so we don't know for certain if an option contains stale data.
I think running a cron task to delete the old ones would be good, maybe once a day, and just order them by ID and leave the most recent X in-place (because we don't want to delete an option for a batch process that's currently underway.)
I would be inclined to make a business class to perform this, and invoke it from `EE_Cron_Tasks`.

Thoughts on this @tn3rb ?

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Steps to Reproduce (for bugs)

* Generate a CSV report
* When its done, look at the newest row in `wp_options` table. It is probably `ee_job_parameters_...`.

## Expected Behaviour

* The job parameter options should be removed, at least daily

## Current Behaviour

* The option is left there. Forever it seems. Actually even when the job worked fine.

## Related Information:

I realized this was an issue on https://github.com/eventespresso/event-espresso-core/pull/2175

**Comment by tn3rb** [comment]
what about deleting any job files when the job is completed?

with regards to doing so via cron tasks, that's fine too although may not be reliable for all servers.

eventually I need to get to refactoring where/how our session data is stored, and will likely utilize a custom table for that.
At that point, we could most likely use the session to store job data using a special key or something.
Then we can properly timestamp all of the entries and run a garbage collector on it.

**Comment by mnelson4** [comment]
> what about deleting any job files when the job is completed?

That should have been happening, but wasn't. After you asked this, I finally investigated why, and it turned out to be an easy fix in my new code (see https://github.com/eventespresso/event-espresso-core/pull/2187/commits/893921c618e4ca68674e05454f63169d065ec1c7). 

> eventually I need to get to refactoring where/how our session data is stored, and will likely utilize a custom table for that.

Yeah that could work.

Given this should now be cleaning up after itself, the priority of adding a cron task to do this is significantly decreased; so much so that I don't think we really need a ticket for it (we may want to reopen it if it is a noticeable issue.)
