### ISSUE TITLE
Accessing EE ticket structure to figure out how long a ticket has been reserved.

### ISSUE THREAD

**Issue by michalm123** [eventespresso/event-espresso-core#219]
> Before submitting your issue, please ensure that what you are reporting is specific to Event Espresso 4.

When submitting an issue, please follow this rough guideline for your report.

### Is this a bug report?

* [ ] yes
* [x ] no

### What branch did this occur in?
4.9.32.rc.014, 4.9.33.p, and BUG-10537-cart-ticket-reservations branch

### What version of WordPress is on the site this issue happened?
4.7.3

### Outline the steps to reproduce
Our tickets are in sold out state even though the event is not sold out. The events are simply added to the cart and the user never proceeds to registration. We cannot release them even with the new maintenance tool (user logs out), caches emptied (every combination has been tested)

We would like to acess the EE ticket structure so we can write our own procedure to check for reserved tickets and how long the tickets have been reserved for. We want to set a timer and release tickets after x minutes and warn the user that they will lose their reservation if they don't complete it within a set time frame but aren't sure where to access this information. any and all help would be greatly appreciated.

**Comment by tn3rb** [comment]
plz try this branch first:
https://github.com/eventespresso/event-espresso-core/tree/BUG-10537-cart-ticket-reservations

**Comment by michalm123** [comment]
We did and we still had the problem

Brent Christensen wrote:

**Comment by tn3rb** [comment]
there is a corresponding fix for the Multi Event Registration addon as well now, which you can access here:
https://github.com/eventespresso/ee4-mer/tree/BUG-10592-line-item-cancellation

Plz also make sure to pull the latest changes for the EE4 core branch as well:
https://github.com/eventespresso/event-espresso-core/tree/BUG-10537-cart-ticket-reservations
