### ISSUE TITLE
Research Webpack Config and Package Bundle Best Practices

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2198]
Something is awry with our current webpack configuration as it seems to stall out during builds and/or takes to long to resolve.

So that needs to be fixed.

As well, we need to begin considering how we are going to assemble our packages and how assets will be delivered to the client.

These things need to be researched so plz spend some time looking into things and report back here with any relevant information and hopefully some insight and/or suggestions into how to move forwards with things.

**Comment by nicolad** [comment]
Monorepo:
- Pro
  - We might want to consider when/ if we'd go with RN. Example: https://github.com/newsuk/times-components
  - Would be an interesting solution if we'd have to support SSR and universal app: https://github.com/wixplosives/sample-monorepo/blob/master/packages/server/src/index.tsx
- Cons
  - Tricky CI setup(at least from what I've listened and read)
  - It is not trivial to integrate with our current webpack configs.

More info about monorepo: https://github.com/korfuri/awesome-monorepo

**Comment by nicolad** [comment]
Another option is to use multi-page apps with CRA's TS ejected configs.

**Comment by nicolad** [comment]
@tn3rb I think this can be closed since we are heading now with CRA way.
I'll close this to make less noise on the board, if you think it should not be closed, let me know and I will re-open.
