### ISSUE TITLE
EE Custom Payment Method when submit Update Settings showing error .

### ISSUE THREAD

**Issue by getcoderzone** [eventespresso/event-espresso-core#222]
Please see my forum support https://eventespresso.com/topic/ee-custom-payment-method-when-submit-update-settings-showing-error/#post-236589

Please Help me

**Comment by mnelson4** [comment]
Hi @getcoderzone! Ya that's coming along.

I installed your payment method, activated it, and updated its settings without getting that error message. I suspect your database got messed up when you renamed files etc.

You can either completely reset your Event Espresso data using the maintenance page's "reset" tab; or jut find your payment method's row in the `esp_payment_method` table and deleting it manually. Then try reactivating your payment method and updating it.

Also, I'd suggest renaming your payment method from `Pagseguro Transparent Payment Method Offsite` to just `Pagseguro Transparent`, as it's getting pretty long (and many of our strings append "Payment Method" onto the name anyway, making string super long).

Closing this as the above should resolve this specific issue you're having.
