### ISSUE TITLE
Price modifier surcharge conflicts with promotional code

### ISSUE THREAD

**Issue by hodyhong** [eventespresso/event-espresso-core#223]
> Before submitting your issue, please ensure that what you are reporting is specific to Event Espresso 4.

When submitting an issue, please follow this rough guideline for your report.

### Is this a bug report?

* [/] yes
* [ ] no

### What branch did this occur in?
Master

### What version of WordPress is on the site this issue happened?
4.7.3

### Outline the steps to reproduce

I have implemented a mandatory transaction fee for every transaction base on the code snippet from here:
https://github.com/eventespresso/ee-code-snippet-library/blob/master/checkout/bc_ee_apply_transaction_surcharge.php
It works perfectly except when an overall promotional code apply to transaction, the total price will calculate strangely. For example, if I put a 50% off promo code in, the Total will be 50% off (including the surcharge). However when I refresh the checkout page, the promote code will then only apply to everything except the surcharge. I believe the latter is the correct result, but why it is incorrect at first? I thought it might the priority of the applying the filter, but after a few test, not good outcome. Please find my code below:

```
function bc_ee_determine_whether_to_apply_surcharge() {
	// CHANGE $surcharge_QST_ID VALUE TO MATCH THE ID OF YOUR QUESTION
	$surcharge_QST_ID = 14;
	if ( isset( $_REQUEST[ 'ee_reg_qstn' ] ) ) {
		foreach ( $_REQUEST[ 'ee_reg_qstn' ] as $registrations ) {
			if ( ! empty( $registrations ) ) {
				foreach ( $registrations as $QST_ID => $response ) {
					if ( $QST_ID === $surcharge_QST_ID ) {
						switch ( $response ) {
							// CHANGE THESE TO EXACTLY MATCH THE ANSWER OPTIONS FOR YOUR QUESTION
							// THEN EDIT / ADD / DELETE THE FUNCTIONS BELOW
							// WHOSE NAMES MATCH THESE OPTIONS
							// YOU CAN ADD NEW OPTIONS, JUST MAKE SURE TO HAVE A CORRESPONDING
							// FUNCTION FOR SETTING THE SURCHARGE DETAILS
							case 'Ticket Transaction Fee' :
								// apply the surcharge
								add_filter( 'FHEE__bc_ee_apply_transaction_surcharge__apply_surcharge', '__return_true' );
								// hook into function below to set surcharge details
								add_filter( 'FHEE__bc_ee_apply_transaction_surcharge__surcharge_details', 'bc_ee_ticket_service_fee_surcharge_details' );
								break;
							
						}
					}
				}
			}
		}
	}
}
add_action( 'AHEE__EE_System__core_loaded_and_ready', 'bc_ee_determine_whether_to_apply_surcharge', 1 );
/**
 * EDIT THIS TO HOLD THE DETAILS FOR ONE OF YOUR ANSWER OPTIONS
 * @return array
 */
function bc_ee_ticket_service_fee_surcharge_details() {
	return array(
		'name'        	=> 'Ticket Transaction Fee',
		'code'        	=> 'ticket-transaction-fee',
		'description' 	=> 'service fee for online tickets',
		'unit_price'  	=> 3.00,
		'taxable'     	=> false,
	);
}

/**
 * DO NOT EDIT ANYTHING EXCEPT DEFAULT SURCHARGE DETAILS
 *
 * bc_ee_apply_transaction_surcharge
 *
 * @param \EE_Checkout $checkout
 * @return \EE_Checkout
 */
function bc_ee_apply_transaction_surcharge( EE_Checkout $checkout ) {
	// DEFAULT SURCHARGE DETAILS - EDIT THIS
	$surcharge_details = apply_filters(
		'FHEE__bc_ee_apply_transaction_surcharge__surcharge_details',
		array(
			//  name for surcharge that will be displayed, ie: 'printing fee'
			'name'        => 'Ticket Transaction Fee',
			// unique code used to identify surcharge in the db, ie: 'print-at-home-fee'
			'code'        => 'ticket-transaction-fee',
			// 'fee for printing tickets'
			'description' => 'service fee for online tickets',
			// surcharge amount
			'unit_price'  => 3.00,
			// whether or not tax is applied on top of the surcharge
			'taxable'     => false,
		)
	);
	// STOP EDITING
	// apply the surcharge ?
	if ( ! apply_filters( 'FHEE__bc_ee_apply_transaction_surcharge__apply_surcharge', false ) ) {
		return $checkout;
	}
	// verify checkout
	if ( ! $checkout instanceof EE_Checkout ) {
		return $checkout;
	}
	// verify cart
	$cart = $checkout->cart;
	if ( ! $cart instanceof EE_Cart ) {
		return $checkout;
	}
	// verify grand total line item
	$grand_total = $cart->get_grand_total();
	if ( ! $grand_total instanceof EE_Line_Item ) {
		return $checkout;
	}
	// has surcharge already been applied ?
	$existing_surcharge = $grand_total->get_child_line_item( $surcharge_details[ 'code' ] );
	if ( $existing_surcharge instanceof EE_Line_Item ) {
		return $checkout;
	}
	EE_Registry::instance()->load_helper( 'Line_Item' );
	$pre_tax_subtotal = EEH_Line_Item::get_pre_tax_subtotal( $grand_total );
	$pre_tax_subtotal->add_child_line_item(
		EE_Line_Item::new_instance( array(
			'LIN_name'       => $surcharge_details[ 'name' ],
			'LIN_desc'       => $surcharge_details[ 'description' ],
			'LIN_unit_price' => (float) $surcharge_details[ 'unit_price' ],
			'LIN_quantity'   => 1,
			'LIN_is_taxable' => $surcharge_details[ 'taxable' ],
			'LIN_order'      => 0,
			'LIN_total'      => (float) $surcharge_details[ 'unit_price' ],
			'LIN_type'       => EEM_Line_Item::type_line_item,
			'LIN_code'       => $surcharge_details[ 'code' ],
		) )
	);
	$grand_total->recalculate_total_including_taxes();
	return $checkout;
}
add_filter( 'FHEE__EED_Single_Page_Checkout___initialize_checkout__checkout', 'bc_ee_apply_transaction_surcharge');
```

**Comment by tn3rb** [comment]
will try to look at this this morning

**Comment by hodyhong** [comment]
Much appreciate it @tn3rb

**Comment by hodyhong** [comment]
Hi @tn3rb, hate to bother you. But have you got any update on this issue?
As we are holding back a major event launch, because we cannot get this to work properly. Is there any way we could prioritise this please?

**Comment by tn3rb** [comment]
It's a bug somewhere in core, but we have yet to isolate exactly where it is happening.
A ticket has been created and has already had a few hours of investigation, but it's impossible for me to say at this point how long it would take to fix, since we have still not been able to identify the exact cause.
I can say for certain that it is only an issue with the values being displayed and not what gets saved to the db.

**Comment by hodyhong** [comment]
Hi @tn3rb, could I temporarily disable the Ajax of applying the promote code, so the checkout page refresh instead of just updating the table. This way it won't show the incorrect figures? I can just use this before you can iron out the bug. Thanks

**Comment by tn3rb** [comment]
@hodyhong 
you could use the following filter to remove data from the JSON response that returns the HTML for the updated cart:

```'FHEE__EED_Promotions__generate_JSON_response__JSON_response'```

I would output what gets returned from that for a bit to figure out how to target the specific content you want removed.

**Comment by mnelson4** [comment]
hey @hodyhong we have created a branch that seems to fix the issue: https://github.com/eventespresso/event-espresso-core/tree/BUG-10654-fix-line-item-recalculate-total-including-taxes . We are just starting internal testing. Could you give it a try and report your findings?

**Comment by hodyhong** [comment]
Hey @mnelson4 appreciate the good work. I have tried out the branch and it appears to be working!
I will try out a bit more to see how I goes!

**Comment by hodyhong** [comment]
Further trialling I have discovered a new issue with the surcharge code. When I put in a promote code with dollar amount that may zero out the surcharge (rendering the ticket free basically). The check out will not proceed and error message will say the off site payment method is not configured properly. I was using PayPal express to test this.

**Comment by mnelson4** [comment]
> Hey @mnelson4 appreciate the good work. I have tried out the branch and it appears to be working!

Ok good to hear that issue is addressed on that branch, we'll work on getting that into master.

> Further trialling I have discovered a new issue with the surcharge code. When I put in a promote code with dollar amount that may zero out the surcharge (rendering the ticket free basically). The check out will not proceed and error message will say the off site payment method is not configured properly. I was using PayPal express to test this.

Let me make sure I understand the issue. E.g., if you have a $9 ticket, with a $1 surcharge, with no taxes, but a $10 discount gets applied, making the transaction total $0, and thus making it so no payment is needed, there is an error, right?

**Comment by hodyhong** [comment]
Spot on! @mnelson4 Basically, it won't process through no matter what payment method is selected.

**Comment by mnelson4** [comment]
huh, I'm not getting that problem @hodyhong. It skips the payment step entirely for me, as it should. What modifications have you made to the above code snippet?

**Comment by hodyhong** [comment]
That's strange, the only thing I have modified from the above code snippet was the name of the surcharge. Here is mine:
`function bc_ee_determine_whether_to_apply_surcharge() {
	// CHANGE $surcharge_QST_ID VALUE TO MATCH THE ID OF YOUR QUESTION
	$surcharge_QST_ID = 14;
	if ( isset( $_REQUEST[ 'ee_reg_qstn' ] ) ) {
		foreach ( $_REQUEST[ 'ee_reg_qstn' ] as $registrations ) {
			if ( ! empty( $registrations ) ) {
				foreach ( $registrations as $QST_ID => $response ) {
					if ( $QST_ID === $surcharge_QST_ID ) {
						switch ( $response ) {
							// CHANGE THESE TO EXACTLY MATCH THE ANSWER OPTIONS FOR YOUR QUESTION
							// THEN EDIT / ADD / DELETE THE FUNCTIONS BELOW
							// WHOSE NAMES MATCH THESE OPTIONS
							// YOU CAN ADD NEW OPTIONS, JUST MAKE SURE TO HAVE A CORRESPONDING
							// FUNCTION FOR SETTING THE SURCHARGE DETAILS
							case 'Transaction Fee' :
								// apply the surcharge
								add_filter( 'FHEE__bc_ee_apply_transaction_surcharge__apply_surcharge', '__return_true' );
								// hook into function below to set surcharge details
								add_filter( 'FHEE__bc_ee_apply_transaction_surcharge__surcharge_details', 'bc_ee_ticket_service_fee_surcharge_details' );
								break;
							
						}
					}
				}
			}
		}
	}
}
add_action( 'AHEE__EE_System__core_loaded_and_ready', 'bc_ee_determine_whether_to_apply_surcharge', 1 );
/**
 * EDIT THIS TO HOLD THE DETAILS FOR ONE OF YOUR ANSWER OPTIONS
 * @return array
 */
function bc_ee_ticket_service_fee_surcharge_details() {
	return array(
		'name'        	=> 'Transaction Fee',
		'code'        	=> 'ticket-transaction-fee',
		'description' 	=> '',
		'unit_price'  	=> 3.00,
		'taxable'     	=> false,
	);
}

/**
 * DO NOT EDIT ANYTHING EXCEPT DEFAULT SURCHARGE DETAILS
 *
 * bc_ee_apply_transaction_surcharge
 *
 * @param \EE_Checkout $checkout
 * @return \EE_Checkout
 */
function bc_ee_apply_transaction_surcharge( EE_Checkout $checkout ) {
	// DEFAULT SURCHARGE DETAILS - EDIT THIS
	$surcharge_details = apply_filters(
		'FHEE__bc_ee_apply_transaction_surcharge__surcharge_details',
		array(
			//  name for surcharge that will be displayed, ie: 'printing fee'
			'name'        => 'Transaction Fee',
			// unique code used to identify surcharge in the db, ie: 'print-at-home-fee'
			'code'        => 'ticket-transaction-fee',
			// 'fee for printing tickets'
			'description' => '',
			// surcharge amount
			'unit_price'  => 3.00,
			// whether or not tax is applied on top of the surcharge
			'taxable'     => false,
		)
	);
	// STOP EDITING
	// apply the surcharge ?
	if ( ! apply_filters( 'FHEE__bc_ee_apply_transaction_surcharge__apply_surcharge', false ) ) {
		return $checkout;
	}
	// verify checkout
	if ( ! $checkout instanceof EE_Checkout ) {
		return $checkout;
	}
	// verify cart
	$cart = $checkout->cart;
	if ( ! $cart instanceof EE_Cart ) {
		return $checkout;
	}
	// verify grand total line item
	$grand_total = $cart->get_grand_total();
	if ( ! $grand_total instanceof EE_Line_Item ) {
		return $checkout;
	}
	// has surcharge already been applied ?
	$existing_surcharge = $grand_total->get_child_line_item( $surcharge_details[ 'code' ] );
	if ( $existing_surcharge instanceof EE_Line_Item ) {
		return $checkout;
	}
	EE_Registry::instance()->load_helper( 'Line_Item' );
	$pre_tax_subtotal = EEH_Line_Item::get_pre_tax_subtotal( $grand_total );
	$pre_tax_subtotal->add_child_line_item(
		EE_Line_Item::new_instance( array(
			'LIN_name'       => $surcharge_details[ 'name' ],
			'LIN_desc'       => $surcharge_details[ 'description' ],
			'LIN_unit_price' => (float) $surcharge_details[ 'unit_price' ],
			'LIN_quantity'   => 1,
			'LIN_is_taxable' => $surcharge_details[ 'taxable' ],
			'LIN_order'      => 0,
			'LIN_total'      => (float) $surcharge_details[ 'unit_price' ],
			'LIN_type'       => EEM_Line_Item::type_line_item,
			'LIN_code'       => $surcharge_details[ 'code' ],
		) )
	);
	$grand_total->recalculate_total_including_taxes();
	return $checkout;
}
add_filter( 'FHEE__EED_Single_Page_Checkout___initialize_checkout__checkout', 'bc_ee_apply_transaction_surcharge');

`

**Comment by hodyhong** [comment]
Everything works fine except when I try to zero the total. That's when the payment won't accepted.

**Comment by tn3rb** [comment]
sry for the delay:
there is a branch that fixes this issue:
https://github.com/eventespresso/event-espresso-core/tree/BUG-10654-fix-line-item-recalculate-total-including-taxes
but it is still waiting to be tested.

Did you have any luck getting things working?

**Comment by tn3rb** [comment]
this is in the current master branch and will be part of the upcoming 4.9.46 release
