### ISSUE TITLE
Convert Shared Domain Components to TS

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2238]
- [ ] domain/eventEditor/shared/defaultDates.js
- [ ] domain/eventEditor/shared/RelationsSelector.js
- [ ] domain/eventEditor/shared/dateRangeInput/*
- [ ] domain/eventEditor/shared/entities/prices/defaultNewPriceModifier.js

**Comment by manzoorwanijk** [comment]
I already did it in #2259
