### ISSUE TITLE
Complete Unit Tests for Price Mutations

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2240]
- [ ] domain/eventEditor/data/mutations/prices/usePriceMutator
- [ ] domain/eventEditor/data/mutations/prices/useUpdatePriceCache

**Comment by manzoorwanijk** [comment]
See [this comment](https://github.com/eventespresso/event-espresso-core/issues/2239#issuecomment-575127536)

**Comment by tn3rb** [comment]
ya well... you see [this comment](https://github.com/eventespresso/event-espresso-core/issues/2239#issuecomment-575281684)
