### ISSUE TITLE
Complete Unit Tests for Ticket Mutations

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2241]
- [ ] domain/eventEditor/data/mutations/tickets/updatePriceCache
- [ ] domain/eventEditor/data/mutations/tickets/useTicketMutator
- [ ] domain/eventEditor/data/mutations/tickets/useUpdateTicketCache

**Comment by manzoorwanijk** [comment]
See [this comment](https://github.com/eventespresso/event-espresso-core/issues/2239#issuecomment-575127536)

**Comment by tn3rb** [comment]
no you see [this comment](https://github.com/eventespresso/event-espresso-core/issues/2240#issuecomment-575282391)
