### ISSUE TITLE
Convert Exit Modal Survey to React

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2250]
Currently the Exit Modal Survey JS depends on jQuery which means that has to be included in bundles when performing asset builds. It would be beneficial to remove that dependency as it is causing errors during builds

**Comment by nicolad** [comment]
After this issue is completed this line needs to be uncommented: https://github.com/eventespresso/event-espresso-core/pull/2210/files#diff-e389ed4107fbd6139ae8b315cb04e04dR95

**Comment by manzoorwanijk** [comment]
Tracking via #2781
