### ISSUE TITLE
Hello , I have some problems about EE4 API 

### ISSUE THREAD

**Issue by s31b18** [eventespresso/event-espresso-core#226]
Hello , first of all , is there any EE4 REST API endpoints can determine the invalid registration url_link (any text) and url_link of other events (may be not my event ,some event that I don't  have the permission to read it)?

 Since , I am now developing a QR Ticket Scanning Apps for my website which uses EE4 as my engine .Currently , I have designed  when the users use my apps to scan the Ticket's QR code , it will return the url_link and then I use the registration endpoint to get the registration url link for further processing.

However , i cannot find that when the user scan whatever invalid QR code or some qr code not my event and then i send the text to the registration endpoint to get the registration url link . Both will also return empty json

**Comment by mnelson4** [comment]
Hi @s31b18, so just to clarify: you want to differentiate between a registration URL being invalid and one that belongs to an event to which you don't have access, right?
There is no service over the EE4 REST API that does this explicitly. You could try to compare the `REG_url_link` to see if it has this format `1-479bd5546960dc568db1b1d142233e63`, that is one to three digits, a dash, and then 32 letters or numbers. If it has that format, it might be a `REG_url_link` for a registration on the site.
Does that answer your question?

**Comment by s31b18** [comment]
Thank you , the problem solved
