### ISSUE TITLE
Sorry , I have one more problem about ee4 api 

### ISSUE THREAD

**Issue by s31b18** [eventespresso/event-espresso-core#227]
Hello , 
In the official ee4 apps , it can get the capacity/limit of each datetimes of a particular event . 
However , I cannot find any endpoints in your documentation to handle with this .

**Comment by mnelson4** [comment]
I'm guessing you closed this because you found it. But they're using the "calculated_fields", see https://github.com/eventespresso/event-espresso-core/blob/master/docs/C--REST-API/ee4-rest-api-GET-calculated-fields.md
