### ISSUE TITLE
Entity Relations Returning Incorrect Results

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2272]
Discovered while working on a Ticket Price Calculator related branch. Thought it was my changes and spent ages trying to determine what I did wrong before finally checking `EDTR/master`. Same issue exists there.

Basically, I have tickets with related prices that are not being returned correctly by the `useTicketPrices()` hook, ie: returned prices do not match what is in database.

**Comment by manzoorwanijk** [comment]
> returned prices do not match what is in database

Can you please elaborate on that? May be with an example?

**Comment by tn3rb** [comment]
Here's the card for a ticket with DB ID 6:

![ticket 6 card](https://user-images.githubusercontent.com/1751030/72921062-65c5a480-3cff-11ea-9247-c9e389e42329.png)


and here's the entry in the `wp_esp_ticket_price` table for ticket 6 which shows a single relation to price 10

![ticket 6 prices](https://user-images.githubusercontent.com/1751030/72921069-68c09500-3cff-11ea-9e17-f10baadb34a1.png)

but when you click to view the ticket price calculator it displays ALL of the prices currently in the cache

![ticket 6 calculator](https://user-images.githubusercontent.com/1751030/72921070-69f1c200-3cff-11ea-8312-6bb43ce489c5.png)

via console logging, a can see that the query in `assets\prototype\domain\eventEditor\data\queries\tickets\useTicketPrices.ts` 

![useTicketPrices](https://user-images.githubusercontent.com/1751030/72921925-02d50d00-3d01-11ea-9267-432b252abd39.png)

does not return any related prices:

![useTicketPrices console log](https://user-images.githubusercontent.com/1751030/72921955-0ec0cf00-3d01-11ea-8ebe-9e188a8dc240.png)
