### ISSUE TITLE
Document connect.ee.com (Silex)

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/event-espresso-core#2274]
I should record how connect.ee.com works (what it does, tech it runs on, how the code is organized, where its hosted).

**Comment by sethshoultes** [comment]
Should we document this in a private repo?

**Comment by mnelson4** [comment]
Yeah I was probably going to add it to the internal server docs. I just made this task anywhere before I forgot.

**Comment by mnelson4** [comment]
I created an issue in that repo instead
