### ISSUE TITLE
Sell until = Event Start

### ISSUE THREAD

**Issue by mintaras** [eventespresso/event-espresso-core#229]
Is there any way to set the sell until to be the same as event start?
https://eventespresso.com/topic/sell-until-event-start/

Even better would be:
A way to set the sell until to be n days before as event start

Thanks

**Comment by nerrad** [comment]
Hi there,

That is not a current feature available within the plugin and would require some javascript work to accomplish what you wish.  

Our README.md file has [some info on our approach to features](https://github.com/eventespresso/event-espresso-core#testing) that is relevant here. In particular:

> GitHub is not the place to suggest a new feature UNLESS you've already got a pull request to implement it (see pull requests section below). Info on sponsoring new features can [be found here](https://eventespresso.com/rich-features/sponsor-new-features/). If you aren't sure whether something is a feature or bug feel free to post the issue - however we give priority to bug issues here.

If this is a critical feature I recommend hiring a developer to customize this for you.
