### ISSUE TITLE
Developer Documentation Link is Broken

### ISSUE THREAD

**Issue by marco-ka** [eventespresso/event-espresso-core#230]
> Before submitting your issue, please ensure that what you are reporting is specific to Event Espresso 4.

When submitting an issue, please follow this rough guideline for your report.

### Is this a bug report?

* [x] yes
* [ ] no

### What branch did this occur in?
master

### Outline the steps to reproduce
Click the link on <https://github.com/eventespresso/event-espresso-core> in README.md to the Developer Targeted Documentation <http://developer.eventespresso.com/docs>.

### Please include any links to the page(s) demonstrating this issue (if possible).
<http://developer.eventespresso.com/docs>

**Comment by joshfeck** [comment]
Thanks for reporting. Fixed that for you.
