### ISSUE TITLE
How to get check-in and check-out timestamp?

### ISSUE THREAD

**Issue by pupunzi** [eventespresso/event-espresso-core#231]
Is it possible to have the date and time for the check-in action?
Is there a filter or an action that I can use to add this property?

Thank you,
Matteo

**Comment by nerrad** [comment]
Unfortunately we're going to need more information than what you've posted.  What "check-in" action are you referring to?

**Comment by pupunzi** [comment]
Hi @nerrad ,

Our client needs to persist DATE and TIME an attendee (Registrant) has been checked-in or checked-out a specific Event. I was wondering if there's a hook I can use when an Event check-in is performed to add my custom data to the registration.
![ee_checkin](https://cloud.githubusercontent.com/assets/56659/26450655/d8bb2d8e-4158-11e7-850d-fa77ae8903a8.jpeg)

**Comment by joshfeck** [comment]
Hi Matteo,

There's actually a branch that we're working on that adds this:

https://github.com/eventespresso/event-espresso-core/tree/FET-10486-add-timestamp-checkins

Once it's finished it will be merged into master and then included with a following update of Event Espresso core. You can try the branch out now to see if the added timestamps work for you.

**Comment by pupunzi** [comment]
@joshfeck 
Thank you so much for the fast answer.
I'll give the branch a try and see if it works for me.

Regards,
Matteo

**Comment by tn3rb** [comment]
@pupunzi 
Here is the branch with the fix that Josh mentioned:
https://github.com/eventespresso/event-espresso-core/tree/FET-10486-add-timestamp-checkins
You are welcome to help with the testing if you have a development server that you can use

**Comment by pupunzi** [comment]
@tn3rb 
thank you!
I'll try the branch in the next days.

**Comment by joshfeck** [comment]
Update: The branch was merged to master and deleted. The check-in and checkout timestamp display is included in the current release of Event Espresso 4.
