### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'EE_Event_List_Query' not found

### ISSUE THREAD

**Issue by PunchRockgroin** [eventespresso/event-espresso-core#232]
### Is this a bug report?

* [x ] yes

### What branch did this occur in?
4.9.39.p

### What version of WordPress is on the site this issue happened?
4.7.5

### Outline the steps to reproduce
After updating to 4.9.39.p, white screen of death occurs. PHP version 7.1.4

Log message states:

`[01-Jun-2017 15:04:50 UTC] PHP Fatal error:  Uncaught Error: Class 'EE_Event_List_Query' not found in /var/www/xxxx/production/wp-content/plugins/event-espresso-core-reg/public/template_tags.php:177`
`Stack trace: #0 /var/www/xxxx/production/wp-content/plugins/xxxx/templates/widgets/event_espresso/events-all.php(10): espresso_get_events(Array)`

Essentially, we are calling espresso_get_events in a custom widget. 

We've applied a fix by directly calling `$events_query = new \EventEspresso\core\domain\services\wp_queries\EventListQuery( $params );` at line 177 of /public/template_tags.php

**Comment by tn3rb** [comment]
A fix has been pushed to master branch.

Thanks for reporting.

**Comment by brianhogg** [comment]
Any ETA on when this fix would be pushed out?

**Comment by nerrad** [comment]
Since its in the master branch, it will get out with our next release.  Our releases are fairly frequent so there may be a release before end of this week but if not definitely next week.

**Comment by joshfeck** [comment]
This was released a few versions ago.
