### ISSUE TITLE
Messages: Add ability to change default event when previewing a message

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#2337]
When trying to preview a custom message for an event, it shows the details for a different event. It would be less confusing to customers to be able to change the event details when creating a custom message for a particular event.

**Comment by sethshoultes** [comment]
See this HelpScout thread for context:
https://secure.helpscout.net/conversation/1055626170/734585/

**Comment by joshfeck** [comment]
Hey Seth we have this issue already planned out:

https://github.com/eventespresso/event-espresso-core/issues/1447
