### ISSUE TITLE
Refactor Responsive Table Component

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2347]
plz see `assets\ZZZ\components\ui\responsive-table`

### Primary Goals

- support highest levels of a11y and i18n as possible (a11n with HTML tables is super easy actually)

- allow for pagination

- allow for drag n drop sorting

- **MOST IMPORTANT** convert to different layout for small screens, where table headers are used to display a pair of header | column value pairings for each row, see example below:

On Large Screens, we want the table to appear with the regular header columns + body rows format:

| Header | A | B | C | D |
| --- | --- | --- | --- | --- |
| Row 1 | A1 | B1 | C1 | D1 |
| Row 2 | A2 | B2 | C2 | D2 |
| Row 3 | A3 | B3 | C3 | D3 |

But on small screens we want it to collapse to look something like this:

| Row 1 | |
| --- | --- |
| A | A1 |
| B | B1 |
| C | C1 |
| D | D1 |
| **Row 2** | |
| A | A2 |
| B | B2 |
| C | C2 |
| D | D2 |
| **Row 3** | |
| A | A3 |
| B | B3 |
| C | C3 |
| D | D3 |

You can see how this was done in the existing ResponsiveTable component

**Comment by nicolad** [comment]
@tn3rb this is also interesting approach(not directly related to what table): https://ant.design/components/descriptions/

**Comment by nicolad** [comment]
@tn3rb there are few vertical mode issues on `antd`, one of which is this: https://github.com/ant-design/ant-design/issues/9155
and I see they've added `plan` label some time ago
![image](https://user-images.githubusercontent.com/1477453/74027547-0e872b80-49b1-11ea-8776-bf909739a3cf.png)
