### ISSUE TITLE
WP_Query args are stripped out of EventListQuery

### ISSUE THREAD

**Issue by brianhogg** [eventespresso/event-espresso-core#235]
> Before submitting your issue, please ensure that what you are reporting is specific to Event Espresso 4.

When submitting an issue, please follow this rough guideline for your report.

### Is this a bug report?

* [X] yes
* [ ] no

### What branch did this occur in?

master

### What version of WordPress is on the site this issue happened?

4.7.5

### Outline the steps to reproduce

create a new EventListQuery with tax_query.  Because EventListQuery extends WP_Query, the property_exists check in parseArgs incorrectly detects WP_Query properties and not just shortcode args.

### Please include any screenshots ar screencasts that can help illustrate the issue (if possible).

Run a query to try and filter by one or more categories using new EventListQuery and that argument is stripped, and WP_Query doesn't use it correctly (since it's assigned directly to the tax_query property).

**Comment by brianhogg** [comment]
A potential fix is to change the condition in parseArgs from:

`if (property_exists($this, $property)) {`

to

`if ( property_exists( $this, $property ) and ! property_exists( 'WP_Query', $property ) ) {`

and while this works great for tax_query I'm not sure if there's another unintended effect from it.  Could submit as a PR?

**Comment by nerrad** [comment]
Hi Brian,
Ya that sounds like a reasonable fix, if you are willing to do a pull request go ahead :)  Be aware that we're currently transitioning to PSR for code style.

**Comment by tn3rb** [comment]
@brianhogg 

Thanks for your contribution.
Your patch has been merged into branch BUG-10824-event-list-query and has been sent for testing.
We'll let you know when that gets merged into master.
If need be, you can checkout and use that branch from here:
https://github.com/eventespresso/event-espresso-core/tree/BUG-10824-event-list-query
but plz be aware that that branch may contain content that has not yet been released

**Comment by tn3rb** [comment]
@brianhogg
Your Pull Request  has been merged to our master branch and will be part of the next release.
thanks for contributing

**Comment by mnelson4** [comment]
Thanks for the 5-star pull request @brianhogg! 
Please considering reviewing [Event Espresso on WordPress.org](https://wordpress.org/support/plugin/event-espresso-decaf/reviews/).

**Comment by joshfeck** [comment]
This fix was included in the Event Espresso 4.9.45.p release.
