### ISSUE TITLE
Migrate DropDownMenu

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2351]
- migrate/copy logic from `assets\ZZZ\components\ui\drop-down-menu` to `assets\src\application\ui\layout`

- replace WP component with AntD equivalent, maybe: https://ant.design/components/dropdown/

- ensure that keyboard navigation works (if not then revert to using WP component)

**Comment by manzoorwanijk** [comment]
AntD Dropdown is not accessible. I tried to make it, but it didn't work. I have created an issue [here](https://github.com/ant-design/ant-design/issues/21357).
