### ISSUE TITLE
Migrate Entity Details Panel

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2354]
The EntityDetailsPanel is used for displaying important metrics for a datetime or ticket while in grid (card) view

![Entity Details Panel.png](https://images.zenhubusercontent.com/55c8c0f14f7a08fbb7f431cd/9da8bec0-2871-4271-a5a9-99fa583934dd)

- see: `assets\ZZZ\components\ui\entity-details-panel\entity-details-panel.js`

- can maybe use AntD Statistic component: https://ant.design/components/statistic/

- migrate to `assets\src\application\ui\display`

- convert to TS

**Comment by nicolad** [comment]
@tn3rb should fields be editable inline?
