### ISSUE TITLE
Edit Thank you Page

### ISSUE THREAD

**Issue by xyluz** [eventespresso/event-espresso-core#236]
Interswitch integration requires specific messages to be outputted to the user, they will not approve if the message displayed is different.

For example, if transaction is not successful, then the user should not see "congratulations"..

How can i edit the thank you page? and maybe in future versions, can we have a setting for that page?

**Comment by tn3rb** [comment]
Hi Seyi,

You can use the 'FHEE__thank_you_page_overview_template__order_conf_desc' filter to change that message, which is in `modules/thank_you_page/templates/thank-you-page-overview.template.php`.

**Comment by xyluz** [comment]
I don't have this modules/thank_you_page/templates/thank-you-page-overview.template.php in my file structure..

**Comment by nerrad** [comment]
Are you looking in the event-espresso core plugin folder? https://github.com/eventespresso/event-espresso-core/blob/master/modules/thank_you_page/templates/thank-you-page-overview.template.php

**Comment by xyluz** [comment]
yes, i found it here: shortcodes/espresso_thank_you/templates

**Comment by xyluz** [comment]
I am sending a few details to Interswitch in "set_redirection_info" I need to display some of that information on the thank you page, any suggestion on how I can get this done?

Thank you.

**Comment by tn3rb** [comment]
The content in 

```
shortcodes/espresso_thank_you/
```

is deprecated. Do not use those templates.

The templates for the Thank You page are now located in 

```
modules/thank_you_page/templates
```

if you do not have that folder, then you need to update to the latest version of Event Espresso core.
There are many many filters and actions available in those templates for displaying content, so where you want to display something will dictate which hook point to use.

**Comment by xyluz** [comment]
Okay, thank you.

I understand.
