### ISSUE TITLE
Refactor Loading Indicator and Migrate Loading Notice

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2360]
I'm thinking that we will require more than one type of component for providing feedback on loading states:

- a "Loading Notice" for showing that a large collection, such as an entire list of entities or new admin screen, is in the process of being loaded. This would be used as placeholder for a list or screen or form when it is loading.

- a smaller "Loading Indicator" for providing user feedback when an action such as saving or deleting is in progress. This could be embedded in other components such as buttons.

### Loading Notice

- see `assets\ZZZ\components\ui\loading-notice`

- move to `assets\src\application\ui\display\loadingNotice`

- can use `<Spin size="large" />` from https://ant.design/components/spin/

- should be rendered inside a large container with an accompanying notice

- can also be wrapped around a container (ie: container is child) which will fade container

### Loading Indicator

- move to `assets\src\application\ui\display\loadingIndicator\`

- delete `assets\src\application\ui\display\LoadingIndicator.js`

- can use https://ant.design/components/spin/ with loading icon:

```js
const antIcon = <Icon type="loading-3-quarters" spin />;
ReactDOM.render(<Spin indicator={antIcon} />, mountNode);
```

**Comment by nicolad** [comment]
This is how `LoadingNotice` will look:
![Peek 2020-03-10 11-32](https://user-images.githubusercontent.com/1477453/76298956-eeee6600-62c2-11ea-892b-1507e5f34ed8.gif)
