### ISSUE TITLE
Ticket price calculator submit error

### ISSUE THREAD

**Issue by manzoorwanijk** [eventespresso/event-espresso-core#2386]
When submitting TPC changes, the ticket update mutation errs.

![image](https://user-images.githubusercontent.com/18226415/74417965-a1224180-4e6d-11ea-9365-34c3a48da58a.png)

I think it passes all the ticket fields (like `dbId`) as mutation input. I think we need to lock down types for mutaton inputs as well.

**Comment by tn3rb** [comment]
>  I think we need to lock down types for mutaton inputs as well.

ya that sounds good... I might have a typo in the field name in TPC too...
which would be caught sooner with stronger typing, so ya, what you said 😄
