### ISSUE TITLE
Cannot create checkout instance in Single Page Checkout

### ISSUE THREAD

**Issue by hoandang** [eventespresso/event-espresso-core#239]
## What version of WordPress is on the site this issue happened?
4.8.1

Hi, after updating to the latest version of Event Espresso, I got transaction object as NULL and the checkout->checkout object as NULL as well.
Here my code (working on the EE 4.8.31.p version …)
$checkout = EED_Single_Page_Checkout::instance();
$transaction = $checkout->transaction();
$reg_form = $checkout->checkout->current_step->generate_reg_form();
$data[‘form’] = array();
Please, help.

Thanks!

**Comment by tn3rb** [comment]
Sorry, but I'm going to need a lot more info than what you have posted above... 
for example...
where are you running your code?

**Comment by tn3rb** [comment]
did you ever figure this out?
