### ISSUE TITLE
Build Edit Date Details Form

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2394]
- opens in modal when edit button is clicked

- has datetime ID and event name in header

- subsection headers have related antd icons (might have to experiment with position)

- has following form sections and fields:
 (`  |  ` means inputs are on same line)

### Basics (profile icon)
	- Title - text 100% width
	- Description - textarea 100% width x 4 lines

### Date & Time (calendar icon)
	- Start Date - date picker 50% width  | Start Time - time picker 50% width
	- End Date - date picker 50% width  | End Time - time picker 50% width

### Details (control icon)
	- Capacity - number 33% width
	- Archived - toggle switch

- other details like help text, validation settings, etc, can be obtained by looking at `assets\ZZZ\editor\events\dates-and-times\editor-date\edit-form\use-date-entity-input-config.js`

- wire up to Apollo mutations and provide all feedback accordingly, ie: "updating", "success", or "error"

**Comment by manzoorwanijk** [comment]
Should we use the new `<EspressoForm />` or the existing `<FormModal />`? The reason for asking this is that `EspressoForm ` has its own instace of RFF.

**Comment by tn3rb** [comment]
oh ya it should use `EspressoForm` and the method of display, ie: modal vs inline, etc, should be decided elsewhere

**Comment by tn3rb** [comment]
see: #2406
