### ISSUE TITLE
Changing Price from Action/Filter Hook - On Step 2: Single Registration Page

### ISSUE THREAD

**Issue by tfont** [eventespresso/event-espresso-core#240]
### Is this a bug report?

* [x ] yes
* [x ] no

_(you tell me...)_

### What branch did this occur in?
master from 4.9.31.p Version 4.8.1

### What version of WordPress is on the site this issue happened?
4.8.1 (self-hosted)

**Please reference this page:**
https://eventespresso.com/topic/changing-price-from-actionfilter-hook/#post-250823
AND
https://gist.github.com/tfont/4045cdd1736fa853bd9bd60b7d6333d9

## **Problem:**

I am looking for after step 2 is submitted/processed and on step 3 I would be allowed to change the pricing. This would have the changed pricing shown in step 3 rather than after step 3 is submitted/processed. In the processing of changing this price. I've tried the above methods to change the pricing on the transaction, however, it remains the same.

Please let me know if I can provide any additional information.

**Comment by mnelson4** [comment]
Hi @tfont I provided some feedback on https://gist.github.com/tfont/4045cdd1736fa853bd9bd60b7d6333d9, although that might not be the cause of your problem.

**Comment by tfont** [comment]
@mnelson4 so far no. I left an update on the GIST. I am trying to figure out the entire EE_SPCO_Reg_Step_Attendee_Information class and its interactions to better debug my problem.

**Comment by mnelson4** [comment]
hi @tfont I'm having difficulty following what you're asking on that gist. Can you please show your entire plugin code? That would help me identify the problem

**Comment by tfont** [comment]
Sadly, not possible. It's pretty straightforward:

When submitting on step 2 which then goes on to step 3. How would one change the price of a transition (item) that will display this price change on step 3 and onwards?

Please see:
https://gist.github.com/tfont/4045cdd1736fa853bd9bd60b7d6333d9#gistcomment-2201375

**Comment by mnelson4** [comment]
@tfont it's much harder for us to help debug your code if you don't show us what it is. 

Here is a code snippet that I've confirmed changes the transaction's total and the amount show during SPCO's payment options step (what you're calling step 3):

```
add_action('AHEE__Single_Page_Checkout__after_attendee_information__process_reg_step', 'custom_hook', 10, 1);
function custom_hook(EE_SPCO_Reg_Step_Attendee_Information $data)
{
    $purchases = $data->checkout->transaction->items_purchased();
    $first_item = reset($purchases);
    //we need to edit the sub-item's unit price, as
    //the line item's total is calculated from its sub-items
    $children = $first_item->children();
    $child_line_item = reset($children);
    $child_line_item->set('LIN_unit_price', 10);
    $data->checkout->cart->get_grand_total()->recalculate_total_including_taxes();
    $data->update_checkout();
}
```

Added this as a new code snippet on https://github.com/eventespresso/ee-code-snippet-library/blob/master/checkout/mn_spco_change_line_item_before_payment_options_step.php

If you would like more help, please provide the code you're using.
