### ISSUE TITLE
Date Entities Do Not Delete

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2407]
A picture is worth a thousand words, so this video should be worth a million:

![date deletion fail.gif](https://images.zenhubusercontent.com/55c8c0f14f7a08fbb7f431cd/356bf2b3-5b22-4a7e-bfb1-322e647c281f)

as well, that error notice is appearing as a success notice, so something else funny os going on

**Comment by manzoorwanijk** [comment]
Can you please check if that Datetime is already deleted/trashed?

**Comment by tn3rb** [comment]
sigh... yes it was trashed already... forgot the current UI wasn't filtering those out yet... :facepalm:
ya so I changed the deleted flag in the db, refreshed the page, and tried it again, and it was successfully deleted

thnx... 

going to close this
