### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pmartinslima** [eventespresso/event-espresso-core#242]
> Before submitting your issue, please ensure that what you are reporting is specific to Event Espresso 4.

When submitting an issue, please follow this rough guideline for your report.

### Is this a bug report?
* [ ] yes
* [X ] no

### What branch did this occur in?
N/A
### What version of WordPress is on the site this issue happened?
N/A
### Outline the steps to reproduce
N/A
### Please include any screenshots ar screencasts that can help illustrate the issue (if possible).
N/A
### Please include any links to the page(s) demonstrating this issue (if possible).

Due to changes, at this moment we are unable to discriminate by status which registrations didn't complete the payment process.

In order to obtain this information, we need to find out in the database how can we identify this records?
More specifically, how can we get the value of  the "Finalize Registration Step" and what value defines those that didn't complete.

Thanks,
Pedro

**Comment by nerrad** [comment]
Hi Pedro,

This is the kind of question that is best posed in the [EventEspresso support forums](https://eventespresso.com/support/forums).

**Comment by pmartinslima** [comment]
Hi!,

I opened this ticket because the support team told me that this was the place to request information about the table/field where we can find the information.

I'll get back to the support forum and ask again.

**Comment by tn3rb** [comment]
Sorry about that, we didn't immediately grok what you were asking about, and it kinda sounded more like a regular support request than a development related question.

We are currently looking into the issue.

**Comment by nerrad** [comment]
My apologies Pedro,  I wasn't aware you had already posted in the Event Espresso support forums and were directed here.

**Comment by pmartinslima** [comment]
Hi!

Apologies accepted! I should have mentioned that I opened this question by Josh suggestion so this was also my fault.

I'm not sure I made a clear explanation of our need. If so, please let me know. 

To simplify, at some point in the past, in the registration list, the abandoned registrations were colored in  yellow and didn't count to the seat count of the default registration status. Now they do and aren't discriminated - we need to keep those apart a cancel them because we keep count of both the "completed" and "pending payment" registrations to manage our "waiting list". 
I suppose that you can help us identify them correctly in the database?!

Thank you very much for your help,

**Comment by tn3rb** [comment]
fix has been pushed to https://github.com/eventespresso/event-espresso-core/tree/BUG-11006-abandoned-transaction-status

Please feel free to **test** this on **a TESTING SERVER**

let us know if that fixes things for you

**Comment by joshfeck** [comment]
The above branch has been tested, merged to the next release candidate a.k.a [master](https://github.com/eventespresso/event-espresso-core), and deleted.

**Comment by joshfeck** [comment]
The fix was included in the version 4.9.47.p release.

**Comment by pmartinslima** [comment]
Thanks Josh.
This will help a lot.

Em 11/10/2017 19:52, "Josh Feck" <notifications@github.com> escreveu:
