### ISSUE TITLE
error trying to write file input value in single_page_checkout.js

### ISSUE THREAD

**Issue by rogiervdl** [eventespresso/event-espresso-core#243]
A file input throws this error on validation:
"Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string."

I believe
```
set_listener_for_input_validation_value_change : function() {
   SPCO.form_inputs.focusout( function() {
      $(this).val( $.trim( $(this).val() ) );
      $(this).valid();
    });
},
```
should change to 
```
set_listener_for_input_validation_value_change : function() {
   SPCO.form_inputs.focusout( function() {
      if(this.type != 'file') {
            $(this).val( $.trim( $(this).val() ) );
      }
      $(this).valid();
    });
},
```

### Is this a bug report?

* [x] yes
* [ ] no

### What branch did this occur in?
master 4.9.46.p

### What version of WordPress is on the site this issue happened?
4.7.5

**Comment by mnelson4** [comment]
hey @rogiervdl how are you getting file inputs on single page checkout? To my knowledge that isn't possiible with EE master by itself. Being able to reproduce the problem ourselves would help us have more confidence in your suggested fix.

**Comment by rogiervdl** [comment]
It is the Files Addon for Event Espresso 4 (https://wordpress.org/plugins/files-addon-for-event-espresso-4/).

**Comment by mnelson4** [comment]
ah, ok thanks. Ya once I added the files add-on, I saw the error in the JS console , although it didn't cause any other noticeable errors: the file still got uploaded fine and SPCO still worked normally.
I verified @rogiervdl's suggested change did remove the error and SPCO still seemed to work fine.

I think I'll leave this for @tn3rb to decide if he has a different approach for resolving this JS error

**Comment by tn3rb** [comment]
@rogiervdl 
do you want to submit your fix as a pull request and become an official contributor,
or do you want us to just add the fix and steal all of the fame and fortune for ourselves?

**Comment by rogiervdl** [comment]
good idea, I’ll submit a pull request, it is nice to contribute ;-)

R>

**Comment by tn3rb** [comment]
plz see: https://github.com/eventespresso/event-espresso-core/pull/247

**Comment by tn3rb** [comment]
#247 has been merged into master and will be part of our next release
