### ISSUE TITLE
[{"code":"json_no_route","message":"No route was found matching the URL and request method"}]

### ISSUE THREAD

**Issue by Nitesh9827** [eventespresso/event-espresso-core#244]
Hello there, 

I am getting error [{"code":"json_no_route","message":"No route was found matching the URL and request method"}] while trying to excess a WooCommerce store via Rest API. 

Can any one suggest why we are getting this error. 
URL is http://s23940.p656.sites.pressdns.com

**Comment by joshfeck** [comment]
Hi there,

I checked and it doesn't appear that you have Event Espresso installed on your website. Did you intend on posting an issue elsewhere and ended up mistakenly posting here instead?

**Comment by Nitesh9827** [comment]
How can i install it?

**Comment by joshfeck** [comment]
Hi again. I hope you can understand that this is not a support channel. To be clear, this issue you opened here seems to be about the REST API and WooCommerce, which has nothing to do with Event Espresso.

I can point you to [the documentation for how to install Event Espresso](https://eventespresso.com/wiki/installing-event-espresso/), and if you have any support related questions you can open a topic in the Event Espresso support forums.
