### ISSUE TITLE
Extract Global Apollo Types from Domain

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2448]
Currently in `/domain/eventEditor/services/apollo/types.ts` we have some base types that are not specific to the EDTR at all and often referenced in code outside of `/domain/eventEditor/`. These include:

- EntityId
- EntityDbId
- Entity
- EntityEdge
- Trashable

these should all be moved into the application layer since they are not specific to the editor and will most certainly be required for other use cases (domains).

tasks:

- create new `types.ts` file in `/application/services/apollo/`
- move type definitions listed above into this new file
- update all paths and imports accordingly

**Comment by manzoorwanijk** [comment]
To solve this issue of data being pulled from EDTR, I had to create a workaround in `/application/services/apollo/mutations/types.ts` - `BaseType {}`

**Comment by tn3rb** [comment]
will this proposed change simplify or complicate things then?

**Comment by manzoorwanijk** [comment]
It will definitely simplify the things. In fact this was in my mind 😄
