### ISSUE TITLE
Validation error messages missing for radiobuttons and checkboxes

### ISSUE THREAD

**Issue by rogiervdl** [eventespresso/event-espresso-core#246]
Validation error messages are missing for radiobuttons and checkboxes. This happens with a fresh wordpress + EE4 Core install (and nothing else).

The culprit is this line in single_page_checkout.js, line 209:

```
error.appendTo(element.parent("div"));
```
This should be:

```
error.appendTo(element.closest("div"));
```

The reason is that for checkboxes and radiobuttons, the inputs are wrapped inside labels, like:

```
<div>
    <label ...>
        <input type="radio" ...>
    </label>
</div>
```

### Is this a bug report?

* [x] yes
* [ ] no

### What branch did this occur in?
master 4.9.46.p

### What version of WordPress is on the site this issue happened?
4.7.5

### Outline the steps to reproduce

- Fresh install Wordpress 
- install EE4 Core
- create event
- add question with radiobuttons
- open event, press 'Proceed to Finalize Registration' -> error messages for radio buttons do not show up

**Comment by tn3rb** [comment]
plz see: https://github.com/eventespresso/event-espresso-core/pull/247

**Comment by tn3rb** [comment]
#247 has been merged into master and will be part of our next release
