### ISSUE TITLE
Dates List TableView Changes

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2473]
see : `\domain\eventEditor\ui\datetimes\datesList\tableView\TableView.tsx`

> image of table view from EDTR v1
![EDTR - event dates list.png](https://images.zenhubusercontent.com/55c8c0f14f7a08fbb7f431cd/70f4b0f4-1582-4c6d-9bb9-59030984599f)

- ID column needs to display DBID instead of GUID, unless no DBID exists, in which case it can display a shortened GUID (see: `\application\services\utilities\text\shortenGuid`)

- status stripe column showing active status of datetime (see: `\domain\shared\entities\datetimes\helpers\getBackgroundColorClass.ts`) needs to be added to far left of table (see image above)

- data for start and end dates needs to be added and column display needs to be controlled via the "display" filter

- registration link needs to be added to Reg List column data (see: `\domain\eventEditor\ui\datetimes\DateRegistrationsLink.tsx`)

- "Actions" column needs to be added as last column and populated with DateActionsMenu (see: `\domain\eventEditor\ui\datetimes\datesList\actionsMenu\DateActionsMenu.tsx`)

- the following fields should be made editable: 

     - Name
     - Start Date
     - End Date
     - Capacity

**Comment by nicolad** [comment]
@tn3rb I can tackle this

**Comment by nicolad** [comment]
I am not happy with responsiveness when toggling between views, here is the screencast. 
On the first page it's actual table component, on the second page is just a string and on the third is antd table with dynamic options:
![Peek 2020-03-05 12-03](https://user-images.githubusercontent.com/1477453/75970863-a6593600-5ed9-11ea-9c33-5298f97e2906.gif)

***
this is not directly related to this PR, just something I noticed and what might need to be investigated and improved
