### ISSUE TITLE
Filter Bar Changes

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2476]
## For Entity List Filter Bar

- see: `\application\ui\layout\entityList\filterBar\EntityListFilterBar.tsx`

- change all references to "List" view (and its variations) to "Table" view and update all related code

- change all references to "Grid" view (and its variations) to "Card" view and update all related code

- update styles so that:

     - all references to WordPress GB classes like `components-icon-button` are removed and replaced accordingly

     - the `ee-active-filters` applies the same color affects as the hover state

     - styles can be converted to sass if that helps with the refactor

## For Dates List Filter Bar

- see `\domain\eventEditor\ui\datetimes\datesList\filterBar\controls\ShowDatesControl.tsx`

- split the "ShowDates" filter and state into two separate components:

     - one for "Status" that includes the following:
          - any (all Dates)
          - activeUpcoming <= default
          - activeOnly
          - upcomingOnly
          - nextActiveUpcomingOnly
          - soldOutOnly
          - expiredOnly
          - recentlyExpiredOnly
          - trashedOnly

     - one for "Sales" that includes the following:
          - any (all Dates) <= default
          - above90Capacity
          - above75Capacity
          - above50Capacity
          - below50Capacity

- update all related logic accordingly

## For Tickets List Filter Bar

- see `\domain\eventEditor\ui\tickets\ticketsList\filterBar\controls\ShowTicketsControl.tsx`

- split the "ShowTickets" filter and state into two separate components:

     - one for "Status" that includes the following:
          - any (all Tickets)
          - onSaleAndPending <= default
          - onSaleOnly 
          - pendingOnly 
          - nextOnSaleOrPendingOnly 
          - soldOutOnly 
          - expiredOnly
          - recentlyExpiredOnly
          - trashedOnly

     - one for "Sales" that includes the following:
          - any (all Tickets) <= default
          - above90Sold 
          - above75Sold 
          - above50Sold 
          - below50Sold 

- update all related logic accordingly

**Comment by nicolad** [comment]
part one: https://github.com/eventespresso/event-espresso-core/pull/2578
