### ISSUE TITLE
Conflict with Beaver Builder plugin.

### ISSUE THREAD

**Issue by mrjonwilson** [eventespresso/event-espresso-core#248]
### Is this a bug report?
Yes

### What branch did this occur in?
4.9.46.p

### What version of WordPress is on the site this issue happened?
4.8.1

### Outline the steps to reproduce
Activate EE and Beaver Builder, then try to edit a module in the Page Builder.

### Please include any screenshots or screencasts that can help illustrate the issue (if possible).
https://www.screencast.com/t/QcvwWgDeT 

I can provide the Beaver Builder plugin for testing if needed.

**Comment by mrjonwilson** [comment]
Errors in console: https://www.screencast.com/t/CvKTIGqjvcF

**Comment by joshfeck** [comment]
Hi Jon,

Can you check in the Network tab and get the response from there?

![network tab](https://user-images.githubusercontent.com/891156/30665740-0d50e07e-9e20-11e7-8d56-ebeb3043f375.jpg)

**Comment by mrjonwilson** [comment]
Here you go Josh. https://www.screencast.com/t/7MnZtoYSPNH

Thanks!

**Comment by joshfeck** [comment]
This turned out to be a bug in Beaver Builder that was fixed.
