### ISSUE TITLE
Reset Pagination After Entity List Filters Change

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2492]
#### Steps to Reproduce

- refresh page and wait till everything loads but don't touch any filters or pagination yet

- if you do not have more than 6 dates in the list already, then change the pagination "per page" value to 2

 - click to view page 2 of the dates

 - now click to view filters, and from the "show" dropdown, select "all active and upcoming" (assuming that your dates list has at least one active or upcoming date in it)

 - the "no results found" notice should appear

 - if you now click on the "page 1" button in the pagination, a result should appear

Looks like we need to reset the pagination if the number of results changes as a result of other filters.

**Comment by manzoorwanijk** [comment]
I don't understand why "no results found" should appear. Here is my dates list

![demo](https://user-images.githubusercontent.com/18226415/75974575-0dd4ad00-5efd-11ea-8dc3-f46125e9966f.gif)
