### ISSUE TITLE
Entity list doesn't update when adding or deleting an entity

### ISSUE THREAD

**Issue by manzoorwanijk** [eventespresso/event-espresso-core#2507]
When adding or deleting an entity, the list doesn't seem to update. The most probable cause is the filterbar paginated entities.

**Comment by tn3rb** [comment]
from chat:

> Manzoor Ahmad Wani  9:30 AM
> Yeah, filter state and pagination is a bit buggy
> Needs an overhaul to let it use Apollo all the time
> We may have to move filter state reducer inside the hook to be able to use Apollo cache via useDatetimes() or useTickets()
> Here lies the main problem. that state.dates never gets update if state already has at least 1 date

```js
const useDatesListFilterState = (dates: Datetime[]): FilterStateManager => {
	const initialState: FilterState = {
		dates,
		datesSortedBy: DatesSorted.chronologically,
		displayDates: DisplayDates.start,
		filteredEntities: dates,
		showDates: ShowDates.all,
	};

	const [state, dispatch] = useReducer(reducer, initialState);

	useEffect(() => {
		if (Array.isArray(state.dates) && state.dates.length < 1 && Array.isArray(dates) && dates.length > 0) {
			dispatch({
				type: ActionType.SET_DATES,
				payload: dates,
			});
		}
	});
```

> The intension of useEffect seems to update the dates at only the beginning when there are no dates in the state
> At load time, the state is empty
> When dates load, it updates the state and never lets it update again

> Brent Christensen:ox:  9:48 AM
> oh right... the state was NEVER updating, because the initial value was set as an empty array, so that useEffect hook would essentially reinitialize the state once the dates became available... was never intended to block further changes
> best option then is likely to just remove ALL state management for the actual entities and have it operate solely as a "pipe" like Vadim said
