### ISSUE TITLE
Are there any filters on registration form inputs (backend / Frontend ) to encrypt all form fileds before saving to database

### ISSUE THREAD

**Issue by amjadsheen** [eventespresso/event-espresso-core#252]
> Before submitting your issue, please ensure that what you are reporting is specific to Event Espresso 4.

When submitting an issue, please follow this rough guideline for your report.

### Is this a bug report?

* [ ] yes
* [x] no

**Comment by mnelson4** [comment]
hey @amjadsheen, I don't think there is a filter like that.
You could look into adding a filter in in `core/db_models/fields/EE_Model_Field_Base.php`'s methods `prepare_for_use_in_db` and `prepare_for_set_from_db`, which should be called when preparing a value for inserting into a database column and when retrieving the value from the database column. Child classes (eg `EE_Maybe_Serialized_Simple_HTML_Field` and `might not reliably call these methods reliably though, so you might need to add calls to `parent::prepare_for_use_in_db()` and `parent::prepare_for_set_from_db()` in them.
Does that make sense?
If you find something like that works, please submit a pull request.

**Comment by tn3rb** [comment]
Please note that we also have an `EE_Encryption` class that might be useful for you and save you having to write some extra code. It's not very thorough encryption, so if  you need things to be extremely secure, then you'll need to write your own. That class is more for obfuscating data and/or protecting it from "script kiddies"

**Comment by nerrad** [comment]
I'm going to close this issue since we've answered your question.  Feel free to add additional related notes to this thread if you have more to add.
