### ISSUE TITLE
[Question] How to trigger messages for Registrations coming from WRITE Endpoint via API?

### ISSUE THREAD

**Issue by Samsonator** [eventespresso/event-espresso-core#254]
> Before submitting your issue, please ensure that what you are reporting is specific to Event Espresso 4.

When submitting an issue, please follow this rough guideline for your report.

### Is this a bug report?

* [ ] yes
* [x] no

### What branch did this occur in?
4.9.46.rc.062

### What version of WordPress is on the site this issue happened?
4.8.2

### If you were directed to create an issue here by the EE support team, what is the link to your original EE support forum thread?
https://eventespresso.com/topic/how-to-trigger-messages-for-registrations-coming-from-write-endpoint-via-api/

### Question
I am currently working on an integration via the new EE JSON API and things are going great!
I had a question before I finish my work on “creating” registrations via the API. If I create all the associated Transaction, Line Items etc. entities and create the Registration using those ID’s, will the corresponding messages that are already set up be triggered?

Or will I have to initialise the registration and then trigger messages by “changing” the status?

Many thanks in advance.
Sam

**Comment by mnelson4** [comment]
Hi @Samsonator, great to hear you're making use of the REST API Write endpoints.

> If I create all the associated Transaction, Line Items etc. entities and create the Registration using those ID’s, will the corresponding messages that are already set up be triggered?

Sorry, no.

> Or will I have to initialise the registration and then trigger messages by “changing” the status?

If you go into the admin and trigger sending messages, that might work. But I don't think that's what you want anyway.

I'm sorry we don't have a really good answer for you. Basically, triggering sending messages over the REST API is crude at best. We should add endpoints for performing that (we've intended to, but haven't made time because have not yet seen a demand... which you're now showing.)
So I'm going to make an internal ticket to support what you're wanting. 

My coworker @nerrad had this to say

> So the only way it’d work for triggering messages by saving data directly to EE_Message table via the REST API is if its saved as a Message to Generate in expected way for the given message type  (there’s stuff that gets attached to the Extra_Meta table too).  Plus, the site would need to be set to send messages on a separate request so the message gets picked up from the “queue”.    Possible? Yes, but very difficult to get right using the REST API directly.

But we all agree that's pretty barbaric. You'd be better sitting tight waiting for us to make a message-sending endpoint, or implement one yourself in a separate add-on (and refer us to it, it would help us in our development of the feature for core). If you'd like to implement such an endpoint yourself, we could point you to what code you'd be wanting to call.

**Comment by mnelson4** [comment]
For our records, this is the internal ticket: https://events.codebasehq.com/projects/event-espresso/tickets/11120 (sorry, it's not public)

**Comment by Samsonator** [comment]
Hey @mnelson4 , thanks for getting back to me.

I may have to find a crude solution using the API in some way as we now have to deliver this functionality in the pretty short term :/ (customer timescales huh), I imagine that we will approach it in the way that @nerrad mentioned or similar. 

Thanks so much for pointing in the right direction.

I am wondering if I can get the "send related messages" functionality that is currently in the admin area to be called via a URL in order to "trigger" the messages for a Registration.

In any case I can keep this ticket updated with my progress, even if that might be an unfortunate unusable "hacky" solution.

**Comment by nerrad** [comment]
Sam, pretty much all the message types in the messages system have a way to be triggered via url (sometimes it requires authed by admin), so the way I'd approach it on a tight deadline is register a custom rpc like endpoint that simply calls the appropriate message trigger for the data sent to the endpoint.  You can take a look at `EED_Messages` which is where a lot of the messages system gets kicked off.  Your rpc endpoint could end up pointing to one of those "triggers" with the correct data needed for sending the right messages.

**Comment by Samsonator** [comment]
Wow, fast response! Thanks and appreciate the unexpected support for my tight deadline :)

I am not as familiar with how WordPress handles RPC compared to admin-ajax and now (thanks to you guys) the JSON API. 

So, I was investigating two possible approaches to getting a temporary solution:
1) Calling the admin page (/wp-admin/admin.php?page=espresso_registrations&action=change_reg_status&change_reg_status_nonce=XXXX directly and passing the values that the admin page uses i.e. 

```
reg_status_change_form[return]:view_registration, 
reg_status_change_form[REG_ID]:XXX, 
reg_status_change_form[reg_status]:RAP or RPP, 
reg_status_change_form[send_notifications]:1, 
reg_status_change_form[submit]:Update Registration Status
```

As of right now I'm not 100% sure how to generate a valid nonce for this but I'm aware of the hilarious "Droids not found" error and the corresponding tip to use "add_query_args_and_nonce". Obviously the code was not meant to be called this way and is therefore protected methods etc. So I'm not sure if I'm barking up the wrong tree.

2) Some sort of custom endpoint, whether using RPC or admin-ajax.php or REST API that would be a cleaner way of calling the EE code but still unsure whether that is possible or how exactly to "correctly" trigger the messages.

I haven't investigated EED_Messages yet but will definitely take a look as well. Do you have any examples of a URL that can trigger an EE message? 
I am essentially looking for a place to provide a REG_ID, new Status and then trigger the associated messages.

**Comment by nerrad** [comment]
The WordPress API framework provides a way to register your own custom endpoints. Or you can avoid that all together and just create your own endpoint listener (using wp_rewrite rules or something like that).

I'm short on time as well for other things so I can't give you explicit examples but one you look at EED_Messages you'll see a number of methods you could call in the handler for whatever custom endpoint you setup, some examples:

`EED_Messages::maybe_registration()` - triggers registration related message types by status
`EED_Messages::payment()` - triggers payment related message types
... etc.

**Comment by Samsonator** [comment]
Thanks for the info.

I've created my own API endpoint but I am struggling to figure out how to trigger a "maybe_registration" for a registration with a specific REG_ID. I can see that its a public function. Can I simply get the registration object by the ID and EE_Message::maybe_registration($registration) ?

Apologies for disrupting you.

**Comment by nerrad** [comment]
```
EED_Messages::maybe_registration(
    EEM_Message::instance()->get_one_by_ID( $registration_id )
);
```
You may need to play a bit with where you call this in terms of the WP request loading order but I *think* anytime after plugins loaded should be fine.

**Comment by mnelson4** [comment]
you need to follow a bit of a method chain to find what params we usually provide in the second arg, but I found

```
$update_params = array(
			'old_txn_status'  => $transaction->old_txn_status(),
			'new_txn_status'  => $transaction->status_ID(),
			'finalized'       => $finalized,
			'revisit'         => $this->_revisit,
			'payment_updates' => $payment instanceof EE_Payment ? true : false,
			'last_payment'    => $payment
		);
```
from `EE_Transaction_Processor::update_transaction_and_registrations_after_checkout_or_payment()`. 
You may only need to provide the `finalized => true` array key

**Comment by Samsonator** [comment]
Excellent! That seems to have somewhat done the trick! I was able to see messages generated and queued for sending. Will test some more.

Here was the final code for my custom endpoint callback function
```
add_action( 'rest_api_init', function () {
	register_rest_route( 'sme_ee_extended/v1', '/registration/(?P<id>\d+)', array(
		'methods' => 'GET',
		'callback' => 'trigger_messages_for_registration',
		'args' => array(
			'id' => array(
				'validate_callback' => function($param, $request, $key) {
					return is_numeric( $param );
				}
			),
		),
//		'permission_callback' => function () { // check if user is admin before completing request
//			return current_user_can( 'manage_options' );
//		}
	) );
} );

function trigger_messages_for_registration( $data ) {
	$registration_id = $data['id'];
	$registration = EEM_Registration::instance()->get_one_by_ID($registration_id);
	$transaction = $registration->transaction();
	$update_params = array(
		'old_txn_status'  => $transaction->old_txn_status(),
		'new_txn_status'  => $transaction->status_ID(),
		'finalized'       => true,
		'revisit'         => false,
		'payment_updates' => false,
		'last_payment'    => null
	);
	if ($registration) {
		add_filter('FHEE__EED_Messages___maybe_registration__deliver_notifications', '__return_true');
		EED_Messages::maybe_registration(
			$registration,
			$update_params
		);
		$data = array('Registration was found and maybe triggered messages.'); // @TODO: Fill this with something more meaningful

		// Create the response object
		$response = new WP_REST_Response( $data );

		// Add a custom status code
		$response->set_status( 201 );

		return $response;
	} else {
		return new WP_Error( 'sme_ee_extended', 'No Registration Found', array( 'status' => 404 ) );
	}
}
```
I tested with a "free ticket" that was created via the API and the messages generated wonderfully. I did have to set `add_filter('FHEE__EED_Messages___maybe_registration__deliver_notifications', '__return_true');` and the solution is fairly crude at the moment but I'm going to "get" the payment from the transaction so that the $update_params remain consistent with what @mnelson4 posted. 

You guys saved me a lot of time! Will update this thread with my final solution.

**Comment by nerrad** [comment]
I'm just going to close this issue since it seems like we've adequately answered your question.  Please do update it if you have anything to share :)
