### ISSUE TITLE
Add Entity List Legend Components

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2547]
In order for users to fully understand the EDTR UI we need to add a legend to the bottom of each entity list in order to describe the various icons and colour codings used throughout.

Here's an example of the legend currently in use below the Events Admin List Table

![Events Admin List Table Legend.png](https://images.zenhubusercontent.com/55c8c0f14f7a08fbb7f431cd/bd7c0dd7-3437-4bb3-9db6-cc4d7df3bb60)

This is something that we will definitely utilize in the UIs for many different use cases, so ideally whatever we build should be highly reusable.

As well, just like the Entity Action Menus and Filter Bars, we will also likely require the ability to inject additional legend items into specific legends from addons, third party code, etc. So we will also want to wire this up using the fancy new registry logic that Manzoor just developed (or is still in the process of developing. That is not critical atm though so it is something we can add later. For now we can just pass an array of legend items.

Initially I see this being composed of three main parts:

1. abstract `EntityListLegend` component located in the `/application/ui/display` folder, which would be responsible for managing items and controlling their layout and display. This will likely also require a `LegendItem` component that will represent a single item. It's possible we may want to have two kinds of legend item components with one for icon based legend items and another for the colour swatches used to represent entity statuses. Because the legend is rather large, we might want to also have them hidden initially like we do with the filter bar filters and then only display them when an icon button is clicked. Let's use the AntD `<CompassFilled />` icon which could also rotate when clicked. I think we'll also want to have some text like "show legend" and "hide legend" beside the legend. The legends should be integrated directly with the EntityList and based on the ListId used for each.

2. a `DatesListLegend` for configuring the legend for the Dates list. This will require legend items for every icon used in the list as well as color swatches for each datetime status.

3. a `TicketsListLegend` for configuring the legend for the Tickets list. This will require legend items for every icon used in the list as well as color swatches for each ticket status.

**Comment by nicolad** [comment]
@tn3rb this was reopened due to: https://github.com/eventespresso/event-espresso-core/pull/2574
?
***
lemme know if it needs to be closed or if there are other aspects that needs attention

**Comment by tn3rb** [comment]
> this was reopened due to: #2574?

yes, closing now
