### ISSUE TITLE
QUESTION: HOW TO QUERY ATTENDEE INFORMATION (CUSTOM QUESTION/ANSWERS)

### ISSUE THREAD

**Issue by davidstodzy** [eventespresso/event-espresso-core#255]
I am curious how one would go about querying attendee information (custom question/answers).  My goal is to use DomPDF to create a custom PDF for each attendee displaying all of their information.

**Comment by mnelson4** [comment]
In case you weren't already aware, the EE invoices and receipts/order confirmations also use DomPDF.
You may want to look into our highly extensible messages system, https://eventespresso.com/wiki/how-to-create-a-custom-message-template/, which could take care of converting HTML into a PDF, and there are also already shortcodes that can be used in messages that will probably meet your needs (eg `[QUESTION_LIST]` .
We even have some skeleton add-ons that will get you part of the way: https://github.com/eventespresso/event-espresso-core/tree/master/tests/mocks/addons. 
If for some reason you don't want to go that route, you can use the models to query the database for that data. Note that the answers to all system questions (eg first name, last name, email, and address questions) are stored on separate fields on each `EE_Attendee`; whereas answers to custom questions are stored as separate `EE_Answer` objects. See https://github.com/eventespresso/event-espresso-core/tree/master/docs/G--Model-System
Please let us know if you need further direction.

**Comment by davidstodzy** [comment]
Mike thanks a lot for your quick reply!

I managed to set up DOMPDF already and added a conditional statement to init that checks the GET variables, and loads the attendee info into a PDF if "&PDF=true" is appended to the the edit registration url from the backend (i.e. "/wp-admin/admin.php?page=espresso_registrations&action=view_registration&_REG_ID=4&view_registration_nonce=5558e0fab4&return=default") and and seems to be working.  What confuses me is how access both the standard registration (fname, lname, etc.) and the custom questions/answers pair with the registration ID.  I have checked the model and understand it from an abstract point of view but not the actual fundamentals/functions that will accomplish what I need.  I would use your built in shortcodes, but the client is very specific on how they want their PDF to be styled.  The one good thing about this is that the questions will be the exact same everytime.

If you could guide me or give me pointers from here I would be VERY appreciative.  Thank you!

**Comment by tn3rb** [comment]
Each EE_Registration has an associated ATT_ID which is the EE_Attendee ID.
If you have a valid EE_Registration object, you can get it's  related  EE_Attendee object using 
```php
$registration->attendee();
```

Similarly, each EE_Answer has an associated REG_ID which is the EE_Registration ID.
If you have a valid EE_Registration object, you can get an array of related  EE_Answer objects using 
```php
$registration->answers();
```

**Comment by tn3rb** [comment]
If you wanted to get the above directly using the `_REG_ID` URL parameter, then you would do something like the following:

```php
$REG_ID = absint($_REQUEST['_REG_ID']);
$attendee = EEM_Attendee::instance()->get_one(
    // query params
    array(
        // where params
        array(
            'Registration.REG_IG' => $REG_ID
        )
    )
);
$answers = EEM_Answer::instance()->get_all(
    // query params
    array(
        // where params
        array(
            'Registration.REG_IG' => $REG_ID
        )
    )
);
```

**Comment by nerrad** [comment]
I'm going to close this issue because it appears like the question was adequately answered, if you have anything more to add feel free to post more info.
