### ISSUE TITLE
Ticket Assignments Manager Perma Errors

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2555]
If a ticket or datetime is missing assignments then an error appears instructing you that entities require at least one relation (paraphrasing), but the error message will not go away and the submit button will not activate after correcting the issue.

Even changing every single cell in the table to have a relation will not resolve the problem:

![Ticket Assignments Manager Perma Errors.png](https://images.zenhubusercontent.com/55c8c0f14f7a08fbb7f431cd/d5bd1f9f-bf57-45cc-aae6-7662ef39809d)

note: it works correctly for the ALL Tickets Assignments Button at the bottom of the dates list, meaning if you resolve ALL missing relations for every date and ticket, then you can submit the changes.

**Comment by manzoorwanijk** [comment]
The reason for that is there is some other date that is orphan. We need to set validations only for the currently visible dates.
