### ISSUE TITLE
Problems with Web 2.0 Directory plugin

### ISSUE THREAD

**Issue by shamalli** [eventespresso/event-espresso-core#256]
```
An exception of type EventEspressoBatchRequest\Helpers\BatchRequestException occurred while running BatchRunner::create_job(). 
Its message was
The class EventEspressoBatchRequestJobHandlersRegistrationsReport does not exist, and so could not be used for running a job. It should implement JobHandlerInterface.

and had trace

#0 /core/libraries/batch/BatchRequestProcessor.php(56): EventEspressoBatchRequest\BatchRequestProcessor->instantiate_batch_job_handler_from_classname(‘EventEspressoBa…’)
#1 /modules/batch/EED_Batch.module.php(172): EventEspressoBatchRequest\BatchRequestProcessor->create_job(‘EventEspressoBa…’, Array)
#2 /modules/batch/EED_Batch.module.php(133): EED_Batch->_enqueue_batch_job_scripts_and_styles_and_start_job()
#3 /modules/batch/EED_Batch.module.php(109): EED_Batch->enqueue_scripts_styles_batch_file_create()
#4 [internal function]: EED_Batch->enqueue_scripts(‘admin_page_espr…’)
#5 /wp-includes/class-wp-hook.php(298): call_user_func_array(Array, Array)
#6 /wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(”, Array)
#7 /wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#8 /wp-admin/admin-header.php(97): do_action(‘admin_enqueue_s…’, ‘admin_page_espr…’)
#9 /wp-admin/admin.php(214): require_once(‘/home4/kfwhiley…’)
#10 {main}
```

Actual discussion about this issue here: https://codecanyon.net/item/web-20-directory-plugin-for-wordpress/6463373/comments?page=335&filter=all#comment_17914251

**Comment by joshfeck** [comment]
Hi there,

May I ask what is your question?

**Comment by shamalli** [comment]
My question is: how to prevent these errors to appear in your plugin?

Please, look at the discussion by the link. Your client has  a problem when my plugin was activated.

**Comment by joshfeck** [comment]
You can download Event Espresso from this repository, install it on a test server where your plugin is installed, troubleshoot, then fix your code. If you have any specific questions related to how your code is interacting with issue you can follow up here.

**Comment by shamalli** [comment]
Actually I'm not sure the problem from my plugin's side. It fully follows wordpress coding standards.

**Comment by joshfeck** [comment]
One approach you could take if troubleshooting yields no results is you make sure your plugin doesn't load on the `admin.php?page=espresso_batch` admin page.

**Comment by mnelson4** [comment]
also @shamalli, if you can provide us with a copy of your conflicting plugin we could see if there's a problem in our code.
From the error, it looks like somehow your plugin is removing the slashes from the classname passed from the querystring, as the classname should be `EventEspressoBatchRequest\JobHandlers\RegistrationsReport` instead of `EventEspressoBatchRequestJobHandlersRegistrationsReport `

**Comment by shamalli** [comment]
How can I send you the plugin?

**Comment by mnelson4** [comment]
You can upload it somewhere like GitHub and give us a link to it (btw we charge for our software but actually also put it on GitHub like this, and somehow that hasn't affected sales), or you can email us a copy at support@eventespresso.com

**Comment by joshfeck** [comment]
Hi there,

We received a copy of your plugin from your customer. Here's the line of code from your plugin that's causing the class to not be found:

`$_GET = stripslashes_deep($_GET);` 

The way forward will be to only change things to run that code **only where needed** (instead of on every request). 

Hope that helps!

**Comment by shamalli** [comment]
Hello, yes, thanks, but it means that your plugin calls the name of class to load from $_GET ?

**Comment by joshfeck** [comment]
Of course.

https://github.com/eventespresso/event-espresso-core/blob/master/modules/batch/EED_Batch.module.php#L166

**Comment by mnelson4** [comment]
Good find Josh!
So I'm going to make our ticket account for other code that might strip slashes from the `$_GET` superglobal, but I agree @shamalli it would probably be better for your plugin to only do that for `$_GET` keys it knows it uses (or create a copy of  `$_GET` and operate on that instead, eg `$get = stripslashes_deep($_GET);`).
And yes we are loading classnames from `$_GET`, verifying they implement a certain interface and then calling a method on them. While a hacker could provide any classname they want over the querystring, that class would need to either be a class already defined in Event Espresso (in which case it's safe), or it could be a malicious class from a hacker (although in that case the question is more how did the hacker get that class defined in the first place?) But if you see a security problem with that @shamalli please report it here: https://eventespresso.com/report-a-security-vulnerability/.

**Comment by tn3rb** [comment]
going to assume that no news is good news since you haven't responded since November 2017.
