### ISSUE TITLE
Remove RFF from Ticket Price Calculator

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2567]
The Ticket Price Calculator (TPC) in both EDTR v1 as well as the current implementation have been using React Final Form (RFF) for managing form state. In retrospect, this unfortunately turned out to be a bad decision because there were a few subtle issues that I have been completely unable to resolve, primarily:

 - RFF requires the use of form decorators for responding to changes in form data but does not allow those callbacks to change from render to render. In order to recalculate the base price or total however, the values need to take into account additional price modifiers added to the form, which changes the content of the decorator callbacks because they now include additional modifiers in their calculations. This appears to be an incompatibility between `final-form-calculate` and `react-final-form-arrays` (or could still be because of my implementation).

Anyways, at this point it should simplify things greatly by just not using RFF at all for the Ticket Price Calculator. This will however require the existing logic to be refactored.

Here's a rough breakdown of the logic in the order that it needs to occur:

- TPC button is clicked for a specific ticket

- current ticket details need to be retrieved from the Apollo cache

- the ticket's related price entities need to be retrieved 

- the price's related price type entities need to be retrieved 

- to avoid updates to the above entities while the user is editing things within the TPC, new objects and TS types should be generated for use within the calculator. A single `PriceModifier` object/type should be sufficient as the only details needed from the ticket are the current total (which can be calculated from the individual prices) and the value for the new `reverseCalculate` field.

example TPC data object:

```js
{
	ticket: {
		id: abc123, // for tracking ticket in apollo cache
		total: 19.95,
		reverseCalculate: false,
	},
	priceModifiers: [
		{
			id: def456, // for tracking existing price in apollo cache
			type: BASE_PRICE,
			label: 'name',
			desc: 'blah blah',
			amount: 15,
		},
		{
			id: 'ghi789', // for tracking existing price in apollo cache
			type: FIXED_SURCHARGE,
			label: 'extra fee',
			desc: 'just cuz',
			amount: 4.95,
		},
		{
			id: 'NEW', // indicates new price to create upon submission
			type: FED_TAX,
			label: 'tax',
			desc: 'theft',
			amount: 10,
		},
	],
}
```

- the array of `PriceModifier` objects, plus values for the `ticketTotal` and `reverseCalculate` need to be initialized and saved to local state.

- the TPC renders with a single table row for each `PriceModifier` plus a footer row showing the `ticketTotal`. Here's a screenshot from a previous build

![ticket price calculator.png](https://images.zenhubusercontent.com/55c8c0f14f7a08fbb7f431cd/33ee7de3-6688-4fcc-9a01-759aef2fcac5):

- the first row should always be for the tickets base price and should NOT have a delete button available because every ticket should have a base price even if the ticket is free, in which case the base price simply has an amount of `0`. The price type selector for the base price should also be disabled since we don't want users changing that to something else.

- each row after that should have a price type selector with "base price" removed as an option (there can only be one!) and a delete button in the "Actions" column.

- the last row of the table body should be for adding a new price modifier which is the same as the previous rows except instead of a delete button it has a button for committing the addition of the new modifier to the ticket price. I'm considering removing this and requiring the user to click the add button first prior to having the fields available because as is, I'm worried that people will enter data into the fields and forget to click the "Add" button and then potentially lose their data. If the add button is clicked we should display an error if no amount has been entered (label and desc can be empty).

- the final row in the table has only two fields. A number input for setting the ticket total price, and a button for toggling the calculation direction, ie: the `reverseCalculate` value. If set to `false` (the default value), then the ticket total field is disabled and its value is calculated starting with the base price and applying each modifier in order. If `reverseCalculate` is set to `true`, then the ticket total field isenabled and its value is used as the starting point to calculate the base price by applying each modifier in reverse order.

- so depending on the `reverseCalculate` value, we either calculate the ticket total or the ticket base price when any of the following events occurs:

     - base price amount is changed (and `reverseCalculate` is `false`)

     - regular price modifier "Price Type" is changed (ie: surcharge, discount, dollar, %)

     - regular price modifier amount is changed

     - new price modifier is added

     - ticket total amount is changed (and `reverseCalculate` is `true`)

- **here's the tricky part** recalculating the total or base price can NOT trigger the calculations to run again (this was another issue with RFF because it would fire its decorators for a field even if the input was disabled causing the updating to recurse). As well, there needs to be a delay between when an input value changes and when the calculator recomputes values because we don't want that happening while someone is still in the process of entering a number. 500ms is sufficient.

- upon final submission, the existing ticket in cache that the data was taken from needs to be updated if either the ticket total or value for `reverseCalculate` has changed. Similarly for prices, any values for `PriceModifier` objects that have an ID corresponding to an existing price in the apollo cache need to be updated. All other `PriceModifier` objects should result in the creation of new prices. We also need to somehow track price modifiers that are removed (maybe via a `trashed` flag in the TPC data?) so that those price objects can be trashed.

**Comment by manzoorwanijk** [comment]
Regarding the last point, we already have a mechanism in place to find out the deleted/trashed prices in `useOnSubmitPrices`

**Comment by tn3rb** [comment]
so imagine you have your table with the base price at the top, followed by a bunch of price modifiers (surcharges, discounts, taxes), and then finally a row for the total ticket price. Using the "reverse calculate" option, you can run the calculations in either direction:

 - starting at the base price and applying modifiers to calculate the ticket total
 or the other way around
 - starting at the ticket total and applying modifiers to calculate the base price.

in order for those calculations to happen automatically whenever something changes (like the amount of a discount) we add some sort of listeners to all of the inputs that need to trigger the calculator. But this also includes the inputs for the base price and ticket total.

So what can happen (and HAS happened in EDTR during development) is the following:

- you change a value that triggers the calculator
- the listener for the changed input is triggered and the calculator runs
- the base price or the ticket total gets updated depending on the value of the reverse calculate option
- the listener for the above input that just changed is triggered and the calculator runs
- the base price or the ticket total gets updated depending on the value of the reverse calculate option
- the listener for the above input that just changed is triggered and the calculator runs
- the base price or the ticket total gets updated depending on the value of the reverse calculate option
- the listener for the above input that just changed is triggered and the calculator runs
- the base price or the ticket total gets updated depending on the value of the reverse calculate option
- the listener for the above input that just changed is triggered and the calculator runs
- the base price or the ticket total gets updated depending on the value of the reverse calculate option
- the listener for the above input that just changed is triggered and the calculator runs
- the base price or the ticket total gets updated depending on the value of the reverse calculate option
- the listener for the above input that just changed is triggered and the calculator runs
- the base price or the ticket total gets updated depending on the value of the reverse calculate option
- the listener for the above input that just changed is triggered and the calculator runs
- the base price or the ticket total gets updated depending on the value of the reverse calculate option
- the listener for the above input that just changed is triggered and the calculator runs
- etc

**Comment by manzoorwanijk** [comment]
Thanks, it's clear now
