### ISSUE TITLE
espresso_reg style missing on admin pages

### ISSUE THREAD

**Issue by ScottDeLuzio** [eventespresso/event-espresso-core#257]
> Before submitting your issue, please ensure that what you are reporting is specific to Event Espresso 4.

When submitting an issue, please follow this rough guideline for your report.

### Is this a bug report?

* [x] yes
* [ ] no

### What version of WordPress is on the site this issue happened?
4.8.3

### Outline the steps to reproduce
Install & Activate Query Monitor plugin https://wordpress.org/plugins/query-monitor/
Go to Event Espresso > Registrations > Contact List tab (issue may exist elsewhere but this is where I found it).
On the Query Monitor tab in the admin bar, select Styles, which should be highlighted in Red
Note that the style 'espresso_reg' is listed as missing.

### To correct
`wp_deregister_style('espresso_reg');` is being called in /admin_pages/registrations/Registrations_Admin_page.core.php on line 715. This is deregistering the style that was registered on line 670 (same file). On line 676 (same file), `wp_enqueue_style('espresso_reg');` is called. The enqueue function as it is written needs the style to be registered in order to process the handle. Since the style was deregistered, it fails to load the style. Add a dequeue for the style so that it doesn't attempt to load the style:
`// Line 715:`
`wp_deregister_style('espresso_reg');`
`// add this`
`wp_dequeue_style('espresso_reg');`

**Comment by nerrad** [comment]
Internal Ticket: https://events.codebasehq.com/projects/event-espresso/tickets/11149

Thanks for reporting!  We'll get that fixed.

**Comment by nerrad** [comment]
fix for this has been merged to master.  Thanks for the report!
