### ISSUE TITLE
Anchor tag not closed on Duplicate Event button wreaking havoc on registration admin page

### ISSUE THREAD

**Issue by webaissance** [eventespresso/event-espresso-core#258]
On this file: event-espresso-core/caffeinated/admin/extend/events/Extend_Events_Admin_Page.core.php

Line 285 should close the anchor tag opened on line 279.

`      $return .= '<a href="'
                       . $href
                       . '" title="'
                       . $title
                       . '" id="ee-duplicate-event-button" class="button button-small"  value="duplicate_event">'
                       . $title
                       . '</button>';`

Since it's not closed it's wreaking havoc on the page and rendering it unusable.
I closed the anchor tag in the file on our site and now it works properly.
I don't know why this isn't affecting everyone the same way?

Please fix. Thank you.

### Is this a bug report?

* [X ] yes
* [ ] no

### What branch did this occur in?
event-espresso-core

### What version of WordPress is on the site this issue happened?
4.9.22.p

### If you were directed to create an issue here by the EE support team, what is the link to your original EE support forum thread?
N/A

### Outline the steps to reproduce
Edit an event

**Comment by nerrad** [comment]
Internal ticket: https://events.codebasehq.com/projects/event-espresso/tickets/11147

Thanks for the report.  We'll get that fixed.
