### ISSUE TITLE
Ticket Price Calculator UI Updates

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2586]
#### Please divide up changes into separate PRs accordingly (ie small related changes can go together)

- extract buttons from `TicketPriceCalculatorModal` and move into separate components inside `/buttons/` folder

- convert to use `ResponsiveTable` component

- add default base price if none exists upon initial launch of TPC

- add error class to price amount input if value is zero

- disable submit / prevent modal closing and add error message if price modifier is added without a value

- left align all buttons

- use Espresso Icons whenever possible or "filled" variants from AntD

- add the following tooltip to buttons:

    - Add Button: "add new price modifier after this row"

    - Delete Button: "delete price modifier"

- add basic confirmation modals to onClick handlers for delete button 

here's a screenshot from EDTR v1 to give a rough idea of previous appearance:

![ticket price calculator EDTR v1](https://user-images.githubusercontent.com/1751030/77377626-e5d4ae80-6d30-11ea-90f9-74bb3fe437c7.png)

**Comment by tn3rb** [comment]
just a heads up that you'll get conflicts with this branch after #2623 is merged

**Comment by nicolad** [comment]
> just a heads up that you'll get conflicts with this branch after #2623 is merged


that PR says `Unwanted Dependencies`, seems like I'll get `Unwanted Conflicts`
