### ISSUE TITLE
TPC Modal Sometimes Reloads Multiple Times

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2588]
steps to reproduce:

- refresh event editor page if one is not already open

- wait for all resources to load and initialize (ie wait for all toaster notices to clear)

- open the TPC and wait

I don't think it happens every time and am unsure of what else to do to reproduce issue 100% of the time

**Comment by manzoorwanijk** [comment]
It works fine from my end. May be I should check via your screen?

**Comment by tn3rb** [comment]
I'll keep an eye on this and see if I can identify some better steps for reproducing the issue

**Comment by manzoorwanijk** [comment]
Since we have switched to Chakra, this shouldn't be there anymore.
