### ISSUE TITLE
need to know about the hooks that triggers during registration process in EE4 admin setting

### ISSUE THREAD

**Issue by kamaljeetsug** [eventespresso/event-espresso-core#259]
Hi, I am using EE4. It  is not a bug report
I am using WordPress 4.7.3 version 
I need to know about the hooks that triggers during registration process in EE4 admin settings. On Event Espresso - Registrations page I want to show my content under "Add new registration" tab and I also want to create my own custom fields and add them to tickets next to quantity column. When someone click on "Add Tickets and Continue to Registrant Details" button, need to pass these custom fields values to next step. So, I want to know which hook I can use for this. I also want to pass these values to last step and when admin will click on "Apply payment" button. I need to send these values to third party API. For reference, Please check the screenshots that Ihave attached below
![add_ticket_continue_reg](https://user-images.githubusercontent.com/33868053/33075516-c3881fb0-ceef-11e7-91a5-18af704f0918.png)
![second_reg_step](https://user-images.githubusercontent.com/33868053/33075567-f9f97d46-ceef-11e7-865f-75ffbac5f8e6.png)
![last_reg](https://user-images.githubusercontent.com/33868053/33075578-0344e0ca-cef0-11e7-8197-0970a26e4a03.png)
Please check all and respond to my queries as soon as possible
Thanks

**Comment by nerrad** [comment]
Hi there,

All available hooks in EE can be found by searching for the `AHEE__` prefix for action hooks and `FHEE__` prefix for filter hooks in the codebase.  

Another trick I also often use when searching for places in the code I can maybe hook into is I pick something from the page content/page source that looks relatively unique to that page and then using my IDE I search for that string in the codebase.  Using that I can usually narrow down and follow the code stack to the logic in the code responsible for that process.
