### ISSUE TITLE
Ticket Assignments Manager UI Updates

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2590]
#### Modal

- modal window should be a fixed size relative to viewport

- modal header/title should include name and dbID for datetime / ticket, ie: `Ticket Assignment Manager for Datetime: 123 - My Event`

#### Filters

- date selector should default to whichever of the following options is most applicable:

     - current month

     - next upcoming month

     - last month in options list if all are expired     

- if ALL relations for entity are expired (or trashed) then default to toggling those flags accordingly

#### date column

- apply following changes to the date column td:

     - set width to 300px with `var(--ee-padding-small)` for padding 

     - add status stripe to left border of td with width of `var(--ee-padding-small)` and color set by entity color class helpers and right border of `5px solid var(--ee-color-white)`

     - set alternating background color using `var(--ee-color-grey-14)` and  `var(--ee-color-grey-13)` (ie: first row date column td uses 24, the next row uses 13, etc) and set one shade lower (ie: 13 -> 12 ) when hover state **for the entire row** is activated

- apply following changes to the cell contents:

     - wrap datetime id before name in `<div>` and add "ee-focus-priority-8" class

     - add datetime start date after name, wrap in `<div>`, and add "ee-focus-priority-6" class

     - wrap datetime name in `<div>` and add "ee-focus-priority-5" class and the following css styles via a class:

```css
      font-weight: bold;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
      width: calc(300px - (var(--ee-padding-small) * 2));
```

#### ticket header

- apply following changes to the td:

     - strip padding, center text

- apply following changes to the cell contents:

     - add inner div wrapper with `padding: var(--ee-padding-nano) var(--ee-padding-tiny);`

     - wrap ticket id before name in `<div>` and add "ee-focus-priority-8" class

     - add ticket price after name in `<div>` and add "ee-focus-priority-8" class

     - wrap ticket name in `<div>` and add "ee-focus-priority-5" class and the following css styles via a class:

```css
  font-weight: bold;
  line-height: 1.1;
  margin: 0 0 var(--ee-margin-micro);
  max-height: calc(var(--ee-font-size-default) * 8);
  overflow: hidden;
  padding: var(--ee-padding-tiny) 0;
  text-align: center;
  width: calc(100px - (var(--ee-padding-smaller) * 2));
```

- then add a div for the status AFTER the inner div wrapper

     - add `ee-focus-priority-6` class

     - set css via class to `font-weight:bold; padding:var(--ee-padding-micro); text-transform: uppercase; width to 100%`

     - apply background using status helper classes for tickets

     - insert ticket start date using format like "MMM DD YYYY"  ex: `MAR 24 2020` 

#### relation buttons

- relations buttons should fill each table cell, ie: 100px square

- icons should be increased in size to 36px square (`var(--ee-icon-button-size)`) with svg fill changed to white

- padding for table rows should be removed completely and padding for cells use `var(--ee-padding-nano)`

- button color should be applied directly to buttons and not the parent cell, ie: currently there are classes like `.old-assignment` applied to the `<td>` tag with a corresponding css style like: `#ticket-assignment-manager-table .old-assignment { background-color: var(--ee-color-primary) !important; }`. This just needs to be changed to something like `#ticket-assignment-manager-table .old-assignment .ant-btn { background: var(--ee-color-primary); }`

Here is a somewhat accurate image showing the above after haxxoring the DOM:

![Ticket Assignments Manager - ticket header and date column](https://user-images.githubusercontent.com/1751030/77369430-dac35380-6d1b-11ea-820d-4c6e9497bb11.png)

**Comment by manzoorwanijk** [comment]
@tn3rb I would suggest to use the modal the way I used for TPC which used the `<Modal />` component which aware of the context. It has many benefits like faster validations and lesser re-renders inside the modal.

**Comment by nicolad** [comment]
Let's pull out this part, it's a bit unclear:
```
#### Filters

- date selector should default to whichever of the following options is most applicable:

     - current month

     - next upcoming month

     - last month in options list if all are expired     

- if ALL relations for entity are expired (or trashed) then default to toggling those flags accordingly
```
