### ISSUE TITLE
Fix Tickets List Filter Bar isChained Filter

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2595]
### steps to reproduce issue

- open filters for dates list

- try different **status** filter options until you find an option that gives either 1 single datetime as a result or zero datetimes

- open filters for ticket list

- click on new **status** filter and select "all tickets for all dates"

- take note of what tickets are showing and total number of tickets (we don't actually display that number but number of pages will suffice)

- click on the "**isChained**" filter button beside the **status** filter

- the **status** filter options _should_ change to "all tickets for above dates only" (or something like that) and the number of tickets in the entity list should change accordingly to reflect only those related to the dates in the dates list (zero tickets if zero dates are displayed)

### other issues

- the "**isChained**" filter button should default to being chained to the dates list (ie: default value === true)

- let's add a label above the button similar to how all of the other filters have a label (ex: status, sales, etc). This label can simply be "link"

- the hover state for the "**isChained**" filter button also needs tweaking when the button is active. It needs the fill color for the icon to be set to `var(--ee-color-white)`

**isChained** filter button hover state:

![isChained button hover state](https://user-images.githubusercontent.com/1751030/77450663-d6954580-6db0-11ea-9fe3-8898a21f6861.png)

### mobile view

- on small screens the filters all look really good, but could be expanded to 100% width

- the isChained button however loses its tooltip because there is no hover state for touch devices

- let's duplicate the tooltip text for ALL Espresso Buttons and add it to the DOM after the button in a div that only gets displayed on screens less than 480px. In fact, it may be best to create an adapter for AntD's `Tooltip` component and add this logic to that

here's an image showing what I'm thinking:

![isChained button on mobile](https://user-images.githubusercontent.com/1751030/77452746-88ce0c80-6db3-11ea-9ba1-7c7c3347f62d.png)

plz feel free to split up into more than one PR

**Comment by nicolad** [comment]
will try to reproduce, but atm chain tooltip is showing:

![image](https://user-images.githubusercontent.com/1477453/77473433-24946280-6e1e-11ea-9de7-261f2c54fefa.png)
