### ISSUE TITLE
Evaluate Error Handling in Apollo

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2597]
Best practices flowchart: https://miro.medium.com/max/2796/1*jAXRW3PCreEw9ftHnD6maw.png

More info [here](https://www.apollographql.com/docs/react/data/error-handling/)

Using the above information, please examine our existing code and identify any areas where error handling and/or user proofing can be improved

**Comment by manzoorwanijk** [comment]
We only have two areas where we can improve the error handling:

1. Initial queries
When the Apollo cache is rehydrated using DOM data, this data may be inconsistent if there is any server-side error while creating the DOM dump. In this case, we may have to disable EDTR completely with an error message. An example of such error is not having any default price.

2. Mutations
Currently the mutation error messages are too generic and don't provide much information to the user. This means we need to work on #2418 and then add more information to error toasters.

**Comment by manzoorwanijk** [comment]
This is done via #2418 and #2843
