### ISSUE TITLE
Improve User Feedback when Actions are Taken

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2600]
If an event has a lot of dates and tickets, there are significantly noticeable delays that occur when performing some actions such as:

- switching between the card view and table view for entity lists

- selecting different options from filter bar filters that change which entities are displayed

- selecting the next page via the entity list pagination

- clicking submit on any modal

We want to try and iron out as many of these issues as possible and/or add user feedback to indicate an action is in progress

#### next steps

- benchmark time between the instant a user action is initiated and the first user feedback they receive (which is currently the toaster notices in the bottom right corner of the screen)

- identify any bottlenecks and evaluate whether code changes and/or optimizations can be applied to improve performance

- if no other improvements can be made, then evaluate whether additional user feedback can be made, such as changing icons on buttons to spinners upon clicking

- document findings in this issue and list pros and cons of various solutions

- apply whatever fixes have been decided upon

- ideally fixes should be abstracted and located in application/domain wide components as opposed to single use case components, as long as their effectiveness is not diminished, for example: loading state spinners would be best applied to Espresso Button and controlled via props as opposed to a single specific button in a single domain component, but only if the abstraction does not impede its functionality, ie: we want feedback to be as instantaneous as possible.

**Comment by manzoorwanijk** [comment]
It's quite difficult to show any feedback because all of these operations are synchronous. These issues are more accurately performance issues which can be solved or at least minimized by optimizations.

**Comment by nicolad** [comment]
I'll try to investigate pagination and filtering here: https://github.com/eventespresso/event-espresso-core/issues/2860

**Comment by tn3rb** [comment]
closing this because latest EDTR is pretty speedy after recent optimization efforts
