### ISSUE TITLE
Question:-  create custom questions in the Event Espresso - Registration Form admin page.

### ISSUE THREAD

**Issue by kamaljeetsug** [eventespresso/event-espresso-core#261]
How to create custom questions by using code  in the Event Espresso - Registration Form admin page?
I am already able to create new question type using this filter "FHEE__EEM_Question__construct__allowed_question_types"  but not able to find the filter that can generate new question and assign it to a question group. So, Please check and let me know as soon as possible

**Comment by mnelson4** [comment]
hey @kamaljeetsug, so you've added a new question type, great. Now you should be able to use the registration form admin page to create a question of that type, and assign it to a group. 
If you don't want to use the WP admin, you can use the models to create a question, and then associate it with a question group. 
Please see https://github.com/eventespresso/event-espresso-core/blob/master/docs/G--Model-System/using-ee4-model-objects.md, especially the part about saving model objects, and "Adding and Removing Related Model Objects". In this case, you'll want to createa  new `EE_Question`, set its type to your new type, then associate it with the question group you want.

Let me know our documentation isn't helpful, or if you need more clarification.

**Comment by kamaljeetsug** [comment]
Okay @mnelson4 , thanks for a quick reply. But I think creating a new question will not be a good idea.
Instead if this creating hidden input fields will be great.  I want to populate these fields and want to get them when registration got completed in admin page. Please check the screenshot and see the blank space. Its the place where I want to create  some hidden fields and text fields
![image](https://user-images.githubusercontent.com/33868053/33154337-b7a77208-d00d-11e7-8f8b-8758b9ce456a.png)
Could you please let me know how can I do that without making changes to core plugin files ?
Thanks

**Comment by mnelson4** [comment]
Sorry @kamaljeetsug I don't think I understand what you're wanting to achieve quite as well as you do. It sounds like you want a pretty extensive customization to the admin-side SPCO (single page checkout) which isn't as simple as just "put the code here". You're going to need to familiarize yourself with how `modules/single_page_checkout/EED_Single_Page_Checkout.module.php` works, I don't think I can walk you through it in the amount of time allowed by free support on GitHub.

It would probably be best to just dive into that SPCO code and make temporary changes to the EE core files and get what you want working. Then once you know where you need to make changes, instead add an action or filter, and hook into those actions or filters from your own plugin or custom code, and open a pull request with the proposed changes (if any are necessary).

**Comment by sethshoultes** [comment]
@tn3rb can you point @kamaljeetsug to any hooks or filters in the admin SPCO that he can use to pull in his data or add hidden fields easier?

**Comment by kamaljeetsug** [comment]
Nevermind @sethshoultes I have figured out myself how to create hidden fields there. But I will update you if I will face any issue further
Regards
