### ISSUE TITLE
Add Confirmation Modals to Event Handlers for Destructive Processes

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2613]
Currently a user can click on buttons (or perform keypresses) for destructive events, like deleting an entity or closing a form, and there is nothing to prevent that from happening if the click or keypress was accidental.

Therefore we need to add a confirmation step prior to performing any kind of destructive logic

- delete buttons
- modal cancel button
- modal close button
- ESC key (onKeyPress handler)

The [AntD Popconfirm component](https://ant.design/components/popconfirm/) is designed specifically for this use case

**Comment by nicolad** [comment]
@tn3rb I found this interesting property [`shouldCloseOnEsc`](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/modal#shouldcloseonesc), that andt modal is missing :disappointed:

**Comment by nicolad** [comment]
Need to improve close icon in context of `ConfirmClose` from here: https://github.com/eventespresso/event-espresso-core/pull/2698#discussion_r409101306

**Comment by nicolad** [comment]
Tried to use `ConfirmDelete` for `TrashDate` and `TrashTicket`, but it won't work.
This has to do with `DropdownMenuItem`
***
@tn3rb IMO we might create a tech debt issue and deal with the described case later, what do you think?

**Comment by tn3rb** [comment]
can you plz elaborate on how/why it didn't work? ie: were there errors?

and can you also plz elaborate on what you tried ? (don't need to go to in depth)

but we definitely want to try and solve this issue

**Comment by nicolad** [comment]
the first approach was same as here: https://github.com/eventespresso/event-espresso-core/pull/2631/files#diff-8d8ef418b51b3a9b4767b5c4bfd88bb6L16

**Comment by nicolad** [comment]
Created a draft to document what I tried: https://github.com/eventespresso/event-espresso-core/pull/2730

**Comment by nicolad** [comment]
@tn3rb while I was testing delete button in table view I noticed that `.ee-rspnsv-table-wrapper` has this property `overflow-x: auto;` which is cutting the dropdown. Before doing any changes there I need to know if there aren't any implications related to that property, in case I would delete that.

![image](https://user-images.githubusercontent.com/1477453/81165379-8b1eab80-8f9a-11ea-83f9-b42303659819.png)
***
![image](https://user-images.githubusercontent.com/1477453/81165421-9c67b800-8f9a-11ea-92a4-09727ad38bf7.png)

**Comment by nicolad** [comment]
Tested delete buttons:

![Peek 2020-05-06 13-10](https://user-images.githubusercontent.com/1477453/81165671-10a25b80-8f9b-11ea-91fa-19418e81e053.gif)

**Comment by nicolad** [comment]
In TAM, when there are errors cancel button is disabled:

![image](https://user-images.githubusercontent.com/1477453/81170276-11d78680-8fa3-11ea-9414-8f8c5e3c48f5.png)
