### ISSUE TITLE
The Great Disappearing Date  Card Sidebar Trick

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2615]
### steps to reproduce the issue:

- click on the edit date button for any date in the dates list

- change the date or time and click submit on the modal form

- voila! you're a wizard Harry!

Here's a screenie showing this dark magic in action:

![Date Sidebar Issue.gif](https://images.zenhubusercontent.com/55c8c0f14f7a08fbb7f431cd/9ac9da2e-9187-432d-8429-1880170981ca)

**Comment by manzoorwanijk** [comment]
This has already been fixed via #2612
