### ISSUE TITLE
Add cacheID property to Entity Interface

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2621]
- add `cacheID` property to Entity Interface

- do the following only when an entity is updated:

     -  remove existing `cacheID` property

     -  run entity through `JSON.stringify()`

     -  save that value as new `cacheID` property

- this value can now be used throughout the codebase for memoization purposes as a way to easily determine if an entity has been updated

ex:

```js
return useMemo( () => (
    <SomeComponent entity={entity} etc={etc} {...props} />
), [entity.cacheID] );
```

**Comment by manzoorwanijk** [comment]
What about using `uuid()` to generate `cacheID`?

**Comment by manzoorwanijk** [comment]
Also, that field will also have to be added to GQL schema

**Comment by tn3rb** [comment]
two potential reasons come to mind:

- UUIDs are known for being complex to generate (one of the arguments against using them) and so running `JSON.stringify()` on our entities _could potentially_ be more efficient than generating a UUID

- if a process results in a mutation being called on an entity, even though it's properties have not changed, then generating a new UUID for the cache ID would make it look like the entity had changed, whereas `JSON.stringify()` would result in the same cache ID and therefore not trigger any re-renders or cache invalidations

Not saying that either of those points is 100% valid, as both would need to be investigated to know for certain what the reality of the situation actually is.

ie:

- generating UUIDs _could_ be faster than stringifying an entity

- there may already be logic in place to prevent an entity from being updated and flushed from cache if none of its properties have changed

so if those two points are true, then UUIDs would be the better solution

**Comment by tn3rb** [comment]
> that field will also have to be added to GQL schema

even if it's only ever used in client side code?

**Comment by manzoorwanijk** [comment]
There are many reason for `JSON.stringify` not being a good solution:
-  `cacheId` will be a field of an entity but it has to be aware of its parent in full, which is against the GQL principles.
- Mutation does not always result in complete object update, very often just a few fields are updated. It will be difficult to get the full object to convert to JSON at the time of doing mutation cache update.
- The result of `JSON.stringify` will be a full entity thus will be a long string which will be duplication of the whole data in Apollo Cache, where as `uuid` string will be of fixed length - not too long.

**Comment by manzoorwanijk** [comment]
> even if it's only ever used in client side code?
Yes, because we are going to add that field to Apollo cache locally, it should match the query schema. The first time, `cacheId` will come from server, then its subsequent updates will be client-side.

**Comment by manzoorwanijk** [comment]
Otherwise, we can make use of `@client` directive of Apollo to keep it only client-side.

**Comment by tn3rb** [comment]
imho it would serve no purpose server side, so might be best to "make use of @client directive of Apollo"

that said, it's possible that it might be beneficial to persist to the db for use in other places.

If we do decide to persist to the db and utilize within PHP, then using UUIDs would be beneficial for the following reasons (in addition to the reasons you listed for using them):

- UUIDs would likely take up less space in the db than a stringified object, which has multiple benefits on its own (speed, indexing, etc)

- the PHP and JS versions for converting to and from JSON are not 100% compatible, so if for some reason you wanted to decode a stringified object server side, you have to perform a few extra steps to prepare the JSON for things to work (like stripslashes, html_entity_decode, etc). However, that's very unlikely to happen since the purpose of the cache ID is simply to be able to quickly identify if an object has changed, and any data contained within the stringified object would be present in the PHP object.

So at this point I think we want to:

- use UUIDs for the cache ID

- keep the cache IDs client side only

**Comment by manzoorwanijk** [comment]
> So at this point I think we want to:
> 
> - use UUIDs for the cache ID
> 
> - keep the cache IDs client side only
> 

Sounds great
