### ISSUE TITLE
LIN_quantity doesnt gets updated 

### ISSUE THREAD

**Issue by 5Hemant** [eventespresso/event-espresso-core#264]
> Before submitting your issue, please ensure that what you are reporting is specific to Event Espresso 4.

When submitting an issue, please follow this rough guideline for your report.

### Is this a bug report?

* [ ] yes
* [x] no

Hello,
I am trying to recalculate the cart item in "AHEE__Single_Page_Checkout__after_attendee_information__process_reg_step" hook. The "LIN_unit_price"  gets updated quite well but "LIN_quantity doesnt gets updated".
CODE:
	$purchases = $data->checkout->transaction->items_purchased();
	$first_item = reset($purchases);
   //we need to edit the sub-item's unit price, as
   //the line item's total is calculated from its sub-items
   $children = $first_item->children();
   $child_line_item = reset($children);
    $child_line_item->set('LIN_quantity', 5); ==========> **Doesnt gets updated!!!!**
   $child_line_item->set('LIN_unit_price', 10);
   $data->checkout->cart->get_grand_total()->recalculate_total_including_taxes();
   $data->update_checkout();

**Comment by mnelson4** [comment]
hey @5Hemant , I'm pretty sure you need to change the quantity on `$first_item` (the line item representing the ticket or thing purchased), not $child_line_item (the sub-line item, representing a price that gets factored into the price of the line item).
Does that make sense?
I'm pretty sure that will fix your issue

**Comment by 5Hemant** [comment]
Hi @mnelson4 Thank you for your reply, But i tried doing : $first_item->set('LIN_quantity', 5); This didn't made any changes to the cart. Is there anything i need to add for this to work??

**Comment by mnelson4** [comment]
You may need to explicitly save the line item, eg use `$line_item->save();` before recalculating the total.
That's what `EEH_Line_Item::increment_quantity()` does

**Comment by 5Hemant** [comment]
Hello @mnelson4 , I've been trying this since some days but i'm struggling it to get this work. 
My function has two parameters (EE_SPCO_Reg_Step_Attendee_Information $data , EE_Line_Item $total_line_item), at first there was only "EE_SPCO_Reg_Step_Attendee_Information $data" as i had to change the child line item i.e LIN Unit Price but i have to update the quantity and for that i have to use "EE_Line_Item $total_line_item" too. 
I'm not sure that my function will receive these two parameters as it runs on "AHEE__Single_Page_Checkout__after_attendee_information__process_reg_step" hook. Do i need to create another custom function on the same hook or i can accomplish them in same function?

Regards

**Comment by mnelson4** [comment]
@5Hemant I'm pretty confused by what you're asking, but here's my attempt at a response.

> My function has two parameters (EE_SPCO_Reg_Step_Attendee_Information $data , EE_Line_Item $total_line_item), at first there was only "EE_SPCO_Reg_Step_Attendee_Information $data" as i had to change the child line item i.e LIN Unit Price but i have to update the quantity too and for that i have to use "EE_Line_Item $total_line_item" too.

The hook `AHEE__Single_Page_Checkout__after_attendee_information__process_reg_step` only provides one parameter, the current step, ie `EE_SPCO_Reg_Step_Attendee_Information $data`. I don't see where it would provide the total line item.

In your original code sample you were accessing the line item for the ticket purchased and its child line item; you can easily change the quantity on the line item for the ticket purchase, and change the unit price on the child line item, like so:

```
$purchases = $data->checkout->transaction->items_purchased();
$first_item = reset($purchases);
$first_item->set('LIN_quantity', 5); //==========> Edits items quantity
$first_item->save(); //=============> don't forget to save!
//we need to edit the sub-item's unit price, as
//the line item's total is calculated from its sub-items
$children = $first_item->children();
$child_line_item = reset($children);
$child_line_item->set('LIN_unit_price', 10); //========>Edits item's unit price
$child_line_item->save(); //========>don't forget to save!
$data->checkout->cart->get_grand_total()->recalculate_total_including_taxes();
$data->update_checkout();
```

> Do i need to create another custom function on the same hook or i can accomplish them in same function?

No you shouldn't need any other function. I hope the above illustrates what you need to do. 

If you're still having trouble, please provide me with your working code that I can run and reproduce the issue with. If your code isn't on GitHub or something similar, I'd highly recommend putting it on there. (Elevates your reputation as a developer, and allows easier integration). If you're really opposed to that, please email your working code (preferably as a zipped plugin) to support (at) eventespresso.com

**Comment by 5Hemant** [comment]
@mnelson4 First of all thankyou for your nice suggestion. Im looking forward to add my code to github. But i think im close to make my code work.
Your sample is the same thing what i've done. I had forgot to save both the line item and the child line item. But the child line item unit price changed even i didnt saved it. 
$child_line_item->set('LIN_unit_price', 20); =================> this worked even while not saving!!

The quantity doesnt got changed!!
 $first_item->set('LIN_quantity', 5); 
 $first_item->save(); ====================> I added this line but still it doesnt show up!! 

Here's my full code:
/**
 * [custom_hook ==== function to update ticket and datetime table and cart items unit price]
 * @param  EE_SPCO_Reg_Step_Attendee_Information $data [Attendees data]
 * @return [type]                                      [object]
 */
add_action('AHEE__Single_Page_Checkout__after_attendee_information__process_reg_step', 'custom_hook', 10, 1);
function custom_hook(EE_SPCO_Reg_Step_Attendee_Information $data)
{
	$purchases = $data->checkout->transaction->items_purchased();
	$first_item = reset($purchases);
    $first_item->set('LIN_quantity', 5);
    $first_item->save();
   //we need to edit the sub-item's unit price, as
   //the line item's total is calculated from its sub-items
   $children = $first_item->children();
   $child_line_item = reset($children);
   $event_unit = $child_line_item->get('LIN_unit_price');
	//$quantity = $recSess*$event_unit ;
   // die();

   $child_line_item->set('LIN_unit_price', 20);
   $child_line_item->save();

   $data->checkout->cart->get_grand_total()->recalculate_total_including_taxes();
   $data->update_checkout();
	// update cart amount

}
One thing is that, i had some changes on the core plugin file where i changed  ticket selector dropdown to a simple input where only 1 ticket could be selected as i didnt wanted users to select bulk tickets.  Did this blocked our code??

Regards

**Comment by mnelson4** [comment]
ok thanks for providing the exact code so I could run it. It turns out it IS updating the line item's price and quantity, but the quantity change isn't being shown in the payment options step (the unit price change, however, is appearing). If you look at the "order confirmation" linked-to from the thank-you page, you'll see the order got updated.

@tn3rb do you have any idea why updating a line item's quantity  on the `AHEE__Single_Page_Checkout__after_attendee_information__process_reg_step` hook doesn't get displayed on the payment options step- but if you change a line item's unit price on that same hook it does?

> One thing is that, i had some changes on the core plugin file where i changed ticket selector dropdown to a simple input where only 1 ticket could be selected as i didnt wanted users to select bulk tickets. Did this blocked our code?? Knowing that this is a wrong way to update things on core. I would also be grateful if you have any idea how to change the dropdown to a simple input with just 1 ticket without changing core plugin files.

@5Hemant please create a separate issue for that and define what you mean by "simple input". I think you should just set the event's "Maximum number of tickets allowed per order for this event" to 1 in the event editor.

**Comment by 5Hemant** [comment]
@mnelson4  @tn3rb  
"One thing is that, i had some changes on the core plugin file where i changed ticket selector dropdown to a simple input where only 1 ticket could be selected as i didnt wanted users to select bulk tickets. Did this blocked our code?? Knowing that this is a wrong way to update things on core. I would also be grateful if you have any idea how to change the dropdown to a simple input with just 1 ticket without changing core plugin files."
I mean, there is a dropdown with bulk ticket selector for each events and i didnt wanted this so i edited plugin core template and change the dropdown to a simple input field where just 1 ticket can be selected. So i was wondering, if this has anything connected with our hook that is not working or not? 

Regards

**Comment by tn3rb** [comment]
I believe with the line items that you need to change the quantity of the Price sub-items as well as the Ticket line-items. 
For example, if you have a single $10 ticket, then both its Ticket line-item and its Price sub-item will have a   quantity of 1 and a unit-price of $10. 
If you change the Ticket line-item quantity to 2, but leave it's Price sub-item quantity at 1.
Then  when the cart recalculates totals, it will use the Price sub-item quantity of 1.

So in your code where you   do this:

```php
    $child_line_item->set('LIN_unit_price', 20);
    $child_line_item->save();
```

I think you need to do this:

```php
    $child_line_item->set('LIN_quantity', 5); // or whatever the actual  quantity is
    $child_line_item->set('LIN_unit_price', 20);
    $child_line_item->save();
```

**Comment by tn3rb** [comment]
going to assume that no news is good news since you haven't responded since December 2017.
