### ISSUE TITLE
Filter Bar Table View and Card View Button Tooltips Do Not Close

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2652]
If you click on either of the Table View or Card View buttons in either of the filter bars, the tooltips that appear when you first click on them do not disappear after the view changes and you are left with something like this:

![Filter Bar Tooltips.png](https://images.zenhubusercontent.com/55c8c0f14f7a08fbb7f431cd/4db25189-2c18-4e5f-baf5-8c7885bf8b5a)

I'm guessing it is a memoization issue

**Comment by manzoorwanijk** [comment]
Memoization is not the reason for that. It may be because the button is disabled after switching to its view.
