### ISSUE TITLE
Wire Up Drag n Drop Functionality for Dates List and Tickets List Table Views

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2653]
Just realized that this was not done already :\

- see: `assets\ZZZ\editor\events\dates-and-times\editor-date\datesListView\use-reorder-dates.js` in current `EDTR/master` or `assets\src\editor\events\dates-and-times\editor-date\list-view\use-reorder-dates.js` in the `EDTR/refactor-master` branch

- see `assets\src\editor\events\tickets\editor-ticket\list-view\use-reorder-tickets.js` in the `EDTR/refactor-master` branch

- the above need to be passed to the `onDragEnd` prop of the  `ResponsiveTable` component

- `useReorderDates()` (as well as `useReorderTickets()`) utilized `useReorderEntities()` which can be found here: `assets\src\components\ui\entity-list\use-reorder-entities.js` in the `EDTR/refactor-master` branch, which basically loops through all of the entities in the current list, and adjusts their `order` property accordingly

- plz note that after reordering the entities, the value for the "sort by" filter bar filter needs to be changed to "custom order" so that the entity list reflects the new order

**Comment by manzoorwanijk** [comment]
This seems to be a topic for discussion because it involves updating/mutating all dates/tickets in the list which is going to be a huge operation if the list is big.

**Comment by tn3rb** [comment]
there's basically two paths we can go with regards to how persistence requests to the server are made:

#### immediate persistence
- all updates, inserts, and deletion requests are sent immediately to the server

- pros:
     - the DB and EDTR are always in sync

     - immediate feedback if something went wrong

     - user does not have to wait as long after clicking the "save" (or "Publish") button in the event editor

     - less data loss overall if the event editor crashes

- cons:
     - events will need to be placed in some kind of "maintenance mode" when they are being edited so that incomplete data (like tickets with no prices) doesn't appear on the website

     - user may forget to click the "save" button in the event editor after making other changes on the page that still require them to do so (like changing questions for the reg form)


#### deferred persistence
- all updates, inserts, and deletion requests are only applied to the Apollo cache and then when the user clicks the "save" (or "Publish") button in the event editor, ALL changes are sent to the server for persistence 

- pros:
     - less waiting for persistence requests to finish while editing an event, especially for complex updates

     - the events do not need to be placed in some kind of "maintenance mode" when they are being edited 

- cons:
     - the DB and EDTR are not in sync until the user clicks the "save" (or "Publish") button in the event editor

     - if the event editor crashes, the user could lose a LOT of changes

**Comment by manzoorwanijk** [comment]
One more approach to try is debounced mutations.

**Comment by tn3rb** [comment]
let's re-address this issue... I'm inclined to continue along with immediate persistence, in which case, we will just have to deal with the reordering request to be a bit big, although bath requests have already been enabled no?

If so, then let's bundle all of the updates triggered by reordering and fire them off in one request.

> One more approach to try is debounced mutations.

Can you elaborate on this please?

**Comment by manzoorwanijk** [comment]
I explored that approach but seems like you can't really debounce them.
