### ISSUE TITLE
Update Modal in AntD Fork to Allow Confirmation Modals for ESC, Close, and Cancel Actions

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2659]
- plz see #2613

@nicolad

can you plz list any additional details regarding specific properties and/or functionality that you discovered to be missing from the AntD Modal while working on #2636

**Comment by nicolad** [comment]
the `onDismiss` property from `@reach-ui/dialog` would be nice to have: https://github.com/reach/reach-ui/blob/master/packages/dialog/src/index.tsx#L267
here is the description from there:
```
  /**
   * This function is called whenever the user hits "Escape" or clicks outside
   * the dialog. _It's important to close the dialog `onDismiss`_.
   *
   * The only time you shouldn't close the dialog on dismiss is when the dialog
   * requires a choice and none of them are "cancel". For example, perhaps two
   * records need to be merged and the user needs to pick the surviving record.
   * Neither choice is less destructive than the other, so in these cases you
   * may want to alert the user they need to a make a choice on dismiss instead
   * of closing the dialog.
   *
   * @see Docs https://reacttraining.com/reach-ui/dialog#dialog-ondismiss
   */
```

**Comment by nicolad** [comment]
in cases we want just to disable closing modal upon pressing escape, than GB's `shouldcloseonesc` might come handy: https://github.com/WordPress/gutenberg/tree/master/packages/components/src/modal#shouldcloseonesc

**Comment by nicolad** [comment]
another very optional and not directly related property is `returnFocusOnClose` from chakra: https://chakra-ui.com/modal
because currently when modal is closed with escape focus is lost :cry: 

![Peek 2020-04-06 21-27](https://user-images.githubusercontent.com/1477453/78592411-bb651400-784d-11ea-8cd5-0f5a23552317.gif)

**Comment by nicolad** [comment]
this is not actual now since we already are using chakra modal
