### ISSUE TITLE
Add hover text to action icons on My Account page

### ISSUE THREAD

**Issue by sewmyheadon** [eventespresso/event-espresso-core#266]
### Is this a bug report?

* [ ] yes
* [X] no

### What branch did this occur in?
4.9.53.p

### What version of WordPress is on the site this issue happened?
4.9

### Outline the steps to reproduce
When on the My Account page and you click the gear icon under Registrations to see ticket details, there's a cluster of Action Icons and they should reveal their purposes on hover.

Of course, there's a key below this area showing exactly what these icons mean, but in conducting usability tests on EE with customers, we saw people get confused by this repeatedly. They kept moving the mouse around waiting for the tooltip telling them what the icon does.

### Screenshot

![ee_actions_icons](https://user-images.githubusercontent.com/2308362/33406574-70f3b280-d522-11e7-9cc4-f24370697496.png)

### Screencast
[30 second screencast](https://goo.gl/QyQSa9)

### Please include any links to the page(s) demonstrating this issue (if possible).

This is default EE behavior that you can see in any install on the My Accounts page.

**Comment by tn3rb** [comment]
So specifically you are referring to whatever page you have `[ESPRESSO_MY_EVENTS]` shortcode from the WP Users addon on  right?
Confused me for a minute because I didn't know what the "My Account" page was (I think that's a page you added as it is not part of EE).

So  basically  we just need to add title attributes to the action links in

```
/eea-wpuser/templates/content-espresso_my_events-event_section_tickets.template.php
```

**Comment by sewmyheadon** [comment]
> So specifically you are referring to whatever page you have [ESPRESSO_MY_EVENTS] shortcode from the WP Users addon on right?

Yes, exactly. Sorry, I forgot that it's a result of the WP Users Add-on.

> So basically we just need to add title attributes to the action links in `/eea-wpuser/templates/content-espresso_my_events-event_section_tickets.template.php`

Yes. Thanks, Brent!

**Comment by nerrad** [comment]
Issue moved to [eventespresso/eea-wpuser-integration #5](https://github.com/eventespresso/eea-wpuser-integration/issues/5) via [**ZenHub**](https://www.zenhub.com/)
