### ISSUE TITLE
Replace babel-plugin-makepot

### ISSUE THREAD

**Issue by manzoorwanijk** [eventespresso/event-espresso-core#2666]
@wordpress has moved @wordpress/babel-plugin-makepot to WP CLI

https://github.com/WordPress/gutenberg/issues/14780#issuecomment-479410142

**Comment by nicolad** [comment]
Based on this: https://developer.wordpress.org/block-editor/developers/internationalization/#create-translation-file
and this message: https://eventespresso.slack.com/archives/C080DDVLM/p1586266708397300
I assume that there is no need to replace `babel-plugin-makepot` with another babel plugin.
@manzoorwanijk please confirm
cc @tn3rb

**Comment by manzoorwanijk** [comment]
Yeah, no other babel plugin. It needs to be integrated with CLI build process. May be require `wp-cli` in composer.json then use `./vendor/bin/wp` for wp-cli.

**Comment by tn3rb** [comment]
see: https://github.com/eventespresso/grunt-wp-plugin-buildmachine/issues/8

**Comment by manzoorwanijk** [comment]
I have created [this issue](https://github.com/WordPress/gutenberg/issues/21466) upstream, hope that it gets fixed soon.
