### ISSUE TITLE
Research Alternate Datepicker / Timepicker Library Options 

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2667]
Chakra UI has no datepicker nor timepicker therefore we need to find alternatives

- please list potential candidates here with a brief list of pros/cons for each (if easily possible)

**Comment by nicolad** [comment]
First option, since we used that before is the components from `blueprint`:
- https://github.com/palantir/blueprint/blob/develop/packages/datetime/src/datepicker.md
- https://github.com/palantir/blueprint/blob/develop/packages/datetime/src/timepicker.md
***
interesting aspect about those: `DatePicker is built on top of the react-day-picker library.`
***
in case we will need to create our own clone, it has: `Apache License 2.0`

**Comment by nicolad** [comment]
another option is `DateTimePicker` from GB, which uses `react-dates` under the hood

**Comment by nicolad** [comment]
since those 2 :point_up: relies on external libs under the hood, I've taken a quick look at top 3 libs :point_down:

**Comment by nicolad** [comment]
| Library                                                              | Pros                                                                                                                                                                                             | Cons                                                                                                                                                                                                                                                                                                                                                                           | Stars |
| -------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ----- |
| [`react-dates`](https://github.com/airbnb/react-dates)               | - backed up by airbnb <br> - internationalizable, accessible, mobile-friendly <br> - theme support                                                                                               | - no TS support, it uses just `PropTypes` <br>- it uses `react-with-styles` for library initilization <br>- they do provide a way to [override styles](https://github.com/airbnb/react-dates/blob/master/README.md#overriding-styles)<br>- they use [interfaces](https://github.com/airbnb/react-dates/blob/master/README.md#interfaces) for styles a bit uncommon way for CSS | 10k   |
| [`react-datepicker`](https://github.com/Hacker0x01/react-datepicker) | [Localization relies on `date-fns`](https://github.com/Hacker0x01/react-datepicker#localization) <br> - Accessibility [support](https://github.com/Hacker0x01/react-datepicker#keyboard-support) | - no TS support <br> -                                                                                                                                                                                                                                                                                                                                                         | 4.6k  |
| [`react-day-picker`](https://github.com/gpbl/react-day-picker)       | - v8 is coming! The next version will be a rewrite in TypeScript. Read more [here](https://github.com/gpbl/react-day-picker/issues/942) <br> - Localizable                                       | - no TS support yet, TBD                                                                                                                                                                                                                                                                                                                                                       | 3.7k  |

**Comment by tn3rb** [comment]
that link you posted regarding `react-day-picker` v8 also states that they will be rewriting to use `date-fns` as well as `TypeScript`

**Comment by manzoorwanijk** [comment]
Unofficial types for `react-dates` https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dates/
