### ISSUE TITLE
Replace Other AntD UI Display Components with Chakra UI Equivalents 

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2673]
#### Alert
- `\domain\eventEditor\ui\ticketAssignmentsManager\components\ErrorMessage.tsx`
- replace with Chakra UI Alert

#### Avatar
- `\application\ui\display\Avatar.tsx`
- replace with Chakra UI Avatar

#### Badge
- `\application\ui\display\Avatar.tsx`
- `\application\ui\display\ItemCount\index.tsx`
- replace with custom component created using some of the logic and css from `\components\ui\icon-menu-item` in the `EDTR/refactor-master` branch

#### Collapse/Panel
- `\application\ui\display\DebugInfo.tsx`
- replace with Chakra UI Collapse

#### Empty
- `\application\ui\display\EmptyState.tsx`
- replace with custom composition similar to what's done here: [Chakra UI Alert](https://chakra-ui.com/alert#composition) but using the subcomponents listed in the Props section directly (ie: Box, Flex, Icon) with the icon being something like:
```css
<Icon name="question-outline" size='96px' color='gray.100'/>
```

#### Popconfirm
- `\application\ui\layout\confirmDelete\ConfirmDelete.tsx`
- replace with Chakra UI AlertDialog

#### Popover
- `\application\ui\calendars\dateDisplay\TimezoneTimeInfo\index.tsx`
- replace with Chakra UI Popover

#### Result
- `\application\ui\display\ErrorIndicator.tsx`
- replace with same custom component used to replace `Empty`, but use the warning icon with `red.500` (until we get a theme set up)

#### Spin
- `\application\services\toaster\useToastManager.tsx`
- `\application\ui\display\LoadingIndicator.tsx`
- `\application\ui\display\loadingNotice\LoadingNotice.tsx`
- replace with Chakra UI Spinner

#### Typography.Paragraph, Typography.Text, & Typography.Title
- `\application\ui\display\EmptyState.tsx`
- `\application\ui\input\InlineEditInput\Editable.tsx`
- `\application\ui\layout\entityList\EntityList.tsx`
- replace with Chakra UI Textarea, Text, & Heading respectively

### steps:

- add adapters in `\infrastructure\ui\display`
- update uses listed above
- submit as separate PRs for each component

**Comment by nicolad** [comment]
`Editable` component was refactored via: https://github.com/eventespresso/event-espresso-core/pull/2697
