### ISSUE TITLE
Replace AntD Notifications with Chakra UI Toast

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2674]
#### known uses:

- `\application\services\toaster\useToastManager.tsx`

#### steps:

- add adapter in `\infrastructure\ui\display`
- update uses listed above
- ensure client code implementations function as expected

**Comment by nicolad** [comment]
After `useToastManager` is refactored, this line needs to be uncommented  https://github.com/eventespresso/event-espresso-core/pull/2682/commits/9da993317f585029230325772d0394d4246eb75d

**Comment by manzoorwanijk** [comment]
Closed via #2702
