### ISSUE TITLE
Replace AntD Icons with Appropriate Alternatives

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2677]
#### known uses:

  - TimezoneTimeInfo: GlobalOutlined
  - FieldRenderer: InfoCircleOutlined
  - LoadingIndicator: Spin, LoadingOutlined
  - RenderModalForm: SaveOutlined
  - CardViewFilterButton: AppstoreFilled
  - ToggleLegendButton : CompassFilled
  - useDateFormConfig: ProfileOutlined, CalendarOutlined, ControlOutlined
  - useTicketAssignmentsManager: SaveOutlined, ButtonProps, ModalFunc
  - useCellIcon: AntIcon, CloseOutlined, MinusOutlined
  - useTicketFormConfig: ProfileOutlined, CalendarOutlined, ControlOutlined
  - AddPriceModifierButton: PlusCircleFilled
  - useFooterRowGenerator: DownCircleFilled, UpCircleFilled

- add adapters in `\infrastructure\ui\display` and/or implement via EspressoIcon
- update uses listed above

**Comment by nicolad** [comment]
InfoCircleOutlined


![image](https://user-images.githubusercontent.com/1477453/80214698-f768e900-8643-11ea-9d45-ac197a65c300.png)
