### ISSUE TITLE
View check-in link

### ISSUE THREAD

**Issue by eboels** [eventespresso/event-espresso-core#270]
### Is this a bug report?

* [X] yes
* [ ] no

### What branch did this occur in?
Master

### What version of WordPress is on the site this issue happened?
4.9.1

### If you were directed to create an issue here by the EE support team, what is the link to your original EE support forum thread?
Slack

### Outline the steps to reproduce
In page=espresso_registrations the links "View Check-ins" send to 
```php
page=espresso_registrations&action=event_registrations&event_id=33&event_registrations_nonce=421d2e29c6
```
 and make a fatal error :

### Please include any screenshots ar screencasts that can help illustrate the issue (if possible).
```php
Fatal error: Uncaught Error: 
Call to a member function get() on null in 
/caffeinated/admin/extend/registrations/Extend_Registrations_Admin_Page.core.php:1164 

Stack trace:
#0 /core/admin/EE_Admin_Page.core.php(1032): Extend_Registrations_Admin_Page->_event_registrations_list_table() 
#1 /core/admin/EE_Admin_Page_CPT.core.php(1110): EE_Admin_Page->_route_admin_request() 
#2 /core/admin/EE_Admin_Page_Init.core.php(218): EE_Admin_Page_CPT->route_admin_request() 
#3 /wp-includes/class-wp-hook.php(286): EE_Admin_Page_Init->initialize_admin_page('') 
#4 /wp-includes/class-wp-hook.php(310): WP_Hook->apply_ 
in /caffeinated/admin/extend/registrations/Extend_Registrations_Admin_Page.core.php on line 1164
```

**Comment by eboels** [comment]
Ok, thx. Can i delete database entries ?

**Comment by nerrad** [comment]
I'm sorry but that question is a bit vague.  How does it relate to this issue?

**Comment by tn3rb** [comment]
going to close this since the problems are due to direct db manipulation (deleting records)
