### ISSUE TITLE
Entity Deletion Errors

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2703]
The Delete action in either of the Entity Action Menus (ie: delete date or delete ticket) result in the following console error, and the mutation also fails.

```
react-dom.development.js:88
Warning: Can't perform a React state update on an unmounted component.
This is a no-op, but it indicates a memory leak in your application.
To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in EditableName
    in EditableName (at Details.tsx:12)
    in Details
    in Details (at TicketCard.tsx:34)
    in div (at EntityCard/index.tsx:16)
    in div (at EntityCard/index.tsx:15)
    in div (at EntityCard/index.tsx:13)
    in div (at EntityPaperFrame/index.tsx:27)
    in div (at EntityPaperFrame/index.tsx:26)
    in div (at EntityPaperFrame/index.tsx:24)
    in EntityPaperFrame
    in EntityPaperFrame (at EntityCard/index.tsx:12)
    in EntityCard
    in EntityCard (at TicketCard.tsx:21)
    in TicketProvider (at TicketCard.tsx:20)
    in TicketCard
    in TicketCard (at EntityCardList.tsx:11)
```

**Comment by nicolad** [comment]
checked out the latest `EDTR/master` and did not reproduced the error
***
![Peek 2020-04-17 11-44](https://user-images.githubusercontent.com/1477453/79550438-fe6e8500-80a0-11ea-9c6d-e1381734e5e7.gif)

**Comment by manzoorwanijk** [comment]
It's because of [this issue](https://github.com/apollographql/react-apollo/issues/3863). Waiting for that to be fixed.

**Comment by tn3rb** [comment]
### steps to reproduce

- create new ticket

- then try to trash it

- Apollo reports an error, and the ticket does not appear to be trashed

- refresh the page, and ticket is now trashed

**Comment by manzoorwanijk** [comment]
> 
> ### steps to reproduce
> 
>     * create new ticket
> 
>     * then try to trash it
> 
>     * Apollo reports an error, and the ticket does not appear to be trashed
> 
>     * refresh the page, and ticket is now trashed

@tn3rb I don't see any error

![demo](https://user-images.githubusercontent.com/18226415/84489074-c2c9f300-acbe-11ea-85b8-a96330618b32.gif)

**Comment by tn3rb** [comment]
i can't reproduce this issue on the NK site so must have been something wonky with my local db...

going to close this but will keep an eye out for this
