### ISSUE TITLE
Load Bundled WP GQL on EE Activation and Flush Permalinks

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2711]
On a new activation of EE, we need to ensure that the bundled WP GQL plugin loads so that it's rewrite rules for the `/graphql/` can be set properly, otherwise that endpoint will be a 404

**Comment by manzoorwanijk** [comment]
I can see from WP GraphQL code that it doesn't use plugin activation hooks for rewrite rules. It uses `wp_loaded` hook. But, I think we just need to call its plugin activation and deactivation callbacks inside ee activation and deactivation callbacks.
