### ISSUE TITLE
create event tickets programmatically (using code)

### ISSUE THREAD

**Issue by kamaljeetsug** [eventespresso/event-espresso-core#272]
Hello, Its not a bug report.  I want to create the event tickets dynamically. As I am getting the ticket details from third party. But I am not able to find any way. Could you please let me know how can I create these event tickets programmatically or using code? Please let me know if there is any hooks available for them.
As I am working on a add  on for event espresso.For reference,  Please also find the attachment
Please respond to my query as soon as possible.
![check](https://user-images.githubusercontent.com/33868053/35256213-c0c1f6ac-0018-11e8-8f0c-c0c3579ca0a5.jpg)
Please respond to my query as soon as possible.
 Thanks

**Comment by mnelson4** [comment]
Yes you can create tickets in PHP using the models system. See https://github.com/eventespresso/event-espresso-core/tree/master/docs/G--Model-System. The model you want to use it EEM_Ticket to create the ticket, EEM_Price to create the different price components that make the tickets total cost, and EEM_Datetime_Ticket to associate a ticket to an event’s datetime.
If your code runs on a different server than where Event Espresso is running, you can use the REST API write endpoints. See https://github.com/eventespresso/event-espresso-core/blob/master/docs/C--REST-API/ee4-rest-api-writing-data.md. If you use the rest api, you’ll want to use the tickets, prices, datetime_tickets endpoints in the same way (the rest api is basically a facade for the models system).
Please let me know if you have any questions about those systems.
