### ISSUE TITLE
Entity lists are not sorted by date when loaded.

### ISSUE THREAD

**Issue by manzoorwanijk** [eventespresso/event-espresso-core#2749]
By default, `sortBy` is set to `date` for dates and tickets. It doesn't seem to work when the list loads for the first time. It only happens if you either change the filters or update an entity from the list.
Solution: Instead of setting the default value in `useReducer`, we should use
```js
useEffect(() => setSortBy('date'), []);
```

**Comment by nicolad** [comment]
Can't reproduce that on my end:

![Peek 2020-04-30 16-16](https://user-images.githubusercontent.com/1477453/80714803-1cef6a00-8afe-11ea-931d-f1a8edcf4257.gif)

**Comment by tn3rb** [comment]
@nicolad 

it's possible that your events are simply loading in the correct order by chance

try this:

refresh the page, without touching any of the filters, change the date of the first card in the list so that that datetime should now come after the other dates.

assuming the mutation works correctly, refresh the page again, to see if that date card is now last in the list (ie: ordered chronologically)

**Comment by nicolad** [comment]
> @nicolad
> 
> it's possible that your events are simply loading in the correct order by chance
> 
> try this:
> 
> refresh the page, without touching any of the filters, change the date of the first card in the list so that that datetime should now come after the other dates.
> 
> assuming the mutation works correctly, refresh the page again, to see if that date card is now last in the list (ie: ordered chronologically)

***
changed as requested, still working as expected:

![Peek 2020-04-30 21-00](https://user-images.githubusercontent.com/1477453/80743496-b8e09c00-8b25-11ea-9205-7d3820e63c8c.gif)

**Comment by manzoorwanijk** [comment]
The issue here is that the filters and sorters are registered on mount and thus are not available when entities are filtered for the first time. We need to solve the problem not hide the symptom. We need to make sure that when a new filter/sorter is registered, it immediately shows its effect.
