### ISSUE TITLE
Translation Bug in Access-Table from Ticket-Details

### ISSUE THREAD

**Issue by medijan** [eventespresso/event-espresso-core#277]
### Is this a bug report?

* [x] yes
* [ ] no

### What branch did this occur in?
4.9.57.p

### What version of WordPress is on the site this issue happened?
4.9.4

In the file "ticket_details.template.php" the two slugs "Total Sold" and "Total Spaces Left" have an "%s" between, so they get not translated. Lines 174 and 181

In general i would suggest creating those alignment classes dynamicaly for giving control about formatting Pricing & Tax table. Ist uncomfortable to style it in a good-looking way with css using :nth-child

cheers :)

**Comment by joshfeck** [comment]
The strings actually do get translated. For example:

https://translate.eventespresso.com/projects/event-espresso-4/pt-br/event-espresso-pt_br/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=22635&filters%5Btranslation_id%5D=106277

https://translate.eventespresso.com/projects/event-espresso-4/pt-br/event-espresso-pt_br/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=20250&filters%5Btranslation_id%5D=106620

**Comment by medijan** [comment]
not in german language. i had a mix german/english before i updated the file like written above.

**Comment by joshfeck** [comment]
While the German translation may not have those strings translated, that's not because of a bug in the software. The strings can be translated and placeholders are common practice.

**Comment by medijan** [comment]
maybe, but after my edit the german translations are correct, so the mo/po has those strings.

**Comment by joshfeck** [comment]
That's not relevant because the strings that include the placeholders are present in the translation files.

**Comment by medijan** [comment]
For me and my customer and from that point of view the consist use of "one" language on a website is most important. If some slugs get not traslated, i dig into the code and solve the problem. I just want to inform you about that issue, i solved it for me & my customer so..., if it's not a bug its a feature ;)

**Comment by joshfeck** [comment]
You didn't actually solve the problem by removing the placeholders. The correct solution is update the translation file so it has translations for the untranslated strings.

The usage of placeholders in translatable strings is not only common, but best practice.

**Comment by medijan** [comment]
Line 174: sprintf( esc_html__( 'Total%sSold', 'event_espresso' ), '<br/>' )
--> No german translation on the frontend for that slug! English Slug "Total Sold" in the span of th...

edited Line 174: sprintf( esc_html__( 'Total Sold', 'event_espresso' ), '<br/>' )
--> German translation "Teilnehmer Gesamt" as the correct translation from the translation file!!!

**Comment by joshfeck** [comment]
That's actually not the correct translation for that string though. There's actually a second string within the same template that uses that other translation. 

I went ahead and updated the two missing translations on the Event Espresso GlotPress site, which is the correct solution and the solution that anyone with account there can contribute. 

You can use download the .zip file attached here then unzip and use the .mo file or export a .mo file of the current translations at any time from here
[event-espresso-4-de_DE.zip](https://github.com/eventespresso/event-espresso-core/files/1731682/event-espresso-4-de_DE.zip)

:
[https://translate.eventespresso.com/projects/event-espresso-4/de/event-espresso-de_de/](https://translate.eventespresso.com/projects/event-espresso-4/de/event-espresso-de_de/)

This way you can avoid having to hack core every time there's an update.
