### ISSUE TITLE
Create and Load AssetManager for WP Plugins Page

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2782]
- see #2781

- add `WpPluginsAssetManager` class to `core/domain/services/assets`

- detect requests to WP Plugins page and load above class

**Comment by manzoorwanijk** [comment]
The assets will have the following deps:
- JS
```php
['react','react-dom', 'jquery', 'wp-i18n', 'wp-components', 'wp-url']
```
- CSS
```php
['wp-components']
```
