### ISSUE TITLE
EDTR Entity List UI Issues

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2783]
#### long titles and descriptions

![ScreenShot_20200506122929.png](https://images.zenhubusercontent.com/55c8c0f14f7a08fbb7f431cd/11c8f78a-01c9-4b7b-94b9-37bb60dc23e6)

As you can see from the above image, really long entity names mess up the card layout.

In EDTR v1 the following things were done:

- names under 25 characters in length had a "short-title" css class added to the heading tag that increased the font-size and line-height

- names over 25 characters but under 50 characters in length had a "long-title" css class added to the heading tag that decreased the font-size and line-height

- names over 50 characters in length were truncated so that they do not span more than 2 (or 3?) lines of text and an ellipsis was added. It would be fantastic if this logic could be added into a configurable component that could simply wrap text elements to provide this functionality.

- we don't want to change the font-size and line-height for entity descriptions, but we do want to truncate those entries so that the content is truncated and an ellipsis is appended. Again, would be ideal if a component could be created for doing this and then used for both the datetime and ticket, names and descriptions. This should be done in a separate PR.

---

#### entity status label

in the image above you can also see that the status label in the bottom of the sidebar is way too small so let's add the following to what's there already:

```css
  font-size: var(--ee-font-size-default);
  font-weight: bolder;
  letter-spacing: 1px;
  text-transform: uppercase;
```

should look something like:

![ScreenShot_20200506154312](https://user-images.githubusercontent.com/1751030/81235644-50c00900-8fb0-11ea-8279-31736697395d.png)

---

#### timezone info

![ScreenShot_20200506125114.png](https://images.zenhubusercontent.com/55c8c0f14f7a08fbb7f431cd/1499bad4-2ce8-4863-bedf-3f6f3eb6aa53)

- currently the timezone info icon button is placed between the year and time (see image for long titles and descriptions). Let's move it after the time so that it does not break the continuity of the date time display (see image for the entity status label).

- the `box-shadow` for the timezone info modal is barely noticable and appears flat but also above the cards which have a more pronounced box-shadow, which looks weird. Let's change the timezone info modal to use `box-shadow: var(--ee-box-shadow-big);`. As well, the blue box-shadow that is applied when the modal is focused either needs to be removed, or changed to be a border.

---

#### pagination

![ScreenShot_20200506125336.png](https://images.zenhubusercontent.com/55c8c0f14f7a08fbb7f431cd/c7ac1275-56f6-4413-a0b4-a4c66527ef5f)

- %cough%cough%fugly%cough%cough%

- add `padding: var(--ee-padding-huge) var(--ee-padding-default)` to `.ee-entity-pagination`

- convert to a "button group" **kinda** like this: https://bootstrapshuffle.com/classes/button-groups/btn-group but following the same kind of style as our other buttons:

![ScreenShot_20200506144612.png](https://images.zenhubusercontent.com/55c8c0f14f7a08fbb7f431cd/0f7e8075-b82f-489c-9961-201d84fbe8ba)

which is basically using a mix of the following applied to what's there already:

```css
  background: var(--ee-background-color);
  border: 2px solid var(--ee-color-grey-10);
  border-radius: var(--ee-border-radius-default);
  height: 3rem;
  width: 3rem;
```

but it gets tricky when you want to apply hover effects

---

#### ticket price

- picture is worth a thousand words:

![ScreenShot_20200506151927.png](https://images.zenhubusercontent.com/55c8c0f14f7a08fbb7f431cd/c797bf16-12e3-40db-b709-9d2851b7ea3e)

---

#### item counts

item counts for relations look fine when the number is positive:

![ScreenShot_20200506152221.png](https://images.zenhubusercontent.com/55c8c0f14f7a08fbb7f431cd/8ac1c35d-4f53-44a0-94be-81131ef2162a)

but is off center when the value is zero:

![ScreenShot_20200506152243.png](https://images.zenhubusercontent.com/55c8c0f14f7a08fbb7f431cd/925fd82c-07a7-40bc-a9ee-9ed4f045450a)

- but instead of displaying `0`, let's use `!` with a bold font (but make sure it is centered)

**Comment by nicolad** [comment]
after changing sidebar label, noticed in the next comment that timezone needs to be below:

![Peek 2020-05-12 17-54](https://user-images.githubusercontent.com/1477453/81708585-00e2b580-947a-11ea-9294-cd72f8d678be.gif)
