### ISSUE TITLE
Adding custom code

### ISSUE THREAD

**Issue by Stefanos-Stefanidis** [eventespresso/event-espresso-core#281]
* [ ] no

Hi i have added some code to display my latest attendee
I have placed the code inside /core/admin/templates/admin_wrapper.template.php
it works fine but i want to know if there is a hook/action to add my code to this specific page
(code contains php to select from a table)

Thanks in advance

![latestreg](https://user-images.githubusercontent.com/16971672/36972249-1ec0d66e-2077-11e8-9488-e0d434920f1f.png)

**Comment by nerrad** [comment]
All our actions are prefixed by `AHEE__` and all our filters are prefixed by `FHEE__`.  Your code editor should have a search function that allows you to find actions/filters in the code and you can use those prefixes to limit your search to EE related actions/filters.

I'm puzzled though, you said you placed your custom code directly in the `/core/admin/templates/admin_wrapper.template.php` file.  I'm guessing you missed the actions _that are there **in** the file_?  See [here](https://github.com/eventespresso/event-espresso-core/blob/master/core/admin/templates/admin_wrapper.template.php#L10)
