### ISSUE TITLE
Ticket Editor && Forms Improvements

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2819]
### Ticket Editor 

- remove Price and Taxable inputs from Edit Ticket form

- add TPC as second step to both Add New Ticket and Edit Ticket forms

- split inputs in the "Details" section of the Edit Ticket form into two columns

- fix price input to not accept regular text (change to number input ?)

---

### Date Editor 

- split inputs in the "Details" section of the Edit Date form into two columns

---

### Ticket Price Calculator

- toggle `is_taxable` field on tickets when tax price modifiers are added or all removed

- format prices to 3 decimal places **for display only**

---

### Ticket Assignments Manager

- add an "All Dates/Tickets" option to the "dates by month" filter (ie: turn off month filtering)

---

### All Forms 

- add cancel confirmation to modal if any form step is dirty

- add an additional margin between form rows of `var(--ee-margin-default)`

- move "Show Debug Info" button to very bottom of form below absolutely everything else (if possible, if not, then place into same row as other buttons (if possible))

- align other buttons (save, next, prev, etc) to right side of editor

--- 

plz split the above into separate PRs

**Comment by manzoorwanijk** [comment]
Adding multi-step to Edit Ticket forms is going to be tricky and needs discussion. The reason is that Edit modals currently render one instance for all edit forms. But, multi-step form modal needs full control, thus cannot use the existing form modal. We either need to create a generic modal stack that can be used everywhere and it will support state preservation between modals.

**Comment by manzoorwanijk** [comment]
> format prices to 3 decimal places for display only

Does that mean we should save all the decimal places?

**Comment by manzoorwanijk** [comment]
If we move Debug Info out, then it has to be rendered on every form/modal we create which again is a problem. IMHO, Since Debug Info is only for dev environment, it shouldn't be a concern.

**Comment by tn3rb** [comment]
> Does that mean we should save all the decimal places? Because currently we save the value upto the decimal places set in site currency config, which is 2 decimal places for US (as an example).

yes especially for reverse calculation to work properly, we need to save prices at a higher decimal resolution
then truncate the decimal places on display

> If we move Debug Info out, then it has to be rendered on every form/modal we create which again is a problem. IMHO, Since Debug Info is only for dev environment, it shouldn't be a concern.

sure that's fine
