### ISSUE TITLE
Can't Enable Sorting from Table View

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2820]
- open an event with two or more dates

- click on "table view" button in filter bar

- click on "sorting" button in filter bar

- change the order of dates in the table, should work fine

- click on "card view" button in filter bar

- now click on "table view" button in filter bar again

- then click on "sorting" button in filter bar again, but this time sorting does not work

**Comment by manzoorwanijk** [comment]
It works perfectly for me 👇 

![demo](https://user-images.githubusercontent.com/18226415/81915579-69ec3980-95f0-11ea-9435-1ab4b4c15451.gif)

**Comment by nicolad** [comment]
![Peek 2020-05-14 22-30](https://user-images.githubusercontent.com/1477453/81977370-988b0400-9632-11ea-92b7-f6bfacdf84a5.gif)

**Comment by nicolad** [comment]
Perfectly here as well:

![Peek 2020-05-14 22-55](https://user-images.githubusercontent.com/1477453/81979745-24525f80-9636-11ea-9f65-b8fb087d99c8.gif)

**Comment by tn3rb** [comment]
Also have this related issue:

![ScreenShot_20200514125613](https://user-images.githubusercontent.com/1751030/81979975-ac0e7e80-95e2-11ea-932c-38fbfda58e82.png)

- open an event with more than 6 dates or tickets

- click on "sorting" button in filter bar

- click on "card view" button in filter bar

- voila! more than 6 entities appear in list

**Comment by manzoorwanijk** [comment]
Fixed via [this](https://github.com/eventespresso/event-espresso-core/commit/f0fb0c2cbf289e9f281b5a5134a5372c4051f242)
