### ISSUE TITLE
Convert NotWithPostTypeCheck to AGQL

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2821]
- see: `/assets/ZZZ/editor-hocs/not-with-post-type-check`

- examine usage in `/assets/ZZZ/blocks/event-attendees/edit.js`

- figure out purpose for component's existence

if useful, convert to use Apollo + GQL

**Comment by manzoorwanijk** [comment]
That's useful only in Gutenberg context, we can't really use it in AGQL. The reason being that it relies upon GB data store to get current post type detail. Getting the current post type outside GB is tricky.
If we ever need it, we will see how to deal with it.
