### ISSUE TITLE
Add Dynamic Entry Point Routing

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2825]
- currently webpack uses a hardcoded entry point in `config/webpack.config.js`

- this is fine atm because we are currently only using React for the event editor

- eventually we will begin to convert other admin pages (as well as frontend elements) to use React + AGQL

- before this happens we will need to know how we are going to handle routing

- ideally, we will: 

     - dynamically route all requests through a single webpack entry to the appropriate UI

     - lazy load components accordingly

     - dynamically fetch data that has been preloaded into the DOM (likely nothing any more special that what we are doing already is needed here, but some logic could potentially be abstracted and shared better)

**Comment by nicolad** [comment]
indeed, we will able to take advantage of federated modules when CRA will update to webpack 5, otherwise we will have to spend too much time of configuration:

https://github.com/facebook/create-react-app/pull/7929
***
looking for alternatives
