### ISSUE TITLE
QUESTION: How can I assign a ticket number sequentially in increments of one (1) every time a registrant is approved

### ISSUE THREAD

**Issue by raffyphl** [eventespresso/event-espresso-core#284]
This is not a bug report. It is a question.

I am using  Event Espresso - 4.9.58.p Running on Wordpress Version 4.9.4

I was directed here by Tony. The link to my original EE support forum thread is [https://eventespresso.com/topic/assign-an-attendee-number-sequentially-for-different-tickets/](https://eventespresso.com/topic/assign-an-attendee-number-sequentially-for-different-tickets/) 

I am aware that a registration code is assigned every time someone tries to submit registration data.

How do I get EE4 to assign a sequential ticket number (increments of one) every time a registration is approved? 

e.g.

### **Transactions**

**TXN 1**
Ticket A x 2
    REG_CODE 1-1-1-a1b2 Ticket A Number (unassigned)
    REG_CODE 1-1-2-d3e4 Ticket A Number (unassigned)
Ticket B x 1
    REG_CODE 1-2-1-f5g6  Ticket B Number (unassigned)
 
**TXN 2**
Ticket A x 1
    REG_CODE 2-1-1-h7i8  Ticket A Number (unassigned)     

**Payment TXN 2** 
    REG_CODE 2-1-1-h7i8  Ticket A Number (1)     

**Payment TXN 1**
    REG_CODE 1-1-1-a1b2 Ticket A Number (2)
    REG_CODE 1-1-2-d3e4 Ticket A Number (3)
    REG_CODE 1-2-1-f5g6  Ticket B Number (1)

**TXN 3**
Ticket B x 3
   REG_CODE 3-2-1-j9k0  Ticket B Number (unassigned)
   REG_CODE 3-2-2-l1m2  Ticket B Number (unassigned)
   REG_CODE 3-2-3-n3o4  Ticket B Number (unassigned)

**Partial Payment TXN 3**
   REG_CODE 3-2-1-j9k0  Ticket B Number (2)

**TXN 4**
Ticket A x 1
    REG_CODE 4-1-1-p5q6 Ticket A Number (unassigned)
Ticket B x 1
    REG_CODE 4-2-1-r7s8  Ticket B Number (unassigned)

**Payment TXN 4**
    REG_CODE 4-1-1-p5q6 Ticket A Number (4)
    REG_CODE 4-2-1-r7s8  Ticket B Number (3)

**Payment Balance TXN 3**
   REG_CODE 3-2-2-l1m2  Ticket B Number (4)
   REG_CODE 3-2-3-n3o4  Ticket B Number (5)

### **Grouped and Sorted Registration Report**

**Ticket A**
    REG_CODE 2-1-1-h7i8  Ticket A Number (1)     
    REG_CODE 1-1-1-a1b2 Ticket A Number (2)
    REG_CODE 1-1-2-d3e4 Ticket A Number (3)
    REG_CODE 4-1-1-p5q6 Ticket A Number (4)

**Ticket B**
    REG_CODE 1-2-1-f5g6  Ticket B Number (1)
    REG_CODE 3-2-1-j9k0  Ticket B Number (2)
    REG_CODE 4-2-1-r7s8  Ticket B Number (3)
    REG_CODE 3-2-2-l1m2  Ticket B Number (4)
    REG_CODE 3-2-3-n3o4  Ticket B Number (5)

**Comment by tn3rb** [comment]
The following hook is triggered every time a registration has it's status changed to Approved:

```php
do_action('AHEE__EE_Registration__set_status__to_approved', $this, $old_STS_ID, $new_STS_ID, $context);
```

so you could easily hook into that using something like:

---php
add_action(
    'AHEE__EE_Registration__set_status__to_approved', 
    function(EE_Registration $registration, $old_STS_ID, $new_STS_ID, $context) {
        // do something with the registration
    }
);
```

I'll leave the details of how to generate the sequential ticket number up to you, but it's probably as easy as saving the next highest ticket number in a wp option, using that for the the next Approved registration, then incrementing that value and resaving the option.

Now that said, I'm not sure where you want to actually **set** the sequential ticket number, meaning where to save that data, or what you plan on doing with it.

If you wanted to replace the registration's existing Reg Code, then you could use:

---php
$registration->set_reg_code( $sequential_ticket_number );
```

or if you wanted to keep the existing Reg Code and save the sequential ticket number somewhere else, then you might want to look at our extra meta methods, which allow you to attach any data of any type to any of our model objects. So something like:


---php
$registration->add_extra_meta( 'sequential_ticket_number', $sequential_ticket_number );
```

would work. Other extra meta methods include:

---php
update_extra_meta();
delete_extra_meta();
get_extra_meta();
```

which can be found in the `EE_Base_Class` class which can be found in  `core/db_classes/EE_Base_Class.class.php` around line 2785

Hope that helps.

**Comment by raffyphl** [comment]
Thank you for the reply.

I want to keep the reg code. I want to assign the sequential number to the a registration like an additional registration_code of sorts which is unique to a registrant except this would be unique to an approved registrant.

I forgot to advise you that I am not a programmer but I will try to understand what you said and give it a shot. That said any additional tips on what I should read up on might(?) help.

Again. Thank you for the reply.

**Comment by nerrad** [comment]
If you're not a programmer then you will unlikely be able to accomplish what you want as it will require some custom development.  The tips etc we give in our github repository are generally more technical in nature.  You may want to consider hiring a developer to do the necessary custom development to accomplish your needs :)

You could also make a feature request for something along the lines you've requested in the EE support forums and it might get added to the [Public Roadmap](https://trello.com/b/zg9DCIpe/event-espresso-public-roadmap) for consideration in a future release of EE.

I'm going to close this ticket, but if you decide to give a go at doing your own development (I don't want to discourage you from that, we all start somewhere in learning :) ) and you have more questions about where to find something you can ask here and we'll try to help, but be aware that we generally help by just pointing to where to go and some generalities in our code examples.  We won't be writing the code for you.

**Comment by nerrad** [comment]
> That said any additional tips on what I should read up on might(?) help.

If you are not familiar with WordePress hooks in general, it'd be good to read up on how WordPress hooks work (googling it should turn up some articles for you).  We expose a lot of Event Espresso functionality for customization via the WordPress hook system.  Most code editors with good search capabilities will help you find hooks throughout our code base by searching for `do_action` or `apply_filters`.

Some additional reading you may want to do is our [developer oriented documentation](https://github.com/eventespresso/event-espresso-core/tree/master/docs).  In particular learning how to use our [model system](https://github.com/eventespresso/event-espresso-core/blob/master/docs/G--Model-System) will be useful.  Of course, depending on how much you understand, you may need to level up your skills in programming within php itself.  We extensively use OOP (object-oriented-programming) throughout EE so some familiarity with that will be necessary to work effectively with any customizations for EE.

I also want to caution you against making any changes directly in the plugin code.   Create your own WordPress plugin that hooks into doing what you want (again lot's of tutorials available via googling for that).

**Comment by raffyphl** [comment]
Thank you for the replies, tn3rb and nerrad.

I'll give it a go.
