### ISSUE TITLE
Entity Action Main Menu Dropdown Issues

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2847]
![ScreenShot_20200518142407.png](https://images.zenhubusercontent.com/55c8c0f14f7a08fbb7f431cd/24cd77c5-00f2-4138-90c1-daf8d3f337ad)

- dropdown position seems to be odd and not location aware (ie: will appear off screen instead of repositioning in order to be visible)

- dropdown will ONLY close if you click the menu button a second time

**Comment by nicolad** [comment]
positioning depends on `popper.js`, let's see if updating to v2 in chakra will fix this issue;
asked [here](https://github.com/chakra-ui/chakra-ui/issues/469#issuecomment-630858126) a more exact time of when upgrade will happen
