### ISSUE TITLE
Custom booking field using wp_dropdown_pages and WP_Query

### ISSUE THREAD

**Issue by emeraldjava** [eventespresso/event-espresso-core#285]
### Is this a bug report?

* [ ] yes
* [X ] no

I'm wondering is there a hook point which would allow me to define a custom booking field, where the details are populated using the wp_dropdown_pages() and custom WP_Query. 

In my scenario, I need a person booking a ticket to select which company they work for. The list of companies is managed within wordpress as a custom post type.

```
$args = array (
				'id' => $field['fieldid'],
				'name' => $field['fieldid'],
				'echo' => 1,
				'post_type' => 'company',
wp_dropdown_pages($args);
```

Any help would be appreciated.
Regards,
Paul

**Comment by tn3rb** [comment]
So just to clarify, you want to add a select input (dropdown) to your registration form that is populated with the names of companies which are custom post types? So when someone is registering for an event, they have to select the Company they work for from the list?

**Comment by tn3rb** [comment]
This idea seemed like it might be useful for others (and I wanted to ensure what I was going to suggest would work) so I created a code snippet.

Plz see: 
https://github.com/eventespresso/ee-code-snippet-library/blob/master/checkout/bc_custom_post_type_input.php

**Comment by tn3rb** [comment]
closing due to no response in past 30 days

**Comment by emeraldjava** [comment]
Hi,

Sorry for the delay in replying to this issue. I got the basic drop down working using this code

https://github.com/emeraldjava/bhaa_ee_plugin/blob/master/src/CompanyPostTypeInput.php

The final blocking issue is for an existing WP_User where we know their company, how I ensure the dropdown is pre-selected. Is it possible to pass the ID or value of the company to be selected as part of the $input_settings?

**Comment by mnelson4** [comment]
hey @emeraldjava, yes you can pass the form input's initial value in `$input_settings['default']`, see https://github.com/eventespresso/event-espresso-core/blob/master/docs/J--EE4-Forms-System/ee-forms-system-overview.md#ee_form_input_base (I just noticed that wasn't properly documented, so I added it)
