### ISSUE TITLE
Ticket Price Calculator Enhancements

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2863]
####  Add Default Taxes 

- in order to reduce the following:

     - time it takes users to configure prices for a ticket

     - errors caused by constantly re-entering price modifiers

     - duplicated records in the db

- we need to add a button just below the last row of the ticket price calculator labeled: :add default taxes"

- then load all of the default prices from the price table where `isDefault` and `isTax` are true ie: `PRC_is_default` === 1 && price type base type === 4

- set `isTaxable` to true on ticket

- we also do not want to clone default taxes and also NOT add relations in the ticket price table

- we also need to automagically load default taxes for tickets that already have `isTaxable` set to true

#### Free Tickets

- if a user doesn't require a price for a ticket, they should be able to skip the TPC step in the Edit/New Ticket Form Modal

- change existing button at bottom of Ticket Details step to read instead of "add ticket prices" 

- add a new button after it labeled "free ticket - assign dates" that skips the TPC and goes directly to TAM

#### But WAIT, There's MORE

- do NOT save prices to the db if their amount is 0

**Comment by manzoorwanijk** [comment]
> - we also do not want to clone default taxes NOT add relations in the ticket price table

this is a bit confusing for me 😕

**Comment by tn3rb** [comment]
oops.. ya sry for that grammar mistake in that one sentence, updated it to:

> we also do not want to clone default taxes and also NOT add relations in the ticket price table

and ya, you figured it out, taxes operate globally, and have always been applied at run time to tickets and therefore do NOT have a relation recorded for each ticket.
