### ISSUE TITLE
ConfirmDelete popup shakes the UI

### ISSUE THREAD

**Issue by manzoorwanijk** [eventespresso/event-espresso-core#2867]
`ConfirmDelete` shakes the UI left-right because the popup hides scrollbars

Here is the demo
![demo](https://user-images.githubusercontent.com/18226415/82704101-77f62600-9c92-11ea-818d-903e0b610bf9.gif)

**Comment by nicolad** [comment]
note to myself:
```
overflow-y:overlay
```

**Comment by manzoorwanijk** [comment]
May be also fix the header title spacing for multi-line text.
![image](https://user-images.githubusercontent.com/18226415/82707103-08d00000-9c99-11ea-8763-81a99d4c249b.png)
