### ISSUE TITLE
Changing site language is throwing an error in TimezoneTimeInfo

### ISSUE THREAD

**Issue by nicolad** [eventespresso/event-espresso-core#2873]
![image](https://user-images.githubusercontent.com/1477453/82946080-6a98ae80-9fa6-11ea-874b-76cddbe484fd.png)

**Comment by nicolad** [comment]
Language was changed here:

![image](https://user-images.githubusercontent.com/1477453/82946280-bcd9cf80-9fa6-11ea-825c-c2465a0d6d7b.png)

**Comment by nicolad** [comment]
the second time I've changed back and forth it had worked:

![image](https://user-images.githubusercontent.com/1477453/82946469-13dfa480-9fa7-11ea-9f3f-d9627ff0fec1.png)

**Comment by manzoorwanijk** [comment]
I am unable to reproduce it. I changed the language to Spanish and reloaded EDTR, all went fine.

**Comment by manzoorwanijk** [comment]
> I tried with Spanish, Arabic, German, Russian, French but found no error. May be this was some temporary glitch. We will keep watching this.
<sub>[View in Slack](https://eventespresso.slack.com/archives/C080DDVLM/p1590663250084000)</sub>
