### ISSUE TITLE
Review EDTR for Mobile, i18n, RTL,  and a11y issues

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2903]
need to test EDTR and look for issues pertaining to:

### i18n

- priority 1

- ensuring all public facing strings are translatable (try PigLatin plugin)

- ensure RTL languages are not impeded by UI

### a11y

- priority 2
- ensure EDTR is navigable via keyboard

- employ a11y tools to test for issues:

    - https://www.softwaretestinghelp.com/accessibility-testing-tools/

    - https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh

    - https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd

### Mobile/Responsiveness

- priority 3

- ensure EDTR is navigable via touch

PLZ document all issues discovered here so that we can discuss solutions and make actionable items

**Comment by nicolad** [comment]
great idea with prioritization :+1:

**Comment by manzoorwanijk** [comment]
Translations not working for blocks. GB needs special loading of translation files. More info [here](https://developer.wordpress.org/block-editor/developers/internationalization/#load-translation-file).

**Comment by manzoorwanijk** [comment]
> <@U03T6AM1N> <@UPHV02MC1> Re. a11y, I disconnected my mouse from my computer to check keyboard a11y of EDTR. I checked almost every component and it worked perfectly :heart_eyes:
<sub>[View in Slack](https://eventespresso.slack.com/archives/C080DDVLM/p1591021253291800)</sub>

**Comment by manzoorwanijk** [comment]
## Mobile/Responsiveness
I tested on my OnePlus 6 (Android 10) with `chrome://inspect` to make sure there are no console errors. Here are some style issues I found:

**Comment by manzoorwanijk** [comment]
#### 1. Needs a fix I guess
![image](https://user-images.githubusercontent.com/18226415/83419208-5808f400-a442-11ea-974d-2d117035882f.png)

**Comment by manzoorwanijk** [comment]
#### 2. Some misplacement?
![image](https://user-images.githubusercontent.com/18226415/83419437-b03ff600-a442-11ea-95fd-6b710a85ba45.png)

**Comment by manzoorwanijk** [comment]
#### 3. TPC button seems to be angry with the rest
![image](https://user-images.githubusercontent.com/18226415/83419664-0f056f80-a443-11ea-9d0c-6ebff30bec46.png)

**Comment by manzoorwanijk** [comment]
#### 4. Our multi-step is quite nice, except these buttons, may be give them full width?
![image](https://user-images.githubusercontent.com/18226415/83419909-79b6ab00-a443-11ea-8edb-02fd99b308d5.png)

**Comment by manzoorwanijk** [comment]
#### 5. You may collect and join those pieces
![image](https://user-images.githubusercontent.com/18226415/83420040-a2d73b80-a443-11ea-832b-db6a49ab16e9.png)

**Comment by manzoorwanijk** [comment]
#### 6. Unusable TAM
![image](https://user-images.githubusercontent.com/18226415/83420113-c7cbae80-a443-11ea-8b8b-33d854a07503.png)


![image](https://user-images.githubusercontent.com/18226415/83420143-d31eda00-a443-11ea-8470-d5371854a9ac.png)

**Comment by manzoorwanijk** [comment]
Regarding RTL, I only found the issues that I have already mentioned in #2885. More issues may be clear once we have a dummy RTL translation ready to test.

**Comment by nicolad** [comment]
For responsive testing, we also might take advantage of browserstack free plan for OS https://www.browserstack.com/open-source
