### ISSUE TITLE
Post Editor Assets Not Loading for EDTR

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2931]
**Steps To Reproduce**

- log into the admin and go to the EE Events admin

- click on the **Default Settings** tab

- change the  **Activate Advanced Editor** options to **Legacy Editor** if not on that already

- save page and then open an Event to edit from the Events Overview tab

- then either:

     - enter text into the main WYSIWYG editor

     - scroll to the bottom of the sidebar and click the **Set Featured Image** link

- results:

     - text does not appear in the WYSIWYG editor (in visual mode)

     - modal window for adding Featured Images does not appear

**Comment by nicolad** [comment]
Upon pressing **Set featured image** this errors appears:
![image](https://user-images.githubusercontent.com/1477453/85848306-9aa7bd00-b7b1-11ea-9801-8e91de1bead6.png)

***
I searched and there might be a conflict between different lodash versions

**Comment by nicolad** [comment]
Also noticed that in `EDTR/refactor-master` the featured image modal is opening.

**Comment by tn3rb** [comment]
ok I _think_ i might have a grasp on what's going on here...

that `TypeError: _.contains is not a function` error in `media-models.js` is not a conflict between different lodash versions but a conflict between `lodash` and `underscore`. The `lodash.contains()` function was dropped in version 4 but remains in `underscore`, and as far as I can tell from looking at the code in `media-models.js`, it's using `underscore`.

I too thought this was a `lodash` issue because if you run `console.log(_.VERSION)` in your browser it returns `4.17.15` which is the latest version.

So this is what I've tried in order to fix this:

- finding the commit where this issue started (painfully slow process with no conclusion)

- removed ALL THINGS `lodash` that I had added when I initially thought the issue was a lack of `lodash`. 
This includes:

    - the bundled `lodash` scripts in `/assets/vender/`

    - enqueuing logic in `CoreAssetManager`

    - externals reference in webpack

- de-registering `lodash` and enqueueing `underscore`

- verifying that `underscore` is loaded before `media-models.js`

**Comment by nicolad** [comment]
> So at this point, the only thing I can think is that it is getting added by a dependency of one of our dependencies, but I have no idea how to deal with that.

I've used `yarn why lodash` to check the dep tree.
As a next step might be checking each package and/ or applying some strict rule upon which needed version is used: https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

![image](https://user-images.githubusercontent.com/1477453/86451478-a6503200-bd23-11ea-87dd-9a2caa91527f.png)

**Comment by nicolad** [comment]
Lodash being used as an external module in GB:

https://github.com/WordPress/gutenberg/pull/5933

**Comment by manzoorwanijk** [comment]
All good here

![demo](https://user-images.githubusercontent.com/18226415/86464714-bc72e800-bd4d-11ea-9484-9b22523939c9.gif)

**Comment by manzoorwanijk** [comment]
The reason or the error was that many of the wp packages bundled lodash into JS leaving no trace in DOM. Lodash then overrode `window._` of `underscore.js` thus creating conflicts.
