### ISSUE TITLE
Default Date Name Blank on New Events / No Placeholder

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2932]
- when you first create an event, the default datetime that appears has no name/title

- the datetime description, despite also being blank shows a placeholder ("edit description...") which can be clicked to enable inline editing

- because the datetime name has no placeholder text, there is nothing to click, so the **only** way to enter a title is to go into the main action menu and click "edit datetime" and go through the entire step form.

we just need to add a default placeholder when there is no title

**Comment by manzoorwanijk** [comment]
The issue here is that Nullish coalescing operator (`??`) works only for `null` and `undefined` not for empty strings.

**Comment by manzoorwanijk** [comment]
There is one more issue though, what if a user wants to leave the description empty?
