### ISSUE TITLE
TPC Issues: Price Order Not Set Correctly && Taxes Applied After Deleting Prices

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2934]
### Steps to Reproduce

- use https://brent.eventespresso.com/

- create a new ticket and on the TPC form step click Add Default Prices

- set base ticket price to $10 and leave tax as is

- save, assign a date, save new ticket, and wait for mutations to complete

- click TPC icon to edit prices

- delete all prices and submit

- click TPC icon again to edit prices

- **???** default tax appears again despite having been deleted

- if you monkey around with variations of the above steps you can sometimes get the default base price to appear AFTER the default tax, but this can not be reproduced reliably and seems to happen almost randomly, but essentially, the PRC_order is not getting set. I've looked directly in the db on my testing site and most of the prices have an order of 0. You can use this tool by going to https://brent.eventespresso.com/wp-admin/tools.php?page=databasebrowser

So looks like two things need to happen

- `isTaxable` needs to be set back to `false` when ALL prices are deleted

- `PRC_order` field needs to get set upon save. This will be a bit tricky because the order of the default taxes can not be modified, so all prices and modifiers prior to taxes can simply be ordered sequentially (1,2,3...) but any that appear after taxes will need to start from the highest order of the last tax (ie, if the last tax has an order of 70, then the next modifier needs to start at 71, although it might be wise to put a bigger gap between taxes and any additional prices (like start at 80)

**Comment by manzoorwanijk** [comment]
I don't see any default taxes there.

**Comment by manzoorwanijk** [comment]
I tested it locally with different combinations, all looks fine.

**Comment by manzoorwanijk** [comment]
Today I was able to reproduce it by creating a new default tax.

**Comment by manzoorwanijk** [comment]
The bug lies both in PHP and JS 👍
