### ISSUE TITLE
EDTR UI Tweaks

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2935]
# Edit Entity Forms

### ⋆⋆⋆ required input indicator ⋆⋆⋆

there is currently nothing to indicate when an input is required, and yet the form submit button will be disabled.

![ScreenShot_20200605160203](https://user-images.githubusercontent.com/1751030/83928822-f39dab80-a745-11ea-9e7d-76fcbd2b35df.png)

typically we have appended an `*` to the input label to indicate that it is a required field, so let's do that and give it the following styles (will need to wrap asterisk in a span with a class like `ee-required-asterisk`):

```css
  color: var(--ee-color-accent);
  font-weight: 900;
  margin: var(--ee-margin-micro);
```

It is only when you focus out of an input that a validation notice appears

![ScreenShot_20200605160151](https://user-images.githubusercontent.com/1751030/83928826-fa2c2300-a745-11ea-885d-861263972e75.png)

let's also add a class to those validation error notices and give them the following styles:

```css
  color: var(--ee-color-white);
  background: var(--ee-color-accent);
  border-radius: var(--ee-border-radius-small);
  display: inline-flex;
  letter-spacing: 2px;
  padding: var(--ee-padding-tiny) var(--ee-padding-default) var(--ee-padding-tiny) var(--ee-padding-small);
```

which should look something like:

![ScreenShot_20200605161034](https://user-images.githubusercontent.com/1751030/83929117-23997e80-a747-11ea-93fb-88f69ef7def1.png)

.

### ⋆⋆⋆ button colors and icons ⋆⋆⋆

plz adjust modal form buttons as follows:

- add `ee-btn--primary` class to all submit buttons (including the TAM modal submit)

- add `ee-btn--secondary` class to the "add ticket prices" button but **ONLY** when on the first step of the edit ticket form

![ScreenShot_20200605164645](https://user-images.githubusercontent.com/1751030/83930390-3498be80-a74c-11ea-9b6a-08337822013f.png)

- add the same "save" icon that appears on the TAM form to all submit buttons

![ScreenShot_20200605164158](https://user-images.githubusercontent.com/1751030/83930271-8b51c880-a74b-11ea-90de-c933535f3703.png)

- as shown in the previous two images, add a second arrow icon to any buttons that jump two steps. They will need to have a negative margin of `-0.5rem` to the side of the icon bordering its twin in order to pull the two icons together

---

# Ticket Price Calculator

### ⋆⋆⋆ default prices notice ⋆⋆⋆

In TPC when you add default prices the following notice appears:

![ScreenShot_20200605153225](https://user-images.githubusercontent.com/1751030/83927458-d36bed80-a741-11ea-956e-f3c4acf7543f.png)

this could be made more helpful by linking to the place that users CAN modify default prices.
so let's change the text for this notice to "modify default prices" and link to  https://www.domain.com/wp-admin/admin.php?page=pricing

.

### ⋆⋆⋆ add/delete prices buttons overlap ⋆⋆⋆

![ScreenShot_20200605153650](https://user-images.githubusercontent.com/1751030/83927702-90f6e080-a742-11ea-9a28-789de025b2f2.png)

let's add a `ButtonRow` component below the TPC table and move these buttons into that

.

### ⋆⋆⋆ add a "remove taxes" button ⋆⋆⋆

after clicking the "add default taxes" button, taxes have to be removed manually by clicking the delete button for each one. This is fine, but could be expedited by changing the "add default taxes" button to say "remove taxes" once taxes have been added, and upon clicking:

 - remove ALL tax prices related to the ticket

 - delete tax prices that are NOT defaults

 - set `isTaxable` on ticket to `false`. This should also occur if taxes are deleted manually using the trash button

.

### ⋆⋆⋆ price amount input height ⋆⋆⋆

![ScreenShot_20200605155229](https://user-images.githubusercontent.com/1751030/83928434-a66d0a00-a744-11ea-9a9c-ce2880060092.png)

seems fine when adding prices manually, but if you start with a free ticket, then click the "add default prices" button, the height of the amount input is off by 2px (40px vs 42px)

..

### ⋆⋆⋆ free ticket notice ⋆⋆⋆

plz change the color for the `i` icon for the free ticket notice to `var(--ee-color-primary-super-low-contrast)`

![ScreenShot_20200605161750](https://user-images.githubusercontent.com/1751030/83929471-5132f780-a748-11ea-8ec7-802dbdea587f.png)

plz also add a bit of margin between the "add default prices" button and the text above it, maybe `var(--ee-margin-small)`

---

# Ticket Assignments Manager

### ⋆⋆⋆ show all dates by default ⋆⋆⋆

maybe it's just me, but I find I am constantly changing the `dates by month` select input to `All Dates` in order to properly assign tickets to dates. As well, I have concerns that users may not realize they need to change the value of that selector to see other date options. So let's use `All Dates` as the default option for that input. Then if a user has too many dates, they can use the filter to reduce the number of options, which I think will happen less often than having to change that input because the date you want is not showing.

---

# IMPORTANT

### plz submit all work in separate PRs (at least each item denoted by the ⋆⋆⋆ bullets)

**Comment by nicolad** [comment]
related: https://github.com/eventespresso/event-espresso-core/pull/2953
