### ISSUE TITLE
Month/Year Selector in Datepicker Closes Entire Form Modal

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2940]
### Steps to Reproduce

- open edit date or edit ticket form

- find a date input and click to open datepicker

- click on the month/year selector at the top of the datepicker:

![ScreenShot_20200608093950.png](https://images.zenhubusercontent.com/55c8c0f14f7a08fbb7f431cd/73e72f3b-578e-4ecb-a36a-1ac3ffd3fd8d)

- entire Form Modal will close and any changes that were made to other inputs are lost :(

**Comment by manzoorwanijk** [comment]
The reason for that is the popover created by datepicker which becomes an overlay to the modal. So when you click on that overlay, the modal closes. So, for now the only solution is to disable modal close on overlay click.
