### ISSUE TITLE
EE Core Plugin - New Activation

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2969]
- create a new WP site (unless you happen to have an existing WP site that has **never** had EE installed on it)

- checkout / download the `barista-prod` branch from here: https://github.com/eventespresso/event-espresso-core/tree/barista-prod

-  go to the WP Plugins page and activate the Event Espresso core plugin

- [x] confirm that no errors occur during activation (other than known issue: #2933)

- click around through the various admin menu pages

- [x] confirm that no errors occur

- return to the WP Plugins page and deactivate the Event Espresso core plugin

- [x] confirm that no errors occur

- reactivate the Event Espresso core plugin

- [x] confirm that no errors occur

- now go to the Event Espresso Events admin page

- click the `Add New Event` button at the top of the page (there shouldn't be any existing events because this is a new installation right?)

- [x] confirm that no errors occur

- [x] confirm that the NEW Advanced Editor loads, you should see something like the following under the WYSIWYG text editor:

![ScreenShot_20200617114959](https://user-images.githubusercontent.com/1751030/84937496-b2d05b80-b090-11ea-8d86-a42741420337.png)

- feel free to play around with the EDTR at this point

- **please** document any issues, questions, or comments you may have regarding any initial impressions regarding UI/UX that you feel may be an issue for users, either below,
or you can add a card in the **Feedback / Issues** column for the project for unrelated issues

### Known Issues

- https://github.com/eventespresso/event-espresso-core/issues/2933
if you experience the `Too few arguments to function Route::__construct()` Exception, you can simply refresh the page, and the plugin should be activated

**Comment by sethshoultes** [comment]
When attempting to activate this branch on a fresh/new install of WP, I am getting the following error:

( ! ) ArgumentCountError: Too few arguments to function EventEspresso\core\domain\entities\routing\handlers\Route::__construct(), 0 passed and at least 3 expected in /Users/sethshoultes/Documents/Websites/espresso-edtr.dev.cc/wp-content/plugins/event-espresso-core-EDTR-master/core/domain/entities/routing/handlers/Route.php on line 65
--

**Comment by sethshoultes** [comment]
NVM. I just noticed I had the EDTR/master branch activated, instead of EDTR/production.

**Comment by sethshoultes** [comment]
Actually, I am still getting that error but according to Brent, it's a known issue.

**Comment by sethshoultes** [comment]
Also, the new editor is not showing for the fresh install:
![image](https://user-images.githubusercontent.com/235315/86033292-f793b500-b9f5-11ea-9c1d-7bbfd2972aac.png)

It looks like it needs to be activated here:
![image](https://user-images.githubusercontent.com/235315/86033412-23169f80-b9f6-11ea-8eed-cbf5246083e9.png)

**Comment by Pebblo** [comment]
Confirmed the above, the default editor on a new install is currently legacy.

**Comment by tn3rb** [comment]
this should be corrected now if you retest with the `EDTR/production` branch

**Comment by sethshoultes** [comment]
This all works. 

Here's what I see for the new admin:
<img width="616" alt="Screen Shot 2020-11-05 at 4 35 01 PM" src="https://user-images.githubusercontent.com/235315/98308293-ed298f00-1f84-11eb-93bd-08ab610fb6e1.png">
