### ISSUE TITLE
EE Core Plugin - Upgrade Existing Install

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2970]
- on an existing WP site that has previously had EE installed on it

- go to the WP Plugins page and **deactivate** the currently active Event Espresso core plugin

- checkout / download the `barista` branch from here: https://github.com/eventespresso/event-espresso-core/tree/barista

- replace the existing ee core installation with the above

- **advanced step** : because the EDTR branch has yet to be merged into EE master branch, it's version string is behind that of master. Therefore in order to test a plugin upgrade, we need to increment the version string in both the plugin header Version as well as the `espresso_version()` function. Maybe use something like `4.11.0.p`

- activate the Event Espresso core plugin

- [x] confirm that no errors occur during activation

- test other aspects of general plugin similar to the New Activation testing notes

- now go to the Event Espresso Events admin page

- click to edit one of your existing events

- [x] confirm that no errors occur

- [x] confirm that the existing Legacy Editor loads (because the new editor should not be active yet for existing installations)

- **please** document any issues, question, or comments you may have below, or you can add a card in the **Feedback / Issues** column for the project for unrelated issues

### Known Issues

- https://github.com/eventespresso/event-espresso-core/issues/2933
if you experience the `Too few arguments to function Route::__construct()` Exception, you can simply refresh the page, and the plugin should be activated

**Comment by sethshoultes** [comment]
Testing on this ticket went well. However, I am seeing the #2933 issue upon activation.

**Comment by tn3rb** [comment]
this should be corrected now if you retest with the EDTR/production branch

**Comment by sethshoultes** [comment]
This is all good now.
