### ISSUE TITLE
Legacy Event Editor

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2971]
- by default the EDTR is not active for existing users, and will have to be turned on manually

- but first let's confirm that the existing Legacy Editor still works as expected 

- go to the Event Espresso Events admin page

- click to edit one of your existing events

- [x] confirm that no errors occur

- [x] confirm that the existing Legacy Editor loads (because the new editor should not be active yet for existing installations)

- edit some of the event's datetimes and tickets 

- [x] confirm that  everything still works as expected

- now save your changes

- [x] confirm that no errors occur and that the changes have been saved as expected

- **please** document any issues, question, or comments you may have below, or you can add a card in the **Feedback / Issues** column for the project for unrelated issues

**Comment by sethshoultes** [comment]
I noticed that the tooltips for fields and the Ticket Status Legend is missing on this branch. If you hover over the ticket Status bands, then it should show a tooltip with the Status Legend displayed. 

Here's a screenshot from current master branch:
![2020-06-29_12-18-40](https://user-images.githubusercontent.com/235315/86041474-f0bf6f00-ba02-11ea-99e9-5ce21c21bcc2.jpg)

**Comment by tn3rb** [comment]
this is fixed in the `barista-prod` branch now

**Comment by sethshoultes** [comment]
There seems to be a new issue with tooltips, as they seem to be sticking when the mouse is moved away:
<img width="465" alt="Screen Shot 2020-11-05 at 4 50 45 PM" src="https://user-images.githubusercontent.com/235315/98309274-498dae00-1f87-11eb-83c9-c2a44951461c.png">

**Comment by sethshoultes** [comment]
Closing this in favor of https://github.com/eventespresso/event-espresso-core/issues/3198
