### ISSUE TITLE
Activating the New Advanced Editor

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2972]
- go to the Event Espresso Events admin page

- click on the **Default Settings** tab at the top of the page

- [x] confirm that no errors occur and that an option titled **Activate Advanced Editor?** appears at the top of the page, which should look like:

- now select "Advanced Editor" from the dropdown input and click save

- [x] confirm that no errors occur

- now click on the **Overview** tab at the top of the page

- click to edit one of your existing events

- [x] confirm that no errors occur

- [x] confirm that the NEW Advanced Editor loads, you should see something like the following under the WYSIWYG text editor:

![ScreenShot_20200617121112](https://user-images.githubusercontent.com/1751030/84939757-ae597200-b093-11ea-9c34-7a76a0b99764.png)

- [x] confirm that the details for your dates and tickets appear to be correct and that no data has been lost and or changed in any way

- feel free to play around with the EDTR at this point

- **please** document any issues, questions, or comments you may have regarding any initial impressions regarding UI/UX that you feel may be an issue for users, either below,
or you can add a card in the **Feedback / Issues** column for the project for unrelated issues

**Comment by sethshoultes** [comment]
This is all working for me.

**Comment by garthkoyle** [comment]
This seems to be working. Can be closed.
