### ISSUE TITLE
Editing Default Datetime on New Events

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2973]
- go to the Event Espresso Events admin page

- click the `Add New Event` button at the top of the page

- [x] confirm that the NEW Advanced Editor loads, and that a default datetime has been created:

![ScreenShot_20200617121747](https://user-images.githubusercontent.com/1751030/84940351-92a29b80-b094-11ea-9ea7-8765e9006f40.png)

- try editing the datetime ( not going to tell you how :stuck_out_tongue_winking_eye: ) and change the following details:

     - datetime title

     - datetime description

     - datetime capacity

     - start and end dates and times

- [x] confirm that the date details change correctly and as expected

- experiment with any weird use case that you can think of that EE customers may try to create

- **please** document any issues, question, or comments you may have below, or you can add a card in the **Feedback / Issues** column for the project for unrelated issues

**Comment by sethshoultes** [comment]
Seems to be working

**Comment by garthkoyle** [comment]
closing out
