### ISSUE TITLE
Editing Default Ticket on New Events

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2974]
- if you haven't already created a new event, then:

     - go to the Event Espresso Events admin page

     - click the Add New Event button at the top of the page

- [x] confirm that the NEW Advanced Editor loads, and that a default datetime has been created:

- the default ticket may NOT appear for you initially (issue discovered while creating this testing note) so if this is not fixed by the time you are reading this, then plz do the following:

     - scroll down to the **Available Tickets** entity list

     - click on the **show filters** button

     - in the **status** dropdown, select "**all tickets for above dates**" (first option)

- [x] confirm that the default new ticket appears, which might look something like:

![ScreenShot_20200617163246](https://user-images.githubusercontent.com/1751030/84961079-394c6380-b0b8-11ea-8e58-0f42c780f0f2.png)

- try editing the ticket ( not going to tell you how :stuck_out_tongue_winking_eye: ) and change the following details:

     - ticket title

     - ticket description

     - ticket total price - **PLEASE NOTE**: I'm purposely leaving out editing the price via the "**Ticket Price Calculator**" because its complexity warrants its own issue and testing notes, but the ticket total can be edited without having to use the calculator

     - ticket quantity

     - ticket sale start and end datetimes

- [x] confirm that the ticket details change correctly and as expected

- experiment with any weird use case that you can think of that EE customers may try to create

- **please** document any issues, question, or comments you may have below

**Comment by garthkoyle** [comment]
Works fine.
