### ISSUE TITLE
Creating a New Datetime

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2975]
- click on the **Add New Date** button at the bottom of the Event Dates entity list

- [ ] confirm that the New Datetime form modal appears

- things to try to break form:

    - advancing to second step without filling out anything on the first step (should not be allowed)

    - advancing to second step without supplying values for required inputs (validation should appear, and advancement should be blocked)

    - entering invalid data into form inputs

    - try using the form using only the keyboard

    - anything else your deviant little mind can think of to try and break the form (looking at you Garth)

- now fill out the form properly including using the date and time pickers

- click the "**Save and assign tickets**" button

- [ ] confirm that you are advanced to the Ticket Assignments step

- select a ticket to assign to the date then click the **"Submit"** button

- [ ] confirm that the New Datetime has been created as expected (may take some time depending on the speed of your testing server - watch the notifications in the bottom right corner of the screen)

**IMPORTANT - pay special attention to the dates and times you select using the date and and time pickers and make sure that they are still correct after saving has completed**

- now create some more datetimes using any typical customer use cases that you can think of (for later testing we'll want some extra datetimes)

### Additional Datetime Functionality

- go back and edit the start and end dates for one of your existing datetimes... can you figure out how to do that?

- copy an existing datetime

- trash an existing datetime

- permanently delete an existing datetime (hint: use the filters Luke)

### Beast Mode

- try to remember any weird edge case scenarios that people have tried (including any bat-$#@! crazy ones) and see if you can recreate those same setups using the EDTR.
Ultimately we are trying to find use cases that can not be satisfied and/or result in erroneous data being generated (ie: bugs).

**Comment by garthkoyle** [comment]
This seems to be working. Closing for now.
