### ISSUE TITLE
Creating a New Ticket

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2976]
- click on the Add New Ticket button at the bottom of the Available Tickets entity list

- [ ] confirm that the New Ticket form modal appears

- things to try to break form:

    - advancing to second or third step without filling out anything on the first step (should not be allowed)

    - advancing to second step without supplying values for required inputs (validation should appear, and advancement should be blocked)

    - entering invalid data into form inputs

    - try using the form using only the keyboard

    - anything else your deviant little mind can think of to try and break the form

- now fill out the form properly including using the date and time pickers and other inputs in the Details section

- **IMPORTANT** - we're going to skip the "Add ticket prices" step because the complexity of the Ticket Price Calculator warrants its own issue and testing notes

- click the "**Skip prices - assign dates**" button (if you really want to, you're welcome to click the "Add ticket prices" button and check out the Ticket Price Calculator, but let's save any discussion about it for its own issue)

- [ ] confirm that you are advanced to the Date Assignments step

- select a date(s) to assign to the ticket then click the **"Submit"** button

- [ ] confirm that the New Ticket has been created as expected (may take some time depending on the speed of your testing server - watch the notifications in the bottom right corner of the screen)

**IMPORTANT - pay special attention to the dates and times you select using the date and and time pickers and make sure that they are still correct after saving has completed**

- now create some more tickets using any typical customer use cases that you can think of (for later testing we'll want some extra tickets)

- some more advanced use cases that should be possible:

    - required tickets

    - graduated pricing - the first **x** tickets cost $$$$ each, then next **x** cost $$$, and the rest above that only cost $$ each

    - ticket bundles - tickets are $ each but you can buy 5 tickets for $$$$ (buying 6 won't get you a discount though... only when you buy 5)

    - creating a default ticket (will require you to create a new event and see if the new default ticket appears for that event - you may have to play with the ticket list filters)

**NOTE - just edit the ticket total price to set up the pricing configurations above instead of using the Ticket Price Calculator**

### Additional Ticket Functionality

- go back and edit the sale dates for one of your existing tickets... can you figure out how to do that?

- copy an existing ticket

- trash an existing ticket

- permanently delete an existing ticket (hint: use the filters Luke)

#### Beast Mode

- try to remember any weird edge case scenarios that people have tried (including any bat-$#@! crazy ones) and see if you can recreate those same setups using the EDTR.
Ultimately we are trying to find use cases that can not be satisfied and/or result in erroneous data being generated (ie: bugs).

**Comment by garthkoyle** [comment]
This seems to be working fine. Closing for now.
