### ISSUE TITLE
Ticket Price Calculator (TPC)

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2978]
- let's start with a new ticket:

    - click the "Add New Ticket" button at the bottom of the Available Tickets entity list

    - complete the Ticket Details step

    - then click the "Add ticket prices" button

you should see something like:

![ScreenShot_20200618083610](https://user-images.githubusercontent.com/1751030/85041434-c803c380-b13e-11ea-8773-77b1978d9986.png)

- click the "Add default prices" button. What prices appear next will depend on what prices you have configured on the **Event Espresso - Pricing** admin page (/wp-admin/admin.php?page=pricing). If you currently have no default prices set up, then you may want to do that now (or not and see how the Ticket Price Calculator(TPC) functions without any)

- [ ] confirm that the default prices that appear match your test site's configured default prices.

you should see something like the following (but again, with your default prices):

![ScreenShot_20200618131918](https://user-images.githubusercontent.com/1751030/85067921-550e4300-b166-11ea-82f0-58d775a9a300.png)

- **things to try**

    - setting the label, description, and amount for the Base Price

    - adding price modifiers of various types and setting details

    - deleting price modifiers

    - finding and using the "reverse calculate" feature 

    - removing taxes

    - adding default taxes (note: inputs for default taxes are disabled and cannot be edited in the Ticket Price Calculator)

    - deleting all prices

    - changing site currency to something that uses different currency sign, formatting, etc

- [ ] confirm that no errors occur and ticket price calculations are correct

- click the "Save and assign dates" button, add a relation to one or more dates, click the "Submit" button

- [ ] confirm that ticket total displayed on the ticket entity card updates correctly after mutations complete (watch system notifications)

- now directly edit the ticket total displayed on the ticket entity card (figure out how to do that yet?) and wait for mutations to complete

- click on the calculator icon in the left side of the ticket entity card to reopen the Ticket Price Calculator

- [ ] confirm that ticket total displayed at the bottom of the calculator matches what you just set on the ticket entity card

- [ ] also confirm that:

    - the "reverse calculate" button beside the ticket total is pointing up `^`

    - the ticket total input is enabled

    - the base price input is disabled

- try to remember any weird edge case scenarios that people have tried (including any bat-$#@! crazy ones) and see if you can recreate those same ticket price setups using the EDTR. Ultimately we are trying to find use cases that can not be satisfied and/or result in erroneous data being generated (ie: bugs).

**Comment by garthkoyle** [comment]
This testing went pretty well. Any issues are addressed in individual tickets. Someone can re-test this if they wish but it's looking good and we can close it if we want to for release.
