### ISSUE TITLE
New Taxes Do Not Appear in TPC

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2980]
#### steps to reproduce

- open TPC for a ticket

- add default taxes (remove any existing first and then re-add)

- click on the "Modify default prices." link and go to new tab

- add a new default tax in the EE Pricing admin and save

- return to the EDTR tab

- click "Remove taxes" then "Add default taxes"

- new tax that was just added does not appear

#### possible solutions

- detect when "Modify default prices." link is clicked and set flag indicating that default taxes need to be refreshed from the server if the  "Add default taxes" is clicked

- ???

**Comment by manzoorwanijk** [comment]
That's technically not a bug but the intended behavior right now. To make that work, we may need to wire up GQL subscriptions to get fetch the latest changes.

**Comment by tn3rb** [comment]
which would be easier:

- wire up GQL subscriptions to fetch the latest changes

- detect when "Modify default prices." link is clicked and set flag indicating that default taxes need to be refreshed from the server if the "Add default taxes" is clicked

???

or does the second solution also require the first ?

**Comment by tn3rb** [comment]
ok based on our discussion in chat, then plz look into what is involved with setting up subscriptions, and then if that looks like it will be too problematic in any way, then we'll utilize some kind of quick fix %cough% hack %cough% 

setting this as low priority
