### ISSUE TITLE
Entity List Filter Bars

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2982]
### card view | table view

- scroll to the top of the "**Event Dates**" entity list and click on the "**table view**" button

- you should see something like the following:

![ScreenShot_20200618150135](https://user-images.githubusercontent.com/1751030/85076266-a3c2d980-b174-11ea-8aa0-b289b1b29ba3.png)

- [ ] confirm that entity details and functionality are identical when compared with the same entities in the card view

---

### filters

- now click on the "**show filters**" button

- you should see something like the following:

![ScreenShot_20200618144922](https://user-images.githubusercontent.com/1751030/85075357-eaafcf80-b172-11ea-8761-725e683e80e5.png)

with the following filters:

 - status -  changes the display of datetimes based on the following statuses: upcoming, active, sold out, expired, or trashed

 - sales -  changes the display of datetimes based on the number of related tickets sold compared to the datetime capacity (reg limit)

- display - will show the datetime start date, end date, or both start and end dates

- sort by - the order the datetimes appear in the list

- search - parses the datetime titles and descriptions and returns results that match whatever is entered into the text input

The ticket entities list also has a "**link**" filter which toggles between  the following options:

 -  only tickets with relations to the datetime currently displayed in the "**Event Dates**" entity list will appear

 - all tickets for all datetimes are displayed regardless of whether they are related or not to the currently displayed Event Dates (subject to other filters)

- experiment with the various filters, but please note that you may have to perform some registrations on the frontend and/or make modifications to your dates for some filters to return results, ie: if none of your datetimes are expired, then nothing is going to show when you select that filter.

- [ ] confirm that everything functions as expected 

---

### sorting

- now click on the "**enable sorting**" button

- [ ] confirm that the entity list switches to a stripped down version of the table view

- drag n drop table rows to change the order of entities

- click the "**disable sorting**" button

- [ ] confirm that the order remains at what was set and that the "**sort by**" filter has changed to the "**custom order**" option (click on the "show filters" button to see this)

---

### legend

- now click on the "**show legend**" button

- [ ] confirm that the appropriate entity list legend appears and that all icons and entity status colors are represented

**Comment by garthkoyle** [comment]
This seems to be working well. Have not found any issues yet.
