### ISSUE TITLE
'Related {entity}: {IDs}' Tooltips from Entity Item Count Bubbles

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2990]
### issue posted by @pebblo

This confused me at first and I think we should just remove the IDs from that tooltip.

When I created an event I had 1 Datetime and 1 Ticket. The DateTime showed "Related Tickets: 2" and I was looking for the 2 related tickets, not a ticket with ID 2.

Now I know it's the IDs it makes sense but as you click on the icon to make the changes anyway I think we can avoid that with just a 'Related Tickets' / 'Related Dates' tooltip

**Comment by tn3rb** [comment]
I think those were added primarily to help us with development so we could quickly check things, but ya I agree that it would be better if those were removed.

will do

**Comment by tn3rb** [comment]
Actually, I'm thinking now that it might be best to leave the tooltips in place for the item counts, but remove the ID list and update the text to something like: 

- on datetimes (ticket icon): "related tickets"

- on tickets (calendar icon): "related datetimes"

thoughts anyone?

**Comment by sethshoultes** [comment]
Where is this located?

**Comment by nicolad** [comment]
> Where is this located?

on the right side of the card there is an assign tickets/ dates button, on hovering that button the tooltip will appear

![Screenshot from 2020-06-25 12-01-04](https://user-images.githubusercontent.com/1477453/85689787-9f01a680-b6db-11ea-8bc7-a2a51d9c2f80.png)

**Comment by nicolad** [comment]
As agreed in slack [here](https://eventespresso.slack.com/archives/C080DDVLM/p1593182370334300?thread_ts=1593182077.329500&cid=C080DDVLM), the tooltip will be renamed to `number of related tickets`
cc @tn3rb
