### ISSUE TITLE
Combine "# Sold" & "Reg List" Entity Details

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2992]
### issue posted by @garthkoyle 

Some rough thinking here...Could we combine the "# Sold" with the "Reg List" action, so if they click on the number sold they would also get the registration list? Showing the button and the quantity sold could simplify what people might expect from the button and give us a cleaner UI???https://www.screencast.com/t/fb6jGzG6oGg

Perhaps the issue is the definition of "Sold" vs. the "Reg List"?

**Comment by tn3rb** [comment]
Just to clarify things, you are suggesting to:

- remove the reg list icon button link

- make the quantity sold count text into a link that goes to the registration list (ie do what the reg list icon button link did)

I personally don't think that will make a big difference with the UI in terms of space (since those things are not currently crowded) and would actually be worse in terms of UI best practices, and here's why:

For links or actionable items that do something when you click on them, you want the UI to be one of the following things:

- an icon representation on a button - ie: a trash can to represent delete

- a text link where the text clearly states the action - ie: text that says "delete item"

- combination of the above two - ie: button with trash can icon AND "delete item" text

Your suggestion would be to remove the icon button, and make the sold count into a text link (if I'm understanding you correctly) which would mean having an actionable link with text like "123". This is not clear at all and can not benefit from adding a legend item like we have for the icon buttons, because the text will obviously change every time a ticket is sold.

So unless I am misinterpreting your suggestion I am inclined to not make that change since it breaks UI best practices

**Comment by garthkoyle** [comment]
I think you understand correctly. But IMO, seeing a number of **123 Sold** that is blue to indicate a link is obvious that it will give you a registration list of the "sold" registrations/tickets/people.

**Comment by Pebblo** [comment]
Personally I think both of those details/icons are valid and would like to throw in another option, keep both but make sold clickable.

This is what you get when combining the reg list into sold and making it a link: https://monosnap.com/file/YuB7xcylZYJm7P7NjPlxvVEpJzuWmH

So make '### sold' a link which lists only Approved registrations linked to that datetime/ticket.

Leave the reg list icon as is as it links to all registrations linked to the datetime/ticket.

I'm not a big fan of combining reg link (as it is now) into the sold section as the reg list is not a 'sold' list and our users need access to both.

If you only have the sold value and link to Approved regs then when users want to view the Reg List for Datetime X they click the sold link, it loads, they then change the 'Status filter' to 'Select status' and filter. That seems clunky to me and would prefer both a sold link and a reg list link as those are the 2 more important/used. 

> But IMO, seeing a number of 123 Sold that is blue to indicate a link is obvious that it will give you a registration list of the "sold" registrations/tickets/people.

Whilst I obviously agree that '123 Sold' should be a link as explained above, sometimes I'm struggling to notice the contrast with the links on the cards so I don't think it'll be that clear cut which is another reason I think we should keep both.

The reg list icon on its own is obviously a link, the first thing you want to do with it is click it and the legend re-enforces that so it's hard to miss IMO, the 123 sold text being a link could easily be missed but if you click it you get more info than you may have expected (which I consider a pro).

(Side note with regards to contrast, my eyesight isn't terrible but I do have glasses for computer use and when wearing those it's a little easier to spot)

**Comment by nicolad** [comment]
Usually, when upon clicking a link text it opens URL in a new tab it is enhanced with an external icon.
If we will go with combining sold with reg list we need to take this into account, but I don't like how this will look, it's bit bloated as of now:

![image](https://user-images.githubusercontent.com/1477453/86613451-4921de00-bfba-11ea-8875-8c68d724271d.png)

**Comment by tn3rb** [comment]
@Pebblo 

totally agree with your comments and think your ideas are great!

with regards to visibility, once the sold quantity numbers are converted to a link, we will add a light blue border hover effect as well as a darker blue border active effect (for tabbing via keyboard) so hopefully it won't take too long for people to discover that.

@nicolad 

ya that extra icon doesn't look great. As well, that's primarily used to indicate an **external** link that takes the user to a different website. It's arguable whether that applies here or not, as they wouldn't be visiting another site, but we are opening a new tab or window (based on browser preferences)

As I explained to Tony, we'll just make sure that the sold quantity link has the appropriate hover and active effects applied to it.
