### ISSUE TITLE
Entity Action Menu

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2993]
### issue posted by @garthkoyle 

What is the rationale for what actions/items are in the hamburger menu opposed to what is in the side menu of the card view? https://www.screencast.com/t/uLxjcGO3EEg

**Comment by tn3rb** [comment]
The general idea was to make most/all of an entity's most important details editable directly from the card view and to move all of the generic / common items into the entity action menus (main "hamberder" menu). Those menus are essentially the same for both datetimes and tickets.

As well, addons like Recurring Events Manager will have the ability to inject additional action items into the sidebar menus, like in this image:
![REM - Action Menu Icon Button](https://user-images.githubusercontent.com/1751030/85614968-62b54400-b610-11ea-8769-441e31657807.png)

Since there is limited room in those sidebar menus, I didn't want to clutter up the UI with the basic edit, copy, & trash functions so that more room could be left for add-ons to inject more customized items.

**Comment by garthkoyle** [comment]
Thanks for the explanation. I'll use that to guide me in further evaluating the EDTR.
