### ISSUE TITLE
Inline Edit Infinity Active/Hover States

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2994]
### issue posted by @garthkoyle 

Is there a way to make it more clear that the datetime capacity can be edited from the card view? Perhaps make it blue like the reg list icon that is also blue?
https://www.screencast.com/t/AleYorH6B7H

**Comment by tn3rb** [comment]
Yes the active and hover states for the other inline edit inputs were just updated in https://github.com/eventespresso/event-espresso-core/pull/2987 but those changes have not been pushed to my dev testing site (will do that today).

That said, I just double checked, and it looks like those same fixes were missed for the Datetime capacity and Ticket Quantity inputs. 

good catch 👍 thanks will fix.

**Comment by nicolad** [comment]
fixed here: https://github.com/eventespresso/event-espresso-core/pull/3002#issue-439962913
