### ISSUE TITLE
Change Inline Edit Input Default Text to Include "Click to edit..."

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2995]
### issue posted by @garthkoyle 

Can we change the "Edit title..." and "Edit description..." to "Click to edit title..." and "Click to edit description..." to make it more clear? https://www.screencast.com/t/ixDPJZ9mfBKy

**Comment by tn3rb** [comment]
will do

**Comment by sethshoultes** [comment]
It might also make sense to add tooltips with "Click to edit title..." and "Click to edit description..." to those locations as well.

**Comment by nicolad** [comment]
updated here: https://github.com/eventespresso/event-espresso-core/pull/2988/commits/4506557075f7b2149dbaa3a466f352ae2d1c8d07
