### ISSUE TITLE
Entity Card GUID

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2996]
### issue posted by @garthkoyle 

What is this number in the datetimes card `20:U6MjA=` and will it be visible when distributed? 

https://www.screencast.com/t/Jw92Vj47tOOn

**Comment by tn3rb** [comment]
Those are the entity GUIDs (Globally Unique ID)

and yes I was planning on leaving those in place to benefit us with any troubleshooting, but those could be moved to a more discrete location, (like into the Entity Action Menu dropdowns)

**Comment by sethshoultes** [comment]
I agree with moving that data to more discrete location. Maybe you add another button link that shows details about the ticket, such as the ID and GUID:
![Events ‹ North Korea Best Korea — WordPress 2020-06-24 17-35-32(1)](https://user-images.githubusercontent.com/235315/85637769-4ed60600-b641-11ea-86e8-ca7d50c38257.jpg)

**Comment by tn3rb** [comment]
I want to reserve that space in the sidebar for more important things, so we can move that info into the dropdown menu

**Comment by sethshoultes** [comment]
Sounds good.

**Comment by garthkoyle** [comment]
What about putting the GUID inside the hamberger menu?

**Comment by tn3rb** [comment]
yes that's what I meant by:

> we can move that info into the dropdown menu

I had intended the existing location to be both discrete and yet still easily accessible for the benefit of troubleshooting, but I can move it into the dropdown/hamberder menu if its current location is really that bad.

I really don't think it is going to clean up the UI in any dramatic way, by removing it from where it is, but at least if it is moved somewhere with some more screen real estate available we can add labels so that it won't be so mysterious.

**Comment by garthkoyle** [comment]
@tn3rb can you run it by your team and see what they think? cc @Pebblo

**Comment by Pebblo** [comment]
Howdy Brent, can you explain a little how these will help with troubleshooting?

The reason I ask is I'm wondering if it would be better to leave them where they are but only display them if WP_DEBUG is enabled.

Here's what I suspect would happen from some of our users (I think most would simply question what it is and then ignore it or complain about it being distracting 😞 ).

1. Uses new editor and notices the 'funky text' above the cards.
2. Posts up on the forum asking what they are and why they have them. (Gets a response explaining they are the GUID and are there to help troubleshooting)
3. Adds 'i-Break-EE-Plugin' to the site which throws 27million JS errors on our editor and the now the user can't edit the cards (if they display).
4. Posts up with something like "Hey, I can't edit my datetime `2:U6Mg==` and ticket `2:V0OjI=` can you help?"

----

What I imagine they help with is when users are editing a specific card and somehow its editing values they aren't correct for the relationships etc. So 'Ticket 1' is assigned to 'Datetime 1' but appears to be linked to Datetime 2 and whatnot, then the GUID can be used (by us) to identify things better, is that right?

**Comment by nicolad** [comment]
If we will keep that ID string, one thing to improve is how and where this is displayed. I was thinking about how plane tickets have that barcode, maybe we can also somehow combine that and the ID our case.

![image](https://user-images.githubusercontent.com/1477453/86614579-e598b000-bfbb-11ea-99bd-999d23dcf05c.png)

**Comment by tn3rb** [comment]
@Pebblo 

those strings are actually a combination of `DB ID : GUID`

so what might be best is if we simply remove the GUID portion of that but keep the DB ID. Then people won't be so distracted and/or confused by the more cryptic GUIDs

@nicolad 

in some earlier designs for the EDTR I actually had the ID displayed sideways within the cards and made to look kinda sorta like a barcode, but dropped that because it just complicated things and didn't seem to really add much in terms of improved UI. Putting the ID discreetly above the top corner of the cards seemed to work best imho. But let's remove the GUID form the string like I suggested above.
