### ISSUE TITLE
BIIIIIIIG HEADINGS

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3000]
### issue posted by @garthkoyle 

The Headings are Really BIG. Do we plan to use these styles or make something a little smaller so they don't take up so much screen real estate? https://www.screencast.com/t/E5rmNSYqW

**Comment by tn3rb** [comment]
That's a little something you may have heard of called "cool" 😉 

From the number one google result for ["UI typography design trends 2020"](https://www.google.com/search?rlz=1C1GIGM_enCA729CA729&sxsrf=ALeKk00FJ3wyYT9DxsFdiwIflnnI7_VU0g%3A1593031249498&ei=UbrzXqCCHvK_0PEPzNqYwA8&q=UI+typography+design+trends+2020&oq=UI+typography+design+trends+2020&gs_lcp=CgZwc3ktYWIQAzoHCAAQRxCwAzoHCCMQsAIQJ1DV8QRY6PIEYP71BGgAcAB4AIABUIgBpQKSAQE0mAEAoAEBqgEHZ3dzLXdpeg&sclient=psy-ab&ved=0ahUKEwjg7vftp5vqAhXyHzQIHUwtBvgQ4dUDCAw&uact=5)
![ScreenShot_20200624134439](https://user-images.githubusercontent.com/1751030/85625835-e840f000-b620-11ea-8441-a8b0e27650bf.png)

That said, those headings will only be that big on Desktop where there is lots of screen real estate to spare. There are responsive styles in place to reduce those font sizes as screen sizes get smaller:

![ScreenShot_20200624134824](https://user-images.githubusercontent.com/1751030/85626151-70bf9080-b621-11ea-9eaa-19b37ff76bc4.png)

**Comment by tn3rb** [comment]
Here's the WordPress Post Editor when you click to add a new post (using Twenty Twenty theme):

![ScreenShot_20200624135906](https://user-images.githubusercontent.com/1751030/85627171-f728a200-b622-11ea-9878-0024e6cdcba2.png)

**Comment by sethshoultes** [comment]
I also feel that the headings take up a lot of real estate in the admin.

**Comment by manzoorwanijk** [comment]
Saw this tweet today from Addy who works in Google Chrome team
https://twitter.com/addyosmani/status/1276802452352724992?s=19

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Tip: Font size isn’t always the best way to emphasize text. Try font color and font weight instead. h/t <a href="https://twitter.com/steveschoger?ref_src=twsrc%5Etfw">@steveschoger</a> <a href="https://t.co/LZG6JCJCik">pic.twitter.com/LZG6JCJCik</a></p>&mdash; Addy Osmani (@addyosmani) <a href="https://twitter.com/addyosmani/status/1276802452352724992?ref_src=twsrc%5Etfw">June 27, 2020</a></blockquote> 

![EbgA-afU4AEFYYF](https://user-images.githubusercontent.com/18226415/85932205-9e3d6000-b8e7-11ea-8787-f61218481b3e.jpeg)

**Comment by tn3rb** [comment]
@manzoorwanijk 
ya that's a good point, but it depends on context.
In the example from that post, the twitter user's name is quite arguably the most important piece of info and therefore **should** be the biggest and/or boldest text in the UI.

For our entity list headings, we want them to be totally obvious but not completely overbearing and distracting, because their only purpose is to identify those lists and are ultimately not as important as the entity names and dates. Having the text HUGE makes the headings immediately visible and super easy to see if you are scrolling up or down the page real fast (important on mobile where screen length is ridiculous), but they quickly fade into the background due to the low contrast font color and don't continue to scream at you for your attention.

So they are easy to see, but just as easy to ignore.

![ScreenShot_20200617121112](https://user-images.githubusercontent.com/1751030/86058530-ea86be00-ba15-11ea-8c16-7cf6d0ef4d91.png)

**Comment by Pebblo** [comment]
Whilst I dig the headings and get what they are trying to do, I have a couple of issues with them.

1. The large headings just don't mesh with the rest of the editor, so on opening the event editor for the first time I assumed it was a conflict with some other styles and was about to create an issue for it, then realised it was intentional.

So for me, the fact that straight away I assumed something was wrong means these are little too in your face.

2. Accessibility wise, the grey on grey is a no no, right?

As Brent mentioned, part of their charm is the low contrast means you do forget they are there fairly quickly when working with them, but that same low contrast likely makes them invisible to anyone with poor eyesight.

So personally I think, higher contrast with a smaller font size fits better here. When comparing stuff like this I like to make a change in another tab and switch between the two to view, so here's a couple of screenshots of what I compared:

https://monosnap.com/file/U8Xh4qaz2ggoNeh0XHP4PSxtANLvw8

https://monosnap.com/file/DRssHqL8XS0OhNK9nfldqpuxdxv0XN

I'm not saying that's exactly how it should look and I literally just hit the first colour I found to see, but the latter fits a little better with the rest of the editor imo.

**Comment by tn3rb** [comment]
> The large headings just don't mesh with the rest of the editor,

the rest of the editor is using styles from several several years ago which don't mesh with the current design direction of WordPress/Gutenberg either. My hope is to convert the rest of the Event Editor over to use React + Apollo/GraphQl and therefore implement a more stylish and modern design there as well. So yeah, the new design doesn't mesh with the old design, but the idea is to replace the old design with the new.

> Accessibility wise, the grey on grey is a no no, right?

font color / background contrast is dependent on font size as well, so low contrast color combinations are only acceptable for really large font sizes which is one of the reasons I went with such a large font size for those headings. For small font sizes though you absolutely have to increase the color contrast with the background in order to remain WCAG compliant. 

Increasing the font color contrast increases the "cognitive demand" of the text more so than the font size, which is why those headings are currently capable of quickly blending into the background despite being huge and immediately noticeable. So increasing the font color contrast will force more attention on those headings even if you decrease the font size. **THIS** is exactly the point that guy was trying to make in the tweet that Manzoor posted above.

I intentionally went with the current design for the following reasons:

- make the headings instantly noticeable (due to the huge font size)

- reduce the "cognitive demand" and not distract from more important info on the page (low contrast color)

- remain WCAG compliant (a11y) (by using huge font size for low contrast color text)

- make those headings easy to spot when scrolling quickly on super long mobile versions of the page

- look cool and stylish (obviously lost on you normies ;p)

So the decision to use a huge font with a low contrast color was a **very** intentional decision which IMHO is the better approach for the UI, because again, it is immediately noticeable but doesn't continue to demand your attention while still remaining WCAG compliant.

I had hoped you could all come to accept it once you got over the initial shock of such a big change, but I don't want to be responsible for your knickers being all knotted up 😝 so I'll reduce the font size and increase the color contrast in an attempt to find a happy medium, even though I now think you are all a bunch of style-challenged normies 😆 (just kidding... I've always known you are all a bunch of style-challenged normies 😆)
