### ISSUE TITLE
Change eejs.data api to use `wp_add_inline_script` instead of `wp_localize_script`

### ISSUE THREAD

**Issue by nerrad** [eventespresso/event-espresso-core#301]
## Issue Overview

Currently EE core uses `wp_localize_script` for [passing through arbitrary data from php to js](https://github.com/eventespresso/event-espresso-core/blob/master/docs/AA--Javascript-in-EE/eejs-data-api.md).  While this works okay, one potential problem with it is WP doesn't pass through data-types accurately in some cases.  For instance, `true` becomes `1`.   This is a [known issue in WordPress](https://core.trac.wordpress.org/ticket/25280) and one that I only recently become aware of.  I think I probably encountered it at some point but just worked around it thinking it just a quirk.

It'd be much more reliable if data-types were preserved in sending through and it turns out it _can_ if we use the more robust option for passing through arbitrary data via `wp_add_inline_script`.

A con with this approach however is that we'd need to bump our minimum required WP version to `4.5.0` as `wp_add_inline_script` was introduced in that version of WordPress.

**Time Estimate**:  The bulk of the time involved with this will simply be switching from using `wp_localize_script` to enqueue up the data to `wp_add_inline_script`.  So my estimate (see 5 for 5 hours) is based on that plus some padding for testing etc.

**Priority**:  This is not critical.  However as we shift to doing more of our javascript in the new build process it will be more and more important that data-types are preserved between php and js so we can reduce the amount of necessary logic js side.  Switching will also allow for future iterations where we can pass along more complex json objects (or even javascript function calls!) too that are trickier to do reliably via `wp_localize_script` alone.

## Bug report or feature request?

* [ ] Bug
* [x] Feature
* [ ] Neither

## Feedback requested

Before getting started on this I'd like feedback from :

- @tn3rb regarding any additional comments/concerns he may have making this switch.
- @joshfeck regarding the necessity to bump to WP 4.5 as a requirement.  I know he's voiced before that he doesn't mind us bumping requirements for WordPress as long as its not based on some arbitrary pattern and its for things we actually need from that version.  This issue falls into that category but I think it'd be good to verify with him as a representative of the support team on this.

**Comment by joshfeck** [comment]
Requiring WP 4.5 is fine by me.

**Comment by tn3rb** [comment]
sry are you just changing this for the new code you have added recently or are you going through the entire codebase and updating all occurrences of  `wp_localize_script` ?

**Comment by nerrad** [comment]
Heavens no, I'm not going to go through our codebase and change all occurrences of `wp_localize_script` :).  As mentioned in the original post, I'm simply looking to use `wp_add_inline_script` for the `eejs.data` api instead of `wp_localize_script`.  I envision we'll be using the `eejs.data` more and more in our new js builds which will over time replace the usage of `wp_localize_script` everywhere else.

**Comment by tn3rb** [comment]
all fine with me
