### ISSUE TITLE
Editing a 'free' ticket price from the card, does not save the price on the ticket

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3016]
Add a ticket, skip pricing and select a datetime.

You'll end up with a ticket like this:
https://monosnap.com/file/0Ijre7py6TrEbkE5ezfXm0sCfDGRB1

Now edit the price from the card:
https://monosnap.com/file/tK8np6jmy07Xk6kaIRrvk3XbuR6A0w

The front end shows a free ticket:
https://monosnap.com/file/yWxOGfKhjFRezqbjxCm9Sb98nbNGH3

Open the TPC and it shows no pricing, ticket is free:
https://monosnap.com/file/FaCpovpcqssUieCkV8YJplweQI53eI

Click to add default pricing and it 'correctly' calculates the price from the bottom up:
https://monosnap.com/file/0luYFJtQdCuPSqUn6ZbPmjxfIQNGwl

Ticket price on the front end how shows pretax:
https://monosnap.com/file/Su7rdiyGOCTkoAXgqaZkdbpikYg5ss

**Comment by manzoorwanijk** [comment]
I have seen that issue before. It's something related to cached priced for front-end.
