### ISSUE TITLE
DOM data not loaded for blocks

### ISSUE THREAD

**Issue by manzoorwanijk** [eventespresso/event-espresso-core#3027]
After #2788 there is no DOM data rendered for blocks

**Comment by tn3rb** [comment]
Can you elaborate on this issue plz?

I've visited the GB Editor in `EDTR/master` and the Event Attendees block appears to work fine.

Is there specific block data that you noticed missing?
What were you expecting to see that you are not seeing now?

**Comment by manzoorwanijk** [comment]
Try to check `eventEspressoData` in console. It works because GQL endpoint falls back to `/graphql` in JS code.
