### ISSUE TITLE
Ticket price change not reflected on front-end

### ISSUE THREAD

**Issue by manzoorwanijk** [eventespresso/event-espresso-core#3034]
With #3016 and #3017 being fixed, the ticket price change is not reflected on front-end even though the values in DB are updated.

Steps:
- Create a ticket with some price or update the price inline after creating it.
- Now open the event on front-end

Ticket price is `0`.

- Now check the database

Ticket price is as expected.

It is some caching issue I guess.

**Comment by tn3rb** [comment]
The ticket total is getting updated in the db but not the related base price. 

Here's some screenies of my db data after changing a free ticket's total to $5 via inline edit:

- ticket card after changing price from $0 to $5

![ScreenShot_20200708082046](https://user-images.githubusercontent.com/1751030/86937423-15e36a00-c0f4-11ea-8cea-3d3e591433ca.png)

- TPC showing base price 89 as well as ticket total both with amount of $5 (so Apollo cache is correct)

![ScreenShot_20200708082109](https://user-images.githubusercontent.com/1751030/86937517-31e70b80-c0f4-11ea-98bb-c417a7e2bc94.png)

- ticket total price on front end

![ScreenShot_20200708082122](https://user-images.githubusercontent.com/1751030/86937562-3f9c9100-c0f4-11ea-8f53-6f0019a405a5.png)

- ticket total in db

![ScreenShot_20200708081835](https://user-images.githubusercontent.com/1751030/86937617-50e59d80-c0f4-11ea-89e3-6055616fef58.png)

- ticket price intersection table showing only one relation for ticket 70

![ScreenShot_20200708081619](https://user-images.githubusercontent.com/1751030/86937710-6f4b9900-c0f4-11ea-9f59-07c4cdb768a0.png)

- price 89 in the db showing amount of 0

![ScreenShot_20200708081720](https://user-images.githubusercontent.com/1751030/86937767-7e324b80-c0f4-11ea-8935-8706881ee263.png)


So looks like the base price in the Apollo cache just isn't getting persisted to the db
