### ISSUE TITLE
Remove date picker icon from Datetime/Ticket mini date/time editor

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3043]
The datepicker icon here: 
![datepicker icon](https://user-images.githubusercontent.com/1751030/88300717-a905cd80-ccb8-11ea-9a47-3952600fbf92.png)

Doesn't really do much when you click the fields and the dateicker automatically pops up anyway, can we remove that?

**Comment by tn3rb** [comment]
maybe !?!?! 

that's added by the library not us, so I'll have to find a way to do so.
worse case scenario is we hide it with CSS

**Comment by tn3rb** [comment]
@nicolad 

I think we simply need to pass null for the calendar icon to hide that button (but not 100% certain)
Can you plz try that and if it does not work, try to find the best way to hide that button? thnx
