### ISSUE TITLE
Mini date/time editor loads offscreen on mobile.

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3044]
First question, what is this thing really called? :)

I'm using chrome to emulate a Pixel 2 or SGS5 and the mini editor loads off the page:

![datepicker modal offscreen on mobile](https://user-images.githubusercontent.com/1751030/88305407-5202f700-ccbe-11ea-8aca-af71fc573b7a.png)

**Comment by tn3rb** [comment]
@nicolad 

Can you please add some responsive rules for this popover and maybe make it fit the screen?

feel free to apply some kind of position sensing intelligence logic to the popover, as I just positioned it absolutely (ie: not intelligently)
