### ISSUE TITLE
Get Registrant Email 

### ISSUE THREAD

**Issue by Khadreal** [eventespresso/event-espresso-core#307]
I am trying to use the offsite skeleton module but I couldn't get the registrar email to process the payment, is there a way to get this

**Comment by tn3rb** [comment]
I'm assuming you are referring to `\tests\mocks\addons\new-payment-method\payment_methods\New_Payment_Method_Offsite\EEG_New_Payment_Method_Offsite.gateway.php` when you say "offsite skeleton module" but can you please elaborate on what you mean by:

> "I couldn't get the registrar email to process the payment"

**Comment by Khadreal** [comment]
Thanks.
Yes, am referring to` \tests\mocks\addons\new-payment-method\payment_methods\New_Payment_Method_Offsite\EEG_New_Payment_Method_Offsite.gateway.php`, I need to append the registrant email address to the payment payload data.
The payment plugin requires email address

**Comment by tn3rb** [comment]
The answer depends totally on the payment provider you are trying to connect to.
What does their documentation say?
We can't help you connect to a service when we don't even know what that service is! 
The payment provider very likely has example code that you can look at which will help you in building your integration with Event Espresso.

I'm sorry to say that that is also beyond the scope of the support that we offer here as we **only** offer support for **our** code.
We'll be more than happy to help you with issues pertaining to our code but we can't help you when those issues pertain to some other party's code.

**Comment by Khadreal** [comment]
Thank you @mnelson4. 
This works fine
