### ISSUE TITLE
Datepicker Changes BOTH Dates!

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3086]
### steps to reproduce

- click on the datepicker icon in the sidebar for a datetime or ticket

- click on the start date and choose a new value from the calendar

the end date will change to the same value

- now click on the end date and select a new value from the calendar

now the start date will change to the same value

**Comment by manzoorwanijk** [comment]
I don't think that's an issue. I think you selected the same start and end date.

Since, it's a date **range**, you need need to select the start and then end date.

Here is the demo
![demo](https://user-images.githubusercontent.com/18226415/90506599-2dd9ef00-e172-11ea-9d6a-b06dc4bbbacf.gif)

**Comment by tn3rb** [comment]
sigh... here we go again!

switching to [react-datepicker](https://reactdatepicker.com/)

- clone repo
- make a separate package
- refactor as necessary
- restyle using BEM + SASS

**Comment by tn3rb** [comment]
closing because datepickers have been replaced and there is zero chance of this issue happening again since the datepickers only operate on single dates now
