### ISSUE TITLE
Change Default Values for Start and End Dates for New Datetimes

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3089]
Currently the EDTR is using "one month from now" and "two months from now" for the default start and end dates when creating a new datetime. This is not what the existing Event Editor uses, nor are month long dates what most customers use.

We need to change the defaults to the following:

- Start date: One month from now @ 8am

- End date: One month from now @5pm

so the End date will be the same day as the Start date

**Comment by manzoorwanijk** [comment]
It means that the time will have to be set after converting the date from UTC to site time.
