### ISSUE TITLE
Can't Select Shortcode Text in Events Categories List Table

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3101]
### steps to reproduce

- got to the EE Events admin page and click on the **Categories** tab

- add an event category if one does not already exist, does not need anything more than a name

- using your mouse, attempt to select the text for the shortcode (click and drag)

- notice that the text in the table header is selectable but text in the table body is not

Here is an image showing this working in the EE core master branch:

![image (1)](https://user-images.githubusercontent.com/1751030/91196588-2f923e00-e6af-11ea-86cc-96c363eb3133.png)

**Comment by tn3rb** [comment]
from chat:

Manzoor Wani
It's in `core/admin/assets/espresso_ajax_table_sorting.js`

![image (2)](https://user-images.githubusercontent.com/1751030/91201497-5ce1ea80-e6b5-11ea-9d3a-5d18413ca8fc.png)

**Comment by tn3rb** [comment]
# FIXED

**Comment by tn3rb** [comment]
fix has been pushed to the NK site for confirmation

**Comment by tn3rb** [comment]
this is fixed in the `barista-prod` branch now

**Comment by garthkoyle** [comment]
Confirmed fixed. Can this be closed?

**Comment by tn3rb** [comment]
thnx Garth
