### ISSUE TITLE
SPCO Copy Attendee Information Not Working

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3102]
#### steps to reproduce

- verify you have an event that requires registration questions for both the primary and additional registrants

- register for that even and select at least two tickets

- on the reg form, fill in information for attendee # 1 then click on the "Use Attendee # 1's information for ALL attendees" checkbox

- the information should be copied from attendee # 1 to all others but is not

- the following error appears in the console and may be a potential cause of interference:

```
Uncaught TypeError: Cannot read property 'registerBlockType' of undefined
    at Module.<anonymous> (index.tsx:9)
    at r (bootstrap:19)
    at Object.<anonymous> (eventespresso-blocks.03493fdb.js?ver=4.10.7.rc.038:2)
    at r (bootstrap:19)
    at bootstrap:83
    at eventespresso-blocks.03493fdb.js?ver=4.10.7.rc.038:2
```

**Comment by tn3rb** [comment]
fix has been pushed to the NK site for confirmation

**Comment by tn3rb** [comment]
this is fixed in the `barista-prod` branch now

**Comment by garthkoyle** [comment]
Can SPCO Copy Attendee Information Not Working be tested on brent.eventespresso.com?

**Comment by garthkoyle** [comment]
oh, yes, it can. See comment above.

**Comment by garthkoyle** [comment]
confirmed fixed on NK site. Can this be closed?

**Comment by tn3rb** [comment]
thnx Garth
