### ISSUE TITLE
Manage Default Tickets

### ISSUE THREAD

**Issue by garthkoyle** [eventespresso/event-espresso-core#3105]
hen someone clicks the button (Master) or activates the toggle (EDTR) to create a default ticket, there is no way to disable creating a default ticket with future events without trying to track down the original ticket that had that option selected. That can be really hard to find if you’ve got lots of events (REM issue). I wish the default tickets would show up in the Pricing area somewhere.

![image](https://user-images.githubusercontent.com/3094547/91363740-7f116080-e7ba-11ea-8bfb-6bdef355bbbe.png)

**Comment by tn3rb** [comment]
closing because this functionality has been added. Currently only available with the Barista plugin active.

![ScreenShot_20210701102051](https://user-images.githubusercontent.com/1751030/124164887-11773600-da56-11eb-9657-fe666dcaf5fc.png)
