### ISSUE TITLE
jQuery.fn.unload() is deprecated

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3115]
`unload()` is currently deprecated and will be removed in jQuery 3.0

To reproduce install Jquery Migrate Helper:

https://wordpress.org/plugins/enable-jquery-migrate-helper/

Load the EE event admin:

> Query Migrate Helper — Warnings encountered
> This page generated the following warnings:
> 
> /event-espresso-core-reg/core/admin/assets/ee-admin-page.js: jQuery.fn.unload() is deprecated
> Please make sure you are using the latest version of all of your plugins, and your theme. If you are, you may want to ask the developers of the code mentioned in the warnings for an update.

**Comment by hoseinrafiei** [comment]
@tn3rb

It seems `unload()` function is removed from EE and replaced with the new method to call `on('unload')`.
Since I cannot find any issue to fix then I'm closing this issue.
