### ISSUE TITLE
Handle i18n strings deployed from barista

### ISSUE THREAD

**Issue by manzoorwanijk** [eventespresso/event-espresso-core#3122]
Barista deploys JS assets along with translations to `languages/event_espresso-translations-js.php` file. We now need to wire up these translation files with the build system in this repo.

**Comment by tn3rb** [comment]
@manzoorwanijk 

can you elaborate on your initial post plz?
This repo no longer has any kind of asset build process so unsure what you mean exactly...
did you mean that we need to have the new JS translations from Barista included in the PO and MO files?
If so, that is done on the `buildmachine` server as part of the release process but we should verify that the `/languages/` folder is not excluded when parsing the plugin for translatable strings.

**Comment by manzoorwanijk** [comment]
I guess this is already covered by build machine. Nothing extra needs to be done now. I wasn't sure before how i18n stuff is handled.
