### ISSUE TITLE
Accessing EE_Cart::instance() seems to clear the cart.

### ISSUE THREAD

**Issue by JacobDB** [eventespresso/event-espresso-core#3123]
I have the following filter:

```
function mytheme_ee_clear_cart_of_invalid_events() {
    $cart = EE_Cart::instance();
}
add_action("wp", "mytheme_ee_clear_cart_of_invalid_events");
```

While eventually this will be a more robust filter, currently all it's doing is accessing the cart. This is for some reason causing the cart to clear immediately when I go to the "Registration" step. I get a message:

"It appears your browser is not currently set to accept Cookies

In order to register for events, you need to enable cookies.
If you require assistance, then click the following link to learn how to enable cookies"

What am I doing wrong here? Literally all I'm doing is loading the cart object, so I don't understand what's happening.

**Comment by JacobDB** [comment]
Think I figured this out by searching through your source code... this seems to do the trick instead.

`$cart = EE_Session::instance()->cart();`

It seems like there's very, very little concrete documentation, everything in your "developer portal" seems either woefully incomplete, or so vague that it's unhelpful (i.e. the "Model" documentation helps to understand how things are structured generally, but not how to interact with each type of model).

**Comment by tn3rb** [comment]
The contents of the cart have nothing to do with your browser's ability to access cookies.
Have you verified that cookies are indeed turned on and that they are not getting reset when the page reloads?

The only cookie that EE depends upon is the PHP Session cookie, and even then, all we utilize is the Session ID.
You can view it's value by opening your browser's dev tools, clicking on the Network tab, then clicking on the main request (should be the first item in the list) and then clicking on the Cookies tab in the request info that opens up to the left. ex:

![ScreenShot_20200915100304](https://user-images.githubusercontent.com/1751030/93242024-08bda980-f73b-11ea-8321-f6d13e06ec8f.png)

Copy the `PHPSESSID` value to your clipboard, then refresh the page, then compare the value from the previous request. If it changes, then you first need to figure out why your session and/or cookies are being reset.

Going back to your action callback...

have you tried seeing if the cart has any contents?

you can try var dumping the results of `EE_Cart::instance()->get_grand_total()`

**Comment by tn3rb** [comment]
bah... should have refreshed before I submitted my commit... didn't see your response

**Comment by tn3rb** [comment]
but yes, getting the cart (as well as the current transaction) from the session is a much better approach since that is ultimately where everything is stored during the registration process

**Comment by tn3rb** [comment]
I've verified on my local testing site that simply calling `EE_Cart::instance()` during the `wp` action hook does not reset the cart.

If you continue to have troubles, you should first look into that issue with your cookies. As well, how were you attempting to access the registration process? All you wrote above was:

> when I go to the "Registration" step

Did you start a registration by selecting tickets and then clicking the "Proceed to Registration" button?
Or did you just try appending `/registration-checkout/` to your site's URL (which won't work but should have given a different error message)?

**Comment by JacobDB** [comment]
I've got it working now, it wasn't anything to do with cookies which is part of why I was so confused. It was literally just calling that class breaking things, disabling it allowed me to register correctly. I just added a ticket to my cart, clicked "Proceed to registration," got dumped in to the broken registration page. But it's fine now, so all good.
