### ISSUE TITLE
Add GQL Mutators for Event & Venue Entities

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3157]
We currently only have the following:

- `EventEspresso\core\domain\services\graphql\mutators\EventUpdate` 
- `EventEspresso\core\domain\services\graphql\mutators\VenueUpdate` 

available for performing mutations on  events and venues, but in order to expand the functionality of the Event Editor we will require the :

- `EventEspresso\core\domain\services\graphql\mutators\EventCreate`
- `EventEspresso\core\domain\services\graphql\mutators\EventDelete`
- `EventEspresso\core\domain\services\graphql\mutators\VenueCreate`
- `EventEspresso\core\domain\services\graphql\mutators\VenueDelete`

please split subsequent work into at least 2 PRs.

**Comment by manzoorwanijk** [comment]
Event and Venue are CPTs, so WP GQL automatically provides all the three mutations for CPTs out of the box. All we need to do it to update the EE specific fields upon creation and updation. This is exactly what that `EventEspresso\core\domain\services\graphql\mutators\EventUpdate` does.

**Comment by tn3rb** [comment]
Well the Event and Venue CPTs are hybrids between the WP CPTs and EE's model system. So when you create a new Event, a record is created in both the `wp_posts` table AND the `wp_esp_event_meta` table. Similarly, creating a new Venue creates a record in the `wp_posts` table and the `wp_esp_venue_meta` table.

Bottom line is that we are going to need custom creation and deletion mutators for those entities to handle those extra tables

**Comment by manzoorwanijk** [comment]
Yes, that's exactly what #3158 does.
