### ISSUE TITLE
Datetime Description Truncated

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3165]
From Garth:

> The datetime description cuts off when multiple rows of text: https://www.screencast.com/t/pTf4gFgPGSWn
> 
> I'm not sure if we want it to wrap or just truncate, but let's decide. I'd lean toward wrapping the text to a new row and showing more information.

**Comment by tn3rb** [comment]
ya I guess we have no option but to wrap the text.

**Comment by tn3rb** [comment]
this can be tested now

**Comment by garthkoyle** [comment]
This is what I see on Barista. No wrapping:
![image](https://user-images.githubusercontent.com/3094547/97905841-efc78280-1cff-11eb-88cb-d6063e94e73c.png)

**Comment by tn3rb** [comment]
???

not seeing that at all:

![ScreenShot_20201105143628](https://user-images.githubusercontent.com/1751030/98304191-57860380-1f74-11eb-8293-5de81ef8fbeb.png)


are you testing on https://barista.eventespresso.com/events/g-event-%e2%9d%b6-%f0%9f%8f%84%f0%9f%8f%bc%e2%80%8d%e2%99%82%ef%b8%8f/

**Comment by garthkoyle** [comment]
It's looking better now. I think there was some browser caching or something.
