### ISSUE TITLE
Datetime and Ticket Description Text Alignment

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3166]
From Garth:

> The Datetime and Ticket description text in the event editor is aligned to the center so that rows that wrap are aligned to the center. But on the front-end of the text is aligned left. Can we make that consistent, or does it matter? I'd tend to think people will think the text will be aligned center if it's shown that way in the editor. Should we align it left by default?  https://www.screencast.com/t/aZO4gOsboY and https://www.screencast.com/t/pTf4gFgPGSWn

**Comment by tn3rb** [comment]
> But on the front-end of the text is aligned left.

with whatever theme you currently happen to be using, but there is no guarantee this will always be the case.

> Can we make that consistent, or does it matter? 

It would be impossible to determine the alignment used in the theme and apply that in the EDTR. I personally don't think it matters.

> I'd tend to think people will think the text will be aligned center if it's shown that way in the editor.

really? why?

I could agree with that if we were giving them alignment control in the rich text editor, but... why would people think that one particular property would get carried over to the frontend. Why not any of the other design elements in the admin, like the coloured sidebars with the date? 

You just wanna go full on WYSIWYG don't you? 😆

I'm just ribbing you 😉 

> Should we align it left by default?

ya we could and it would look something like this:

![ScreenShot_20201020151512](https://user-images.githubusercontent.com/1751030/96656005-c7995600-12f3-11eb-9806-efb55fcbcfc7.png)

which is easy enough to implement if you like. 

**But again**... if you use a theme that centers text, then the admin will NOT reflect that. So we can left align those elements in the admin, but then they will always be left aligned.

thoughts?

**Comment by garthkoyle** [comment]
I tested a few default WP themes and they are aligned left. ¯\_(ツ)_/¯

**Comment by tn3rb** [comment]
> I tested a few default WP themes and they are aligned left

I don't doubt that and I wasn't trying to imply that that wasn't the most likely default. All I want to convey is the fact that the editor alignment will NOT adopt whatever alignment the theme uses. So if a user DOES happen to employ a theme that uses center alignment, the editor will not reflect that. The editor will remain using whatever alignment we set it to.

So we can hard code the alignment for the entity title and description to be left justified, which is a better default if we want to try and emulate what most themes use, but that alignment will be hard coded and will not change. I had chosen center alignment simply because it looks better (more balanced) when there are short titles and descriptions and doesn't look bad when they are longer. With left justification, the cards look really unbalanced when the titles and descriptions are short, but that's not a big deal.

**Comment by garthkoyle** [comment]
Right, I follow you. I do like the balance of the centered text in the admin. If you want to keep it centered as a design decision then I'm fine with that for now. If we do get reports of people being confused by this then we can address it later. Thanks for discussing.

**Comment by tn3rb** [comment]
just for thoroughness, here's what a ticket with a short name and description could look like with the text all left aligned:

![ScreenShot_20201021130201](https://user-images.githubusercontent.com/1751030/96776429-e0f6dc80-139d-11eb-85b1-158d3f9c47bb.png)


versus what it looks like currently:

![ScreenShot_20201021131134](https://user-images.githubusercontent.com/1751030/96777286-00dad000-139f-11eb-9095-0aa64a58c21f.png)

which imho looks off balance which is why I went with the text centered.
Again, it's not a huge issue, and my reasoning was simply for the design.

**Comment by garthkoyle** [comment]
go with centering for the design.

**Comment by nicolad** [comment]
sorry for chiming in :) 
I do agree with center-alignment, took a quick look over some other card UIs and it seems that for our specific case and ticket orientation left alignment would create inconsistency with sidebar text and with other elements;
***
left-alignment looks ok on vertically oriented ticket UI since you can span text at full width

![image](https://user-images.githubusercontent.com/1477453/96778766-ca2fa480-13f4-11eb-85e1-44f1bf066b06.png)
***
also left-alignment seems ok for less complex ticket UIs (not our case :sweat_smile:  )

![image](https://user-images.githubusercontent.com/1477453/96779224-0bc04f80-13f5-11eb-806d-da2d4da73d67.png)


![image](https://user-images.githubusercontent.com/1477453/96781138-a325a280-13f5-11eb-9704-a31492f5c138.png)
