### ISSUE TITLE
Cannot select today as a ticket sale date.

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3168]
I tried to create a new ticket to go on sale today, but I can't select today as the sale START date. https://www.screencast.com/t/b8Ww9YMt

Perhaps I've got the timezones mixed up, but the question remains...how do I set a ticket to go on sale at this moment so I can test?

plz see: https://github.com/eventespresso/barista/issues/364

**Comment by garthkoyle** [comment]
Fixed.
