### ISSUE TITLE
Block Ticket Price Bulk Edit for Tickets with Registrations

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3169]
i was able to BULK EDIT a ticket price after registrations were approved.

You'll notice that on this event, the first ticket is called "Free Ticket". I have two attendees that registered and were approved, then, I BULK EDITED the tickets together and changed the prices to a non-zero dollar amount. Now the free ticket is no longer free. In master, we prohibited people from changing the price of tickets once a registration had been complete as to not confuse the accounting of registrations and transactions: https://barista.eventespresso.com/wp-admin/admin.php?page=espresso_events&action=edit&post=40

see: https://github.com/eventespresso/barista/issues/363

**Comment by tn3rb** [comment]
this is ready for testing now Garth

**Comment by garthkoyle** [comment]
Seems to be working, 👍
