### ISSUE TITLE
Setting Datetimes

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3170]
From Garth:

> Unable to Add a Datetime Later than one month from today. When I created a new event today, I was not able to create a datetime that started after Nov 19 (a month from now). Am I missing something? https://www.screencast.com/t/ymiaSBnj9

**Comment by tn3rb** [comment]
You're trying to set the start date after the end date.

If you create a new datetime via the "Add New Datetime" button, then the two fields will allow you to leapfrog the dates.

What we would need to do for the date range picker is disable the internal date validation and then display an error inside the modal if the two dates are not chronologically sequential as well as disable the save button.

**Comment by garthkoyle** [comment]
I'm not sure I completely follow you, but this is how I use it.

The start date and time is the first field to edit when changing the dates.. In this example, I can't move the Start Date to be after Nov 19 unless I first move the end date back. That is difficult and not how I do that in master. With master, I can set the Start Date to anything in the future and core automatically adjusts the End Date to be after the Start date. See: https://www.screencast.com/t/omtsA6nLrvGH

If you're saying the same thing in a different way then we're good.

**Comment by tn3rb** [comment]
> If you're saying the same thing in a different way then we're good.

I am. 

What's happening is that the datepicker component uses internal validation that blocks you from putting the dates out of chronological order. So the start date can NOT go after the end date and vice versa. So we will have to remove the internal validation and add that externally, so that the save button is disabled and an error message is displayed if you set the dates out of order. That will at least allow you to initially set the start date after the end date, but you won't be able to save until you also move the end date so that it is once again after the start date.

**Comment by garthkoyle** [comment]
Fixed.
