### ISSUE TITLE
WP Post Content Editor Tabs Missing

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3172]
From Garth:

> The Visual/Text tab is missing on barista.eventespresso.com. I looked on Master and it's looking normal. https://www.screencast.com/t/RFnNBiewl41

**Comment by tn3rb** [comment]
Not seeing that issue locally nor on Barista. Here's what I see on that same event:

![ScreenShot_20201020170958](https://user-images.githubusercontent.com/1751030/96657528-46dc5900-12f7-11eb-8699-a1bf70bea8a3.png)

what browser are you using?

and... 

![have you tried turning it off and then on again](https://user-images.githubusercontent.com/1751030/96657549-5491de80-12f7-11eb-922f-aba466832716.jpg)

**Comment by garthkoyle** [comment]
Firefox.

**Comment by garthkoyle** [comment]
I updated again, this time to 82.0, still the same issue.

**Comment by tn3rb** [comment]
kk thnx will check it out

**Comment by tn3rb** [comment]
installed FireFox and still not seeing that issue:

![ScreenShot_20201021113851](https://user-images.githubusercontent.com/1751030/96767989-1ac1e600-1392-11eb-934e-7febaec7d220.png)

I'm assuming you were also on a Mac?

I can go and try on my wife's computer later (son is in school zoom atm)

**Comment by garthkoyle** [comment]
This is also an issue for me with Chrome (on OSX).

**Comment by tn3rb** [comment]
well that was a wild ride 😆
