### ISSUE TITLE
Payments admin page is blank

### ISSUE THREAD

**Issue by stargate03** [eventespresso/event-espresso-core#3185]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - Version of Event Espresso:  
 - Version of WordPress: 
 - Browser 
 - PHP Version 

**Additional context**

When i go to the payments option page in EE admin, its blank

**Comment by garthkoyle** [comment]
Can you provide more detail on what versions of software you are using? Which plugins do you have installed?
