### ISSUE TITLE
Legacy Editor: Tooltips are sticking when the mouse has moved away

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#3198]
Reported here: https://github.com/eventespresso/event-espresso-core/issues/2971#issuecomment-722711257

In the Barista branch, the Tooltips are sticking when the mouse has moved away. If you want to type in a field, you have to wait about 20 seconds for the tooltip to go away and they seem to be stacking:
<img width="465" alt="Screen Shot 2020-11-05 at 4 50 45 PM" src="https://user-images.githubusercontent.com/235315/98309424-9ec9bf80-1f87-11eb-9725-4c238d1e00fc.png">

**Comment by tn3rb** [comment]
This same issue happens on master branch so is likely something to do with qTips in general OR recent changes to jQuery, but is not because of the EDTR

![ScreenShot_20201210124315](https://user-images.githubusercontent.com/1751030/101828664-b5af8480-3ae6-11eb-9040-8ba73a821e86.png)
