### ISSUE TITLE
Add ability to hide note about status colors changing

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#3199]
Can you please add an option to hide this message?
"Click for an Important Notice regarding Status Color Codes"

<img width="745" alt="Screen Shot 2020-11-05 at 4 53 31 PM" src="https://user-images.githubusercontent.com/235315/98309695-58289500-1f88-11eb-881d-1eae67de61fe.png">

**Comment by tn3rb** [comment]
want to give this a try now Seth?

**Comment by garthkoyle** [comment]
@sethshoultes is this what you wanted? I think you wanted the option to remove the red text, no?

![image](https://user-images.githubusercontent.com/3094547/103679931-b818c900-4f42-11eb-9d46-edb3508d06c8.png)

**Comment by sethshoultes** [comment]
> @sethshoultes is this what you wanted? I think you wanted the option to remove the red text, no?

@garthkoyle (& @tn3rb) that's correct, I want the option to remove the red text. Once it's been read by a user, then I don't they should keep seeing it there.

**Comment by tn3rb** [comment]
you need to click the notice first to read it, then there is an option to dismiss it

**Comment by sethshoultes** [comment]
Right. I see the option to dismiss the message:
<img width="830" alt="Screen Shot 2021-01-11 at 8 13 47 AM" src="https://user-images.githubusercontent.com/235315/104199720-03205980-53e5-11eb-8868-a95fbb2a5e97.png">

Which works great. However, I don't want to see this text once I've read the message and dismissed it. I don't see that option here:
<img width="831" alt="Screen Shot 2021-01-11 at 8 15 37 AM" src="https://user-images.githubusercontent.com/235315/104199884-3b279c80-53e5-11eb-8457-37f4da596713.png">

**Comment by tn3rb** [comment]
> I see the option to dismiss the message:

ooo  actually... it looks like you are not...
looks like your screen is getting cut off for some reason. 
The dismiss option is a link in the bottom right corner of that message
the `x` in the top right corner simply closes the notice but does not hide it permanently 

can you plz tell me what Browser and OS you are using?

**Comment by garthkoyle** [comment]
@sethshoultes need a little more feedback here. ^

**Comment by garthkoyle** [comment]
I do not see a dismiss option in the bottom right corner with either Chrome, FF, or Safari. I set browser to really wide an didn't see anything.

Do you have a screenshot of what it's supposed to look like?

**Comment by sethshoultes** [comment]
I was using both Firefox and Chrome and didn't see a way to close the red message.

**Comment by tn3rb** [comment]
ahh man.. the Event Editor uses a different page slug than the Events List, which is why I didn't notice this issue. Fixed now in #3284

**Comment by garthkoyle** [comment]
Looks great, and works.
![image](https://user-images.githubusercontent.com/3094547/105775728-7e752580-5f24-11eb-8158-818997cc22bb.png)
