### ISSUE TITLE
GraphQl Does Not Work With Plain Permalink Structure

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3206]
### steps to reproduce

- go to `example.com/wp-admin/options-permalink.php` admin page

- set permalinks structure to `Plain` and click save

- go to `example.com/graphql` and/or attempt to use EDTR

I realize that anybody sane with at least half a brain will not be using plain permalink structures, but not everybody fits into that category unfortunately, so we need to at least investigate whether this issue can be mitigated

**Comment by manzoorwanijk** [comment]
Here is how the things should work:

Apart from other slug based checks to detect GQL requests, `isGQL()` in `EventEspresso\core\domain\services\contexts\RequestTypeContextChecker` should ideally check `isset( $_GET[ \WPGraphQL\Router::$route ] )`, but we use `isGQL` to actually load WP GQL 🤷‍♂️ 

For more information about how WP GQL detects GQL requests, you can see `is_graphql_http_request()` in `\WPGraphQL\Router`

**Comment by tn3rb** [comment]
closing because #3207 was merged
