### ISSUE TITLE
Perform PHP 8.0 Audit

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3210]
Yikes, November 26th arrived much earlier this year than it has in the past!!!

PHP 8.0 with a slew of changes was released today so we need to begin preparing for customers to begin switching over. I don't actually think that will happen any time soon because this version of PHP has a number of backwards compatibility breaking changes and I don't expect most people to be prepared any time soon, at least not with production servers. That said, PHP 8 introduces JIT (just in time) compilation which has the potential to increase performance significantly (although I doubt much for WordPRess sites) so there may be some pushing to try it out. 

[WordPress Core aims to be compatible with PHP 8.0 in the 5.6 release (currently scheduled for December 8, 2020)](https://make.wordpress.org/core/2020/11/23/wordpress-and-php-8-0/) so we likely have at least a couple of weeks before we will even see any mentions of whether we are compatible.

**Comment by joshfeck** [comment]
Critical issue reported in #3256
I'll add the deprecated notices to this one.

**Comment by joshfeck** [comment]
### Deprecated method
`PHP Deprecated:  Method ReflectionParameter::getClass() is deprecated in /wp-content/plugins/event-espresso-core/core/services/container/Mirror.php on line 161`

**Comment by joshfeck** [comment]
### Required parameter follows optional parameter

- [ ] `PHP Deprecated:  Required parameter $pan_message follows optional parameter $pan_name in /wp-content/plugins/event-espresso-core/core/EE_Error.core.php on line 1159`
- [ ] `PHP Deprecated:  Required parameter $file follows optional parameter $dismissible in /wp-content/plugins/event-espresso-core/core/services/notices/NoticesContainer.php on line 92`
- [ ] `PHP Deprecated:  Required parameter $func follows optional parameter $dismissible in /wp-content/plugins/event-espresso-core/core/services/notices/NoticesContainer.php on line 92`
- [ ] `PHP Deprecated:  Required parameter $line follows optional parameter $dismissible in /wp-content/plugins/event-espresso-core/core/services/notices/NoticesContainer.php on line 92`
- [ ] `PHP Deprecated:  Required parameter $file follows optional parameter $dismissible in /wp-content/plugins/event-espresso-core/core/services/notices/NoticesContainerInterface.php on line 45`
- [ ] `PHP Deprecated:  Required parameter $func follows optional parameter $dismissible in /wp-content/plugins/event-espresso-core/core/services/notices/NoticesContainerInterface.php on line 45`
- [ ] `PHP Deprecated:  Required parameter $line follows optional parameter $dismissible in /wp-content/plugins/event-espresso-core/core/services/notices/NoticesContainerInterface.php on line 45`
- [ ] `PHP Deprecated:  Required parameter $capabilities_checker follows optional parameter $return_url in /wp-content/plugins/event-espresso-core/core/services/notifications/PersistentAdminNoticeManager.php on line 68`
- [ ] `PHP Deprecated:  Required parameter $request follows optional parameter $return_url in /wp-content/plugins/event-espresso-core/core/services/notifications/PersistentAdminNoticeManager.php on line 68`
- [ ] `PHP Deprecated:  Required parameter $old_value follows optional parameter $option in /wp-content/plugins/event-espresso-core/core/EE_Config.core.php on line 402`
- [ ] `PHP Deprecated:  Required parameter $value follows optional parameter $option in /wp-content/plugins/event-espresso-core/core/EE_Config.core.php on line 402`
- [ ] `PHP Deprecated:  Required parameter $registration follows optional parameter $EVT_ID in /wp-content/plugins/event-espresso-core/core/db_models/EEM_Event.model.php on line 449`
- [ ] `PHP Deprecated:  Required parameter $model_field_factory follows optional parameter $timezone in /wp-content/plugins/event-espresso-core/core/db_models/EEM_Attendee.model.php on line 137`
- [ ] `PHP Deprecated:  Required parameter $model_field_factory follows optional parameter $timezone in /wp-content/plugins/event-espresso-core/core/db_models/EEM_WP_User.model.php on line 32`
- [ ] `PHP Deprecated:  Required parameter $reg_step follows optional parameter $state_options in /wp-content/plugins/event-espresso-core/modules/add_new_state/EED_Add_New_State.module.php on line 707`
- [ ] `PHP Deprecated:  Required parameter $registration follows optional parameter $state_options in /wp-content/plugins/event-espresso-core/modules/add_new_state/EED_Add_New_State.module.php on line 707`
- [ ] `PHP Deprecated:  Required parameter $question follows optional parameter $state_options in /wp-content/plugins/event-espresso-core/modules/add_new_state/EED_Add_New_State.module.php on line 707`
- [ ] `PHP Deprecated:  Required parameter $answer follows optional parameter $state_options in /wp-content/plugins/event-espresso-core/modules/add_new_state/EED_Add_New_State.module.php on line 707`
- [ ] `PHP Deprecated:  Required parameter $reg_step follows optional parameter $country_options in /wp-content/plugins/event-espresso-core/modules/add_new_state/EED_Add_New_State.module.php on line 749`
- [ ] `PHP Deprecated:  Required parameter $registration follows optional parameter $country_options in /wp-content/plugins/event-espresso-core/modules/add_new_state/EED_Add_New_State.module.php on line 749`
- [ ] `PHP Deprecated:  Required parameter $question follows optional parameter $country_options in /wp-content/plugins/event-espresso-core/modules/add_new_state/EED_Add_New_State.module.php on line 749`
- [ ] `PHP Deprecated:  Required parameter $answer follows optional parameter $country_options in /wp-content/plugins/event-espresso-core/modules/add_new_state/EED_Add_New_State.module.php on line 749`
- [ ] `PHP Deprecated:  Required parameter $transaction follows optional parameter $class in /wp-content/plugins/event-espresso-core/modules/messages/EED_Messages.module.php on line 1316`
- [ ] `PHP Deprecated:  Required parameter $ticket follows optional parameter $qty in /wp-content/plugins/event-espresso-core/modules/ticket_sales_monitor/EED_Ticket_Sales_Monitor.module.php on line 249`
- [ ] `PHP Deprecated:  Required parameter $source follows optional parameter $valid_reserved_ticket_line_items in /wp-content/plugins/event-espresso-core/modules/ticket_sales_monitor/EED_Ticket_Sales_Monitor.module.php on line 992`
- [ ] `PHP Deprecated:  Required parameter $reg_form follows optional parameter $req_data in /wp-content/plugins/event-espresso-core/caffeinated/modules/recaptcha_invisible/EED_Recaptcha_Invisible.module.php on line 248`
- [ ] `PHP Deprecated:  Required parameter $event follows optional parameter $html in /wp-content/plugins/event-espresso-core/caffeinated/modules/recaptcha_invisible/EED_Recaptcha_Invisible.module.php on line 281`
- [ ] `PHP Deprecated:  Required parameter $domain follows optional parameter $i18n_map in /wp-content/plugins/event-espresso-core/core/services/assets/I18nRegistry.php on line 63`
- [ ] `PHP Deprecated:  Required parameter $model_field_factory follows optional parameter $timezone in /wp-content/plugins/event-espresso-core/core/db_models/EEM_WP_User.model.php on line 32`
- [ ] `PHP Deprecated:  Required parameter $model_name follows optional parameter $default_value in /wp-content/plugins/event-espresso-core/core/services/orm/ModelFieldFactory.php on line 95`
- [ ] `PHP Deprecated:  Required parameter $allowed_enum_values follows optional parameter $default_value in /wp-content/plugins/event-espresso-core/core/services/orm/ModelFieldFactory.php on line 226`
