### ISSUE TITLE
Group transaction log entries for an update by TXN ID

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#3222]
While looking into a customer's site, I noticed that they have multiple transaction log entries for a single transaction on the Payment Method > Logs page:
<img width="906" alt="Screen Shot 2020-12-08 at 10 10 58 AM" src="https://user-images.githubusercontent.com/235315/101640920-59693980-39ee-11eb-813d-966fde1d1a21.png">

At first, I was confused because I thought it wasn't normal to have so many updates to the same transaction with PayPal Express. Then, Tony explained that a single payment with PayPal Express makes multiple requests and we have multiple log entries for each of those requests. 

Such as:

> 1. Payment Token Request
> 2. Payment Token Response
> 
> `#1` is sent to PayPal to initiate a checkout (before the user is sent over to PayPal) and we log the details of the request, `#2` is the response from that request (we need to log it in case there are errors during that)
> 
> The user goes to PayPal and creates a payment, our PayPal Express payment method doesn't USE IPN's but PayPal do still send them (I think this is the problem here) so when that hits the site it'll create a log entry:
> 
> 3. IPN data received (this is created by SPCO)
> 
> Then when the user returns back to the site a method runs to handle the payment update, the first thing that does is create a log entry:
> 
> 4. Return from Authorization
> 
> That holds the details sent on the request. From there EE sends a 'Customer Details' request to PayPal and gets a response, so those are both logged:
> 
> 5. Customer Details Request
> 6. Customer Details Response
> 
> Based on the response from 6 we can send another request, so again, request and response saved:
> 
> 7. Do Payment Request
> 8. Do Payment Response
> 
> All being well from all of those, we have a final log entry:
> 
> 9 Post Payment Transaction Details
> 
> So 1 and 2 create the checkout within PayPal, 3 is data logged from a request sent to PayPal and then 4-9 are all actually on a single update to the transaction its just that we have multiple requests and log them all to help to troubleshoot if needed.

Wouldn't it make sense to group these logs by transaction ID?

**Comment by Pebblo** [comment]
I posted a comment about this after the above which I thnk should also go here:

> We could, but I already know that we'll run into an issue with that as it stands as some of the payments methods don't assign any objects to the log entry (they show as unknown) so then don't get assigned to the TXN.
> Meaning we'll end up with log entries mixed between TXN's and Unknowns It already gets confusing when that happens with multiple payment requests so if we then start grouping some but can't others I think it might get worse.
> 
> I've been slowly pushing back on the entries as I find them/review code for them and have switched a fair few out to stop it, but I think grouping them should be done after those have all been properly fixed.

To give some details to this, sometimes a payment method creates a log entry with the `EE_Payment` object, sometimes they create a log with the `EE_Transaction` object and others they just pass the payment method itself (which is pretty much useless in terms of logging which is why I've been updating it as I go)

So whilst I like the idea of better logging for the above, for this to function correctly I think everywhere that creates a payment log entry would need to be reviewed and set to use the EE_Transaction object as the table has ID's for both the TXN and Payment objects and neither, all for the same transaction.
