### ISSUE TITLE
Hide Extra Details Table Rows for Hidden Tickets

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3228]
Using his incredibly impressive power to break things, Garth has discovered that creating 92 event dates using the new REM editor will result in a big solid bar appearing at the bottom of the ticket selector table on the frontend. 

The reason is because the bottom border for the "extra details" rows are still appearing for ticket rows that are hidden due to the date selector only showing a limited number of dates. We just never noticed before because the bar would normally have only been a few extra pixels.

**Comment by tn3rb** [comment]
This is implemented on the Barista test site now Garth

**Comment by garthkoyle** [comment]
looks better here: https://barista.eventespresso.com/?espresso_events=lotoevents
