### ISSUE TITLE
Ticket Selector Ticket Rows Hidden if Event Has Only 1 Ticket

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3244]
see: https://github.com/eventespresso/event-espresso-core/issues/3228

### steps to reproduce

- find event with only one ticket (or create one)

- visit event listing on frontend

- ticket is hidden because of code added in 3228

**Comment by garthkoyle** [comment]
This looks better here: https://rc.eventespresso.com/events/one-ticket/
