### ISSUE TITLE
Users still showing as 'Abandoned' after returning from off-site payment method

### ISSUE THREAD

**Issue by jhourani** [eventespresso/event-espresso-core#3246]
## Issue Overview
I have created a custom payment method for Card Connect using an off-site payment. For payment, I send them to [my Hosted Payment Page](https://fingerlakesmuseu.securepayments.cardpointe.com/pay) where they compete their transaction. However it turns out this payment page does **not** send a response after the transaction describing the result. Is there a way to simply mark the registration as `Approved` once the user is returned to the website from the off-site payment form? Because right now they are all showing as `Abandoned`. 

Alternatively, if there was some way to force `handle_payment_update()` to be called that would work too, as I could just update the payment that way. But `handle_payment_update()` is never called, I believe because there is no IPN or response being returned from the off-site payment page.

## Bug report or feature request?

* [ ] Bug
* [ ] Feature
* [x] Neither

## Environment Data:

Version of EE: 4.10.11.rc.000 

Version of WordPress: 5.6

PHP Version: 7.3

Browser used:  Chrome

**Comment by tn3rb** [comment]
> this payment page does not send a response after the transaction describing the result.

### 😬

really?

that doesn't sound right... never heard of a payment gateway that doesn't provide some form of response regarding the status of the payment. How are you supposed to know the user paid?

I would double/triple check that there is not some way to receive the status after payment. The most common way is via an IPN (Instant Payment Notification) that is sent in a separate request so that the user can not spoof the payment, but some off-site gateways will send the response as URL parameters attached to the request that returns the user to your site. It would then be up to you to confirm the payment in a separate request (usually via curl). In either case (separate IPN or URL params returned with user) you have to provide a URL to the payment gateway to send the user back to.

If they really literally have no way to send a payment response, I would seriously consider using a different payment method because again... how are you supposed to know the user paid? Are you supposed to give the user access to your product even though you have no way to know whether they paid or not?

> But handle_payment_update() is never called, I believe because there is no IPN or response being returned from the off-site payment page.

what URL are you entering for your users to return to? If everything is set up correctly then `handle_payment_update()` should be called automatically, so we need to figure out what's missing.

Which off-site payment gateway from EE did you use as a reference?

Is there anywhere your code can be viewed?

Plz do NOT post any confidential information of any kind here though.

**Comment by jhourani** [comment]
> > this payment page does not send a response after the transaction describing the result.
> 
> ### 😬
> really?
> 
> that doesn't sound right... never heard of a payment gateway that doesn't provide some form of response regarding the status of the payment. How are you supposed to know the user paid?
> 
> I would double/triple check that there is not some way to receive the status after payment. The most common way is via an IPN (Instant Payment Notification) that is sent in a separate request so that the user can not spoof the payment, but some off-site gateways will send the response as URL parameters attached to the request that returns the user to your site. It would then be up to you to confirm the payment in a separate request (usually via curl). In either case (separate IPN or URL params returned with user) you have to provide a URL to the payment gateway to send the user back to.
> 
I spoke with CardPointe about this, and the [Hosted Payment Page (HPP)](https://fingerlakesmuseu.securepayments.cardpointe.com/pay) is not really setup for website integrations, it is more of a standalone front-end to their gateway. That being said, they did recommend that I use the [Card Connect API](https://developer.cardconnect.com/cardconnect-api) after the transaction to check on its status. To do this, I would need to do a lookup using the transaction ID passed from Event Espresso. I think I could do that easy enough, but I am not sure where I would write this code since `handle_update_payment()` is not being called. I would think it would then need to do a lookup via transaction ID using the Card Connect API, and finally update the EE_Payment object accordingly. 
> If they really literally have no way to send a payment response, I would seriously consider using a different payment method because again... how are you supposed to know the user paid? Are you supposed to give the user access to your product even though you have no way to know whether they paid or not?
I was equally surprised, but see my answer above. Also, we are using their "free" version, which is just that Hosted Payment Page (HPP). I think if we were to upgrade to the full "gateway version" or whatever it's called then we would get something more setup for custom integrations.
> 
> > But handle_payment_update() is never called, I believe because there is no IPN or response being returned from the off-site payment page.
> 
> what URL are you entering for your users to return to? If everything is set up correctly then `handle_payment_update()` should be called automatically, so we need to figure out what's missing.
Hmm, see my code below but other than that the only other place I specify the return URL is in my CardPointe configuration for the HPP.
> 
> Which off-site payment gateway from EE did you use as a reference?
I just used your [Custom Gateway Skeleton](https://github.com/eventespresso/event-espresso-core/blob/master/docs/D--Addon-API/using-new-payment-method-addon-skeleton.md) and made some minor changes, mostly to the `set_redirection_info()` function. See code below.
> 
> Is there anywhere your code can be viewed?
> 
Here are my changes to the `set_redirection_info()` function (the payment page is a public URL, I just took out the hash for security purposes)
```
/**
	 *
	 * @param EEI_Payment $payment
	 * @param type $billing_info
	 * @param type $return_url
	 * @param type $cancel_url
	 */
	public function set_redirection_info($payment, $billing_info = array(), $return_url = NULL, $notify_url = NULL, $cancel_url = NULL) {
		global $auto_made_thing_seed;
		if( empty( $auto_made_thing_seed ) ) {
			$auto_made_thing_seed = rand(1,1000000);
		}
		$payment->set_txn_id_chq_nmbr( $auto_made_thing_seed++ );
		
		
		var_dump($billing_info);
		print_r($billing_info);
		$first_name = '';
		$last_name = '';
		$email = '';
		$phone = '';
		$address = '';
		$address2 = '';
		$city = '';
		$country = '';
		$state = '';
		$zip = '';

		if (!empty($billing_info)) {
			if (!empty($billing_info['first_name'])) {
				$first_name = $billing_info['first_name'];	
			}

			if (!empty($billing_info['last_name'])) {
				$last_name = $billing_info['last_name'];	
			}

			if (!empty($billing_info['email'])) {
				$email = $billing_info['email'];	
			}

			if (!empty($billing_info['phone'])) {
				$phone = $billing_info['phone'];	
			}

			if (!empty($billing_info['address'])) {
				$address = $billing_info['address'];	
			}

			if (!empty($billing_info['address2'])) {
				$address2 = $billing_info['address2'];	
			}

			if (!empty($billing_info['city'])) {
				$city = $billing_info['city'];	
			}

			if (!empty($billing_info['country'])) {
				$country = $billing_info['country'];	
			}

			if (!empty($billing_info['state'])) {
				$state = $billing_info['state'];	
			}

			if (!empty($billing_info['zip'])) {
				$zip = $billing_info['zip'];	
			}
		}
		

		$payment->set_redirect_url( 'https://fingerlakesmuseu.securepayments.cardpointe.com/pay?signature={SOME_HASH}&paymentType=cc' );
		$payment->set_redirect_args( array(
			'amount' => $payment->amount(),
			'gateway_txn_id' => $payment->txn_id_chq_nmbr(),
			'return_url' => $return_url,
			'uses_separate_IPN_request' => $this->uses_separate_IPN_request(),
			'ipn_url' => $notify_url,
			'billFName' => $first_name,
			'billLName' => $last_name,
			'email' => $email,
			'cf_Name_' => $first_name.' '.$last_name,
			'total' => $payment->amount(),
			'billAddress1' => $address,
			'billAddress2' => $address2,
			'billCity' => $city,
			'tempBillState' => $state,
			'billZip' => $zip,
			'email' => $email,
			'phone' => $phone
		));

		return $payment;
	}
```
So the `$returnURL` is whatever is passed into `set_redirection_info()`. There is data in `$billing_info` because I define a custom billing form in `EE_PMT_Card_Connect_Payment_Method_Offsite`:
```
/**
	 * Creates the billing form for this payment method type
	 * @param \EE_Transaction $transaction
	 * @return NULL
	 */
	public function generate_new_billing_form( EE_Transaction $transaction = NULL ) {
		$billing_form = new EE_Billing_Attendee_Info_Form( $this->_pm_instance, array() );
    	return $this->apply_billing_form_debug_settings( $billing_form );
	}
```
And that's really about all I have done as far as modifications to your provided Off-Site Custom Payment Method skeleton code.

(It could be that the HPP that CardPointe provides as a free service is just not sufficient to accomplish this integration. If so we will need to upgrade our payment gateway but I just want to make sure with you all that this is the case first. Thanks for everything I really appreciate it and we love the plugin!)

**Comment by tn3rb** [comment]
closing in favour of #3252 which i will keep open for the time being as a channel of communication
