### ISSUE TITLE
UXIP nag persists on every admin page load

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#3255]
**Describe the bug**

On a new site the UXIP opt-in notification doesn't completely dismiss after clicking its "Dismiss" link. So it comes back on the next page load. 
**To Reproduce**
1. Load up a new site (no prior EE installation or a completely reset site) and switch to the /dev branch of EE4
2. go to an EE admin page
3. click on the "Dismiss" link within the UXIP notification
4. check the JS console. I saw an error like this: 400
Bad Request http://localhost/wp56/wp-admin/admin-ajax.php
5. Load another EE admin page and you'll see the UXIP notification again

**Expected behavior**

On master branch, when the UXIP dismiss link is clicked, the notification no longer appears on other admin page loads.
**Screenshots**

![Screen Shot 2021-01-08 at 1 15 11 PM](https://user-images.githubusercontent.com/891156/104049918-c7527d80-51b3-11eb-8c7d-97399c9ee547.png)
![Screen Shot 2021-01-08 at 1 15 57 PM](https://user-images.githubusercontent.com/891156/104049925-ca4d6e00-51b3-11eb-9b85-18c1fe18b5ef.png)

**Comment by tn3rb** [comment]
Also received this error:

```
Notice: Trying to access array offset on value of type bool
in /core/third_party_libs/pue/pue-client.php on line 1368
```

**Comment by tn3rb** [comment]
fix has been merged to dev branch
this can be tested now

**Comment by joshfeck** [comment]
Verified the fix.
