### ISSUE TITLE
Fatal error when activating MailChimp add-on when testing EDTR /dev branch

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#3259]
This fatal error is thrown when activating MailChimp master branch while testing EDTR /dev branch:

`PHP Fatal error:  Declaration of EE_MailChimp::name() must be compatible with EE_Addon::name(): string in /wp-content/plugins/eea-mailchimp/EE_MailChimp.class.php on line 131`

No error when activating MailChimp while testing EE4 master branch.

**Comment by tn3rb** [comment]
plz see: #3270

**Comment by tn3rb** [comment]
this can be tested now

**Comment by garthkoyle** [comment]
I was able to activate the Master branch of MailChimp on rc.eventespresso.com which has the latest EDTR/Dev updates.
