### ISSUE TITLE
Runtime exception when using the Attendee Mover while on /dev branch (EDTR)

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#3261]
Core branch: /dev
Attendee Mover branch: master

Activate Attendee mover add-on, go to Event Espresso > Registrations and click the icon to move a registration

Step 1 does not load the event selector and this exception is thrown:

`An RuntimeException was thrown!   code: EE_Registry - _create_object - 1264
"Invalid arguments supplied for the EventEspresso\core\libraries\rest_api\controllers\model\Read class, 1 were required but 0 were passed."`

**Comment by tn3rb** [comment]
plz see: #3270

**Comment by tn3rb** [comment]
fixed and ready for testing

**Comment by garthkoyle** [comment]
Attendee mover works now, no errors.
