### ISSUE TITLE
Ticket menu displayed under admin menu on larger screens

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3266]
Edge case?

On an event, create 2 tickets.

On the ticket closest to the admin menu, click on the ticket menu, it's displayed under the admin menu.

Like so: https://monosnap.com/file/18KslCvpYTEmHKKCUispiHHobVls46

Happens below 1760px wide for me when I adjust the zoom on the browser to 90%

**Comment by tn3rb** [comment]
fixed in https://github.com/eventespresso/barista/pull/630
ready for testing

**Comment by sethshoultes** [comment]
What branch do we test this with? Are there testing notes?

**Comment by Pebblo** [comment]
@sethshoultes EDTR changes are all on `dev` branch

Tested and confirmed this is fixed.
