### ISSUE TITLE
Changes related to the 'Are you sure you want to close this?' message.

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3267]
So, first, steps to highlight the 'problem' here.

On an Event with 2 datetimes and 2 tickets, open TAM and **UN**assign all tickets from all datetimes.

Now you have something like this: 
![image](https://user-images.githubusercontent.com/4345417/104596898-88696f80-566c-11eb-984a-a14c43b47a51.png)

Obviously, that's bad!  I don't know what to do! I'm lost and I wanna get out of here.... pronto!

But the Cancel has been disabled! arrgggghhhh.

Oh, there's an X! Smash that X button!

https://monosnap.com/file/TZuw0OoZjnxpNNV14lVQJ8p9XW7c0G

> Alert!
> Are you sure you want to close this?

Erm, I was.... until you asked me that! Why are you asking me? If I close it does it save, have I broken everything? I've broken it haven't I! Hit yes, I'm sure.... now I'll need to fix everything aga.... oh, nothing happened, it's fine. Yay!

----

Now that everyone is up to speed and full of TAM popup anxiety, questions :)

Should the cancel buttons ever be disabled in those models? We don't update unless Submit is clicked so cancel should always be just that, a way to cancel everything we've just done, right?

Can we change the 'Are you sure you want to close this?' message to make it clear that the changes will not be saved?

----

If I edit a datetime using Menu -> Edit datetime, click through to assign tickets to the datetime and remove the all ticket assignments I get a similar message to above:

https://monosnap.com/file/yHOG8kgCua3seIyGPxc500O9Vj5Fsb

Only this time if I click the X it simply closes, should that alert also be shown there? OR should the alert NOT be shown on the other section?

**Comment by manzoorwanijk** [comment]
> We don't update unless Submit is clicked so cancel should always be just that, a way to cancel everything we've just done, right?

I agree with keeping the cancel button always enabled.

**Comment by tn3rb** [comment]
TAM cancel button fixed in https://github.com/eventespresso/barista/pull/629
confirmation dialog enhancement in progress with: https://github.com/eventespresso/barista/issues/636

**Comment by tn3rb** [comment]
cancel close enhancements in progress in https://github.com/eventespresso/barista/pull/644

**Comment by tn3rb** [comment]
ready for testing now

**Comment by garthkoyle** [comment]
I can see clearly now, the cancel button is showing.
