### ISSUE TITLE
EE REST API Broken on EDTR?

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3276]
Found whilst testing #3261 

Attendee mover activated but testing its functionality failed, the REST request sent to pull in the events on step one showed 404.

So, then I started checking other endpoints locally and noticed that they no longer work.
 
Some quick examples:

https://rc.eventespresso.com/wp-json/ee/v4.8.36
https://rc.eventespresso.com/wp-json/ee/v4.8.36/site_info
https://rc.eventespresso.com/wp-json/ee/v4.8.36/events

I did checkout the commit right before the changes for above were made but that didn't seem to fix it so I don't think this is from the latest changes?

**Comment by tn3rb** [comment]
was a dumb dumb mistake I made
have a fix in #3277

**Comment by garthkoyle** [comment]
@Pebblo will you re-test this?

**Comment by garthkoyle** [comment]
This is working now, no errors.

**Comment by joshfeck** [comment]
Verified the fix.
