### ISSUE TITLE
Anonymize registrant IP address for GDPR

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/event-espresso-core#328]
## Issue Overview
Migrated from codebase ticket https://events.codebasehq.com/projects/event-espresso/tickets/11364.
However, on the similar WordPRess core ticket https://core.trac.wordpress.org/ticket/43588 they planned to store IP addresses of commenters until they were either marked as spam or approved, because the IP address can help identify spammers. And then when they "anonymize" the IP address, they only remove the last octet, not the entire thing.

So we may want to store the first 3 octets of the IP address, and possibly store the entire IP address while the transaction is incomplete.

**Comment by mnelson4** [comment]
I'm thinking that when a transaction progresses to complete or pending payment, we should anonymize the IP address. And maybe it should be optional?

Theoretically, having the IP address could be useful for identifying and blocking spammers, so it might be nice to keep it, like how WP comments keep it until the comment is approved. Thoughts @tn3rb ?

**Comment by tn3rb** [comment]
ya the primary reason why I tracked the IP was to facilitate blocking spammers and bots, but thought it would also come in handy for metrics, ie: getting a rough idea where registrants were coming from. That's never been pursued so anonymizing the last 3 octets of the IP address would be ideal imho as that would still allow a site to approximately localize registrants but not with any precision (like determine the general area they are from). 

With regards to blocking bots, we now have a request stack middleware app for doing so which does use the IP address, but that is long before the IP is saved to the session data, and the middleware app does not record anything, so there is currently no need to store IPs long term.

> I'm thinking that when a transaction progresses to complete or pending payment, we should anonymize the IP address.

I think this could be done directly within `\EE_SPCO_Reg_Step_Finalize_Registration::_finalize_transaction()` which would simply require us to edit the IP address in the session data before storing it.

I don't know of anywhere else we store a user's IP address.
