### ISSUE TITLE
EDTR loads the WordPress React instead of the internal bundled React

### ISSUE THREAD

**Issue by manzoorwanijk** [eventespresso/event-espresso-core#3280]
In #2769, `react` and `react-dom` were bundled to load them externally. Both of those assets and their minified versions were added to `assets/vendor` directory and registered in WP as `react` and `react-dom` handles respectively.

But, due to the older version of deployment from barista, that `assets/vendor` directory got wiped out. But why wasn't there any error? 🤔

The reason for that being the name of the script handles - `react` and `react-dom`, which are already registered by WP with its internal URLs. So even thought the script was registered by EE, but it loaded and still loads the WP React and not the internal EE bundled react.

Two possible solutions:
1. Deregister `'react' ` and `'react-dom'` via `wp_deregister_script()` before registering them. But, this should not happen in blocks domain for obvious reasons.

2.
    - Rename the handles as something like `eventespresso-react` and `eventespresso-react-dom` to avoid the WP handle name.
    - Re-add those assets into `assets/vendor` directory.
    - Update dependency extraction script in barista to use the above handle names.

Notes:
- First solution is the easiest but we will need to be aware of the domain before-hand, which means addons will have to handle this logic separately, because core won't be aware of the addon domains or will it be? 🤔 
- Second solution is a bit complicated but the addons will have known and clear-cut dependencies defined (`eventespresso-react`, `eventespresso-react-dom`) and they won't need to re-run the deregister logic. Otherwise if we can expose that logic via core, it should work.

**Comment by manzoorwanijk** [comment]
Lets stick to the WP react version for now.

**Comment by tn3rb** [comment]
just for the record, i think your second solution above might be the better one if we go that route
the biggest problem with simply de-registering existing assets is that others may be depending on those specific versions
