### ISSUE TITLE
Sort Dates by Datetime by Default

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#3281]
I've noticed that when adding datetimes to an event, the datetimes are organized in a random order rather than by date. Here's a screenshot from this event (https://rc.eventespresso.com/wp-admin/admin.php?page=espresso_events&action=edit&post=81) where the datetimes are randomly organized by default:
<img width="1169" alt="Screen Shot 2021-01-25 at 11 11 27 AM" src="https://user-images.githubusercontent.com/235315/105747809-7b673e80-5efe-11eb-8f53-fabc552c71b4.png">
<img width="1176" alt="Screen Shot 2021-01-25 at 11 19 59 AM" src="https://user-images.githubusercontent.com/235315/105748374-4a3b3e00-5eff-11eb-8f63-a0e106d1b8fd.png">

I added the datetimes in order of date (ex. February 24 event, then the February 25 event, and so on) but the datetimes seem to be sorted in random order. Can we sort the dates by datetime by default?

**Comment by tn3rb** [comment]
the default is the custom order, which is the same as the existing event editor:

![ScreenShot_20210125110102](https://user-images.githubusercontent.com/1751030/105752903-ba949000-5efc-11eb-8a19-952a35807fc9.png)

With the new EDTR though, your filter selections are saved to your browser's session data, so try this:

- click on "show filters"
- change "sort by" to "start date"
- click "hide filters"
- then refresh the page (or visit another admin page and come back)
- dates list should still be sorted by date, you can even open up another event and its dateslist will also be sorted the same

**Comment by sethshoultes** [comment]
Okay, that works. Thanks.
