### ISSUE TITLE
Notification Tabs Styling Issues

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#3282]
It seems the tabs for the notifications section of the event editor are pushed down a bit. Here are some screenshots from Firefox, then Google Chrome on my Mac:
<img width="750" alt="Screen Shot 2021-01-25 at 11 42 21 AM" src="https://user-images.githubusercontent.com/235315/105751401-31348c00-5f03-11eb-82f5-91ef7300bf8c.png">
<img width="958" alt="Screen Shot 2021-01-25 at 11 42 29 AM" src="https://user-images.githubusercontent.com/235315/105751411-342f7c80-5f03-11eb-9b0a-563ce5114d92.png">

**Comment by tn3rb** [comment]
looks like the `.nav-tab` class needs `box-sizing: content-box;` added to it

**Comment by tn3rb** [comment]
fixed in #3283 and ready for testing

**Comment by garthkoyle** [comment]
That looks better on Dev (barista.eventespresso.com). 

![image](https://user-images.githubusercontent.com/3094547/105774648-c3985800-5f22-11eb-800a-2f2c015a3879.png)

Checking to see if this was pushed to rc.eventespresso.com to re-test there too.

**Comment by garthkoyle** [comment]
looking good on RC: 

![image](https://user-images.githubusercontent.com/3094547/105775285-ce072180-5f23-11eb-8679-fbf6b9ac449e.png)
