### ISSUE TITLE
Prices not cloned from default tickets.

### ISSUE THREAD

**Issue by manzoorwanijk** [eventespresso/event-espresso-core#3287]
Steps:
- Create a default ticket or mark a ticket as default
- Add prices to the ticket
- Check the database for the correct relations being set between the ticket and the prices
- Add a new event
- Check the prices of the cloned default ticket

**Expected** The cloned ticket should have the prices that you added above

**Actual** The ticket has no prices.

**Comment by tn3rb** [comment]
https://github.com/eventespresso/event-espresso-core/pull/3293 addresses some of this issue, but it appears there are still some client side changes required before the prices will show up correctly in the calculator

**Comment by manzoorwanijk** [comment]
> but it appears there are still some client side changes required before the prices will show up correctly in the calculator

Everything looks fine to me. Closing this.
