### ISSUE TITLE
Facilitate having checkbox for consenting to site's privacy policy for GDPR

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/event-espresso-core#330]
When users register for an event, they should explicitly consent to the site's privacy policy, so we should have an input on registration forms for this.
Right now I think it should be optional in case someone adamantly refuses to have their regform modified

**Comment by mnelson4** [comment]
The easiest way to achieve this would be:
-add a new system question, whose label is something like "Do you consent to having your data stored according to the Privacy Policy (link)?" and there would be a checkbox with the value "I consent to the Privacy Policy". 

This approach has a few drawbacks though:
1. Ideally this question will always appear at the very bottom of the reg form. We'd probably like to default to having this be part of the Personal info question group, but then if there are address questions or other systme questions, it will actually be towards the top of the form.
2. If we put it in a new system question group that has a very high order value so it always appears at the bottom, then site admins will need to manually include it on every event (and they probably want to use it on ALL or none)
3. If it's a regular checkbox, we'd probably want to allow admins to change the text, but certainly not provide more checkbox options, which by default the question would allow. Also, once the question is answered, they won't be able to change the text right next to the checkbox.
4. The value to this question will appear on the registration approved email, CSV reports, etc. That will probably be annoying. Ideally it just appears during registration, maybe even only during initial registration, and that's it.
5. We don't want this to appear for EACH registration on a group registration, just once on the form

So it's becoming clearer to me that this should NOT be new system question afterall.

I think there should be a checkbox in the admin saying "Require consent to Privacy Policy in Registraiton Form?", and a text field allowing the admin to choose what language is used for the field. Then, when that's checked, SPCO takes care of adding this extra checkbox right above the submit button, and preferably only when they first fill out the form (not on revisits)

Thoughts @sethshoultes ?

**Comment by sethshoultes** [comment]
@mnelson4 i think that sounds like a good plan. Thanks for thinking this through.

**Comment by mnelson4** [comment]
PR https://github.com/eventespresso/event-espresso-core/pull/470 was just merged into master
