### ISSUE TITLE
Custom off-site gateway - transaction completed and approved but still shows Pending Payment

### ISSUE THREAD

**Issue by jhourani** [eventespresso/event-espresso-core#3317]
## Issue Overview
I am able to successfully process and update transactions, however the registration itself still shows as Pending Payment. I have created a custom off-site gateway for CardPointe using your skeleton as a basis. In my case, CardPointe does not allow for dynamic notify or return URLs to be sent, only a webhook which points to a static page. So, as an alternative I have setup a static page where I have code to process the transaction when it arrives. I then take the `$return_url` created by Event Espresso, add my additional arguments to it and make a GET request to the `registration-checkout` page. I know this all works because it hits the `handle_payment_update()` method and updates the transaction accordingly. Now, I am thinking I also need to update the user's registration so that it is not pending, but I am not sure how to do that? Here is my gateway class:
```
<?php

if (!defined('EVENT_ESPRESSO_VERSION')) {
	exit('No direct script access allowed');
}

/**
 *
 * EEG_Card_Connect_Payment_Method_Offsite
 *
 * @package			Event Espresso
 * @subpackage
 * @author				Mike Nelson
 *
 */
class EEG_Card_Connect_Payment_Method_Offsite extends EE_Offsite_Gateway{

	/**
	 * This gateway supports all currencies by default. To limit it to
	 * only certain currencies, specify them here
	 * @var array
	 */
	protected $_currencies_supported = EE_Gateway::all_currencies_supported;
	
	/**
	 * Example of site's login ID
	 * @var string
	 */
	protected $_login_id = null;
	
	/**
	 * Whether we have configured the gateway integration object to use a separate IPN or not
	 * @var boolean
	 */
	protected $_override_use_separate_IPN = null;
	
	/**
	 * @return EEG_Card_Connect_Payment_Method_Offsite
	 */
	public function __construct() {
		//if the gateway you are integrating with sends a separate instant-payment-notification request
		//(instead of sending payment information along with the user)
		//set this to TRUE
		$this->set_uses_separate_IPN_request( false ) ;
		parent::__construct();
	}
	
	/**
	 * Override's parent so this gateway integration class can act like one that uses
	 * a separate IPN or not, depending on what is set in the payment methods settings form
	 * @return boolean
	 */
	public function uses_separate_IPN_request() {
		if( $this->_override_use_separate_IPN_request !== null ) {
			$this->set_uses_separate_IPN_request( $this->_override_use_separate_IPN_request );
		} 
		return parent::uses_separate_IPN_request();
	}

	/**
	 *
	 * @param arrat $update_info {
	 *	@type string $gateway_txn_id
	 *	@type string status an EEMI_Payment status
	 * }
	 * @param type $transaction
	 * @return EEI_Payment
	 */
	public function handle_payment_update($update_info, $transaction) {

		if (!isset($update_info['gateway_txn_id'])) {
			return NULL;
		}

		$payment = $this->_pay_model->get_payment_by_txn_id_chq_nmbr($update_info['gateway_txn_id']);
		
		if($payment instanceof EEI_Payment &&  isset($update_info['status'])) {

			if ($update_info['status'] == 'Approved') {
				$payment->set_status( $this->_pay_model->approved_status() );
				$payment->set_gateway_response( __( 'Payment Approved', 'event_espresso' ));
			} else {
				$payment->set_status( $this->_pay_model->failed_status() );
				$payment->set_gateway_response( __( 'Payment Failed', 'event_espresso' ) );
			}
		}
		
		return $payment;
	}

	/**
	 *
	 * @param EEI_Payment $payment
	 * @param type $billing_info
	 * @param type $return_url
	 * @param type $cancel_url
	 */
	public function set_redirection_info($payment, $billing_info = array(), $return_url = NULL, $notify_url = NULL, $cancel_url = NULL) {
		
		global $auto_made_thing_seed;
		global $wpdb;   

		if( empty( $auto_made_thing_seed ) ) {
			$auto_made_thing_seed = rand(1,1000000);
		}
		$payment->set_txn_id_chq_nmbr( $auto_made_thing_seed++ );
		
		$first_name = '';
		$last_name = '';
		$email = '';
		$phone = '';
		$address = '';
		$address2 = '';
		$city = '';
		$country = '';
		$state = '';
		$zip = '';
		$event_ID = null;
		$event_name = '';
		$transaction_ID = null;

		if (!empty($billing_info)) {
			if (!empty($billing_info['first_name'])) {
				$first_name = $billing_info['first_name'];	
			}

			if (!empty($billing_info['last_name'])) {
				$last_name = $billing_info['last_name'];	
			}

			if (!empty($billing_info['email'])) {
				$email = $billing_info['email'];	
			}

			if (!empty($billing_info['phone'])) {
				$phone = $billing_info['phone'];	
			}

			if (!empty($billing_info['address'])) {
				$address = $billing_info['address'];	
			}

			if (!empty($billing_info['address2'])) {
				$address2 = $billing_info['address2'];	
			}

			if (!empty($billing_info['city'])) {
				$city = $billing_info['city'];	
			}

			if (!empty($billing_info['country'])) {
				$country = $billing_info['country'];	
			}

			if (!empty($billing_info['state'])) {
				$state = $billing_info['state'];	
			}

			if (!empty($billing_info['zip'])) {
				$zip = $billing_info['zip'];	
			}
		}
		
		
		$transaction = $payment->transaction();

		if ( $transaction instanceof EE_Transaction ) {

			$primary_registrant = $transaction->primary_registration();
			$event = $primary_registrant->event_obj();

			$event_ID = $event->ID();
			$event_name = '';
			$transaction_ID = $transaction->ID();

			$name_of_event_array = EEM_Event::instance()->get_col([['EVT_ID' => $event_ID]], 'EVT_name');
			if ($name_of_event_array && count($name_of_event_array) > 0) {
				$event_name = $name_of_event_array[0];
			}	


			$payment->set_redirect_url( 'https://myhostedpaymentpage.com/pay?signature=19adqVcABcJxxp4JBa4%2FbwNOpv%2B3K%2B4sTZNvbE%2F3V%2FybwxmXo6L5VxEqX1Aq4TEFM%3D&paymentType=cc');

			$payment->set_redirect_args( array(
				'amount' => $payment->amount(),
				'gateway_txn_id' => $payment->txn_id_chq_nmbr(),
				'return_url' => $return_url,
				'uses_separate_IPN_request' => $this->uses_separate_IPN_request(),
				'ipn_url' => $notify_url,
				'billFName' => $first_name,
				'billLName' => $last_name,
				'email' => $email,
				'cf_Name_' => $first_name.' '.$last_name,
				'total' => $payment->amount(),
				'billAddress1' => $address,
				'billAddress2' => $address2,
				'billCity' => $city,
				'tempBillState' => $state,
				'billZip' => $zip,
				'email' => $email,
				'phone' => $phone,
				'cf_hidden_Event_ID' => $event_ID,
				'cf_hidden_Event_Name' => $event_name,
				'cf_hidden_return_url' => $return_url,
				'cf_hidden_Transaction_ID' => $transaction_ID 
			));
		}

		return $payment;
	}
}
```
And here is my custom plugin that processes the transaction information and makes the GET request back to the Event Espresso registration-checkout page:
```
/**
 * This is a function to process IPNs sent from a CardPointe Hosted Payment Page (HPP). As long as this
 * plugin is activated it can be placed on any page. This block of code receives and parses the response,
 * grabs the return_url originally sent by Event Espresso and then makes an HTTP GET request to the registration 
 * checkout page (which Event Espresso is expecting and will take over the registration from there).
 * 
 * @author Jordan Hourani
 * 
 * @param string $ipn_pagename The name (slug) of the page receiving the IPN 
 * @return void
 */
function process_cardpointe_ipn($ipn_pagename) {

	if (is_page($ipn_pagename)) {
		if (isset($_POST["json"]) && !empty($_POST["json"])) {

			$data = stripslashes($_POST["json"]);
			$decoded_data = json_decode($data, true);

			if ($decoded_data && count($decoded_data) > 0) {

				// Make sure this came from our event payment page
				if ($decoded_data["merchantId"] == MERCHANT_ID) {

					// We will only be getting a webhook response for successfull payments. But just in case,
					// make sure that this was an Approval (00).
					$response_code = $decoded_data["responseCode"];
					if ($response_code == "00" || $decoded_data['responseText'] == "Approval") {

						$return_url = htmlspecialchars_decode($decoded_data["cf_hidden_return_url"]);
						$notify_url = htmlspecialchars_decode($decoded_data["cf_hidden_ipn_url"]);

						// the return_url will have #checkout on the end. We need to remove that so that we can add
						// the rest of the server-side arguments. Then we can put it back on the end afterwards.
						$return_url = str_replace("#checkout", "", $return_url);

						// Ok we have the response data and it is an Approval so post the data to the
						// registration-checkout page which Event Espresso is expecting
						$transaction_data = array(
							'payment' => "Credit",
							'amount' => $decoded_data['total'],
							'status' => "Approved",
							'gateway_txn_id' => $decoded_data['cf_hidden_gateway_txn_id']
						);

						$query_string = http_build_query($transaction_data);

						$registration_checkout_url = $return_url."&".$query_string."#checkout";

						$response = wp_remote_get( $registration_checkout_url, array(
							'method' => 'GET',
							'timeout' => 45,
							'redirection' => 5,
							'httpversion' => '1.0',
							'blocking' => true,
							'headers' => array(),
							'body' => array(),
							'cookies' => array()
							)
						);
					}
				}
			}
		}
	}
}
```
So in the admin, the transaction shows as Complete along with the Gateway Response being Payment Approved, so all good. However the user themselves is still in a Pending Payment state and requires manual Approve and Notify. Can I do this possibly in the `handle_update_payment()` method?

## Bug report or feature request?

* [ ] Bug
* [ ] Feature
* [x] Neither

## Environment Data:
Version of EE: 4.10.10.decaf

Version of WordPress: 5.6

PHP Version: 7.3

Browser used: Chrome

**Comment by tn3rb** [comment]
First off, here's a couple minor suggestions for code improvements:

In `EEG_Card_Connect_Payment_Method_Offsite::set_redirection_info()` remove:

```php
global $auto_made_thing_seed;
global $wpdb;

if (empty($auto_made_thing_seed)) {
    $auto_made_thing_seed = rand(1, 1000000);
}
$payment->set_txn_id_chq_nmbr($auto_made_thing_seed++);
```

then further down below that change

```php
if ($transaction instanceof EE_Transaction) {
    $primary_registrant = $transaction->primary_registration();
    $event          = $primary_registrant->event_obj();

    $event_ID       = $event->ID();
    $event_name     = '';
    $transaction_ID = $transaction->ID();

```

to:

```php
if ($transaction instanceof EE_Transaction) {
    $primary_registrant = $transaction->primary_registration();
    $payment->set_txn_id_chq_nmbr($primary_registrant->reg_code());
    
    $event          = $primary_registrant->event_obj();
    $event_ID       = $event->ID();
    $event_name     = $event->name();
    $transaction_ID = $transaction->ID();
```

Everything else looks pretty good. Now to fix your problem...

Can I please see an example of the query string for your page where the `process_cardpointe_ipn()` function runs?

It looks to me like there is a mismatch between the keys used for the query parameters.

For example, in `EEG_Card_Connect_Payment_Method_Offsite::set_redirection_info()` you have the following fields in the redirect args array:

```php
'total'                     => $payment->amount(),
'cf_hidden_Event_ID'        => $event_ID,
'cf_hidden_Event_Name'      => $event_name,
'cf_hidden_return_url'      => $return_url,
'cf_hidden_Transaction_ID'  => $transaction_ID,
```

but in `process_cardpointe_ipn()` you are retrieving the following fields from the `$decoded_data` array:

```php
'merchantId'
'responseCode'
'responseText'
'cf_hidden_return_url'
'cf_hidden_ipn_url'
'total'
'cf_hidden_gateway_txn_id'
```

the first three (`'merchantId'`, `'responseCode'`, `'responseText'`) I'm assuming are sent by the gateway and obviously would not be set in the redirect args ahead of time, but `'cf_hidden_return_url'` and `'total'` ARE set in the redirect args array. 

However, and this is where I think you're mistake might be, the redirect args set `'cf_hidden_Transaction_ID'` but your response logic is looking for an argument named `'cf_hidden_gateway_txn_id'`. Where is `'cf_hidden_gateway_txn_id'` supposed to be coming from and is that supposed to `'cf_hidden_Transaction_ID'` instead? (or conversely, should `'cf_hidden_Transaction_ID'` be renamed to `'cf_hidden_gateway_txn_id'`?)

The reason that the payment and transaction are updated is because those are handled by the IPN (the logic that runs in `handle_payment_update()`). After that we need to get you redirected to the checkout page correctly so that your registrants can complete the entire registration process. Another important question: after returning from making a payment, are you eventually forwarded to the Thank You page?

So to reiterate, I need:

- an example of the full query string sent to your static return page. **PLEASE don't publish any sensitive info**, I'm really only interested in seeing values for Transaction related parameters)

- also need to know if you are making it to the Thank You page after payment (I'm guessing not)

**Comment by jhourani** [comment]
Thanks for the code suggestions, duly noted! May I ask what was wrong with this part though? I needed to send the event name to our payment gateway and this seemed like the way to do it (using the modeling system)
```
$name_of_event_array = EEM_Event::instance()->get_col([['EVT_ID' => $event_ID]], 'EVT_name');
if ($name_of_event_array && count($name_of_event_array) > 0) {
    $event_name = $name_of_event_array[0];
}
```

Yes it's true that I set a `cf_hidden_Transaction_ID`, but I also set `gateway_txn_id` above that:
```
$payment->set_redirect_args( array(
				'amount' => $payment->amount(),
				'gateway_txn_id' => $payment->txn_id_chq_nmbr(), // <-- right here
				'return_url' => $return_url,
				'uses_separate_IPN_request' => $this->uses_separate_IPN_request(),
				'ipn_url' => $notify_url,
				'billFName' => $first_name,
				'billLName' => $last_name,
				'email' => $email,
				'cf_Name_' => $first_name.' '.$last_name,
				'total' => $payment->amount(),
				'billAddress1' => $address,
				'billAddress2' => $address2,
				'billCity' => $city,
				'tempBillState' => $state,
				'billZip' => $zip,
				'email' => $email,
				'phone' => $phone,
				'cf_hidden_Event_ID' => $event_ID,
				'cf_hidden_Event_Name' => $event_name,
				'cf_hidden_return_url' => $return_url,
				'cf_hidden_Transaction_ID' => $transaction_ID 
			));
		}
```
So I think those are matching up, because it does hit `handle_payment_update()` and it does mark it as Approved.

1. Here is an example of the query string that I create in `process_cardpointe_ipn()`;
```
https://www.mydomainname.org/registration-checkout/?uts=1612809905&step=payment_options&action=process_gateway_response&selected_method_of_payment=card_connect_payment_method_offsite&spco_txn=123&payment=Credit&amount=20.00&status=Approved&gateway_txn_id=315635#checkout 
```
I should also note, that if I take that URL directly and put it into my browser, everything works fine and I am directed to the checkout and Thank You page. But since the user and the data are arriving back on my site at different times, I could not simply just redirect them (as mentioned by one of your developers [here](https://github.com/eventespresso/event-espresso-core/issues/142)). That's why my plugin code in `process_cardpointe_ipn()` makes a GET request instead of say `wp_redirect()`.

2. You are correct, no they do not go to the Thank You page from  Event Espresso. I just send them to a Thank You page that I made. Should I set my payment form to send the user directly to the Event Espresso Thank You page? I didn't do that because I thought Event Espresso probably expected things to happen in a certain order, but I certainly could do that if needed!

**Comment by jhourani** [comment]
Hello, just checking in to see if you've had a chance to look at this yet? I am sure you are busy so just trying to keep this on the radar :)

**Comment by joshfeck** [comment]
Hi,

I can follow up with your question about why the event name code should be removed. The reason to remove it is because if you add the following (per tn3rb's suggestion) :

```if ($transaction instanceof EE_Transaction) {
    $primary_registrant = $transaction->primary_registration();
    $payment->set_txn_id_chq_nmbr($primary_registrant->reg_code());
    
    $event          = $primary_registrant->event_obj();
    $event_ID       = $event->ID();
    $event_name     = $event->name();
    $transaction_ID = $transaction->ID();```

then you've already set $event_name from the event that's attached to the primary registrant. Therefore it's not needed to hit the database again to get the name of the event.

**Comment by tn3rb** [comment]
First off, sorry for the delay, have been buried in some code for the past couple of weeks.

What @joshfeck wrote is correct. Since you have already run a query to obtain an event object (`$event`) it doesn't make sense to run an additional query to get the event's name, when you can obtain it from the object you already have via `$event->name()`.

re:
> I should also note, that if I take that URL directly and put it into my browser, everything works fine and I am directed to the checkout and Thank You page. But since the user and the data are arriving back on my site at different times, I could not simply just redirect them (as mentioned by one of your developers here).

not sure what specific comment you are referring to on that other issue, but in [this response here](https://github.com/eventespresso/event-espresso-core/issues/142#issuecomment-177001461) Michael states:

> I think you're best using some old fashioned wp actions to detect a return or notify request from the gateway and redirect the request to the urls the EE4 payment methods system is expecting

and I agree. If that URL you posted works correctly, and you are able to detect the users on your static return page, then why not redirect them to that URL?

re:
> I just send them to a Thank You page that I made. Should I set my payment form to send the user directly to the Event Espresso Thank You page? I didn't do that because I thought Event Espresso probably expected things to happen in a certain order, but I certainly could do that if needed!

No you don't want to send them directly to the Thank You page. Basically the registration process has three steps:

 1. attendee information - the registration form questions for gathering registrant data
 2. payment options - choosing method of payment, etc
 3. finalization - update transaction, registration, and payment data accordingly

you've gotten through step 1 and most of step 2, but you also need to complete steps three. I only say you've gotten through **most** of step 2 because the payment step has a bunch of subroutines depending on the type of payment gateway, but the user doesn't directly see these. Similarly the user doesn't directly see step 3 as it happens behind the scenes and is what performs the redirect to the Thank You page. This is why you are not seeing things being completed properly, because your users are getting redirected to some other page and are not completing the entire registration process.

So again, without being able to see all of your code and setup, it seems to me like your best bet is to redirect your users to that URL you posted, especially since you know that everything works correctly if you go to it.

...now going back to your older response, and this comment:

> Yes it's true that I set a cf_hidden_Transaction_ID, but I also set gateway_txn_id above that:

yes I saw that your code was setting `gateway_txn_id`:

```php
'gateway_txn_id' => $payment->txn_id_chq_nmbr(), // <-- right here
```

but in this code that processes the response:

```php
'gateway_txn_id' => $decoded_data['cf_hidden_gateway_txn_id']
```

you are looking for `cf_hidden_gateway_txn_id` which is not the same as `gateway_txn_id`

So it appears to me that you either need to change your initial redirect args to:

```php
	$payment->set_redirect_args( array(
		'amount' => $payment->amount(),
		'cf_hidden_gateway_txn_id' => $payment->txn_id_chq_nmbr(), <<<<<<<<< CHANGED
		'return_url' => $return_url,
		'uses_separate_IPN_request' => $this->uses_separate_IPN_request(),
		'ipn_url' => $notify_url,
		'billFName' => $first_name,
		'billLName' => $last_name,
		'email' => $email,
		'cf_Name_' => $first_name.' '.$last_name,
		'total' => $payment->amount(),
		'billAddress1' => $address,
		'billAddress2' => $address2,
		'billCity' => $city,
		'tempBillState' => $state,
		'billZip' => $zip,
		'email' => $email,
		'phone' => $phone,
		'cf_hidden_Event_ID' => $event_ID,
		'cf_hidden_Event_Name' => $event_name,
		'cf_hidden_return_url' => $return_url,
		'cf_hidden_Transaction_ID' => $transaction_ID 
	));
```

OR...

change your response processing code to:

```php
	$transaction_data = array(
		'payment' => "Credit",
		'amount' => $decoded_data['total'],
		'status' => "Approved",
		'gateway_txn_id' => $decoded_data['gateway_txn_id'] <<<<<<<<< CHANGED
	);
```

so that things match up. That is unless you have some other code somewhere that is handling that somehow.

**Comment by jhourani** [comment]
@tn3rb thank you so much for your response! And we are totally on the same page with what needs to be done, i.e 

- the gateway sends the user back to your static page
- you detect the request and either get their data from the request vars or their session data
- redirect them to that registration checkout payments options step with all of the correct request parameters
- Event Espresso will handle finalizing the transaction and forward them to the "Thank You" page

But I think you misunderstood. I am already detecting the request and either get their data from the request vars or their session data. And I am already redirecting them to the url that Event Espresso is expecting. What I am saying is that it is not completely working, only partly. It does complete the transaction information and it records it properly in Event Espresso, but it fails to actually finalize their registration. Here is my code for detecting the request, getting the data and redirecting the user:
`function process_cardpointe_ipn($ipn_pagename) {

	if (is_page($ipn_pagename)) {
		if (isset($_POST["json"]) && !empty($_POST["json"])) {

			$data = stripslashes($_POST["json"]);
			$decoded_data = json_decode($data, true);

			if ($decoded_data && count($decoded_data) > 0) {

				// Make sure this came from our event payment page
				if ($decoded_data["merchantId"] == MERCHANT_ID) {

					// We will only be getting a webhook response for successfull payments. But just in case,
					// make sure that this was an Approval (00).
					$response_code = $decoded_data["responseCode"];
					if ($response_code == "00" || $decoded_data['responseText'] == "Approval") {

						$return_url = htmlspecialchars_decode($decoded_data["cf_hidden_return_url"]);
						$notify_url = htmlspecialchars_decode($decoded_data["cf_hidden_ipn_url"]);

						// the return_url will have #checkout on the end. We need to remove that so that we can add
						// the rest of the server-side arguments. Then we can put it back on the end afterwards.
						$return_url = str_replace("#checkout", "", $return_url);

						// Ok we have the response data and it is an Approval so post the data to the
						// registration-checkout page which Event Espresso is expecting
						$transaction_data = array(
							'payment' => "Credit",
							'amount' => $decoded_data['total'],
							'status' => "Approved",
							'gateway_txn_id' => $decoded_data['cf_hidden_gateway_txn_id']
						);

						$query_string = http_build_query($transaction_data);

						$registration_checkout_url = $return_url."&".$query_string."#checkout";

						wp_mail(DEBUG_EMAIL, 'return_url', print_r($registration_checkout_url, true));

						$response = wp_remote_get( $registration_checkout_url, array(
							'method' => 'GET',
							'timeout' => 45,
							'redirection' => 5,
							'httpversion' => '1.0',
							'blocking' => true,
							'headers' => array(),
							'body' => array(),
							'cookies' => array()
							)
						);
					}
				}
			}
		}
	}
}`

This code is sitting on the page that the webhook from the payment gateway is posting the transaction data to. I know that it works because like I said, it does update and complete the transaction. It just doesn't finish the process and I can't figure out what I am missing.

**Comment by jhourani** [comment]
Oh and sorry I meant to answer this part too. It actually is `cf_hidden_gateway_txn_id ` because our payment page send it back with that extra field on it.

**Comment by jhourani** [comment]
Here is what it looks like on the admin site. As you can see, it does process the transaction from Card Pointe and marks it as complete. But for some reason the user still shows up as Pending Payment in their registration status and they require manual approval.
![ee_1](https://user-images.githubusercontent.com/1932333/109065803-20ba3180-76ba-11eb-8144-12f51ff30873.png)
![ee_2](https://user-images.githubusercontent.com/1932333/109065824-26b01280-76ba-11eb-9dce-31e3ab6c3dee.png)

**Comment by jhourani** [comment]
Guys I am happy to report that I have now gotten this working. I ended up storing the complete registration URL that I put together while processing the transaction in transient data. By the time the user returns to the site, the URL is ready so I get it out of transient data and then redirect them to that URL where Event Espresso takes over. And @tn3rb yes they do now end up on your thank you page! Thanks for the help, reading back over what you said helped me to solve this. Please feel free to close this ticket!

**Comment by tn3rb** [comment]
AWESOME!!!

Great to hear you got everything working. 
Please don't hesitate to reach out again if you need help with anytihng
