### ISSUE TITLE
Event submission crashes on an edge case

### ISSUE THREAD

**Issue by manzoorwanijk** [eventespresso/event-espresso-core#3323]
Steps:
- Activate Advanced Editor
- Edit an event
- Without closing the event edit page, open the Advanced Editor settings in new tab
- Deactivate Advanced Editor
- With the above event edit page still open, try to Save as Draft or Update.

BOOM! Critical error
```
Fatal error: Uncaught Exception: The "edit_event_datetimes" array is invalid therefore the event can not be updated.
in /home/eeservice/www/barista.eventespresso.com/wp-content/plugins/event-espresso-core/caffeinated/admin/new/pricing/espresso_events_Pricing_Hooks.class.php on line 308
```

**Comment by tn3rb** [comment]
imho this is expected behaviour similar to logging out in one tab then expecting to perform actions requiring authorization in another tab, or deactivating a plugin, then trying to use it, etc
