### ISSUE TITLE
Move all ticket information so it's displayed before the registration form if there's only one attendee information form

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#333]
Codebase: https://events.codebasehq.com/projects/event-espresso/tickets/11099

Requested:

https://eventespresso.com/topic/personal-info-section-embedded-within-ticket-details-on-attendee-info-page/
https://eventespresso.com/topic/multiple-event-registration-checkout-customization/
https://secure.helpscout.net/conversation/458079216/450050?folderId=100570

> Also, the Registration Checkout page displays information in this
> order:
> 
> 1st ticket (Camp 1) personal information 2nd ticket (Camp 2) 3rd
> ticket (English Course)
> 
> I would prefer to to have all tickets together in one list and then
> either before or after collect the payer / attendee information. The
> current layout does not make a lot of sense.

In cases like these I've been sharing [this snippet][3] that embeds some JavaScript to move all the ticket information divs into one place. Which results in something that looks like this:

![attendee info step][4]

> On the Attendee Info page after selecting the “Register Now” button, the screen displays the first ticket details followed by the request for Attendee 1 Personal Information (name, address, email, etc), then the second and third ticket details. This split is confusing. After selecting “Proceed to Payment Options” it summarizes and totals the ticket offerings as expected.

https://eventespresso.com/topic/ee4-multi-ticket-total-vat/

> One questions – is there an option to show all selected tickets on top of the actual registration form. By default we always see the first selected ticket, then the form and then the other ticket(s). Can it be modified?

https://eventespresso.com/topic/edit-registration-checkout-page/

> Edit registration-checkout page to show all the tickets purchased be together. If more than one type of ticket is purchased the details is shown, then the personal Information section is displayed, then the details of any subsequent tickets is shown. Can the detail information not be split?

https://eventespresso.com/topic/event-checkout-page-doesnt-show-all-selected-tickets/#post-228630

> I would like to specify only one address with an order of 2 tickets and show the tickets in a table. The first ticket is displayed at the top, then the query for the personal data comes and then the second ticket appears.
This makes no sense for me if I do not ask a second participant.

Screenshot showing the proposed move:

![move stuff][1]

Possible end result could look like this:

![enter image description here][2]

  [1]: https://www.evernote.com/l/AAR-uPh1i01AxrABeNH6hKhdvhnH_Z-97_0B/image.png
  [2]: https://www.evernote.com/l/AAQObkked8tI5Z0Q7w122nAm9e0hFtfDRycB/image.png
  [3]: https://gist.github.com/joshfeck/c14830939e0fe067597e82f90f3fecd9
  [4]: https://www.evernote.com/l/AASYt_5N4M5JxJ6NwekaigB7q4TLCQEqS4sB/image.png

**Comment by joshfeck** [comment]
Another report:
https://eventespresso.com/topic/limited-to-one-ticket/#post-268942

**Comment by joshfeck** [comment]
https://eventespresso.com/topic/checkout-page-item-then-form-to-fill-then-next-item/

**Comment by joshfeck** [comment]
https://eventespresso.com/topic/registration-page-set-up-formatting/

**Comment by joshfeck** [comment]
https://eventespresso.com/topic/shopping-cart-items-are-displayed-split-apart-on-registration-page/
