### ISSUE TITLE
Create Privacy Policy Content for GDPR

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/event-espresso-core#338]
Related to #325, except we need some actual content, not just "Lorem ipsum"...

I've made some notes about what data we store:
-ip address (although there is a ticket to change this on #328)
-some getaways store a few digits of card
-gateway logs for a week (plans to change this on #329)
-name and email (and address)
-registration answers 
-payment history
-event attendance and check ins
-history of emails received
-user agent (debated whether this is personal data or not, see https://core.trac.wordpress.org/ticket/43438#comment:17)

Add-ons
-MailChimp sends data. See https://kb.mailchimp.com/accounts/management/collect-consent-with-gdpr-forms
-infusion soft sends data to infusionsoft
-segment: purchases, activity, 
-affiliate wp? (not sure if it stores any data)

It's debatted whether "Privacy policy" and "Cookie policy" should be different.

**Comment by mnelson4** [comment]
WP equivalent ticket: https://core.trac.wordpress.org/ticket/43473

**Comment by mnelson4** [comment]
This is WooCommerce's current privacy policy suggested text:

We coll

> ect information about you during the checkout process on our store. This information may include, but is not limited to, your name, billing address, shipping address, email address, phone number, credit card/payment details and any other details that might be requested from you for the purpose of processing your orders.
> 
> Handling this data also allows us to:
> 
> - Send you important account/order/service information.
> - Respond to your queries, refund requests, or complaints.
> - Process payments and to prevent fraudulent transactions. We do this on the basis of our legitimate business interests.
> - Set up and administer your account, provide technical and customer support, and to verify your identity.
> 
> Additionally we may also collect the following information:
> 
> - Location and traffic data (including IP address and browser type) if you place an order, or if we need to estimate taxes and shipping costs based on your location.
> - Product pages visited and content viewed whist your session is active.
> - Your comments and product reviews if you choose to leave them on our website.
> - Shipping address if you request shipping rates from us before checkout whist your session is active.
> - Cookies which are essential to keep track of the contents of your cart whist your session is active.
> - Account email/password to allow you to access your account, if you have one.
> - If you choose to create an account with us, your name, address, email and phone number, which will be used to populate the checkout for future orders.
> 

I think it's probably still a work-in-progress, but it's something

**Comment by sethshoultes** [comment]
I think the WooCommerce text is pretty standard from what I've seen elsewhere. Here's the text you shared above but slightly tweaked:

We collect information about you during the checkout process on our store. This information may include but is not limited to, your name, billing address, mailing address, email address, phone number, credit card/payment details and any other details that might be requested from you for the purpose of processing your registration or ticket purchase.

Handling this data also allows us to:
	•	Send you important account/purchase/service information.
	•	Respond to your queries, refund requests, or complaints.
	•	Process payments and to prevent fraudulent transactions. We do this on the basis of our legitimate business interests.
	•	Set up and administer your account, provide technical and customer support, and to verify your identity.
Additionally, we may also collect the following information:
	•	Location and traffic data (including IP address and browser type) if you register for an event, make a purchase, or transaction on our site.
	•	Pages visited and content viewed whilst your session is active.
	•	Comments and reviews if you choose to leave them on our website.
	•	Account email/password to allow you to access your account, if you have one.
	•	If you choose to create an account with us, your name, address, email and phone number, which may be used to populate the checkout for future purchases.
