### ISSUE TITLE
Add Toggle For Setting Ticket Visibility

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3389]
plz see: https://github.com/eventespresso/barista/issues/473

# testing steps

- checkout the `dev` branch on the event-espresso-core repo

- Go to Event Editor and add/edit an event 

- add/edit 4 tickets

- Ticket 1
    - name: Public
    - open edit ticket form modal and set visibility to: "Public"

        ![ScreenShot_20210507153630](https://user-images.githubusercontent.com/1751030/117515600-94df4400-af4b-11eb-92f0-0b3696093f37.png)

- Ticket 2
    - name: Members Only
    - open edit ticket form modal and set visibility to: "Members Only"

- Ticket 3
    - name: Admins Only
    - open edit ticket form modal and set visibility to: "Admins Only"

- Ticket 4
    - name: Admin UI Only
    - open edit ticket form modal and set visibility to: "Admin UI Only"

- save event

- go to Users admin page and add/edit three users

- User 1 - set role to Administrator
- User 2 - set role to Event Administrator
- User 3 - set role to Subscriber (anything other than the above roles)

- LOG OUT

- log in again as Administrator User
	- visit registration page on frontend
	- [x] confirm that "Public", "Members Only", and "Admins Only" tickets are visible

        ![ScreenShot_20210506172820](https://user-images.githubusercontent.com/1751030/117515697-d8d24900-af4b-11eb-8688-8d04ca335091.png)

	- go to event lists admin page and click on the "Registrations" link under the name of the event from above

        ![ScreenShot_20210507154639](https://user-images.githubusercontent.com/1751030/117515564-7da05680-af4b-11eb-8853-4f747551db2a.png)

	- click "Add New Registration" button at top of screen
	- [x] confirm that "Public", "Members Only", "Admins Only", and "Admin UI Only" tickets are visible

		![ScreenShot_20210506173300](https://user-images.githubusercontent.com/1751030/117515759-05866080-af4c-11eb-9ee9-a96479f7064e.png)

- LOG OUT
- repeat above steps with Event Administrator role

- LOG OUT

- log in again as Subscriber User
	- visit registration page on frontend
	- [x] confirm that "Public", and "Members Only" tickets are visible

		![ScreenShot_20210506172850](https://user-images.githubusercontent.com/1751030/117515847-4ed6b000-af4c-11eb-9d7c-a3788013ffee.png)

- LOG OUT

	- visit registration page on frontend
	- [x] confirm that only the "Public" ticket is visible

		![ScreenShot_20210506172915](https://user-images.githubusercontent.com/1751030/117515857-526a3700-af4c-11eb-8b48-a68846cd1b6a.png)

**Comment by sethshoultes** [comment]
Tests went well for me.
