### ISSUE TITLE
GDPR Compliance

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/event-espresso-core#342]
This epic is for making EE GDPR-compliant.
Related to discussion http://p2.eventespresso.com/2018/04/19/gdpr-for-ee-plan-not-eventsmart-or-ee-com/

# Phases
## 1. Hook into WP core Systems
Hook into WP core's systems for showing privacy policy, and exporting and anonymizing data

## 2. Supplementary Event Espresso-specific Features
There are a few changes to EE core itself that should be made.

Most of these features can be developed and released independently of each other

**Comment by mnelson4** [comment]
Ok stage 1 is in EE core now. Now it's those other core tickets, add-ons, and then ES (that'll be done in a separate repo) that may need some work

**Comment by joshfeck** [comment]
See also: https://events.codebasehq.com/projects/event-espresso/tickets/11324
and
http://p2.eventespresso.com/2018/01/30/gdpr-for-wp-interface-release-1-0-0/
