### ISSUE TITLE
Table ers doesn't exists

### ISSUE THREAD

**Issue by seball78** [eventespresso/event-espresso-core#3436]
If table prefix is 'plus_', the class EE_Table_Base constructor method is trimming 'plus_users' to 'ers'.

https://github.com/eventespresso/event-espresso-core/blob/8a68549dbb6db29b0a1a7f87b8a8fbe8647b8d14/core/db_models/helpers/EE_Table_Base.php#L58

Should be something like: $table_name = preg_replace('/'.$prefix.'/', '', $table_name, 1);

**Comment by tn3rb** [comment]
Hi  @seball78 

thank you for the issue, and sry for the long delay in responding, simply didn't see this issue 😕 

I'll get a fix out for this today

**Comment by tn3rb** [comment]
plz see #3452
