### ISSUE TITLE
Don't autoload ee_dms_map_Core_4.1.0_events options

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#346]
See original Codebase ticket: https://events.codebasehq.com/projects/event-espresso/tickets/11227

Per Josh:
I was working on a support token where they were having issues with the site going down (largely due to a runaway ee_transient_schedule option and ee_ssn_ transient options). While looking into this I saw that their options table has a number of fairly large autoloading options that store what appears to be information about what was migrated over from EE3. Are these options necessary to autoload on every request? Can they be safely deleted to help speed up a site?

**Comment by mnelson4** [comment]
they certainly don't need to be autoloaded. Changing that for future updates would be a very quick fix

**Comment by joshfeck** [comment]
Fixed in #959
