### ISSUE TITLE
ACF Compatibility - Change Post Type 'show_ee_ui' to 'show_ui'

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#348]
> Hi guys,
> 
> Elliot here - developer of Advanced Custom Fields.
> I just want to let you know of an upcoming change that will affect the compatibility of our plugins.
> 
> Currently, the EE post types (event, venue, contact) show up in the ACF location rules for 'post_type'. This is due to some custom coding from my end to allow '3rd party' post types without the 'show_ui' setting to appear.
> 
> This however, will soon be changing. I will only show post types that have the 'show_ui' setting. Why - Because it makes sense to only connect a field group to a post type that can be edited via UI. This will hide other post types that want to stay hidden.
> 
> To avoid any downtime, I'm adding in a filter and a compatibility layer to keep the current EE post types.
> 
> The filter is called 'acf/get_post_types' and can be used to customize the post types loaded for given $args.
> 
> The compatibility layer hooks into this filter and adds any post types with the 'show_ee_ui' setting.
> 
> I'm asking that we add this compatibility layer (~10 lines of code total) to your plugin as it makes more sense that it should be controlled from your end.
> 
> I intend to remove the compatibility layer from my end in a few months - most likely sometime around May.
> 
> Please let me know when you receive this email so we can chat further, and I can show you the code to add in compatibility.
> 
> Thanks
> Elliot

**Comment by joshfeck** [comment]
@nerrad this is the shim they're using:

https://github.com/AdvancedCustomFields/acf/blob/master/includes/third-party.php#L44

and it sounds like they want that shim in EE instead of in ACF.

**Comment by nerrad** [comment]
@joshfeck I donwloaded the latest ACF and it looks like it's still working on our cpts.  Do we still need to do this?  It looks like Elliot might have relented on removing the shims he has (considering he first reached out over a year ago...)

**Comment by joshfeck** [comment]
They're probably waiting to hear back from us before they'll make that change.

**Comment by nerrad** [comment]
So... do it, or leave it?  I see that we're not the only one still in their `third-party.php` file.  I'm inclined to not do it for now if it's not an issue.

**Comment by sethshoultes** [comment]
I'd say just leave it for now.

**Comment by joshfeck** [comment]
Please add the compatibility shim to EE4. I chatted with Elliot and they're definitely planning to remove the compatibility shim from ACF.
