### ISSUE TITLE
Extract eejs vue library from core and put it into its own public repo

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#351]
@nerrad stated this in Trello: https://trello.com/c/XEZ229rq/498-eejsapi#comment-5ae0b69e8b519e93a4a2a4a1

> So although we won't be investing more time into this eejs vue library I built, again it was time well spent and is recouped in other endeavours. What we may want to do at some point is extract the eejs vue library from core and put it into its own public repo. That way if someone else (or maybe me sometime as part of an ICE project) wants to expand on it to add support for the REST write endpoints it can still happen.

**Comment by joshfeck** [comment]
Dreamhost may have flagged the eejs-api.min.js file because their malware scanners found base64 encoding of the sourcemapping for the file at the end of the file.

https://eventespresso.com/topic/javascript-in-event-express-identified-as-malware/

**Comment by joshfeck** [comment]
Another report:
https://eventespresso.com/topic/deleted-reinstall-plugin-malware/

**Comment by joshfeck** [comment]
Also please note that eejs-api.min.js weighs in at 1.5Mb. Since it's not used anywhere it'd be a quick win to remove for now (save some bandwidth for everyone). Putting this into a public repo could be done later.
