### ISSUE TITLE
Decaf Fixes - 'Transaction Table' not loading on thank you page.

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3519]
Use a paid ticket on #3503 branch

Select Invoice as a payment method, on the thank you page the transaction table doesn't load.

This is what I see on #3503 
https://monosnap.com/file/8TUZAujRBYkQgxHrm5tKLVyCJmNLQs

Master:
https://monosnap.com/file/iS4oUGgrTt1HfIfRQ9FCbs48E3pK11

Tested with EEDECAF set to true and false.

Works as expected if I switch to master

**Comment by tn3rb** [comment]
pushed a fix here sir:
https://github.com/eventespresso/event-espresso-core/commit/a250530f40765a84fa317b128171e9af35c43dad

**Comment by Pebblo** [comment]
That fixed it, Thanks @tn3rb
