### ISSUE TITLE
Fix errant code example on failed migrations page

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#352]
The failed migration page gives this example code to add to the wp-config.php file:

`define( EE_MIGRATION_STEP_SIZE, 10 );`

This needs to be changed to:

`define( 'EE_MIGRATION_STEP_SIZE', 10 );`

**Comment by joshfeck** [comment]
This text should also be changed:

> Your last Database Update had a FATAL ERROR, and CANNOT be continued.

The migration can actually be continued.

**Comment by mnelson4** [comment]
> The migration can actually be continued.
right, more recently we added an option to re-start the migration. What woording would be better?
Maybe "Your last Database Update had a FATAL ERROR, and was stopped."?

**Comment by mnelson4** [comment]
work on **BUG/errant-code-example-for-migrations**

**Comment by joshfeck** [comment]
> "The database update had a fatal error and was halted."

No need for all caps.

**Comment by mnelson4** [comment]
this PR was merged into master 14 days ago
