### ISSUE TITLE
Fatal Error at Checkout

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3525]
Fatal when Proceeding to Registration checkout. Brent thinks an add-on messed up the data.

requires ALL of the add-ons to be active (except AUEN & Barista)

**Comment by manzoorwanijk** [comment]
<b>Fatal error</b>:  Uncaught TypeError: Argument 4 passed to `EED_WP_Users_SPCO::primary_reg_sync_messages()` must be an instance of `EE_SPCO_Reg_Step_Attendee_Information`, instance of `EventEspresso\core\domain\services\registration\form\v1\RegFormQuestionGroup` given, called in /wp-includes/class-wp-hook.php on line 303 and defined in `/wp-content/plugins/eea-wpuser-integration/EED_WP_Users_SPCO.module.php:282`
Stack trace:
- /wp-includes/class-wp-hook.php (303): EED_WP_Users_SPCO::primary_reg_sync_messages('', Object(EE_Registration), Object(EE_Question_Group), Object(EventEspresso\core\domain\services\registration\form\v1\RegFormQuestionGroup))
- /wp-includes/plugin.php(189): WP_Hook->apply_filters('', Array)
- /wp-content/plugins/event-espresso-core/core/domain/services/registration/form/v1/RegFormQuestionGroup.php(12 in <b>/wp-content/plugins/eea-wpuser-integration/EED_WP_Users_SPCO.module.php</b> on line <b>282</b><br>

**Comment by garthkoyle** [comment]
When I disable the WP User plugin, the registration process works again.

**Comment by garthkoyle** [comment]
I'm going to disable that plugin on my testing site for now so I can continue testing.

**Comment by tn3rb** [comment]
lolz... not only was your testing site's version of the WP User addon set to the `master` branch (needs to be on `dev`) but it was also like 13 commits behind.

- fetched latest changes from repo for the WP User addon
- switched branch to `dev`
- activated WP User addon
- performed a test registration

all good now
