### ISSUE TITLE
Ticket Taxes Issue

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3560]
plz see: the "Bundle" Ticket (ID: 187) on this event: https://garth.eventespresso.com/events/edtr-2/
See: https://www.screencast.com/t/skPIAUgN

Notice the inconsistency with the taxes. 

Also, when you checkout, the price is only $10 each.

**Comment by garthkoyle** [comment]
I think this is fine now. What do we do with this ticket, just close it?

![image](https://user-images.githubusercontent.com/3094547/150037037-5d74c8d8-bd40-4625-a26d-d54f93bf2283.png)

**Comment by tn3rb** [comment]
yup thnx for checking that
