### ISSUE TITLE
Add phpcs linting to our build process/automated tests.

### ISSUE THREAD

**Issue by nerrad** [eventespresso/event-espresso-core#357]
## Issue Overview
To aid in our code reviews, I think it'd be beneficial if we automate the code style checks using phpcs geared towards the EE php standards.  That way human reviews can be focused on the syntax/logic of the code, and phpcs will take care of linting for all code style problems in the code.  This can be incorporated with our automated tests on travis so that it shows up there.   We can have it so that the phpcs review is one of the jobs in the builds and that in turn can trigger a fail if the phpcs run fails (indicating code that needs cleaned up before merge).

One difficulty we will experience though is that we still have a lot of legacy files.  This means for a period of time, we will have to apply phpcs exclusion comments to many of the legacy files.  I'll investigate, but there may be a way to provide a configuration file that has all those exclusions in one place.

### Steps to complete:

* [x] Setup phpcs in phpStorm and configure the ruleset to fit our styles/coding standards.
* [x] Figure out a way to exclude certain files from rules that break in legacy code.
* [x] Save the ruleset/configuration to the repo.
* [ ] Replicate that to all our add-ons (adjusting the file exclusions as needed).
* [x] Configure travis builds to run phpcs as one of the jobs.
* [x] Configure our `package.json` file to include phpcs as one of the scripts.

### Time to complete

@sethshoultes I estimate half a day to a full day work to get this implemented.  But its one of those things that will bring much more time savings over time for all our reviews.

**Comment by tn3rb** [comment]
this is a great idea

**Comment by nerrad** [comment]
I'm going to _start_ on this because I have a bunch of tickets blocked by various things at the moment.

**Comment by nerrad** [comment]
I think I'm going to start a package for our phpcs rulesets, that way it can be included as a dependency for core and all our add-ons.  So this will involve adding basic composer support to all codebase as well.

**Comment by nerrad** [comment]
See the new [EventEspressoCS coding standards repository](https://github.com/eventespresso/ee-coding-standards).  So the work in here will consist of adding file exclusions etc to configuration specific to EE (and testing).  Any tweaks for global standards will get done in that new repository.
