### ISSUE TITLE
Build GutenbergBlockManager and supporting classes for locating and loading Gutenberg blocks

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#362]
Codebase ticket: https://events.codebasehq.com/projects/event-espresso/tickets/11400

already need something like this in place to start converting REM over to work with Gutenberg (otherwise the replacement code I write now for REM will just have to be converted **AGAIN** later on)

MVP will be really simple and straightforward as we don't yet know what functionality the various interfaces will require

The pseudo code would be something like:

 - **EE_System** (or similar class) loads **GutenbergBlockManager**
 - GutenbergBlockManager scans a core directory (maybe: `core/services/gutenberg/blocks/`) to return a list of folder names that correspond to EE block loaders and then wraps the resulting array in a filter so that addons can inject paths
 - GutenbergBlockManager then (or at a later hookpoint) loops through those folder paths and grabs files matching a particular naming schema (like: *GutenbergBlockLoader.php), instantiates each class, and adds each service to a collection which restricts what kind of objects can be added
 - GutenbergBlockManager then (or at a later hookpoint) loops through that collection, maybe calls some sort of init() method which would allow blocks the opportunity to set hooks for preventing other blocks from loading (ie: allows addons to override blocks), and then tells each loader to load its corresponding block.
 - each individual GutenbergBlockLoader class would determine whether it should proceed to load its corresponding block or just do nothing because it has been told not to, or because its corresponding block is not valid for the current request.

**Comment by tn3rb** [comment]
copied content of this ticket to 354 and closed in favour of that PR
