### ISSUE TITLE
Infinite Loop When Bulk Deleting Zero Events

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3652]
@marlonhario found the following bug while working on E2E tests for the Events admin:

- go to the Events admin overview tab on trash link 
- select "Delete Permanently" bulk action 
- click apply without selecting any event
- infinite loop of "Identified 0 items for deletion." error messages appears

![bug_1_at_overview_trash](https://user-images.githubusercontent.com/1751030/146241832-4e04c366-4934-48da-a218-39bd0dfd7710.gif)

**Comment by garthkoyle** [comment]
See also #3674

**Comment by tn3rb** [comment]
@hoseinrafiei 

for this issue you will need to poke around in one or more of the following:

- `admin_pages/events/Events_Admin_Page.core.php`
- `core/domain/services/admin/events/data/ConfirmDeletion.php`
- `core/libraries/batch/JobHandlers/PreviewEventDeletion.php`
- `core/domain/services/admin/events/data/ConfirmDeletion.php`
- and/or any of the classes/files related to the above

**Comment by hoseinrafiei** [comment]
This issue is fixed in https://github.com/eventespresso/event-espresso-core/pull/3689 PR.
