### ISSUE TITLE
Convert `[ESPRESSO_MY_EVENTS]` shortcode to Gutenberg block

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#366]
Codebase https://events.codebasehq.com/projects/event-espresso/tickets/11435

**Comment by nerrad** [comment]
Issue moved to [eventespresso/eea-wpuser-integration #9](https://github.com/eventespresso/eea-wpuser-integration/issues/9) via [**ZenHub**](https://www.zenhub.com/)
