### ISSUE TITLE
Date time header status is not updating when changing event status to active

### ISSUE THREAD

**Issue by marlonhario** [eventespresso/event-espresso-core#3678]
The status event at datetimes header is not the same as event banner status, it suppose to be active but datetime header still upcoming.

![image](https://user-images.githubusercontent.com/37426301/149959856-e0ae62f8-a72a-49f8-b8f4-d7ee4cfe4e09.png)

**Comment by tn3rb** [comment]
The Event Status is (in this case "Active") is derived from looking at the datetimes for the event but is still a different thing.
The "Upcoming Dates" heading is just a generic label in the template and does not changes based on the dates.
Would be difficult to change that heading based on the dates, so it's okay as is.
