### ISSUE TITLE
Add Error/Warning Notice When Zero Events Selected for Bulk Deletion

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3690]
In #3689, Hossein applied a quick fix for the recursion issue that was happening when zero events were selected when attempting to bulk delete events (see https://github.com/eventespresso/event-espresso-core/pull/3689/files#r792935378).

This UX should be improved, by returning an error or warning notice that no events were selected. With the quick fix that Hossein added, a user could think that things were successful if they failed to correctly check a box when bulk deleting events.

So in `EventEspressoBatchRequest\JobHandlers\PreviewEventDeletion::continue_job()`: add a new conditional before the others (around line 229) that detects the missing root node (ie: extract Hossein's fix into its own case) and returns an error notice to the user instead of marking the job as complete

**Comment by tn3rb** [comment]
the easiest way to do this is to likely just throw a [RuntimeException](https://www.php.net/manual/en/class.runtimeexception.php) which will then get picked up by `EventEspressoBatchRequest\BatchRequestProcessor::_get_error_response()`

**Comment by hoseinrafiei** [comment]
@tn3rb 

If I throw an exception in the `EventEspressoBatchRequest\JobHandlers\PreviewEventDeletion::continue_job()` function you will see following.

<img width="1627" alt="Screen Shot 2022-05-10 at 17 20 47" src="https://user-images.githubusercontent.com/29144542/167632841-1f8dbe4a-8710-430d-b134-d58a9f5372b7.png">

But we already have an exception for this. I don't know when this is added (Maybe recently) but it does exactly what we're looking for.

<img width="1529" alt="Screen Shot 2022-05-10 at 17 21 56" src="https://user-images.githubusercontent.com/29144542/167632858-20785e1f-dd31-4d54-8f7a-c06acfe68dac.png">

Please check and let me know your feedback.

**Comment by tn3rb** [comment]
hmmm... ok... that exception is coming from `EventEspresso\core\domain\services\admin\events\data\PreviewDeletion::handle()`  but i guess that will do for now. Error handling in the batch processors isn't the greatest is it? 😕 

ok going to scrap this issue then, thnx
