### ISSUE TITLE
Dev UI/Admin Refresh - Remove the Event Status Column in the Event Overview

### ISSUE THREAD

**Issue by garthkoyle** [eventespresso/event-espresso-core#3709]
In the Dev UI updates, can we remove the Status column? There is a row under the event name that helps to communicate the status, and that's sufficient. I don't want to spend the screen real estate on the status.

Horizontal rows are easier to scroll down through than scrolling sideways through vertical columns.
![image](https://user-images.githubusercontent.com/3094547/153058782-e7ad0e7c-2c80-4480-9a5c-e1dc5298e1ac.png)

**Comment by tn3rb** [comment]
done:

<img width="371" alt="Screenshot 2022-02-14 181159" src="https://user-images.githubusercontent.com/1751030/153979415-f11ea9da-7eb5-4df6-83e2-9b02af9de1f5.png">

**Comment by garthkoyle** [comment]
Thank you.

**Comment by tn3rb** [comment]
mesa can closesa now?

**Comment by garthkoyle** [comment]
yes
