### ISSUE TITLE
Dev UI/Admin Refresh - Standardize or Normalize Event Editor Button Spacing

### ISSUE THREAD

**Issue by garthkoyle** [eventespresso/event-espresso-core#3710]
I'd like to see the admin ui buttons to be more consistently spaced. Specifically:

- spacing between buttons
- spacing within the buttons for the appropriate label

Here are the buttons on the Event Overview screen.
![image](https://user-images.githubusercontent.com/3094547/153059384-4ff53522-1ff9-4539-85ca-bbe64add3b81.png)

Notice: 
- the spacing between the buttons looks good and standardized
- the spacing inside the buttons looks good and standardized

Now, look at the dev ui in the event editor:
![image](https://user-images.githubusercontent.com/3094547/153059606-4a4b8194-1d39-481a-9a07-bf45f9d1b85c.png)

Notice:
- the spacing between the buttons is uniform, but different than the Event Overview screen. I like the distance between buttons like we have on the Event Overview Actions screen.
- The spacing between the edge of the words and the edge of the button is not uniform and it makes the big buttons look squished. I'm not sure we can do anything about that.

**Comment by garthkoyle** [comment]
![admin-refresh-buttons](https://user-images.githubusercontent.com/3094547/153072310-3125e3f9-82ca-454a-a659-78e3e325f89a.gif)

**Comment by tn3rb** [comment]
Better?

<img width="653" alt="Screenshot 2022-02-14 180300" src="https://user-images.githubusercontent.com/1751030/153978680-69c5b949-ce61-4a42-ac25-e9baf862c4bd.png">

<img width="653" alt="Screenshot 2022-02-14 180333" src="https://user-images.githubusercontent.com/1751030/153978687-95d2117e-8a13-4867-a739-ac4f722003cc.png">

**Comment by garthkoyle** [comment]
Yes, better! Thanks.

**Comment by tn3rb** [comment]
can close?

**Comment by garthkoyle** [comment]
yes, let's do that now.
