### ISSUE TITLE
Dev UI/Admin Refresh - Event Registration Options Box Input Spacing

### ISSUE THREAD

**Issue by garthkoyle** [eventespresso/event-espresso-core#3711]
The Max number of tickets and the Display TS could use a little spacing between the inputs:

![image](https://user-images.githubusercontent.com/3094547/153071462-23538559-48af-42bf-9716-80d2b4e681fb.png)

**Comment by tn3rb** [comment]
this has been updated recently and fix is live on MENW. can you plz confirm and close if acceptable

example:

<img width="377" alt="Screenshot 2022-03-16 171811" src="https://user-images.githubusercontent.com/1751030/158712319-b6e1a7b8-c8e1-45c5-ad9a-a69fcfaea053.png">
?

**Comment by garthkoyle** [comment]
With a page over 2000px wide, the DRS of `Pending Payment` is not fully visible. It would be good to fix that so people don't have to click to see what it says.

![image](https://user-images.githubusercontent.com/3094547/158733974-40d094af-2a53-4635-a325-d533148f2643.png)

**Comment by tn3rb** [comment]
Fix pushed to MENW, plz confirm

<img width="368" alt="Screenshot 2022-03-31 111634" src="https://user-images.githubusercontent.com/1751030/161123000-9c421c50-1d77-47e1-8207-41690fa1f830.png">

**Comment by garthkoyle** [comment]
Ya, looks better
