### ISSUE TITLE
Admin Refresh/Dev UI - Categories Checkbox Spacing

### ISSUE THREAD

**Issue by garthkoyle** [eventespresso/event-espresso-core#3712]
The categories selector could use some space below the last checkbox:
![image](https://user-images.githubusercontent.com/3094547/153071759-c578b9c6-6d92-48cd-bf5a-48b31b39aed9.png)

**Comment by tn3rb** [comment]
this has been updated recently and fix is live on MENW. can you plz confirm and close if acceptable?

**Comment by Saam01** [comment]
Confirmed, the issue is fixed:
![image](https://user-images.githubusercontent.com/99984614/158745748-95c776b1-5d89-49b7-ae69-be040900e1a4.png)

**Comment by mohdshakeel** [comment]
I tested and confirmed that It's working fine.
![image](https://user-images.githubusercontent.com/1772444/158748033-a3d693db-bfff-43f5-a88a-df7b8dcf3321.png)

**This issue has been fixed.**

**Comment by garthkoyle** [comment]
Thank you for testing. You can close the ticket if the issue is fixed.
