### ISSUE TITLE
Personal information question group can be removed from Primary Registrant questions

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3726]
Found by @mohdshakeel 

Create an event and give it a title.

Check the 'Question Groups for Primary Registrant'.

Notice the 'Personal Information' question group is no longer disabled and CAN be unchecked.

It's checked by default but if you uncheck it and update the event it's removed from the reg form:

https://monosnap.com/file/8a0MhXJ6iS6IOhyelQh2wJRAgGxFly

When the event reloads after saving, Personal Information gets automatically checked again, but it has been unselected from the event. 

Saving again updates the question groups to include it on the event.

**Expected behavior**

Personal info should not be allowed to be unchecked from the Primary Registrant group.

**Comment by Pebblo** [comment]
First report of this on the forum: https://eventespresso.com/topic/first-attendee-information-form-not-being-displayed/?view=all

**Comment by garthkoyle** [comment]
@mohdshakeel Will you double check this? Test to be sure you can not remove the Primary Registrant Personal Information assignment.

**Comment by mohdshakeel** [comment]
I had many run to test and found that issue has been fixed completely. I attached the screenshot to check.
![image](https://user-images.githubusercontent.com/1772444/155279129-d6c56676-a084-48bb-b12a-63c5524fe262.png)

**Comment by garthkoyle** [comment]
Thank you @mohdshakeel
