### ISSUE TITLE
Critical error on demoee (dev branch)

### ISSUE THREAD

**Issue by knazart** [eventespresso/event-espresso-core#3735]
There is a critical error on demoee when we checkout the `dev` branch of EE core.

Here are a few things I have discovered so far...

The error is not being logged for some reason and won't be displayed even with `WP_DEBUG` and `WP_DEBUG_DISPLAY` set to true.

Things I found out with a local install of this site:
- There are a bunch of warnings like:
```
Warning: Unexpected character in input: ' in /srv/www/demoee.test/public_html/wp-content/plugins/event-espresso-core/espresso.php on line 141

Warning: Unexpected character in input: ' in /srv/www/demoee.test/public_html/wp-content/plugins/event-espresso-core/core/services/container/Mirror.php on line 289

Parse error: syntax error, unexpected ' '' in /srv/www/demoee.test/public_html/wp-content/plugins/event-espresso-core/core/EE_Dependency_Map.core.php on line 1104

Notice: is_embed was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 3.1.0.) in /srv/www/demoee.test/public_html/wp-includes/functions.php on line 5768
```

Btw, the "... input: ' in ..." warnings are being fixed by simply opening the file (vim) and saving it without any changes.

- After you fix a few, then there's this:
```
PHP Fatal error:  Declaration of EEH_File::ensure_file_exists_and_is_writable(string $full_file_path = ''): bool must be compatible with EEHI_File::ensure_file_exists_and_is_writable($full_file_path = '') in /srv/www/demoee.test/public_html/wp-content/plugins/event-espresso-core/core/helpers/EEH_File.helper.php on line 25
```

- After I've rest my changes and re-checked out the `dev` branch again I started getting the WSoD locally as well (this wasn't so on the first checkout and pull). And no errors are being logged. Note, master branch still works fine.

**Comment by tn3rb** [comment]
weird... 

here's what I see for that interface on dev branch:

```php
interface EEHI_File
{
    /**
     * ensure_file_exists_and_is_writable
     * ensures that a file exists and is writable, will attempt to create file if it does not exist
     *
     * @param string $full_file_path
     * @throws EE_Error
     * @return bool
     */
    public static function ensure_file_exists_and_is_writable(string $full_file_path = ''): bool;
```

and here's the declaration in `EEH_File`:

```php
    /**
     * ensure_file_exists_and_is_writable
     * ensures that a file exists and is writable, will attempt to create file if it does not exist.
     * Also ensures all the parent folders exist, and if not tries to create them.
     *
     * @param string $full_file_path
     * @return bool
     */
    public static function ensure_file_exists_and_is_writable(string $full_file_path = ''): bool
    {
```

did your local copy get messed up somehow?
maybe nuke the branch and repull.

**Comment by knazart** [comment]
> what pages/routes?

All. Admin and front end.

> did your local copy get messed up somehow?

This was on demoee.org and I simply was able to reproduce. I didn't try nuking the branch, I'll do that.

> no errors are being logged

That's when I'm getting the WSoD. No logs at all.

**Comment by tn3rb** [comment]
remember that with branches that have been rebased, you can not simply "pull" in the changes because the history has been rewritten.
you need to delete the branch and check it out again

**Comment by tn3rb** [comment]
is this error still happening?

**Comment by knazart** [comment]
Looks like dev branch works now.

**Comment by tn3rb** [comment]
kk going to close this, thnx
