### ISSUE TITLE
Apply WP_KSES() to ALL Unescaped Output

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3738]
According to the ppl at wp.org, the following template (example) is a horrible security issue:

```php
<div class="container">
	<h4><?php echo $title;?></h4>
	<p><?php echo $text ;?></p>
	<p><?php echo $button;?></p>
</div>
```

because those variables are NOT being escaped upon echoing, despite them being sanitized before being passed to the template, like:

```php
$title = esc_html__('some title', 'ee');
$text = esc_html__('some paragraph text', 'ee');
$button = '<a class="button" href="' . esc_url_raw($url) . '">' . esc_html__('click me', 'ee') . '</button>';
```

No amount of reasoning is acceptable to them.

So in order to satisfy the ppl at wp.org, we need to apply `wp_kses()` to ALL echoed content that is not already being escaped, regardless of whether the content has been _previously_ escaped prior to appearing in the template. It's possible that we may have to undo some of the other escaping as well.

For the example above, we would have to change the template to be something like:

```php
<div class="container">
	<h4><?php echo wp_kses($title);?></h4>
	<p><?php echo wp_kses($text) ;?></p>
	<p><?php echo wp_kses($button);?></p>
</div>
```

(just to be 100% clear, if an echoed variable is already being escaped via another function like one of the  `esc_attr()` or `esc_html()` variations, then that does not need to have `wp_kses()` applied.)

In cases, where more complex tags and attributes are required, we can grab one of the global `$allowed_tags` variables (or use `wp_kses_allowed_html()`) and pass that as the second parameter to `wp_kses()`.

For cases where we need an even _MORE_ complex set of allowed tags and attributes, I have created the `EventEspresso\core\services\request\sanitizers\AllowedTags` class that can be used for building a hardcoded list of tags and attributes that can be easily referenced like so:

```php
// at top of file:
use EventEspresso\core\services\request\sanitizers\AllowedTags;

// in code
$allowed_tags = AllowedTags::getAllowedTags();
wp_kses($html, $allowed_tags );
```

but I'm open to variations on that particular usage.  For example, maybe we don't want to have one accessor for ALL tags and instead want to break things up like:

```php
AllowedTags::getAll();

AllowedTags::getButtonTags();

AllowedTags::getMessageContainerTags();
```

i dunno, whatever... just saying that i'm not opposed to getting granular with the hard coded tags if we need to.

### ANYWAYS...

For ALL work done towards this issue, plz create a new PR for each major section of the codebase. For example, the files within `admin_pages/about/templates` could be done in a single PR since there are only 5 files in that folder, or maybe even ALL of the files within `admin_pages/about` since there are only a couple more that are not templates.  I don't want to place any hard rules on how many files to include in each PR because 10 small templates may have far less lines of code than 1 huge template, so basically just play it be ear. Just be reasonable, and don't do too much at once.

### IMPORTANT !!!

It may not be obvious what content is being output through template variables because of WordPress filtering. So it is imperative that you find and identify what variables are being processed by `wp_kses()` BEFORE doing so, in order to identify what tags and attributes you will need to allow. Failure to do so could strip out critically important attributes, especially if they are being used for JS. As well, we need to know what variables are being modified so that support can verify that things are working, especially with add-ons or any common gists that customers may use.  To facilitate this, I would also like you to include screenshots of any affected DOM elements so that support knows exactly what to test. for example, something like:

![Ticket Sale Info](https://user-images.githubusercontent.com/1751030/155055641-207ca8a1-cf2f-45cc-9b44-2b980fd05981.png)

Images can be uploaded into a GitHub post simply by dragging and dropping into the same text box you type comments into, so plz don't upload screenshots to some third party site that we have to click on to go visit and deal with whatever nonsense there (cookies, ads, etc). I don't care how exactly you format or markup your screenshots as long as support can figure out quickly what they need to test.

**Comment by tn3rb** [comment]
# FILES LIST

# admin_pages
## about
- templates
  - [] credits.template.php
  - [] decafvpro.template.php
  - [] ee4-overview.template.php
  - [] reviews.template.php
  - [] whats_new.template.php
- [] About_Admin_Page.core.php
- [] About_Admin_Page_Init.core.php

## events
- form_sections
  - [] ConfirmEventDeletionForm.php
- help_tabs
  - [] event_editor.help_tab.php
  - [] event_editor_event_datetimes.help_tab.php
  - [] event_editor_event_registration_options.help_tab.php
  - [] event_editor_event_tickets.help_tab.php
  - [] event_editor_other.help_tab.php
  - [] event_editor_questions_registrants.help_tab.php
  - [] event_editor_save_new_event.help_tab.php
  - [] event_editor_tags_categories.help_tab.php
  - [] event_editor_title_richtexteditor.help_tab.php
  - [] event_editor_venue_details.help_tab.php
  - [] events_add_category.help_tab.php
  - [] events_categories.help_tab.php
  - [] events_categories_other.help_tab.php
  - [] events_categories_table_column_headings.help_tab.php
  - [] events_categories_views.help_tab.php
  - [] events_default_settings.help_tab.php
  - [] events_default_settings_max_tickets.help_tab.php
  - [] events_default_settings_status.help_tab.php
  - [] events_edit_category.help_tab.php
  - [] events_import.help_tab.php
  - [] events_overview.help_tab.php
  - [] events_overview_filters.help_tab.php
  - [] events_overview_other.help_tab.php
  - [] events_overview_table_column_headings.help_tab.php
  - [] events_overview_views.help_tab.php
  - [] general_settings_templates.help_tab.php qtips 
- qtips
  - [] EE_Event_Editor_Decaf_Tips.lib.php templates
- templates
  - [] event_category_details.template.php
  - [] event_preview_deletion.template.php
  - [] event_publish_box_extras.template.php
  - [] event_registration_options.template.php
  - [] event_settings.template.php
  - [] event_tickets_metabox_main.template.php
  - [] event_tickets_metabox_ticket_row.template.php
  - [] new_price_layout.template.php 
- [] Event_Categories_Admin_List_Table.class.php
- [] Events_Admin_List_Table.class.php 
- [] Events_Admin_Page.core.php 
- [] Events_Admin_Page_Init.core.php

## general_settings
- help_tabs
  - [] general_settings_admin_options.help_tab.php
  - [] general_settings_countries.help_tab.php
  - [] general_settings_critical_pages.help_tab.php
  - [] general_settings_your_organization.help_tab.php
- templates
    - [] countries_settings.template.php
    - [] country_details_settings.template.php
    - [] espresso_page_settings.template.php
    - [] state_details_settings.template.php
- [] AdminOptionsSettings.php 
- [] General_Settings_Admin_Page.core.php
- [] General_Settings_Admin_Page_Init.core.php 
- [] OrganizationSettings.php

## messages
- help_tabs
  - [] messages_overview.help_tab.php
  - [] messages_overview_filters.help_tab.php
  - [] messages_overview_messengers.help_tab.php
  - [] messages_overview_other.help_tab.php
  - [] messages_overview_table_column_headings.help_tab.php
  - [] messages_overview_types.help_tab.php
  - [] messages_overview_views.help_tab.php
  - [] messages_preview.help_tab.php
  - [] messages_settings.help_tab.php
  - [] messages_settings_message_types.help_tab.php
  - [] messages_settings_messengers.help_tab.php
  - [] messages_templates.help_tab.php
- qtips
    - [] EE_Message_List_Table_Tips.lib.php
- templates
    - [] ee_msg_details_main_add_meta_box.template.php
    - [] ee_msg_details_main_edit_meta_box.template.php
    - [] ee_msg_details_messenger_meta_box.template.php
    - [] ee_msg_details_messenger_mt_meta_box.template.php
    - [] ee_msg_details_mt_settings_tab_item.template.php
    - [] ee_msg_details_sidebar_edit_meta_box.template.php
    - [] ee_msg_editor_active_context_element.template.php
    - [] ee_msg_m_settings_content.template.php
    - [] ee_msg_message_templates_help_tab.template.php
    - [] ee_msg_message_type_help_tab.template.php
    - [] ee_msg_messages_help_tab.template.php
    - [] ee_msg_messages_settings_help_tab.template.php
    - [] ee_msg_messages_shortcodes_help_tab.template.php
    - [] ee_msg_messages_templates_editor_help_tab.template.php
    - [] ee_msg_messenger_help_tab.template.php
    - [] ee_msg_mt_settings_content.template.php
    - [] ee_msg_overview_help_tab.template.php
    - [] ee_msg_preview_help_tab.template.php
    - [] shortcode_selector_skeleton.template.php
    - [] template_pack_and_variations_metabox.template.php 
    - [] EE_Message_List_Table.class.php
    - [] espresso_events_Messages_Hooks.class.php
    - [] Messages_Admin_Page.core.php
    - [] Messages_Admin_Page_Init.core.php
    - [] Messages_Template_List_Table.class.php

**Comment by garthkoyle** [comment]
Here is the checklist that we can use for testing. Duplicate this list each round of testing: https://trello.com/c/HLAuS4LP/1140-ee4-master-testing-checklist-decaf

**Comment by hoseinrafiei** [comment]
@tn3rb Would you please complete the files list?

**Comment by tn3rb** [comment]
@hoseinrafiei 

Here's what I found after searching for "`echo $`":
(numbers are line numbers)

### Usage in code

- \core\
    - EE_Addon.core.php
        - [ ] 867 echo $after_plugin_row;
    - EE_Error.core.php
        - [ ] 110 echo $type . ': ' . $message . '<br />' . $file . ' line ' . $line;
        - [ ] 477 echo $output;

- \core\admin\
    - EE_Admin_List_Table.core.php
        - [ ] 471 echo $filter; // already escaped
        - [ ] 752 echo $this->handle_row_actions($item, $column_name, $primary);
        - [ ] 763 echo $this->handle_row_actions($item, $column_name, $primary);
        - [ ] 781 echo $this->_get_hidden_fields(); // already escaped
        - [ ] 788 echo $this->_admin_page->get_action_link_or_button(
    - EE_Admin_Page.core.php
        - [ ] 1595 echo $content; // already escaped
        - [ ] 1671 echo $content; // already escaped
        - [ ] 2282 echo $pre . $output . $post; // already escaped
        - [ ] 2286 echo $pre . $loading . $post; // already escaped
    - EE_Admin_Page_CPT.core.php
        - [ ] 1355 echo $html;  // already escaped
        - [ ] 1487 adminpage = '<?php echo $admin_page; ?>';

- \core\exceptions\
    - ExceptionStackTraceDisplay.php
        - [ ] 80 echo $styles, $output, $scripts; // already escaped

- \core\helpers\
    - EEH_Debug_Tools.helper.php
        - [ ] 410 echo $result;
        - [ ] 597 echo $result;
    - EEH_Line_Item.helper.php
        - [ ] 1579 echo $line_item->name();

- \core\libraries\iframe_display\
    - Iframe.php
        - [ ] 283 echo $this->getTemplate(); // already escaped
    - iframe_wrapper.template.php
        - [ ] 32 <?php echo $eei18n; ?>
        - [ ] 36 <script type="text/javascript" src="<?php echo esc_url_raw($url); ?>"<?php echo $header_attributes; ?>></script>
        - [ ] 41 <?php echo $notices; // already escaped ?>
        - [ ] 43 <?php echo $content; // already escaped ?>
        - [ ] 47 <script type="text/javascript" src="<?php echo esc_url_raw($url); ?>"<?php echo $footer_attributes; ?>></script>
    - IframeEmbedButton.php
        - [ ] 136 echo $this->embedButtonHtml(); // already escaped

- \core\libraries\messages\defaults\default\
    - email_main_wrapper.template.php
        - [ ] 24 <?php echo $main_body; // already escaped ?>
    - email_preview_wrapper.template.php
        - [ ] 3 <?php echo $main_body; // already escaped ?>
    - html_main_wrapper.template.php
        - [ ] 46 <?php echo $main_body; // already escaped ?>

- \core\libraries\messages\messenger\
    - EE_Html_messenger.class.php
        - [ ] 476 echo $this->_get_main_template(); // already escaped

- \core\third_party_libs\dompdf\lib\
    - Cpdf.php
        - [ ] 3906 echo $tmp;

- \core\third_party_libs\dompdf\src\
    - Dompdf.php
        - [ ] 851 echo $msg . "\n";
        - [ ] 855 echo $canvas->get_cpdf()->messages;
    - Helpers.php
        - [ ] 514 echo $errstr . "\n";
    - Renderer.php
        - [ ] 62 echo $frame;

- \core\third_party_libs\dompdf\src\Adapter\
    - CPDF.php
        - [ ] 1154 echo $tmp;
    - PDFLib.php
        - [ ] 1339 echo $data;

- \core\third_party_libs\pue\
    - pue-client.php
        - [ ] 516 <?php echo $this->_error_msg; ?>
        - [ ] 1235 <?php echo $this->_sanitize_notices($errors); ?>
        - [ ] 1251 <?php echo $this->_sanitize_notices($attentions); ?>
        - [ ] 1267 <?php echo $this->_sanitize_notices($successes); ?>
        - [ ] 1295 echo $content;
        - [ ] 1478 id="pu_dashboard_message"><?php echo $this->_sanitize_notices($msg); ?>
        - [ ] 1497 echo $content;
        - [ ] 1623 echo $content;

- \modules\ical\
    - EED_Ical.module.php
        - [ ] 210 echo $key . ':' . $value . "\r\n";

- \modules\single_page_checkout\
    - EED_Single_Page_Checkout.module.php
        - [ ] 1754 echo $json_response;

- \modules\single_page_checkout\inc\
    - EE_SPCO_JSON_Response.php
        - [ ] 414 echo $this;

- \vendor\nikic\php-parser\grammar\
    - rebuildParsers.php
        - [ ] 78 echo $output;

- \vendor\squizlabs\php_codesniffer\src\
    - Config.php
        - [ ] 1335 echo $usage;
    - Reporter.php
        - [ ] 244 echo $generatedReport;
        - [ ] 249 echo $generatedReport;
    - Ruleset.php
        - [ ] 278 echo $sniffList;
    - Runner.php
        - [ ] 131 echo $e->getMessage();
        - [ ] 206 echo $e->getMessage();
        - [ ] 749 echo $debugOutput;

- \vendor\squizlabs\php_codesniffer\src\Generators\
    - HTML.php
        - [ ] 46 echo $content;
    - Markdown.php
        - [ ] 40 echo $content;
        - [ ] 115 echo $content.PHP_EOL;
    - Text.php
        - [ ] 220 echo $firstLineText.str_repeat(' ', (46 - strlen($firstLineText)));
        - [ ] 222 echo $secondLineText.str_repeat(' ', (47 - strlen($secondLineText)));
        - [ ] 242 echo $firstLineText.str_repeat(' ', max(0, (47 - strlen($firstLineText))));
        - [ ] 244 echo $secondLineText.str_repeat(' ', max(0, (48 - strlen($secondLineText))));

- \vendor\squizlabs\php_codesniffer\src\Reports\
    - Cbf.php
        - [ ] 113 echo $report['filename'].">>$errorCount>>$warningCount>>$fixableCount>>$fixedCount".PHP_EOL;
        - [ ] 195 echo $file.str_repeat(' ', $padding).'  ';
        - [ ] 205 echo $data['fixed'];
        - [ ] 212 echo $remaining;
    - Checkstyle.php
        - [ ] 67 echo $out->flush();
        - [ ] 103 echo $cachedData;
    - Code.php
        - [ ] 169 echo $file;
        - [ ] 303 echo $errorMsg.PHP_EOL;
        - [ ] 353 echo $cachedData;
    - Csv.php
        - [ ] 86 echo $cachedData;
    - Diff.php
        - [ ] 89 echo $diff.PHP_EOL;
        - [ ] 122 echo $cachedData;
    - Emacs.php
        - [ ] 48 echo $report['filename'].':'.$line.':'.$column.': '.$type.' - '.$message.PHP_EOL;
        - [ ] 85 echo $cachedData;
    - Full.php
        - [ ] 87 echo $file;
        - [ ] 174 echo $errorMsg.PHP_EOL;
        - [ ] 222 echo $cachedData;
    - Junit.php
        - [ ] 79 echo $out->flush();
        - [ ] 125 echo $cachedData;
    - Notifysend.php
        - [ ] 100 echo $report['filename'].PHP_EOL;
    - Source.php
        - [ ] 59 echo $source.'>>'.$data['fixable'].'>>'.$data['count'].PHP_EOL;
        - [ ] 211 echo $source;
        - [ ] 224 echo $parts[0].str_repeat(' ', (10 - strlen($parts[0])));
        - [ ] 231 echo $category.str_repeat(' ', (20 - strlen($category)));
        - [ ] 239 echo $sniff.str_repeat(' ', ($width - 39 - strlen($sniff)));
        - [ ] 241 echo $sniff.str_repeat(' ', ($width - 35 - strlen($sniff)));
        - [ ] 245 echo $sourceData['count'].PHP_EOL;
    - Summary.php
        - [ ] 43 echo $report['filename'].'>>'.$report['errors'].'>>'.$report['warnings'].PHP_EOL;
        - [ ] 134 echo $file.str_repeat(' ', $padding).'  ';
    - VersionControl.php
        - [ ] 278 echo $line.PHP_EOL;
        - [ ] 312 echo $source;
        - [ ] 319 echo $line.PHP_EOL;
    - Xml.php
        - [ ] 84 echo $content;
        - [ ] 120 echo $cachedData;

- \vendor\squizlabs\php_codesniffer\src\Tokenizers\
    - CSS.php
        - [ ] 129 echo $cleanContent.PHP_EOL;



### Usage in comments
plz just remove the commented out code

\core\third_party_libs\dompdf\lib\html5lib\
    - Tokenizer.php
        - [ ] 135 /*echo $state . ' ';
    - TreeBuilder.php
        - [ ] 185         echo $this->strConst($mode);

- \core\third_party_libs\dompdf\src\Css\
    - Stylesheet.php
        - [ ] 1197             echo $style;

- \core\third_party_libs\dompdf\src\FrameDecorator\
    - AbstractFrameDecorator.php
        - [ ] 893 //echo $this->_frame; flush();

- \modules\gateways\Invoice\lib\templates\
    - invoice_body.template.php
        - [ ] 226                 <td class="item_l"><?php echo $registration->event_name() ?></td>
        - [ ] 227                 <td class="item_l"><?php echo $registration->ticket()->name() ?></td>
        - [ ] 229                 <td class="item_l"><?php echo $registration->attendee()->full_name() ?></td>
        - [ ] 283 <?php // echo $discount; ?>
    - receipt_body.template.php
        - [ ] 167 <?php // echo $is_percent ? '' : $sub_line_item->quantity()?>
        - [ ] 445 <?php // echo $discount; ?>

**Comment by hoseinrafiei** [comment]
@tn3rb

I believe we don't need to (and shouldn't) touch files in `/vendor` directory.
There are two instances on `/modules` directory that are for printing JSON encode which we don't need to escape them.
Moreover, there are some variables of dompdf under `/core/third_party_libs/` directory which we don't need to change them since they're not for HTML and also because they're related to a third party package.

Only a few of variables are remaining now. A few of them are under `pue` directory which has javascript codes combined.
And some of them are for whole page including doctype, html, head, meta, style, script and some other tags which we shouldn't escape because some part of the page would remove. For example one of the variables under `iframe` directory.

Please let me know your feedback on this.

**Comment by tn3rb** [comment]
> I believe we don't need to (and shouldn't) touch files in /vendor directory.

oh ya that makes sense... i generated that list of files dynamically and obviously didn't go through the entire list

> There are two instances on /modules directory that are for printing JSON encode

might have to use your `echo ($var); trick then so that WP doesn't detect those

> there are some variables of dompdf under /core/third_party_libs/ directory

we are bundling those so I'm assuming that WP core will consider that part of our plugin, so we'll need to address those just like the rest of our code

> A few of them are under pue directory 
> some of them are for whole page

might have to use your `echo ($var); trick there as well if possible. Some of the arguments i had with WP core regarding this issue were lines of code where a variable was clearly sanitized in the same block of code but they still wanted it escaped. ex:

```php
$ID = absint( $ID );
// one or two lines of other code
echo $ID:
```

*obviously* does not need escaping because `$ID` can NOT be anything other than an integer, but the WP core ppl did NOT care and insisted that that HAD to be escaped. So we unfortunately have to play by their rules and escape EVERYTHING even when it is totally stupid and/or insane to do so, OR we need to figure out a way to output a sanitized variable without them detecting that it has not also been escaped.
