### ISSUE TITLE
Move EDTR Admin Option Loading

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3756]
Basic Plan users on MENW don't have access to the option for enabling the EDTR:

<img width="1021" alt="Screenshot 2022-03-07 132446" src="https://user-images.githubusercontent.com/1751030/157123995-08b15fe4-dcca-4900-8a0f-bcd0fe912475.png">

because (assumption) `AdvancedEditorAdminFormSection` is being loaded via `Extend_Events_Admin_Page`

need to switch things around so that it is loaded via `Events_Admin_Page`

**Comment by tn3rb** [comment]
@garthkoyle can you plz verify this is working as expected now?

**Comment by garthkoyle** [comment]
Confirmed the option is available for free plan users https://github.com/eventespresso/eventsmart.com-website/issues/915#issuecomment-1063431027
