### ISSUE TITLE
Pricing Description Includes Extra Spaces

### ISSUE THREAD

**Issue by garthkoyle** [eventespresso/event-espresso-core#3764]
Testing on MENW which is currently on `dev`: https://www.screencast.com/t/F7ISRRS8LdZt
<img width="720" alt="image" src="https://user-images.githubusercontent.com/3094547/157732063-1bb6bd68-036b-4f71-82a2-ca7fc759f30d.png">

**Comment by tn3rb** [comment]
fix has been pushed to MENW, plz confirm

**Comment by Saam01** [comment]
Confirmed, this issue is fixed: https://www.awesomescreenshot.com/video/7930316?key=02aa46f69fe482ee9fccba2d451440d2

![image](https://user-images.githubusercontent.com/99984614/158744800-2279b135-1a3e-409e-a9a1-298c4988fb25.png)

**Comment by mohdshakeel** [comment]
I tested and found that Issue has been fixed.

![image](https://user-images.githubusercontent.com/1772444/158779371-31f887e0-ea9c-4e2d-ac25-f4e2a1e8991b.png)

**RESOLVED**  **RESOLVED**  **RESOLVED**

**Comment by garthkoyle** [comment]
Thank you for testing. You can close the ticket if the issue is fixed.
