### ISSUE TITLE
Modify CSV Report to Clarify Check-in Data (see Gist)

### ISSUE THREAD

**Issue by garthkoyle** [eventespresso/event-espresso-core#3770]
Can we add this to core so that people can get the per-datetime check in/out data?

https://gist.github.com/joshfeck/4a8ea5b02855ebd4d7cc720dd6112d5f

**Comment by hoseinrafiei** [comment]
@garthkoyle 
I added these columns in the https://github.com/eventespresso/event-espresso-core/pull/3808 PR.
