### ISSUE TITLE
4.10.30.rc.003, Tickets Disappear after Updating Event

### ISSUE THREAD

**Issue by garthkoyle** [eventespresso/event-espresso-core#3773]
Reported here: https://secure.helpscout.net/conversation/1823527592/895201?folderId=100617

When you add tickets to an event, the tickets disappear after you update an event.

On Demoee.org, I saw that when I clicked the `add ticket` button, I get these jquery errors:
![image](https://user-images.githubusercontent.com/3094547/159802321-fefd9514-412c-45cb-a79b-75055ac594ce.png)

I can reproduce this on garth.eventespresso.com with ONLY core installed.

I can also reproduce this locally with ONLY core installed. I also get a second jquery error when adding a price.

![image](https://user-images.githubusercontent.com/3094547/159802423-6a40f3b3-58e8-4f84-a596-74265828d34a.png)

**Comment by tn3rb** [comment]
bug was introduced in https://github.com/eventespresso/event-espresso-core/pull/3740

**Comment by hoseinrafiei** [comment]
@garthkoyle @tn3rb 

I just fixed the issue in the https://github.com/eventespresso/event-espresso-core/pull/3771 branch.
The issue was created due to mis-using `sanitize_text_class` function and using `absint` instead of `esc_attr` for non numeric variables.
