### ISSUE TITLE
Trashed any question group. It is still visible at front end. 

### ISSUE THREAD

**Issue by mohdshakeel** [eventespresso/event-espresso-core#3793]
**Describe the bug**

KSES - PART 3 https://github.com/eventespresso/event-espresso-core/pull/3778
When I trash any question group. It is still visible at front end. We need to update the event to remove it completely from front end.

Trashed Questions group should not be display at front event page.

If we have 100 events then we need to update the each event one by one to hide the trashed question group from front end.
**To Reproduce**

**Expected behavior**

**Screenshots**

I am using the extra information question group. I trashed it. But It is still displayed at front end. I need to go at edit event page and uncheck this question group & update event .
![image](https://user-images.githubusercontent.com/1772444/161570615-7ce143b1-f33b-4f2d-ae49-328b22496f4b.png)

![image](https://user-images.githubusercontent.com/1772444/161571648-8460403d-3bda-4189-9141-b1eb78f11004.png)

**Environment:**
 - Version of Event Espresso:  
 - Version of WordPress: 
 - Browser 
 - PHP Version 

**Additional context**

**Comment by hoseinrafiei** [comment]
I did following steps:

1- Created couple of custom questions.
2- Added a question group and assigned newly created questions to the created question group.
3- Modified some events and enabled new question group for them.
4- Trashed the question group.
4- Tried to permanently delete the question group but faced following error:

    This Question Group is currently linked to one or more Event to Question Group Link records. If this Question Group is incorrect, then please remove it from all Event to Question Group Links before attempting to delete it.

<img width="1394" alt="Screen Shot 2022-04-13 at 18 29 43" src="https://user-images.githubusercontent.com/29144542/163197470-80a66296-3826-4112-91ea-0e1463982fac.png">

Therefore, I believe it designed this way and it's not an issue.
