### ISSUE TITLE
Fix EEH_Event_Query orderby parameters returning empty string

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3795]
This has been reported in relation to the table view template add-on but I tracked it down to core, so adding this to core for now.

Easiest way to reproduce is using the table view template and setting the order_by parameter to use `event_name`:

`[ESPRESSO_EVENTS_TABLE_TEMPLATE order_by=event_name]`

The output will be the default order by which uses start_date.

Tracked this down to [HERE](https://github.com/eventespresso/event-espresso-core/blob/master/core/helpers/EEH_Event_Query.helper.php#L183)

It returns an empty string and I think it is because `event_query_orderby` is an array with a single string element.

If I switch line 185 to be:

`$event_query_orderby = self::getRequest()->getRequestParam('event_query_orderby', $orderby, 'string');`

It works but wasn't sure if the other calls to getRequestParam needed the same change and/or if it would cause issues with other code using that class?

**Comment by joaovictorangeline** [comment]
Ticket to reply to customer when it's closed: https://eventespresso.com/topic/espresso-event-table-order_by-not-working/
