### ISSUE TITLE
I cant add the new question group

### ISSUE THREAD

**Issue by mohdshakeel** [eventespresso/event-espresso-core#3798]
KSES- 5 BUG - I tried to add new question group but I am getting this error.
![image](https://user-images.githubusercontent.com/1772444/162928582-c6d3ecc0-6974-4e5e-b16b-f0199d28b15c.png)

**Comment by mohdshakeel** [comment]
I tested and confirm with master. Everything is working perfect.

**Comment by hoseinrafiei** [comment]
@mohdshakeel Thanks for finding this.
It was a general issue so I fixed by creating a new branch.
