### ISSUE TITLE
Backend Registration not working.

### ISSUE THREAD

**Issue by Saam01** [eventespresso/event-espresso-core#3804]
Getting error while registering in the backend in kses-2: 

https://user-images.githubusercontent.com/99984614/163602122-3b25aa2c-3433-40e0-b2dd-bb1af797a7f2.mp4

**Comment by garthkoyle** [comment]
I'll test this now.

**Comment by garthkoyle** [comment]
@Saam01 what branch were you testing?

**Comment by Saam01** [comment]
@garthkoyle  I am testing on **kses-2** with **decaf disabled**. 

Testing for this PR: https://github.com/eventespresso/event-espresso-core/pull/3803#issuecomment-1100061514

**Comment by garthkoyle** [comment]
@Saam01 are you testing some kses-2 site or that branch? kses-2 branch has been merged. 

Please explain yourself.

**Comment by Saam01** [comment]
It is mentioned here to test the KSES-2 branch: https://trello.com/c/bml8JS9m/1156-ee4-core-testing-checklist-pr-3803

https://prnt.sc/upgmCfqtTmqe
