### ISSUE TITLE
Remove reCAPTCHA challenge from SPCO re-visit

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#381]
A reCAPTCHA challenge is triggered when you try to pay. Is this wanted? I took a screencapture video that shows the issue along with a strange message added by the promotions add-on (you'll need to be logged into Slack to see the video).

https://eventespresso.slack.com/files/U03SRJ08M/FAHPU5FB6/recaptcha_issue.mov

**Comment by sethshoultes** [comment]
@joshfeck is this still an issue?

**Comment by joshfeck** [comment]
Yes this is still an issue.

To replicate: Activate Invisible reCAPTCHA and select the option to enable Invisible reCAPTCHA on the Registration Form. Also activate the Promotions add-on.

**Comment by tn3rb** [comment]
## questions

- do we want this turned off for revisits to **any** reg step (ie: attendee info AND payment options), or just for the payment options reg step?

## required steps and estimates

- (1 hour) add filter to `EE_SPCO_Reg_Step_Payment_Options::set_hooks()` similar to one currently using the`EE_SPCO_Reg_Step_Payment_Options::bypass_recaptcha_for_load_payment_method()` callback 
- (1 hour) add `set_hooks()` method to `EE_SPCO_Reg_Step_Attendee_Information` plus filter and callback similar to above
