### ISSUE TITLE
KSES 8 Edit Question Group - Active question checkbox is not displaying as checked. That create a confusion.

### ISSUE THREAD

**Issue by mohdshakeel** [eventespresso/event-espresso-core#3810]
Edit Question group - Check any question and save. Its displaying at front end and while It is unchecked at backend. Its confusing. This issue does not come in master branch.
KSES 8 #3806 

MASTER BRANCH

![image](https://user-images.githubusercontent.com/1772444/164386393-309892aa-2dff-449a-980e-9a473140a179.png)

 KSES 8 BRANCH

![image](https://user-images.githubusercontent.com/1772444/164386604-76c3ff36-0c54-44b6-9558-237f208eda50.png)

**Comment by hoseinrafiei** [comment]
@mohdshakeel 
Please update `fix/kses-8` branch and re-check this issue. It should be fixed now.
To update the branch you just need run following commands.

```
git checkout fix/kses-8
git pull
```

**Comment by mohdshakeel** [comment]
Thanks, Its working fine.
