### ISSUE TITLE
PHP8: Deprecated and Warnings at the plugin activation

### ISSUE THREAD

**Issue by joaovictorangeline** [eventespresso/event-espresso-core#3815]
**Describe the bug**
A lot of Deprecated and Warnings are displayed when Event Espresso is activated. I saved the HTML page since there are a lot of different deprecated and warnings: https://file.io/q6HZ5iTicWTa

**To Reproduce**

**Expected behavior**
No Deprecated and warnings on the Dashboard.

**Screenshots**
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/102395051/165804133-bcd65ffd-ffb6-4656-a29c-75a50fa68745.png">

**Environment:**
- Web Server: Apache/2.4.43 (Unix)
 - Version of Event Espresso:  4.12.0.rc.001
 - Version of WordPress: 5.9.3
 - Browser Chrome Version 100.0.4896.127 (Official Build) (arm64)
 - PHP Version 8.0.0 (Supports 64bit values)

**Comment by garthkoyle** [comment]
Confirmed.

When you refresh the page, the notices disappear and the menu is displayed.

**Comment by tn3rb** [comment]
fixed in #3522

**Comment by garthkoyle** [comment]
#3522 was merged to master, so I tested this with master branch and PHP 8. No errors.
