### ISSUE TITLE
No gear icon loading the "Registration" page.

### ISSUE THREAD

**Issue by joaovictorangeline** [eventespresso/event-espresso-core#3869]
**Describe the bug**
There is no gear icon or message displayed when we go through the Registration steps. 

**To Reproduce**
1. Make sure to have the Event Espresso 4.10.30
2. Register for an event
3. Notice there are no gear icons or messages while the page is loading (what is present on 4.10.29)

**Expected behavior**
A "loading" icon should appear just to indicate that the visitor needs to wait for something to happen. Currently, the visitors think the page is not working after the button is clicked.

**Screenshots**
Event Espresso 4.10.29: It's possible to view a message when we finish the registration, but it's displayed too fast. 
**https://share.cleanshot.com/pX8iWr**

Event Espresso 4.10.30: Nothing is displayed.

**Environment:**
 - Version of Event Espresso:  4.10.30.rc.026
 - Version of WordPress: 6.0
 - Browser: Chrome (Version 101.0.4951.64 (Official Build) (arm64))
 - PHP Version: 7.4.1

**Comment by joaovictorangeline** [comment]
Related ticket:
https://eventespresso.com/topic/form-registration-no-submission-progress-indicator-failed-registrations/

**Comment by tn3rb** [comment]
@joaovictorangeline can you check this again plz?
I just test latest master (version `4.10.31.rc.004`) and this appears to be fixed.
May have been fixed by https://github.com/eventespresso/event-espresso-core/pull/3819

**Comment by joaovictorangeline** [comment]
It's working fine on 4.10.31 @tn3rb!
