### ISSUE TITLE
Add Session Lifespan Admin Option

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3871]
The Session Lifespan controls how long the EE user sessions remain active on the frontend of a website during the registration process. Currently this value defaults to 1 hour and can only be controlled via a filter. This has worked fine for EE plugin users but does not work for Event Smart users as they have no ability to add filters. 

for additional background, plz see: https://github.com/eventespresso/eventsmart.com-website/issues/984 

- create new class `EventEspresso\core\domain\values\session\SessionLifespanOption`
	- have `SessionLifespanOption` extend `EventEspresso\core\services\database\WordPressOption` (search for other classes that do the same for examples)
	- set an appropriately named constant for the option name 
	- add an appropriately named setter and getter (with validation) for value
	- set default value to `(int) HOUR_IN_SECONDS`

- in constructor for `EventEspresso\core\domain\values\session\SessionLifespan`
	- replace ternary checking `$lifespan` and setting default of 1 hour with if conditional
	- if `$lifespan` is not set, instantiate `SessionLifespanOption` 
	- get default value for `$lifespan`  from `SessionLifespanOption` 

- open `caffeinated/admin/extend/registration_form/Extend_Registration_Form_Admin_Page.core.php` 
	- look at `_reg_form_settings()` and `_update_reg_form_settings()`
	- using the code for `email_validation_settings_form()` as an example
		- add methods `setSessionLifespan` and `updateSessionLifespan`
		- add hook in `_reg_form_settings()` using `setSessionLifespan()` as callback
		- position form after `copy_attendee_info_settings_form` (the hook priority likely controls the form position)
		- call `updateSessionLifespan()` in `_update_reg_form_settings()` but do NOT pass or set `EE_Registry::instance()->CFG->registration` as we will not be storing the session lifespan value in that config class.
		- instead of adding method like `_email_validation_settings_form()` create a new folder : `caffeinated/admin/extend/registration_form/forms`
		- create new class in that folder named `SessionLifespanForm` that extends `EE_Form_Section_Proper` and namespace that form accordingly
		- use the form structure in `_email_validation_settings_form()` as an example
		- use the `EE_Admin_Two_Column_Layout` layout strategy
		- add a heading titled "Session Settings"
		- add a select input with following 
			- answer options: 5, 15, 30, 60, & 120 validated as integers
			- input settings: 
				- label text: "Session Lifespan"
				- help text: "Controls how long a user has to complete the registration form. Defaults to 1 hour."
				- default: value from `SessionLifespanOption` (instantiate in constructor)
		- instantiate `SessionLifespanForm` in both `setSessionLifespan()` and `updateSessionLifespan()`
		- use logic in `update_email_validation_settings_form()` as example for how to handle `updateSessionLifespan()` but place that logic in new class called something like `SessionLifespanFormHandler`, then in `updateSessionLifespan()`  do something like:
			```php
			$handler = new SessionLifespanFormHandler();
			$handler->process( new SessionLifespanForm() );
			```
		- pass form value to `SessionLifespanOption` setter and save option
			

- confirm everything works by setting a value then testing registrations on the frontend
	- ex: if session lifespan is set to 5 minutes, then adding tickets to cart, proceeding to reg form, and waiting for more than 5 minutes, should invalidate the session and cancel the reg process

- add a unit test class to confirm that `SessionLifespanOption` works as expected (namespace should be mirrored inside the testcases directory, ie: `EventEspresso\tests\testcases\core\domain\values\session\SessionLifespanOption`)
  
- ask questions regarding anything you are unsure about or want to know more about

- as always, i am open for suggestions and ideas about other ways to approach things, but the above approach should integrate well with existing logic and systems while minimizing the amount of work you will have to do

**Comment by hoseinrafiei** [comment]
I'm closing this because it fixed by https://github.com/eventespresso/event-espresso-core/pull/3926 PR.
