### ISSUE TITLE
MER - TKT ID shown on modal when max_attndz is set to 1

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3872]
Related thread: https://eventespresso.com/topic/pop-up-of-items-added-to-cart-showing-incorrect-number/

To view this you need MER but I think this is a core issue and related to this:
https://github.com/eventespresso/event-espresso-core/pull/3675#issuecomment-1014607726

So I've added this issue here and I'm pretty sure this was tested and worked previously.

**To Reproduce**
Set up an event to have the 'Maximum number of tickets allowed per order for this event' option set to 1.

Use MER and add the above ticket to the cart, the modal will show the TKT_ID, like this: https://monosnap.com/file/jFYNVVUEIL29Ud4gtxp1Ft5Cr315hw

**Environment:**
 - Version of Event Espresso:  current release and master.

**Comment by tn3rb** [comment]
plz see: https://github.com/eventespresso/ee4-mer/pull/33

**Comment by tn3rb** [comment]
@Pebblo 
can you plz test https://github.com/eventespresso/ee4-mer/pull/33 to verify that it fixes this issue?
