### ISSUE TITLE
2022 theme: No tables (borders) are showing in the event page

### ISSUE THREAD

**Issue by Saam01** [eventespresso/event-espresso-core#3874]
**Describe the bug**

When we open the event page in 2022 theme, no tables (borders) are showing.
![image](https://user-images.githubusercontent.com/99984614/172388037-02a78737-feec-46fa-885d-67df0bd71602.png)

Also, after registration the "Registration Details" also not sowing table(borders).
![image](https://user-images.githubusercontent.com/99984614/172388679-18aa34ff-9166-4b01-aa1f-f2c4524f97f8.png)

**Expected behavior**

The same is showing fine in other theme:
![image](https://user-images.githubusercontent.com/99984614/172389016-ce95a8bf-128c-428f-8151-72e8b0669b46.png)

![image](https://user-images.githubusercontent.com/99984614/172389135-694a6810-b350-4031-82cb-87b5fe840bbd.png)

**Environment:**
 - Version of Event Espresso: 4.10.31.rc.003 
 - Version of WordPress: 6.0
 - Browser: Chrome 
 - PHP Version: 7.4.1

**Comment by tn3rb** [comment]
@Saam01 
Can you plz show me an example of what a table normally looks like in the 2022 theme? 🥲

**Comment by Saam01** [comment]
@tn3rb 
Yes, you are right, it seems the theme has no style for tables.

**Comment by tn3rb** [comment]
lolz ok, i'm going to close this then, thnx
