### ISSUE TITLE
Fix reCaptcha V2 broken since 4.10.30

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3879]
Checkbox reCaptcha (V2) no longer works in 4.10.30 but does in .29

If you use checkbox reCaptcha it fails when checking out, blocking the registration by returning to SPCO with unformatted fields.

I did a little digging into this it looks like it's from changes in #3803 

If I checkout the commit right before those changes the registration works fine, repeat and I get the above.

**To Reproduce**
Using Master enable reCaptcha in Event Espresso -> Registration Form -> Reg Form settings.

If you don't have v2 keys, create a set here: https://www.google.com/recaptcha/admin/create

Make sure you use 'reCAPTCHA v2' and the "I'm not a robot" tickbox option. Add your domain to the allowed domains and accept the TOS.

Set the keys in the EE setting page.

Here's my set-up: https://monosnap.com/file/OJsp5CYHIKN6F0WXT03ujTbJyoHPoS

---

Add a registration whilst logged out or in private/incognito and validate the Recaptcha.

This is how you'll know something isn't right: https://monosnap.com/file/5aDjuimy0EsvGJwUULxShHN7bnufzH

The text area for the reCaptcha response is visible.

Test a registration and something like this will happen: https://monosnap.com/file/hr0PkTPE5QwbM9pxzE22K5KRFjxH9A

The formatting changes and the registration doesn't work.

**Comment by Pebblo** [comment]
The above issue is from this change: https://github.com/eventespresso/event-espresso-core/commit/8d385e087be4ee800c22f784f186810c907ecc10#diff-21d4bd339849f1dffbb6a1dc2a5ebac5204fd7fd7c820b804a1509c77c0e22fdR88

If we don't have a proper fix for this today I'll likely just remove that call to wp_kses() to get an update pushed so we can fix users' sites and then discuss this further.

**Comment by garthkoyle** [comment]
I updated my testing notes on the branch.

**Comment by garthkoyle** [comment]
- MENW, I don’t get a recaptcha challenge until I select the TS and Reg form boxes (video): https://www.screencast.com/t/ZuRg3TGFfz
- on ES, I’m not getting the recapcha challenge regardless of those settings: https://www.screencast.com/t/fbf5s7GV

It seems a lot of ES sites have this setting and I got the recaptcha challenge or privacy button on the screen for the TS step:
<img width="285" alt="image" src="https://user-images.githubusercontent.com/3094547/175164788-0e8103a4-8855-4c41-9fdf-138c35bdf7e4.png">

<img width="207" alt="image" src="https://user-images.githubusercontent.com/3094547/175164909-1b292c3d-73fd-4ae6-877c-aa457adb3405.png">

So, I'm presuming this works as expected.
