### ISSUE TITLE
Quickbooks Add-on: It is not possible to connect on 4.10.30p

### ISSUE THREAD

**Issue by joaovictorangeline** [eventespresso/event-espresso-core#3881]
**Describe the bug**
It's not possible to Connect Quickbook integration with Event Espresso 4.10.30p due to the following problems:
- Connected message appears even "Not Connected to Quickbooks" is displayed:
![CleanShot 2022-06-13 at 3 23 28@2x](https://user-images.githubusercontent.com/102395051/173419555-cef25cd0-517a-42c6-ba9e-952a9429cf1c.jpg)
- Disconnect button returns **"Missing some signature required PM data!"** in the console log when is clicked.
- Connect button throws this error when the pop-up is opened: There was an error while trying to request a request_token, please try again
![CleanShot 2022-06-13 at 3 24 32@2x](https://user-images.githubusercontent.com/102395051/173419734-b6d60c83-a9d0-4270-b60c-9b037521eb73.jpg)

**To Reproduce**
1. Have the 4.10.30p
2. Try to connect the Quickbooks integration
3. It works fine on 4.10.29

**Expected behavior**
The integration should be connected with no issues.

**Environment:**
 - Version of Event Espresso:  4.10.30
 - Version of WordPress: 6.0
 - Browser Chrome
 - PHP Version 7.4.1

**Comment by joaovictorangeline** [comment]
Related ticket: https://secure.helpscout.net/conversation/1916243149/907862/

**Comment by knazart** [comment]
The whole connect process here needs refactoring.

**Comment by knazart** [comment]
Yes, this one seems like a duplicate. Probably could close this one in favor for #3906.
