### ISSUE TITLE
Fix Critical Pages dropdowns not saving changes

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3888]
**Describe the bug**
Changes to EE4's critical page dropdowns are no longer saving.

Go to Event Espresso -> General Settings -> Critical Pages.

Set a different page on any of the dropdowns and hit save, the page will show the original value. Refresh and its still the same, so its not an issue with it just loading the last value etc.

Tested v4.10.29.p and the changes save in that version, so new from .30+

**Comment by garthkoyle** [comment]
This looks to be working fine now (video): https://www.screencast.com/t/gXTMHQU89EN
