### ISSUE TITLE
"Max Registrations per Transaction" Does not save on Publish event

### ISSUE THREAD

**Issue by majidabbasi96** [eventespresso/event-espresso-core#3893]
When we create an event and press Publish button some data does not save. For example, if we do not change "Max Registrations per Transaction" and leave the default value there it does not save.

Also, it would be good if we check other fields' values and ensure they are saved after Publish.

![screen-capture](https://user-images.githubusercontent.com/1751030/173941177-149957f4-88c1-4b63-872e-fcb404bc49d1.gif)

**Comment by tn3rb** [comment]
plz pull latest dev branch and test
