### ISSUE TITLE
Fix searching within the registration list removing filters

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3899]
Reported here: https://eventespresso.com/topic/csv-exports-ee4/

If you apply a filter within the registration list table and then use search to narrow down your selection... when you export the results none of the filters (including the search) apply to the export.

**To Reproduce**
I use an event with 2 different ticket types to test this.

Have registrations on both ticket types and have some that are pending payment (or just something other than Approved).

Before: https://monosnap.com/file/ujmChfmG47ehfzNPLGZ7X8Lx6lCaNR

Export works fine.

Set the Reg status to Approved, filter: https://monosnap.com/file/nhBQKubaib0RLRjbcRRzRfxYW8cBSv

My export now contains 7 registrations, as expected.

Now add something to the search field, in my example I'm filtering to another specific ticket name: https://monosnap.com/file/9z4TfkaFOEa6u4CPBzPoMHzoTHJ3B5

Export now contains ALL registrations, including the pending payment reg that was filtered previously, so in this example I'm getting 8 regs exported, should be 2 as above.

(Priority high due to previous issues with exports)

**Comment by tn3rb** [comment]
> Priority high due to previous issues with exports

This issue is with master branch though right?
Those previous issues were with dev branch on Event Smart... did this ever work?

**Comment by tn3rb** [comment]
plz test: https://github.com/eventespresso/event-espresso-core/pull/3907
