### ISSUE TITLE
Fix views no longer being applied to registration reports

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3901]
@joaovictorangeline mentioned that the 'Views' on the registrations table did not apply to the registration report during testing of #3875 , specifically [HERE](https://github.com/eventespresso/event-espresso-core/pull/3875#issuecomment-1149378953)

Afaik those views did not apply to the report, however, I've been testing the difference between v4.10.29 and the current version with regards to the CSV reports and those views do indeed apply in v29 when using the 'Filtered CSV Report' button (my apologies to @joaovictorangeline )

----

To reproduce simply go to Event Espresso -> Registrations.

Use say the 'This Month' view: https://monosnap.com/file/MHeGrOL1UCpZe969xlR2470qWl7jj4

You can see I get 8 registrations returned and that's what is exported when I click the 'Filtered CSV Report'

In master, I get the same registration list table view but on export, it exports all of my sites registrations

**Comment by tn3rb** [comment]
plz test: https://github.com/eventespresso/event-espresso-core/pull/3907
