### ISSUE TITLE
Upload Logo button is not showing as a button under General Settings

### ISSUE THREAD

**Issue by Saam01** [eventespresso/event-espresso-core#3915]
**Describe the bug**

When we go to General Settings the upload Logo button is not showing as a button.

**To Reproduce**
Go to EE > General Settings > Your Organization > Company Logo

**Screenshots**
![image](https://user-images.githubusercontent.com/99984614/176617419-9acbc5e4-7246-41f8-91cd-d4c16a855845.png)

**Environment:**
 - Version of Event Espresso: 4.10.33.rc.013
 - Version of WordPress: 6.0
 - Browser: Chrome
 - PHP Version 7.4.1

**Comment by garthkoyle** [comment]
This looks good:
![image](https://user-images.githubusercontent.com/3094547/177630286-c57d879e-1032-48d8-bd4d-1cb6580365f3.png)
