### ISSUE TITLE
First errant conditional in `espresso_event_tickets_available()` template tag

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#392]
The function's signature has 3 params:
```
function espresso_event_tickets_available( $EVT_ID = 0, $echo = TRUE, $format = TRUE )
```

so it's echo'ed by default and format is true. If formatting is set to false then an array of tickets is returned. However, this conditional causes nothing to be displayed if the defaults are used:

```
if ( $echo && ! $format ) {
	echo $html;
	return '';
}
```

**Comment by mnelson4** [comment]
PR is off for review

**Comment by mnelson4** [comment]
related pull request was merged in
