### ISSUE TITLE
Fix error when editing active plugins via the built-in editor

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#394]
Steps to replicate with EE4 master activated:
1) Go to the WP > Plugins > Editor page and try to make an edit to any **active** plugin.
2) Click "Update File"

The unexpected result will be this message:

```
Your PHP code changes were rolled back due to an error on line 56 of file wp-content/plugins/32-core/caffeinated/modules/recaptcha_invisible/InvisibleRecaptcha.php. Please fix and try saving again.
```
```
Uncaught TypeError: Argument 2 passed to EventEspresso\caffeinated\modules\recaptcha_invisible\InvisibleRecaptcha::__construct() must be an instance of EE_Session, none given in wp-content/plugins/32-core/caffeinated/modules/recaptcha_invisible/InvisibleRecaptcha.php:56
Stack trace:
#0 [internal function]: EventEspresso\caffeinated\modules\recaptcha_invisible\InvisibleRecaptcha->__construct(Object(EE_Registration_Config))
#1 wp-content/plugins/32-core/core/EE_Registry.core.php(1262): ReflectionClass->newInstanceArgs(Array)
#2 wp-content/plugins/32-core/core/EE_Registry.core.php(773): EE_Registry->_create_object('EventEspresso\\c...', Array, '', false)
#3 wp-content/plugins/32-core/core/services/loaders/CoreLoader.php(116): EE_Registry->create('EventEspresso\\c...', Array, true, false, false, '')
#4 wp-content/plugins/
```

**Comment by mnelson4** [comment]
note: `wp_ajax_edit_theme_plugin_file` is what calls the extra asynchronous request to check if a fatal error was added.

**Comment by mnelson4** [comment]
note: `wp_ajax_edit_theme_plugin_file` is what calls the extra asynchronous request to check if a fatal error was added.

**Comment by mnelson4** [comment]
What's really odd: when I use `wp_remote_get` as a "loopback" request, it doesn't work. But if I use CURL directly, like on https://stackoverflow.com/questions/5412069/can-i-do-a-curl-request-to-the-same-server, it works fine. So VVV and laragon setups have some setup, combined with something in how wp's `wp_remote_get` works, that's causing the loopback requests to fail...

**Comment by mnelson4** [comment]
aha- I think I pinpointed the problem being `Requests_Transport_cURL::stream_headers()`. If I disable that method from being invoked, the loopback request works fine

**Comment by mnelson4** [comment]
...well, except somewhere further down the request things blew up still. I haven't managed to get WordPress' built-in file editor to work locally still. I managed to get it to work on a poopy.life server and made a band-aid PR
