### ISSUE TITLE
Fix message template editor styles since 4.10.30

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3957]
Reported here: https://eventespresso.com/topic/text-formatting-bar-disappeared/?view=all

Something is wonky with the message editor visuals since 4.10.30

In master it looks like this: 
https://monosnap.com/file/7YQWYwbc5acyI4GEf76N31s1VXvkiU
![message editor master 4 10 30](https://user-images.githubusercontent.com/1751030/178616398-4a0ffd28-3964-4930-aeb5-69cfd557afb2.png)
(shows both the visual and text buttons, tabs are aligned left etc)

In version 4.10.29.p it shows like this: 
![image](https://user-images.githubusercontent.com/4345417/178513209-347d4b9c-2690-4030-89be-1c5edc0513a7.png)

**To Reproduce**
Just edit any message template to view the above sections.

Event Espresso -> Messages -> Default Message Templates -> Registration Approved -> Edit Registrant.

**Comment by tn3rb** [comment]
issue appeared in #3775
