### ISSUE TITLE
Missing Custom Messages Fields Data Migrating or Installing New Dev Branch

### ISSUE THREAD

**Issue by garthkoyle** [eventespresso/event-espresso-core#3958]
There is missing data in a custom message template, that I expect would have been copied to the new custom template. It will frustrate people if they have to update these fields before using the template especially because they don't know what's supposed to go in those template without doing more research.

- migrate from `master` to `dev` OR install `dev` new
- create a custom message template
- try saving the template as it is presented to you and notice several of the fields are empty and you can't save the template

Here are the specific fields missing for each template:

Payment Received missing fields:
* [ ] attendee list
* [ ] datetime list
* [ ] question list

Refund Issued missing fields:
* [ ] attendee list
* [ ] datetime list

Registration Approved missing fields:
* [ ] To field

Not Approved Registration missing fields:
* [ ] question list

Registration Pending Payment missing fields:
* [ ] question list

Payment Reminder missing fields:
* [ ] attendee list
* [ ] datetime list
* [ ] question list

Payment Declined missing fields:
* [ ] attendee list
* [ ] datetime list
* [ ] question list

Registration Declined missing fields:
* [ ] attendee list
* [ ] question list

Registration Cancelled Payment missing fields:
* [ ] question list

Payment Failed missing fields:
* [ ] attendee list
* [ ] datetime list
* [ ] question list

Invoice missing fields:
* [ ] attendee list
* [ ] datetime list
* [ ] question list

**Comment by tn3rb** [comment]
I deleted my db, installed a fresh site, and activated EE on `master` branch and the following fields were missing (no check - checked off fields were NOT missing)


Payment Received missing fields:
* [ ] attendee list
* [ ] datetime list
* [ ] question list

Refund Issued missing fields:
* [ ] attendee list
* [ ] datetime list

Registration Approved missing fields:
* [ ] To field

Not Approved Registration missing fields:
* [ ] question list

Registration Pending Payment missing fields:
* [ ] question list

Payment Reminder missing fields:
* [ ] attendee list
* [ ] datetime list
* [ ] question list

Payment Declined missing fields:
* [ ] attendee list
* [ ] datetime list
* [ ] question list

Registration Declined missing fields:
* [ ] attendee list
* [ ] question list

Registration Cancelled Payment missing fields:
* [ ] question list

Payment Failed missing fields:
* [ ] attendee list
* [ ] datetime list
* [ ] question list

Invoice missing fields:
* [ ] attendee list
* [ ] datetime list
* [ ] question list

**Comment by garthkoyle** [comment]
You can merge 3966.

The only remaining issue then is that some of the “to” fields are blank. That’s a bad situation. We don't want a blank "to" field otherwise the messages won't send when expected.

**Comment by Pebblo** [comment]
@garthkoyle I posted this in slack but just to make sure it isn't buried.

The missing 'To' fields are expected for contexts that are disabled by default


That's how we disabled message contexts before we had the toggle switch on them, so if those are going to be set by default we'll need to make sure the toggle for those same contexts is disabled by default.

**Comment by garthkoyle** [comment]
@Pebblo Got it. I think it makes sense to have the templates properly set up and turned off if that's what we normally do. cc @tn3rb

**Comment by tn3rb** [comment]
ok closing this then
