### ISSUE TITLE
SVG version of Event Espresso logo

### ISSUE THREAD

**Issue by remcotolsma** [eventespresso/event-espresso-core#3961]
In the Pronamic Pay plugin we have an integration for many Dutch (iDEAL) payment providers. For marketing purposes we are looking for an SVG version of the Event Espresso logo.

https://cdn.eventespresso.com/wp-content/uploads/2020/10/29111402/logo.png

Is there a vector graphic available for the Event Espresso logo? I did found the SVG icon:

https://github.com/eventespresso/event-espresso-core/blob/master/wp-assets/icon.svg

**Comment by tn3rb** [comment]
I don't believe there is an SVG version of the word mark but I can ask the owners if they have any of the original marketing materials and look for one
