### ISSUE TITLE
Refactor Usage of Third Party Libs for Decaf

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3973]
The third party libraries in the `core/third_party_libs/` directory need to have one of the following actions applied to them:

##### ACTION OPTIONS
- `A` moved to global assets folder `core/templates/global_assets` if required by multiple use cases
- `B` co-located to same folder as code that utilizes it if required for a single use case
- `C` move implementation behind feature flag / file check(s) (ie: ` if ( lib exists ) { run lib code }` so that lib can be removed in decaf
- `D` if lib is WP plugin, add logic for recommending download and installation, so that lib can be removed in decaf
- `E` removed altogether because not needed / no longer used
- `F` other possible solutions ???

Here's the libs and the action that I feel may be required (this is subject to change if need be)

- accounting - `A`
- cssinliner - `B`
- dompdf - `C`
- Jaybizzle- `C`
- joyride - `E`
- moment - `A`
- PUE - `C`
- qtip - `A` or `E`
- wp-api-basic-auth - `D`
- wp-graphql - `D`
- jquery.countdown.min.js - `A`
- jquery.plugin.min.js - `A`

If the above action appears to be the best for each lib in question, then plz proceed, otherwise plz provide feedback regarding complications, alternate suggestions, etc

Please perform all work in separate PRs (one for each lib, but some of those smaller assets can be grouped into a single PR). 

Please use `master` branch as the base for all work branches.

Please tag PRs with the following labels: 
- ` category:decaf `
- ` category:3rd-party-integrations `
- ` type:task `

For action option `D` I will likely try to add some kind of helper class for performing plugin recommendations upon activation. So please work on those libs last.

As always, please ask questions if there is *anything* you are unsure about, and I am always open for alternate approaches since there is always more than one way to solve a problem.

**Comment by hoseinrafiei** [comment]
@tn3rb

All the dependencies are done except those that are marked as `D`.
Please let me know when we're ready to work on those items.

**Comment by tn3rb** [comment]
ok great thnx @hoseinrafiei 
`D` was covered by #4043
