### ISSUE TITLE
Remove External Dependencies

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3975]
From the WordPress Plugin Review Team:

> Offloading images, js, css, and other scripts to your servers or any remote service (like Google, MaxCDN, jQuery.com etc) is disallowed. When you call remote data you introduce an unnecessary dependency on another site. If the file you're calling isn't a part of WordPress Core, then you should include it -locally- in your plugin, not remotely. If the file IS included in WordPress core, please call that instead.

> An exception to this rule is if your plugin is performing a service. We will permit this on a case by case basis. Since this can be confusing we have some examples of what are not permitted:
> - Offloading jquery CSS files to Google - You should include the CSS in your plugin.
> - Inserting an iframe with a help doc - A link, or including the docs in your plugin is preferred.
> - Calling images from your own domain - They should be included in your plugin.

> Here are some examples of what we would permit:
> - Calling font families from Google or their approved CDN (if GPL compatible)
> - API calls back to your server to process possible spam comments (like Akismet)
> - Offloading comments to your own servers (like Disqus)
> - oEmbed calls to a service provider (like Twitter or YouTube)

> Please remove external dependencies from your plugin and, if possible, include all files within the plugin (that is not called remotely). If instead you feel you are providing a service, please re-write your readme.txt in a manner that explains the service, the servers being called, and if any account is needed to connect.

> Example(s) from your plugin:
> - `event-espresso-decaf/admin_pages/about/templates/whats_new.template.php` line 94
>     - `<a href="https://ee-screenshots.s3.amazonaws.com/2014/05/ticket-bundles.png">`

Please perform all work in separate PRs (a bunch of smaller stuff can be grouped into a single PR)

Please use `master` branch as the base for all work branches.

Please tag PRs with the following labels: 
- ` category:assets `
- ` category:decaf `
- ` type:task `

As always, please ask questions if there is *anything* you are unsure about, and I am always open for alternate approaches since there is always more than one way to solve a problem.

**Comment by hoseinrafiei** [comment]
@tn3rb

I only found those 3 images which fixed in https://github.com/eventespresso/event-espresso-core/pull/3994 PR.
I searched for iframe codes but found no suspicious one. Also checked the potential external CSS files but nothing found.

Believe that we're done on this task unless you can come up with some instances.

**Comment by tn3rb** [comment]
ok thnx
