### ISSUE TITLE
Console error while editing the page.

### ISSUE THREAD

**Issue by Saam01** [eventespresso/event-espresso-core#4003]
EE backend menus working fine.
But I found error under Page editor (Pages > Edit/create a new page): 

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/99984614/185739787-406db634-2f26-4041-ba2d-c542354aaba6.png)

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

**Environment:**
 - Version of Event Espresso:  4.10.39.rc.009
 - Version of WordPress: 6.0.1
 - Browser: Chrome
 - PHP Version: 7.4.1

**Comment by garthkoyle** [comment]
What page is that happening on? 

I'm testing this one and don't see a problem there: https://august2022update.makeeventsnotwar.com/wp-admin/post-new.php?post_type=page

**Comment by Saam01** [comment]
@garthkoyle  This issue is related to the master branch.

**Comment by tn3rb** [comment]
that code is gone as soon as soon as dev is merged so just going to close this

**Comment by Saam01** [comment]
@tn3rb I can still seeing the issue. Please check the video.

https://user-images.githubusercontent.com/99984614/192084372-45f4a06d-7fcc-4f68-9a54-27e75f481977.mp4
