### ISSUE TITLE
(De-)Activing a message template isn't possible

### ISSUE THREAD

**Issue by tislars** [eventespresso/event-espresso-core#4008]
**Describe the bug**
Activating or deactivating a template does not seem to be saved. After saving a message template, the page reloads and the option is back to its original state.

**To Reproduce**

1. Go to the menu item `Event Espresso > Messages`
2. Go the tab `Default message templates`
3. Edit a registrants message template (e.g. Automated Upcoming Event Notification)
4. Active (or de-active if the option is already activated) the template
5. Save the page
6. The state of the template should be back to the previous state and **not** the state that you wanted

**Expected behavior**
I expected the state of the toggle to be saved in the state I changed it to.

**Screenshots**

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/1890311/186613777-5a6ddc3e-9a4d-4fbf-9cf8-53ae24da48cf.png">

**Environment:**
 - Version of Event Espresso:  Dev branch at commit [ccd490d](https://github.com/eventespresso/event-espresso-core/commit/ccd490d067dfab2a52826824ea2c84b7788d52d4)
 - Version of WordPress: 5.9.3
 - Browser: FireFox 103.0.2 (also verified the bug exists on Google Chrome 104.0.5112.101)
 - PHP Version: 7.4.30

**Additional context**

The following Event Espresso plugins are active:
- Automated Upcoming Event Notification (EE 4.9.44+) - 1.0.5.p
- Grid View Template (EE 4.4.9+) - 1.2.4.p
- Recurring Events Manager (EE 4.9+) - 1.0.0.rc.005
- Wait Lists (EE4.9+) - 1.0.2.p
- WP Users (EE4.6+) - 2.0.18.p

**Comment by garthkoyle** [comment]
I can reproduce the issue too, but I'm using PHP 8.0.0.

**Comment by garthkoyle** [comment]
This doesn't seem to be an issue with the AUEN add-on, all the message on/off toggles in `dev` don't stay switched on/off after trying to save the message.

**Comment by tn3rb** [comment]
fix pushed to #4009

**Comment by garthkoyle** [comment]
@tislars please give this branch a try: `fix-message-active-toggle`

**Comment by garthkoyle** [comment]
@tn3rb this needs to be merged upstream.
