### ISSUE TITLE
Number of events showing in the category page after deleting all the categories.

### ISSUE THREAD

**Issue by Saam01** [eventespresso/event-espresso-core#4027]
When we assign the categories to the events and then delete the event, it is still showing the number of events assign to the categories in the Category page.

**Screenshots**
https://user-images.githubusercontent.com/99984614/188494657-0031aa26-1e59-4683-9dd3-8ff22df77b49.mp4

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

**Environment:**
 - Version of Event Espresso:  4.10.39.rc.018
 - Version of WordPress: 6.0.1
 - Browser: Chrome
 - PHP Version: 7.4.1

**Comment by tn3rb** [comment]
@Saam01  good find  👍🏻 

need to remove the term relation upon event deletion.
surprised this wasn't done already. might be broken.

**Comment by hoseinrafiei** [comment]
@Saam01

Thanks for your report. Please test the https://github.com/eventespresso/event-espresso-core/pull/4029 PR and let me know if the issue is fixed.

**Comment by Saam01** [comment]
@hoseinrafiei This issue is fixed in the masters.

Please check the ES with the same issue.
