### ISSUE TITLE
Not work filter posts_where on Events page

### ISSUE THREAD

**Issue by KostinOlegA** [eventespresso/event-espresso-core#4049]
I'm trying to filter the displayed Events so that the user only sees their own events.
But the posts_where filter doesn't work
```
function eeac_expired_events_where($sql, WP_Query $wp_query)
{
    if (is_admin()) {
        var_dump('-----------------------');
    }
    return $sql;
}
add_filter('posts_where', 'eeac_expired_events_where', 10, 2);
```

**Comment by tn3rb** [comment]
where are you adding that filter?

do you have a public repo with the code that I could look at?

would be nice if you could provide some more information than the above

**Comment by tn3rb** [comment]
if you are running that on the frontend of the site, 
then `is_admin()` is going to return false and you are not going to see any output

**Comment by KostinOlegA** [comment]
@tn3rb I am executing this code in functions.php

**Comment by tn3rb** [comment]
what theme are you using and what version of Event Espresso?

**Comment by KostinOlegA** [comment]
@tn3rb I use this in admin panel
On the posts page, the filter works

**Comment by KostinOlegA** [comment]
@tn3rb Event Espresso Version 4.10.8.p, theme is self-written

**Comment by tn3rb** [comment]
so your admin page like `http://yourdomain.com/wp-admin/admin.php?page=espresso_events`

**Comment by KostinOlegA** [comment]
@tn3rb Yes, page is `http://yourdomain.com/wp-admin/admin.php?page=espresso_events`

**Comment by tn3rb** [comment]
ok sorry but that list table is not using the standard WP_Query but there are other filters available in `Events_Admin_Page::get_events()` which can be found in `plugins/event-espresso-core/admin_pages/events/Events_Admin_Page.core.php`

**Comment by KostinOlegA** [comment]
@tn3rb Got it, thanks for the quick replies

**Comment by KostinOlegA** [comment]
@tn3rb Thanks a lot! This is what I need

**Comment by tn3rb** [comment]
something like the following _might_ be what you are looking for (but I'm guessing)

```php
function eeac_expired_events_where(array $where)
{
    $where['EVT_wp_user'] = get_current_user_id();
    return $where;
}
add_filter('posts_where', 'FHEE__Events_Admin_Page__get_events__where', 10);
```
