### ISSUE TITLE
Add Column To Messages Table List

### ISSUE THREAD

**Issue by KostinOlegA** [eventespresso/event-espresso-core#4053]
Is it possible to somehow add a column with the username to the table Event Espresso - Message Activity ?
![image](https://user-images.githubusercontent.com/45523133/192877327-eff892a5-17a3-4b21-9bc7-742291bd5f83.png)

**Comment by tn3rb** [comment]
thnx for your request, 
there is currently no code in place to add a column for the registrant's name but it is certainly possible form a technical standpoint and sounds like a good idea to me.

**Comment by garthkoyle** [comment]
> Is it possible to somehow add a column with the username to the table Event Espresso - Message Activity ?

Not all recipients of messages are `users` within WordPress and thus do not have a corresponding `username`. Therefore, adding a dedicated column for `usersname` for is not a good fit. Also, not every website that uses Event Espresso will want to display an empty `username` column. But as Brent suggests, that possible the `attendee` or `registrant` first name could be added. Would that work for you?

If the first name is not a good fit for you in that column then perhaps we'd just provide a way for you to customize the column yourself while we maintain the current layout for existing Event Espresso users.

**Comment by KostinOlegA** [comment]
I think this will suit me. Thank you

**Comment by garthkoyle** [comment]
yup
