### ISSUE TITLE
Fix form validation messages aka the "Chicken is a required question" issue

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#407]
From Codebase ticket: https://events.codebasehq.com/projects/event-espresso/tickets/11245

Apparently the registration forms default validation message, the one that displays in the pop up message, uses the first answer option as the question name. It's important that this gets fixed because if you set up a required question with radio buttons like below:
Choose your meal preference:*
Chicken
Beef
Fish
then if the registrant does not complete the field, the pop up error message says ‘Chicken is a required question’. 😂

https://slack-files.com/T02SY781D-F8EJQ8Y0N-c1e918bf7c

**Comment by tn3rb** [comment]
should still likely be fixed so that be default, the question name is used instead of the option name.
