### ISSUE TITLE
Separate Billing Users

### ISSUE THREAD

**Issue by Panamus** [eventespresso/event-espresso-core#4076]
**Is your feature request related to a problem? Please describe.**

The registration is somewhat limiting our ability to continue with our project. We require that when the registration form is completed, the person completing the form may well not be someone who is actually attending the event. We deem these users as `Billing users`. Right now, the primary attendee is deemed the billing user. In our scenario a billing user may not attend the event and will be booking multiple attendees.

**Describe the solution you'd like**

We'd like to have the form ask for billing details separate from the primary attendee, with the ability to copy the billing details over to the primary attendee.

**Describe alternatives you've considered**

We have looked through the current pool of add-on's and there doesn't seem to be anything that offers this as a solution, or anything that we could possible build on ourselves.

**Additional context**

We were directed here by Garth off the back of an email conversation.

**Comment by garthkoyle** [comment]
Hi @Panamus As I stated in my email, the person completing the billing form could be a different person than the primary attendee. For example, I could register my children for an event, yet provide my own billing information via a card payment in the billing form. That is currently supported and has been for a long time.

Please describe how that does not work for you. It's not clear in the description above how you're using the term "user". From our email discussions I understand it that you want to create an official WordPress user, which is also different from the Attendee or Registrant in Event Espresso. 

It is also not clear to me how you want to programmatically create a `Billing User` and what that means in your website. Is that again a definition or capability or role within the WordPress user system or a contact/registration/registrant type within Event Espresso?

**Comment by Panamus** [comment]
Apologies the correct solution for this may have just clicked.

I realise that it's the WP User Add-On where the primary attendee syncs with the logged in user. So when we're trying to book, whoever is logged in is treated as the primary attendee as if you change the details (name for example) of the primary attendee then it automatically syncs with the primary attendee. 

So turning off the sync functionality would stop the primary attendee updating the logged in user. 

But we'd still require all the attendees (including the primary attendee, if primary attendee isn't the logged in user) to have accounts created for them.
