### ISSUE TITLE
Allow custom sortable columns to be used in list table order_by param?

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#410]
Reported here: https://eventespresso.com/topic/sorting-by-custom-column-in-events-registration-table/

In short if you add a custom column to the registrations list, then use this filter:

```$_sortable = apply_filters("FHEE_manage_{$this->screen->id}_sortable_columns", $_sortable, $this->_screen);```

To enable sorting on that column, although you can click to sort, and if you've done it correctly the URL will change to short something like `&orderby=REG_code&order=desc` the orderby parameter doesn't actually get used and defaults to REG_date

See https://github.com/eventespresso/event-espresso-core/blob/master/admin_pages/registrations/Registrations_Admin_Page.core.php#L1468

I switched this out so that `$orderby_field` was set to whatever was passed in `_req_data['orderby']` and then ran through the switch (setting it to whatever the value is if it doesn't match) and it worked as expected then but should this be done through a filter?

**Comment by mnelson4** [comment]
IMO I think ideally, the default switch case would double-check they're requesting to filter by a valid column name, and if so, use it for ordering. We probably shouldn't order by just whatever is passed in, as the current user might not have permission to see that column they're requesting to filter by (so that would be a bit of a security issue)

**Comment by Pebblo** [comment]
I think the work done in #525 covers the original request in this ticket, however, it doesn't filter the sortable columns based on what the user has access too as Mike suggested.

So @mnelson4 do you still think that is something that should be done or can this be closed?

**Comment by mnelson4** [comment]
Hmmm, ya. That is technically still an issue. We shouldn't accept just any user input, we should have a filter that accepts the user's input, which plugin code can use (and validate the user's input), rather than just accepting any input user's submit.
