### ISSUE TITLE
Class extensions not working as expected

### ISSUE THREAD

**Issue by Panamus** [eventespresso/event-espresso-core#4102]
**Describe the bug**

When following the documentation [here](https://github.com/eventespresso/event-espresso-core/blob/master/docs/D--Addon-API/model-and-class-extensions.md#class-extensions) for extending a class I'm not sure if I've missed something but when calling the method that I've added I get an error.

> Method get_course_survey_completion on class EE_Registration does not exist! You can create one with the following code in functions.php or in a plugin: add_filter('FHEE__EE_Registration__get_course_survey_completion','my_callback',10,3);function my_callback($previousReturnValue,EE_Base_Class $object, $argsArray){/*function body*/return $whatever;}

I assumed that the class extension took care of this under the hood? 

**To Reproduce**
1. Add a class extension
2. Add it under 'class_extensions' in the addon register
3. Call the added method

**Expected behavior**

By the looks of the documentation this should just work without adding the filters.

**Environment:**
 - Version of Event Espresso:   4.10.40.p
 - Version of WordPress:  6.1.1
 - Browser:  chrome
 - PHP Version  8.0

**Additional context**

```php
<?php

class EEE_LD_Registration extends EEE_Base_Class
{
    public function __construct()
    {
        $this->_model_name_extended = 'Registration';
        parent::__construct();
    }

    /**
     * get_course_survey_completion
     * 
     * Returns the status for if a course has been completed
     * 
     * @return string
     */
    public function get_course_survey_completion()
    {
        return $this->_->get_extra_meta('ld_survey_reg_completed', true, 0) ? 'Yes' : 'No';
    }

    /**
     * get_course_survey_link
     * 
     * Returns the status for if a course has been completed
     * 
     * @return string
     */
    public function get_course_survey_link()
    {
        return $this->_->get_extra_meta('ld_survey_reg_entry_link', true, false);
    }    
}
```

**Comment by tn3rb** [comment]
@Panamus 
sorry for the delay getting to this issue.
Is your code publically available somewhere, like a github repo, where i can look at everything? That would give me a better opportunity to comment correctly on it.

Base on what you have provided, i have the following initial comments:

- you don't need to setup a filter like
  ```php
    add_filter('FHEE__EE_Registration__get_course_survey_completion','my_callback',10,3);
   ```
   as that is taken care of automagically under the hood. In fact, doing so is likely interfering with your class extension, as that filter would noe be getting added twice.

- in order to find your class extension methods, they need to be prefixed with `ext_` like in the example from the documentation you referenced. So your class would need to look like:
  ```php
    class EEE_LD_Registration extends EEE_Base_Class
    {
        public function __construct()
        {
            $this->_model_name_extended = 'Registration';
            parent::__construct();
        }
    
        /**
         * Returns the status for if a course has been completed
         *
         * @return string
         */
        public function ext_get_course_survey_completion()
        {
            return $this->_->get_extra_meta('ld_survey_reg_completed', true, 0) ? 'Yes' : 'No';
        }
    
        /**
         * Returns the status for if a course has been completed
         *
         * @return string
         */
        public function ext_get_course_survey_link()
        {
            return $this->_->get_extra_meta('ld_survey_reg_entry_link', true, false);
        }
    }
   ```

I'm guessing it's that second point that is the root of thr problem.
I'd be happy to look into this more though if you can provide access to your code.

**Comment by tn3rb** [comment]
> Here's where the method is being called.

Don't use the `ext_` prefix when calling your class extension methods, so you can cahnge that call to:

```php
echo  $item->get_course_survey_completion();
```

The methods needs to be _named_ with the `ext_` prefix but you drop that when calling it.

> What parts specifically are you interested in?

finding the spot in your code that is causing these issues for you :)
I don't know where exactly things have gone wrong, so i wanted to look over everything to find what is wrong. Ideally I could clone the repo and run the code locally to see it in action.

**Comment by Panamus** [comment]
Dropping the ext_ from the method call worked.

Thanks @tn3rb!
