### ISSUE TITLE
Access PHP input stream for payment gateway IPN. 

### ISSUE THREAD

**Issue by Panamus** [eventespresso/event-espresso-core#4116]
Our custom payment gateway used XML from the payment provider which currently can't be collected and passed to handle_payment_update as process_ipn and handle_ipn just pass the request body and XML is in the php input stream. 

How can I inject this into process_ipn? I have considered overriding the EspressoTxnPage shortcode but this seems to be different to normal addon shortcodes and I'm unsure of how to implement this.

Do payment gateways support their own shortcodes?

This is the final piece of the puzzle that I need for our custom gateway.

**Comment by Panamus** [comment]
I've explored a few options for this. 

One of which is a custom transaction shortcode that basically injects the results I need from the xml into the request data that's sent to `process_ipn` via an array merge. However, for some reason when we get to `handle_payment_update` the injected data is no longer in the request. 

I don't see how this is happening, other than perhaps there is multiple calls to the transaction page and the second time around there's no php input stream.

**Comment by tn3rb** [comment]
Hi @Panamus 

sry i missed this issue, i'm guessing from your latest issue that you at least got this working via the `FHEE__EES_Espresso_Txn_Page__run__exit` filter?

**Comment by Panamus** [comment]
Hi @tn3rb 

Sorry I don't know how I missed this reply either. 

as it happens, it was still fine to get the XML via the input stream during the transaction. What I wasn't aware of at the time is that both the notify_url and return_url were calling `handle_payment_update`. But because of the issue with the polluted request because of the XML I wasn't hitting the payment method when the IPN hit the transactions endpoint. So I was seeing the empty input stream being logged when the return url was hit because no XML was being sent there. 

Obviously the stream was empty at this point, so it wasn't causing the bug that wasn't finding the payment method.

So yes, we got this working now.
