### ISSUE TITLE
Blocker: Custom Payment Method not returning 

### ISSUE THREAD

**Issue by Llanilek** [eventespresso/event-espresso-core#4118]
**Describe the bug**
When creating a custom payment gateway the `EES_Espresso_TXN_Page` shortcode doesn't work as expected.

https://github.com/eventespresso/event-espresso-core/blob/master/core/domain/entities/shortcodes/EspressoTxnPage.php#L73

The above is returning `false` when attempting to get the `EEM_Payment_Method` via `get_one_by_slug`.

the slug being requested is `wpm_payment_method` and in the database `PMD_slug` is `wpm_payment_method`.

I'm not sure why this is returning false, but it's a major blocker for our progress.

**Expected behavior**
`$payment_method instanceof EE_Payment_Method && $payment_method->is_off_site()` should be both returning true, yet because it's not returning a payment method this is failing, and the transaction page is not triggering `process_ipn` as it should be.

**Environment:**
 - Version of Event Espresso:  4.10.43.p
 - Version of WordPress: 6.1.1
 - Browser:  chrome
 - PHP Version  8.0

**Comment by tn3rb** [comment]
looking into that right now, will hopefully get a solution for you in a bit

**Comment by tn3rb** [comment]
@Panamus 
can I see your PM code?
is this code on github or other web accessible repo and if so, can you grant me read access?

the query to retreive the `EEM_Payment_Method::get_one_by_slug()` method is totally straightforward, so I can only surmise that there is something else that is causing this issue as that method is used in over 20 places in our codebase without issue.

If you can get me some more info I can trouble shoot this for you.

**Comment by Panamus** [comment]
we haven't got any seats left in our org to add you with read access. Let me try and set up a gist or something.

**Comment by tn3rb** [comment]
a gist works, thnx

**Comment by Panamus** [comment]
@tn3rb https://gist.github.com/Panamus/43ab237d2df1f0971c10ca2fdd6a39aa

**Comment by tn3rb** [comment]
> it's littered with debugging stuff

wiat... that's not normal? 😉

**Comment by tn3rb** [comment]
@Panamus 

seems to be working fine for me:

![Screenshot from 2023-01-17 14-21-36](https://user-images.githubusercontent.com/1751030/213025328-673ee917-2c0c-4849-941f-272ff0ee8476.png)

did you save your PM's settings on the Payment Methods Admin page?
![Screenshot from 2023-01-17 14-24-39](https://user-images.githubusercontent.com/1751030/213025758-7dc68339-bc00-4c4f-aed6-5a743130325f.png)

![Screenshot from 2023-01-17 14-23-02](https://user-images.githubusercontent.com/1751030/213025550-b6561fa6-7cf3-489f-b5f8-9a3253a39e79.png)

**Comment by tn3rb** [comment]
i may need to get a list of values to enter into that settings form to test further 
but you should verify that when you return from the offsite gateway, the return URL at least contains the following parameters:

- e_reg_url_link=#abcd
- ee_payment_method=wpm_payment_method

**Comment by Panamus** [comment]
Odd one that... It's definitely returning with the ee_payment_method=wpm_payment_method. 

All the settings are working fine, it's hitting the offsite fine and when the request comes back it's definitely got the correct params in the URL. 

I'll do some more debugging to see if something comes amiss. 

Out of interest what are you using to spit out the vars like that on your first screenshot? That looks helpful haha.

**Comment by tn3rb** [comment]
`EEG_WPM_Payment_Method::set_redirection_info()` appears to be getting a correct notify URL:

![Screenshot from 2023-01-17 14-34-37](https://user-images.githubusercontent.com/1751030/213027168-a460c150-f2e7-4727-8f08-15b5137eec2d.png)

which you are assigning to:

```php
$data['callbackurl'] = $notify_url;
```

so I would do the following:

- verify that `'callbackurl'` is the correct key name to use with your gateway for that paramater

- verify that the URL for the EE transactions page looks something like:
   ```
    your-domain.com/transactions/?e_reg_url_link=abcdefg&ee_payment_method=wpm_payment_method
   ```

**Comment by Panamus** [comment]
`/transactions/?e_reg_url_link=1-b3fca1fffe7b38a9c8857295166e1766&ee_payment_method=wpm_payment_method`

just did a test transaction and monitored what's being hit in apache. The above was the requested url.

**Comment by tn3rb** [comment]
> Out of interest what are you using to spit out the vars like that on your first screenshot?

i have a debugging method i use that's in EE core:

```
\EEH_Debug_Tools::printr($variable, '$variable', __FILE__, __LINE__);
```

it will format content differently depending on what data type you pass.

I use phpStorm for PHP development which has a feature called "live templates" 
so i have the following saved as a user tempalte named `pt`
```php
\EEH_Debug_Tools::printr($VAR$, '$VAR$', __FILE__, __LINE__);$END$
```

so i only need to type `pt` and that template gets inserted, then i copy n paste my variable into the first spot where `$VAR$` is and it autocompletes the rest

**Comment by tn3rb** [comment]
> just did a test transaction and monitored what's being hit in apache. The above was the requested url.

can you try pasting that URL directly into your browser plz?

i really baffled by this as everything seemes to be working fine on my end

**Comment by Panamus** [comment]
This is the strange thing... I've just used postman to do a request using that url with the expect XML and it's working. it's just when the gateway does it its like nooope.

**Comment by tn3rb** [comment]
wonder if it's a char set issue or something absolutely bonkers like that?

**Comment by Panamus** [comment]
the fact it's using XML is bonkers, but alas it's what I've got to work with 😂. I'll check charset.

**Comment by tn3rb** [comment]
the gateway is returning xml? yuk

oh hey... one thing to watch out for is any URL param key that start with `reg`
because in a URL those appear like `&reg` which can get interpreted as the html entity for "registration" and literally converted in the URL to `®`

that's why our `e_reg_url_link` param starts with `e_` it's just to break up that pattern

**Comment by Panamus** [comment]
Yeah it returns XML to the notify_url which then has to be replied to by echoing out XML into the transaction page body for a handshake. It's a nightmare honestly. 

Luckily I found `FHEE__EES_Espresso_Txn_Page__run__exit` that helped there and threw in a closure that then returned the XML that the gateway needed. It's been a massive headache.

**Comment by tn3rb** [comment]
well I can't see anything in your code that looks out of place, so i would focus on trying to determine how the data and url params are getting returned from the gateway.

beyond that i would need testing creds and details to be able to run a transaction myself

payment gateways are fun eh? 🙄 

good luck and let me know how things go, and feel free to hit me up for more help of need be.
i don't really know what else to do with this atm.

**Comment by Panamus** [comment]
Well, it's nearly midnight here so going to try again in the morning.

Looks like it was handle_IPN_in_this_request wasn't returning what I wanted so I removed the override and just set it it's returning true for now. 

that got it so that if I hit transactions directly with the expected XML then everything works just fine. But when I go through the actual payment gateway then it's a completely different story. More debugging tomorrow it seems!

**Comment by Panamus** [comment]
@tn3rb I think I've located why `$payment_method` is returning `NULL` when being hit from the payment gateway itself rather than just visiting the URL directly.

I logged what `$payment_method_slug` contains and it's returning `'wpm_payment_method]]><![CDATA[https://my.domain.com/registration-checkout/?uts=1674034884'`

So looks like for some reason the TXN page is freaking out when getting `ee_payment_method` from the url params. Not sure how to deal with this one 😂

**Comment by Panamus** [comment]
```EventEspresso\core\services\request\Request::__set_state(array(
   'cookies' => NULL,
   'files' => 
  array (
  ),
   'is_bot' => false,
   'request_params' => 
  EventEspresso\core\services\request\RequestParams::__set_state(array(
     'get' => 
    array (
      'e_reg_url_link' => '1-d1a59398f64f0cd76dd1554a03748df3',
      'ee_payment_method' => 'wpm_payment_method',
    ),
     'post' => 
    array (
      ' '"d304ccb1c778cb8f364707dbe1836b20">8187129201example@example.com 'payment_options',
      'action' => 'process_gateway_response',
      'selected_method_of_payment' => 'wpm_payment_method',
      'spco_txn' => '86#checkout]]> 'wpm_payment_method]]> '1#checkout]]>300.000.00300.00ExemptE012023-01-18 11:27:00300.000.00300.00LONDEC5808501234502023-01-18 11:29:333001Neil Hickmanvs5262042024
',
    ),
     'request' => 
    array (
      'e_reg_url_link' => '1-d1a59398f64f0cd76dd1554a03748df3',
      'ee_payment_method' => 'wpm_payment_method]]> '"d304ccb1c778cb8f364707dbe1836b20">8187129201example@example.com 'payment_options',
      'action' => 'process_gateway_response',
      'selected_method_of_payment' => 'wpm_payment_method',
      'spco_txn' => '86#checkout]]> '1#checkout]]>300.000.00300.00ExemptE012023-01-18 11:27:00300.000.00300.00LONDEC5808501234502023-01-18 11:29:333001Neil Hickmanvs5262042024
',
    ),
     'sanitizer' => 
    EventEspresso\core\services\request\sanitizers\RequestSanitizer::__set_state(array(
    )),
  )),
   'request_type' => 
  EventEspresso\core\domain\services\contexts\RequestTypeContextChecker::__set_state(array(
     'request_type' => 
    EventEspresso\core\domain\entities\contexts\RequestTypeContext::__set_state(array(
       'is_activation' => false,
       'valid_request_types' => 
      array (
        0 => 'activation-request',
        1 => 'non-ajax-admin-request',
        2 => 'admin-ajax-request',
        3 => 'frontend-ajax-request',
        4 => 'admin-ajax-heartbeat',
        5 => 'other-ajax-request',
        6 => 'rest-api',
        7 => 'command-line',
        8 => 'wp-cron',
        9 => 'feed-request',
        10 => 'non-ajax-frontend-request',
        11 => 'iframe-request',
        12 => 'wp-rest-api',
        13 => 'wordpress-scrape',
      ),
       'slug' => 'non-ajax-frontend-request',
       'description' => 'The current request is for the frontend',
    )),
     'identifier' => 'requesttypecontextchecker',
     'acceptable_values' => 
    array (
      0 => 'activation-request',
      1 => 'non-ajax-admin-request',
      2 => 'admin-ajax-request',
      3 => 'frontend-ajax-request',
      4 => 'admin-ajax-heartbeat',
      5 => 'other-ajax-request',
      6 => 'rest-api',
      7 => 'command-line',
      8 => 'wp-cron',
      9 => 'feed-request',
      10 => 'non-ajax-frontend-request',
      11 => 'iframe-request',
      12 => 'wp-rest-api',
      13 => 'wordpress-scrape',
    ),
     'evaluation_callback' => 
    array (
      0 => NULL,
      1 => 'evaluateContext',
    ),
  )),
   'server_params' => 
  EventEspresso\core\services\request\ServerParams::__set_state(array(
     'ip_address' => 'xx.x.xxx.xxx',
     'sanitizer' => 
    EventEspresso\core\services\request\sanitizers\ServerSanitizer::__set_state(array(
    )),
     'server' => 
    array (
      'SERVER_SOFTWARE' => 'Apache/2.4.54 (Debian)',
      'REQUEST_URI' => '/transactions/?e_reg_url_link=1-d1a59398f64f0cd76dd1554a03748df3&ee_payment_method=wpm_payment_method',
      'WP_REDIS_DISABLED' => '1',
      'USER' => 'cbkurrhtpu',
      'HOME' => '/home/846646.cloudwaysapps.com/cbkurrhtpu',
      'SCRIPT_NAME' => '/index.php',
      'QUERY_STRING' => 'e_reg_url_link=1-d1a59398f64f0cd76dd1554a03748df3&ee_payment_method=wpm_payment_method',
      'REQUEST_METHOD' => 'POST',
      'SERVER_PROTOCOL' => 'HTTP/1.0',
      'GATEWAY_INTERFACE' => 'CGI/1.1',
      'REDIRECT_QUERY_STRING' => 'e_reg_url_link=1-d1a59398f64f0cd76dd1554a03748df3&ee_payment_method=wpm_payment_method',
      'REDIRECT_URL' => '/transactions/',
      'REMOTE_PORT' => 51234,
      'SCRIPT_FILENAME' => '/home/846646.cloudwaysapps.com/cbkurrhtpu/public_html/index.php',
      'SERVER_ADMIN' => '[noaddressgiven]',
      'CONTEXT_DOCUMENT_ROOT' => '/home/846646.cloudwaysapps.com/cbkurrhtpu/public_html/',
      'CONTEXT_PREFIX' => '',
      'REQUEST_SCHEME' => 'http',
      'DOCUMENT_ROOT' => '/home/846646.cloudwaysapps.com/cbkurrhtpu/public_html/',
      'REMOTE_ADDR' => 'xx.x.xxx.xxx',
      'SERVER_PORT' => 80,
      'SERVER_ADDR' => '127.0.0.1',
      'SERVER_NAME' => 'my.domain.com',
      'SERVER_SIGNATURE' => '
Apache/2.4.54 (Debian) Server at my.domain.com Port 80

',
      'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
      'HTTP_X_VARNISH' => '1248180',
      'HTTP_HOST' => 'my.domain.com',
      'HTTP_X_FORWARDED_FOR' => 'xx.x.xxx.xxx',
      'HTTP_PRAGMA' => 'no-cache',
      'HTTP_CACHE_CONTROL' => 'no-cache',
      'CONTENT_TYPE' => 'application/x-www-form-urlencoded',
      'HTTP_ACCEPT' => '*/*',
      'HTTP_USER_AGENT' => 'WPM_webHTTP',
      'CONTENT_LENGTH' => '2398',
      'HTTP_CONNECTION' => 'close',
      'HTTP_X_VERSION' => '60',
      'HTTP_X_APP_USER' => 'cbkurrhtpu',
      'HTTP_X_APPLICATION' => 'wordpress',
      'HTTP_X_FORWARDED_HOST' => 'my.domain.com',
      'HTTP_X_FORWARDED_PROTO' => 'https',
      'HTTP_X_REAL_IP' => 'xx.x.xxx.xxxx',
      'SCRIPT_URI' => 'http://my.domain.com/transactions/',
      'SCRIPT_URL' => '/transactions/',
      'HTTP_AUTHORIZATION' => '',
      'HTTPS' => 'on',
      'cw_allowed_ip' => '0',
      'REDIRECT_STATUS' => '200',
      'REDIRECT_SCRIPT_URI' => 'http://my.domain.com/transactions/',
      'REDIRECT_SCRIPT_URL' => '/transactions/',
      'REDIRECT_HTTP_AUTHORIZATION' => '',
      'REDIRECT_HTTPS' => 'on',
      'REDIRECT_cw_allowed_ip' => '0',
      'FCGI_ROLE' => 'RESPONDER',
      'PHP_SELF' => '/index.php',
      'REQUEST_TIME_FLOAT' => 1674041373.7814,
      'REQUEST_TIME' => 1674041373,
    ),
     'request_uri' => NULL,
     'user_agent' => 'WPM_webHTTP ',
  )),
))```

So this is the request object var export.

As you can see, the get is perfectly fine...

the post is having trouble with the `spco_txn` containing part of the XML

the request itself is `ee_payment_method' => 'wpm_payment_method]]> '"d304ccb1c778cb8f364707dbe1836b20">8187129201example@example.com 'payment_options',`

I'm not sure where RequestInterface::getRequestParams is getting `ee_payment_method` from but it's polluted with the XML for some reason.

**Comment by Panamus** [comment]
Here's the XML that was posted from the gateway to the notify url. 

```xml
<?xml version="1.0"?>
<wpmpaymentrequest msgid="ef686ce898bd8734c2a2afd632cd7d3">
  <clientid>1</clientid>
  <requesttype>1</requesttype>
  <pathwayid>1</pathwayid>
  <departmentid>1</departmentid>
  <staffid/>
  <customerid><![CDATA[18]]></customerid>
  <title/>
  <firstname><![CDATA[Neil]]></firstname>
  <middlename/>
  <lastname><![CDATA[Hickman]]></lastname>
  <emailfrom><![CDATA[example@example.com]]></emailfrom>
  <toemail>example@example.com</toemail>
  <ccemail/>
  <emailfooter/>
  <transactionreference><![CDATA[88]]></transactionreference>
  <redirecturl><![CDATA[https://my.domain.com/registration-checkout/?uts=1674055468&step=payment_options&action=process_gateway_response&selected_method_of_payment=wpm_payment_method&spco_txn=88#checkout]]></redirecturl>
  <callbackurl><![CDATA[https://my.domain.com/transactions/?e_reg_url_link=1-12dbbd72a7d6a6f5c67187e0ecc747e8&ee_payment_method=wpm_payment_method]]></callbackurl>
  <cancelurl><![CDATA[https://my.domain.com/registration-checkout/?uts=1674055468&step=payment_options&ee_cancel_payment=1#checkout]]></cancelurl>
  <billaddress1><![CDATA[TEST]]></billaddress1>
  <billaddress2/>
  <billaddress3/>
  <billtown><![CDATA[TEST]]></billtown>
  <billcounty><![CDATA[TEST]]></billcounty>
  <billpostcode><![CDATA[TEST]]></billpostcode>
  <billcountry><![CDATA[GB]]></billcountry>
  <payments id="1" type="PN" payoption="SC">
    <description><![CDATA[Minor Oral Surgery  Course Cohort 1]]></description>
    <payment payid="1" paid="1">
      <amounttopay>300.00</amounttopay>
      <amounttopayvat>0.00</amounttopayvat>
      <amounttopayexvat>300.00</amounttopayexvat>
      <vatdesc>Exempt</vatdesc>
      <vatcode>E</vatcode>
      <vatrate>0</vatrate>
      <mandatory>1</mandatory>
      <dateofpayment>2023-01-18 15:24:00</dateofpayment>
      <amountpaid>300.00</amountpaid>
      <amountpaidvat>0.00</amountpaidvat>
      <amountpaidexvat>300.00</amountpaidexvat>
    </payment>
  </payments>
  <transaction>
    <transid>580967</transid>
    <authcode>12345</authcode>
    <preauth>0</preauth>
    <dateofpayment>2023-01-18 15:26:11</dateofpayment>
    <totalpaid>300</totalpaid>
    <success>1</success>
    <failurereason/>
    <carddetails>
      <cardholdername>Neil+Hickman</cardholdername>
      <cardtype>vs</cardtype>
      <cardlast4>0000</cardlast4>
      <cardexpdate>042024</cardexpdate>
      <cardstartdate/>
      <cardissuenumber/>
    </carddetails>
  </transaction>
</wpmpaymentrequest>
```

**Comment by Panamus** [comment]
@tn3rb I've managed to get around this by creating a custom shortcode that doesn't use `requestParams` to get the payment method and the reg url. 

Not ideal, but until I can figure out what's causing the XML to pollute the request this remains an issue. 

I have a feeling it's something to do with the `<![CDATA[]]>` tags not being escaped correctly.

**Comment by tn3rb** [comment]
ya it looks like our request object is mangling the XML
you could just get your GET / POST values directly from the super global instead of using our Request object. (ie: use `$_GET` and `$_POST` directly)

**Comment by Panamus** [comment]
> ya it looks like our request object is mangling the XML you could just get your GET / POST values directly from the super global instead of using our Request object. (ie: use `$_GET` and `$_POST` directly)

It's the `[ESPRESSO_TXN_PAGE]` shortcode that is erroring out. While we can create a custom shortcode to replace it, that would be replacing a critical page shortcode and isn't ideal. 

We have got it working, but I think this one is definitely a bug.
