### ISSUE TITLE
Help Text on questions

### ISSUE THREAD

**Issue by Panamus** [eventespresso/event-espresso-core#4120]
**Is your feature request related to a problem? Please describe.**

A common feature of most forms is the ability to add further help text assist users understand what is expected from a form field. 

**Describe the solution you'd like**

Add helptext as an option for a question so that additional information can be shown with the label and the field.

**Describe alternatives you've considered**

I appreciate that the question text does allow HTML, but that doesn't provide enough flexibility here to be able to add text under the field it just adds it within the label.

Currently trying to implement this in a custom add-on that we're building. but it seems silly to have an extra plugin just for this when it's a simple feature.

I've created a class extension for `EE_Question` and a model extension for `EEM_Question` and added a DMS (which still for the life of me I can't get running)

```php
<?php

class EEE_Question extends EEE_Base_Class
{
    public function __construct()
    {
        $this->_model_name_extended = 'Question';
        parent::__construct();
    }

    /**
     * Return the help text for a question
     * 
     * @return @string
     */
    public function ext_get_helptext()
    {
        $this->set('QST_helptext');
    }
}
```

```php
<?php

class EEME_Question extends EEME_Base
{
    public function __construct()
    {
        $this->_model_name_extended = 'Question';
        $this->_extra_tables = array(
            'Question_Meta' => new EE_Secondary_Table('esp_question_meta', 'MQST_ID', 'QST_ID')
        );
        $this->_extra_fields = array('Question_Meta' => array(
            'MQST_ID' => new EE_DB_Only_Int_Field('MQST_ID', __('Question Meta Row ID', 'event_espresso'), false),
            'MQST_ID_fk' => new EE_DB_Only_Int_Field('QST_ID', __('Foreign Key to Question', 'event_espresso'), false),
            'QST_helptext' => new EE_Plain_Text_Field('QST_helptext', __('Helptext', 'event_espresso'), false)
        ));
        parent::__construct();
    }
}
```

```php
<?php

use EventEspresso\core\services\database\TableAnalysis;
use EventEspresso\core\services\database\TableManager;

class EE_DMS_Ld_WP_Users_1_0_1 extends EE_Data_Migration_Script_Base
{
    /**
     * EE_DMS_Ld_WP_Users_1_0_1 constructor.
     * 
     * @param TableManager  $table_manager
     * @param TableAnalysis $table_analysis
     */
    public function __construct(TableManager $table_manager = null, TableAnalysis $table_analysis = null)
    {
        $this->_pretty_name = esc_html__('Data Update to Ld 1.0.1', "event_espresso");
        $this->_priority = 10;
        $this->_migration_stages = array();
        parent::__construct();
    }

    public function can_migrate_from_version($version_array)
    {
        $version_string = $version_array['Ld_WP_Users'];
        if (version_compare($version_string, '1.0.2', '<')) {
            return true;
        } else if (!$version_string) {
            return false;
        } else {
            return false;
        }
    }

    public function schema_changes_before_migration()
    {
        $table_name = 'esp_question_meta';
        $sql = "MQST_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
                    QST_ID int(10) unsigned NOT NULL,
                    QST_helptext text NOT NULL,
                    PRIMARY KEY  (MQST_ID);";
        $this->_table_is_new_in_this_version($table_name, $sql);

        return true;
    }

    public function schema_changes_after_migration()
    {
        return true;
    }

    public function migration_page_hooks()
    {
    }
}
```

However I'm at this point unsure how we'd add this to the settings form when adding/editing a question field.

**Comment by tn3rb** [comment]
Hi again @Panamus,

What's getting returned for `$version_string` in `can_migrate_from_version()` ???
As well, what does version `1.0.2` represent? IS that the current version of your addon? IF so, then that version compare is likely returning `false`;

what happens if you try:

```php
version_compare($version_string, '1.0.2', '>=')
```

everything else in this file looks great and I can't see why it would be causing you issues.
sure would be great to be able to see all of the code together.
anyway you can fork your repo to another account and add me as a user there?

**Comment by tn3rb** [comment]
re: help text on questions...

sorry you are having so many troubles with things. The code you have shown me all appears to be fine. That said, instead of adding a model extension for questions to essentially add one field, you could simply use the existing Extra Meta model which is auomatically joined to every other non-abstract model. So you can add/get/edit/delete meta data for any EE entity object using the following methods:

- `EE_Base_Class::add_extra_meta()`
- `EE_Base_Class::get_extra_meta()`
- `EE_Base_Class::update_extra_meta()`
- `EE_Base_Class::delete_extra_meta()`

so in the case of questions, assuming you have a valid `EE_Question` object you can simply do something like:

```php
        $question->add_extra_meta(
            LD_WPU_META_KEY_HELP_TEXT, // constant so that key doesn't get misspelled 
            'actual help text',
            true // enforce unique entry (no duplicates)
        );
```

wherever you process your admin logic for the questions.

Then to inject the help text into the frontend registration form, you could use the `FHEE__EE_SPCO_Reg_Step_Attendee_Information___generate_question_input__input_constructor_args` filter to modify the form input arguments:

so something like:

```php

add_filter(
    'FHEE__EE_SPCO_Reg_Step_Attendee_Information___generate_question_input__input_constructor_args',
    function(
        array $form_input_args, 
        EE_Registration $registration, 
        EE_Question $question, 
        ?EE_Answer $answer = null
    ): array {
        $help_text = $question->get_extra_meta(
            LD_WPU_META_KEY_HELP_TEXT,
            true
        );
        if ($help_text) {
            $form_input_args['html_help_text'] = $help_text;
            $form_input_args['html_help_class'] = 'css-class'; // default = "description"
            $form_input_args['html_help_style'] = 'inline css';
        }
        return $form_input_args;
    },
    10,
    4
);
```

**Comment by Panamus** [comment]
Hi @tn3rb thanks for getting back to me.

> What's getting returned for $version_string in can_migrate_from_version()

Absolutely nothing, because it seems `can_migrate_from_version` isn't being called at all. Tried throwing in `EEH_Debug_Tools` in there and getting nothing, as well as a few other debugging plugins i've got on the go. nothing picks up the call.

> anyway you can fork your repo to another account and add me as a user there?

I'll see what I can do. It wasn't allowing me earlier though. 

While we're on the subject, this whole thing is supposed to allow users to add help text to forms. I have no idea how I'd then go about updating the admin question form to allow the capture of that data.

Since I posted this issue I have located a way to hardcode fields to display the help text we need. But it's far from elegant.

```php
<?php

add_action('AHEE__EE_Form_Input_Base___construct_finalize__end', 'input_extra_attributes');

function input_extra_attributes($input)
{
    if (!is_admin()) {
        $label = $input->html_label_text();

        if (strtolower($label) == 'field label') {
            $input->set_html_help_text(esc_html__('help text goes here!', 'event_espresso'));
        }

    }
}

```

obviously there's already the information there to do this, It was a bit strange that this wasn't already part of the question form in the admin.

**Comment by tn3rb** [comment]
is your DMS script registered during addon registration? ie: when you call `EE_Register_Addon::register()`

Should have something like:

```php
EE_Register_Addon::register(
    'Promotions',
    [
        'version' => 1.0.2 // <<< current addon version
        'dms_paths' => ['/path/to/your/data_migration_script_folder/'],
```

**Comment by tn3rb** [comment]
as an alternate way to get me a copy of your codebase, maybe you can zip it all up and use one of these online "send big file" services to email it to me: brent@eventespresso.com

**Comment by Panamus** [comment]
> 

Yep

```php
<?php

EE_Register_Addon::register(
    'Ld_WP_Users',
    array(
        'version' => EE_LD_WP_USERS_VERSION,
        'min_core_version' => '4.10.40p',
        'main_file_path' => EE_LD_WP_USERS_PLUGIN_FILE,
        'admin_callback' => 'additional_admin_hooks',
        'module_paths' => array(
            EE_LD_WP_USERS_PATH . 'EED_Ld_WP_Users_SPCO.module.php',
        ),
        'autoloader_paths' => array(
            'EE_Ld_WP_User_Integration' => EE_LD_WP_USERS_PATH . 'EE_Ld_WP_Users.class.php'
        ),
        'model_paths' => array(EE_LD_WP_USERS_CORE . 'db_models'),
        'class_extension_paths' => array(EE_LD_WP_USERS_CORE . 'db_class_extensions' . DS),
        'model_extension_paths' => array(EE_LD_WP_USERS_CORE . 'db_model_extensions' . DS),
        'dms_paths' => array(EE_LD_WP_USERS_CORE . 'data_migration_scripts' . DS),
        'shortcode_paths' => array(EE_LD_WP_USERS_PATH . 'EES_Ld_Txn_Page.shortcode.php'),
    )
);

```

**Comment by tn3rb** [comment]
# 🤦🏻 oh dear...

```php
'dms_paths' => array(EE_LD_WP_USERS_CORE . 'data_migration_scripts' . DS),
```

the folder name was `database_migration_scripts`

**Comment by Panamus** [comment]
🤦🏻

I've probably been staring at that for days too... Sorry!!

Well, now that's sorted... I can confirm that it works just fine!

Definitely a can't see the forest for the trees kinda deal!

Now to see if I can hook up the form and get the question populating the help text.

**Comment by tn3rb** [comment]
let me keep poking around and see what other thigns I can fix up for you

**Comment by tn3rb** [comment]
ok here's some of my recommended changes...

i can push these directly to your repo if you like but i had to move everything up a folder

actually... let me just do that because it might be easier for you to copy over changes

**Comment by tn3rb** [comment]
ok created a PR on the repo for you

**Comment by Panamus** [comment]
Appreciate it thanks @tn3rb!
