### ISSUE TITLE
Implement greenkeeper.io

### ISSUE THREAD

**Issue by nerrad** [eventespresso/event-espresso-core#414]
**Is your feature request related to a problem? Please describe.**

https://greenkeeper.io is a service that sits between npm and github and will automatically create pull requests for any package updates occurring in npm (which would then run tests so we can see if the package update breaks anything).  This automates package updates for us and we only have to attend to updates as needed.

Won't take long to implement and is free for all public repositories.

**Comment by nerrad** [comment]
Other tools that may be useful as well (only listing tools that are free for public repos):

- https://codeclimate.com/quality/
- https://renovatebot.com/ (possible alternative to greenkeeper).

**Comment by nerrad** [comment]
I might actually try renovate first.  I like the fact that it creates pull requests only vs greenkeeper which could do a pull request OR issue (depending on nature of dependency changes).  Greenkeeper would require turning on running tests against branches along with pull requests which means we'd see duplicate test runs on pull requests (which slows down test completion).

**Comment by nerrad** [comment]
Another option is dependabot which monitors dependencies for php as well as javascript (and other languages too) it also has a free plan. https://github.com/marketplace/dependabot/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW4zNTQ=#pricing-and-setup

**Comment by joshfeck** [comment]
It looks like renovatebot is free 14 day trial only now. Do you want to try dependabot?

**Comment by nerrad** [comment]
ya we could give dependabot a try and see how it goes.

**Comment by nerrad** [comment]
Okay I've implemented dependabot for just ee core for now.  Currently its monitoring both composer.json and package.json.  The pull requests will have a review requested by me and assigned to both me and josh and with the labels `category:assets` and `status:triage`.  They'll appear in the New Issues pipeline (josh can move them into code review if they show up - or I will if I see them before him.).
