### ISSUE TITLE
Only enqueue jQuery countdown plugin if needed

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#415]
Per @joshfeck in Codebase ticket: 
https://events.codebasehq.com/projects/event-espresso/tickets/11463

Right now jQuery countdown.js loads on every SPCO page on the front end. Ideally this should only be enqueued if a countdown timer is actually displayed.

**Comment by lorenzocaum** [comment]
I'm seeing a 404 on this file during registration checkout:

```
/event-espresso-core-reg/core/third_party_libs/jquery.countdown.min.map
```

**Comment by joshfeck** [comment]
Opened PR #649
