### ISSUE TITLE
Fix UXIP option not saving without changing something else on the page

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#416]
Per @Pebblo from Codebase:
https://events.codebasehq.com/projects/event-espresso/tickets/11503

Found here: https://eventespresso.com/topic/user-experience-improvement-program-uxip/

The user reported that the UXIP setting wouldn't save and always defaulted to Yes.

I tested this on one of my test sites and sure enough, when I changed the option to No and saved, it displayed Yes again on reload.

However, if I changed the Org name at the same time (just added a 1 to the name) and saved, it saved the correct option.

After doing the above, the option now saves without having to change anything else on the page.

I don't have any warnings, notices etc for the site from testing.

**Comment by sethshoultes** [comment]
@nerrad can you please take a look?

**Comment by nerrad** [comment]
There were also some [comments made in our slack](https://eventespresso.slack.com/archives/C080L8G68/p1528810769000423) about changing this to default to opt-in vs the current default of opt-out.  Did you want me to change that as well for this ticket?

**Comment by joshfeck** [comment]
p2'ed:
http://p2.eventespresso.com/?p=5141

**Comment by sethshoultes** [comment]
@nerrad yes, please update that to be opt-in, instead of opt-out by default.

**Comment by joshfeck** [comment]
per the discussion in Slack, we're going to try to make this a single checkbox where you check the box to opt-in.

**Comment by nerrad** [comment]
closing in favor of #530
