### ISSUE TITLE
Fix issue with constants related to `EE_Event_Category_Taxonomy`

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#417]
[TopOnline reports](https://eventespresso.com/topic/bug-two-small-bugs-fixes/):
in the file event-espresso-core-reg/core/db_models/EEM_CPT_Base.model.php
on line 2, it reads:
`define('EE_Event_Category_Taxonomy', 'espresso_event_category');`
and it should be, as used everywhere else in EE:
`define('EE_Event_Category_Taxonomy', 'espresso_event_categories');`
The above is problematic only in the same file, where it’s used in the add_event_category() and remove_event_category() methods.

**Comment by mnelson4** [comment]
Pull request https://github.com/eventespresso/event-espresso-core/pull/420 impliments josh's fix

**Comment by sethshoultes** [comment]
@joshfeck can you please test?

**Comment by joshfeck** [comment]
No @sethshoultes , because this cannot be tested.

**Comment by mnelson4** [comment]
My bad for missing this- the PR has unit tests that test it, I just didn't get around to merging the associated PR after it passed code review. But I just merged it now.
