### ISSUE TITLE
improvements for conference registration

### ISSUE THREAD

**Issue by minkah1** [eventespresso/event-espresso-core#4170]
At Arnes we organize a free, 3-day conference with many lectures and workshops. 

This conference is organized for teachers who receive a certificate of attendance at the end of the conference. To obtain this certificate, they must register through the single sign of one.
At the same time, this conference is also organized for researchers who do not have the option of single sign one, so they are not logged into Wordpress when registering and do not need this type of certificate.

1. In the current version of Event Espresso, we really miss the feature where there are several different lectures within one event (eg Day 1) and the individual is limited to buying a maximum of one ticket for each lecture. Instead of a drop-down menu of available options, we would prefer to be able to select several different tickets, using checkboxes.
2. We would like to disable option for our users from registering multiple times for the same events with one e-mail. So that only one registration with one email is possible.
4. We would like to disable the option to change the autofill data from sso in the registration form.
5. We would like to be able to customize data for csv export (to add username etc.), because we need it to issue certificate of attendance.

**Comment by garthkoyle** [comment]
Hi Minkah, can you break out these requests into individual github issues so they can be discussed and tracked individually? I'll meet with our development team about them.

**Comment by minkah1** [comment]
Hi @garthkoyle, I formed them into individual github issues.

**Comment by garthkoyle** [comment]
thank you
