### ISSUE TITLE
customizable data for csv export 

### ISSUE THREAD

**Issue by minkah1** [eventespresso/event-espresso-core#4174]
At Arnes we organize a free, 3-day conference with many lectures and workshops.
This conference is organized for teachers who receive a certificate of attendance at the end of the conference. To obtain this certificate, they must register through the single sign of one.
At the same time, this conference is also organized for researchers who do not have the option of single sign one, so they are not logged into Wordpress when registering and do not need this type of certificate.

We would like to be able to customize data for csv export (to add username etc.), because we need it to issue certificate of attendance.

**Comment by garthkoyle** [comment]
> We would like to be able to customize data for csv export (to add username etc.), because we need it to issue certificate of attendance.

Here is a snippet that may do what you need: https://gist.github.com/hreidco/4b6f5f2a7f9f0337e6d2650b428cebe1

Does that help?

**Comment by garthkoyle** [comment]
Closing this for now. Let me know if you have more questions or need more help.

**Comment by garthkoyle** [comment]
https://github.com/eventespresso/cafe/issues/1784
