### ISSUE TITLE
 Maximum number of tickets

### ISSUE THREAD

**Issue by minkah1** [eventespresso/event-espresso-core#4178]
Hello,
I have question regarding the maximum number of tickets. Even though I change the limit in the general event settings, the maximum number still shows as 255 for individual events. Do you have experience with this issue?

**Comment by garthkoyle** [comment]
I replied to your email.

Where did you set the maximum number of tickets? There is no limit on the number of tickets that can be sold. It sounds like to me you are confusing the Maximum Number of Tickets Allowed Per Order for This Event, which is simply a setting in the ticket selector of how many tickets someone can purchase during a single checkout, not the number of tickets that can be sold (I think that sets a maximum number of tickets in the ticket selector at 255, again per order, not the number of tickets that can be sold for each event nor the number of the type of events that can be created).

![image](https://github.com/user-attachments/assets/990fdacd-ea30-4591-aa80-50f515d28f8a)
