### ISSUE TITLE
Fix Invalid field (count) passed to constructor of `EE_Term_Taxonomy`

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#418]
[TopOnline reports](https://eventespresso.com/topic/bug-two-small-bugs-fixes/):

in event-espresso-core-reg/core/db_models/EEM_CPT_Base.model.php on line 323, it reads:
`'count' => 1,`
This throws an `EE_Error` Exception:
```
Invalid field (count) passed to constructor of EE_Term_Taxonomy. Allowed fields are :term_taxonomy_id, term_id, taxonomy, description, parent, term_count
```
as the error indicates, it should be:
`'term_count' => 1,`
according to the model, in file event-espresso-core-reg/core/db_models/EEM_Term_Taxonomy.model.php
on line 66:
`'term_count' => new EE_Integer_Field(`

**Comment by sethshoultes** [comment]
@mnelson4 want to fix this really quick?

**Comment by mnelson4** [comment]
https://github.com/eventespresso/event-espresso-core/pull/419 implements josh's fix

**Comment by sethshoultes** [comment]
@joshfeck can you please test?

**Comment by joshfeck** [comment]
No, sorry @sethshoultes . Please see the discussion in the pull request ( #419 ) The fix cannot be tested because the method with the bug in it isn't used by EE core anywhere.

**Comment by mnelson4** [comment]
ya, I should have noticed that. The associated pull request has been merged into master so this is resolved (it has unit tests to verify this works)
