### ISSUE TITLE
Translation Issue in Registration Form - Personal Information Fields Not Translating

### ISSUE THREAD

**Issue by minkah1** [eventespresso/event-espresso-core#4180]
Description:
We are encountering an issue when attempting to translate the fields in Question Group #1 ("Personal Information") in the registration form. The fields First Name, Last Name, and Email Address are not being translated.

Steps we followed:

Navigated to Event Espresso > Registration Form > Questions.
Edited the relevant fields and added translations.
Saved the changes.
However, despite saving the translations, these fields continue to appear in English on the website.

Could you assist in resolving this issue?

**Comment by garthkoyle** [comment]
Hi Minkah, I'm not able to reproduce this doing the same as you described. Here is my translation in the admin and on the front-end: 

Back-end: 
<img width="722" alt="image" src="https://github.com/user-attachments/assets/f95881ca-f2bf-4de0-8089-b3ab9b05e0cf">

What type of caching do you have on the server?


Front-end:
<img width="459" alt="image" src="https://github.com/user-attachments/assets/0f8be2d6-748b-40f9-bdb1-c684c10319c6">
