### ISSUE TITLE
Build facetwp integration

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#422]
Codebase https://events.codebasehq.com/projects/event-espresso/tickets/11454

Per @joshfeck 

This could make it so facetwp results for EE event queries exclude expired events. This could also add some template helpers for displaying things like dates and other event related data that's not in post data or post_meta.

https://facetwp.com/
https://github.com/FacetWP

**Comment by joshfeck** [comment]
We can track interest and ideas on this trello card. Once we're ready to start planning we'll reopen this issue.
