### ISSUE TITLE
Migrations: Change DMS so that EE3 events with "Deleted" status and their associated data do not get migrated

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#423]
Codebase https://events.codebasehq.com/projects/event-espresso/tickets/10290

Per @joshfeck 

One site in particular had a series of recurring events that was made by mistake (one event every day for 20 years). The series was quickly deleted by clicking on the "Delete all events in this series" link. This doesn't really delete the events, it acts more like the Trash bin in WP. When they tried to migrate to EE4, it was extremely slow even though they had more than sufficient server resources.

I think before there's an EE4 REM add-on the migrations scripts need to ignore these deleted events because if there is a significant amount of deleted events in EE3 it can have a negative impact on the migration experience. They either have to wait a really long time to migrate unwanted data, or go through and perm. delete potentially hundreds or thousands of events that they thought were deleted.

Per @mnelson4 

I think this should just require changing `EE_DMS_4_1_0_events::_migration_step()`'s query to NOT migrate  events where `event_status="D"`, and maybe where `is_active='Y'`. Also need to make sure we don't migrate registrations, questions group relations, datetimes or anything else from those events

**Comment by mnelson4** [comment]
PR was merged in
