### ISSUE TITLE
Assigning event category by slug, which also exists as regular post category, creates duplicates

### ISSUE THREAD

**Issue by youri--** [eventespresso/event-espresso-core#432]
Using EE version 4.9.61.p.

**Description of bug**
When using custom code to assign an event category (using slug) to an event, EE looks up the term by slug/name to get an ID. It however fails to specify its own taxonomy in this query (ie. 'event_espresso_categories'), so if there is a regular post category with this same slug, it will fetch that. 

After that it will try to fetch the term_taxonomy record for the term with the previously retrieved ID and its own taxonomy ('espresso_event_categories'). Of course when the term initially gotten is a regular post category, there's no relationship with the espresso_event_categories taxonomy, so this returns `null`.

Subsequently, the code assumes the EE category therefore doesn't yet exist and creates a new category with the same slug.

The next time we try to add this same category to an event, the same thing will happen, and yet another category will be created.

**Expected behavior**
The lookup for an existing term should specify the taxonomy 'espresso_event_categories', so it stays within its own taxonomy.

**To Reproduce**
1- Use the WP admin to add a new, regular, post category with the slug "security".
2- Use the WP admin to add a new Event Espresso Category with the slug "security".
3- Use custom PHP code to get or create an EE_Event object and add an existing event category to it:

```
$new_event = EE_Event::new_instance( array(
	'EVT_name' =>  'Event Name',
	'EVT_desc' =>'Some text',
	'EVT_display_ticket_selector' => 0,
	'EVT_external_URL' => 'http://google.com/',
) );
$new_post_id = $new_event->save();

$new_event->add_event_category( 'security' );
```

This will call in turn call method `add_event_category()` in EEM_CPT_Base.model.php.

**Additional context**
in the file `event-espresso-core-reg/core/db_models/EEM_CPT_Base.model.php` starting on line 293:
```
        $term = EEM_Term::instance()->get_one(array(
            array(
                'OR' => array(
                    'name' => $category_name,
                    'slug' => $category_slug,
                ),
            ),
        ));
```
This doesn't specify the taxonomy, so it matches regular post categories as well. If that happens, and a term from the 'category' taxonomy (regular post category) is fetched, then when the term_taxonomy is looked up, it fails, because there's obviously no relationship between a regular category term and a espresso_event_categories term.
```
        $term_taxonomy = EEM_Term_Taxonomy::instance()->get_one(array(
            array(
                'term_id'  => $term->ID(),
                'taxonomy' => EE_Event_Category_Taxonomy,
            ),
        ));
```
It is then created as a new term, with a new_instance/save call.

**Stack**
```
EEM_CPT_Base.model.php:325, EEM_Event->add_event_category()
EE_CPT_Base.class.php:125, EE_Event->add_event_category()
taf.php:1405, taf::post_form_shortcode()
shortcodes.php:319, do_shortcode_tag()
shortcodes.php:197, preg_replace_callback()
shortcodes.php:197, do_shortcode()
class-wp-hook.php:286, WP_Hook->apply_filters()
plugin.php:203, apply_filters()
post-template.php:240, the_content()
page.php:169, include()
template-loader.php:74, require_once()
wp-blog-header.php:19, require()
index.php:17, {main}()
```

**Environment:**
 - Version of WordPress: 4.9.5
 - PHP Version 7.1

**Comment by mnelson4** [comment]
thanks for the bug report @youri--, I'll convert your sample code into a unit test and try to resolve it

**Comment by mnelson4** [comment]
this should be addressed by https://github.com/eventespresso/event-espresso-core/pull/434

**Comment by mnelson4** [comment]
PR merged into its parent

**Comment by mnelson4** [comment]
PR (https://github.com/eventespresso/event-espresso-core/pull/434) merged into master
