### ISSUE TITLE
Create Class or Helper for Donations Feature

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#438]
See original Codebase ticket https://events.codebasehq.com/projects/event-espresso/tickets/3455

Per @tn3rb 

If an event has the EVT_donations boolean flagged in the event_meta table, then we need to add a text field somewhere in SPCO for a donation amount to be entered.
This would then be added to the cart total. The value for the donation would be saved in the txn_meta table.

Per @lorenzocaum 

Not sure if this was filed separately but how about a generic variable pricing option?

It would be nice to have a minimum value flag and this would cover these use cases:

pay what you want
variable donations

Another customer request:
https://secure.helpscout.net/conversation/317600381/304923/

Notes from @tn3rb to implement just the donate feature:

SPCO is already setup now to accept a change in the total price that is sent to gateways

which was added because of the Promotions addon
so I think we would need the following:

a text input that gets added to the Payment Options SPCO step for entering the payment amount
ability to tag TXNs as having received a donation and record that amount, likely as a new field on the transaction table
modifications to any logic that calculates TXN totals and/or amounts owing so that the donation amount can be factored out
changes in the admin UI to display donation amounts in the TXN details, and maybe TXN admin list table
new field on TXN table would require changes to the next DMS
here's a rewrite of the points:
1. plan out UI changes where donation amounts will be displayed in the admin
2. plan out UI changes to checkout where donations will be input/accepted
3. add new TXN_donations field to EEM_Transaction and modify esp_transaction in upcoming DMS
4. add boilerplate to EE_Transaction for new field as well as for recording additional donation details in meta data (allows multiple donations)
5. add class for injecting donation amount input into SPCO payment options reg step form and processing it upon submission
6. add class for implementing changes to admin UI
7. add class for modifying any logic that calculates TXN totals and/or amounts owing so that the donation amount can be factored out (so that TXNs do not appear as being under or overpaid, etc)
8. add any action or filter hooks required by the above classes for modifying existing code

steps 3-8 will take 30-40 hours

**Comment by joshfeck** [comment]
Donations are possible with the Price Modifier add-on (available from a third party).

We'll continue to track interest for these two donation-related feature ideas:
https://trello.com/c/qO6ExJor/14-pay-what-you-want-donation-option
https://trello.com/c/XcpKD3aI/26-write-in-donations
