### ISSUE TITLE
Customer request: Display prices with taxes consistently across the checkout

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#441]
Per @joshfeck 

This customer left some feedback about how the prices with tax are displayed during the registration process:

They noted that the tax is included in price that labeled in the ticket selected (without itemization or mention that tax is added)
http://monosnap.com/image/InX5cPk7O9BtVVTEl79SATQFwqS3F3

Then later when you fill out the reg forms the tax is not included with the ticket price:
http://monosnap.com/image/Uk2h10eAGDz74xP1AlbVwe0jDQkF0O

Further suggestions:

> Would be ideal if this was the same across all steps, and ideally
> stated which it was doing. Secondly, as a feature request I guess;
> would be the ability to either include or exclude the tax amount from
> the shown price with notification of which way round that was
> happening.

http://eventespresso.com/topic/ee4-tax-administration/

We really need to be careful about changing defaults at this stage.

Per @lorenzocaum 

Also requested here:

http://eventespresso.com/topic/ee4-and-how-taxes-are-displayed/
http://eventespresso.com/topic/checkout-show-prices-with-tax/
https://eventespresso.com/topic/payment-notification-and-payment-options-page-adjustment/#post-146558

**Comment by joshfeck** [comment]
also previously reported in https://events.codebasehq.com/projects/event-espresso/tickets/8422

**Comment by joshfeck** [comment]
We do have filters now where prices are displayed so at the very least this may be something that can be controlled via a filter function. 

Ideally though, we could use the existing settings for how taxes should be displayed across checkout, instead of using the settings for how prices are displayed in the ticket selector only.
