### ISSUE TITLE
Add or alter a hook/filter for attendee data on the payment screen

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#442]
See original Codebase ticket https://events.codebasehq.com/projects/event-espresso/tickets/6858

Per @Apina 

I hope I havent missed an existing one, but at the payment screen there are various filters to allow modification of the price, but nothing seems to allow access to the attendee data at the same time. As such whicle you can modify the price there doesnt seem to be a way to base that modification on any thing.

Forum post http://eventespresso.com/topic/fetch-attendee-info-at-payment-options-screen-ee4/#post-123177

I looked at event-espresso-core-reg/modules/single_page_checkout/templates/registration_page_payment_options.template.php and the other templates in the SPCO folder.

**Comment by joshfeck** [comment]
I checked the original request in the forums, and they said they wanted to:
> Basically I would like to grant a discount based on the user information.

They could use the existing `FHEE__EED_Single_Page_Checkout___initialize_checkout__checkout` hook.
