### ISSUE TITLE
allow users to add more tickets from SPCO

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#443]
See original Codebase ticket https://events.codebasehq.com/projects/event-espresso/tickets/3267

Per @joshfeck 

Pretty sure MER for EE4 does this, right? Except I guess where you have one event (and no MER installed), and you've selected a few tickets, and you want to change your ticket selection quantities somewhere later along the way through SPCO. So this might be something where we could add a navigation button to direct them over to a ticket selector where they can change quantities.

I'd say for now anyone requesting this could install Multi Event Registration.

**Comment by joshfeck** [comment]
Closing this because customers have not actually requested this, and MER adds this feature anyway.
