### ISSUE TITLE
Investigate EE_SPCO_Reg_Step_Attendee_Information – process_reg_step – 598 for some users

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#446]
Codebase https://events.codebasehq.com/projects/event-espresso/tickets/8268

Per @Pebblo 

This is the thread I'm working on currently: http://eventespresso.com/topic/split-many-failed-transactions/#post-158975

But this has come up before and we've been unable to find a specific cause.

With this user if he registers onto any event from his office network, the above error is shown.

He added some further details to the thread:

Front end error message
> An error has occurred: Your form data could
> not be applied to any valid registrations.
> EE_SPCO_Reg_Step_Attendee_Information – process_reg_step – 598
 

Admin error message 
> An error has occurred: An event id was not
> provided or was not received. Please click the back button on your
> browser and try again. EED_Ticket_Selector – process_ticket_selections
> – 530

The transactions session shows:
```
Transaction Session Details
Registration Session	3sskge9qoomjimp5vbhk7hknc4
Transaction placed from IP
Registrant User Agent
Registration Step Progress
Attendee Information : Initiated May 29, 2015 7:57 am
Payment Options : Completed
Finalize Registration : Completed
```

But this is the same for an Incomplete/Failed (REG/TXN) on my sites

I asked him to connect a computer directly to his router, bypassing any firewall/proxy, which he apparently has done and got the same results.

If he registers from his home network, or using a mobile device (not using the office wifi) it works.

If I register onto his test event here: http://pssc.vfair.sg/events/test-webinar-the-economist-service-scholarship/ I register without any issue.

The user is concerned that for users running into this issue they can't register and the attendee details aren't captured for him to contact them, he's requested if it would be possible to enable logging to write the attendee details to a file either before attempting to add them to the DB, or when that error is shown? Is that something we could add?

Per @tn3rb 

ya that's probably not a bad idea... pretty sure this is some kind of cookie/session issue on their work network, but i can investigate that angle of this issue some more as well.

**Comment by joshfeck** [comment]
I read over the support topic from 2015 and it looks like this is an issue where the session was reset, and some conflation about "failed" transactions.
