### ISSUE TITLE
Fix PayPal Pro gateway so it sends the correct value for the State/Province field

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#453]
Currently the PayPal Pro gateway sends the full state/province name instead of the expected state/province code. Examples:

https://developer.paypal.com/docs/classic/api/state_codes/#usa
https://developer.paypal.com/docs/classic/api/state_codes/#canada

**Comment by sethshoultes** [comment]
@Pebblo is this something you can fix?

**Comment by joshfeck** [comment]
possibly related: #1302

**Comment by joshfeck** [comment]
https://eventespresso.com/topic/paypal-payments-pro-not-sending-state/
