### ISSUE TITLE
Only load .php files in the Collection Loader

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#467]
Reported here: https://eventespresso.com/topic/website-crash-2/

In short, it looks like the Collection Loader is loading more than just PHP files

To reproduce go to `/event-espresso-core-reg-git/core/domain/entities/shortcodes`

Add a `.listing` file to that directory (which may be created by Wget) and then reload the site, you'll see:

```
An EventEspresso\core\exceptions\InvalidClassException was thrown!   code: CollectionLoader - loadClassFromFQCN - 295
"The "\EventEspresso\core\domain\entities\shortcodes\.listing" Class is either missing or invalid."
click to view backtrace and class/method details 
/wp-content/plugins/event-espresso-core-reg-git/core/services/collections/CollectionLoader.php   ( line no: 295 )
```

**Comment by joshfeck** [comment]
I found something similar in the wild today:
`Fatal error: Uncaught exception 'EE_Error' with message 'No Class name was specified while registering an autoloader for the following path: /wp-content/plugins/eea-promotions/core/db_model_extensions/error_log.' in /wp-content/plugins/event-espresso-core-reg/core/helpers/EEH_Autoloader.helper.php:111 Stack trace: #0 /wp-content/plugins/event-espresso-core-reg/core/libraries/plugin_api/EE_Register_Model_Extensions.lib.php(86): EEH_Autoloader::register_autoloader(Array) #1 /wp-content/plugins/event-espresso-core-reg/core/libraries/plugin_api/EE_Register_Addon.lib.php(767): EE_Register_Model_Extensions::register('Promotions', Array) #2 /wp-content/plugins/event-espresso-core-reg/core/libraries/plugin_api/EE_Register_Addon.lib.php(280): EE_Register_Addon::_register_models_and_extensions('Promotions') #3 /wp-content/plugins/eea-promotions/EE_Promotions.class.php(104): EE_R in /wp-content/plugins/event-espresso-core-reg/core/helpers/EEH_Autoloader.helper.php on line 111`

In this case it was an error_log file added by the server.

**Comment by joshfeck** [comment]
and another report:

```
Fatal error: Uncaught exception 'EE_Error' with message 'No Class name was specified while registering an autoloader for the following path: /wp-content/plugins/eea-promotions/core/db_models/error_log in /wp-content/plugins/event-espresso-core-reg/core/helpers/EEH_Autoloader.helper.php:111
```
