### ISSUE TITLE
Start process for bumping PHP version to 5.5

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#473]
Codebase ticket: https://events.codebasehq.com/projects/event-espresso/tickets/11449

Per @nerrad 

Just created this ticket to keep things bump bumpeting along.    We can take a look at the stats when time rolls around for doing this ticket and determine whether we can bump requirements directly to 5.6 or not but we'll stick with the conservative 5.5 as the next requirement bump for now.

* [ ] Release a version of EE notifying that next release will require PHP 5.x
* [ ] After that release is out, in master bump the PHP requirements in core to PHP 5.x
* [ ] Setup a ticket for the next bumpety bump

**Comment by nerrad** [comment]
@sethshoultes I did some percentage graphs giving the latest stats on phpversions in use but I'm waiting on a response for whether I should post this here or not (see [the convo in slack here](https://eventespresso.slack.com/archives/C02SY781M/p1527173068000274) ).

**Comment by nerrad** [comment]
@joshfeck based on the [charts I posted in slack](https://eventespresso.slack.com/archives/C02SY781M/p1527173009000789), do you think we should just table this ticket for another month and do another review or should we bump to required version of PHP to 5.5 for the next round of updates?

**Comment by joshfeck** [comment]
Seeing that there's more PHP 5.4 installations than PHP 5.5 I do think we should table this for awhile.

**Comment by nerrad** [comment]
Just making note of this nifty thing buddypress did: https://github.com/buddypress/BuddyPress/blob/3efd14b0e8506f2f40827eeaf5571a491dc01565/src/bp-core/admin/bp-core-admin-functions.php#L1117

When I posted about the first negative Organize Series feedback related to me bumping minimum php version requirements in #poststatus slack, I got lots of feedback about the ability for plugins to _prevent_ updating if conditions aren't met.  It does require for the code to be in place in advance of the actual requirements implementation but it'd be good to consider putting in place before our next version bump.  Basically with something like this in place, if people go to update to a version of the plugin that doesn't support requirements, the update would be aborted and the existing version would remain.

We could do a variation of that for EE core management of add-ons as well (including dependencies between add-ons).

**Comment by sethshoultes** [comment]
It's been a few months. Want to look into this again?

**Comment by joshfeck** [comment]
We'll need some new data Seth.

**Comment by joshfeck** [comment]
Just noting here that there's been movement on this in WP core. So as WP core begins to require PHP 5.6+ and so on, new versions of EE can do the same.

**Comment by joshfeck** [comment]
We'll bump the PHP version requirement when either:
1) We need to 
2) WP starts requiring PHP 5.6 or later
