### ISSUE TITLE
Fix [ESPRESSO_EVENT_ATTENDEES] no longer parsing in the calendar content.

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#477]
Reported here: https://eventespresso.com/topic/registered-members-short-code/

In ver 4.9.59+ the [ESPRESSO_EVENT_ATTENDEES] shortcode stopped parsing in the calendar content.

To reproduce just add the above shortcode to an event's description, then view that event on the calendar. The shortcode doesn't parse at all and just shows in the content -  http://take.ms/jKmrWi

Switching to EE core 4.5.58 the shortcode parses as expected.

**Comment by joshfeck** [comment]
Other shortcodes seem fine. The breakage appears to have started with the merge of the Add Bot Detection Middleware branch. https://events.codebasehq.com/projects/event-espresso/tickets/11174

**Comment by Pebblo** [comment]
Apologies, I missed this.

As Josh mentioned standard WP shortcodes work (and other plugins shortcodes) but EE's shortcodes do not.

These work:

```
[restrict]This content is limited to logged in users.[/restrict] (Restrict content Pro)
[gallery]
```

These do not:

```
[ESPRESSO_EVENTS]
[ESPRESSO_EVENTS_TABLE_TEMPLATE]
[ESPRESSO_EVENT_ATTENDEES]
[ESPRESSO_TICKET_SELECTOR event_id=xx]
```

I wouldn't actually expect the first 2 of the second set of shortcodes to work in the calendar anyway but wanted to test various EE shortcodes.

**Comment by joshfeck** [comment]
Possibly related to #529
