### ISSUE TITLE
Work out route specific bundled assets.

### ISSUE THREAD

**Issue by nerrad** [eventespresso/event-espresso-core#485]
## Issue Overview

As we work on the GB integration (and the js build process in general), one issue we run into is that with blocks being registered client side, it doesn't matter how we register things server side because any js loaded in the GB editor is executed.  So for instance if we bundle all our "core" blocks in one bundle, and in that bundle are blocks that are _not_ intended to load in every editor, they _will_ get loaded in every editor anyways.  So how do we resolve this?  Some ideas (not exhaustive, just some of what came to mind as I thought on this problem):

### Option 1: Create route specific bundles.  

Similar to what I did with the `wp-plugins-page` bundle, route specific bundles would be a named bundle that is specific to a given route.  So you might have `wp-post-editor`, `wp-page-editor`, etc.   Downsides is this isn't very dynamic and any cpts would have to manually define what blocks they want included in the webpack config.

### Option 2: Create bundles as we are now, but pass along what blocks would be registered for the route via eejsdata.

In this option, eejsdata would be used to pass along an array of blocks that get loaded for the given route (likely just an array of block keys).   Then in our source, we'd only call `registerBlockType` for those block keys if the block key is included in that server defined array.

An advantage with this option is that it can be more dynamic and we can keep bundles organized somewhat.  A disadvantage is we're still loading a bunch of code that might not even get used on the given route. Another disadvantage is the reliance on the eejsdata global for whether the block loads or not.  This works fine in a browser environment, but what about eventual mobile implementations?

### Option 3: Every block goes in its own bundle.

Instead of grouping blocks together in a single bundle, we build each block into its own bundle.  So for example `event-attendees` might be built to `ee-event-attendees-block.js` and that js only has what's required for that block.  

An advantage to this method is enqueuing is solely controlled server side and blocks would only be enqueued on routes they are used. 

A disadvantage is this increases the number of asset files loaded by the browser.  With `http2` this is actually preferable compared with a monolithic big js bundle, but since http2 still doesn't have widespread adoption yet, I'm not sure we can go this route.

**Comment by tn3rb** [comment]
from chat:

*BUNDLE SEPARATION*

*FRONTEND*

- all-blocks.js/css
- {specific-route}.js/css i.e. may include:
    - EE CPT routes (events, event, venue, etc)
    - checkout
    - thank you page
    - IPN/payments route

*ADMIN*

- all-post-type-blocks.js/css (loaded for every gb editor instance for post types supporting gb)
- {post_type}-blocks.js/css (post type specific blocks)
- {admin-route}.js/css (specific route assets)

the above list does not account for things like our package/vendor bundles
