### ISSUE TITLE
Account for "Index column size too large" database error

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#493]
There was a site that migrated data from EE3 to EE4 and none of the attendee data was migrated into `wp_esp_attendee_meta`. This error was captured when doing the migration:

```WordPress database error: [Index column size too large. The maximum column size is 767 bytes.] CREATE TABLE wp_esp_attendee_meta ( ATTM_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT, ATT_ID BIGINT(20) UNSIGNED NOT NULL, ATT_fname VARCHAR(45) NOT NULL, ATT_lname VARCHAR(45) NOT NULL, ATT_address VARCHAR(255) DEFAULT NULL, ATT_address2 VARCHAR(255) DEFAULT NULL, ATT_city VARCHAR(45) DEFAULT NULL, STA_ID INT(10) DEFAULT NULL, CNT_ISO VARCHAR(45) DEFAULT NULL, ATT_zip VARCHAR(12) DEFAULT NULL, ATT_email VARCHAR(255) NOT NULL, ATT_phone VARCHAR(45) DEFAULT NULL, PRIMARY KEY (ATTM_ID), KEY ATT_fname (ATT_fname), KEY ATT_lname (ATT_lname), KEY ATT_email (ATT_email) ) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci```

```Stack Trace:#0 /wp-content/plugins/event-espresso-core-reg/core/helpers/EEH_Activation.helper.php(671): EventEspresso\core\services\database\TableManager->createTable('esp_attendee_me...', 'ATTM_ID INT(10)...', 'InnoDB ') #1 /wp-content/plugins/event-espresso-core-reg/core/data_migration_scripts/EE_Data_Migration_Script_Base.core.php(647): EEH_Activation::create_table('esp_attendee_me...', 'ATTM_ID INT(10)...', 'ENGINE=InnoDB ', true) #2 /wp-content/plugins/event-espresso-core-reg/core/data_migration_scripts/EE_Data_Migration_Script_Base.core.php(471): EE_Data_Migration_Script_Base->_create_table_and_catch_errors('esp_attendee_me...', 'ATTM_ID INT(10)...', 'ENGINE=InnoDB ', true) #3 /wp-content/plugins/event-espresso-core-reg/core/data_migration_scripts/EE_DMS_Core_4_1_0.dms.php(147): EE_Data_Migration_Script_Base->_table_is_new_in_this_version('esp_attendee_me...', 'ATTM_ID INT(10)...', 'ENGINE=InnoDB ') #4 /wp-content/plugins/event-espresso-core-reg/core/data_migration_scripts/EE_Data_Migration_Script_Base.core.php(419): EE_DMS_Core_4_1_0->schema_changes_before_migration() #5 /wp-content/plugins/event-espresso-core-reg/core/data_migration_scripts/EE_Data_Migration_Script_Base.core.php(323): EE_Data_Migration_Script_Base->_maybe_do_schema_changes(true) #6 /wp-content/plugins/event-espresso-core-reg/core/EE_Data_Migration_Manager.core.php(663): EE_Data_Migration_Script_Base->migration_step(50) #7 /wp-content/plugins/event-espresso-core-reg/core/EE_Data_Migration_Manager.core.php(779): EE_Data_Migration_Manager->migration_step() #8 /wp-content/plugins/event-espresso-core-reg/admin_pages/maintenance/Maintenance_Admin_Page.core.php(362): EE_Data_Migration_Manager->response_to_migration_ajax_request() #9 [internal function]: Maintenance_Admin_Page->migration_step('') #10 /wp-includes/class-wp-hook.php(286): call_user_func_array(Array, Array) #11 /wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #12 /wp-includes/plugin.php(453): WP_Hook->do_action(Array) #13 /wp-admin/admin-ajax.php(99): do_action('wp_ajax_migrati...') #14 {main}Migrated 55 records successfully during Organization Options/Config```

**Comment by joshfeck** [comment]
Possibly related codebase ticket:
https://events.codebasehq.com/projects/event-espresso/tickets/10435

I took a quick glance at the comments in 10435 and it seems this issue is resolved if updating from EE4.9.x to newer 4.9.x. If you're updating from EE3 and it's migrating data to 4.1 the same "WordPress database error: [Index column size too large. The maximum column size is 767 bytes.]" error occurs.

**Comment by mnelson4** [comment]
Addressed by related PR
