### ISSUE TITLE
Avoid PHP fatal error if PHP sessions are not available, notably on Pantheon servers

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#494]
See:
https://pantheon.io/docs/wordpress-known-issues/#php-sessions
and
https://pantheon.io/docs/wordpress-sessions/

tldr; Pantheon requires a plugin to enable PHP sessions. It seems that other plugins that require sessions do not throw a fatal (only a PHP warning) so this would be a nice bit of managing a worse-case scenario if the fatal could be avoided.

**Comment by sethshoultes** [comment]
@mnelson4 is this something you can fix?

**Comment by mnelson4** [comment]
I could investigate a bit, but session-related stuff is usually @tn3rb 's domain

**Comment by mnelson4** [comment]
@joshfeck where does the fatal error happen? I've disabled sessions by adding `ini_set('session.use_cookies', '0');` to my localhost's `wp-config.php`, and I can't register for an event, but have yet to see a fatal error. Or got any tips on how to reproduce the issue?

**Comment by joshfeck** [comment]
One way is get a free Pantheon hosting account (dev sites are free) and don't install their plugin that adds support for PHP sessions. 

This is the error I get if I deactivate that plugin:

```Warning: session_start(): user session functions not defined in /code/wp-content/plugins/event-espresso-core-reg/core/EE_Session.core.php on line 567 ```

```Fatal error: session_start(): Failed to initialize storage module: user (path: ) in /code/wp-content/plugins/event-espresso-core-reg/core/EE_Session.core.php on line 567 ```

**Comment by mnelson4** [comment]
Ok thanks @joshfeck. Ya I'm just reproducing the fatal error on Pantheon's server.
What plugins do you know of that only produce a warning though? I actually didn't know any offhand that even used the session (that I could think of anyway), but found the "Wise Chat" did, but it also had a fatal error on Pantheon.
If you know of any that would probably help me to identify how to fix this

**Comment by mnelson4** [comment]
aha, I've isolated the problem. Pull request imminent. (Although if you do know of any other plugins that don't have the fatal, just a warning, that would still be useful for comparison)

**Comment by mnelson4** [comment]
links useful for reference:
https://www.drupal.org/project/civicrm_starterkit/issues/1978796
https://phppot.com/php/php-session-configuration/
https://wordpress.org/plugins/wp-native-php-sessions/

**Comment by joshfeck** [comment]
It's noted [here](https://pantheon.io/docs/wordpress-sessions/) that WooCommerce uses PHP sessions and requires the Native PHP sessions plugin to work properly on Pantheon. If you deactivate the Native PHP sessions while WooCommerce is activated, no fatal errors though.

**Comment by mnelson4** [comment]
aha, thanks. Yeah I first thought of Woocommerce but didn't see the function `session_start()` called anywhere. I took another look once I knew Pantheon specifically said they used it, and I see they *now* use a custom PHP-session-like class, `WC_Session_Handler`, which actually stores their session data in the database table `wp_woocommerce_session`. 
So it seems they got tired of this error coming up with PHP sessions, and decided to alternatively implement their own sessions!
If my PR for this isn't good enough, I guess that's what we'll need to do

**Comment by sethshoultes** [comment]
@mnelson4 What's the status of this issue? I see that the connected pull request is closed.

**Comment by sethshoultes** [comment]
@joshfeck can you please test this one?

**Comment by joshfeck** [comment]
Actually testing the PR. No need to assign the issue when there's an open PR.

**Comment by mnelson4** [comment]
PR https://github.com/eventespresso/event-espresso-core/pull/620 merged
