### ISSUE TITLE
Message Queue triggers a fatal error if the site is in MM2

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#500]
Whilst testing #489 I've had a site in MM2 for a prolonged period and noticed that the message queue is triggering a fatal:

```
[05-Jun-2018 08:19:18 UTC] PHP Fatal error:  Uncaught EE_Error: Event Espresso Level 2 Maintenance mode is active. That means EE can not run ANY database queries until the necessary migration scripts have run which will take EE out of maintenance mode level 2. Please inform support of this error. in D:\xampp\htdocs\ee4\wp-content\plugins\event-espresso-core-reg\core\db_models\EEM_Base.model.php:2378
Stack trace:
#0 D:\xampp\htdocs\ee4\wp-content\plugins\event-espresso-core-reg\core\db_models\EEM_Base.model.php(1080): EEM_Base->_do_wpdb_query('get_results', Array)
#1 D:\xampp\htdocs\ee4\wp-content\plugins\event-espresso-core-reg\core\db_models\EEM_Base.model.php(954): EEM_Base->_get_all_wpdb_results(Array, 'ARRAY_A', NULL)
#2 D:\xampp\htdocs\ee4\wp-content\plugins\event-espresso-core-reg\core\libraries\messages\EE_Messages_Queue.lib.php(225): EEM_Base->get_all(Array)
#3 D:\xampp\htdocs\ee4\wp-content\plugins\event-espresso-core-reg\core\libraries\messages\EE_Messages_Processor.lib.php(230): EE_Messages_Queue->get_to_send_batch_and_send()
#4 D:\xampp\htdo in D:\xampp\htdocs\ee4\wp-content\plugins\event-espresso-core-reg\core\db_models\EEM_Base.model.php on line 2378
```

To reproduce you can add: `update_option('ee_maintenance_mode', 2);`

In functions.php or a plugin to set EE Mainteance mode lvl 2.

Then visit the front end of the site after a few mins and check your error log.

I don't have messages in the queue for generation/sending but I do have 'Failed Sending, Can Be Retried' (expected with my current local setup).

Not classed as critical as this has no effect on users or the expected behavior (users don't see the error on the front end/admin as its run on WP cron and messages don't send because there was a fatal but messages wouldn't send in MM2 anyway).

**Comment by sethshoultes** [comment]
@mnelson4 and @Pebblo does this need to be tested? Are there testing notes?

**Comment by mnelson4** [comment]
there are testing notes on the PR: https://github.com/eventespresso/event-espresso-core/pull/622. Once the PR is created, basically all discussion continues there. (I just thought we were supposed to keep updating the ticket, which is admittedly a bit silly but that's what I thought we were supposed to do. I'd almost like to have a status for ticket like "has-pull-request" and then we don't need to keep updating them... I'll make a p2 suggesting that)

**Comment by mnelson4** [comment]
PR merged in
