### ISSUE TITLE
Avoid fatal errors related to "The namespace for this manifest file has already been registered"

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#501]
This fatal error has been reported in 3 support topics:
https://eventespresso.com/topic/nav-menu-php-wont-load/
https://eventespresso.com/topic/white-screen-error-on-wp-admin-nav-menus-php/
https://eventespresso.com/topic/problems-when-people-try-to-register-an-event-on-there-mobile-phone/#post-270951

In each case the error happens on a specific admin page related to a specific plugin. So far these are the plugins known to be affected by this bug:

https://wordpress.org/plugins/megamenu/
https://wordpress.org/plugins/wp-megamenu/
https://wordpress.org/plugins/child-theme-configurator/

The first two are affected when viewing the WP > Menu Manager
The third is affected when using the Analyze tool on the Tool > Child Themes pag

**Comment by joshfeck** [comment]
![screen shot 2018-06-05 at 11 39 27 am](https://user-images.githubusercontent.com/891156/40988235-9345090e-68b8-11e8-96a5-0c48f1c0fb9f.png)

**Comment by sethshoultes** [comment]
@tn3rb can you please look into these errors?

**Comment by joshfeck** [comment]
Also reported in a plugin deactivation:
https://secure.helpscout.net/conversation/599822051/538574?folderId=100572
