### ISSUE TITLE
Avoid fatal errors caused by uncaught exceptions related to persistent admin notices

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#505]
This fatal error was reported to support:

```php
Fatal error: Uncaught exception EventEspresso\core\services\collections\DuplicateCollectionIdentifierException’ 
with message ‘The supplied identifier “ca-ab” already exists within this collection.’ 
in /core/services/collections/Collection.php:116 

Stack trace: 
#0 /core/domain/entities/notifications/PersistentAdminNotice.php(312): 
    EventEspresso\core\services\collections\Collection->add(
        Object(EventEspresso\core\domain\entities\notifications\PersistentAdminNotice),
        ‘ca-ab’
    ) 
#1 [internal function]: 
    EventEspresso\core\domain\entities\notifications\PersistentAdminNotice->registerPersistentAdminNotice(
        Object(EventEspresso\core\services\collections\Collection)
    ) 
#2 /wp-includes/class-wp-hook.php(286): call_user_func_array(Array, Array) 
#3 /wp-in in /core/services/collections/Collection.php on line 116
```

The user reported they had just updated to the current version of EE4 and PUE stats showed the prior version was 4.9.48. 

This was what was stored within the `ee_pers_admin_notices` option at the time the fatal error was thrown:

```
a:17:{
	s:30:"php_version_5-3-28_recommended";N;
	s:5:"CA-AB";N;
	s:5:"CA-BC";N;
	s:5:"CA-MB";N;
	s:5:"CA-NB";N;
	s:5:"CA-NL";N;
	s:5:"CA-NS";N;
	s:5:"CA-ON";N;
	s:5:"CA-PE";N;
	s:5:"CA-QC";N;
	s:5:"CA-SK";N;
	s:5:"gb-uk";N;
	s:5:"GB-UK";N;
	s:30:"php_version_5-4-33_recommended";N;
	s:28:"new-state-added-in-tamilnadu";N;
	s:21:"new-state-added-ie-wx";N;
	s:25:"new-state-added-ph-laguna";N;
}
```

**Comment by joshfeck** [comment]
Reported again:
https://eventespresso.com/topic/collection-fatal-error-post-update/

**Comment by sethshoultes** [comment]
@nerrad will you please look into this and see if it's something you can fix within an hour or two.

**Comment by nerrad** [comment]
This will have to go to Brent for fixing.

As far as I can tell, the error indicates that under the right conditions, `Collection->has()` will return false and thus with the conditional usage in `PersistentAdminNotice::registerPersistentAdminNotice`, an object could potentially get added to the collection twice (or maybe have a reference to the object linked to a new identifier).  

The `Collection::has` method checks whether a registered object for the given `identifier` exists.  Whereas the `Collection::add` method (which is ultimately where the exception is getting triggered) is doing a `Collection::contains` check which checks for if there's already that object in the collection.

I'm not sure what fix Brent would want to add here.  One potential fix would be to simply throw a try/catch around the call to `Collection::add` in `PersistentAdminNotice::registerPersistentAdminNotice`.  

Another possible fix may be to make the conditional for `Collection::has` behave consistently with `Collection::add`.  In other words, have `has` do a `contains` check (and ignore identifier) or have the `add` method not do a `contains` check and use `has` instead.

**Comment by sethshoultes** [comment]
@tn3rb will you please help with this issue? Thanks

**Comment by joshfeck** [comment]
This continues to be a problem:

https://eventespresso.com/topic/collection-fatal-error-when-updating-ee-4/

**Comment by tn3rb** [comment]
> The Collection::has method checks whether a registered object for the given identifier exists. Whereas the Collection::add method (which is ultimately where the exception is getting triggered) is doing a Collection::contains check which checks for if there's already that object in the collection.

Ya the purpose of the Collection is to maintain a bunch of unique objects without duplicates which is why we perform a `contains()` check prior to adding. It is intended for object identifiers to also be unique so that either can be used to determine object existence within the Collection. There should probably be an additional `has()` check performed within `Collection ::add()` in the same line of code where we perform the `contains()` check. This would make it impossible to add a new object to the Collection using an identifier that is currently in use by another object.

> Another possible fix may be to make the conditional for Collection::has behave consistently with Collection::add. In other words, have has do a contains check (and ignore identifier) or have the add method not do a contains check and use has instead.

No we would not want to do that because there are times when you do not have the actual object available and only have a known identifier to use in order to check if an object exists in a Collection. The best example of this is Fully Qualified Class Names, where the FQCN is used as the object identifier, and you want to check if the object exists before performing an expensive instantiation.
