### ISSUE TITLE
Preserve double line breaks in venue description when displayed within the event page (maybe add wpautop?)

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#507]
Steps to replicate the issue:

1. Compose a venue description for a Venue CPT and include lots of double line breaks between lines of text. 
2. View the Venue CPT, note that WordPress changes the double line-breaks in the text into HTML paragraphs (`<p>...</p>`). 
3. Assign an event to the Venue
4. View the Event CPT and you'll notice no double line breaks in the Venue description.

I think this may be as simple as adding the `wpautop()` function where the Venue Description is echo'd in the content-espresso_event-venues.php template.

**Comment by mnelson4** [comment]
related PR merged in
