### ISSUE TITLE
GDPR - Remove phone number from the EE Contact when person data erase request is fulfilled.

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#509]
The 'Phone number' answer is not removed from the EE contact when using WP's new GDPR erase feature.

Before - http://take.ms/cds2A

After  - http://take.ms/3dQwD

To reproduce create an event that collects Address info and add a registration using dummy data, be sure to provide the phone number.

Open up the registration in EE and note the email address for the EE Contact.

To reproduce, go to Tools -> Erase Personal Data

Create a request for the above email and force it through.

Now refresh the registration/contact and the Phone number will still be present.

**Comment by mnelson4** [comment]
the PR was merged into master
