### ISSUE TITLE
EE_Event object not attached to post data on ajax requests.

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#529]
Reported here: https://eventespresso.com/topic/ajax-request-return-data-doesnt-include-ee_event-information-in-post-data/

A quick way to reproduce is to use WP Debug bar console and add:

```
$posts = get_posts(array('post_type'=>'espresso_events','suppress_filters'=>false));

var_dump($posts);
```

With master, you'll just get WP_Post objects with no EE_Event objects.

The same code used in a template file returns the WP_Post and EE_event object.

If you switch to 4.9.59.rc.009 you'll get both objects on the same ajax request above, it looks like this was introduced with:

https://events.codebasehq.com/projects/event-espresso/tickets/11174

**Comment by joshfeck** [comment]
Possibly related to #477

**Comment by sethshoultes** [comment]
@Pebblo can you please test?
