### ISSUE TITLE
Add support for new config options for Invisible reCaptcha

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/event-espresso-core#532]
From issue 49 on the Event Smart project.

We need a way to use another constant for Invisible reCaptcha. Invisible reCaptcha is opt-in as in an event organizer that is using the original reCaptcha needs to make the switch on their own and part of doing that is creating a separate set of keys.

**Comment by knazart** [comment]
@lorenzocaum regarding ES - I can fix that, it should still work. But yeah, it could be nice to have a separate `$config->invisible_recaptcha_publickey` for the Invisible recaptcha as it requires a different key from the regular one.

Just to note: I think @tn3rb was the one adding the Invisible reCaptcha to EE Core.

**Comment by tn3rb** [comment]
@knazart 
can you plz link this issue to your pull that adds the new config options

**Comment by knazart** [comment]
Here is the pull: https://github.com/eventespresso/eventsmart.com-website/pull/53

> link this issue to your pull

do you mean in zenhub @tn3rb ?

**Comment by sethshoultes** [comment]
@knazart what's the status of this?

**Comment by knazart** [comment]
Closing this. No work regarding this issue was done on EE core. This Issue was connected (in zenhub) to the PR in the ES repo.
