### ISSUE TITLE
Fix typo in help tab for PayPal Express

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/event-espresso-core#534]
From the WP-admin (WordPress dashboard), go to Event Espresso --> Payment Methods. Then click on the Help tab in the top right and click on PayPal Express.

There is a typo: https://cl.ly/3Y0Y2n2N3C2h

**Comment by sethshoultes** [comment]
@mnelson4 or @knazart can one of you please fix this really quick?

**Comment by mnelson4** [comment]
created https://github.com/eventespresso/event-espresso-core/pull/535 to address this
