### ISSUE TITLE
Apostrophes in Organization Name cause \ to multiple in test emails

### ISSUE THREAD

**Issue by NateWr** [eventespresso/event-espresso-core#54]
If the Organization Name in the settings includes an apostrophe, like ```Nate's Thing```, the name is escaped with a ```\'s``` in the subject of the test email that is sent from the messages interface. When the page reloads, the ```\'s``` will be tripled to ```\\\'s```. This multiplies with each test email sent, so that after several tests it's easy to have so many ```\``` that it can cause memory shortages and make the email un-openable in email clients.

The extra ```\```s persist even if you browse away and come back.

I was unable to test this on ```master``` but can reproduce it reliably on ```4.4.6.p```.

**Comment by nerrad** [comment]
this was fixed and released with 4.4.9
