### ISSUE TITLE
Decaf: adding required questions does not show up at registration checkout

### ISSUE THREAD

**Issue by gettyhub** [eventespresso/event-espresso-core#562]
When going to registration questions and wanting more than First Name, Last Name and Email, and selecting the required information to be added to the checkout, the only questions that show are still only the critical three.

**Comment by joshfeck** [comment]
Hi,

It sounds like you need to go in to edit the event, then check the checkbox next to “Address Information”, located in the Questions for Primary Registrant box on the side of the event editor page.

Here’s a screenshot that shows that option:

![screen_shot_2018-07-04_at_1 38 37_pm](https://user-images.githubusercontent.com/891156/42467781-e195929e-8380-11e8-8563-7cfc9f6802c9.png)
