### ISSUE TITLE
Add recent addon releases to core Extensions & Services page 

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#569]
The following add-ons need to be advertised in the Extensions & Services page:

- Wait List Manager
- PayPal Express Checkout SB
- Authorize.NET Accept addons

**Comment by joshfeck** [comment]
It'd be best to remove the Authnet SIM add-on entry from the Extensions page and replace with Authnet Accept.

**Comment by tn3rb** [comment]
I'm assuming the content for the Add-on descriptions can be obtained from https://eventespresso.com/add-ons/?

**Comment by lorenzocaum** [comment]
We are trying another approach for this page here: https://github.com/eventespresso/event-espresso-core/pull/1721
