### ISSUE TITLE
Improve rewrite slug escaping

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#574]
Originally reported here:
https://eventespresso.com/topic/warning-message-at-the-top-of-the-menu/

Steps to replicate the issue:
- Activate WP_DEBUG
- Switch Site Language to Français
- Refresh permalinks
- View a single post (of any post type), where you'll see PHP warnings like these:

```Warning: preg_match(): Unknown modifier '0' in /srv/www/plugins/public_html/wp-includes/class-wp.php on line 219

Warning: preg_match(): Unknown modifier '0' in /srv/www/plugins/public_html/wp-includes/class-wp.php on line 218
```

I did some troubleshooting and tracked this down to the translation of the `event-type` text string, which is basically an unused taxonomy for the Event Espresso event post type. The [French translation of the string](https://translate.eventespresso.com/projects/event-espresso-4/fr/event-espresso-fr_fr/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=14199&filters%5Btranslation_id%5D=82540) has a space in place of the dash:  `type d'événement`

So it turns out that the escaping used on rewrite slugs should not be `esc_html()`, but instead use something like `sanitize_title()`.  

As mentioned in chat, there's a slight chance this could be a breaking change if there's custom code out there actually relying on an improperly escaped rewrite slug. Probably a very slim chance though.

**Comment by mnelson4** [comment]
PR merged in
