### ISSUE TITLE
MER reg form only displays Primary Registrant Question Groups from first Event

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#577]
See Codebase ticket for full details:
https://events.codebasehq.com/projects/event-espresso/tickets/10377

setup two events that each have a separate set of custom questions asked for the primary registrant
ie:

Event A : Primary Registrant Q Groups = Personal Info + Diet Requirements
Event B : Primary Registrant Q Groups = Personal Info + Medical Information
add one ticket from each to the cart, then checkout
reg form only shows question groups for whichever event ticket got added first

Reported here:
https://eventespresso.com/topic/ee4-multi-event-registration-registration-forms/
https://eventespresso.com/topic/additional-registrant-questions-with-multiple-registration/
https://eventespresso.com/topic/checking-in-on-mer-update/
https://eventespresso.com/topic/only-custom-questions-of-first-added-event-to-cart-are-shown/

@tn3rb can you give an estimate of time to fix please?

**Comment by joshfeck** [comment]
reported here:
https://eventespresso.com/topic/ask-the-primary-registrant-all-the-questions/#post-282944

**Comment by joshfeck** [comment]
This may require the refactor in #856

**Comment by tn3rb** [comment]
setting estimate at medium for the time being, but won't know until this is investigated.
I'm assuming that this will be a bit tricky since it could require refactoring how the reg forms are compiled
