### ISSUE TITLE
Auto-populate a Registration Question with Answers from Another Question

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#580]
Would it be possible to have registration questions linked in a way that the available options are populated from another question?

An example of this would be a registration form for sporting leagues, where a question on the registration form is "Team Name," which is previously populated with a list of known team names, then below that is a field to add your team name (if it's not listed). By adding your team's name, any future registrations will have the option to select their team name from the options.

**Comment by joshfeck** [comment]
Adding something like this would probably require the registration form system refactor, and would also be add-on territory. The add-on could add a new question type where the question type pulls in a list of previously input answers to another question. 

We can track interest on this trello card:
https://trello.com/c/JRcJeJAp/246-new-dropdown-question-type-to-a-list-of-previously-input-answers-to-another-question-on-the-same-registration-form
