### ISSUE TITLE
Filters get applied to first event post only when event post is listed twice on the same page

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#584]
**Describe the bug**

Additional content added via filters on `the_content` is not added after the first time an event is listed on a page using the `[ESPRESSO_EVENTS]` shortcode.

https://eventespresso.com/topic/book-now-button-on-event-missing/

**To Reproduce**

Post content filters should be applied to all posts.
**Example URL**

https://ee4m.eventespresso.com/two-event-category-lists/

Note bulk bag part II's second listing.

**Comment by sethshoultes** [comment]
@mnelson4 is this one you can fix?

**Comment by mnelson4** [comment]
I can certainly help investigate, but it is outside my usual domain

**Comment by mnelson4** [comment]
hmm, I'm not reproducing this issue locally...
![screenshot-laragonee test-2018-08-16-07-39-16](https://user-images.githubusercontent.com/1766382/44215539-9f1bdd00-a127-11e8-87f2-71eee64abe1e.png)
But I see it's still happening on ee4m like in Josh's link (thanks!). So I need to see how my config is different

**Comment by mnelson4** [comment]
I made my template settings the same, but that didn't reproduce. I'm going to make sure I have all the same add-ons active next, and try the same theme.

**Comment by mnelson4** [comment]
hmmm, I've got the same theme, same page template settings, and the same gateways active, (except for all the payment method ones) and am not yet reproducing...

**Comment by mnelson4** [comment]
hmmm, @joshfeck if you have any clues as to why this is happening on ee4m but not on my local site, I'm all ears! Otherwise I'll keep investigating...

**Comment by mnelson4** [comment]
In slack DM, @joshfeck said it's not a really high priority issue then, considering the difficulty of reproducing and the few reports. If we get more reports, or isolate how to reproduce, we can pick it up again.

**Comment by mnelson4** [comment]
@sethshoultes I propose putting this in the "icebox" pipeline until we get another report or more info (@joshfeck suggested that in Slack DM)

**Comment by joshfeck** [comment]
We'll close this until we get more information.
