### ISSUE TITLE
EE_Error::add_error() notices appear in the wrong spot

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/event-espresso-core#586]
## Issue Overview

When using `EE_Error::add_error()` (and possibly other notices setup via `EE_Error`) they always appear ABOVE the page's title, where @knazart and I think below the title would be more natural (see https://github.com/eventespresso/eea-vanco-pm/pull/3#issuecomment-405291003, especially https://monosnap.com/file/0BUkSUD49KDavuDjmzFQ1NwAOXNePX#)

## Bug report or feature request?

* [ ] Bug
* [ ] Feature
* [ ] Neither
* [x] Nitpick

## Environment Data:

Version of EE: 

Version of WordPress: 5.0-alpha

PHP Version:   7.1

Browser used:   Firefox

## Steps to Reproduce (for bugs)

add `EE_Error::add_error()` inside `EE_System::init()` or somewhere. 

## Expected Behaviour

We'd expect the message to appear below the title, that's where messages like this usually appear.

## Current Behaviour

But instead they're above the title.

**Comment by mnelson4** [comment]
This is primarily Brent's code, I think, so he'll probably have some input on this (especially on whether this is a good proposed change, and whether it would be easy. My spidey senses say it would be easy.)

**Comment by sethshoultes** [comment]
@tn3rb do you have any feedback on this change?

@mnelson4 is it something you or @knazart can tackle?

**Comment by mnelson4** [comment]
I can look into it; it might be an easy fix. (Brent would probably be better, but I understand we're trying to free him up)

**Comment by mnelson4** [comment]
Oh ok. Would it make for a more consistent look then if we always put the notices above the title then? Because persistent notices appear under the title.


(FYI I see both done by other WP plugins. Here's a notice from Updraft pro that appears BELOW the title: https://drive.google.com/a/eventespresso.com/file/d/1N6sT8W01ZwXr0nCXVgAzHubyZMGzowvA/view?usp=drivesdk, and here's a notice from WordFence that appears ABOVE the title: https://drive.google.com/a/eventespresso.com/file/d/1Nv75YIHjzVccKfNd9-Rlct--lTLHuIVE/view?usp=drivesdk)

**Comment by tn3rb** [comment]
ya personally I think they look better **below** the title, so as long as there isn't a big objection from the tEEm, then I'd be totally ok with moving all notices so that they appear below the title

**Comment by mnelson4** [comment]
:+1: thanks Brent.
Ya I think once we have this triaged, I'll ping everyone in general and ask if there are any preferences. I think consistently having them appear below the title would be better (the WP ecosystem might be inconsistent about where they put notices, but we could at least be consistent about it).

**Comment by mnelson4** [comment]
Seeing how the general WP ecosystem is inconsistent about where notices appear, it may be best to leave things as-is until we get more user feedback.
