### ISSUE TITLE
Customizing the message system

### ISSUE THREAD

**Issue by nickheyvaert** [eventespresso/event-espresso-core#594]
Hi,

I’m currently trying to send an email using the Event Espresso system. I have written the code below:

```
$args = array(
 'MSG_messenger' => 'email',
 'MSG_message_type' => 'registration',
 'MSG_context' => 'primary_attendee',
 'MSG_recipient_type' => 'Attendee'
);
$message = EE_Message_Factory::create( $args );
$message->set_to( 'john.appleseed@domain.com' );
$message->set_from( 'noreply@domain.com' );
$message->set_content( 'test' );

$messages_processor = EE_Registry::instance()->load_lib( 'Messages_Processor' );

if ( !$messages_processor instanceof EE_Messages_Processor ) {
 return;
}

$messages_processor->batch_generate_from_queue( $message );
```

It seems not to work though, what am I doing wrong?

Messages won't generate and output an error saying there is "no generation data found".

I want to send e-mails with Event Espresso so they become available to be accessed from the messages overview.

**Comment by nerrad** [comment]
Are you just wanting to hardcode the content of the message and not have it parse shortcodes in the content using data related to the message?

**Comment by nickheyvaert** [comment]
Indeed, I just want to code the content. If I need to pass data to it, I will get it using a hook. It just seems that my code misses a piece for the message to be generated correctly.

**Comment by nerrad** [comment]
We haven't really done that use-case so what I'm about to suggest may or may not work for you.  Since you are just hard-coding content, it sounds like the "state" of the `Message` is `EEM_Message::status_idle` (which essentially means its ready for sending).  So you'd likely want to do something like this:

```php
$args = array(
 'MSG_messenger' => 'email',
 'MSG_message_type' => 'registration',
 'MSG_context' => 'primary_attendee',
 'MSG_recipient_type' => 'Attendee'
   'STS_ID' => EEM_Message::status_idle
);
$message = EE_Message_Factory::create( $args );
$message->set_to( 'john.appleseed@domain.com' );
$message->set_from( 'noreply@domain.com' );
$message->set_content( 'test' );
$message->save();

$messages_processor = EE_Registry::instance()->load_lib( 'Messages_Processor' );

if ( !$messages_processor instanceof EE_Messages_Processor ) {
 return;
}

$messages_processor->batch_send_from_queue( array( $message ) );
```

**Comment by nickheyvaert** [comment]
Sadly, that doesn't work. The error message is the following:

An error has occurred:
No message was sent because of problems with sending. Either all the messages you selected were not a sendable message, they were ALREADY sent on a different scheduled task, or there was an error. If there was an error, you can look at the messages in the message activity list table for any error messages.
EED_Messages - send_now - 1180

---

Message was not executed successfully.
Messenger and Message Type were valid and active, but the messenger send method failed.
The email did not send successfully.
The WordPress wp_mail function is used for sending mails but does not give any useful information when an email fails to send.
It is possible the "to" address (nick@strak.be) or "from" address (noreply@domain.test) is invalid.

EE_Email_messenger - _send_message - 454

Please let me know your suggestions and ideas.

**Comment by nickheyvaert** [comment]
I have managed to make it work, it was simply a missing subject when calling the wp_mail.
All I needed to do was adding `$message->set_subject( 'test' );` to my code.

Thanks!

**Comment by nerrad** [comment]
ahh yah, that would be it.  Glad you got something working for your needs.
