### ISSUE TITLE
"You need to select a ticket quantity" notice only displays for logged in users

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#595]
Reported here:
https://eventespresso.com/topic/error-message-when-zero-0-tickets-selected-not-displaying/
and confirmed locally

**Describe the bug**

No error message is displayed if you're logged out of the site and do not select a ticket quantity and just click the submit the button below the ticket selector.
**To Reproduce**

**Expected behavior**

There should be an error message, and there was one prior to Event Espresso 4.9.59.p

**Environment:**
 - Version of Event Espresso:  Current master, and current releases since 4.9.59.p

**Additional context**

This looks to be related to the work done in https://events.codebasehq.com/projects/event-espresso/tickets/11406

**Comment by sethshoultes** [comment]
@mnelson4 can you fix this? If not, please pass to @tn3rb .

**Comment by joshfeck** [comment]
@mnelson4 I'm not sure if you've looked into this, but one other thing I found while investigating this is it appears to be something going awry related to part of the `getStoredNotices()` method in EE_Error.core.php. I did a `var_dump($session_data);` inside that method's second conditional and it always returns an empty array when I'm logged out of the site and submit a ticket selector form with no selections. 
If I do a 
```var_dump(EE_Session::instance()->set_session_data(
  array(EE_Error::OPTIONS_KEY_NOTICES => $notices)
);```
just before the return in the `storeNotices()` method (next method down in the same class) it does return true, so it seems that something happening between these two methods. In chat, Darren mentioned it could be the notices aren’t getting persisted to the database.

**Comment by joshfeck** [comment]
Another clue is everything works as expected if MER is activated. So you can be logged out of the site, hit the ticket selector submit with 0 ticket selections, and the error notice **does** display. 

From what I can tell, the session vars aren't getting saved to the db in the above reported scenario because of the checks at the beginning of the _save_session_to_db method. Note also the comment there:
```
// and unless we're deleting the session data, don't save anything if there isn't a cart
```

So in this case, there isn't a cart, so the error notices will not get saved to the db as session vars.

**Comment by joshfeck** [comment]
Brent mentioned in chat that "we could maybe add some logic to the session to also check for notices when saving since I don't think there's many other (if any) cases where notices get saved without a cart -- so it wouldn't be increasing the usage of the session much -- otherwise those notices have the potential to go to someone else"

**Comment by mnelson4** [comment]
> So in this case, there isn't a cart, so the error notices will not get saved to the db as session vars.
 :+1: ya that's exactly what's going on. And that explains why it works with MER (MER must override that behaviour).

> Brent mentioned in chat that "we could maybe add some logic to the session to also check for notices when saving...

man, you guys really laid out the fix for me!
