### ISSUE TITLE
Make license key check request more resilient

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#605]
For the backstory see this forum topic:
https://eventespresso.com/topic/api-timeout-calls-crashing-admin-on-high-traffic-site/

and this slack chat starting here:
https://eventespresso.slack.com/archives/C080L8G68/p1532457321000038

(Note to future readers: the slack chat may not be available due to free account constraints) 
So the tldr; version of that chat is we think there may be another plugin highjacking the request leading to runaway license key checks numbering into the tens of thousands for this particular site.
The key PUE looks for in the post request is `site_license_key`, so maybe one part of this is make that key more unique.

**Comment by sethshoultes** [comment]
@nerrad is this something you can fix before you go on vacation? Or maybe @knazart can help?

**Comment by nerrad** [comment]
@sethshoultes I doubt I'm going to get to this before I go on vacation.  Nazar may be able to look at it.  However, this isn't super critical, it's been this way for a while and various logs I looked at indicated that not a lot of site seem impacted.  So while I do agree its something that _should_ be done I think its safe to wait until I get back and in the meantime @joshfeck has a workaround for customers that are affected if necessary.
