### ISSUE TITLE
Fix the 1-click upgrade from Decaf

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#609]
Many users are reporting they've purchased an Event Espresso support license, entered a support key, and are not getting a prompt to upgrade to Caffeinated. So I've been advising them to manually do the upgrade.

I've replicated this issue on my test site at josh.eventespresso.com by deactivating EE4 regular, installing and activating EE4 decaf, then saving the General Settings page with the correct support key in place. No prompt to upgrade is displayed.

This might not be an issue with core and instead an issue on the server side (on ee.com's server), but I'm reporting this here so it can be triaged.

**Comment by lorenzocaum** [comment]
I've seen this issue recently. Here is an example:

https://secure.helpscout.net/conversation/604054489/540558

**Comment by sethshoultes** [comment]
@knazart can you please look into this? If you need assistance, please ping @mnelson4.
