### ISSUE TITLE
filter_var FILTER_VALIDATE_URL isn't always reliable

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#624]
in \event-espresso-core-reg\core\services\assets\Registry.php the registerManifestFile() method does a validation check with:
```
if (filter_var($url_base, FILTER_VALIDATE_URL) === false) {
```

One user tried to set up a dev server where the domain includes underscores in its name and the error got triggered.

For context see:
https://d-mueller.de/blog/why-url-validation-with-filter_var-might-not-be-a-good-idea/

and

https://eventespresso.com/topic/registry-registermanifestfile-500/

**Comment by tn3rb** [comment]
ya I think when we started using `filter_var($url, FILTER_VALIDATE_URL)` multibyte characters were not allowed in URLs but of course are now acceptable so we should purge all uses of this method and replace with a service that can better accommodate modern URLs.

**Comment by sethshoultes** [comment]
@mnelson4 is this one you can take on?

**Comment by mnelson4** [comment]
I can, but if anyone has any suggestions on where to start I'm open to hear them. (Otherwise I'm just going to start Googling)

**Comment by mnelson4** [comment]
Started on branch BUG/better-url-validation, right now it's mostly just unit tests.

> multibyte characters were not allowed in URLs but of course are now acceptable so we should purge all uses of this function and replace it with a service that can better accommodate modern URLs.

Technically, multibyte characters are still not allowed in URLs (see https://wordpress.stackexchange.com/questions/310894/why-dont-wordpress-post-slugs-allow-accents/311020#311020) although we ourselves are currently relying on browsers handling IRLs just like URLs... So i think we should basically regard them as valid.

**Comment by mnelson4** [comment]
resources for better URL validation:
http://halfelf.org/2015/url-validation/
https://github.com/franksrevenge/StrictUrlValidator
and I want to see what WP currently does to validate commenter's websites

**Comment by mnelson4** [comment]
The related PR was merged in, so this is fixed.
