### ISSUE TITLE
Encoding Bug for Email From Address

### ISSUE THREAD

**Issue by Daronspence** [eventespresso/event-espresso-core#626]
**Describe the bug**

When an email is sent, the apostrophe in the [CO_EMAIL] from address is rendered incorrectly in Gmail.

Screenshot
https://cl.ly/002F1646173c

https://cl.ly/2o28041W3P08

**To Reproduce**
Set the organization name to have an apostrophe eg: Bob's Candy

**Expected behavior**
Emails should display a correctly formatted from address label

**Screenshots**

See above

**Environment:**
 - Version of Event Espresso:  4.9.65.p 
 - Version of WordPress: 4.9.8
 - Browser: Firefox Developer Edition 62.0b14
 - PHP Version: 7.1.18

**Additional context**
Pinged Darren on Slack and he told me to open an issue :)

**Comment by nerrad** [comment]
@sethshoultes this looks like an encoding issue and probably should receive an initial look by @mnelson4

**Comment by mnelson4** [comment]
yeah, we shouldn't be converting "from" address to HTML entities...

**Comment by Pebblo** [comment]
Previous internal ticket ref: https://events.codebasehq.com/projects/event-espresso/tickets/11397

**Comment by Pebblo** [comment]
@Daronspence, are you using a plugin to send your emails via SMTP, or any plugin to filter the from name on the emails?

I can't reproduce this on my test sites, e.g - http://take.ms/2nK2b

I found the site in question and the site title is also "Steve's Floral" so if you set Org name not to have an apostrophe, but leave the site title as is, do you get the same issue?

**Comment by mnelson4** [comment]
Hmm I can't reproduce it yet... It would be helpful to see what @Daronspence has in WP dashboard -> Settings General, and in WP dashboard -> Event Espresso -> General Settings

**Comment by Daronspence** [comment]
Well this is embarrassing. I think it may be related to @Pebblo suggestion about the email service. We're using Sendgrid on this site. I just came on for this project so I overlooked that portion.

Sending a test email from the Sendgrid settings screen returns an email with the same formatting error. Here is what I see when removing the sender name and letting it fall back.

https://cl.ly/0x1y2n302A19

Settings screens @mnelson4 
General: https://cl.ly/0h3F0K1P3l1B
EE: https://cl.ly/002o2q3v2k2J

Sendgrid Settings: https://cl.ly/19240x3V3j3I

I'm not 100% sure on the expected behavior here so I'll fall back to you all. If the email is the only thing shown, we're okay with that.

Cheers

**Comment by mnelson4** [comment]
Aha, good find @Daronspence and @Pebblo. Ya this isn't the first time we've had an issue with SendGrid...
Ya I think the problem is in the SendGrid plugin... which I actually see you're on top of! https://github.com/sendgrid/wordpress/issues/79
No worries.
