### ISSUE TITLE
Stop any travis builds for docs only changes

### ISSUE THREAD

**Issue by nerrad** [eventespresso/event-espresso-core#631]
I stumbled across a [travis configuration](https://github.com/facebook/react/pull/2000/commits/233af7e2dff4c79619f5cda6943388ff9e21581b) that cancels builds when a pull request only has documentation changes.  I think this will be useful for us to implement so we don't have unnecessary builds happening.  Doesn't have to be implemented right away but should be fairly trivial to implement (under 30 min).

**Comment by nerrad** [comment]
I gave a go at this but discovered that others who have implemented something similar ended up reverting because of it not working as expected (I'm seeing the same thing in testing).  So I'm just going to close this.

**Comment by joshfeck** [comment]
oops I accidentally deleted Darren's last comment where he wrote:

> I gave a go at this but discovered that others who have implemented something similar ended up reverting because of it not working as expected (I'm seeing the same thing in testing). So I'm just going to close this.
