### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by maverstef** [eventespresso/event-espresso-core#632]
Hi  i register the attendee through the api endpoint (/v4.8.36/registrations with the following keys
{
“EVT_ID”:9986,
“ATT_ID”:10001,
“TXN_ID”:9,
“TKT_ID”:3,
“STS_ID”:”RAP”,
“REG_url_link”:”1-aaaf6d26ac8e67effe9d07e427caf804″,
“REG_final_price”: 20.00,
“REG_paid”: 20.00
}
)

..on the registration panel the registration is approved but the mail (Ticket Notice)  is not triggered.. is there any idea how to trigger the corresponding mail (Ticket Notice) ?

**Comment by sethshoultes** [comment]
@mnelson4 any ideas on this question?

**Comment by mnelson4** [comment]
Registrations created through the REST API don't cause messages to automatically be sent. You're not the first person to ask about this @maverstef. 
The easiest way to achieve this, besides clamouring for us to add the feature, is to use the code snippet from https://github.com/eventespresso/event-espresso-core/issues/254#issuecomment-340730103, which creates a custom endpoint that will trigger sending the registration message, and then just send a request to that endpoint anytime a message should be triggered.
Closing this issue as a duplicate
