### ISSUE TITLE
Add Data Model Foreign Keys to REST Responses

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#636]
Currently, the REST API JSON responses do not include any database foreign keys and all relations have to be explored via the related fields (`_links`).
This can increase the amount of querying that needs to be performed and/or increase the complexity of queries because one has to manually indicate that they want the foreign keys included.

This feature request is to have ALL foreign keys for direct relations automatically included as part of the REST API responses when querying object endpoints.

So for example, currently a request to `/wp-json/ee/v4.8.36/datetimes` would return the following entity fields:

```
DTT_ID
DTT_name
DTT_description
DTT_EVT_start
DTT_EVT_end
DTT_reg_limit
DTT_sold
DTT_reserved
DTT_is_primary
DTT_order
DTT_parent
DTT_deleted
```

as well as some additional fields that are part of the general schema such as `_links` and `_calculated_fields`.

In order to determine what event a datetime may belong to, it is necessary to either manually request that the `EVT_ID` foreign key field be included in the above, or to perform an additional query to the `/wp-json/ee/v4.8.36/datetimes/#/event` where `#` represents the ID for the Datetime in question.

The suggestion in this request is to automatically add the `EVT_ID` foreign key field to the above data for ALL queries so that the returned fields instead look like:

```
DTT_ID
EVT_ID
DTT_name
DTT_description
DTT_EVT_start
DTT_EVT_end
DTT_reg_limit
DTT_sold
DTT_reserved
DTT_is_primary
DTT_order
DTT_parent
DTT_deleted
```

Placement isn't too important, but having all keys at the top of the data schema would be a nice touch.

PLZ NOTE: this would only apply to entities that are part of a one to one relationship (in which case both objects would contain the foreign key to their relation), or where the related entity is singular in a one to many relationship (in which case only one object would contain the foreign key to their relation). Any object with many related entities would not contain those foreign keys and additional queries (or manual joins) would be required. So using the example above, the related `Event` entity would **not** possess a corresponding `DTT_ID` field because an Event can have many related Datetimes. 

Any additional data that is required from the related object would still need to be obtained the same way it is now, by either manually requesting it be included in the response or by performing additional queries.

This feature is needed in order to build entity object classes that are to be used for completing our Gutenberg integration as well as any other systems being built using React.

**Comment by mnelson4** [comment]
for the record, the REST API clients could have used `include=...` to include the related models, thus avoiding needing to send another HTTP request. But that's pretty non-standard and we may as well add this anyway.

**Comment by tn3rb** [comment]
>  the REST API clients could have used include=... to include the related models, 

right, that's what I was trying to get across by saying "manually requesting it be included in the response" which I guess I could have clarified by stating the actual mechanism for doing that.

**Comment by mnelson4** [comment]
PR merged in
