### ISSUE TITLE
Fatal error submitting invisible-recaptcha form after logging out

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/event-espresso-core#653]
## Issue Overview

This error was originally reported on https://github.com/eventespresso/event-espresso-core/pull/650#issuecomment-413717078, where I wasn't quite sure how to reproduce. 

To state it here, I get the following fatal error:

```

( ! )  Fatal error: Uncaught RuntimeException: We&#039;re sorry but an  attempt to verify the form&#039;s reCAPTCHA has failed. <br />   Please try again. in  E:\Software\laragon\www\laragonee\wp-content\plugins\event-espresso-core\caffeinated\modules\recaptcha_invisible\InvisibleRecaptcha.php  on line 178
--



1 | 0.0000 | 379544 | {main}(  ) | ...\index.php:0
2 | 0.0000 | 381576 | require( 'E:\Software\laragon\www\laragonee\wp-blog-header.php' ) | ...\index.php:17
3 | 0.5200 | 33993896 | wp(  ) | ...\wp-blog-header.php:16
4 | 0.5200 | 33993944 | WP->main(  ) | ...\functions.php:1035
5 | 0.5200 | 34046672 | WP->query_posts(  ) | ...\class-wp.php:737
6 | 0.5200 | 34046768 | WP_Query->query(  ) | ...\class-wp.php:620
7 | 0.5200 | 34046712 | WP_Query->get_posts(  ) | ...\class-wp-query.php:3360
8 | 0.5300 | 34050488 | do_action_ref_array(  ) | ...\class-wp-query.php:1711
9 | 0.5300 | 34050488 | WP_Hook->do_action(  ) | ...\plugin.php:531
10 | 0.5300 | 34050488 | WP_Hook->apply_filters(  ) | ...\class-wp-hook.php:310
11 | 0.5700 | 35332096 | EE_Front_Controller->pre_get_posts(  ) | ...\class-wp-hook.php:286
12 | 0.5700 | 35332792 | EE_Module_Request_Router->resolve_route(  ) | ...\EE_Front_Controller.core.php:227
13 | 0.5700 | 35332792 | EE_Module_Request_Router->_module_router(  ) | ...\EE_Module_Request_Router.core.php:181
14 | 0.5700 | 35332872 | EED_Ticket_Selector->process_ticket_selections(  ) | ...\EE_Module_Request_Router.core.php:241
15 | 0.5900 | 35578008 | EventEspresso\modules\ticket_selector\ProcessTicketSelector->processTicketSelections(  ) | ...\EED_Ticket_Selector.module.php:226
16 | 0.5900 | 35578008 | do_action(  ) | ...\ProcessTicketSelector.php:187
17 | 0.5900 | 35578384 | WP_Hook->do_action(  ) | ...\plugin.php:465
18 | 0.5900 | 35578384 | WP_Hook->apply_filters(  ) | ...\class-wp-hook.php:310
19 | 0.6000 | 35761336 | EED_Recaptcha_Invisible::processTicketSelectorForm(  ) | ...\class-wp-hook.php:286
20 | 0.6100 | 35800864 | EED_Recaptcha_Invisible::verifyToken(  ) | ...\EED_Recaptcha_Invisible.module.php:313
21 | 0.6100 | 35800864 | EventEspresso\caffeinated\modules\recaptcha_invisible\InvisibleRecaptcha->verifyToken(  ) | ...\EED_Recaptcha_Invisible.module.php:195
22 | 0.8000 | 36160776 | EventEspresso\caffeinated\modules\recaptcha_invisible\InvisibleRecaptcha->generateError(  ) | ...\InvisibleRecaptcha.php:163
```

See "Steps to Reproduce"

Not too huge of an issue, because only site users logging in and out will get this. But here's a report, and explanation of how to reproduce, in case someone asks.

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Environment Data:

Version of EE: 

Version of WordPress: 4.9.7

PHP Version:   7.1

Browser used:  Mozilla Firefox

## Steps to Reproduce (for bugs)

* log into your site, 
* setup invisible recaptcha, 
* go to view an event from the front-end, 
* from there log out, 
* PRESS BACK in your browser, 
* submit the ticket selector form, then you'll get the error. 

Here is a video: https://drive.google.com/file/d/1FSvw9S-VXBzN5awcNvMWPdvHv6XptZC1/view

## Expected Behaviour

Ideally we should redirect back to the page where the form was submitted

## Current Behaviour

See video

**Comment by tn3rb** [comment]
so basically you're using a TS that was generated when you were logged in, 
but then submitting it while logged out, which is expecting a reCAPTCHA token to exist

you can likely achieve the same thing by using multiple tabs like so:

- open a browser tab and log into the admin
- open a second browser tab and go to an event page (should still be logged in)
- in tab 1, log out of the admin
- in tab 2, submit the ticket selector
