### ISSUE TITLE
ESPRESSO_TICKET_SELECTOR throws an exception for all users if the event ID doesn't exist.

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#655]
**Describe the bug**
If you add `[ESPRESSO_TICKET_SELECTOR event_id=999999]` to a page and view said page both logged in and out of the site.

Both outputs show the exception with various details, if you have WP_Debug enabled you'll get a 'pretty' output but shouldn't this exception only be thrown to admins, or at least editors rather than all users?

**Expected behavior**
iirc the exception should not be displayed to all users, if the event doesn't exist it should return an empty string.

**Screenshots**
See here - http://take.ms/M95vZ
(left logged in, right logged out)

**Environment:**
 - Version of Event Espresso:  master
 - Version of WordPress: 4.9.8
 - Browser: any
 - PHP Version 7.2

**Additional context**
Reported here: https://eventespresso.com/topic/ee-will-break-pages-with-missing-ee-events/

**Comment by joshfeck** [comment]
Previously reported in Codebase:

https://events.codebasehq.com/projects/event-espresso/tickets/10883

where it was suggested to replace the exception with the following:

1) If the user is logged in and has the edit_pages capability they should see a friendly error message that says something to the effect of "Oops! The [ESPRESSO_TICKET_SELECTOR] shortcode on this page has an event ID that's not correct. You can correct this by editing this page".
2) If the user doesn't have the edit_pages capability or isn't logged in the shortcode should return nothing and the rest of the page should be allowed to render.

**Comment by Pebblo** [comment]
I realized, the exception was thrown when WP_Debug was true, however, setting it to false throws a fatal error:

```
 Fatal error: Uncaught InvalidArgumentException: A valid Event ID is required to use the &quot;ESPRESSO_TICKET_SELECTOR&quot; shortcode.<br />An Event with an ID of &quot;9999&quot; could not be found.<br />Please verify that the shortcode added to this post&#039;s content includes an &quot;event_id&quot; argument and that it&#039;s value corresponds to a valid Event ID. in C:\xampp\htdocs\ee4\wp-content\plugins\event-espresso-core-reg\core\domain\entities\shortcodes\EspressoTicketSelector.php on line 75
```
