### ISSUE TITLE
Support License Key field is displayed on sub-sites

### ISSUE THREAD

**Issue by knazart** [eventespresso/event-espresso-core#661]
The Support License Key field under General >> Organization settings is being displayed on sub-sites on a network install, whereas it should be hidden there by default and displayed only on the main site. Unless there was a decision for that to work otherwise ?

**Comment by knazart** [comment]
What I found is that there was some code refactoring done between core versions 4.9.63.rc.004 and 4.9.67 where the "Your Event Espresso Support License Key" settings area was moved from the ` event-espresso-core/admin_pages/general_settings/templates/your_organization_settings.template.php
` into the ` event-espresso-core/admin_pages/general_settings/OrganizationSettings.php
`  and it looks like the `if (is_main_site())` condition wrapping that section just got missed.

**Comment by sethshoultes** [comment]
This was merged with the pull https://github.com/eventespresso/eventsmart.com-website/pull/126

**Comment by knazart** [comment]
Right, but this is related to the core and needs to be fixed here. The fix applied on ES is just a workaround.
