### ISSUE TITLE
non-ascii characters sent to authnet produce 270 error and HTML should be removed

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/event-espresso-core#662]
## Issue Overview

If your event title, ticket name or ticket description have non-ascii characters (eg emojis, Chinese characters, accented characters, or curly quotes) in it, you'll get an error 

> Line item 1 is invalid. (Reason Code: 270)

while paying for the event with Authorize.net AIM.

On https://eventespresso.com/topic/authorize-net-payment-declines-line-item-1-is-invalid-reason-code-270/#post-276437 PJ Doland reported

> After talking to my 5th Authorize.net representative, I found out that NO SPECIAL CHARACTERS are supposed to be in the line item

ie, so we should probably strip non-ascii characters from authnet. We should also document somewhere that this is done, so event managers expect this (I'm not currently sure on the best spot- this probably applies to any data sent to Authnet, so it would need to be in a LOT of spots if we literred it throughout EE, so probably just having it documented on Authnet AIM's help section might suffice).

I should also investigate to see how HTML in ticket descriptions is handled. I don't recall if we're currently removing it. If not, we should. If so, we should document that. 

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Environment Data:

Version of EE: 4.9.67

Version of WordPress:4.9.9

PHP Version:  7.1

Browser used:  Firefox

## Steps to Reproduce (for bugs)

Add non-ascii charaacters to either:
* ticket name
* ticket description
* event name

others?

Then try to pay for that ticket using Authnet.

## Expected Behaviour

First we expected authnet to be ok with non-ascii characters. Failing that, we'd really like EE to convert non-ascii characters into comparable ascii ones (eg remove accents), or at least just remove the characters outright.

## Current Behaviour

When registering for an event and EE sends non-ascii characters ot authnet, you get a 270 error

**Comment by mnelson4** [comment]
Ah, we actually previously had a very similar issue: https://events.codebasehq.com/projects/event-espresso/tickets/10298. So we actually fixed it for when emojis were used, but it seems curly quotes were still a problem.

**Comment by mnelson4** [comment]
I hope it's ok, in the process of investigating this issue, I create a quickfix in a PR

**Comment by sethshoultes** [comment]
Pull request has already been merged.
