### ISSUE TITLE
Fix unnecessary repetition of event name in line items sent to AIM

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/event-espresso-core#664]
**Describe the bug**

On https://eventespresso.com/topic/authorize-net-payment-declines-line-item-1-is-invalid-reason-code-270/#post-276437, Pj suggested

> Maybe stop concatenating the event title to the ticket title in the case of short ticket titles, since the event title is already being included in the description field. Seems redundant and created this weird bug that sent me on a 72-hour back-and-forth between you guys and Anet.

Specifically, Authorize.net is receiving line item descriptions like the following:

> Event Registrations from Mike Site for 15th Anniversary PartyA Celebration of Fifteen-ness (For 15th Anniversary Party)

Notice that the event's name, "15th Anniversary Party" occurs twice. That's because it's being added by `GatewayDataFormatter::formatOrderDescription()` (`GatewayDataFormatter::formatLineItemName()` does too) into the item's name, and the description, which is the line item description, also has the event name in it (by `EEH_Line_Item::create_ticket_line_item()`).

That's a lot of event names...

Sorry, I'll finish this report, interrupted...

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - Version of Event Espresso:  
 - Version of WordPress: 
 - Browser 
 - PHP Version 

**Additional context**

**Comment by sethshoultes** [comment]
Oh, I saw a pull request (#662) and thought it was related to, so moved this to the next pile.

**Comment by mnelson4** [comment]
anyways, this needs a bit more analysis to assess where all the pieces are coming from, and where, if anywhere, we ought to change thins. Here is a sample screenshot of the data that arrives in Authnet:https://drive.google.com/a/eventespresso.com/file/d/1JlrBTP_JmSZHC_JpWUJwKVq0SnQ2aaXh/view?usp=drivesdk, although I'd like to make a clearer example
