### ISSUE TITLE
Register Question Type

### ISSUE THREAD

**Issue by cenomla** [eventespresso/event-espresso-core#665]
I am writing an add-on for event espresso and I need to extend the event registration forms with a custom form input type. I have created a new form input that extends EE_Form_Input_Base and the display, normalization, etc... strategies for it. However I could not find documentation on how to register a new question type with EE core. Does anyone know if this is supported and if so how to do it?

**Comment by sethshoultes** [comment]
@tn3rb or @nerrad any suggestions?

**Comment by tn3rb** [comment]
Hi @cenomla,

Thanks for your interest in developing an add-on for Event Espresso.

All of the question properties such as the question type are filtered in `EEM_Question::__construct()` and includes the following:

- `FHEE__EEM_Question__construct__allowed_question_types`
- `FHEE__EEM_Question__construct__question_type_categories`
- `FHEE__EEM_Question___construct__question_types_with_max_length`

(just noticed that two of those arrays have the same filter name, so will need to fix that ASAP!)

just as an FYI, all of our action hooks names are prepended with `AHEE__` and all of our filter hook names are prepended with `FHEE__`. 
Then the names for both types include the class name, method name, and target (variable filtered or action location/purpose) which can be used to locate where a hook point is in the codebase.

Hope that helps, let us know how things go. We'd love to see your add-on when it's complete. Seth can also let you know more about options we have available to help promote third party add-ons if you are interested.
