### ISSUE TITLE
Åland Islands shows as &#197;land Islands in countries dropdown

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/event-espresso-core#666]
This was seen while testing Event Smart. I don't think its specific to a recent version.

**Summary**
In the countries dropdown menu, Åland Islands has some characters at the beginning which I understand is to get that "Å" character:

https://cl.ly/e43c7e353b5f

**Steps to reproduce**
Go to a website with a current version of Event Espresso. Then go to General Settings --> Countries.

**Comment by mnelson4** [comment]
this might be an easy fix... we'll see...

**Comment by mnelson4** [comment]
PR merged in
