### ISSUE TITLE
Remove timing component of bot trap

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#670]
We see quite a few support requests where they get a false positive "server timing error", like this one:
![image](https://user-images.githubusercontent.com/891156/44802314-5c2b2200-ab89-11e8-9193-ed34bd5a9801.png)

Since there could be reasons why a ticket selector form could be over 1 hour old (interruptions, caching, or even someone really taking their time to mull over whether they want to attend the event) I think the timing component of the bot trap should be removed. Further, the ticket selector can be protected with reCAPTCHA now as well. 

The hidden input part could probably remain.

**Comment by sethshoultes** [comment]
Let's try it and see how it goes.
