### ISSUE TITLE
Default to the country that is selected for base of operations in the your organization settings

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/event-espresso-core#677]
A customer (https://secure.helpscout.net/conversation/651312341/561622/) shared a suggestion to improve the registration process.

If you are an event organizer in the United Kingdom, then have the country field dropdown on the registration form and the payment form default to the United Kingdom by default.

**Comment by tn3rb** [comment]
## required steps and estimates

- (2 hours) detect if `$input_constructor_args['default']` has been set for country and state type questions within switch statement in `EE_Question::generate_form_input()` and if not, then set default based on values from `EE_Organization_Config`

**Comment by garthkoyle** [comment]
Will this be improved/handled with #739 and #749 ?

**Comment by sethshoultes** [comment]
I think so. @tn3rb and @lorenzocaum what are your thoughts on Garth's question above?

**Comment by lorenzocaum** [comment]
Those will make it easier for an event organizer to get information set up. For example, if I'm in Canada, then load up the provinces.

This issue is to help the attendees that are registering as it will default to the country that is set in the base of operations:

![image 2018-11-02 at 4 18 38 pm](https://user-images.githubusercontent.com/1079138/47938653-25d88e80-debb-11e8-95e6-be54f7068ab2.png)

**Comment by joshfeck** [comment]
This could be perceived as a bug when released because it's a change to the existing behavior of the registration forms. It's a good idea for most use cases, but could be an issue if the organization's country isn't the same as most/all of the registrant's country.

**Comment by garthkoyle** [comment]
I can see how this might be convenient for attendees. However, having a default selection might result in false selections where the attendee doesn't correct the country selection (or at least confirm it) before submitting their registration. So, the event organizer might get less correct data.

My guesstimate is that it may help 70-80% of attendees, then inconvenience 5-10% of event organizers (our customers).

**Comment by joshfeck** [comment]
Agreed. I think we could do this a bit differently where instead of forcing a default of what's set in in the Organization Country field, we instead allow event organizers to opt in by editing the Country question/form field. This could be as simple as a yes/no field where setting Yes could opt them in to forcing that default. It could also be a more flexible field where the event organizer could select from the available countries to set as the default. 

One factor to consider is whether this can be done without adding new columns to the db (because of Eventsmart). Maybe this is something that could be done with the extra_meta table.

**Comment by lorenzocaum** [comment]
Another idea is to pull the country for base of operations to the top of the list if there are multiple countries enabled:

![image 2019-01-08 at 2 29 13 pm](https://user-images.githubusercontent.com/1079138/50853982-e1052400-1351-11e9-86a7-01dd2a4f8f82.png)

Then do the same for states/provinces that are for that country.

**Comment by joshfeck** [comment]
This is a support topic where they wanted to move their country (in this case, the US) to the top of the list:
https://eventespresso.com/topic/set-default-country-at-top-of-list/
