### ISSUE TITLE
Recover from error code 10486

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/event-espresso-core#684]
**Seen on a current release and this is not specific to a recent version**

**Summary**
When there is a problem with the funding source, then an attendee is taken back to registration checkout and an error code 10486 is shown: 

![image 2018-09-09 at 2 43 37 pm](https://user-images.githubusercontent.com/1079138/45267710-e738d180-b43f-11e8-932a-0b04ad923d01.png)

However, an attendee doesn't know what that is so they won't know what to do to move past the error.

If that error code is triggered then PayPal recommends redirecting back to PayPal.com (https://developer.paypal.com/docs/classic/express-checkout/ht_ec_fundingfailure10486/#error-code-details) and then it seems they'll handle it:

https://developer.paypal.com/docs/classic/express-checkout/ht_ec_fundingfailure10486/#the-buyers-experience

The sample error message is helpful because it lets them know that their payment option isn't working and suggests to try another.

**Steps to reproduce**
Here is how to trigger this with a Sandbox account: https://developer.paypal.com/docs/classic/express-checkout/ht_ec_fundingfailure10486/#test-a-sale-or-authorization-integration

**Other notes**
Once a solution is discussed, then I think we may need something for the PayPal Smart Buttons as well: https://developer.paypal.com/docs/checkout/how-to/customize-flow/#manage-funding-source-failure

**Comment by mnelson4** [comment]
thanks for the steps to reproduce. I'll get to this once it's next in my next list

**Comment by sethshoultes** [comment]
@joshfeck @Pebblo has this been reported by many customers?

**Comment by joshfeck** [comment]
No.

**Comment by sethshoultes** [comment]
Okay if I move this to the backlog, then?

**Comment by joshfeck** [comment]
We could. Or this issue could be closed and if we get word that it's happened again, we'll reopen the issue.
