### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable in RegistrationsReport.php

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/event-espresso-core#687]
**Summary**
This shows up if you are on PHP 7.2:

`PHP Warning: count(): Parameter must be an array or an object that implements Countable in /dom16100/wp-content/plugins/event-espresso-core/core/libraries/batch/JobHandlers/RegistrationsReport.php on line 207`

**Steps to reproduce**
1) Set up Event Espresso on a website that uses PHP 7.2.

2) Then create an event and add a couple of registrations.

3) Run a registration report.

**Comment by sethshoultes** [comment]
@mnelson4 is this your realm? Something you can fix?

**Comment by sethshoultes** [comment]
Related ES issue: https://github.com/eventespresso/eventsmart.com-website/issues/185

**Comment by mnelson4** [comment]
yeah I can address this...

**Comment by mnelson4** [comment]
PR #690 addressed this
