### ISSUE TITLE
Fix Fatal error related to usage of REST API

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#689]
Steps to replicate:
EE4 Master + Attendee Mover
Go to Event Espresso > Registrations and click the icon to move an attendee

```Fatal error: Uncaught ArgumentCountError: Too few arguments to function EventEspresso\core\libraries\rest_api\controllers\model\Read::__construct(), 0 passed in /srv/www/wordpress-default/public_html/wp-content/plugins/32-core/core/libraries/form_sections/inputs/EE_Select_Ajax_Model_Rest_Input.input.php on line 97 and exactly 1 expected in /srv/www/wordpress-default/public_html/wp-content/plugins/32-core/core/libraries/rest_api/controllers/model/Read.php:53 Stack trace: #0 /srv/www/wordpress-default/public_html/wp-content/plugins/32-core/core/libraries/form_sections/inputs/EE_Select_Ajax_Model_Rest_Input.input.php(97): EventEspresso\core\libraries\rest_api\controllers\model\Read->__construct() #1 /srv/www/wordpress-default/public_html/wp-content/plugins/eea-attendee-mover/form/SelectEvent.php(66): EE_Select_Ajax_Model_Rest_Input->__construct(Array) #2 /srv/www/wordpress-default/public_html/wp-content/plugins/32-core/core/libraries/form_sections/form_handlers/SequentialStepFormManager.php(490): EventEspresso\AttendeeMover\ in /srv/www/wordpress-default/public_html/wp-content/plugins/32-core/core/libraries/rest_api/controllers/model/Read.php on line 53```

**Comment by mnelson4** [comment]
PR merged
