### ISSUE TITLE
Registration Report:  headers already sent error

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#693]
If I run a registration report using a site with PHP 7.2 and WP 4.9.8 I'm getting this on each report:

```
Warning:  Cannot modify header information - headers already sent
by (output started at \wp-includes\formatting.php:5100) in \wp-includes\pluggable.php on line 1219
Stack trace:
  1. {main}() \wp-admin\admin.php:0
  2. do_action() \wp-admin\admin.php:224
  3. WP_Hook->do_action() \wp-includes\plugin.php:453
  4. WP_Hook->apply_filters() \wp-includes\class-wp-hook.php:310
  5. Registrations_Admin_Page_Init->initialize_admin_page() \wp-includes\class-wp-hook.php:286
  6. Extend_Registrations_Admin_Page->route_admin_request() \core\admin\EE_Admin_Page_Init.core.php:194
  7. Extend_Registrations_Admin_Page->_route_admin_request() \core\admin\EE_Admin_Page_CPT.core.php:1130
  8. Extend_Registrations_Admin_Page->_registrations_report() \core\admin\EE_Admin_Page.core.php:1004
  9. Extend_Registrations_Admin_Page->_registrations_report_base() \admin_pages\registrations\Registrations_Admin_Page.core.php:3466
 10. wp_redirect() \admin_pages\registrations\Registrations_Admin_Page.core.php:3439
 11. header() \wp-includes\pluggable.php:1219
```

To reproduce to make sure you have error logging enabled and run a registration report.

This is a clean install with only core activated, not other plugins.

**Comment by sethshoultes** [comment]
@Pebblo are you still experiencing this issue? Has anyone else experienced it?

**Comment by tn3rb** [comment]
the output source appears to be originating from `_print_emoji_detection_script()` in `wp-includes\formatting.php`

we can be removed by adding: 

```php
remove_action( 'wp_head', 'print_emoji_detection_script', 7 );
remove_action( 'admin_print_scripts', 'print_emoji_detection_script' );
```

somewhere to the logic that runs when setting up the registration report.

This **may** need to be patched in earlier in our admin page loading prior to the execution of the above hook points.

**Comment by joshfeck** [comment]
This is still an issue. I'm not aware of it being reported anywhere else. I see a similar PHP warning logged whenever I do a Registration CSV report.

**Comment by mnelson4** [comment]
Hmmm I was intermittently seeing a similar error in debug.log with WP_DEBUG on, PHP's output_buffering turned off, using PHP 7.2, WP 4.9.8, and EE 4.9.58.p. But not consistently (eg every other request I'd see that message in the debug log). I didn't ever reproduce it on EE master though.
@Pebblo sorry to ask, can you still reproduce?

**Comment by hoseinrafiei** [comment]
@Pebblo Would you please try to replicate this issue again?
I tried but wasn't able to see any error. Everything works fine for me.

Since it's very old issue, it might be fixed either by WordPress or ourselves.

**Comment by Pebblo** [comment]
Tested a few different exports and I can't reproduce this anymore.

If it happens again I'll reopen this but for now, closing out.
