### ISSUE TITLE
URL Validation annoyances (in the admin)

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/event-espresso-core#698]
## Issue Overview

In the admin, our URL validation strategy for URL fields still verifies the URL is actually accessible using an HTTP request. This continues to often be annoying because sometimes servers have unexpected setups that cause the HTTP ping to fail and then admins can't set the URL properly.
We most recently removed the HTTP request as part of validation for the front-end on https://github.com/eventespresso/event-espresso-core/commit/36355f6c808. The rationale for why we didn't remove it from the admin was:
> if someone sets the wrong url for a button image, instead of having an error it silently resets it which I think is probably worse UX
So if we're going to disable the HTTP ping for URL validation server-side, our code that checks payment method button URLs are valid should also be disabled. We originally decided to try to fix broken payment method button URLs (on https://events.codebasehq.com/projects/event-espresso/tickets/7308) because
> If you secure your checkout page, the payment method images still load using HTTP
> I can just edit the Image URL within the invoice settings (in this example) to use HTTPS but I think EE should be doing that automatically?

But maybe the problem is just that, if they enter a "bad" URL, we automatically change it to the default. Because our code has erroneously thought valid button URLs were invalid, maybe we should instead only attempt fixing the HTTP/HTTPS part of the URL, and if it's still an "invalid" URL, just leave it (don't replace with the default).

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Environment Data:

Version of EE: 
4.9.67
Version of WordPress:
4.9.9
PHP Version:  
7.1
Browser used:  
Firefox

## Steps to Reproduce (for bugs)

Try to set a payment method's button URL to a URL that's valid but EE can't ping because of special server setup (eg `https://www.njadvancemedia.com`). Disable the server-side URL validation ping (using `add_filter('FHEE__EE_URL_Validation_Strategy__validate__check_remote_file_exists', '__return_true');`) and save.

## Expected Behaviour

If URL validation erroneously finds a URL is invalid, maybe we should just leave it invalid.

## Current Behaviour

The button's URL will pass validation but be automatically updated back to the payment method's default. :cry: 

## Related Information:

Probably related tickets:
https://events.codebasehq.com/projects/event-espresso/tickets/7308
https://events.codebasehq.com/projects/event-espresso/tickets/7956

**Comment by sethshoultes** [comment]
Yes, let's just leave the image URL as invalid.

**Comment by joshfeck** [comment]
example of this:
https://eventespresso.com/topic/your-organization-settings-form-is-invalid/

**Comment by joshfeck** [comment]
another related support topic:
https://eventespresso.com/topic/organization-settings-invalid/

**Comment by joshfeck** [comment]
reported again:

https://eventespresso.com/topic/that-url-seems-to-be-broken-please-enter-a-valid-url-2/

**Comment by joshfeck** [comment]
This was fixed in #939
