### ISSUE TITLE
Remove please note help text from Custom Display Order setting

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/event-espresso-core#702]
**This is not specific to a recent version of Event Espresso**

**Summary**
A few years ago we introduced the custom display order setting to rearrange the event details. Prior to that being available, we used some filters to help with the change and this message was added:

![image 2018-09-22 at 11 27 01 am](https://user-images.githubusercontent.com/1079138/45920548-712e6480-be5a-11e8-99fd-4457fe42fccb.png)

Can we have that removed since its been a few years?

**Steps to reproduce**
This can be seen in the Templates tab in Event Espresso.

**Comment by sethshoultes** [comment]
@joshfeck and @Pebblo what do you think about this suggestion?

**Comment by joshfeck** [comment]
I think what's there can be removed. The contents of the help text there is going to confuse more than clarify anything.
