### ISSUE TITLE
Batch CSV system not adding the UTF-8 BOM characters

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#703]
Reported here: https://eventespresso.com/topic/issues-after-upgrading-from-4-8-25-p-to-4-9-56-p/#post-262482

And again here: https://eventespresso.com/topic/chinese-characters-not-showing-up-on-export/

The batch job handlers use `create_file_from_job_with_name()` to create a temporary file and write the CSV data to it, but that means the new system completely skips the hoop jumping that `EE_CSV->begin_sending_csv(`) jumps through to get the file to open up correctly in excel (and other systems) when using anything other than English - http://take.ms/9W1CX

Can we add the FHEE__EE_CSV__begin_sending_csv__start_writing filter back into the mix when using the batch jobs?

**To Reproduce**
Add some Chinese characters to a registration and export the registrations using the batch system, when you view the registration in Excel the characters will not display correctly.

Now add `define( 'EE_USE_OLD_CSV_REPORT_CLASS', true );` to wp-config.php and repeat.

_I've moved this ticket over from Codebase._

**Comment by sethshoultes** [comment]
@mnelson4 thoughts on this? See Tony's question:

> Can we add the FHEE__EE_CSV__begin_sending_csv__start_writing filter back into the mix when using the batch jobs?

**Comment by mnelson4** [comment]
I can try; the mechanism is a little different now. Before we used to generate the file in-memory and then stream it to the browser; whereas now we direct the browser to download the file normally. I think we might just need to write UTF-8 BOM characters to the beginning of the file

**Comment by mnelson4** [comment]
PR merged
