### ISSUE TITLE
Build System for Importing Data

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#713]
This would be a system for importing attendee and event data. I want to see if we can start with a base system in core for importing data (for example: Example Data), then build add-ons to extend it, such as attendee, event, and venue imports.

Please see the history and discussions in these Codebase tickets:
https://events.codebasehq.com/projects/event-espresso/tickets/11314
https://events.codebasehq.com/projects/event-espresso/tickets/11197
https://events.codebasehq.com/projects/event-espresso/tickets/11202
https://events.codebasehq.com/projects/event-espresso/tickets/11203
https://events.codebasehq.com/projects/event-espresso/tickets/7537

**Comment by mnelson4** [comment]
Ok happy to hear this will be on my plate again. 

First thing I'm going to want to do is re-create different tickets for each use-case because right now this the vagueness of this ticket description is a recipe for trouble (eg I'll probably build for one use-case when the reality will be very different).

**Comment by sethshoultes** [comment]
That makes sense. Shall we turn this into an Epic?

**Comment by mnelson4** [comment]
Ya, I think that would describe this pretty well.

**Comment by sethshoultes** [comment]
Done. Please let me know if you need anything else for this.

**Comment by joshfeck** [comment]
While core did get some additions to support importing data, the system was built in an add-on.
