### ISSUE TITLE
Add tax feature to PayPal Express

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#718]
I thought this was resolved with https://events.codebasehq.com/projects/event-espresso/tickets/4710 but it appears that something has changed so when you set a tax rate within PayPal (and set Paypal Calculates Taxes to Yes in Event Espresso > Payment Methods > PayPal Settings). 

Previously if taxes were added the Payment Status would not update to "Overpaid", but that's what it does not (tested on EE4 master) and reported here:

https://eventespresso.com/topic/overpayment-message-from-paypal-standard-taxes-ee4/

Would it be best to add this feature to PayPal Express instead?

**Comment by mnelson4** [comment]
Yeah I think events.codebasehq.com/projects/event-espresso/tickets/4710  did fix it, but it's been a long time since I've tested it. It will probably be easier to add the feature to PayPal Express and encourage users more strongly to stop using PayPal Standard

**Comment by joshfeck** [comment]
I agree it'd be better to add the feature to PayPal Express.

**Comment by mnelson4** [comment]
I'm starting on this, but it might be worth considering: should we skip Express and instead add this to smart buttons? It seems Express is likely to be deprecated before Smart Buttons just because it's older.

**Comment by mnelson4** [comment]
to-dos:
* [ ] don't send EE taxes to PayPal
* [ ] somehow indicate to PayPal we want them to add taxes?
* [ ] make sure taxes are setup on a PayPal account ( sell_tax_and_ship@eventespresso.com is the one I think)
* [ ] when payment data is returned, update the EE payment etc
* [ ] I think we'll need to store info indicating the order was updated with taxes (and shipping?) from PayPal; which will avoid adding those again if the payment is declined or refunded and the registrant re-pays
* [ ] check over old testing notes from https://events.codebasehq.com/projects/event-espresso/tickets/4710#Consolidated-testing-notes

**Comment by joshfeck** [comment]
I think it'd be fine to add this to Smart Buttons only since this is more akin to a premium feature. While you're working on adding this feature, this issue could be done too:

https://github.com/eventespresso/eea-paypal-smart-buttons/issues/30

**Comment by mnelson4** [comment]
kk I'll investigate doing this for PayPal Smart buttons and look into that other issue first. thanks

**Comment by mnelson4** [comment]
ugh everything's deprecated.
PayPal Express has been deprecated for over 2 years:https://developer.paypal.com/docs/classic/api/#express-checkout

v1 of the PayPal Payments REST API, which we use for smart buttons, is deprecated (not sure since when), I just noticed today. See https://developer.paypal.com/docs/api/payments/v1/#definition-transaction

**Comment by mnelson4** [comment]
Upping the complexity, because IMO we probably should move off the deprecated version of Smart Buttons too... there's quite a bit to figure out with this one...
