### ISSUE TITLE
Fix [GOOGLE_MAP_IMAGE] shortcode used in messages

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#721]
It seems the map image no longer renders when used in a message template.

**Comment by joshfeck** [comment]
It appears that the API key isn't included in the URL when it's an eventsmart site.

**Comment by sethshoultes** [comment]
The images seem to be working for me as well:
![your ticket for event b-2 2018-10-10 06-58-50](https://user-images.githubusercontent.com/235315/46737911-00f55080-cc5a-11e8-9134-1855d1115308.jpg)
![events by espresso wordpress 2018-10-10 06-58-09](https://user-images.githubusercontent.com/235315/46737913-00f55080-cc5a-11e8-9c7d-d7cb4e286325.jpg)

**Comment by sethshoultes** [comment]
Do you want a ticket to look into this on Event Smart?

**Comment by joshfeck** [comment]
I think we're going to need an issue on the Event Smart repo. It doesn't look like the API key is getting set if it's an html ticket. It might be good to check email messages there too.

**Comment by joshfeck** [comment]
I looked into this a bit further and this does appear to be a bug in EE4 core, and the bug is exposed by Eventsmart.

What's happening is we use the `FHEE__EEH_Maps__espresso_google_maps_js__api_key` filter hook on Eventsmart to pass in a Google Maps API key. See https://github.com/eventespresso/eventsmart.com-website/blob/master/plugins/ee-saas-solution/EE_Saas_Restriction_Mods.class.php#L130

This works great on a front end page(like an /events/ or /venues/ page), but on a ticket page (where the URL has ?ee=ee-txn-tickets-url) the function hooked to FHEE__EEH_Maps__espresso_google_maps_js__api_key isn't called.

**Comment by nerrad** [comment]
This ended up just requiring a fix in the EventSmart Repo (you can see https://github.com/eventespresso/eventsmart.com-website/pull/243 for details) so I'm closing out this issue.
