### ISSUE TITLE
Add button to recalculate line items within a transaction

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#726]
See here: https://eventespresso.com/topic/need-to-send-revised-invoice-after-payment/

We've had a couple of requests where users have either forgotten to set a ticket as taxable or their tax rate has changed and they need to update a transaction to include/update the tax.

Brent mentioned in slack that we may be able to add a button in the edit transaction page used to recalculate the line items for the above.

**Is your feature request related to a problem? Please describe.**
If you create a paid ticket on an event and do not set the ticket to be taxable, register and pay on said ticket.

Now update the ticket in the event editor to make it taxable, other than re-registering the previous attendee onto the same ticket there's no way to update the previous registration to request the missing tax.

**Describe the solution you'd like**
Possibly a button to recalculate line items?

This seems similar to the issue mentioned here: https://github.com/eventespresso/eea-attendee-mover/issues/4

**Comment by sethshoultes** [comment]
@tn3rb can you please give an outline of changes and an estimate of time?
