### ISSUE TITLE
Display number of registrations currently checked in

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#733]
This would be nice-to-have feature to show the number of registrations that have the Checked In status. Since an event can have a number of different datetimes with different check-in counts, a possible good place to display this information would be on the Event Espresso > Registrations > Event Check-In page when a specific event or datetime is selected.

**Comment by sethshoultes** [comment]
Great idea!

**Comment by sethshoultes** [comment]
@nerrad can you please outline the modifications involved and estimate for adding a column check-in page? I'm thinking the column would be hidden by default but can be shown in the screen options page.

![image 2018-10-18 12-12-16](https://user-images.githubusercontent.com/235315/47174875-16f4b800-d2cf-11e8-92c0-2363c3786ebb.jpg)

**Comment by nerrad** [comment]
Seth, the screenshot you showed me is a table of individual registrations.  So after reading Josh's original post and your post and looking at the screenshot, are you suggesting we add a column to that table and each row would have a count of checkins for that specific registration?   That seems to contradict Josh's request which is:

> show the number of registrations that have the Checked In status.

You might want to get together with Josh and figure out exactly what the request is here before I comment further?

**Comment by joshfeck** [comment]
Yeah, I didn't ask for a column. Here's a screenshot of what I have in mind:

![screenshot_2018-10-18 testing machine it s ok wordpress](https://user-images.githubusercontent.com/891156/47183205-6817a280-d2f5-11e8-8a09-3e49369f95da.png)

**Comment by sethshoultes** [comment]
Oh okay. Yes, that makes more sense. Should we also add a display for Checked-out, if there any that have that status?

**Comment by joshfeck** [comment]
I think the checked-in count is sufficient.

**Comment by nerrad** [comment]
I'm going to go ahead and assume the feedback-needed label isn't relevant anymore.
