### ISSUE TITLE
Add an Incomplete view to the transactions screen

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/event-espresso-core#735]
**Summary**
Over the past few weeks, I've had conversations with event organizers about sending payment reminders and one common thing that comes up is asking if there is an easy way to see those all at once.

Right now, they are shown on the transactions overview screen and for event organizers with paid events, that will mostly be a line of green down the screen. That is a great thing because it means most attendees are registering and paying. 

However, it makes it difficult to spot those incomplete transactions where a balance is due.

![image 2018-10-16 at 12 40 33 pm](https://user-images.githubusercontent.com/1079138/47032639-d830f780-d140-11e8-9317-2d8bbb4ce56d.png)

---

**Update thread when released**: https://eventespresso.com/topic/list-of-unpaid-transactions-2/#post-280892

**Comment by sethshoultes** [comment]
@lorenzocaum are you suggesting we change the color of the left stripe? If so, I think something a little brighter and contrasting might be good.

**Comment by lorenzocaum** [comment]
For most event organizers with paid events, they'll have paid transactions with some pending payment transactions scattered. Right now, they have to scroll through the transactions screen to find those. 

Here is what I'm referring to:

![image 2018-10-18 at 4 55 13 pm](https://user-images.githubusercontent.com/1079138/47183688-a6fa2800-d2f6-11e8-9856-ca75c5bd8501.png)

Then an event organizer can see incomplete transactions that have a balance due and click to send out payment reminders faster.

**Comment by Pebblo** [comment]
@sethshoultes I've recently opened a pull request (#753) to add a filter that allowed this feature to be added through a snippet.... I then remembered this ticket!

But, because I worked through that PR, I can probably add this in, so shall I give this a shot?

**Comment by sethshoultes** [comment]
Yes, please do :)
