### ISSUE TITLE
Remove the Failed transactions link from Transactions overview screen

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/event-espresso-core#737]
**Summary**
On the transactions overview screen, there is a link that shows Failed transactions. An event organizer can't reach out to the attendee because there is no information connected. And this is difficult to explain to event organizers because it seems like there is a problem with the system.

I think that link to the view should be removed.

If you think there is value in having it appear for some event organizers, then maybe have a filter to restore it.

**Other notes**
- See recent discussion on the P2 and those linked from it (http://p2.eventespresso.com/2018/10/15/this-week-in-event-espresso-october-14-october-20/#comment-19812)
- https://events.codebasehq.com/projects/event-espresso/tickets/7317
- https://events.codebasehq.com/projects/event-espresso/tickets/7412

**Comment by joshfeck** [comment]
+1 on this.

It's been mentioned elsewhere about the value of cart abandonment rates. It would be helpful to have that rate available somewhere, perhaps on an analytics report page. Even better: an integration with Google Analytics for either E-commerce or event tracking.

**Comment by garthkoyle** [comment]
I would concede this change with a filter to turn it back on.

> Even better: an integration with Google Analytics for either E-commerce or event tracking.

+1

**Comment by sethshoultes** [comment]
@tn3rb can you please give us an outline and estimate of time to implement this?
