### ISSUE TITLE
Improvements to General Settings > Your Organization > Country field and General Settings > Countries tab

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#739]
These items need to happen:

A) The General Settings > Your Organization page’s Country input needs to load in all countries (not just active ones)
This is an improvement over the current UI because currently the end user needs to:
1) Go to the Countries tab
2) Select a country
3) Change Country Appears in Dropdown Select Lists == Yes
4) Click Save
5) Go back to General Settings > Your Organization
6) then select the Country

We can eliminate steps 1-5 if all countries load in that input. 
Another reason for this improvement is because, at a quick glance, having only United States and Canada available there by default suggests that's all that EE4 supports. See also:
https://wordpress.org/support/topic/only-for-us-and-canada/

B) The General Settings > Your Organization page’s State input needs to load in States for the currently selected Country. 
This is an improvement over the current UI because currently, for example, if you have United States selected, you have to scroll through Canadian Provences and/or which ever other activated country states are activated on the site

C) The Country value that is saved in that Country input needs to automatically be activated (in other words, its Country Appears in Dropdown Select Lists gets sets to Yes). This was previously requested by Mike in https://events.codebasehq.com/projects/event-espresso/tickets/7410

D) Related to B above, get an XML file or similar ready to auto-populate states for the selected country. See also Mike's comment from this P2:
http://p2.eventespresso.com/2016/02/19/discussion-about-countries-and-states-provinces-pack-hey/#comment-15456

E) Place a metabox at the top of the General Settings > Countries page to include a deactivation form with checkbox list of all currently activated countries. This will allow for quickly deactivating any unneeded countries. Only activated countries would be included in the list, once a country is deactivated it will no longer be included in the form. For the sake of clarity, Country Appears in Dropdown Select Lists set to Yes means the country is activated.

**Comment by garthkoyle** [comment]
These issues are a daily concern with Event Smart. We go through a lot of work to try and onboard people in other locations other than US and CA. I know it would be a slight annoyance to people who don't want the country selection to be too long in their forms, but I think that's a trade off we can handle with E above.

**Comment by joshfeck** [comment]
> I know it would be a slight annoyance to people who don't want the country selection to be too long in their forms, but I think that's a trade off we can handle with E above.

To be clear, the country selection on the front end registrations forms isn't going to get longer with these changes. The change here is only going to affect the General Settings > Your Organization > Country field. Front-end Country fields will remain the same. There are improvements that can be made for the front end form inputs related to selecting Countries & States, but those are separate issues.

**Comment by sethshoultes** [comment]
@tn3rb can you please give me an outline and estimate of time for this?
