### ISSUE TITLE
Change defaults in db schema for datetime fields

### ISSUE THREAD

**Issue by nerrad** [eventespresso/event-espresso-core#748]
## Issue Overview

As a part of the work in #747 and #743, it was discovered that there's issues with instantiating a `DateTime` object with a value of `0000-00-00 00:00:00` as the timestamp (for backstory follow the links).  It's likely that any fields with that value saved to them in the db have it defined as a default in the schema _plus_ allow null as a part of the field config (defined in models) (where null gets converted to `0000-00-00 00:00:00`) on persisting to the db.

Long term, it'd probably be a good idea to change things so we're not using this as a default.

#747 and #743 deal with the issue codewise so there's not an immediate need for this to be done but probably would still be good to do at some point.

@mnelson4 I've asked for your feedback in case there's some reason you're aware of where we should definitely leave `0000-00-00 00:00:00` as the schema default for the db?

**Comment by mnelson4** [comment]
sorry I didn't notice "feedback needed" tickets in Zenhub. (I know how to search by label per-repository, but I'm not sure if I can do that across all repos yet).
But no, I'm not aware of any reason the DB default needs to be `0000-00-00 00:00:00`. What alternative default should we have? null? current date?

**Comment by nerrad** [comment]
Mike, here's a screenshot that shows how I discover `status:feedback-needed` issues/pulls needing looked into: 

![zenhub screenshot](https://www.evernote.com/l/AAM8NQG5HflCJ5xocIr3ahyR-W7NR5P3F0IB/image.png)

Notice, that I have all repos selected in the top left (that's my usual view in the Zenhub board).

It's worked really well for me keeping on top of things.  I offer it as an option that might work well for you.

> What alternative default should we have? null? current date?

I think in nearly all cases our models set the default as "now" so that should be an acceptable default for the table schema.  However, it's not guaranteed that the mysql database will be setup in the same timezone as a site so we'll have to account for that in the table schema likely.

**Comment by mnelson4** [comment]
thanks Darren yes that is very helpful- I hadn't noticed I could collapse the pipelines or filter by labels in there.
Ya setting the default to the MySQL current time would probably be better, although I'm not sure what we can do about the timezone. What's more, the timezone may change after the tables are created. So I'm inclined to just take the easier option and set it to the current time in whatever timezone MySQL is set to. The models will generally provide the current time, in the site's timezone, as the default anyway.

**Comment by nerrad** [comment]
@mnelson4 one thing to keep in mind is mysql _does_ have unix time date functions.  Since all our times stored in the db are considered UTC you probably could use [`UTC_TIMESTAMP`](https://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html#function_utc-timestamp) for this.
