### ISSUE TITLE
Increase default for pagination for registration form overview screen to 20

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/event-espresso-core#750]
**Summary**
This is similar to https://github.com/eventespresso/event-espresso-core/issues/723. The default for the questions pagination is 10 so when an event organizers creates a new one, its on page 2.

Can we raise the default limit from 10 to 20?

**Comment by nerrad** [comment]
If the feedback needed from me is whether we can do this, the answer is yes.

**Comment by sethshoultes** [comment]
Thanks. Hopefully, it's something quick and simple :)

**Comment by joshfeck** [comment]
Same idea proposed in #723. No need to create separate issues for this.
