### ISSUE TITLE
Email subject line - character encoding error

### ISSUE THREAD

**Issue by kristinoc** [eventespresso/event-espresso-core#751]
Email marketing message - has character encoding error that is causing the weird characters to show in email subject line
![email_character encoding](https://user-images.githubusercontent.com/37596604/47313875-4ff99900-d5fd-11e8-8e5e-0ae1905b676a.jpeg)

Received this email message. see attached.

**Comment by sethshoultes** [comment]
Issue moved to [eventespresso/eventespresso.com-website #102](https://github.com/eventespresso/eventespresso.com-website/issues/102) via [**ZenHub**](https://www.zenhub.com/)
