### ISSUE TITLE
Add filters to allow overriding help tours

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/event-espresso-core#754]
**Summary**
Here is the feedback that Nazar shared here (https://github.com/eventespresso/eventsmart.com-website/pull/275#issuecomment-432587177):

> It is not working because a wrong filter is used for this. Most templates are generated with `EEH_Template::display_template()` and that is where the `FHEE__EEH_Template__display_template__template_path` filter resides (which is used in this PR).
> 
> Help tours, on the other hand, are generated with a different method - `EEH_Template::help_tour_stops_generator()` and I don't see an obvious and proper hook.
> 
> The path to each help tour class looks to be hard-coded in the `_add_help_tour()` method in the `EE_Admin_Page.core.php`. And there are also no filters in the help tour classes to make those required changes.
> 
> I think that we will need more EE core changes to be able to filter the help tours.
>

**Comment by sethshoultes** [comment]
@knazart is this something you are comfortable with adding?

**Comment by joshfeck** [comment]
We have some documentation on naming conventions to use when adding new hooks:

https://github.com/eventespresso/event-espresso-core/blob/master/docs/A--Best-Practices/ee-actions-and-filters.md

**Comment by tn3rb** [comment]
looks like the filter needs to be applied to `$this->_help_tour` right at the very end of `EE_Admin_Page::_add_help_tour()`
