### ISSUE TITLE
Database errors in a single installation on a multisite

### ISSUE THREAD

**Issue by jonathan-dejong** [eventespresso/event-espresso-core#76]
Hi. 
If I'm supposed to put this in the EE support forum I apologize. Yell at me and I'll post it there instead. I figured that I'm usually sent here when the question is a bit more technical anyway. 

I'm having some strange behaviours going on in my dev-setup of a multisite installation. EE is only activated for the main site (NOT network activated) and it runs smoothly on the prod site. Seemingly randomly and sometimes when I've pulled a fresh version of the DB from prod to dev (WP Migrate DB Pro) the network admin goes blanc and the error log spits out this error:

```
[20-May-2015 14:28:07 UTC] WordPress databasfel för Table 'kfsk_db.wp_14_esp_event_meta' doesn't exist förfrågan SELECT COUNT(Event_CPT.ID) FROM  wp_14_posts AS Event_CPT  LEFT JOIN wp_14_esp_event_meta AS Event_Meta ON Event_CPT.ID = Event_Meta.EVT_ID  WHERE Event_CPT.post_type = 'espresso_events' AND Event_CPT.post_status NOT IN ('auto-draft','trash') skapat av require_once('wp-admin/network/admin.php'), require_once('wp-admin/admin.php'), do_action('admin_init'), call_user_func_array, EE_PUE->track_event_info, EEM_Soft_Delete_Base->count, EEM_Base->count, EEM_Base->_do_wpdb_query, call_user_func_array
[20-May-2015 14:28:07 UTC] PHP Fatal error:  Uncaught exception 'EE_Error' with message 'WPDB Error: "Table 'kfsk_db.wp_14_esp_event_meta' doesn't exist"' in /srv/www/projects-collaboration/kfsk/htdocs/wp-content/plugins/event-espresso-core-reg/core/db_models/EEM_Base.model.php:1451
Stack trace:
#0 /srv/www/projects-collaboration/kfsk/htdocs/wp-content/plugins/event-espresso-core-reg/core/db_models/EEM_Base.model.php(1388): EEM_Base->_do_wpdb_query('get_var', Array)
#1 /srv/www/projects-collaboration/kfsk/htdocs/wp-content/plugins/event-espresso-core-reg/core/db_models/EEM_Soft_Delete_Base.model.php(124): EEM_Base->count(Array, NULL, false)
#2 /srv/www/projects-collaboration/kfsk/htdocs/wp-content/plugins/event-espresso-core-reg/core/EE_PUE.core.php(330): EEM_Soft_Delete_Base->count()
#3 [internal function]: EE_PUE->track_event_info('')
#4 /srv/www/projects-collaboration/kfsk/htdocs/wp-includes/plugin.php(496): call_user_func_array(Array, Array)
#5 /srv/www/projects-collaboration/kfsk/htdocs/wp-admin/admin.php(158): do_action('admin_init')
#6 /srv/www/p in /srv/www/projects-collaboration/kfsk/htdocs/wp-content/plugins/event-espresso-core-reg/core/db_models/EEM_Base.model.php on line 1451
```

What's interesting is that the site in question has never had EE activated and there is absolutely no esp_ table in the wp_14 tables. If I go directly to that sites admin and activate EE the error disappears but now the network also thinks that site with id 14 is the "main site". I can now delete EE completely from the "maintenance" page and the DB error is gone but the network is still fooled into thinking 14 is the main site.. On some occasions the siteurl and home values for the main sites wp_options have also been changed to site 14s url (not every time I tested it tho). 

Very strange!

**Comment by nerrad** [comment]
What's wierd, is EE should only be running on the main site if that's the only site you have it active on.  I *think* however that the network admin is considered part of the "main site" with plugins activated.  We'll investigate and get back to you.

**Comment by nerrad** [comment]
Jonathon is it possible that you have another plugin active that is doing a `switch_to_blog()` at some point and then not switching back?  It's possible that the EE queries that are running are happening while the internal WP process is set to have the "$current_blog" set to another blog (which affects all queries running then).  I'm wondering if that may be something that DB Migrate is doing while migrating multisite dbs (and somehow other plugin hooks are fired while that's happening?)

**Comment by jonathan-dejong** [comment]
Hmm.. I'm using switch_to_blog on a few places myself within the theme (not in any of my own plugins) but I'm 100% sure I'm switching back each time (otherwise something would definitely break on the frontend). I'm also using Elasticsearch with elasticpress to do global searches and queries but I don't think that they use switch_to_blog at all since the whole point is to index sites within elasticsearch. 

DB migrate has the ability to install a mu plugin which runs before push/pull that disables selected plugins during the migration which I've tried enable and disabled all plugins including EE. I'll try disabling everyone except EE and do a new migration to see if anything changes.

What's funny is that now that I'm about to do a migration DB Migrate also think that wp_14 is the main tables and throws a warning:
```
Warning: Different Table Prefixes

Whoa! We've detected that the database table prefix differs between installations. Clicking the Migrate button below will create new database tables in your local database with prefix "wp_".

However, your local install is configured to use table prefix "wp_14_" and will ignore the migrated tables. So, AFTER migration is complete, you will need to edit your local install's wp-config.php and change the "wp_14_" variable to "wp_".

This will allow your local install the use the migrated tables. Once you do this, you shouldn't have to do it again.
```

wp-config is set to 'wp_' tho and I can't find any reference to the main table ID in DB (not sure where to look but I've checked wp_options, wp_sites, wp_sitemeta etc.).

**Comment by mnelson4** [comment]
hi @jonathan-dejong yes that is very strange. Like @nerrad I'm also very suspicious of the blog switching.that's going on and would suggest trying to grab more info on it.
If I were in your situation I'd suggest trying to track every call to `switch_to_blog()` by echoing out something within the wp core function, possibly along with a call to `debug_backtrace(DEBUG_BACKTRACE_PROVIDE_OBJECT , 2)` to find out who's calling the method. That way you can know when it's being called and by what code. It would probably also be good to track `restore_current_blog()` in the same manner. I'd be espeically suspicious of any code that's switching the blog to blog 14.
But from the sounds of it, I don't see how EE core could be the culprit: it never does any blog switching or changes to `$wpdb`. It throws that exception whenever one of its model database queries has an error (whereas elsewhere in WP it just spits out the error).

**Comment by nerrad** [comment]
the other thing you might want to check into is if there's a `switch_to_blog()` early in the request (i.e. in an init callback) and then a `restore_current_blog()` later in the request  (i.e. a later hook).

**Comment by jonathan-dejong** [comment]
Since the live site didn't have these issues I figured I'd do some hard-resetting first. I completely removed all plugins from dev and imported them anew from live so to be sure they have the exact same "this could be what's messing it up" factor. 

Now the issue is gone. I'm going to try a migration again just to be sure. I suppose the issue then was in one of the dev plugins I had.. hm.
