### ISSUE TITLE
Cannot modify header information - headers already sent by pluggable.php on line 1219

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/event-espresso-core#766]
**Summary**
This was reported here (https://github.com/eventespresso/eventsmart.com-website/issues/280). However, it is reproducible elsewhere.

```
24 Oct 2018 07:40:07.287[24-Oct-2018 11:40:07 UTC] PHP Warning: Cannot modify header information - headers already sent by (output started at /wordpress-4.9.8/wp-includes/script-loader.php:1554) in /wordpress-4.9.8/wp-includes/pluggable.php on line 1219
```

**Steps to reproduce**
- Enable debug.log on your site
- Run a registration report

**Reported or seen on**
https://github.com/eventespresso/eventsmart.com-website/issues/280

**Other notes**
The reports still work even with the PHP warnings.

**Comment by mnelson4** [comment]
Hmmm I'm not reproducing this issue.

I've tried EE 4.9.71.rc.000, WP 4.9.9-alpha-43715, EE infusionsoft and Promotions active. I see other PHP warnings are getting into my debug.log, but when I generate a registration CSV report (either the "Filtered CSV Report" or "All Registrations CSV Report") I don't get any warnings appearing in my debug.log.

I also tried on my local copy of ES and no luv. (I'm seeing other warnings n stuff go into debug.log, but not that one).

Can you share what version of WP and what add-ons you're using @lorenzocaum or @knazart? That might help me in debugging.

**Comment by lorenzocaum** [comment]
This came up again while testing on the staging for Event Smart.

**Comment by mnelson4** [comment]
I'm not too overly concerned about this, as it's just a warning that occurs when WP_DEBUG is on and not reproducible locally. But when I get to working on this, I'll try to reproduce on MENW and then on my local copy of ES, and see where that takes me.

**Comment by lorenzocaum** [comment]
This appears to just happen on Event Smart along with the staging area.

**Comment by joshfeck** [comment]
OK then likely not a core issue.
