### ISSUE TITLE
Confirmation message doesn't show on the transactions overview screen

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/event-espresso-core#767]
**Seen on a current release**

**Summary**
If you use one of the actions on the registrations overview screen or another one like the messages overview screen, then it shows a confirmation of what was done.

However, on the transactions overview screen, the page refreshes without showing a confirmation.

For example, try sending a payment reminder from the transactions overview screen using the action item for the envelope. The message is sent out but there isn't a confirmation shown at the top of the page.

**Steps to reproduce**
See above

**Comment by joshfeck** [comment]
This is a duplicate of [11499](https://events.codebasehq.com/projects/event-espresso/tickets/11499)
