### ISSUE TITLE
Customize Unauthorized message from PayPal

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/event-espresso-core#772]
**Summary**
With PayPal Express and PayPal Express Checkout Smart Payment Buttons, we check the credentials on save to make sure they work. If there is a problem such as entering them in the wrong order, then an event organizer will see something like this:

Error validating PayPal credentials. Unauthorized

![image 2018-11-02 at 7 40 26 am](https://user-images.githubusercontent.com/1079138/47913464-96a78880-de72-11e8-8ce9-06ef5b56cf05.png)

Could we tailor the "unauthorized" message so its more specific to the payment gateway?

That way we can provide some tips to get back on track.

Examples:

- [PayPal Express] PayPal did not accept your API credentials. Double-check your credentials and copy and paste them into the fields again and save changes. Alternatively, remove your existing credentials in PayPal.com and request new API credentials and try them.

- [PayPal Smart Buttons] PayPal did not accept your API credentials. Double-check your credentials and copy and paste them into the fields again and save changes. Alternatively, create a new app and try the new API credentials.

**Other notes**
Also see: https://github.com/eventespresso/eea-paypal-smart-buttons/issues/27

**Comment by mnelson4** [comment]
PR merged
