### ISSUE TITLE
Attendee Block settings shouldn't have Archive Settings when editing WP page

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#777]
**Describe the bug**

If you're working on adding an Attendee block to a WP page, the block settings includes the Archives Settings section. I think we only need that setting if it's a WP post (or other post type that has archives).

**Environment:**
 - Version of Event Espresso:  master
 - Version of WordPress: 5

**Comment by nerrad** [comment]
@sethshoultes I'm going to move this to my in progress and get it done over the weekend, should be a fairly trivial fix (hopefully).
