### ISSUE TITLE
Querying past events with support for this and that

### ISSUE THREAD

**Issue by jonathan-dejong** [eventespresso/event-espresso-core#78]
Hi!

Following up on the dev portals comments. 
I've currently created a custom wpdb query with which I find past events and implement some pagination. 

It's a bit of a hack and I haven't had the time to prepare the queries (they are still just a fetch so not too important). I'd love an example of how I do pretty much the same thing with the new and improved date handling in EE. In a dreamworld it'd be so easy as to hook into something like pre_get_posts and setting some custom wp_query parameters.. That would let me use the regular archive with just a GET parameter to display past events and would support search, pagination etc. out of the box *drool*

```
<?php
		//fetch all previous events with a custom wpdb query
		global $wpdb;
		$posts_per_page = 10;
		$current_page = isset( $_GET['archivepage'] ) ? abs( (int) $_GET['archivepage'] ) : 1;
		$offset = ( $current_page * $posts_per_page ) - $posts_per_page;
		//The main query
		$query = "SELECT wp_posts.*, wp_esp_datetime.* , wp_esp_event_meta.* FROM wp_posts INNER JOIN wp_esp_datetime ON ( wp_posts.ID = wp_esp_datetime.EVT_ID ) LEFT JOIN wp_esp_event_meta ON ( wp_esp_event_meta.EVT_ID = wp_posts.ID ) WHERE 1=1  AND wp_posts.post_type = 'espresso_events' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'cancelled' OR wp_posts.post_status = 'postponed' OR wp_posts.post_status = 'sold_out' OR wp_posts.post_status = 'private') AND wp_esp_datetime.DTT_EVT_end < curdate() GROUP BY wp_posts.ID ORDER BY wp_esp_datetime.DTT_EVT_start DESC LIMIT $offset, $posts_per_page";

		//The total query, stripped down.
		$total_query = "SELECT wp_posts.* FROM wp_posts INNER JOIN wp_esp_datetime ON ( wp_posts.ID = wp_esp_datetime.EVT_ID ) LEFT JOIN wp_esp_event_meta ON ( wp_esp_event_meta.EVT_ID = wp_posts.ID ) WHERE 1=1  AND wp_posts.post_type = 'espresso_events' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'cancelled' OR wp_posts.post_status = 'postponed' OR wp_posts.post_status = 'sold_out' OR wp_posts.post_status = 'private') AND wp_esp_datetime.DTT_EVT_end < curdate()";

		//get events
		$past_events = $wpdb->get_results($query);
		//Get total events
		$total = $wpdb->get_var( "SELECT COUNT(*) FROM ($total_query) AS combined_table" );
		?>
		<?php if(!empty($past_events)): ?>
			<?php foreach( $past_events as $post ): setup_postdata($post); ?>
				<article <?php post_class('article-item clearfix'); ?> id="event-<?php echo get_the_ID(); ?>">
					…
				</article>
			<?php endforeach; ?>
			<?php
			//setup pagination
			$pagination = paginate_links( array(
				'base' => add_query_arg( 'archivepage', '%#%' ),
				'format' => '',
				'prev_text'    => __( '&lsaquo;', 'event_espresso' ),
				'next_text'    => __( '&rsaquo;', 'event_espresso' ),
				'total' => ceil($total / $posts_per_page),
				'current' => $current_page,
				'type' => 'plain'
			));
			echo ! empty( $pagination ) ? '<div class="ee-pagination-dv clear">' . $pagination . '</div>' : '';
			?>
			<?php wp_reset_postdata(); ?>

		<?php else: ?>
			…
		<?php endif; ?>


```

**Comment by nerrad** [comment]
Here' how you can do the above using the EE model system (with the new datetime work branch, if you want to use with current master you just substitute `time()` with `current_time()`:

```
<?php
//example just using ee models
//fetch all previous events with a custom wpdb query
$posts_per_page = 10;
$current_page = isset( $_GET['archivepage'] ) ? abs( (int) $_GET['archivepage'] ) : 1;
$offset = ( $current_page * $posts_per_page ) - $posts_per_page;

$where = array(
		'status' => array( 'IN', array( 'publish', 'private', EEM_Event::postponed, EEM_Event::cancelled ) ),
		'Datetime.DTT_EVT_end' => array( '<', time() )
	);

$past_events = EEM_Event::instance()->get_all( array(
	//where conditions are always an array at index 0
	0 => $where,
	'group_by' => 'EVT_ID',
	'order_by' => array( 'Datetime.DTT_EVT_start' => 'DESC' ),
	'limit' => array( $offset, $posts_per_page )
) );
$count = EEM_Event::instance()->count( array( $where ), 'EVT_ID', true );

?>
<?php if( ! empty($past_events) ): ?>
	<?php foreach( $past_events as $event ) :  ?>
		<article <?php post_class('article-item clearfix', $event->ID() ); ?> id="event-<?php echo $event->ID(); ?>">
			…
		</article>
	<?php endforeach; ?>
	<?php
	//setup pagination
	$pagination = paginate_links( array(
		'base' => add_query_arg( 'archivepage', '%#%' ),
		'format' => '',
		'prev_text'    => __( '&lsaquo;', 'event_espresso' ),
		'next_text'    => __( '&rsaquo;', 'event_espresso' ),
		'total' => ceil($total / $posts_per_page),
		'current' => $current_page,
		'type' => 'plain'
	));
	echo ! empty( $pagination ) ? '<div class="ee-pagination-dv clear">' . $pagination . '</div>' : '';
	?>
<?php else: ?>
	…
<?php endif; ?>
```

Now I'm not sure what "archive" page you want this to be on, but if its the default event archive page, take a look at `core/CPTs/EE_CPT_Strategy.core.php`, that's the strategy class that works for modifying the default WP_Query when the "events" archive page is loaded.  You can birth the dream world you talk of by manipulating the filters in there to setup the query parameters you want (if you just want to modify the existing CPT archive page - if you want to do something similar for your custom archive page you can likely learn from how we're doing it and implement your solution that way).  Keep in mind that if you are modifying the filters in this strategy (by de-registering and then registering your own), you want to make sure you have conditions in your callback that only account for the main query (otherwise you'll be modifying every wp_query involving events).

**Comment by nerrad** [comment]
Oh forgot to mention.  With my code example, in the loop, each `$past_event` is actually an `EE_Event` object.  So you can output the information you want just using the `EE_Event` methods (including any post_meta that might be attached to the event).  All other information is accessible via that object and if you need more pointers for that just let me know.

**Comment by tn3rb** [comment]
@jonathan-dejong 
so has this issue been resolved for you?

**Comment by jonathan-dejong** [comment]
@tn3rb 
I haven't had the chance to pursue this further yet as other things keep coming in between! :) 
But if you want to close it for simplicity sake that's fine.

**Comment by tn3rb** [comment]
kk thnx
just reopen or start a new issue if required
