### ISSUE TITLE
Provide alternative way of doing "IN" or "NOT IN" type entity REST queries.

### ISSUE THREAD

**Issue by nerrad** [eventespresso/event-espresso-core#781]
**Is your feature request related to a problem? Please describe.**

The current method for doing "IN" type queries using the REST API is very verbose:

```
https://mydomain.com/wp-json/ee/v4.8.36/events/where[EVT_ID][0]=IN&[EVT_ID[1]=1414&[EVT_ID][1]=1412
```

While this follows more closely our model behaviour for these type of queries, there's a couple problems:

- it's harder for client code to automatically generate the necessary query string for these type of queries.
- it's much more likely that query string character limits will be hit for these type of queries (for every single ID in the above query there's an additional 12 characters needed!)

I'd like to propose we follow a simpler format for the query string:

```
https://mydomain.com/wp-json/ee/v4.8.36/events/where[EVT_ID][IN]=1414,1412
```

**Comment by mnelson4** [comment]
PR merged
