### ISSUE TITLE
Improve line items sent with PayPal Pro gateway when promotion is applied at checkout

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#789]
**Describe the bug**

Line items for each type of ticket are not sent with the PayPal Pro gateway when a promotion code is applied at checkout.
Real-world scenario described here:
https://eventespresso.com/topic/promotion-code-disrupts-flow-of-ticket-information-from-ee-to-paypal/
**To Reproduce**

1. Set up an event with more than one ticket type, label each ticket type with a unique name
2. Register for the event, select multiple ticket types, then pay with PayPal Pro
3. Check the line item names sent in EE > Payment Methods > Logs
4. Repeat 2, and redeem a promo code at checkout
5. Compare the line item name sent in EE > Payment Methods > Logs

**Expected behavior**

Ideally the names of the tickets should be included regardless of promotion applied at checkout.

**Comment by tn3rb** [comment]
from chat:

> Brent Christensen [9:48 AM]
> I think the problem might be in `EE_Gateway::_sum_items_and_taxes()`
> which is called by `EE_Gateway::_can_easily_itemize_transaction_for()`
> which is used by `EEG_Paypal_Pro::do_direct_payment()` to decide how to send the line items
> `EE_Gateway::_sum_items_and_taxes()` does the following:
> 
```
foreach ($total_line_item->get_items() as $item_line_item) {
    $total += max($item_line_item->total(), 0);
}
```
> 
> which is going to break when it hits a negative line item
> because it will switch the amount to `0` instead of `-10` (or whatever amount the promo is for)
> ...from the phpdocs:
> 
```
This can be used to determine if some more complex line items, like promotions,
surcharges, or cancellations occurred (in which case we might want to forget
about creating an itemized list of purchases and instead only send the total due)
```
> 
> Mike Nelson [9:52 AM]
> I think that’s there because some gateways don’t support negative line items. But I bet PayPal pro would work with them
> 
> Brent Christensen [9:52 AM]
> so I'm assuming PayPal chokes on those line item types (edited)
> 
> Mike Nelson [9:53 AM]
> Well or you might need to send them differently
> 
> Brent Christensen [9:53 AM]
> right...
> 
> Mike Nelson [9:53 AM]
> It’s worth a ticket imo
> 
> Brent Christensen [9:53 AM]
> anyways,, my ultimate point is that if PPPro needs that gist to work with promotions, then we should likely add that logic directly to the gateway
> I wouldn't add it to the promo add-on because it appears to affect other line items as well
> 
> Josh Feck [9:54 AM]
> that gist just works around the logic
> 
> Brent Christensen [9:56 AM]
> right... well the other option is to examine PPPro some more to determine if they accept negative line items, and if so, refactor its `EEG_Paypal_Pro::do_direct_payment()` method accordingly
> I bet there is a better solution than waiting for people to hit the forums and then directing them to that gist
> 
> Josh Feck [9:58 AM]
> Yeah the better solution would be to not send a single generic line item when there happens to be a promotions in the mix.

**Comment by mnelson4** [comment]
the related PR is awaiting testing

**Comment by joshfeck** [comment]
PR #817
