### ISSUE TITLE
Simplify relation write/delete interface for REST api.

### ISSUE THREAD

**Issue by nerrad** [eventespresso/event-espresso-core#790]
## Issue Overview

Currently in order for REST clients to manage relations between entities for our REST Api they need to:

- know the type of relation they are dealing with
- depending on the type, discover the foreign key for the relation and update OR the join table for the relation.
- build a request for the appropriate join table if the relation has one.

That's a number of complicated steps involving parsing involved schemas for automating client CUD tasks around relations.

I'd like to propose we implement a somewhat simplified relation management structure for our API that looks something like this:

`PUT /ee/v4.8.36/events/10/datetime/20` for **adding relations**

This request would add a relation between the event entity with the id of 10 and the datetime entity with the id of 20.  You probably could accept `POST` write method for this as well although I think we may want to reserve that for future iterations where a create might be involved as well.

`DELETE /ee/v4.8.36/events/10/datetime/20` for **removing relations**

This request would remove the relation between the event entity with the id of 10 and the datetime entity with the id of 20.

## Other notes regarding _initial iteration_ of this:

- permissions work the same as write endpoints for initial iteration (which currently means user has to be an administrator).  Finer grained permissions would be iterated on separately.
- these endpoints will require _both_ entities to already exist.  Later iterations maybe can implement special handling for creating new entities via a `POST` request but that's something more complicated that can be worked on later (and might never be needed).

**Comment by mnelson4** [comment]
Related codebase ticket: https://events.codebasehq.com/projects/event-espresso/tickets/10550

An initial working version of this would be about 4-5 hours, unit tests would be another 2-3 hours, anticipated probably code tidy-up may be another 1-4 hours.

Also this may make fine-grained permissions a little trickier (it's just another endpoint that needs to account for permissions), but I think we should proceed with this regardless.
