### ISSUE TITLE
Prepare EE for PHP 7.3

### ISSUE THREAD

**Issue by nerrad** [eventespresso/event-espresso-core#794]
**Describe the bug**

Our automated tests on travis are showing a number of fails in a PHP 7.3 environment. We don't currently have those fails block "success" for the entire build but with PHP 7.3 dropping soon (December) we need to get working on figuring out why our tests are failing and discover if there's any fixes we need to add to EE for php 7.3.

As a part of this work, we should probably update our travis configuration so that PHP7.3 failing builds are not skipped (for success measurement) and add a build for the next version of PHP (that is allowed to fail).

Might be a good time to do another PHP version stat measurement for our users and see if we can plan to bump our minimum version requirements again.

**Comment by nerrad** [comment]
@tn3rb I'm on the fence regarding priority of this.  I don't anticipate most of our customers will run into issues with this for at least a couple months because I don't think most hosts will bump up to 7.3 right away (WP Engine _just_ started provisioning PHP 7.2).  But I do think we might want to get on this fairly soon in the new year at least?

**Comment by nerrad** [comment]
It should be noted that a number of the fails in PHP 7.3 are actually caused by WordPress core files, so that should be fixed once WP 5.0 ships.  But I think there's still at least a couple that are in our code (which _should_ be fairly trivial fixes).

**Comment by joshfeck** [comment]
getting this warning on a php7.3 test site:

```PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /srv/www/wordpress-default/public_html/wp-content/plugins/32-core/admin_pages/transactions/Transactions_Admin_Page.core.php on line 1429```

**Comment by joshfeck** [comment]
Update: the above warning no longer happens after updating to WP 5.0.2 RC.
