### ISSUE TITLE
Display Error if admin attempts to set both a Country's Currency Decimal Mark AND Thousands Separator to the SAME value

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#795]
From Codebase: https://events.codebasehq.com/projects/event-espresso/tickets/4879

As well... "Seperator" is spelled wrong in the label "Currency Thousands Seperator"

**Comment by joshfeck** [comment]
The typo with "Seperator" was fixed in another PR.

**Comment by joshfeck** [comment]
Result of this gotcha:

https://eventespresso.com/topic/bug-price-of-ticket-is-multiplied-by-10-when-updating-an-event/
