### ISSUE TITLE
Attendee Block's "Number of Attendees to Display:" slider control could be perceived to only allow displaying a max of 100 attendees

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#799]
Events will have more than 100 attendees, and the slider control stops at 100.

You **can** type in a higher limit if you ignore the slider control and input numbers directly into the text field. I wonder if the option would be easier to use if the slider was removed or replaced? A slider that stops at 100 would seem to be best used for controlling percentage based option values (like setting a width or scaling an image).

Also, I think the default value of 10 is a bit low (the shortcode also defaulted to 10 and this led to more than a few "My attendee list is missing names!" support requests). Could the default limit be 100?

**Comment by joshfeck** [comment]
@nerrad we've discussed this in slack and I remember we came to the conclusion that this control shouldn't be a slider. 

https://eventespresso.slack.com/archives/C080L8G68/p1546873722284600

What do you estimate for the effort to change the control to a number instead?

**Comment by nerrad** [comment]
I don't think the estimate needs to change from what it already is...
