### ISSUE TITLE
Undefined property: EE_Template_Config::$EED_Ticket_Selector 

### ISSUE THREAD

**Issue by sumobi** [eventespresso/event-espresso-core#80]
Master branch. When updating an event this notice appears twice:

`PHP Notice:  Undefined property: EE_Template_Config::$EED_Ticket_Selector in /wp-content/plugins/event-espresso-core/modules/ticket_selector/EED_Ticket_Selector.module.php on line 283`

Notices are also shown when viewing the event on the front-end

**Comment by lorenzocaum** [comment]
Thanks Andrew!

Reported in Codebase as 8298

**Comment by Pebblo** [comment]
Hi Andrew,

Our developers are investigating this however currently if you go to Event Espresso -> Events -> Templates (tab) - http://take.ms/dMgEy

Make no changes and simply save the settings, the notices will no longer be thrown.

**Comment by joshfeck** [comment]
The fix has been pushed to Master.
