### ISSUE TITLE
PHP warning-proof PUE client

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#803]
These errors were logged on an EE4 site:

`PHP Warning: Attempt to assign property of non-object in /wp-content/plugins/event-espresso-core-reg/core/third_party_libs/pue/pue-client.php on line 1650`

`PHP Warning: Attempt to assign property of non-object in /wp-content/plugins/event-espresso-core-reg/core/third_party_libs/pue/pue-client.php on line 1651`

`PHP Warning: Attempt to assign property of non-object in /wp-content/plugins/event-espresso-core-reg/core/third_party_libs/pue/pue-client.php on line 1655`

`PHP Warning: Invalid argument supplied for foreach() in wp-content/plugins/event-espresso-core-reg/core/third_party_libs/pue/pue-client.php on line 1166`

reported here:
https://eventespresso.com/topic/contining-php-errors/

**Comment by sethshoultes** [comment]
@nerrad or @knazart can you please look into this?
