### ISSUE TITLE
Inconsistent spacing around form elements

### ISSUE THREAD

**Issue by sumobi** [eventespresso/event-espresso-core#81]
Master branch

There appears to be inconsistent spacing around form elements:

![screen shot 2015-06-05 at 1 58 37 pm](https://cloud.githubusercontent.com/assets/52581/7998051/063afd44-0b8b-11e5-9c5d-d9a5607ad022.png)

This is caused by the 250px width on the elements:

`textarea.all-options, input.all-options {
    width: 250px
}`

I propose changing this width to `100%` so it looks more consistent with the UI

![screen shot 2015-06-05 at 2 01 26 pm](https://cloud.githubusercontent.com/assets/52581/7998081/6e0f65b8-0b8b-11e5-910b-a86fdb8523a6.png)

And if you moved the metabox:

![screen shot 2015-06-05 at 2 01 32 pm](https://cloud.githubusercontent.com/assets/52581/7998080/6e04e64c-0b8b-11e5-8cf7-f695a6b98b66.png)

**Comment by nerrad** [comment]
see #82, the commits pushed there should fix.
