### ISSUE TITLE
Fix failing unit test build in master

### ISSUE THREAD

**Issue by nerrad** [eventespresso/event-espresso-core#812]
## Issue Overview

There is a failing unit test build being [reported for master](https://travis-ci.org/eventespresso/event-espresso-core/jobs/463442564) and it looks like a test that was introduced with the password protection work recently merged in.

@mnelson4 I've assigned this to you because it should be fixed asap and merged into master so that new pulls based off master or existing pulls bringing in master changes don't have failing test runs.

**Comment by mnelson4** [comment]
dang I thought I had fixed that one... did I forget to create the PR? ...

**Comment by mnelson4** [comment]
yeah that PR fixed this.
