### ISSUE TITLE
PLease remove unnecessary string storage in database

### ISSUE THREAD

**Issue by chaserau** [eventespresso/event-espresso-core#816]
Hi, IT support for a venue that uses EE4 here, one big request/suggestion for developers. Please consider going through your code and removing instances where placeholder strings are stored in the database for regularly occurring entries.

Examples of these are 'A message with this status indicates that there was a problem...' paragraph stored when there is a mailing error (EE_Message.class.php), and "No Biography Provided" saved as both the post_content and post_excerpt in WP_posts when a user us created without providing biography info. There are plenty of others that I can't remember off the top of my head.

In the latter case, storing the value as null or an empty string could then be interpreted code side to display "No Biography Provided" if null, rather than storing the string in the database. This is important because a database with 5000 customers then suddenly has 10,000 instances of "No Biography Provided" stored as a string for seemingly no reason.

This stuff doesn't seem like much on a dev/new/barebones site, but on a website running for a year these erroneous strings have led to a very oversized database, which makes backing up a headache.

**Comment by nerrad** [comment]
Yeah I think we can take a look at where we're storing placeholder content in the database unnecessarily.  In order to be actionable though, we need some concrete examples of where this is occurring in the code so we can prioritize and evaluate the changes.  Pull requests are always welcome as well :)

In some cases, modifying things should be relatively straightforward but in other cases it might be a bit trickier.

Also, keep in mind that there _may_ already be users already handling that default content, so we would need to communicate any changes here fairly thoroughly.

**Comment by nerrad** [comment]
I think I should clarify my statement:
> In order to be actionable though, we need some concrete examples of where this is occurring in the code

By that I mean the actual method/line whatever for proposed changes.

The goal here is to have some things to discuss on:

a. Is that a change we want to make for that particular example
b. How do we address that.

Let's use the messages message reference for an example.  I _think_ what the author of the post is referring to is found in `EE_Message.class.php` around line 874 in the `set_messenger_is_executing` method:

```
$this->set_error_message(
            esc_html__(
                'A message with this status indicates that there was a problem that occurred while the message was being
                processed by the messenger.  It is still possible that the message was sent successfully, but at some
                point during the processing there was a failure.  This usually is indicative of a timeout issue with PHP 
                or memory limits being reached.  If you see this repeatedly you may want to consider upgrading the memory 
                available to PHP on your server.',
                'event_espresso'
            )
        );
```

a. I don't think this should be changed because it provides context for later review of messages that failed being executed.
b. Based on ^^ I don't think this particular message needs modified in behaviour.

**Comment by tn3rb** [comment]
we could certainly remove any string defaults that are set directly in the table declarations or models themselves, and move the default to the model object getters instead.

**Comment by mnelson4** [comment]
Thank you @chaserau for the feedback! Regardless of if we do anything immediately, your vote about priorities is helpful.

> a. I don't think this should be changed because it provides context for later review of messages that failed being executed.

@nerrad I think we could, however, store a shorter string in the DB, eg maybe an error code, and based on that code, generate this longer error message during the request to view the message's error.

However, I think that will be a fairly significant refactor, right? Also, like you said, purging old messages is easy. So I don't think changing this string is very high priority.

> we could certainly remove any string defaults that are set directly in the table declarations or models themselves, and move the default to the model object getters instead.

So when getting the attendee's full bio, if it's blank, instead return "No biography provided", right?

That would reduce storage in the DB a little, although other code accessing it (eg `WP_Post`s and direct DB accessing) will now see an empty string.

Although in the case of "No Biography provided", I don't think that string is so long that it will impact database size significantly, so IMO it's rather low priority to remove that. 

So I don't think we should adjust either that message's error text or the attendee's default bio right now. But I think it's good feedback and good to avoid storing unnecessary, long, strings directly in the database.

So helpful feedback, but nothing actionable IMO, so I think this can be closed.

**Comment by tn3rb** [comment]
> I think we could, however, store a shorter string in the DB, eg maybe an error code, and based on that code, generate this longer error message during the request to view the message's error.

I think that's a great idea

> That would reduce storage in the DB a little, although other code accessing it (eg WP_Posts and direct DB accessing) will now see an empty string.

right, but I think it's obvious that a blank description for an attendee means that no bio was provided, and there is likely only one place in the UI that we really want to be displaying that notice. It's likely that that could be removed from the table creation script (or default model data or wherever that is set) without having any negative impact on things, but would benefit big sites as well as ES.

> helpful feedback, but nothing actionable IMO, so I think this can be closed.

I disagree about there being nothing actionable, but it would likely be so low a priority that it would only get touched if we refactor those systems, so may as well be closed.

**Comment by joshfeck** [comment]
We'll close this. If anyone reading this wants to open a PR for anything actionable we can go from there.
