### ISSUE TITLE
"Get in line" to avoid overselling, possibly using middleware, command bus, or helper methods

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/event-espresso-core#818]
## Issue Overview

We want to avoid overselling at events. On https://github.com/eventespresso/event-espresso-core/issues/306#issuecomment-446440024 I suggeted one way would be to somehow limit so only one request can be in certain critical code blocks at a time, in order to prevent concurrent requests from interfering with each other and resulting in overselling.
On that ticket, we're going to focus on Brent's original idea which is complementary to the one I suggested.
There are 3 main possibly approaches to this:
- **middleware** so certain requests aren't allowed to happen concurrently (eg, only one ticket selector or one SPCO finalize step request at a time; this could cause the biggest bottleneck but is kinda elegant in design)
- **command bus** so certain commands aren't allowed to happen concurrently (eg only one "approve registration" command at a time; IMO this would be the most elegant design but probably biggest refactor)
- **helper methods** which can be called anywhere. We'd probably call them just before and after doing any code that reads/writes to the tickets and datetimes' reserved and sold counts. (This would probably be the easiest and fastest but least elegant; highest likelihood of forgetting to call these helper methods in spots that would benefit from them.)

It would be great if we could come up with a way to test this well. Otherwise we're kinda in the dark about how well we've actually avoided overselling.

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Steps to Reproduce (for bugs)

It's hard, especially when I believe most webservers are setup to NOT handle concurrent requests. But basically, have two requests come in simultaneously to reserve a ticket when there's actually only space for 1. 

## Expected Behaviour

The request that arrives a millisecond late should be told the ticket isn't available.

## Current Behaviour

The event will get oversold.

## Related Information:

There is a related middleware proposed here: https://github.com/eventespresso/event-espresso-core/issues/344

Brent suggested they might correlate with this (possible) middleware in the following way:
> I think the two middleware (MW) would work like this:

>-  Rate Limiting MW would control # of registrations in progress based on value set in admin (let's say 10)

>- M-Mode MW would activate, but check # of registrations in progress (let's say 3) and then save current value for Rate Limiting MW reg in progress (10), then change that to match current regs in progress (3) so that Rate Limiting MW blocks any new registration requests from starting

>- then as registrations complete, M-Mode MW decrements the regs in progress allowed (2, then 1) which continually prevents new registrations from starting

>- eventually M-Mode MW sets that value to 0 and fully activates M-Mode

>- when M-Mode is complete (db update, whatever) then M-Mode MW resets value of regs in progress allowed back to original value (10)

**Comment by mnelson4** [comment]
Josh also pointed out that there may be multiple events being sold at the same time. So either "the line" would need to move really fast (ie, the code block that prohibits concurrency would need to be as fast as possible) or we'd need different lines for each ticket/datetime (although this could get complex with MER)

**Comment by nerrad** [comment]
@tn3rb 's proposal sounds very similar to the concept of a `mutex` and I think it would work well here.  However, I would suggest that this be something that is opt-in for a site as it could degrade the flow for very low traffic sites.  I would envision this being something that is enabled at the event level for event managers who know they have potential for high traffic sell-out conditions for an event.

One of the best explanations of the `mutex` term I found here: https://stackoverflow.com/a/34558/439720

**Comment by nerrad** [comment]
Also, I think ideally, implementation of some sort of gating (or mutex) concept will require using either ajax or REST API for the flow.  That way there'd be a response that the javascript could react to appropriately for whether the current visit has access to register (and show the appropriate "in queue" message etc).

**Comment by tn3rb** [comment]
setting effort estimate at 10 because there are some options for this that are not too too complex, but depending on what path is chosen, this could require more effort, but that would be better to create additional issues and set their effort estimates separately
