### ISSUE TITLE
Attempting to pay for a registration on an expired event changes the reg status to waitlist

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#826]
**Describe the bug**
Currently, we don't allow users to pay for registrations on an expired event, however, if you try to open a payment link for such an event, the registration will switch to waitlist and the transaction show as complete (because you no longer have a price assigned to you ticket).

Note, you don't need the waitlist add-on active for this to happen.

**To Reproduce**
Either open up a receipt for an old pending payment registration on an expire event, then view the registration/transaction.

Or add a pending payment registration and then set the datetimes for an event to the past so its expired, then open up a payment link for the event.

**Expected behavior**
At least leave the registration as is, I'd like to say all payments on expired events, but thats a marmite option (you'll love it hate it) so likely needs some planning.

**Comment by sethshoultes** [comment]
@tn3rb what are your thoughts on this?

**Comment by tn3rb** [comment]
will have to investigate in the code itself, because there **IS** logic for handling expired events, but it may be operating after the logic that is switching the registrations to RWL. So might just be an "order of operations" issue. Won't know for sure until I dig into the code.

**Comment by joshfeck** [comment]
This might be a duplicate of #336

**Comment by tn3rb** [comment]
@joshfeck 

I don't think this is a duplicate of #336 which pertains to allowing expired tickets to be sold, whereas this issue involves expired events

**Comment by tn3rb** [comment]
setting complexity estimate to 1 for the time being but won't know for sure until this is investigated
