### ISSUE TITLE
Implement shims for wp_doing_ajax() and wp_doing_cron() and use everywhere

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#830]
Originally reported in https://events.codebasehq.com/projects/event-espresso/tickets/11055
where @nerrad originally wrote:

> See https://events.codebasehq.com/projects/event-espresso/repositories/32-core/commit/50177d2042fcd5393285120983027a21e3f96c1f#diff-5c0911 where I introduced this idea.
> 
> - `wp_doing_ajax` was introduced in WordPress as a part of WP version 4.7
> - `wp_doing_cron` was introduced in WordPress as a part of WP version 4.8
> 
> Since EE currently supports back to WP 4.1 of WordPress, if we want to use the above methods we'd have to create shims for versions that don't use them.
> 
> Where I mentioned this in the above commit note, Brent asked me to link to any documentation.  There may be some, but I don't know of any offhand.  It's easy enough to use your IDE to find these functions within WP core code though and you can use that as the base for any shims if the function doesn't exist.

Then @tn3rb followed up with:

> Ideally, these would be implemented early in the request to determine the request type, which would get recorded on the EE_Request object.
> This could then be used to coordinate what resources and/or systems get loaded as the request progresses. For example, currently, we really only change what gets loaded based on whether the current request is a request for the admin or the frontend, but there is a lot more we could do to streamline things, and get away from the WordPress "LOAD IT ALL" approach.

**Comment by joshfeck** [comment]
The source for wp_doing_ajax() is:
```
function wp_doing_ajax() {
    /**
     * Filters whether the current request is a WordPress Ajax request.
     *
     * @since 4.7.0
     *
     * @param bool $wp_doing_ajax Whether the current request is a WordPress Ajax request.
     */
    return apply_filters( 'wp_doing_ajax', defined( 'DOING_AJAX' ) && DOING_AJAX );
}
```
`wp_doing_cron()` does the same.

The functions are more concise code and they each add a filter hook. I wonder though if it's worth making shims and refactoring all usage of `defined( 'DOING_AJAX' ) && DOING_AJAX );` and the similar doing cron check to use said shims. 

Also, we're heading on a path where at some point EE4 will require WP 5 with the move to more client side UI features. With these points in mind I'm inclined to close this. After EE4 requires WP 5 we can just start using wp_doing_ajax() and wp_doing_cron() without shims. By not adding shims we'll also avoid fewer things to deprecate in the future. 

Is there anything I'm missing here or any reason why we should do this anyway?

**Comment by nerrad** [comment]
Imo it really depends on "when" we plan on requiring WP 4.7+ (which is when these two functions were added) or WP 5.0+.  If that's not going to happen for another year or two, then I think adding the shims will cut down on code throughout our codebase (plus expose the ability to use filters to change behaviour for automated testing etc).

So if you see us updating min required version of EE core within 3-6 months then ya let's kibosh this ticket.   However if you don't see that happening for at least another year or two then I think it's worthwhile keeping this alive.  It'd be really trivial to implement (add the shims and search/replace).  So effort would be a 1 on this.

**Comment by nerrad** [comment]
Actually after re-reading the comment you quoted from @tn3rb, he's already implemented that in the new `Request` (and related `RequestTypeContextChecker` class in EE (added sometime last year or the year before maybe even).  So that reduces the need for shims now.
