### ISSUE TITLE
Multiple states can appear for the United States under certain conditions

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/event-espresso-core#832]
**Seen on a recent version of Event Espresso**

**Summary**
I was testing this issue (https://github.com/eventespresso/event-espresso-core/issues/734) on Event Smart staging and noticed that the site had duplicate entries for the states for the United States afterward.

I ran additional testing on different websites and was able to reproduce the issue on a new site and an old site.

**Steps to reproduce**
Go through the steps here: https://github.com/eventespresso/event-espresso-core/issues/734

**Reported or seen on**
- https://lorenzoinvisible.makeeventsnotwar.com/wp-admin/admin.php?page=espresso_general_settings
- https://lorenzowp313.makeeventsnotwar.com/wp-admin/admin.php?page=espresso_general_settings

**Other notes**
Kristin was able to verify this issue and there are more affected sites here: https://github.com/eventespresso/eventsmart.com-website/issues/341#issuecomment-448367177

**Comment by sethshoultes** [comment]
@tn3rb can you please look into this?
