### ISSUE TITLE
Implement e2e (end to end) tests for EE core.

### ISSUE THREAD

**Issue by nerrad** [eventespresso/event-espresso-core#833]
The GB project has an end to tests that [are maturing](https://github.com/eventespresso/event-espresso-core/issues/794) which could be used as a template (somewhat) for incorporating our own e2e tests for GB related things (and really we can expand for implementing e2e tests for all our things).

While we do have codeception tests, they haven't really gotten any momentum from our team in writing tests and part of that is probably due to the difficulty in getting it setup :(.  I've found them valuable in catching some bugs that otherwise would have gotten released but they only retain that value when there's actual coverage.

As we move towards a more javascript heavy interface, and with the more rapid changes in the WP development world, I think it's becoming more crucial that we have some end to end tests in our automated set of tools.

**Comment by nerrad** [comment]
On thing I like about using the GB e2e tests as a model is that they are incorporating tests for catching accessibility related things as well.  I think it's important we incorporate some accessibility specific tests in things we do as well.

**Comment by tn3rb** [comment]
closed in favour of https://github.com/eventespresso/barista/issues/689
