### ISSUE TITLE
Plugin deactivation form hangs

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/event-espresso-core#837]
## Issue Overview

When you deactivate EE, it asks if you'd like to give the reason for deactivating. If you answer the question, the plugin doesn't get deactivated and you can't proceed with plugin deactivation.
This feature was added a little while ago, but I wasn't involved in it.

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Environment Data:

Version of EE: 4.9.75

Version of WordPress: 5.0.1

PHP Version:  5.6 and 7.1

Browser used:  Firefox, Google Chrome

## Steps to Reproduce (for bugs)

Activate EE decaf or EE caff, then go to deactivate it. Click "Sure, I'll help". Choose any option.

## Expected Behaviour

The pop-up should disappear, and the plugin should get deactivate3d.

## Current Behaviour

The pop-up stays, and nothing else happens. You can't close the pop-up either. You need to refresh the page.

## Related Information:

Here's a video: https://drive.google.com/file/d/18OB5cBNbPMICF_DRiGNqATsxfKOVObBR/view

**Comment by nerrad** [comment]
The pipeline should be changed on this if it's needed for me to work on right away.  New issues pipeline is something I generally ignore (cc @sethshoultes)
