### ISSUE TITLE
Remove link to view transactions if user does not have the `read_transaction`-related caps

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#846]
Originally reported in https://events.codebasehq.com/projects/event-espresso/tickets/11352

> If the ee_read_transaction and ee_read_transactions capabilities are not set for a user account/role, the following text appears, with links, when viewing a single registration:
> 
> View Registrations / Transactions for this event
> 
> We actually expect the link text "Transactions" to not be displayed if the user doesn't have ee_read_transactions capabilities.

These links are in reg_admin_details_header.template.php. In order to prevent breaking translation strings, and keep strings translatable, I think what we should do is add a conditional so if the user has the `read_transactions` caps, they'll see both links. Then if they don't, show a different string that only includes the link for viewing registrations.

**Comment by tn3rb** [comment]
PLZ SEE: #847
