### ISSUE TITLE
Don't Store Session Data in Transients

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#853]
This has been an ongoing issue where the "Nothing in Your Event Queue" error will randomly happen on sites hosted on GoDaddy Managed hosting, Pantheon, and WordPress.com Business hosting (formerly Pressable).

Also, this prior to the launch of Eventsmart:
https://events.codebasehq.com/projects/saas/tickets/427
tldr; we had to disable object-caching on Eventsmart due to similar issues.

**Comment by joshfeck** [comment]
related p2: http://p2.eventespresso.com/2019/01/02/moving-away-from-depending-on-session-transients/

**Comment by sethshoultes** [comment]
Is this something that we should consider implementing before the REM add-on?

**Comment by joshfeck** [comment]
@sethshoultes how about we discuss time frames in the P2?

**Comment by joshfeck** [comment]
This was also an issue on Dreamhost

https://eventespresso.com/topic/no-tickets-can-be-purchased/
