### ISSUE TITLE
EE_Register_Payment_Method::deregister() needs to call EE_Payment_Method::deactivate() to clear 'PMD_scope' field in db or else error occurs on next request

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#862]
Originally reported in [codebase 11110](https://events.codebasehq.com/projects/event-espresso/tickets/11110) and again in [11322](https://events.codebasehq.com/projects/event-espresso/tickets/11322)

@tn3rb reported:

> In https://events.codebasehq.com/projects/event-espresso/tickets/10202#update-46248919, @sethshoultes discovered that deactivating a Payment Method addon and then refreshing the EE Payment Methods admin page resulted in an error message getting dumped out in the footer. This was a result of both a bug in the new code in 10202 as well as the bug explained pretty succinctly in the title of this ticket. Basically what happens is that the Payment Methods admin page pulls a list of available PMs from the db and then checks each one to verify it still exists (is activated). Any PM that is not activated but still recorded as being active produces an error. A PM's active/inactive state is persisted using the `PMD_scope` field in the `esp_payment_method` db table. `EE_Register_Payment_Method::deregister()` should be clearing this value, but is currently not. This can easily be done by calling `EE_Payment_Method::deactivate()`.
[
Further discussion follows in that ticket](https://events.codebasehq.com/projects/event-espresso/tickets/11110#update-46443982), and please also see Mike's comments in [11322](https://events.codebasehq.com/projects/event-espresso/tickets/11322).

**Comment by mnelson4** [comment]
I think this got fixed sometime, as I'm not reproducing it.

Here's what I tried:
* I activated Mollie add-on
* I activated Mollie payment method
* in another tab, I deactivated the Mollie add-on
* I refreshed the payment methods page and there was no error in the footer

@sethshoultes are you still able to reproduce this issue?
