### ISSUE TITLE
Add a filter to allow the complete removal of the maximum tickets purchased footnote

### ISSUE THREAD

**Issue by richardtape** [eventespresso/event-espresso-core#87]
https://github.com/eventespresso/event-espresso-core/pull/86 Adds a filter to be able to completely remove the footnote.

If you simply return an empty string to the existing filter, you get a paragraph tag with just a '*' character. This is unnecessary. It's possible to hide this via CSS, but having a filter to show or hide this footnote is cleaner.

**Comment by tn3rb** [comment]
a version of this has been merged to master
