### ISSUE TITLE
Attendee 1 form is missing, on ee4 sandbox, when multi-attendee registration 

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#873]
**Describe the bug**

Attendee 1 form is missing when "Personal Information" Group is required for additional attendees & multiple tickets are registered for. 

**To Reproduce**

1. Go to https://ee4m.eventespresso.com/happenings/2019-event/ **or** set up an event that requires the Personal Information Group for Additional Attendees
2. Select 2 or more tickets, and submit TS form
3. You'll be redirected to SPCO step 1
4. See missing attendee 1 form

**Expected behavior**

Attendee 1 form included
**Screenshots**

![screen shot 2019-01-02 at 6 09 54 pm](https://user-images.githubusercontent.com/891156/50620065-4b8a1000-0ecb-11e9-8230-fce0eed50c47.png)

**Environment:**
 - Version of Event Espresso: current master
 - Version of WordPress: 5.0
 - Browser: Firefox, Chrome
 - PHP Version 7.1.25

**Additional context**

**Not** an issue on this other site, also running EE4 master:
https://josh.eventespresso.com/events/wordpress-5/

**Comment by joshfeck** [comment]
Update: This is only an issue on master, not in the release (4.9.75.p)

**Comment by tn3rb** [comment]
`4.9.76.rc.006` appears to still be good, but issue starts in `4.9.76.rc.007`

**Comment by mnelson4** [comment]
caused by https://github.com/eventespresso/event-espresso-core/pull/798/files#diff-7ec6cba948e6194ffe136de7715e376bR186

**Comment by joshfeck** [comment]
I guess #875 wasn't properly linked to this issue so it did not auto-close.
