### ISSUE TITLE
Remove/Increase ESPRESSO_EVENT_ATTENDEES shortcode limit

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#879]
**Describe the bug**
Looks like in #331 a limit of 10 was accidentally introduced on the ESPRESSO_EVENT_ATTENDEES shortcode:

https://github.com/eventespresso/event-espresso-core/blob/master/core/domain/entities/shortcodes/EspressoEventAttendees.php#L162

**To Reproduce**
Just add `[ESPRESSO_EVENT_ATTENDEES]` to an event description on an event with more than 10 attendees

**Expected behavior**
We need to load a higher number of attendees than 10, default of 200 maybe? It needs to be high enough to cater for most users.

**Comment by sethshoultes** [comment]
@Pebblo can that value be overridden using shortcode parameters?

**Comment by Pebblo** [comment]
Yes, it can by adding `limit=200`

But we've gone from no limit to 10, and that's a significant difference. If you've been using that shortcode to display your attendee you now only display 10 until you edit the shortcodes.

It's also possible to override the value with a filter:

https://gist.github.com/Pebblo/ed0af384f64095609855f18995083e38

However I still think the default limit is top low to be useable for the majority of users.

**Comment by joshfeck** [comment]
@nerrad would the fix be limited to removing the `limit` item from the array returned by `getAttributes()`? There wasn't a limit set there before. If a limit is needed there, would it be OK to set that to a higher limit than 10?

**Comment by nerrad** [comment]
For the shortcode, I think we should restore it to whatever it was before the change in terms of limit.  The block doesn't use shortcode rendering anymore (it does its own render) so we don't have to worry about side effects there.  If there were no issues with the previous limit (or lack of limit) then we can go back to what it was. I imagine this is kind of important to for back-compat reasons.
