### ISSUE TITLE
Question: Are there any filters on registration form inputs?

### ISSUE THREAD

**Issue by richardtape** [eventespresso/event-espresso-core#88]
I've been looking through the way in which EE generates the markup for the questions used on the registration form. We have custom questions, but let's use the native 'Personal Information' inputs for this example.

Our users have an account on the WordPress install where EE is installed. On user registration we ask them to fill in a few details (it's required), so we have their name and email address stored as user meta.

I can't seem to find the way in which the actual form inputs are output. I've found the place where the actual reg. form itself is output 

`$reg_form = EE_Template_Layout::get_subform_name( $registration->reg_url_link() ); echo ${$reg_form};`

But I can't seem to work up the tree to find out exactly how each input for each question is generated and to see if there any filters.

If there aren't any, I'll happily go ahead and create a PR adding them, if someone could show me where...

Any pointers?

**Comment by richardtape** [comment]
I may be starting to answer my own question. Just discovered the `FHEE__EEM_Answer__get_attendee_question_answer_value__answer_value` filter in `includes/models/EEM_Answer.model.php` which may be exactly what I need.

**Comment by tn3rb** [comment]
It's not exactly clear what it is that you are asking or looking for in your first comment...
you say you are looking for where the form inputs are output... 
then say you can add some filters... 
filters for what exactly?

If you just want to grab a copy of the incoming attendee registration information, then I *think* you may want to look at where the attendee information is processed, which is in :
\EE_SPCO_Reg_Step_Attendee_Information::_process_registrations()

but to go out on a limb, I think you might be wanting to tie your registrations to your WP user accounts, in which case, you should seriously look at our WP User addon which does just that and more:
http://eventespresso.com/product/eea-wp-user-integration/

**Comment by richardtape** [comment]
It's the `value` property of the inputs I was after a filter. The filter I discovered does what I need. You're right, my question was vague, apologies.

The add-on you linked looks awesome. It currently only does the basic user info, we need a few other bits and pieces so the filter is invaluable.

**Comment by tn3rb** [comment]
Do you want to get the all of the values for each of the registration form inputs upon submission?
 
Because if so, then I don't think that filter will do what you want, as I believe that is employed more so when you are populating a form with existing attendee info. It is really only called from \EE_SPCO_Reg_Step_Attendee_Information::reg_form_question() which is part of the form generation, not the submitted form processing.

The "FHEE__EE_Single_Page_Checkout__process_attendee_information__valid_data_line_item" filter will give you access to ALL of the submitted data for each registration in one shot, or if you want to process each input individually, then you could use the "FHEE__EE_SPCO_Reg_Step_Attendee_Information___save_registration_form_input" filter, which also allows you to bypass the normal processing if you want to do your own processing of the form input ( be careful with that though :D )

**Comment by richardtape** [comment]
It's cool, the filter I mentioned does what I need. To pre-fill the value of the input before the user submits based on user meta stored. i.e. if we have their First and Last name stored as user meta, I want to pre-fill that information into the relevant inputs on the registration page for them, but still allow them to change it should they wish.

The filters you mention look super useful for something else we need, though. Thank you!

**Comment by nerrad** [comment]
The filter you are using for pre-populating based on user meta for logged in user is exactly what we use for the WP User Integration addon :)

**Comment by tn3rb** [comment]
oh as well... re:

"The add-on you linked looks awesome. It currently only does the basic user info, "

are you basing that on the form inputs shown in the screenshots on the addon sales page?

those examples are merely using the Personal Information question group question only, it can link more data than that, and I'm sure you would find it less work to extend that addon than to reinvent the wheel.

What are your plans if someone attempts to register without having logged in first ? Or is your reg form behind the login?

**Comment by richardtape** [comment]
I'm basing that on the following note in a yellow box

>"At this time, only the First Name, Last Name, and Email Address are pulled from the WordPress profile to the registration form for logged in users."

Is that not the case for custom user meta and custom registration questions with that add-on?

The reg form is behind a login (it's mandated in our case)

**Comment by tn3rb** [comment]
my apologies, you're right.

If you are already behind the login, then you should be fine.

**Comment by richardtape** [comment]
:+1: thanks both, really appreciate your input.
