### ISSUE TITLE
Question: Why does the SPCO clear (or not have access to) the current user object when processing a registration

### ISSUE THREAD

**Issue by richardtape** [eventespresso/event-espresso-core#89]
Hey folks,

I can't quite work out where this is happening (and hence don't know if it's a bug or by design) but, if I hook into  `FHEE__EE_SPCO_Reg_Step_Attendee_Information___process_registrations__pre_registration_process` and do one of the following;

`$user_id = get_current_user_id(); var_dump( $user_id );`

or

`global $current_user; var_dump( $current_user );`

I get back nothing or an empty object as appropriate.

(I'm definitely signed in ;) )

I've tracked it down to somewhere during the AJAX request when a user clicks on 'Proceed to Finalize Registration' on the Event Registration page. When that page first loads (i.e. it just loads the form for people to fill in their details), I *do* have access to the user ID i.e. that's in `EED_Single_Page_Checkout::_handle_json_response()` however, as soon as the ajax request begins, (i.e. the conditional at the top of that method passes), I no longer have access the to the User ID.

Any suggestions?

**Comment by nerrad** [comment]
not sure what's happening in your case.  I use the same filter in our WP User Integration addon and get_current_user_id() is working fine for me.  Doublecheck the filter setup and try var_dumping ANYTHING to see if the callback is even getting called.

**Comment by richardtape** [comment]
Thanks @nerrad  The callback is definitely being called (I'm adding to a log to see what's happening)

The user ID is available when the form is displayed. However, when the AJAX submission happens, the user ID is not available. (I wonder if that's an internal WP thing, because the AJAX process itself isn't attached to a user...?)

Are you saying that when you make the ajax submission that you can still access the user ID?

**Comment by nerrad** [comment]
Yes the WP User Integration uses the same filter as what you are using and the callback has access to current_user_id().

In WordPress, ajax requests run in the context of the current_user.

**Comment by nerrad** [comment]
Here's a snippet from the callback in the WP User Integration addon:

```
if ( is_user_logged_in() ) {
								$current_user = get_userdata( get_current_user_id() );
								if ( $current_user->user_email == $user->user_email ) {
									continue;
								} else {
									$error_message = '<p>' . __('You have entered an email address that matches an existing user account in our system.  You can only submit registrations for your own account or for a person that does not exist in the system.  Please use a different email address.', 'event_espresso' ) . '</p>';
									$stop_processing = TRUE;
									$field_input_error[] = 'ee_reg_qstn-' . $registration->ID() . '-email';
								}
							}
```

**Comment by richardtape** [comment]
Super, super weird.

I'm running WP 4.2.2, multisite, EE Version 4.6.32.rc.001, no other plugins other than the one I'm developing, which I've just reduced to just adding a callback to that filter thus;

```add_filter( 'FHEE__EE_SPCO_Reg_Step_Attendee_Information___process_registrations__pre_registration_process', array( $this, 'FHEE__EE_SPCO_Reg_Step_Attendee_Information___process_registrations__pre_registration_process__add_extra_user_meta_on_registration' ), 10, 6 );```

```
public function FHEE__EE_SPCO_Reg_Step_Attendee_Information___process_registrations__pre_registration_process__add_extra_user_meta_on_registration( $process_reg, $att_nmbr, $registration, $registrations, $valid_data, $attendee_object ) {
		$user_id = get_current_user_id();
		file_put_contents( WP_CONTENT_DIR . "/debug.log", print_r( array( $user_id ), true ), FILE_APPEND );
		return $process_reg;
}
```

And I'm just getting 

```
Array
(
    [0] => 0
)
```
In my log file (I should be seeing '1' as the value)

I'm stumped.

**Comment by richardtape** [comment]
I've worked out a way around the problem (which, frankly, is disgusting, but it'll do for now) but I'd be interesting to work out why this is happening as this work-around could do with going away as fast as possible ;)

**Comment by tn3rb** [comment]
you have my curiosity peaked...

what's this disgusting work around?

**Comment by richardtape** [comment]
hah.

1. Hook into `AHEE__before_spco_whats_next_buttons` to add a hidden form field with a hashed version of the User ID. (The form only displays if a user is signed in anyway)
2. Hook into `wp_ajax_process_reg_step` to get the `$_POST` of that hidden form field, dehash it, sanitize it and set it to a class property.
3. Fetch that property in `FHEE__EE_SPCO_Reg_Step_Attendee_Information___process_registrations__pre_registration_process` and verify there's a user ID with that and then process the user meta as necessary

:mask:

**Comment by tn3rb** [comment]
oh and for the record:

```
function add_extra_user_meta_on_registration( $process_reg, $att_nmbr, $registration, $registrations, $valid_data, $attendee_object ) {
	$user_id = get_current_user_id();
	var_dump( $user_id );
}

add_filter( 'FHEE__EE_SPCO_Reg_Step_Attendee_Information___process_registrations__pre_registration_process', 'add_extra_user_meta_on_registration', 10, 6 );
```
worked for me

**Comment by nerrad** [comment]
Richard, by any chance do you have any object-caching setup on the server you are testing things on (fringe thing maybe but worth a check)

**Comment by tn3rb** [comment]
have you checked what other plugins you have active ?

**Comment by richardtape** [comment]
No object caching. No other plugins active (including mu-plugins). Default theme.

**Comment by nerrad** [comment]
yeah a puzzler, sorry we can't be more help but no reason get_current_user_id() shouldn't be available.  Is it possible elsewhere in the plugin you are developing that the global $current_user got reset?

**Comment by tn3rb** [comment]
are you using Firebug or something similar?
what URL are the AJAX requests going to?

**Comment by richardtape** [comment]
I reduced the plugin down to just the filter and callback.

Weird one. I'll have to live with this work around for now (deadlines, deadlines) but I *will* revisit this and get back to you. Feel free to close this thing though and I'll just report my findings in the future.

**Comment by nerrad** [comment]
fwiw IF there was a problem with the this filter we'd be hearing from a lot of our users using our WP User Integration add-on :)

**Comment by richardtape** [comment]
The AJAX requests go to the correct admin URL. I've inspected the actual AJAX requests themselves and everything looks hunkydory.

Yeah I'm entirely certain it isn't a problem with ee now after you guys have said you use the same filter elsewhere.

Thanks so much for your help, really appreciate it.

**Comment by nerrad** [comment]
well I'm knocking wood, hope we don't all of a sudden get a bunch of reports from our users ;)
