### ISSUE TITLE
Fix events not showing related date-times  in the trash view for the event list table

### ISSUE THREAD

**Issue by nerrad** [eventespresso/event-espresso-core#890]
**Describe the bug**

I expect when viewing trashed events in the Event List table to see data in the Event Start column.  That is not happening.

**To Reproduce**

- Trash an event that has datetimes
- Click to view the `trash` route for the event list table.

**Screenshots**

![trash view of event list table with no dates](https://www.evernote.com/l/AAMvgQoV9TFARoJAj3uJagBEe7-7R7h120cB/image.png)

**Environment:**
 - Version of Event Espresso:   4.9.76
 - Version of WordPress:  5.0.3
 - Browser  Chrome
 - PHP Version 7.3

**Additional context**

I suspect this is caused by the default where conditions when getting related datetimes to the event.  Datetimes are getting excluded from the results of the query because the event is trashed.

**Comment by joshfeck** [comment]
Is this a quick fix?

**Comment by mnelson4** [comment]
Ya I could take a look at it. I will be surprised if it’s not a model-related issue. If it’s more than an hour I’d assign for re-triage.

**Comment by tn3rb** [comment]
setting effort estimate at 1, although this has the potential to be more complex
