### ISSUE TITLE
Session/Cart cleared before getting to event registration page

### ISSUE THREAD

**Issue by richardtape** [eventespresso/event-espresso-core#91]
Hey folks, this is a bit of a strange one, and I'm fairly sure it's platform specific, but I was hoping you may be able to help shed some light.

We're using the Single Page Checkout - all events are free. So the process is a user sees an event, clicks to view details, then clicks 'Register Now' as there's only ever one ticket type, they're always 0-priced. They're taken to the 'event-registration' page which is where they fill in their details.

Locally, this works great. However, when we put it on our staging environment the process breaks down. When a user clicks 'Register Now' they are taken to the event registration page, but they see a message 

>Nothing in your Event Queue.

I've looked through the EE source and found that's what happens when the cart is empty in `modules/single_page_checkout/templates/registration_page_wrapper.template.php` line 19. `$empty_cart` is a template_arg passed in from `_display_spco_reg_form()` and it's because `$this->checkout->transaction->registrations( $this->checkout->reg_cache_where_params )` returns an empty array.

I've been trying to follow the stack to see exactly where things are going awry and added an output on the `AHEE_log` action. I *think* it's something to do with how the session is passed around. If I do

```
add_action( 'AHEE_log', 'eedebug_test_log_output', 10, 3 );
function eedebug_test_log_output( $file, $function, $string ) {

	if ( $function !== '_save_session_to_db' ) {
		return;
	}

	file_put_contents( WP_CONTENT_DIR . '/debug.log', print_r( array( $file, $function, $string, $_POST, $_GET, $_REQUEST  ), true ), FILE_APPEND );

}
```

Then from that I can see that from when the person clicks the 'Register Now' button, the `_save_session_to_db` method is called 3 separate times. The first two are still on the single events page itself, and contain the $_POST vars that you would imagine from the form i.e.

```
Array
        (
            [process_ticket_selections_nonce] => f6fc2b3013
            [_wp_http_referer] => /events/edx-studio-3/
            [tkt-slctr-qty-1215] => 1-1
            [tkt-slctr-ticket-id-1215] => Array
                (
                    [0] => 542
                )

            [noheader] => true
            [tkt-slctr-return-url-1215] => /events/edx-studio-3/
            [tkt-slctr-rows-1215] => 1
            [tkt-slctr-max-atndz-1215] => 1
            [tkt-slctr-event-id] => 1215
        )
```

The third time the method is run, we're on the event-registration page and the `$_POST`, `$_GET` and `$_REQUEST` globals are all empty.

If I take a look inside the `_espresso_session()` method I can see that you're looking for an already open session and if there is one, then you're looking for a transient based on the session ID. The issue here is we use a custom authentication system called CAS which is session based. So while there *is* a session, there's no transient with that name. So the conditional at https://github.com/eventespresso/event-espresso-core/blob/master/core/EE_Session.core.php#L410 is going to fail meaning we're going to return false there on line 434.

So I'm a bit stuck as to how that would work in our case. Any suggestions?

Happy...Friday...? :)

**Comment by richardtape** [comment]
As a follow-up, if I do

`add_filter( 'FHEE_load_EE_Session', '__return_false' );`

locally, I get the same behaviour as on the staging environment - i.e. an empty cart always on the event-registration page.

**Comment by tn3rb** [comment]
we only use the PHP Session ID as an identifier for the session data which is saved to the database via the WordPress Transient API. So as long as you have PHP sessions enabled on your system that *should* work. The main point being that transients are saved in the database and not in the session.

I would be more inclined to look into whether you have any caching active on your server, and if so, take the necessary steps to exclude the Event Espresso generated /registration-checkout/ and /thank-you/ pages from being cached.

**Comment by richardtape** [comment]
I think I've just had a brain-wave.

The transients API has a max-length for the name of the transient. Our PHP session IDs are of the form

`ST-14208-KPrASc6yYqJt4mRecE33-casstgidubcca`

and so are pretty long.

If you're using that (with a prepended `ee_ssn_` too) then I'm 99% certain that it's too long for `set_transient` and it's barfing. I'll look into this now.

**Comment by tn3rb** [comment]
ya that would explain it
we'll create a ticket

**Comment by richardtape** [comment]
OK, yep, confirmed. That it was the length of the transient. As this is...clearly...critical for us, I'm happy to work out a PR for this.

Maybe wrap a filter around the transient name? Would that sound sensible? Perhaps I could create a method which returns the transient name which is then used in `set_` and `get_transient` which returns a filtered value.

Thoughts?

**Comment by tn3rb** [comment]
I'm working on a fix right now
will post a branch as soon as I push

**Comment by richardtape** [comment]
(for my testing purposes, I actually just wrapped `$this->_sid` in an `md5()` call as I know that it'll always has a length of 32 characters, then with the prepended 'ee_ssn_' it'll never be more than 42 chars which is under the limit of 45 chars. I'm not suggesting that's the way forward by the way, just wanted to let you know how I tested)

**Comment by richardtape** [comment]
Oh and also, if it's decent to have some background:

https://core.trac.wordpress.org/ticket/13310

**Comment by nerrad** [comment]
I've been watching that ticket for a long time richard :) You'll even see a post from me in it.  Interestingly enough, right before you mentioned the transient issue, Brent and I were talking about it being a possible cause for your issue :)  Thanks for working with us on this!

**Comment by richardtape** [comment]
:+1:  My pleasure. Thanks for all your help as always :)

**Comment by tn3rb** [comment]
@richardtape 

plz have a look at https://github.com/eventespresso/event-espresso-core/tree/BUG-8426-session-id
for the fix for this issue

**Comment by richardtape** [comment]
I love open source software. Thanks so much for doing this.

So, if I understand this correctly, you have a filter in the `_generate_session_id()` method https://github.com/eventespresso/event-espresso-core/blob/BUG-8426-session-id/core/EE_Session.core.php#L500 which is used to set the class property, and then that is used (with a new class constant) to form the name for the transient.

So, theoretically, all I'd need to do is apply a callback to that new filter which returns a string guaranteed to be less than 38 characters and that way the transient name will always be <45 chars.

Does that sound like I'm reading it properly?

**Comment by richardtape** [comment]
Actually, you already `md5()` it so it should be fine by default. Awesome. :)

**Comment by tn3rb** [comment]
ya I had to leave the session id prefix outside of the filter because we use that for garbage collection. If I had allowed the full session transient key to be filtered, then the current garbage collection would not work. 
So it will be up to the dev to ensure that whatever they return for the filtered session id is not ultimately truncated when used as the transient key.

plz let us know if this fixes things for you.

**Comment by richardtape** [comment]
I absolutely will. Will probably be early next week. But I'm 99.9% certain this fix will work as it's very similar to what I did in my tests.

**Comment by joshfeck** [comment]
Update: BUG-8426-session-id was merged to Master branch and deleted.

**Comment by richardtape** [comment]
:+1: Amazing. Thanks so much.
