### ISSUE TITLE
Datetime Selector Planning 

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#92]
These are the options that were outlined in our P2. They are for planning the next templates we build that will focus on datetime selection. 

<blockquote>

<h2>Datetime Selector</h2>
Almost the same as what we have now, except the inclusion of a dropdown at the top of the Ticket Selector. The rest of the Ticket Selector is initially blank. The dropdown is filled with the Datetime options for that event. Selecting an option from the datetime dropdown populates the rest of the Ticket Selector table, just like we have now, but you would **only** see ticket options that are for the selected datetime.

<b>Pros:</b>
<ul>
<li>Less clicks to select tickets ( datetime, then qty )</li>
<li>More information available at one time</li>
</ul>

<b>Cons:</b>
<ul>
<li>Uses more screen real estate</li>
<li>Still possibly too much information</li>
</ul>

<h2>Cascading Datetime Selector</h2>
You have a table with 3 columns:

[ Datetime ][ Ticket ][ Quantity ]

Selecting an option from the first dropdown for the datetime, would then populate the next dropdown with the ticket options for that date, and selecting an option from this dropdown populates the quantity selector based on the availability of that ticket option.

<b>Pros:</b>
<ul>
<li>Uses far less screen real estate</li>
<li>Possibly less confusing for user since options are broken down into smaller chunks</li>
</ul>

<b>Cons:</b>
<ul>
<li>Requires way more clicking</li>
<li>Hard to compare ticket information from multiple datetimes</li>
</ul>

<h2>Cascading Date & Time Selectors</h2>
Same as above, but with dedicated dropdowns for both Date and Time
You have a table with 4 columns:

[ Date ][ Time ][ Ticket ][ Quantity ]

Selecting an option from the first dropdown for the date, populates the time dropdown, which then populates the ticket option dropdown, which populates the quantity selector.

<b>Pros:</b>
<ul>
<li>Uses far less screen real estate</li>
<li>Possibly less confusing for user since options are broken down into smaller chunks</li>
</ul>

<b>Cons:</b>
<ul>
<li>Requires way more clicking, possibly too much</li>
<li>Hard to compare ticket information from multiple datetimes</li>
</ul>
</blockquote>

**Comment by vilhellem** [comment]
The datetime selector option seems most user friendly for most use cases.

**Comment by jonathan-dejong** [comment]
So while you're doing this, if you plan on using the same datetime selector as the one in the backend, will you also make sure it's localised? 

I started a thread on the localisation of the datetime picker in admin long time ago with little interest but with this is becomes even more important. For non US countries having AM/PM times aren't working out and especially if you have lots of less tech-savvy (read idiots) people handling EE in both backend and frontend.

**Comment by womp2** [comment]
Hi Josh 

How is this progressing ?

I believe the Datetime selector offers the best solution, simple/intuitive and would sit alongside other tickets without confusion.

details of my personal situation are in the following post 
https://eventespresso.com/topic/ticket-with-date-selector/

**Comment by tn3rb** [comment]
This feature was merged to master and released a little while ago.
