### ISSUE TITLE
Allow 0.00 cost registrations to have their status updated when applying payments in the admin

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#923]
For backstory, please see https://events.codebasehq.com/projects/event-espresso/tickets/9864#update-41653864 where @tn3rb explained:

> I'm sure that the code in the admin, is simply ignoring the free registrations because we are processing a payment, and that obviously doesn't apply to free registrations. But that's of course missing the point that we are also toggling the reg status at the same time.

> So all we need to do, is change whatever code is going on in the loop, so that the free registrations are still included, but only get skipped over when applying payments. Everything else, like status changes, should apply.

Steps to replicate the issue:

- [ ] set up an event that has both a paid ticket & a free ticket

- [ ] register via the admin for one of each ticket

- [ ] on the admin transaction page, apply a payment and keep the default to set reg to approved

The expected behavior is both regs get updated to approved, which is what happens on the frontend. What actually happens is the paid ticket registration gets approved but the free ticket registration stays on "Pending Payment" status.

**Comment by tn3rb** [comment]
setting complexity estimate to 1 for the time being but won't know for sure until this is investigated
