### ISSUE TITLE
Improve a11y for actions in list tables.

### ISSUE THREAD

**Issue by nerrad** [eventespresso/event-espresso-core#925]
## Issue Overview

As a part of #922, @joshfeck requested taking a look at what sort of a11y improvements we could make to the actions in list tables.  As I noted there:

* [ ]  WP removes the `title` attribute and adds `aria-label="Trash"` etc in its list tables for the actions.  This would require updating our `EE_Admin_List` parent to do the same which means _all_ our list tables will be affected (could be a good thing)?
- we're not overriding any of the css for the `.row-actions` provided by WP here so any accessiblity things.  For screen-readers the actions are actually accessible because the element is in the dom (just positioned off screen for visibility).  There's some js that makes it "visible" by changing the positioning when hovered.

We decided to break this work into its own issue/pull because it increases the scope of work and testing needed.

This will be good work to do because it will improve the accessibility of these actions.

**Comment by joshfeck** [comment]
This is still a work in progress. A lot of files need to be converted still.
