### ISSUE TITLE
Hard limit on the number of question options

### ISSUE THREAD

**Issue by richardtape** [eventespresso/event-espresso-core#94]
Here's a fun one.

We have a custom question - a dropdown field - which has a lot of options. We require it to have around 230 options (I'll be making this a select2 field on the front-end so people can actually use this thing).

However, we've input 197 options and we're now unable to add any more.

I have a suspicion it's akin to the WordPress menu manager problem where you can run into a url query limit if you have too many menu items. But I'm really struggling to track this down absolutely.

I've checked in `Registration_Form_Admin_Page::_insert_or_update_question()` to see what's going on, and if I dump the `$_POST` in there, after I add a new one (or add several) it simply doesn't appear in there. We have everything 'ordered' so each answer has a relevant `QSO_Order` value in the database (0-based, so the last one is 196).

When dumping the `$_POST`, here's a snipped version

```
[update_question_nonce] => c13a392d78
            [action] => update_question
            [QST_ID] => 21
            [QST_system] => 
            [QST_wp_user] => 1
            [QST_deleted] => 
            [QST_display_text] => Department
            [QST_admin_label] => Dept
            [QST_order] => 9
            [QST_type] => DROPDOWN
            [question_options] => Array
                (
                    [xxcountxx] => Array
                        (
                            [QSO_order] => 0
                            [QSO_value] => 
                            [QSO_desc] => 
                        )

                    [0] => Array
                        (
                            [QSO_value] => Access & Diversity
                            [QSO_desc] => 
                            [QST_ID] => 21
                            [QSO_ID] => 186
                        )

                        ...
                        ...

                       [196] => Array
                        (
                            [QSO_value] => School of Architecture & Landscape Architechure
                            [QSO_desc] => 
                            [QST_ID] => 21
                            [QSO_ID] => 382
                        )

                    [198] => Array
                        (
                            [QSO_order] => 198
                        )
                )

            [question_options_disabled] => Array
                (
                    [0] => Array
                        (
                            [QSO_order] => 
                        )

                    [1] => Array
                        (
                            [QSO_order] => 
                        )

                    ... etc

```

There's also a `[question_options_count] => 200` at the end (that number is because I tried to add a few but the same applies if I try to add one)

Any thoughts?

**Comment by nerrad** [comment]
I'm not absolutely certain either, but you *may* be hitting the php `max_input_vars` limit. (see http://php.net/manual/en/info.configuration.php#ini.max-input-vars)

**Comment by richardtape** [comment]
Confirmed: It is, as you suspected @nerrad , `max_input_vars` limit being hit. It was set to 1000 on our environments. Bumping it up allowed more to be saved.

Now the question is - for you folks - what would you like to do about it? Perhaps a warning if someone tries to save something and they hit the limit?

**Comment by nerrad** [comment]
Well we already do something like that on the events editor because we had customers commonly encountering that issue there.  However, its something we haven't encountered (up until you :) ) on the question editor.  If you want to take a look at what we did for the event editor you can and maybe do a pull request for the question editor.  It's unlikely to be something high on our priority list to implement here. 

Thanks for verifying that was the issue tho!
