### ISSUE TITLE
Improve datetime-related unit tests

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#940]
- [x] Improve `EEH_DTT_Helper_Test::test_date_time_subtract` to assert for within one minute instead of equal
> Occasionally tests run will result in this:

```
EEH_DTT_Helper_Test::test_date_time_subtract
The EEH_DTT_Helper::date_time_subtract() method failed to produce correct results for the the period interval PT0S for timezone "" and UTC offset "-5" .
Expected value: 2016-04-29 13:57:40
Actual value: 2016-04-29 13:57:41
```

> This would be a good spot to use the assert within one minute method.

- [x] Improve `EEM_Payment_Test::test_get_payments_between_dates`
> This test will fail if it is executed either:
> 
>     within one hour of 23.59:59 GMT
>     within two hours of 0:00:00 GMT 
> 
> This is because the unit test sets up Payment objects with relative times vs actual times.

- [x] Fix false fails for `EE_Datetime_Test::test_ticket_types_available_for_purchase` (see #1143)

> This was attempted once in Codebase 8971 but has resurfaced.  Test is marked as skipped until we can resolve this.

**Comment by nerrad** [comment]
`EEH_DTT_Helper_Test::test_date_time_subtract` already does do an assertion within one minute:

https://github.com/eventespresso/event-espresso-core/blob/master/tests/testcases/core/helpers/EEH_DTT_Helper_Test.php#L349

I wonder if it got fixed sometime before this issue was created?  If it pops up again, we'll need a link to the travis build where it failed.

**Comment by nerrad** [comment]
`EEM_Payment_Test::test_get_payments_between_dates` also looks like it was fixed at some point by specifying a "save" time for "now": 

https://github.com/eventespresso/event-espresso-core/blob/7790dcb1bcee17120c74d57c8ad46fdb817c2dcd/tests/testcases/core/db_models/EEM_Payment_Test.php#L102
