### ISSUE TITLE
add check for "/wp-content/themes/{current active WordPress theme}/espresso/" in EEH_Template::locate_template()

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#945]
plz see: http://p2.eventespresso.com/2016/05/04/template-load-order-in-eeh_templatelocate_template/#comment-15840

originally reported in https://events.codebasehq.com/projects/event-espresso/tickets/9705

**Comment by tn3rb** [comment]
plz see related issue in https://github.com/eventespresso/event-espresso-core/issues/860:

 - deprecate check for "content/uploads/espresso/templates/" in EEH_Template::locate_template()

**Comment by joshfeck** [comment]
This isn't something at gets requested.
