### ISSUE TITLE
move js in espresso_core.js into the `eejs` namespace

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#946]
Darren reported in codebase 10305:

> In efforts to incorporate best practices into our code and keep things cleaner, we want to make start making sure any js work we do in EE is within a namespace. We'll start with espresso_core.js but this will slowly over time be incorporated everywhere we use js as it gets refactored/replaced.

**Comment by nerrad** [comment]
@joshfeck on reviewing this issue, I'm not sure there's much value in converting `espresso_core.js` over to the new build system.  Much of the logic in this file would end up getting completely replaced by react components etc as we replace ui/ux using `espresso_core` so I think it might be wasted effort getting this into the build process.

I'm just going to close this.

**Comment by joshfeck** [comment]
👍
