### ISSUE TITLE
WP Users Integration and SQL

### ISSUE THREAD

**Issue by cstucker25** [eventespresso/event-espresso-core#96]
Has anyone come dealt with this scenario before? I have been working with your espresso 4 core plugin, multi registrations, WP users integration and I see some limitations. Here is what I am looking to do.

Scenario: I am looking to sell seminars that will allow for one person to register multiple people. I do see that the User Interface is great for this. I also want to capture the system questions and some additional questions. I do see that I can create the additional questions through the registration form, but I am not see those values in the SQL tables anywhere. Do you know where they are stored? I thought that they may be in the attendee_meta table, but they aren't there. Just the core system fields.

I have activated the WP User integration properly. I do realize that I will only be able to integrate the original user in the WP usersmeta table (hopefully all in the future), but only the system questions (first name, last name, email) are populated. I have researched the forums and haven't seen any information on this.

Any advice?

**Comment by joshfeck** [comment]
Hi there,

You will find the answer values that you are looking for in the _esp_answer table.

**Comment by cstucker25** [comment]
I see that table, but is there an _esp_answer_meta table?

**Comment by nerrad** [comment]
no there isn't an esp_answer_meta table.  I'm sorry but its not very clear what you are wanting to know (or why you're asking about an `answer_meta` table).

All answers to questions are recorded in the `esp_answer` which joins with the `esp_registration` table via `REG_ID` and with the `esp_question` table via `QST_ID` and records the answer value for that intersection.

Going by what you are saying here:

>  I do see that I can create the additional questions through the registration form, but I am not see those values in the SQL tables anywhere.

I think what you are referring to there is what is found in the `esp_question` table.  You'll see all the information about additional questions you created there.  But again, the actual *answers* to those questions are stored in `esp_answer`.

Regarding this paragraph here:

> I have activated the WP User integration properly. I do realize that I will only be able to integrate the original user in the WP usersmeta table (hopefully all in the future), but only the system questions (first name, last name, email) are populated. I have researched the forums and haven't seen any information on this.

I'm not clear what you are asking here?

**Comment by cstucker25** [comment]
Sorry, if I am confusing.  Basically, I am creating a bunch of products in Woocommerce. When someone purchases a product individually (course), they create an account (added to the WP tables (users_meta)).  I have some custom fields, such as DOB, etc...  that are captured in this users_meta table.  

I want to do something similar with Events, but I am having a hard time locating the actual user information.  I did create some custom fields, which are shown in the esp_question table (date-of-birth).  I do see that the attendee_meta table has all of the default values of the attendees, but not the new question (date-of-birth) that were created (dob,etc...).  

Ultimately, I am creating an integration that will retrieve user information from Woocommerce product purchases and Event Espresso purchases.  I have figured out how to grab the data for Woocommerce (wp users), but can't nail down how to grab EE user information.

esp_question table
![esp_question](https://cloud.githubusercontent.com/assets/13153725/8748615/b9ebd896-2c69-11e5-86ad-757695636daf.PNG)


users_meta table
![users_meta](https://cloud.githubusercontent.com/assets/13153725/8748545/3f3d5516-2c69-11e5-80d4-3adab41ca0f9.PNG)

attendee_meta table
![attendee_meta](https://cloud.githubusercontent.com/assets/13153725/8748550/44ecb3d0-2c69-11e5-96c5-627b75a62d4e.PNG)

**Comment by nerrad** [comment]
You've listed a screenshot of every table **except** the `esp_answer` table which I explained the relationships in my reply.  It answers your question about where the answers to your custom questions are stored.

The attendee table contains answers to system questions because it saves a join when retrieving that consistent data.  But *all* custom question answers is stored in the `esp_answer` table.

**Comment by tn3rb** [comment]
@cstucker25 
Only the system questions (the ones in esp_question table that have a value for QST_system) are recognized as being user properties. 

You are assuming that ALL custom questions should become part of the user meta but that simply is not the case with Event Espresso. Often custom questions are used to capture a registrant's preferences for a particular event, for example: Do you want the Steak or Chicken dinner? That is not relevant information that should become part of a user's  permanent profile.

So as has already been explained, the answers to all custom questions (ie: all non-system questions) can be found in the  esp_answer table.

If you are looking to integrate some specific custom questions into your user profiles, then I would look at the hook points found in the *EEM_Answer* class ( /core/db_models/EEM_Answer.model.php ). An example of how we do that can be found in the WP Users addon.

**Comment by tn3rb** [comment]
@cstucker25 
Do you have any other questions regarding this or can we close this issue?

**Comment by tn3rb** [comment]
closing due to no response
