### ISSUE TITLE
Prevent Fatal error: Uncaught TypeError: Argument 2 passed to EEH_Parse_Shortcodes::parse_ticket_list_template() must be an instance of EE_Ticket, null given, called in /event-espresso-core-reg/core/libraries/shortcodes/EE_Ticket_List_Shortcodes.lib.php on line 99 with cancelled registrations

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#971]
A few users have reported this but we couldn't really narrow down the problem, usually, the user had used the Attendee Mover to move a registration and they'd get this error when resending the registration emails or even on the Invoice:

```
Notice: Undefined index: ticket in /event-espresso-core-reg/core/libraries/shortcodes/EE_Ticket_List_Shortcodes.lib.php on line 97

Fatal error: Uncaught TypeError: Argument 2 passed to EEH_Parse_Shortcodes::parse_ticket_list_template() must be an instance of EE_Ticket, null given, called in /event-espresso-core-reg/core/libraries/shortcodes/EE_Ticket_List_Shortcodes.lib.php on line 99 and defined in /event-espresso-core-reg/core/helpers/EEH_Parse_Shortcodes.helper.php:97 
Stack trace: 
#0 /event-espresso-core-reg/core/libraries/shortcodes/EE_Ticket_List_Shortcodes.lib.php(99): EEH_Parse_Shortcodes->parse_ticket_list_template(Array, NULL, Array, Array) 
#1 /event-espresso-core-reg/core/libraries/shortcodes/EE_Ticket_List_Shortcodes.lib.php(61): EE_Ticket_List_Shortcodes->_get_ticket_list_for_main() 
#2 /event-espresso-core-reg/core/libraries/shortcodes/EE_Ticket_List_Shortcodes.lib.php(44): EE_Ticket_List_Shortcode in /event-espresso-core-reg/core/helpers/EEH_Parse_Shortcodes.helper.php on line 97
```

Turns out the problem is with cancelled registrations if you have a registration on that same event and use [TICKET_LIST] in some locations, for example in the main content of the Registration Approved template.

To reproduce create add `[TICKET_LIST]` (or `[RECIPIENT_TICKET_LIST]`) to the main content of the registration approved message template (registrant context).

Register onto a single event with more than 1 ticket type on a single datetime and register onto both (or more) tickets in a single group. E.g - https://monosnap.com/file/XxR9aINwnoEU91BHfapAPffh5ZV0Qw

Pay and then cancel just 1 registration within the admin.

Now resend the registration email on any of the registration except the one you just cancelled.

**Additional context**
Just to let know you know what I found, I've traced this back to the lines items here: https://github.com/eventespresso/event-espresso-core/blob/master/core/libraries/messages/data_class/EE_Messages_incoming_data.core.php#L422-L430

The reg_obj loop [HERE](https://github.com/eventespresso/event-espresso-core/blob/master/core/libraries/messages/data_class/EE_Messages_incoming_data.core.php#L337-L341) works correctly and has all of the registrations (including the cancelled one) but skips the cancelled registration when setting up `$tickets`

The line items code I linked to above pulls the line items for ALL of the tickets on that event, so when it loops over the cancelled ticket it adds another element to `$tickets` that contains just a `line_item` and `sub_line_itmes`.

**Comment by nerrad** [comment]
I was unable to reproduce this using the steps given but I think the area of code you highlighted is likely the culprit regardless so the pull I did addresses that.

On the surface it looks to me like this line: https://github.com/eventespresso/event-espresso-core/blob/master/core/libraries/messages/data_class/EE_Messages_incoming_data.core.php#L345

The above line would return nothing if the related ticket on that registration is _archived_ (which could be due to an attendee move, or because a price change on the ticket resulted in archived values).  But I tried setting up conditions to trigger that as well and was unsuccessful.

**Comment by Pebblo** [comment]
> On the surface it looks to me like this line: https://github.com/eventespresso/event-espresso-core/blob/master/core/libraries/messages/data_class/EE_Messages_incoming_data.core.php#L345
> 
> The above line would return nothing if the related ticket on that registration is _archived_

I tested this to confirm and it returns the ticket as expected:
https://monosnap.com/file/wVSeg0Agvz0UwJw5NxnVG8GwcbNPYz

That's a call to kint jut after that line to output the ticket, the REG ID is there for me to double check (all good).

Just noting here that I forgot to mention, for testing this I have messages set to send on the same request, otherwise you have to force the message to generate and sometimes it doesn't show the above error but another about it being on a different batch.... easier to just do it on the same request for this.

I also use a custom message template to test this just so I don't have to revert the change etc. I'm going to test it on defaults but with Darren not being able to reproduce just adding here.
