### ISSUE TITLE
WPML

### ISSUE THREAD

**Issue by Kenshino** [eventespresso/event-espresso-core#98]
Hello -

I made a plugin meant to integrate popular plugins with EE4. Currently it includes GravityForms and WordPress SEO by Yoast.

I have had a person ask if I could do the same with WPML. See https://wordpress.org/support/topic/wpml-integration-6?replies=2

I'd like to ask if you guys are working on it?

Cheers!

**Comment by nerrad** [comment]
Hi Kenshino,

No we aren't working on a wpml integration at this time (and no immediate plans to do so either).

**Comment by mnelson4** [comment]
Hey kenshiro have you considered putting your plugin on our list of third party addons? http://eventespresso.com/third-party-addons/
We receive requests for those integrations rather frequently and you could probably sell support and access to them

**Comment by Kenshino** [comment]
@nerrad: Thanks! I might work on WPML integration in my free time, but if we're lucky, one of my clients might request it and it'll get done immediately :dancer: 

@mnelson4: Not very concerned about selling support - but actually it seems like Seth (i think from your team) has already helped me add my plugin onto the list. See https://wordpress.org/support/topic/works-pretty-well-6?view=all#post-

Cheers!!

**Comment by mnelson4** [comment]
oh cool!
