### ISSUE TITLE
Beef up 'caching' of related object on model objects

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#980]
@mnelson4 proposed in [2862](https://events.codebasehq.com/projects/event-espresso/tickets/2862)

> Basically, we could add a "dirty" flag on model objects so we can know when we should or should not save.
> Basically, it might help avoid a few queries to the database. It could have also helped with issues like https://github.com/eventespresso/event-espresso-core/issues/306. But just how much it will help is unclear, and whether we could get away with it without needing to refactor the models is up-in-the-air. (The PHP files EEM_Base and EE_Base_Class are getting really big and we've been threatening to refactor them for a while). But I think this could be added onto existing files without requiring a big refactor.
> If we were to do this, I'd like to first try to do a quick-n-dirty version of it, then use a query monitor plugin or something to assess just how many queries it actually saves and how much quicker requests go. If there's no noticeable improvement I wouldn't be as eager to release the change (although it is always possible it would help more in high-load environments like EventSmart).

**Comment by tn3rb** [comment]
this has been added: https://github.com/eventespresso/event-espresso-core/commit/9c617e
