### ISSUE TITLE
Avoid Fatal error during Database Migration related to migrating the _events_attendee.checked_in column

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#983]
**Describe the bug**

This error is logged when doing the migration from EE3 to EE4 if unexpected data is in the `_events_attendee` table's `checked_in` column:
`PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in //wp-content/plugins/event-espresso-core/core/data_migration_scripts/4_1_0_stages/EE_DMS_4_1_0_checkins.dmsstage.php:73`

**To Reproduce**

**Expected behavior**

The invalid data could be worked around and the migration allowed to continue. Worse case scenario the check in data will no be accurate.
**Screenshots**

![screen shot 2019-02-26 at 11 08 50 am](https://user-images.githubusercontent.com/891156/53427592-386d5b00-39b7-11e9-9f74-fab5a1a39943.png)

![screen shot 2019-02-26 at 11 09 12 am](https://user-images.githubusercontent.com/891156/53427618-46bb7700-39b7-11e9-91bd-8d78e32fa6e9.png)

**Environment:**
 - Version of Event Espresso:   4.9.78
 - Version of WordPress:  5.1
 - PHP Version  7.1.25

**Comment by joshfeck** [comment]
Also found this to happen if no unexpected data is within the _events_attendee table's checked_in column. This was verified on a live site.

**Comment by mnelson4** [comment]
so it happens with or without unexpected data in `events_attendee.checked_in` table? Any idea how the unexpected data gets in there? (Maybe an older version of EE3 inserted it?)

**Comment by joshfeck** [comment]
Not exactly. If you had EE3 and used the app so there are check-ins & on PHP 7+, then there's a fatal error.
